src/reducer/resource/list/queryReducer.js

[RFR] Fix list filter reset

---

docs/Tutorial.md

People could get frustrated by trying out code that only works on master.

Recommend the matching version of the tutorial

---

src/index.js

[RFR] Fix fetchUtil export

---

README.md

You would probably run make build naturally if you are developing a
feature, but if you want to try out something someone else has
developed, chances are you will not think of it.

Add missing build command

---

docs/Custom-App.md

Because many of the early questions I got were about this...

[RFR] Document way to write custom apps

---

docs/Custom-App.md
src/mui/list/Datagrid.js

Also cleaned list components a bit to avoid react warnings in the console.
NOTE: WIP until we actually make custom app work

[RFR] Fix custom app documentation

---

package.json

[RFR] Remove double dependency to react-dom

---

docs/RestClients.md
docs/_layouts/default.html

[RFR] Move REST client documentation to the docs folder

---

docs/AdminResource.md
docs/_layouts/default.html

[RFR] Add admin and resource doc

---

src/CrudRoute.js
src/mui/detail/Create.js
src/mui/detail/RecordForm.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/ReferenceInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js
src/mui/input/TextInput.spec.js
src/mui/list/Filter.js
src/mui/list/Filter.spec.js
src/mui/list/FilterForm.js
src/mui/list/FilterForm.spec.js
src/mui/list/List.js
src/mui/list/List.spec.js
src/reducer/resource/list/queryReducer.js
src/reducer/resource/list/queryReducer.spec.js

[RFR] Fixing comments and filters

---

src/mui/detail/Create.js

[RFR] Fix create form

---

src/mui/layout/Notification.js
src/mui/list/Pagination.js

[RFR] Avoid render time binding

---

src/mui/field/ReferenceField.js

ReferenceField does not handle deep field properly #72

---

docs/RestClients.md
docs/Tutorial.md
example/package.json
src/rest/jsonServer.js
src/rest/simple.js
src/util/fetch.js

This changes the signature of the response in the restClient, so it's a BC break.
Fixes #79

[BC Break] [RFR] Pass Headers object to restClient

---

src/sideEffect/saga/crudFetch.js

[RFR] Fix spinner not stopping after delete

---

src/sideEffect/saga/referenceFetch.js

[RFR] Fix multiple ReferenceFields in a list incorrectly loads data

---

src/sideEffect/saga/referenceFetch.js

[RFR] Beautify reference fetch saga

---

docs/CustomApp.md

See https://github.com/marmelab/admin-on-rest/issues/111

Fix doc on reducers in CustomApp 

---

docs/CustomApp.md

[RFR] Fix custom app docs now that redux form is required

---

src/mui/input/RadioButtonGroupInput.js

[RFR] Fix RadioButtonGroupInput

---

docs/Theming.md

**NOTE:** You may want to add more detail to what I have here.  I went with details for a basic customization of colors via a new custom theme.

Theming Docs

---

docs/Theming.md
docs/_layouts/default.html
example/posts.js
src/mui/field/ChipField.js
src/mui/field/DateField.js
src/mui/field/EmailField.js
src/mui/field/ReferenceField.js
src/mui/field/RichTextField.js
src/mui/field/TextField.js
src/mui/field/UrlField.js
src/mui/input/DateInput.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js

Also, rewrite part of the Theming doc contributed in #107.

[RFR] Add style support to all Fields and Inputs

---

src/mui/list/List.js

[RFR] Fix clearing text filter doesn't fetch the unfiltered list

---

Makefile
README.md

[RFR] Add instructions to run the example app

---

docs/AdminResource.md
docs/CustomApp.md
example/app.js
example/posts.js
src/Admin.js
src/CrudRoute.js
src/Resource.js
src/mui/button/ShowButton.js
src/mui/button/index.js
src/mui/detail/Show.js
src/mui/detail/Show.spec.js
src/mui/detail/index.js
src/mui/index.js
src/mui/input/Labeled.js
src/mui/layout/index.js

[RFR] Add <Show> view

---

example/posts.js
src/mui/list/Datagrid.js

[RFR] Fix Warning when Datagrid contains two action buttons

---

src/rest/jsonServer.js
src/rest/simple.js

[RFR] Add warning in case of missing header

---

docs/Inputs.md
src/mui/input/ReferenceInput.js
src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js

[RFR] Add allowEmpty support on SelectInput

---

src/reducer/references/possibleValues.js

[RFR] Fix allowEmpty on ReferenceInput

---

src/mui/list/FilterForm.spec.js

[RFR] Fix test-watch command

---

src/actions/dataActions.js

[RFR] Fix inability after creation and update

---

src/actions/dataActions.js
src/reducer/resource/list/ids.js
src/sideEffect/saga/crudFetch.js
src/sideEffect/saga/success.js

[RFR] Fix list after delete

---

src/rest/jsonServer.js

Use httpHeader for GET_MANY

---

docs/Fields.md
docs/Theming.md
docs/_layouts/default.html

Nothing new in the code, just documentation. In fact, React has all that's needed to do conditional formatting!

[RFR] Document conditional formatting

---

src/mui/list/Pagination.js

[RFR] Fix pagination on large number of pages

---

src/rest/jsonServer.js

[RFR] Fix bad _end argument for jsonServer REST client

---

docs/RestClients.md
src/rest/jsonServer.js
src/rest/simple.js

[RFR] Explicit pagination and CORS headers even more

---

docs/AdminResource.md
docs/Theming.md
docs/_layouts/default.html

[RFR] Clarify custom layout documentation

---

src/mui/field/DateField.js
src/mui/field/DateField.spec.js
src/mui/field/NumberField.js
src/mui/field/NumberField.spec.js

[RFR] Fix <NumberField> and <DateField> when record has no value for the source

---

docs/Inputs.md
docs/_layouts/default.html
example/posts.js
src/mui/input/NumberInput.js
src/mui/input/NumberInput.spec.js
src/mui/input/TextInput.js
src/mui/input/index.js

[RFR] Add `<NumberInput>` component

---

Makefile
docs/Fields.md
package.json
src/mui/field/DateField.js
src/mui/field/DateField.spec.js
src/mui/field/NumberField.js
src/mui/field/NumberField.spec.js

[RFR] Date field format

---

src/mui/delete/Delete.js

[RFR] Improve Delete button labels

---

src/mui/button/CreateButton.js
src/mui/button/DeleteButton.js
src/mui/button/EditButton.js
src/mui/button/ListButton.js
src/mui/button/SaveButton.js
src/mui/button/ShowButton.js

[RFR] Add label prop to all buttons

---

src/mui/button/SaveButton.js
src/mui/form/SimpleForm.spec.js
src/reducer/index.js
src/reducer/saving.js

[RFR] Fix endless spinning save button upon error

---

example/comments.js
package.json
src/util/validate.js
src/util/validate.spec.js

[RFR] Fix validation on nested fields

---

docs/Fields.md
docs/RestClients.md
docs/Tutorial.md
example/package.json
example/posts.js
src/actions/dataActions.js
src/mui/field/ReferenceManyField.js
src/mui/field/ReferenceManyField.spec.js
src/reducer/references/oneToMany.js
src/rest/jsonServer.js
src/rest/simple.js

[RFR] Add perPage, sort and filter props to <ReferenceManyField>

---

docs/CreateEdit.md
docs/Fields.md
docs/Theming.md

These create errors in the rendered documentation

[RFR] Fix unescaped liquid tags in doc

---

docs/List.md
example/posts.js
src/mui/list/FilterButton.js
src/mui/list/FilterForm.js
src/mui/list/List.js

Add support for `defaultValue` for `Input` components inside a `<Filter>`.
Refs #192

[RFR] Filter default value

---

docs/CreateEdit.md
example/posts.js
package.json
src/CrudRoute.js
src/mui/detail/Create.js
src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js
src/mui/form/getDefaultValues.js

Allow `defaultValue` to be a function for form and input components.
Use case:
```js
export const PostCreate = (props) => (
<Create {...props}>
<SimpleForm>
<DisabledInput source="id" defaultValue={() => uuid()}/>
...
</SimpleForm>
</Create>
);
```
Closes #274

[RFR] Default value function

---

src/mui/layout/Layout.js

Rely material-ui to auto-prefix flex-box elements.

Prefix flex-box elements

---

docs/AdminResource.md
src/mui/defaultTheme.js
src/mui/index.js
src/mui/layout/index.js
src/mui/list/Datagrid.js

Use theme colors in datagrid.
Before: 
After:

[RFR] Themable Datagrid

---

docs/AdminResource.md
src/mui/layout/Menu.js
src/mui/layout/Title.js

[RFR] Fix custom title in view and custom label in resource

---

src/mui/form/FormTab.js
src/mui/form/SimpleForm.js

Right now, fields can't be skipped on the fly. This PR add the ability to hide this fields.

[RFR] Add ability to hide fields

---

docs/Translation.md

I added a chinese translation link.*^_^*

chinese translation link

---

src/CrudRoute.js

[RFR] Simplify custom app setup

---

src/mui/input/SelectInput.js

[RFR] Fix SelectInput arrow click hides input

---

docs/CustomApp.md
src/CrudRoute.js
src/mui/layout/Menu.js

[RFR] Update custom app documentation

---

src/i18n/TranslationUtils.js

We are currently working on an admin panel with only French and German users. We need to fallback on French, not English. This PR allows to specify which locale should be the default.

[RFR] Allow to specify default locale

---

src/actions/dataActions.js
src/mui/detail/Edit.js
src/mui/detail/Show.spec.js

Allows translation to `PATCH` HTTP verb
Closes #338

[RFR] Pass old record in CRUD_UPDATE action payload

---

docs/Tutorial.md

LOGIN_CHECK is not imported in your example

One forgot in the tutorial (LOGIN_CHECK)

---

docs/Translation.md

Russian translation link added.

russian translation link

---

src/i18n/messages.js
src/sideEffect/saga/crudResponse.js

[RFR] Show notification for server error even when the response body is empty

---

docs/AdminResource.md
src/Admin.js
src/mui/auth/Logout.js
src/mui/layout/Layout.js
src/mui/layout/Menu.js

[RFR] Allow to customize menu without overriding the layout

---

docs/RestClients.md

Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>

[RFR] Add link aor-feathers-client in doc

---

src/mui/form/getDefaultValues.js
src/mui/form/getDefaultValues.spec.js

fix incorrect defaultValue assignment for nested resource attributes in SimpleForm

---

docs/Translation.md

Hey! Thank you guys for this amazing framework, I have added a package for Spanish translations in the documentation.

Added Spanish translations package

---

src/mui/auth/Login.js

Hi there,
Small PR to improve the UX on the default Login page.
This include Fields locking and loader on submit Button.
Preview
By the way, great framework ! 👍

Login page: improve UX with form lock and loader

---

docs/Translation.md

I just do the translation for Vietnamese. Please check and accept.

Add Vietnamese language

---

docs/RestClients.md

I just create new REST client that works correctly with Loopback-backend API.

Add Loopback-like REST client

---

src/sideEffect/saga/crudResponse.js

[RFR] Fix redirection after creation

---

docs/AdminResource.md
src/Admin.js

Lets me save some things in local storage. E.g. user profile

Pass initial state to create store

---

src/mui/input/ImageInput.js
src/mui/input/ImageInput.spec.js

[RFR] Fix image input previews on drop

---

docs/Translation.md

I have added the Hungarian translations link. Please, check and accept.

Add mention of Hungarian translations

---

src/mui/list/Pagination.js
src/mui/list/Pagination.spec.js

[RFR] Fix pagination on mobile

---

src/mui/list/FilterForm.js

[RFR] Fix list layout breaking when there are more than 3 filters

---

src/sideEffect/saga/crudFetch.js

Should make debugging REST clients easier

[RFR] Throw error when REST response does not contain the error key

---

docs/Fields.md
docs/Inputs.md
docs/_layouts/default.html
example/data.js
example/posts.js
src/mui/field/ReferenceField.js
src/mui/field/SelectField.js
src/mui/field/SelectField.spec.js
src/mui/field/index.js
src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js
src/mui/input/CheckboxGroupInput.js
src/mui/input/CheckboxGroupInput.spec.js
src/mui/input/NullableBooleanInput.js
src/mui/input/NullableBooleanInput.spec.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/RadioButtonGroupInput.spec.js
src/mui/input/ReferenceInput.js
src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js

[RFR] Add Select field, translate options

---

docs/Authentication.md
docs/RestClients.md

Fix Custom HTTP Client documentation

---

docs/Authentication.md

Fix typo in Authentication.md

---

src/sideEffect/saga/auth.js

[RFR] Hide notification before redirecting to login

---

src/mui/detail/Edit.js

[RFR] Fix edit refresh, take 2

---

docs/List.md

Fix documentation about custom List actions

---

docs/AdminResource.md

[RFR] Fix Custom dashboard documentation

---

docs/Fields.md

[RFR] Add warning about <Resource> required for ReferenceManyField usage

---

docs/Inputs.md

Changes to be committed:
modified:   docs/Inputs.md

add `parse()` and `format()` usage

---

docs/Inputs.md

add link for `<ImageInput>`

---

src/mui/form/TabbedForm.js

[RFR] Fix translation warning on tab names

---

docs/Translation.md

This is a proposal for the Dutch translation. Please check/accept.
Thanks!

Add Dutch language

---

docs/Translation.md

Added a link to the Czech language file.

added Czech Language file

---

docs/Translation.md

I found Japanese translation so I would like to link it

Add Japanese language

---

docs/List.md
src/mui/list/DatagridHeaderCell.js

[RFR] Fix ability to disable sort for a field

---

src/mui/auth/Logout.js

Hello team :)
This pull request resolve #587

[RFR] connect theme logout button

---

docs/Inputs.md

[RFR] Mention obligation to declare a resource for ReferenceInput

---

src/mui/input/CheckboxGroupInput.js
src/mui/input/CheckboxGroupInput.spec.js

[RFR] Fix CheckboxGroupInput on IE

---

src/mui/list/List.js

[RFR] Fix filters on refresh

---

src/mui/input/NumberInput.js

[RFR] Ensure numberinput never send null

---

src/mui/detail/Edit.js
src/mui/detail/Show.js

[RFR] Ensure Edit updates when fields change

---

src/mui/layout/Sidebar.js

Fixes #634
Supercedes #638
Applying custom width:
```js
const theme = {
...defaultTheme,
drawer: { width: '24em' },
}
```

[RFR] Make sidebar themable

---

src/mui/list/FilterForm.js

[RFR] Fix FilterForm typo

---

src/mui/field/ReferenceField.js
src/mui/field/ReferenceField.spec.js

[RFR] Fix ReferenceField should not fetch null values

---

src/mui/list/List.js
src/util/removeKey.js
src/util/removeKey.spec.js

[RFR] Clean filters when using deep paths

---

src/reducer/resource/list/ids.js

[RFR] Fix list optimistic rendering

---

CHANGELOG.md
src/reducer/resource/list/ids.js

Reverts marmelab/admin-on-rest#659 as its creates problems.
Steps to reproduce: 
1. Go to the post list
2. Go to the comments list
3. click the "next" link in pagination
4. Come back to post list
The console gets filled with errors.
@djhi you'll have to take another guess at fixing the related problem.

Revert "[RFR] Fix list optimistic rendering"

---

src/mui/form/FormField.js
src/mui/input/AutocompleteInput.js
src/mui/input/BooleanInput.js
src/mui/input/CheckboxGroupInput.js
src/mui/input/DateInput.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/NumberInput.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/SelectArrayInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js
src/util/FieldTitle.js
src/util/FieldTitle.spec.js

[RFR] Show asterisk for required TextInput

---

docs/Ecosystem.md

And add link to the translation page.
Fixes #677

[RFR] Remove translations list from Ecosystem

---

docs/Actions.md
package.json
src/Admin.js
src/sideEffect/saga/auth.js
src/sideEffect/saga/crudFetch.js
src/sideEffect/saga/crudResponse.js
src/sideEffect/saga/crudSaga.js

`yield [...effects]` is deprecated, use `yield all([...effects])`

[WIP] added all([...effects]) to yield [...effects] and updated redux-saga to 0.15.3

---

src/mui/input/SelectInput.js

[RFR] Support null and false value in SelectInput options.

---

example/data.js
src/mui/field/ReferenceArrayField.js

if backend is not kind enough to provide empty array

ReferenceArrayField fix when ids is null

---

src/mui/input/DisabledInput.js

DisabledInput takes value from redux-form

---

example/app.js
src/Admin.js

Closes #298
Can't add doc for it because of documentation overhaul in master (would imply a big rebase). Will add it once `master` is merged into `next`.

[RFR] Allow to use custom history in admin

---

src/mui/field/ReferenceManyField.js

Add sort feature to ReferenceManyField

---

src/mui/field/ReferenceManyField.js

fix delayed sorting

---

src/mui/list/FilterButton.js

Just remove the duplicated prop `resource` on FilterButton.js

Fix duplicate propType `resource`

---

docs/Translation.md

Add Thai Translations.

---

src/mui/detail/Show.js
src/mui/detail/TabbedShowLayout.js
src/mui/form/TabbedForm.js

Related to #749
Fix complete with #781

[RFR] Show now passes translate to its children

---

src/mui/detail/Show.js
src/mui/detail/ShowActions.js

Related to #749
Fix complete with #780

[RFR] Show has a refresh action like Edit

---

src/actions/accumulateActions.js
src/actions/authActions.js
src/actions/dataActions.js
src/actions/fetchActions.js
src/actions/filterActions.js
src/actions/listActions.js
src/actions/localeActions.js
src/actions/notificationActions.js
src/actions/uiActions.js

replace and complete: https://github.com/marmelab/admin-on-rest/pull/547

[RFR] prefix aor actions with `AOR/`

---

docs/Admin.md
src/mui/layout/AppBarMobile.js
src/mui/layout/Menu.js
src/mui/layout/MenuItemLink.js
src/mui/layout/index.js

Fixes #642
BreakingChange: Use `MenuItemLink` instead of `MenuItem` with `Link`

[RFR] Fix mobile menu unwanted effects

---

docs/Tutorial.md

react-create-app should be create-react-app

Fix a typo in tutorial

---

src/mui/input/ReferenceInput.js
src/mui/input/ReferenceInput.spec.js

[RFR] Fix ReferenceInput filter

---

docs/RestClients.md

[RFR] Reformat custom REST client list for better readability

---

README.md

JSX highlighting on README.md

---

docs/Fields.md

Documented code seems to be a bit bugged

Fixes documentation on ReferenceArrayList

---

docs/Fields.md

Add Doc about the addLabel prop for ReferenceField

---

docs/Actions.md

[RFR] Fix custom saga documentation

---

src/mui/field/ReferenceArrayField.js

[RFR] Fix ReferenceArrayField used with Datagrid child

---

docs/Tutorial.md

Fixed Tutorial.md typo

---

docs/Inputs.md
docs/_layouts/default.html

original code contains error
Changes to be committed:
modified:   docs/Inputs.md
modified:   docs/_layouts/default.html

fix doc for ISO date input

---

docs/Admin.md

[RFR] Document admin history prop

---

docs/Inputs.md
src/mui/input/NumberInput.js

[RFR] Allow numeric value in NumberInput step prop

---

docs/Translation.md

PropTypes.function is undefined, the field is called PropTypes.func: https://www.npmjs.com/package/prop-types .

Fix PropTypes field typo

---

src/mui/input/SelectInput.js

[RFR] Fix SelectInput Bidirectional binding

---

src/mui/list/Pagination.js
src/mui/list/Pagination.spec.js

[RFR] Use colors from MUI theme for pagination chevrons

---

src/mui/form/validate.js
src/mui/form/validate.spec.js

[RFR] Fix numeric validators

---

src/mui/input/FileInput.js
src/mui/input/FileInput.spec.js

[RFR] Fix FileInput handling when allowing only a single file

---

docs/RestClients.md

An Epilogue Client for admin-on-rest

Add Epilogue Client

---

docs/RestClients.md
src/actions/dataActions.js
src/mui/delete/Delete.js

Also updated RestClient docs
Closes #968

Add `previousData` to `crudDelete` payload

---

docs/Admin.md
docs/Authentication.md
docs/CreateEdit.md
docs/CustomApp.md
docs/FAQ.md
docs/Fields.md
docs/Inputs.md
docs/List.md
docs/Resource.md
docs/Show.md
docs/Theming.md
docs/index.md

Hopefully did not miss any.
Consider this my first contribution until I ramp up on admin on rest & react (but for this I need the documentation) :)

fix internal links

---

src/util/removeEmpty.js
src/util/removeEmpty.spec.js

[RFR] Fix date filters

---

src/mui/list/Actions.js
src/mui/list/List.js

[RFR] Fix breaking change: List refresh

---

src/mui/input/BooleanInput.js
src/mui/input/BooleanInput.spec.js

[RFR] Fix BooleanInput onChange with false value

---

src/mui/list/Filter.spec.js
src/mui/list/FilterForm.js
src/mui/list/FilterForm.spec.js

[RFR] Fix alwaysOn filters defaultValue being ignored

---

src/reducer/admin/record.js
src/reducer/admin/record.spec.js

[RFR] Fix default values handling for deep paths with dot notation

---

Makefile

Add clean and install steps before building

---

src/reducer/admin/resource/list/ids.js

[RFR] Fix delete reducer on IE11

---

src/mui/button/CreateButton.js

Fix missing ' in CreateButton for onlyUpdateForKeys

---

src/mui/input/RadioButtonGroupInput.js
src/mui/input/RadioButtonGroupInput.spec.js

According to https://github.com/callemall/material-ui/issues/297

Add valueSelected so RadioButtonGroup will update its value

---

docs/CustomApp.md

[RFC] corrected example #1078

---

src/auth/Restricted.js

[RFC] fix #1080

---

src/mui/input/FileInput.spec.js
src/mui/input/FileInputPreview.js
src/mui/input/FileInputPreview.spec.js
src/mui/input/ImageInput.spec.js

[RFR] Make the FileInputPreview themable

---

src/mui/list/Filter.js
src/mui/list/Filter.spec.js
src/mui/list/FilterForm.js

[RFR] Make the FilterForm themable

---

src/mui/delete/Delete.js

sometimes there is need to redirect to some other location after delete

[RFR] Add redirect prop to Delete

---

src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js

Please see #1046 for issue description
supersede #1048

[RFR] Allow bound search text value to change

---

src/mui/detail/Create.js
src/mui/detail/CreateActions.js
src/mui/detail/Edit.js
src/mui/detail/EditActions.js
src/mui/detail/Show.js
src/mui/detail/ShowActions.js

[RFR] Hide list button when no list

---

docs/Admin.md
docs/Authorization.md

[RFR] Fix documentation about onTouchTap vs onClick

---

package.json
src/reducer/admin/resource/data.js
src/reducer/admin/resource/data.spec.js
src/reducer/admin/resource/list/ids.js
src/reducer/admin/resource/list/ids.spec.js
src/util/getFetchedAt.js
src/util/getFetchedAt.spec.js

[RFR] Fix optimistic list

---

src/mui/list/List.js
src/mui/list/List.spec.js

[RFR] Fix link trailing slash

---

src/mui/field/ReferenceManyField.js
src/reducer/admin/references/oneToMany.js
src/reducer/admin/references/oneToMany.spec.js

[RFR] incorporate filter in relation name

---

docs/Fields.md
src/mui/field/FileField.js
src/mui/field/FileField.spec.js

sometimes you really need to open the attachments in new window

[RFR] [Feature] add target to FileField

---

docs/CustomApp.md

- Sorry about that. Now I think it's ok.

[WIP] Fix doc adminReducer customApp

---

docs/List.md
src/mui/list/SimpleList.js

to choose where to redirect on click
resolves #926

[RFR] [Feature] SimpleList redirect prop

---

docs/Theming.md

[RFR] Fix custom layout doc

---

docs/Authorization.md
src/auth/WithPermission.js

[RFR] Remove FormField from WithPermission

---

src/i18n/messages.js
src/sideEffect/saga/crudResponse.js

[RFR] Bad element error

---

src/mui/list/List.js

Bind List.refresh to class

---

src/mui/detail/Edit.js
src/mui/detail/Show.js
src/mui/detail/SimpleShowLayout.js
src/mui/detail/TabbedShowLayout.js
src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js

The Refresh button didn't force refetch of related records (e.g. in `<ReferenceManyField>`).
Closes #1131

[RFR] Fix Refresh in Edit and Show views

---

docs/List.md

fix List.md documentation

---

docs/Theming.md
src/actions/notificationActions.js
src/mui/layout/Notification.js
src/reducer/admin/notification.js
src/reducer/admin/notification.spec.js

resolves #911
the autoHideDuration can be set globally: `<Notification autoHideDuration={5000} />`
or even different for every message: `showNotification('you_fail', 'warning', 30000)`

[RFR] [Feature] can set autoHideDuration for Notification's

---

package.json
packages/react-admin/src/i18n/TranslationUtils.js
packages/react-admin/src/mui/field/SelectField.js
packages/react-admin/src/mui/form/TabbedForm.js
packages/react-admin/src/mui/input/CheckboxGroupInput.js
packages/react-admin/src/mui/input/Labeled.js
packages/react-admin/src/mui/input/RadioButtonGroupInput.js
packages/react-admin/src/mui/input/ReferenceArrayInput.js
packages/react-admin/src/mui/input/ReferenceInput.js
packages/react-admin/src/mui/input/SelectInput.js
packages/react-admin/src/mui/layout/Layout.js
packages/react-admin/src/mui/list/Datagrid.js
packages/react-admin/src/mui/list/DatagridBody.js
packages/react-admin/src/mui/list/DatagridHeaderCell.js
packages/react-admin/src/mui/withChildrenAsFunction.js
packages/react-admin/src/util/FieldTitle.js
yarn.lock

[RFR] Upgrade to prettier 1.7

---

docs/Translation.md

Hi guys,
I've added a more recent translation of AOR & published a NPM package for it (the previous repo didn't have one).

Adding a link to the updated Hebrew translations.

---

docs/Admin.md

[RFR] Fix custom Menu documentation

---

docs/Actions.md

for fix example export function error

for fix example export function error

---

packages/ra-example/app.js
packages/react-admin/src/mui/button/CreateButton.js
packages/react-admin/src/mui/button/DeleteButton.js
packages/react-admin/src/mui/button/EditButton.js
packages/react-admin/src/mui/button/ListButton.js
packages/react-admin/src/mui/button/ShowButton.js
packages/react-admin/src/mui/layout/DashboardMenuItem.js
packages/react-admin/src/mui/layout/MenuItemLink.js

[RFR] Fixes for MUI 1.0

---

packages/react-admin/src/mui/button/DeleteButton.js
packages/react-admin/src/mui/button/EditButton.js
packages/react-admin/src/mui/button/ListButton.js
packages/react-admin/src/mui/button/ShowButton.js
packages/react-admin/src/mui/layout/MenuItemLink.js

[RFR] Fixes for navigation and buttons

---

packages/react-admin/src/mui/button/CreateButton.js
packages/react-admin/src/mui/button/EditButton.js
packages/react-admin/src/mui/button/RefreshButton.js
packages/react-admin/src/mui/button/SaveButton.js
packages/react-admin/src/mui/button/ShowButton.js
packages/react-admin/src/util/FieldTitle.js

PR fixed issue that field titles aren't updated on locale change, as shown below:

Bugfix: Fieldtitle does not update on locale change

---

docs/CreateEdit.md
packages/ra-example/posts.js

Introduced by #1265 which is necessary.
Updated documentation accordingly.

[RFR] Fix validation bug in tests

---

packages/react-admin/src/mui/list/List.js

[RFR] Fix default List page parameter

---

docs/Admin.md
src/index.js

[RFR] Export getResources to allow ressource injection in custom components

---

docs/Translation.md

[RFR] Fix translation doc

---

packages/react-admin/src/AdminRoutes.js
packages/react-admin/src/reducer/admin/auth.js
packages/react-admin/src/reducer/admin/index.js
packages/react-admin/src/reducer/index.js

See #1295
An additional but not required step would be to store whatever the `authClient` returns on login in the store too

[RFR] Ensure permissions are reset after logout

---

UPGRADE.md
packages/ra-data-fakerest/package.json
packages/ra-data-fakerest/src/index.js

[RFR] Upgrade guide about addons renaming

---

docs/DataProviders.md
docs/_layouts/default.html
packages/ra-data-fakerest/README.md

[RFR] Rewrite data provider documentation

---

Makefile

[RFR] Fix mocha compilers deprecation warning

---

Makefile

See Jest [documentation](https://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server)

[RFR] Apply recommandations for running Jest on Travis

---

docs/Inputs.md

Changed Spelling of Labeled

---

src/mui/button/SaveButton.js

Same as #862 and #567, for SaveButton.

Fix missing key warning

---

docs/RestClients.md

wasted ALOT of time on this :(

Fix RestClient example

---

packages/react-admin/src/mui/layout/AppBarMobile.js

[RFR] Fix titles on small devices

---

packages/react-admin/src/mui/form/SimpleForm.js
packages/react-admin/src/mui/form/TabbedForm.js

[RFR] Ensure whole form is accessible on small devices

---

packages/react-admin/src/mui/button/Button.js
packages/react-admin/src/mui/button/CreateButton.js
packages/react-admin/src/mui/button/DeleteButton.js
packages/react-admin/src/mui/button/EditButton.js
packages/react-admin/src/mui/button/ListButton.js
packages/react-admin/src/mui/button/RefreshButton.js
packages/react-admin/src/mui/button/ShowButton.js
packages/react-admin/src/mui/button/index.js
packages/react-admin/src/mui/list/FilterButton.js

[RFR] Make all buttons responsive

---

docs/Fields.md
e2e/chromeDriver.js
packages/react-admin/src/actions/dataActions.js
packages/react-admin/src/mui/field/ReferenceManyField.js
packages/react-admin/src/mui/field/ReferenceManyField.spec.js

[RFR] Allow to specify source in ReferenceManyField

---

packages/react-admin/src/mui/list/List.js

When you want to browse to a list using the browser url with query params, you get an error as shown below, this PR fixes this.

[Fix/RFR]: Limit valid query params and make sure filter is initialized.

---

packages/react-admin/src/mui/auth/Login.js
packages/react-admin/src/mui/auth/LoginForm.js
packages/react-admin/src/mui/auth/index.js
packages/react-admin/src/mui/index.js
packages/react-admin/src/sideEffect/saga/auth.js

Because of passing down the additional props to the outer div of the LoginPage there were alot of console errors, because all redux-form props weren't sanitized. Normally redux-form should be wrapped around a Form, so I externalized the Form.

[RFR]: Login page bugfix

---

docs/_layouts/default.html
docs/css/style.css
docs/img/menu.svg
docs/js/menu.js

[RFR] Backport fixes for doc on mobile

---

docs/css/style.css

[RFR] Add shadow under doc menu bar on mobile

---

docs/Reference.md
docs/Theming.md
packages/react-admin/src/mui/layout/index.js

I think this component should be exported.

[RFR]: Export component Loading

---

examples/simple/package.json
packages/react-admin/package.json
packages/react-admin/src/mui/button/SaveButton.spec.js
packages/react-admin/src/mui/field/ReferenceArrayField.spec.js
packages/react-admin/src/mui/field/ReferenceField.spec.js
packages/react-admin/src/mui/field/ReferenceManyField.spec.js
packages/react-admin/src/mui/form/SimpleForm.js
packages/react-admin/src/mui/form/SimpleForm.spec.js
packages/react-admin/src/mui/form/TabbedForm.js
packages/react-admin/src/mui/form/TabbedForm.spec.js
packages/react-admin/src/mui/input/BooleanInput.spec.js
packages/react-admin/src/mui/input/CheckboxGroupInput.spec.js
packages/react-admin/src/mui/input/DateInput.spec.js
packages/react-admin/src/mui/input/FileInput.spec.js
packages/react-admin/src/mui/input/FileInputPreview.spec.js
packages/react-admin/src/mui/input/ImageInput.spec.js
packages/react-admin/src/mui/input/NullableBooleanInput.spec.js
packages/react-admin/src/mui/input/RadioButtonGroupInput.spec.js
packages/react-admin/src/mui/input/SelectInput.spec.js
packages/react-admin/src/mui/layout/Layout.js
packages/react-admin/src/mui/layout/Loading.js
packages/react-admin/src/mui/layout/NotFound.js
packages/react-admin/src/mui/list/DatagridCell.spec.js
packages/react-admin/src/mui/list/DatagridHeaderCell.spec.js
packages/react-admin/src/mui/list/Filter.spec.js
packages/react-admin/src/mui/list/List.spec.js
packages/react-admin/src/mui/list/Pagination.spec.js
yarn.lock

Breakpoints are now inclusive again

[RFR] Update to MUI 1.0.0-beta.27

---

docs/Authentication.md
packages/react-admin/src/actions/authActions.js
packages/react-admin/src/mui/auth/Logout.js
packages/react-admin/src/sideEffect/saga/auth.js

Currently logout always redirects to `/login`, this PR allows to redirect to another page. 
Usage: 
```
<Admin 
logout={()=><Logout redirectTo="/"/>}..
```

Allow logout redirect

---

package.json

[RFR] Upgrade material-ui-chip-input

---

src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js

[RFR] Fix Bottom Toolbars on mobile

---

src/mui/input/BooleanInput.js
src/mui/input/BooleanInput.spec.js

[RFR] Fix BooleanInput warning about uncontrolled to controlled component

---

packages/react-admin/src/mui/input/CheckboxGroupInput.js

[RFR] Fix display of CheckboxGroupInput

---

docs/Authentication.md

[RFR] change extraction of status for AUTH_ERROR

---

examples/demo/package.json
examples/demo/src/App.js
examples/demo/src/dashboard/NewCustomers.js
examples/demo/src/dashboard/PendingOrders.js
examples/demo/src/dashboard/PendingReviews.js
examples/simple/package.json
examples/tutorial/package.json
packages/react-admin/package.json
packages/react-admin/src/mui/button/DeleteButton.js
packages/react-admin/src/mui/layout/AppBar.js
packages/react-admin/src/mui/layout/AppBarMobile.js
yarn.lock

Changes: https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.30
Also updated demo to use the new i18nProvider

[RFR] Upgrade to mui beta 30

---

docs/CreateEdit.md

this doesn't look like valid code and doesn't use the values parameter sent in, which I think was the point of the example.

Example fix

---

examples/graphcool-demo/src/products/GridList.js
examples/graphql-demo/src/products/GridList.js

A missing upgrade after upgrading to mui beta 29

[RFR] Fix gql examples, products

---

Makefile
examples/data-generator/package.json
examples/data-generator/src/categories.js
examples/data-generator/src/commands.js
examples/data-generator/src/customers.js
examples/data-generator/src/finalize.js
examples/data-generator/src/index.js
examples/data-generator/src/products.js
examples/data-generator/src/randomDate.js
examples/data-generator/src/reviews.js
examples/demo/package.json
examples/demo/src/restServer.js
yarn.lock

I can't use the generator in the `graphql-demo` yet as some changes on the `json-graphql-server` are needed. I'll work on it in a separate PR once those changes are merged.
https://github.com/marmelab/json-graphql-server/pull/41

[RFR] Data generator for examples

---

src/mui/input/SelectArrayInput.js

Fixes #1359
I confirm it now work on both react 15 and 16

[RFR] Fix SelectArrayInput

---

README.md
docs/Admin.md
docs/Tutorial.md
docs/index.md
example/comments.js
example/i18n/index.js
example/posts.js
example/users.js

[RFR] Use standard es6 in docs and example

---

src/mui/form/validate.js

[RFR] Ensure validation custom messages without translation don't add warnings

---

src/i18n/translate.js
src/mui/input/NullableBooleanInput.spec.js

Fix #1261
I tracked down the issue to recompose getContext function.

[RFR] Fix warnings in React 16

---

docs/Authorization.md
docs/CreateEdit.md
docs/FAQ.md
example/comments.js
example/posts.js
example/users.js
src/auth/withPermissionsFilteredChildren.js
src/mui/list/List.js

[RFR] Fix WithPermissionsFilteredChildren should not put regular children in state

---

src/mui/form/FormField.js
src/mui/form/FormField.spec.js

[RFR] Fix form default values can't be changed once mounted

---

docs/Inputs.md

Fix #1183  
Add explanation about dateInput and timezone in documentation, with a parser exemple to solve the problem if it exists.

[RFR] Add explanation about dateInput and timezone

---

src/mui/field/ReferenceField.js
src/mui/field/ReferenceField.spec.js

[RFR] Fix link color in reference field

---

src/mui/list/FilterForm.js
src/mui/list/FilterForm.spec.js

[RFR] Fix default value for filter when source is a path with dot

---

e2e/pages/CustomPage.js
e2e/tests/customPages.js
example/app.js
example/customRouteLayout.js
example/customRouteNoLayout.js
src/Admin.js
src/AdminRoutes.js
src/AdminRoutes.spec.js
src/mui/layout/Layout.js

[RFR] Refactor resources handling

---

packages/ra-language-french/index.js

[RFR] Add missing french translation keys

---

docs/RestClients.md
example/addUploadFeature.js

[RFR] Update documentation about addUploadCapabilities

---

docs/CreateEdit.md
docs/List.md
docs/Show.md
example/posts.js

[RFR] Update documentation about new RefreshButton syntax

---

src/mui/input/SelectArrayInput.js

hopefully it will not break the fix by much

fix setState typo in #1427

---

Makefile

[RFR] Fix ra-realtime package build

---

UPGRADE.md
docs/Authorization.md
docs/CreateEdit.md
docs/CustomApp.md
examples/demo/package.json
examples/demo/src/Login.js
examples/demo/src/configuration/Configuration.js
examples/graphcool-demo/package.json
examples/graphcool-demo/src/Login.js
examples/graphcool-demo/src/configuration/Configuration.js
examples/simple/comments.js
examples/simple/package.json
examples/simple/posts.js
examples/simple/users.js
examples/tutorial/package.json
packages/react-admin/package.json
packages/react-admin/src/mui/auth/LoginForm.js
packages/react-admin/src/mui/button/CreateButton.js
packages/react-admin/src/mui/button/SaveButton.js
packages/react-admin/src/mui/delete/Delete.js
packages/react-admin/src/mui/form/Toolbar.js
packages/react-admin/src/mui/layout/AppBar.js
packages/react-admin/src/mui/layout/AppBarMobile.js
packages/react-admin/src/mui/layout/NotFound.js
packages/react-admin/src/mui/layout/Sidebar.js
packages/react-admin/src/mui/layout/ViewTitle.js
packages/react-admin/src/mui/list/List.js
packages/react-admin/src/mui/list/Pagination.js
yarn.lock

The latest 2 versions of material-ui introduce BC breaks:
* https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.32
* https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.31

[RFR] Upgrade material-ui to v1.0.0-beta.32

---

docs/Admin.md
examples/demo/src/Menu.js
examples/graphcool-demo/src/Menu.js
packages/react-admin/src/mui/layout/DashboardMenuItem.js
packages/react-admin/src/mui/layout/MenuItemLink.js

[RFR] Use React Router NavLink in menu

---

UPGRADE.md
docs/Admin.md
docs/Authentication.md
docs/Authorization.md
examples/demo/src/Menu.js
examples/graphcool-demo/src/Menu.js
packages/react-admin/src/mui/layout/DashboardMenuItem.js
packages/react-admin/src/mui/layout/Menu.js
packages/react-admin/src/mui/layout/MenuItemLink.js
packages/react-admin/src/mui/layout/Sidebar.js

[RFR] Rename `onMenuTap` to `onMenuClick` 

---

packages/react-admin/src/mui/layout/Layout.js

[RFR] Fix layout isn't scrollable

---

docs/Theming.md

[RFR] Fix custom layout documentation

---

docs/RestClients.md

Add DynamoDb to RestClients.md

---

packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/react-admin/src/mui/button/SaveButton.js
packages/react-admin/src/mui/button/SaveButton.spec.js
packages/react-admin/src/mui/form/SimpleForm.js
packages/react-admin/src/mui/form/TabbedForm.js
packages/react-admin/src/mui/form/Toolbar.js

[RFR] Display error message when the form doesn't validate

---

UPGRADE.md
docs/Admin.md
docs/Theming.md
e2e/tests/permissions.js
packages/react-admin/src/mui/auth/Logout.js
packages/react-admin/src/mui/layout/AppBar.js
packages/react-admin/src/mui/layout/AppBarMobile.js
packages/react-admin/src/mui/layout/Layout.js
packages/react-admin/src/mui/layout/LoadingIndicator.js
packages/react-admin/src/mui/layout/Menu.js
packages/react-admin/src/mui/layout/Responsive.js
packages/react-admin/src/mui/layout/Responsive.spec.js

[RFR] Review AppBar on desktop 

---

CHANGELOG.md
docs/DataProviders.md
docs/List.md
docs/Show.md
examples/simple/addUploadFeature.js
examples/simple/posts.js

The backport of changes made to the reference inputs will be done in a new PR (without rebase).

[RFR] Next backport without reference inputs

---

packages/react-admin/src/mui/button/SaveButton.js

[RFR] Sanitize show notification

---

docs/Inputs.md
packages/react-admin/src/mui/input/AutocompleteInput.js
packages/react-admin/src/mui/input/AutocompleteInput.spec.js

There are a couple of issues with `AutocompleteInput`:

[RFR] AutocompleteInput issues

---

examples/simple/comments.js

[RFR] Fix warning in simple example

---

packages/react-admin/src/mui/list/SimpleList.js

[RFR] Fix warnings in SimpleList due to Bulk Actions

---

docs/RestClients.md

https://github.com/marmelab/aor-graphql

Use new repo for GraphQL

---

packages/react-admin/package.json

... and support React 16.1 and 16.2

[RFR] Remove support for React 15.4

---

packages/ra-core/src/util/FieldTitle.js
packages/ra-core/src/util/FieldTitle.spec.js

[RFR] Humanize camel case sources

---

packages/ra-core/src/controller/field/ReferenceArrayFieldController.js
packages/ra-core/src/controller/field/ReferenceArrayFieldController.spec.js
packages/ra-core/src/reducer/admin/references/oneToMany.js

[RFR] Fix ReferenceArrayField

---

packages/ra-ui-materialui/src/auth/Logout.js
packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/layout/AppBar.js

[RFR] Reduce button size

---

UPGRADE.md

[RFR] Add TOC to UPGRADE.md

---

examples/demo/src/commands/MobileGrid.js
examples/demo/src/commands/index.js
examples/demo/src/i18n/en.js
examples/demo/src/visitors/MobileGrid.js
examples/graphcool-demo/src/commands/MobileGrid.js
examples/graphcool-demo/src/commands/index.js
examples/graphcool-demo/src/i18n/en.js
examples/graphcool-demo/src/visitors/MobileGrid.js

[RFR] Display command list for mobile

---

examples/demo/src/reviews/MobileGrid.js
examples/demo/src/reviews/index.js
examples/demo/src/reviews/rowStyle.js
examples/graphcool-demo/src/reviews/MobileGrid.js
examples/graphcool-demo/src/reviews/index.js
examples/graphcool-demo/src/reviews/rowStyle.js

[RFR] Display review list on mobile

---

docs/Translation.md
docs/_layouts/default.html

[RFR] Document how to pass variables to notifications

---

examples/demo/package.json
examples/graphcool-demo/package.json
packages/ra-core/package.json
packages/ra-realtime/package.json
yarn.lock

[RFR] Update Redux saga

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js

[RFR]: Sanitize ReferenceArrayInput

---

packages/ra-ui-materialui/src/list/Datagrid.js

This PR allows users to select all items in the list. 
See the before and after screenshots:
After:

[RFR] List allow selecting all items

---

e2e/pages/ListPage.js
e2e/pages/ShowPage.js
e2e/tests/create.js
e2e/tests/list.js
packages/ra-core/src/controller/ListController.js
packages/ra-ui-materialui/src/list/FilterForm.js

[RFR] Fix next E2E tests

---

examples/demo/src/App.js
examples/demo/src/Login.js
examples/demo/src/commands/MobileGrid.js
examples/demo/src/configuration/Configuration.js
examples/demo/src/dashboard/Dashboard.js
examples/demo/src/dashboard/Welcome.js
examples/demo/src/products/Poster.js
examples/demo/src/visitors/CustomerLinkField.js
examples/demo/src/visitors/SegmentsField.js
examples/demo/src/visitors/SegmentsInput.js
examples/demo/src/visitors/ShowPage.js
examples/demo/src/visitors/index.js

Various fixes on demo:
Before:
After:

[RFR] Fixes on demo

---

examples/demo/src/Layout.js
packages/ra-ui-materialui/src/layout/Layout.js

This saves between 70ms-120ms on each page change.

[RFR] Only create a new theme if the underlying object has changed

---

UPGRADE.md

Type "function as child" expression, instead of "child as a function".

Update UPGRADE.md: Use "function as child"

---

packages/ra-ui-materialui/src/layout/Notification.js

Notifications didn't show if there are any available before the `Notification` component is mounted.

[RFR]: Show notifications if available at mount

---

packages/ra-core/src/form/FormField.js

Closes #1645 
Side note for myself: this type of bug wouldn't happen if we used strong typing.

[RFR] Fix false default value not used

---

packages/ra-ui-materialui/src/form/Toolbar.js

Closes #1637
Supersedes #1638
Before:
After:

[RFR] Fix edit toolbar truncated on medium screens

---

examples/demo/src/commands/Basket.js
examples/demo/src/commands/index.js
examples/graphcool-demo/src/commands/Basket.js
examples/graphcool-demo/src/commands/MobileGrid.js
examples/graphcool-demo/src/commands/index.js
examples/graphcool-demo/src/dashboard/Dashboard.js
examples/graphcool-demo/src/dashboard/PendingReviews.js
examples/graphcool-demo/src/reviews/ReviewEditActions.js
examples/graphcool-demo/src/reviews/index.js
examples/graphcool-demo/src/reviews/reviewActions.js
examples/graphcool-demo/src/reviews/reviewSaga.js
examples/graphcool-demo/src/visitors/MobileGrid.js
examples/graphcool-demo/src/visitors/index.js
packages/ra-ui-materialui/src/list/DatagridRow.js

[RFR] Fix Graphcool demo

---

packages/ra-data-graphcool/README.md
packages/ra-data-graphql-simple/README.md

People looking for a GraphQL data provider need to easily see if the ones we offer match their GraphQL grammar.

[RFR] Better document the expected GraphQL grammar

---

docs/Tutorial.md

[RFR] Fix tutorial usage of ReferenceInput for Create

---

UPGRADE.md

Same content, but more readable, and smaller (255 additions and 597 deletions).

[RFR] Change upgrade syntax to use diff for snippets

---

docs/Translation.md

[RFR] Add Catalan translation

---

src/mui/auth/Login.js

Fix issue described in https://github.com/marmelab/admin-on-rest/issues/1705

Fix login layout in IE 11

---

packages/ra-data-graphcool/README.md
packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/README.md
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql/README.md
packages/ra-data-graphql/package.json

[RFR] Make graphql a peer dependency

---

packages/ra-ui-materialui/src/layout/Layout.js

[RFR] Fix TabFormLayout

---

packages/ra-core/src/reducer/admin/resource/list/total.js
packages/ra-core/src/sideEffect/undo.js
packages/ra-core/src/sideEffect/undo.spec.js

[RFR] Refresh after success of optimistic action

---

docs/CreateEdit.md
docs/Tutorial.md
docs/_layouts/default.html
examples/tutorial/src/App.js
examples/tutorial/src/posts.js
packages/ra-core/src/CoreAdmin.js
packages/ra-core/src/CoreAdminRouter.js
packages/ra-data-json-server/src/index.js

The tutorial was a bit hard to follow. I made shorter sections, added a bit more explanations, and removed non-related content.
Also, I added the ability to run an `<Admin>` with no child (just displays a confirmation screen). IMO, it provides a better developer experience for first time users, by allowing baby steps.

[RFR] Update Tutorial for better first contact

---

src/mui/input/NumberInput.js
src/mui/input/NumberInput.spec.js

Closes #1612 on `master`
Fixed in `next` in ba0b514068fc01f94282a7e3de1f599b55e7ca3e

[RFR] Fix NumberInput returns String value

---

packages/ra-ui-materialui/src/layout/AppBar.js

[RFR] Force AppBar redraw when locale changes

---

.gitignore
Makefile
packages/react-admin/package.json

Bundle docs in main package

---

docs/Authentication.md

params.message.status is undefined

Fix typo in Authentication documentation

---

packages/ra-core/src/actions/dataActions.js

[RFR] Fix infinite loading loop in case of HTTP error

---

packages/ra-ui-materialui/src/input/ArrayInput.js
packages/ra-ui-materialui/src/input/ArrayInput.spec.js

see #1783 
Allow ArrayInput to pass the record props to its child.

[RFR] Fix array input

---

docs/Inputs.md
packages/ra-ui-materialui/src/list/Filter.spec.js
packages/ra-ui-materialui/src/list/FilterForm.js
packages/ra-ui-materialui/src/list/FilterForm.spec.js
packages/ra-ui-materialui/src/list/FilterFormInput.js

[RFR] Allow all inputs to be alwaysOn filters

---

docs/Authentication.md

[RFR] Fix outdated Logout documentation

---

yarn.lock

[RFR] Upgrade yarn.lock to get latest upath

---

examples/demo/src/dashboard/CardIcon.js
examples/demo/src/dashboard/MonthlyRevenue.js
examples/demo/src/dashboard/NbNewOrders.js
examples/demo/src/dashboard/NewCustomers.js
examples/demo/src/dashboard/PendingReviews.js

[RFR] Nicer dashboard in demo example

---

packages/ra-ui-materialui/src/list/SingleFieldList.js

[RFR] Fix warning in SingleFieldList

---

docs/Inputs.md
packages/ra-ui-materialui/src/form/SimpleFormIterator.js

Added allowAdd & allowRemove attribute to control ADD & REMOVE buttons

---

packages/ra-ui-materialui/src/auth/Login.js

[RFR] Fix proptype warning in custom login form

---

examples/demo/src/dashboard/Welcome.js

The demo is our showcase, so it better be good lookin'. And what's more good lookin' than a good ol' beard? (pardon my accent, I'm French)

[RFR] Add media to dashboard

---

docs/Translation.md

[RFR] Add Russian translation

---

packages/ra-ui-materialui/src/auth/Logout.js

[RFR] Fix logout button icon padding

---

README.md
docs/CustomApp.md
docs/Fields.md
examples/demo/src/dataProvider/rest.js
examples/simple/src/dataProvider.js
packages/ra-realtime/README.md
packages/react-admin/README.md

Refs https://github.com/api-platform/docs/pull/503#issuecomment-395964338

[RFR] Fix mentions of REST client in the documentation

---

docs/Inputs.md

[RFR] Fix AutocompleteInput documentation refers to outdated mui doc

---

docs/Fields.md

- In withStyles usage sample add destructuring parameters with ({ classes, ...props })
- In sample where override the field header use headerClassName property instead of cellClassName

fix withStyles usage samples

---

packages/ra-ui-materialui/src/input/Labeled.js
packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/ReferenceInput.js

[RFR] Label & validation fixes

---

examples/demo/package.json
examples/demo/src/dashboard/NewCustomers.js
examples/demo/src/dashboard/PendingOrders.js
examples/demo/src/dashboard/PendingReviews.js
examples/demo/src/products/GridList.js
examples/graphcool-demo/package.json
examples/simple/package.json
examples/tutorial/package.json
packages/ra-ui-materialui/package.json
yarn.lock

Normally no breaking changes, but it adds new features. See https://github.com/mui-org/material-ui/releases for detailed changelog.

[RFR] Upgrade to material-ui 1.2.1

---

docs/CreateEdit.md

[RFR] Document custom path as the redirect prop on Create/Edit

---

docs/Inputs.md
packages/ra-core/src/controller/input/ReferenceInputController.js

[RFR] Pass the sort, pagination, and filters to the child of ReferenceInput

---

packages/ra-input-rich-text/src/index.js

[RFR] Add validation to `<RichTextInput>`

---

docs/CreateEdit.md
packages/ra-core/src/sideEffect/redirection.js
packages/ra-core/src/util/resolveRedirectTo.js
packages/ra-core/src/util/resolveRedirectTo.spec.js
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

[RFR] Redirect function

---

packages/ra-ui-materialui/src/input/ArrayInput.js

[RFR] Fix missing resource in ArrayInput iterator

---

docs/Admin.md
docs/Authorization.md

[RFR] Document icon format restriction in MenuItemLink

---

docs/Theming.md

[RFR] Fix outdated theming doc

---

packages/ra-core/src/util/fetch.js

[RFR] Fix error in jsonserver provider on Windows

---

packages/ra-core/src/auth/WithPermissions.js

[RFR] Fix WithPermissions calling setState in async function

---

docs/Theming.md

Pretty sure it wasn't meant to be here

[RFR] Docs - Writing a Custom Theme

---

packages/ra-core/src/Resource.js
packages/ra-core/src/controller/CreateController.js
packages/ra-core/src/controller/EditController.js
packages/ra-core/src/controller/ListController.js
packages/ra-core/src/controller/ShowController.js

[RFR] Refactor Resource component to handle route parsing

---

examples/demo/src/visitors/SegmentInput.js
examples/demo/src/visitors/index.js
packages/ra-ui-materialui/src/form/FormInput.js
packages/ra-ui-materialui/src/input/Labeled.js

[RFR] Fix fullWidth warning when using Labeled

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

The case was simply not handled... 😰 
Closes #1943

[RFR] Fix AutocompleteInput when used in standalone

---

packages/ra-core/src/actions/dataActions.js
packages/ra-core/src/sideEffect/undo.js
packages/ra-core/src/sideEffect/undo.spec.js

[RFR] Restrict refresh in case of fetch failure to pessimistic mode

---

docs/Admin.md

[RFR] Fix broken ink in `<Admin>` documentation

---

docs/List.md

[RFR] Remove outdated style prop in <Datagrid> documentation

---

packages/ra-ui-materialui/src/form/FormInput.js

[RFR] Fix FormInput not passing resource anymore

---

cypress/integration/create.js
examples/simple/src/posts/PostCreate.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

[RFR] Fix form resetting when a input with defaultValue is dynamically added

---

docs/Admin.md
docs/Theming.md
packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/layout/Error.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/index.js

[RFR] Add Error Page

---

docs/CreateEdit.md

[RFR] Fix duplicated block in CreateEdit doc

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

[RFR] Add support for asyncBlurFields in forms

---

cypress/integration/list.js
cypress/integration/permissions.js
cypress/start.js
examples/simple/src/comments/CommentList.js
examples/simple/src/posts/PostList.js
examples/simple/src/users/UserList.js
packages/ra-core/src/controller/ListController.js
packages/ra-core/src/reducer/admin/resource/data.js
packages/ra-core/src/reducer/admin/resource/index.js
packages/ra-core/src/reducer/admin/resource/index.spec.js
packages/ra-core/src/reducer/admin/resource/list/ids.js
packages/ra-core/src/reducer/admin/resource/list/index.js
packages/ra-core/src/reducer/admin/resource/list/params.js
packages/ra-core/src/reducer/admin/resource/list/total.js

[RFR] Fix list filterDefaultValues is shared accross resources

---

examples/demo/package.json
examples/graphcool-demo/package.json
examples/simple/package.json
examples/tutorial/package.json
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/layout/AppBar.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/Sidebar.js
yarn.lock

Material-ui 1.4 ships with the "dense" toolbar variant (cf https://github.com/mui-org/material-ui/issues/11619). It allows us to give more screen real estate to content on desktop.
Before:
After:

[RFR] Make AppBar dense

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

[RFR] Fix form keep values after navigation

---

packages/ra-ui-materialui/src/field/BooleanField.js
packages/ra-ui-materialui/src/field/BooleanField.spec.js
packages/ra-ui-materialui/src/field/DateField.js
packages/ra-ui-materialui/src/field/DateField.spec.js
packages/ra-ui-materialui/src/field/FunctionField.js
packages/ra-ui-materialui/src/field/FunctionField.spec.js
packages/ra-ui-materialui/src/field/NumberField.js
packages/ra-ui-materialui/src/field/NumberField.spec.js
packages/ra-ui-materialui/src/field/SelectField.js
packages/ra-ui-materialui/src/field/SelectField.spec.js
packages/ra-ui-materialui/src/field/TextField.js
packages/ra-ui-materialui/src/field/TextField.spec.js

Fixes #2031 
Before:
After:
Note: There is still an issue with the tab buttons but it seems to be on material-ui side

[RFR] Fix Theme doesn't apply to Fields

---

packages/ra-core/src/util/fetch.js

[RFR] Fix buffer test

---

packages/ra-ui-materialui/src/detail/index.js
packages/ra-ui-materialui/src/layout/index.js

[RFR] Export CreateActions and RecordTitle

---

.gitignore
.travis.yml
Makefile
README.md
examples/data-generator/package.json
lerna.json
package.json
packages/ra-core/package.json
packages/ra-data-fakerest/package.json
packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql/package.json
packages/ra-data-json-server/package.json
packages/ra-data-simple-rest/package.json
packages/ra-input-rich-text/package.json
packages/ra-language-english/package.json
packages/ra-language-french/package.json
packages/ra-realtime/package.json
packages/ra-ui-materialui/package.json
packages/react-admin/package.json
yarn.lock

Fixes #2030
Use package scripts compatible with all platforms (using [cross-env](https://github.com/kentcdodds/cross-env))
Makefile will use those scripts.

[RFR] Use package scripts

---

docs/DataProviders.md
packages/ra-core/src/dataFetchActions.js
packages/ra-core/src/sideEffect/fetch.js
packages/ra-language-english/index.js
packages/ra-language-french/index.js

Should improve DX for newcomers.
Supersedes #2057, refs #2055

[RFR] Add dataProvider response format validation

---

packages/ra-core/src/actions/dataActions.js

[RFR] Fix ReferenceInput loop on missing reference

---

docs/Inputs.md

Replaced `UrlInput` by the generic `TextInput`

[RFR] (docs) Inputs : There is no UrlInput component in react-admin

---

Makefile

Reverts marmelab/react-admin#2071

Revert "Fix the 'directory already exists' issue when re-making the project"

---

cypress/integration/create.js
examples/simple/src/posts/PostCreate.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Reverts marmelab/react-admin#2037, which caused a chain of regressions

Revert "[RFR] Fix form resetting when a input with defaultValue is dynamically added"

---

cypress/cypress.json
cypress/plugins/index.js
cypress/start.js

See https://github.com/cypress-io/cypress/issues/2037

[RFR] Fix cypress failing on chrome 68

---

cypress/cypress.json
cypress/integration/create.js
cypress/plugins/index.js
cypress/start.js

[RFR] Fix cypress on next

---

docs/Ecosystem.md

Hi,
We are happy to introduce you a new plugin for react-admin we developed with @ArnaudD .
Below a preview, more info on https://github.com/fizix-io/ra-customizable-datagrid.
<a href="https://fizix-io.github.io/ra-customizable-datagrid/" rel="noopener" target="_blank">Demo link</a>
<p align="center">
</p>

[RFR] docs/ecosystem : add ra-customizable-datagrid

---

cypress/integration/create.js
cypress/support/CreatePage.js
examples/demo/package.json
examples/graphcool-demo/package.json
examples/simple/src/posts/PostCreate.js
examples/simple/src/users/UserCreate.js
examples/simple/src/users/UserEdit.js
packages/ra-core/package.json
packages/ra-core/src/actions/formActions.js
packages/ra-core/src/reducer/admin/record.js
packages/ra-core/src/reducer/admin/record.spec.js
packages/ra-core/src/sideEffect/admin.js
packages/ra-core/src/sideEffect/index.js
packages/ra-core/src/sideEffect/recordForm.js
packages/ra-core/src/sideEffect/recordForm.spec.js
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/form/FormTab.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
yarn.lock

[RFR] Fix form reinitializations 

---

package.json

[RFR] Fix prettier command

---

packages/ra-ui-materialui/src/form/index.js

Just adding this here so we can import to our custom SimpleFormIterator.

Exporting FormInput

---

docs/Actions.md
docs/CreateEdit.md
docs/Show.md
examples/demo/src/reviews/ReviewEditActions.js
examples/graphcool-demo/src/reviews/ReviewEditActions.js
packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/EditActions.js
packages/ra-ui-materialui/src/detail/ShowActions.js

[RFR] Remove ListButton

---

packages/ra-core/src/controller/field/ReferenceManyFieldController.js
packages/ra-core/src/controller/field/ReferenceManyFieldController.spec.js
packages/ra-core/src/controller/input/ReferenceArrayInputController.js
packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.js
packages/ra-core/src/controller/input/ReferenceInputController.js
packages/ra-core/src/controller/input/ReferenceInputController.spec.js

[RFR] Fix Reference components do not update from their props

---

packages/ra-ui-materialui/src/layout/AppBarMobile.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/ViewTitle.js

|Before|After|
|------|-----|
|![localhost_8080_ iphone 6_7_8](https://user-images.githubusercontent.com/99944/43527652-678fd4f8-95a7-11e8-8e68-10722149fb1a.png)|![localhost_8080_ iphone 6_7_8 1](https://user-images.githubusercontent.com/99944/43527651-676dad6a-95a7-11e8-87c0-f60750962c68.png)|

[RFR] Fix mobile layout

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

[RFR] Fix Autocomplete list is cut off by content area

---

cypress/integration/create.js
docs/Inputs.md
examples/simple/src/posts/PostCreate.js
packages/ra-core/src/form/FormDataConsumer.js
packages/ra-ui-materialui/src/form/SimpleFormIterator.js

[RFR] Allow the FormDataConsumer to be used inside an ArrayInput

---

packages/ra-ui-materialui/src/auth/LoginForm.js

Fix Not Bounding correctly <label> and <input> in login form

---

packages/ra-ui-materialui/src/list/DatagridHeaderCell.js
packages/ra-ui-materialui/src/list/DatagridHeaderCell.spec.js

Closes https://github.com/marmelab/react-admin/issues/2143

[RFR] Sort fields with with sortBy even if they have no source

---

cypress/integration/edit.js
cypress/support/EditPage.js
examples/simple/src/posts/PostEdit.js
packages/ra-core/src/sideEffect/recordForm.js
packages/ra-core/src/sideEffect/recordForm.spec.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

[RFR] Fix form reset on navigation

---

packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectInput.js

[RFR] Fix Select inputs validation

---

docs/DataProviders.md

As discussed in #1958, here's my PR to reference the data provider for Prisma

[RFR] Add a data provider for Prisma in documentation

---

packages/ra-ui-materialui/src/form/Toolbar.js

[RFR] Allow overriding handleSubmit props in toolbar items

---

docs/AdvancedTutorials.md
docs/_layouts/default.html

[RFR] Add a Advanced Tutorials section to the documentation

---

packages/ra-ui-materialui/src/input/SelectInput.js
packages/ra-ui-materialui/src/input/SelectInput.spec.js

[RFR] Fix SelectInput empty value

---

docs/Inputs.md

[RFR] Fix FileInput documentation

---

examples/demo/src/commands/CommandList.js
examples/demo/src/products/index.js
examples/demo/src/reviews/index.js
examples/demo/src/visitors/index.js
examples/simple/src/comments/CommentList.js
packages/ra-ui-materialui/src/input/SearchInput.js
packages/ra-ui-materialui/src/list/FilterForm.js

[RFR] Adjust SearchInput margin to avoid jump when adding new filter

---

docs/List.md

[RFR] Fix list documentation for bulkActions

---

packages/ra-ui-materialui/src/field/FileField.js

[RFR] Fix FileField warnings about unknown props

---

examples/simple/src/comments/CommentList.js
examples/simple/src/posts/PostEdit.js
packages/ra-ui-materialui/src/list/Datagrid.js

Mostly, re-adding the right padding on the last cell of the datagrids.

[RFR] Miscellaneous UI fixes

---

packages/ra-input-rich-text/src/index.js

pass fullWidth in RichTextInput to FormControl be able to make the wysiwyg full width

[RFR] RichTextInput - allow fullWidth

---

packages/ra-input-rich-text/src/index.js

Reverts marmelab/react-admin#2247 because it was merged on the wrong branch

Revert "[RFR] RichTextInput - allow fullWidth"

---

docs/Inputs.md
examples/simple/src/posts/PostEdit.js
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInputChip.js
packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/index.js
packages/ra-ui-materialui/src/input/sanitizeRestProps.js
yarn.lock

[RFR] AutocompleteArrayInput

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInputChip.js

[RFR] Fix AutocompleteArrayInput select on click

---

docs/Translation.md

Hi, I created the hungarian translation for react-admin, and published it to npm. Now I added the path of the git repo to the Translation doc

Added Hungarian translation

---

packages/ra-ui-materialui/src/input/DateInput.js

[RFR] Fix dateInput keyboard handling

---

packages/ra-ui-materialui/src/form/Toolbar.js

[RFR] Fix Delete button for record of id zero

---

packages/ra-core/src/actions/accumulateActions.js

[RFR] Fix crudGetMatchingAccumulate not using relatedTo to build accumulateKey

---

packages/ra-data-graphql/README.md

https://github.com/marmelab/react-admin/blob/master/UPGRADE.md#removed-the-delete-view-in-resource

removed remove prop in Resource in graphql readme usage instructions

---

packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/ListActions.js
packages/ra-ui-materialui/src/list/ListToolbar.js

[RFR] Fix type warning when `bulkActions=false`

---

docs/DataProviders.md

Adding Data Provider for Firebase

ra-data-firebase-client

---

packages/ra-core/src/sideEffect/recordForm.js
packages/ra-core/src/sideEffect/recordForm.spec.js

[RFR] Fix resetform when navigating to same page

---

packages/ra-core/src/reducer/admin/resource/list/selectedIds.js

[RFR] Remove id of deleted records from selectedIds array

---

packages/ra-input-rich-text/src/QuillSnowStylesheet.js

[RFR] Fix RichTextInput link tooltip z-index

---

docs/Translation.md

turkish translations for react-admin is available on npm.

new Turkish transtation

---

docs/List.md

Small typo in List doc

---

docs/DataProviders.md

Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>

[RFR] Docs: renaming aor-feathers-client to ra-data-feathers

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js

Closes #2352 (which describes the issue and the fix perfectly, thanks @Dragonqos!)

[RFR] Fix SimpleFormIterator does not iterate on sub records

---

packages/ra-ui-materialui/src/input/SelectArrayInput.js

The error wasn't styled properly

[RFR] Fix SelectArrayInput error display

---

docs/Reference.md
docs/_layouts/default.html

[RFR] AutocompleteArrayInput documentation

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js

[RFR] Fix AutocompleteArrayInput label

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

[RFR] Limit autocomplete height

---

packages/ra-ui-materialui/src/detail/Show.js

[RFR] Fix wrong PropType warning in ShowView

---

packages/ra-ui-materialui/src/button/ExportButton.js

[RFR] Fix bug in exporter fetchRelatedRecords

---

packages/ra-data-simple-rest/README.md
packages/ra-data-simple-rest/src/index.js

Fix CREATE url
``` 
POST http://my.api.url/posts/123
```
->
```
POST http://my.api.url/posts
```

Fix ra-data-simple-rest  CREATE doc.

---

README.md
package.json

[RFR] Fix instructions to develop react-admin using npm link

---

docs/Translation.md

I've translated contents to catalan as a translation package (own repository)

Added catalan translations

---

docs/List.md

|react-admin version|
|--|
|v2.4.1|
Fixed params in example code inside the docs about `List` view.

[Docs] Fixed example code

---

packages/ra-ui-materialui/src/button/DeleteButton.js

[RFR] Fix click on DeleteButton in List redirects to Edit

---

docs/UnitTesting.md
docs/_layouts/default.html

docs: add docs for unit testing custom views

---

examples/demo/src/Login.js
examples/demo/src/products/index.js
examples/demo/src/visitors/index.js
examples/simple/src/posts/PostCreate.js
examples/simple/src/users/UserCreate.js
packages/ra-ui-materialui/src/auth/LoginForm.js

[RFR] Add Autofocus to login and creation form

---

packages/ra-ui-materialui/package.json
yarn.lock

Fix breaking change in material-ui-chip-input breaks compilation

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.js

Fix Error when using <CheckboxGroupInput> with wrong source attribute

---

packages/ra-data-graphcool/README.md

[RFR] Remove outdated graphcool demo link

---

packages/ra-core/src/CoreAdmin.tsx
packages/ra-ui-materialui/src/auth/Login.js

[RFR] Apply theme to login

---

packages/ra-ui-materialui/src/input/SelectInput.spec.js

[RFR] Fix warning in SelectInput test

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js

closes #2611
That one was hard to track, and reproducible only with compiled code.

[RFR] Fix AutocompleteArrayInput crash when selecting value

---

cypress/support/CreatePage.js
cypress/support/EditPage.js
packages/ra-ui-materialui/src/form/Toolbar.js

Closes #2618 
Before | After
---------|----------

[RFR] Fix mobile toolbar overlays on last input

---

docs/Theming.md

[RFR] Fix broken link to default layout in Theming documentation

---

packages/ra-ui-materialui/src/list/index.js

Export DatagridBody, DatagridRow, DatagridHeaderCell, and DatagridCell according to documentation to customize data grid at any level
Fixes #2637

Fix DataGrid export

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js

[RFR] Fix ArrayInput error format

---

docs/Inputs.md

[RFR] Fix custom material-ui input documentation

---

.github/ISSUE_TEMPLATE/Bug_report.md

[RFR] Update Codesandbox link

---

docs/Translation.md

[RFR] Fix Chinese Locale name

---

examples/demo/package.json
examples/tutorial/package.json
yarn.lock

[RFR] Fix ra-data-simple-rest dependency

---

packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/ListToolbar.js

Related to https://github.com/marmelab/react-admin/pull/2638#issuecomment-452768564

Fix propType warning when using exporter false in List

---

packages/ra-ui-materialui/src/auth/LoginForm.js

[RFR] Fix double attribute declaration in LoginForm causes error in IE11

---

docs/Inputs.md

[RFR] Fix ReferenceInput documentation mentioning wrong data provider verb

---

packages/ra-ui-materialui/src/list/Datagrid.js

fix(Datagrid): corrected proptypes error.

---

packages/ra-ui-materialui/src/button/CloneButton.js

[RFR] Fix warning in CloneButton when used inside Toolbar

---

packages/ra-ui-materialui/src/field/ReferenceManyField.js

[RFR] Fix warning when using Pagination in ReferenceManyField

---

docs/List.md
examples/demo/src/invoices/InvoiceList.js
packages/ra-ui-materialui/src/list/DatagridRow.js

[RFR] Add support for rowClick="expand" in Datagrid

---

packages/ra-core/src/controller/EditController.js
packages/ra-core/src/controller/ShowController.js

`location` isn't required at all.
Closes #2804

[RFR] Fix error when using Edit component as expand in list

---

docs/Admin.md

[RFR] Fix outdated documentation about messages prop in Admin

---

docs/CustomApp.md
packages/ra-core/src/form/index.js

[RFR] Fix missing export preventing custom app to work

---

packages/ra-input-rich-text/src/index.js

[RFR] Fix RichTextInput adds extra paragraph element after list items

---

packages/ra-core/src/controller/input/ReferenceInputController.spec.js

Thanks to @JulienMattiussi for finding this :smile:

[WIP] Remove .only in tests

---

docs/DataProviders.md

I created a parse client data provider that I added to the list.

Added Parse Client to data providers

---

docs/CreateEdit.md

Hi guys,
It's my first PR here. Really thanks about this awesome project. :heart: 
Closes #2781
**/CC:** @djhi

add a note about CloneButton component to docs

---

packages/ra-input-rich-text/src/index.js

Fix RichTextInput does not update when content is changed outside the editor

---

docs/Theming.md
packages/ra-ui-materialui/src/layout/MenuItemLink.js

[RFR] Fix MenuItemLink propTypes and documentation

---

packages/ra-language-french/index.js

#2943 Failed to minify ra-language french at build time

---

docs/List.md

Hi guys.
When I was going through documents, I noticed setting the primary color on button was outdated.
What do you think about this?

Fix button usage to show primary color

---

README.md
examples/demo/README.md

Fix demo installation documentation

---

docs/_layouts/default.html
docs/css/style.css

Add search engine to documentation (powered by Qwant)

---

packages/react-admin/package.json

Revert declaration of types for react-admin package

---

docs/Tutorial.md

Fixed a small typo of the word "that" to "than"

Fixed typo

---

docs/Translation.md

Hi guys
I translated official [english translation](https://github.com/marmelab/react-admin) repo to arabic.
I think people can use and benefit from this.
What do you guys think?

Arabic translation

---

packages/react-admin/tsconfig.json

Fix Typescript Import Errors

---

docs/Authentication.md

Fix misleading documentation about auth failure redirection

---

docs/CreateEdit.md
docs/Show.md
packages/ra-ui-materialui/src/detail/Tab.js
packages/ra-ui-materialui/src/form/FormTab.js

Add the ability to style the tab contents in Show and Edit views

---

packages/ra-tree-ui-materialui/README.md

Fix outdated i18n syntax in ra-tree-material-ui documentation

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

add helper text to autocompleteinput

---

packages/ra-ui-materialui/src/list/Filter.js

Hi guys
I made this PR for [this issue](https://github.com/marmelab/react-admin/issues/3012).
Please let me know how it looks.
Cheers

Remove unused debounce prop from Filter

---

docs/Authentication.md

[RFR] Fix misleading example about action creator usage

---

docs/Authentication.md

Fixes https://github.com/marmelab/react-admin/issues/3033#issuecomment-475622706

[RFR] Fix redirect after logout documentation

---

packages/ra-core/src/auth/WithPermissions.tsx

https://stackoverflow.com/questions/55297559/react-admin-what-is-authparams-for?answertab=active#tab-top

doc(WithPermissions): Update example, using render instead of children

---

docs/Translation.md

add: zh-TW translation in Doc

---

packages/ra-data-graphql/README.md

"builqQuery" instead of "buildQuery"

Fix typo in ra-data-graphql documentation

---

packages/ra-ui-materialui/src/layout/Confirm.js

[RFR] Fix delete confirmation dialog triggers rowClick

---

packages/ra-ui-materialui/src/list/DatagridRow.js

[RFR] Fix Datagrid cells have non unique ids

---

examples/demo/src/App.js
examples/demo/src/layout/Layout.js

[RFR] Fix demo uses deprecated menu customization syntax

---

examples/demo/src/reviews/ReviewList.js
packages/ra-core/src/controller/ListController.tsx

Better display of the review drawer which will *push* the list with an animated transition

Improve drawer animation of review edition in Posters Galore demo

---

packages/ra-ui-materialui/src/list/DatagridRow.js

Datagrid misspelling fix

---

docs/CustomApp.md
packages/ra-core/src/CoreAdmin.tsx

[RFR] Fix deprecation warnings for recent react-router releases

---

examples/simple/package.json

Objective: create a codesandbox automatically from GitHub.

[RFR] Fix simple example dependencies

---

docs/FAQ.md
examples/demo/package.json
examples/simple/package.json
examples/tutorial/package.json
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/field/BooleanField.spec.js
yarn.lock

[RFR] Revert Relax material ui version dependency

---

docs/Actions.md

[RFR] Fix Mutation documentation showing wrong notification side effect syntax

---

packages/ra-ui-materialui/src/list/DatagridRow.js

Fix rowClick using function value returning empty redirect behavior

---

packages/ra-ui-materialui/src/field/ArrayField.tsx

[RFR] Fix propTypes warning when using ArrayField sortable

---

packages/ra-ui-materialui/src/auth/Login.tsx

Do not pass staticContext prop to html element

---

docs/Ecosystem.md

I added my markdown editor to the list of available inputs and fields.

Added markdown input to Ecosystem documentation

---

packages/ra-input-rich-text/src/index.js

Reverts marmelab/react-admin#3208

Revert "[ra-input-rich-text] Do not show error message, if input isn't touched"

---

packages/ra-core/src/controller/useListParams.spec.ts
packages/ra-core/src/controller/useListParams.ts

[RFR] Fix useListParams hook

---

packages/ra-core/src/reducer/admin/resource/list/queryReducer.spec.ts
packages/ra-core/src/reducer/admin/resource/list/queryReducer.ts

[RFR] Reset page on per page count change

---

docs/Authentication.md

Doc error fix in customizing login and logout component section
Fixes #3237

[RFR] Doc fix Customizing Login and Logout components

---

docs/Ecosystem.md

[RFR] Add ra-auth-acl to the ecosystem

---

docs/Admin.md
docs/Theming.md

[RFR] Fix MenuItemLink primaryText documentation

---

packages/ra-ui-materialui/src/list/index.js

For some reason `ListView` wasn't exported.

export ListView component

---

docs/List.md

[RFR] Fix dead link to material-ui doc in List customization

---

docs/List.md

Reverts marmelab/react-admin#3351

Revert "[RFR] Fix dead link to material-ui doc in List customization"

---

docs/List.md

Fix Lists/Aside sum example

---

examples/demo/src/layout/Menu.js
examples/demo/src/layout/SubMenu.js
packages/ra-ui-materialui/src/layout/Menu.js
packages/ra-ui-materialui/src/layout/MenuItemLink.js

Fixes #3343. The demo uses a custom menu so I updated it to also show the tooltip. I created a PR for this before but I closed it due to have chosen the wrong branch.

[RFR] Add tooltip to menu entries on the sidebar

---

packages/ra-core/src/util/withDataProvider.ts

[RFR] Ensure dataProvider callback sideeffect is called when using withDataProvider

---

packages/ra-ui-materialui/src/layout/Confirm.js

[RFR] Fix click on dialog text triggers datagrid rowClick

---

packages/ra-core/src/controller/ListController.tsx

[RFR] Fix List does not update if AUTH_GET_PERMISSIONS is slow

---

packages/ra-data-graphql-simple/src/buildVariables.js
packages/ra-data-graphql-simple/src/buildVariables.test.js

[RFR] Add pagination and sorting params to GET_MANY_REFERENCE

---

examples/data-generator/README.md

generate import does not match used function.

[RFR] Fix data generator usage example

---

packages/ra-core/package.json

Closes #3431 
Supersedes #3439

[RFR] Promoting react-testing-library as a dependency

---

packages/ra-ui-materialui/src/input/LongTextInput.js

[RFR] Fix long text input isn't so long

---

docs/List.md
examples/simple/src/posts/ResetViewsButton.js
packages/ra-core/src/fetch/index.ts
packages/ra-core/src/fetch/useDelete.ts
packages/ra-core/src/fetch/useDeleteMany.ts
packages/ra-core/src/fetch/useUpdateMany.ts
packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.js

[RFR] Add useDeleteMany and useUpdateMany hooks

---

examples/demo/src/products/ProductList.js
examples/simple/src/posts/PostList.js
packages/ra-ui-materialui/src/list/FilterForm.js
packages/ra-ui-materialui/src/list/FilterFormInput.js

[RFR] Fix hide filter button isn't aligned with field

---

packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/field/ReferenceField.spec.js

The URL was always undefined. I added a test to avoid that kind of regression in the future.

[RFR] Fix ReferenceField link

---

docs/Translation.md

Updated the Swedish translation to react-admin and added link in _Translations_ documentation

Add Swedish translation link for react-admin

---

docs/List.md

[RFR]: add missing imports

---

packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridCell.js
packages/ra-ui-materialui/src/list/DatagridHeaderCell.js
packages/ra-ui-materialui/src/list/DatagridLoading.js
packages/ra-ui-materialui/src/list/DatagridRow.js

Fixes #3435
With bulk actions:
Without bulk actions:
Without bulk actions nor expand:

[RRR] Fix Datagrid headers

---

docs/CustomApp.md
packages/ra-core/src/CoreAdmin.tsx

Fixes #3445
*Note*: I tried it by following the custom app documentation on our simple example locally.

[RFR] Fix Custom Apps

---

docs/CustomApp.md
docs/FAQ.md
docs/UnitTesting.md
examples/demo/src/i18n/en.js

- This PR fixes typos in welcome message of demo and documentation.
- Some of the typo needs confirmation from the repo owner.
- Text review
- Needs more than 10 minutes for review? No
- (I really appreciate you guys for making this amazing library. I'll study harder to contribute more!)

[RFR] Fix typos in documentation and demo

---

package.json

Found by https://github.com/marmelab/react-admin/pull/3457#discussion_r312320855

[RFR] Fix typo in package.json

---

packages/ra-core/src/form/FormField.tsx
packages/ra-core/src/form/isRequired.ts
packages/ra-core/src/form/useInput.spec.tsx
packages/ra-core/src/form/useInput.ts

This is the first step to avoid the `addField` HOC in our inputs.

[RFR] Introduce useInput hook

---

cypress/integration/create.js
packages/ra-core/src/form/index.ts
packages/ra-core/src/form/useInput.ts
packages/ra-ui-materialui/src/input/BooleanInput.js
packages/ra-ui-materialui/src/input/BooleanInput.spec.js
packages/ra-ui-materialui/src/input/BooleanInput.spec.tsx
packages/ra-ui-materialui/src/input/BooleanInput.tsx
packages/ra-ui-materialui/src/input/InputPropTypes.ts
packages/ra-ui-materialui/src/input/sanitizeRestProps.ts

[RFR] Convert BooleanInput to TypeScript

---

examples/simple/package.json
examples/simple/src/index.js
examples/simple/src/tags/TagList.js
examples/simple/webpack.config.js
packages/ra-tree-ui-materialui/package.json
packages/ra-tree-ui-materialui/src/NodeForm.js
packages/ra-tree-ui-materialui/src/Tree.js
yarn.lock

Temporary because I'm rewriting those packages from scratch. This will allow me to migrate another projet to v3.

[RFR] Temporary migration of ra-tree to v3

---

packages/ra-ui-materialui/src/input/DateTimeInput.js
packages/ra-ui-materialui/src/input/DateTimeInput.tsx

[RFR] Migrate DateTimeInput to TypeScript

---

cypress/package.json
yarn.lock

Solves the conflicts between chai and jest types

[RFR] Upgrade Cypress

---

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
packages/ra-ui-materialui/src/input/NumberInput.tsx

[RFR] Migrate NumberInput to TypeScript

---

packages/ra-ui-materialui/src/layout/LoadingIndicator.js

Just another conversion to `useStyles` for LoadingIndicator component

[RFR] Change to useStyles for LoadingIndicator component

---

packages/ra-tree-ui-materialui/src/NodeActions.js

Changed to a function component and use `useStyles` instead of `withStyles`

[RFR] Change to useStyles for NodeActions component

---

packages/ra-ui-materialui/src/layout/Error.js

Use useStyles instead of withStyles for ra-ui-materialui Error component

[RFR] Change to useStyles for Error component

---

packages/ra-ui-materialui/src/layout/Confirm.js

Change to useStyles for Confirm component of ra-ui-materialui package.

[RFR] Change to useStyles for Confirm component

---

packages/ra-ui-materialui/src/button/SaveButton.js

Converted `SaveButton` to a function component and replace `withStyles` with `useStyles`. Thank you in advance for reviewing.

[RFR] Change to useStyles for SaveButton component

---

packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/input/FileInput.js
packages/ra-ui-materialui/src/input/FileInput.spec.js
packages/ra-ui-materialui/src/input/FileInputPreview.js
packages/ra-ui-materialui/src/input/FileInputPreview.spec.js
packages/ra-ui-materialui/src/input/ImageInput.js
packages/ra-ui-materialui/src/input/ImageInput.spec.js
yarn.lock

[RFR] Migrate FileInput and related components to hooks

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx

[RFR] Add row prop to CheckboxGroupInput

---

packages/ra-tree-ui-materialui/src/Tree.js

Change to useStyles for Tree component

[RFR] Change to useStyles for Tree component

---

packages/ra-ui-materialui/src/field/BooleanField.tsx
packages/ra-ui-materialui/src/field/ChipField.spec.js
packages/ra-ui-materialui/src/field/ChipField.tsx
packages/ra-ui-materialui/src/field/FileField.spec.js
packages/ra-ui-materialui/src/field/FileField.tsx
packages/ra-ui-materialui/src/field/ImageField.spec.js
packages/ra-ui-materialui/src/field/ImageField.tsx

[RFR] Use makeStyles in Field Components

---

packages/ra-ui-materialui/src/layout/Loading.js

[Convert Loading component to useStyles

[RFR] Convert Loading component to useStyles

---

packages/ra-ui-materialui/src/layout/AppBar.js

Convert AppBar component to useStyles

[RFR] Convert AppBar component to useStyles

---

UPGRADE.md
packages/ra-ui-materialui/src/input/InputWithOptions.ts
packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.spec.js
packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
packages/ra-ui-materialui/src/input/SelectArrayInput.tsx

[RFR] Migrate SelectArrayInput to TypeScript

---

packages/ra-ui-materialui/src/layout/LinearProgress.js

Removed leftover reference to `withStyles` in LinearProgress component

Remove comment on withStyles in LinearProgress

---

packages/ra-tree-ui-materialui/src/DragLayer.js

Convert DragLayer component to useStyles #3453

[RFR] Convert DragLayer component to useStyles

---

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx

[RFR] Fix SelectArrayInput Override Choices of  ReferenceArrayInput

---

packages/ra-core/src/form/validate.spec.ts
packages/ra-core/src/form/validate.ts

[RFR] Required Validate Arrays

---

packages/ra-ui-materialui/src/list/Datagrid.js

Convert DataGrid component to useStyles #3453

[RFR] Convert DataGrid component to useStyles

---

packages/ra-ui-materialui/src/field/ReferenceManyField.spec.js
packages/ra-ui-materialui/src/list/SingleFieldList.js
packages/ra-ui-materialui/src/list/SingleFieldList.spec.js

- Convert SingleFieldList component to useStyles
- Remove `WithStyles` from `WithStyles(SingleFieldList)`
- Use default import for `SingleFieldList` in `SingleFieldList.spec.js`

[RFR] Convert SingleFieldList component to useStyles

---

packages/ra-language-english/index.js
packages/ra-language-french/index.js

[RFR] Add missing translation in NullableBooleanInput

---

packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql-simple/src/getResponseParser.js
packages/ra-data-graphql-simple/src/getResponseParser.test.js
packages/ra-data-graphql/package.json
packages/ra-data-graphql/src/index.js
yarn.lock

Fix: https://github.com/marmelab/react-admin/issues/3160

[RFR] Allow aliases in graphql dataprovider

---

docs/Theming.md

[RFR] Update examples in Theming.md

---

.travis.yml
UPGRADE.md
cypress/integration/edit.js
docs/Inputs.md
examples/simple/src/posts/PostCreate.js
examples/simple/src/posts/PostEdit.js
packages/ra-core/src/controller/input/useGetMatchingReferences.ts
packages/ra-core/src/controller/useFilterState.ts
packages/ra-core/src/controller/useSortState.ts
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js
packages/ra-ui-materialui/src/input/AutocompleteInput/AutocompleteInput.spec.js
packages/ra-ui-materialui/src/input/AutocompleteInput/AutocompleteInputTextField.js
packages/ra-ui-materialui/src/input/AutocompleteInput/AutocompleteSuggestionItem.js
packages/ra-ui-materialui/src/input/AutocompleteInput/AutocompleteSuggestionList.js
packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.js
packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js
packages/ra-ui-materialui/src/input/AutocompleteInput/index.js
yarn.lock

[RFR] New AutocompleteInput using Downshift

---

packages/ra-core/src/controller/useListController.spec.tsx
packages/ra-core/src/controller/useListParams.ts

[RFR] Fix Adding a Filter Override Displayed Filters

---

packages/ra-ui-materialui/src/list/PaginationActions.js

[RFR][alpha.4] fix bad import in PaginationActions

---

packages/ra-tree-ui-materialui/src/RootDropTarget.js

[RFR][alpha.4] fix bad import in RootDropTarget

---

docs/css/style-v2.css

Reverts marmelab/react-admin#3680
Closes #3700

Revert "Independent scrolling for the book summary"

---

docs/_layouts/default.html
docs/css/style-v2.css

- Added script to default.html in order to change style according to the search result display.
- Added the overflow styling back to the css.

Independent book-summary scrolling saga

---

packages/ra-ui-materialui/src/input/BooleanInput.spec.tsx
packages/ra-ui-materialui/src/input/BooleanInput.tsx

[RFR] Fix BooleanInput Does Not Update on Label Click

---

docs/assets/styles.css
docs/index.html

[RFR] Fix styling issues

---

packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js

Fix TabbedForm does not detect errors when source is a path

---

packages/ra-core/README.md

Also added a link to referenced package

Fixed typo in ra-core readme

---

packages/ra-core/src/sideEffect/refresh.ts

fix incorrect code documentation

---

packages/ra-ui-materialui/src/auth/LoginForm.tsx

Closes #3650 
See https://goo.gl/9p2vKq)

Added autocomplete attribute to Password field on LoginForm.tsx

---

packages/ra-core/src/Resource.spec.tsx
packages/ra-core/src/Resource.tsx

[RFR] Fix Trailing Slash in url Breaks Routing

---

docs/CustomApp.md
packages/react-admin/src/index.ts

Fix defaultI18nProvider Export

---

packages/ra-ui-materialui/src/list/Filter.js

Fix Warnings Displayed when Overriding Filter Classes

---

packages/ra-core/src/CoreAdminRouter.tsx
packages/ra-core/src/util/Ready.tsx
packages/ra-core/src/util/index.ts

this screen appears when a developer creates an `Admin` component with no `Resource` inside, i.e. when setting up a react-admin application.
Before: 
After:

[RFR] Improve welcome screen look and feel

---

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Fix AutocompleteInput does not use custom label

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Fix AutocompleteInput error color

---

packages/ra-core/src/controller/useListController.ts
packages/ra-core/src/controller/useListParams.ts
packages/ra-ui-materialui/src/field/ReferenceManyField.js

[RFR] Fix Datagrid is not sortable when inside ReferenceManyField

---

docs/Inputs.md

The arrow function was returning nothing

Fix typo in example

---

cypress/integration/list.js
packages/ra-core/src/controller/useListParams.ts
packages/ra-ui-materialui/src/list/DatagridHeaderCell.js

[RFR] Prevent calling an outdated updateSort

---

packages/ra-ui-materialui/src/layout/Layout.js

Fix theme can't be changed dynamically

---

packages/ra-ui-materialui/src/input/DateTimeInput.tsx

[RFR] Fix DateTimeInput style differs from other inputs

---

packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js

[RFR] Fix DeleteWithConfirm throws exception

---

UPGRADE.md

Fix notifications upgrade guide

---

docs/DataProviders.md

I would like to add a reference to a data provider created to interact with [Moleculer Services](https://moleculer.services/) APIs.
Your feedback would be great!

Adds a reference to a new data provider

---

packages/ra-core/src/controller/useFilterState.spec.tsx
packages/ra-core/src/controller/useFilterState.ts

[RFR] Fix useFilterState does not react to permanentFilter changes

---

packages/ra-ui-materialui/src/button/EditButton.js

[RFR] Fix overly aggressive EditButton memoization

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx

[RFR] Fix label prop not being passed to FieldTitle

---

packages/ra-ui-materialui/src/list/FilterForm.js

Problem: FilterForm not styleable
EnhancedFilterForm did not respect provided classes property.

EnhancedFilterForm: Respect classes property

---

packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts

[RFR] Fix pessimistic delete one does not remove item from selection

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx

[RFR] Fix click in AutocompleteArrayInput does not show options

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx

[RFR] Fix delete wrong item in AutocompleteArrayInput

---

packages/ra-ui-materialui/src/auth/LoginForm.tsx

[v3] Fix typo, autocomplete to autoComplete

---

packages/ra-core/src/controller/useCreateController.spec.tsx
packages/ra-core/src/controller/useCreateController.ts
packages/ra-ui-materialui/src/button/CloneButton.js
packages/ra-ui-materialui/src/button/CloneButton.spec.js

[RFR] Fix CloneButton for nested objects

---

packages/ra-core/src/dataProvider/useGetMany.ts

[RFR] Fix useGetMany hook accumulatedIds filter function

---

packages/ra-language-english/package.json
packages/ra-language-french/package.json

Fix duplicate keywords (package.json)

Fix duplicate keywords

---

docs/Inputs.md

[RFR] Improve Inputs doc to make props more obvious

---

docs/List.md

Following the discussion in #3725

📚 [documentation] add example of Datagrid custom usage

---

docs/Ecosystem.md
docs/Labs.md
docs/List.md

[RFR] Fix links to ra-tree documentation

---

packages/ra-core/src/util/Mutation.tsx

Fix call setState on an unmounted <Mutation>

---

packages/ra-ui-materialui/src/input/SelectInput.tsx

Closes [#3657](https://github.com/marmelab/react-admin/issues/3657)

Allow SelectInput label to be hidden.

---

UPGRADE.md

Upgrade > Login uses children instead of a loginForm prop

---

assets/styles.css

Fix height of preview image on safari

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Fix AutocompleteInput required label

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/ReferenceInput.tsx

Fix ReferenceInput should not set filter in getList when q is empty

---

docs/Ecosystem.md

https://github.com/marmelab/react-admin/pull/3908

ra-realtime no longer exists

---

packages/ra-core/src/controller/index.ts

Export useFilterState

---

UPGRADE.md
packages/ra-core/src/controller/useCreateController.ts

Fix create form prefill

---

packages/ra-core/src/dataProvider/useDataProvider.ts

Fix List does not Refresh Correctly after Optimistic Update

---

examples/demo/src/layout/Login.js

Fix warning about unmounted component after Login on Demo

---

packages/ra-data-graphql-simple/src/buildGqlQuery.js
packages/ra-data-graphql-simple/src/buildGqlQuery.test.js

Make sure that fields of same type is kept

ra-data-graphql-simple: Fields dropped with the same type on query #3401

---

packages/ra-data-graphcool/src/buildGqlQuery.js

This PR is a continuation of https://github.com/marmelab/react-admin/pull/3692, which adds Interface support.

Support for GraphQL Interface type, continuation of 3692

---

examples/demo/src/dashboard/NewCustomers.js

Fix Warnings on Logout on Demo
