packages/ra-ui-materialui/src/list/DatagridRow.js
=> Fix DatagridRow rowClick event handling

packages/ra-ui-materialui/src/form/TabbedForm.js
=> fix(TabbedForm): organize import

doc/3.0/Tutorial.md
=> fix: deleted unexpected semicolon

packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix incorrect dataProvider leads to infinite render loop

packages/ra-ui-materialui/src/list/FilterForm.js
=> Fix  ArrayInput usage in FilterForm

packages/ra-ui-materialui/src/input/ResettableTextField.js, packages/ra-ui-materialui/src/input/SearchInput.tsx
Closes #4069 and #3869.
Supersedes #3905
=> Fix TextInput endAdornment when resettable

packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx
Fix #4121 
Possibly this PR will conflict with #4123
=> [RFR] Fix option not being checked when numeric ids are used

cypress/integration/edit.js, packages/ra-core/src/form/useInitializeFormWithRecord.ts
=> [RFR] Fix cloned record reverts values when submitting

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
=> ReferenceArrayInput to pass parse and format

packages/ra-ui-materialui/src/input/FileInput.tsx
=> Fix FileInput onDrop option

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js, packages/ra-ui-materialui/src/input/ReferenceInput.tsx, packages/ra-ui-materialui/src/input/sanitizeRestProps.ts
=> Better prop sanitation for reference inputs

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix warning in SelectInput when alwaysOn is true

docs/Ecosystem.md
This was discussed here https://github.com/marmelab/react-admin/issues/4164
=> Add resource aggregator to docs

packages/ra-core/src/form/FormWithRedirect.tsx
Caused by TypeScript bug https://github.com/microsoft/TypeScript/issues/35771
Refs #4116
=> Fix unexpected token in FormWithRedirect

packages/ra-core/src/auth/useGetPermissions.ts
=> Fix ReferenceError in useGetPermissions due to temporal dead zone

packages/ra-core/src/form/useSuggestions.ts
The signature was updated some time ago.
=> Fix matchSuggestion Type

packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
=> Fixed filter of undefined error by setting records to empty array 

examples/demo/src/App.tsx
=> Fix graphql demo

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
=> fix red validation message for SelectArrayInput

packages/ra-data-graphql-simple/src/buildVariables.js
=> fix ra-data-graphql-simple convert SCALAR Date type to ISOString

docs/DataProviders.md
Reverts marmelab/react-admin#4230
=> Revert "Add Hasura GraphQL Provider in DataProviders list"

packages/ra-ui-materialui/src/input/NullableBooleanInput.spec.tsx, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
Closes #4299
Regression introduced by #3522
=> Fix NullableBooleanInput does not show initial value

packages/ra-ui-materialui/src/list/Datagrid.js, packages/ra-ui-materialui/src/list/List.js
=> Add sticky header to Datagrid

packages/react-admin/src/Admin.tsx
See https://github.com/api-platform/admin/pull/263#discussion_r365708363
=> Show deprecated messages only in dev

docs/CreateEdit.md
=> Fix form customization code snippet in CreateEdit documentation

docs/Theming.md
=> Fix custom layout documentation doesn't mention the importance of the <Notification> component

docs/DataProviders.md
=> Fix documentation about extending a dataProvider

packages/ra-core/src/controller/useListParams.ts
=> Fix Default Value of Filters with Paths not Applied Correctly

README.md, docs/Ecosystem.md
=> Updated development experience in README.md

docs/CreateEdit.md
=> Fix typo in Create / Edit documentation

packages/ra-input-rich-text/src/styles.js
Closes #4366 
Rich text toolbar is not visible in dark theme
=> Fix RichTextInput dark theme

packages/ra-input-rich-text/src/styles.js
=> Fich rich text colors

docs/Theming.md
=> Fix custom menu snippet in theming documentation

cypress/integration/edit.js, cypress/support/EditPage.js, examples/simple/src/users/UserEdit.js, packages/ra-core/src/sideEffect/useRedirect.ts, packages/ra-ui-materialui/src/form/FormTab.js, packages/ra-ui-materialui/src/form/TabbedForm.js
=> Fix Clone Button does not work with Tabbedform

packages/ra-ui-materialui/src/input/FileInput.spec.tsx, packages/ra-ui-materialui/src/input/ImageInput.spec.tsx
Hi guys
I found a typo in a variable name in tests
Please check it out
=> Refactor variable name defaut to default

docs/AdvancedTutorials.md
=> Fix broken images in advanced tutorials

packages/ra-core/src/core/createAdminStore.ts
Requests with Unauthorized error dispatch only FETCH_START.
=> [FIX] LoadingIndicator show infinite loading after Unauthorized error

docs/CreateEdit.md
=> Fix code sample in CreateEdit docs.

docs/Inputs.md
Pull request fix for issue #4526
=> Fix code sample in Inputs/ArrayInput docs

docs/DataProviders.md, docs/Tutorial.md, packages/ra-data-simple-rest/README.md
=> Fix invalid JSON pass to URLS in documentation.

docs/Translation.md
Added ra-language-korean translation package for react-admin.
=> add link to ra-language-korean

assets/styles.css, index.html
Add external links for all Technos and APIs
=> Add external links on Landing page

assets/styles.css
=> Revert opacity on links

docs/css/style-v4.css
=> Fix right menu : Allow to scroll when too hight

docs/Theming.md
=> Fixing theming documentation for custom icons

docs/DataProviders.md
=> Fix docs's data provider convertFileToBase64 function snippet.

packages/ra-ui-materialui/package.json, yarn.lock
=> Fix duplicate react-transition-group package

packages/ra-core/src/i18n/TranslationMessages.ts, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/layout/AppBar.js
Closes #4584
PRed against `next` because I don't want to add too many new translations in master.
=> Add translation for hamburger menu tooltip

docs/CreateEdit.md, docs/List.md, docs/Reference.md, docs/Show.md, docs/navigation.html
=> Document page controller hooks

packages/ra-ui-materialui/src/button/BulkExportButton.tsx, packages/ra-ui-materialui/src/button/ExportButton.tsx, packages/ra-ui-materialui/src/list/ListActions.js, packages/ra-ui-materialui/src/list/ListToolbar.js
=> Fix ExportButton ignores custom exporter prop

packages/ra-ui-materialui/src/input/FileInput.tsx
=> added custom onRemove

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
=> Fix missing defaultValue handling in ReferenceArrayInput

assets/styles.css, thank-you/index.html
=> Add a Thank you page

examples/demo/src/reviews/StarRatingField.tsx
=> Fix: css typo haight -> height

packages/ra-ui-materialui/src/input/AutocompleteSuggestionItem.tsx
Fixes https://github.com/marmelab/react-admin/issues/3909#issuecomment-610911371
=> Fix AutocompleteInput empty suggestion item height

docs/Translation.md
The maintainers ignored my PR for a week so I made my own package, the original had some missing translations.
=> [Docs]: Changed the portuguese translation

UPGRADE.md
=> [Doc] Fix snippet in Upgrade guide regarding `<FormDataConsumer>`

CHANGELOG.md, UPGRADE.md, docs/CreateEdit.md, docs/Fields.md, docs/Resource.md
And zero with characters in  UPGRADE.md
=> Fix identifiers in docs.

packages/ra-core/src/auth/useCheckAuth.ts
Missing parentheses in comment.
=> Fix typo in code comment for checkAuth

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix SelectInput prop sanitization

packages/ra-core/src/controller/useListController.spec.tsx, packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix List Race Condition on Loading Pages Quickly

docs/List.md, packages/ra-ui-materialui/src/list/SimpleList.js
=> Updated documentation and propType for SimpleList linkType.

docs/DataProviders.md
We published a new maintained data provider for prisma 2 (beta) and wanted to share it here!
=> add prisma 2 data provider to the docs

packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
=> Fix DeleteButton throws error when accessing detail page

docs/List.md, examples/simple/src/users/UserEditEmbedded.js
=> Fix Edit view used as expand panel in List

packages/ra-ui-materialui/src/input/CheckboxGroupInputItem.tsx
=> CheckboxGroupInputItem doesn't propagate options to Checkbox

packages/ra-core/src/reducer/admin/ui.ts
Refs https://github.com/marmelab/react-admin/pull/4677#issuecomment-624276796
=> Fix broken SSR due to sidebar open default value

packages/ra-ui-materialui/src/button/CreateButton.tsx
=> Fix Fab component console warning in empty list small screen

docs/CreateEdit.md
=> [Doc] Fix outdated mention of function default value for inputs

docs/Fields.md, packages/ra-ui-materialui/src/field/FileField.tsx
=> Add support for download, rel, and ping attributes in FileField

UPGRADE.md, docs/CustomApp.md
=> fix custom application route documentation

packages/ra-core/src/controller/index.ts
=> useListParams hook exported.

docs/DataProviders.md
Loopback is updated from 3 to 4.
Many people are using version 3 yet. Version 4 has many break changes.
Thankfully, elmaistrenko created a provider for the new version. It works well.
=> Update information for Loopback4

packages/ra-core/src/types.ts
=> Fix dataProvider.delete input type

packages/ra-core/src/controller/useListParams.spec.ts, packages/ra-core/src/controller/useListParams.ts
=> Fix list params from location are lost after redirection

packages/ra-ui-materialui/src/list/PaginationActions.js
=> Allow to style pagination buttons

packages/ra-ui-materialui/src/input/FileInput.tsx
=> Fix FileInput when used without children

packages/ra-ui-materialui/src/form/Toolbar.js
- Fix https://github.com/marmelab/react-admin/issues/4733
=> Fix: pristine not applied from edit toolbar on save button

packages/ra-ui-materialui/src/input/NumberInput.tsx
=> Fix NumberInput doesn't accept min and max props

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Feature: Add disabled prop to AutocompleteInput

.github/workflows/codeql-analysis.yml
Testing the new capabilities offered by GitHub.
=> Add GitHub Security Analysis

packages/ra-core/src/dataProvider/Query.spec.tsx, packages/ra-core/src/dataProvider/useQuery.ts
=> Fix useQuery does not run again after calling refresh

README.md
I would use react-admin not just for B2B (as your Github repo description says) or admin applications. But for any data-driven web application that I would start or plan to build today.
=> Data-driven

packages/ra-core/src/dataProvider/useGetOne.ts
=> Fix useGetOne throws exception when used in Dashboard

packages/ra-ui-materialui/src/list/DatagridRow.spec.js, packages/ra-ui-materialui/src/list/DatagridRow.tsx
Now I'm thinking this should be merge into master.
=> DatagridRow with rowClick set to "toggleSelection" and selectable set to "false" got selected.

packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
=> Fix ReferenceManyField does not pass the right resource to its children

examples/simple/webpack.config.js
Closes #5066 
Add rules in webpack dev server
=> Fix CORS issue in simple example codesandbox

packages/ra-core/src/dataProvider/useUpdateMany.ts
=> Fix useUpdateMany parameter definition

packages/ra-ui-materialui/src/layout/Layout.js
Closes #5071 
Notification toasts are shown under confirms dialog.
Set notification toasts to be shown over confirms dialog, in the Layout component.
=> Set notification over confirms dialog, not under

packages/ra-core/src/form/FormDataConsumer.tsx
=> Typo FormDataConsumer.tsx

examples/demo/package.json, packages/ra-core/package.json, packages/ra-core/src/util/removeEmpty.ts
Reference https://github.com/marmelab/react-admin/pull/5051#pullrequestreview-448934920
=> Remove recompose dependency from ra-core and demo projects.

packages/ra-ui-materialui/src/layout/Layout.js
=> Fix Default Color in Layout

packages/ra-ui-materialui/package.json, yarn.lock
Fixes https://github.com/marmelab/react-admin/issues/4793#issuecomment-648764853
=> Use latest react-transition-group

packages/ra-core/src/auth/useLogout.ts
=> Fix authProvider.checkAuth() support for redirection with query string

packages/ra-ui-materialui/src/layout/Sidebar.js
=> Fix missing styles for full height sidebar

assets/styles.css, index.html
The public website is accessible at [marmelab.com/react-admin](https://marmelab.com/react-admin).
=> Fix some typos in the public website

packages/ra-core/src/form/useSuggestions.ts
=> Fix TypeError when suggested element in AutocompleteInput is empty

packages/ra-core/src/controller/input/useGetMatchingReferences.ts
=> Fix ReferenceInput throws exception on custom pages

packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/dataProvider/useRefreshWhenVisible.ts
=> Fix addEventListener calls for compatibility with React v17.

packages/ra-core/src/actions/uiActions.ts, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useIsAutomaticRefreshEnabled.ts, packages/ra-core/src/dataProvider/useRefreshWhenVisible.ts, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/reducer/admin/ui.spec.ts, packages/ra-core/src/reducer/admin/ui.ts, packages/ra-core/src/types.ts
=> Disable Edit Automatic Refresh if Form is Dirty

docs/Ecosystem.md
Ref: #5149 
@djhi Kindly review. Thanks!
=> [docs] Added @bb-tech/ra-treemenu to the ecosystem.

docs/CreateEdit.md
This is a common demand, so I think it should be documented.
Refs #2741
=> [Doc] Explain how to add a custom back button

packages/ra-ui-materialui/src/button/SortButton.tsx
=> Fix SortButton labels.

docs/Inputs.md
https://github.com/marmelab/react-admin/pull/4365#issuecomment-676294084
=> Fixed documentation about `<NullableBooleanInput>`

docs/_layouts/default.html, docs/css/style-v5.css
=> Fix doc sidebar navigation on Firefox

cypress/cypress.json, cypress/package.json, yarn.lock
=> Fix Firefox support in end-to-end tests

examples/simple/package.json, yarn.lock
Closes https://github.com/advisories/GHSA-48gc-5j93-5cfq
=> Fix vulnerability in simple example due to serve package

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
=> Add margin to <AutocompleteArrayInput /> chips when variant=outlined

docs/AdvancedTutorials.md
=> Update Tutorial Links

packages/ra-ui-materialui/src/list/datagrid/useDatagridStyles.tsx
=> Fix Datagrid Header Cells Remove Border Radius

docs/Actions.md
Remove extra word in `Actions.md`
=> Fix minor typo in documentation

packages/ra-ui-materialui/src/layout/LoadingIndicator.js
=> Improve LoadingIndicator component styling

packages/ra-core/src/dataProvider/useRefreshWhenVisible.ts
=> Fix missing capture option in event listener removal

packages/ra-ui-materialui/src/detail/Edit.tsx
=> Fix Edit logs warning when using transform prop

packages/ra-ui-materialui/src/layout/Error.tsx
=> Fix warning about Error component proptypes when using string error

packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
This is a simple PR to allow the className attribute in SimpleFormIterator.
=> allow className attribute in SimpleFormIterator

examples/demo/src/orders/NbItemsField.tsx, packages/ra-ui-materialui/src/field/FunctionField.tsx
=> Add ability to specify record type in FunctionField

docs/List.md
=> [doc] Fix rendering a Datagrid outside a Resource instructions

packages/ra-core/src/auth/AuthContext.tsx, packages/ra-core/src/auth/useGetIdentity.ts
=> Fix default AuthContext value fails TypeScript compilation

packages/ra-core/src/auth/useGetIdentity.ts
=> Fix default authProvider.getIdentity() triggers infinite loop

docs/Authentication.md, packages/ra-core/src/auth/useCheckAuth.spec.tsx, packages/ra-core/src/auth/useCheckAuth.ts, packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx, packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
=> Add ability to hide notification when authProvider.checkAuth() or authProvider.checkError() fail

docs/Authentication.md
=> [Doc] Fix custom login snippet missing theme

docs/Actions.md, docs/Reference.md
=> [Doc] Fix specialized dataProvider hooks usage

docs/Inputs.md, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteSuggestionList.tsx
=> Fix AutocompleteInput suggestions appear beneath Dialog

packages/ra-core/src/auth/AuthContext.tsx
=> Fix TypeScript compilation error on defaultIdentity

examples/data-generator/src/customers.ts, examples/demo/src/dashboard/CardWithIcon.tsx, examples/demo/src/dashboard/NewCustomers.tsx, examples/demo/src/dashboard/OrderChart.tsx, examples/demo/src/dashboard/PendingReviews.tsx, examples/demo/src/i18n/en.ts, examples/demo/src/i18n/fr.ts, examples/demo/src/invoices/InvoiceList.tsx, examples/demo/src/layout/Menu.tsx, examples/demo/src/orders/Basket.tsx, examples/demo/src/orders/NbItemsField.tsx, examples/demo/src/orders/OrderEdit.tsx, examples/demo/src/orders/OrderList.tsx, examples/demo/src/orders/Totals.tsx, examples/demo/src/types.ts, examples/demo/src/visitors/AddressField.tsx, examples/demo/src/visitors/VisitorEdit.tsx
=> [Demo] Improve Order Edit UI

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
=> Fix AutocompleteArrayInput doesn't support the disabled prop

examples/simple/README.md
=> Fix simple example usage instructions

packages/ra-core/src/util/removeEmpty.spec.ts, packages/ra-core/src/util/removeEmpty.ts
=> Fix filter with nested source

docs/Authentication.md, packages/ra-core/src/auth/useLogout.ts, packages/ra-core/src/types.ts
=> Add ability to disable redirection after logout

docs/_layouts/default.html, docs/css/style-v8.css, docs/navigation.html
The main navigation has too many items and is hard to browse visually. Not all the elements are visible at once. 
We need to add some style.
=
=> Improve doc main navigation

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
=> Fix failed delete doesn't refresh the view

packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts, packages/ra-core/src/dataProvider/withDataProvider.tsx
=> Fix error when using withDataProvider without options argument

packages/ra-ui-materialui/src/field/EmailField.tsx, packages/ra-ui-materialui/src/field/UrlField.tsx
=> Fix EmailField with target prop fails TypeScript compilation

packages/ra-language-french/src/index.ts
Hi there, 
this is just a little PR to fix french translations. 
You make great work, keep going 👍
=> fix(french-translations): fix typo on bulk french translations

docs/Readme.md
The property is not `multiLine`. It is `multiline` in the component props.
=> [RFR] Fix documentation issue

docs/_layouts/default.html, docs/css/style-v9.css
=> [Doc] Fix search input is not visible enough

packages/ra-core/src/core/Resource.tsx
=> Fix options prop not being injected to View elements

packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix setImmediate is not defined error

docs/Inputs.md
=> [Doc] Fix link formatting in "Writing your own input" documentation

packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
=> Fix variant and margin prop on an input have no effect inside a Filter form

examples/demo/public/index.html
Can you believe we've had the wrong font all along?
=> Fix missing Roboto font in e-commerce demo

packages/ra-data-graphql-simple/src/buildGqlQuery.js, packages/ra-data-graphql-simple/src/buildGqlQuery.test.js
=> Fix ra-data-graphql-simple DELETE result

packages/ra-data-simple-rest/src/index.spec.ts, packages/ra-data-simple-rest/src/index.ts
=> Fix ra-data-simple-rest delete headers

examples/demo/package.json, examples/simple/package.json, examples/tutorial/package.json, packages/ra-core/src/controller/details/useCreateController.ts, packages/ra-core/src/controller/details/useEditController.ts, packages/ra-ui-materialui/package.json, packages/react-admin/package.json, yarn.lock
=> Fix Edit Notifications are not shown

docs/CreateEdit.md
=> [Doc] Fix create and edit controller usage documentation

examples/demo/src/layout/themes.ts, packages/ra-ui-materialui/src/defaultTheme.ts
=> Disable ripple effect

examples/data-generator/package.json, examples/data-generator/src/customers.ts
=> Fix data-generator avatars

packages/ra-ui-materialui/src/detail/index.ts
=> [TypeScript] Fix EditActionsProps type missing

packages/ra-data-simple-rest/src/index.spec.ts, packages/ra-data-simple-rest/src/index.ts
=> Fix ra-data-simple-rest delete method fails because of bad header

packages/ra-ui-materialui/src/auth/Login.tsx
We can't custom notification, so i decided to make this PR.
=> Add ability to customize the notification element in the Login page

packages/ra-ui-materialui/src/list/SimpleList.tsx
Added rowStyle example usage to SimpleList
=> Added rowStyle example usage to SimpleList

docs/Tutorial.md
- Fixed typo SelectIpnut -> SelectInput in two occurrences inside Tutorial documentation
=> Fix typos in Tutorial doc

docs/Actions.md
Optimistic Rendering and Undo section ApproveButton example is missing the 4th argument for previousData in useUpdate.
=> [Doc] Fix syntax in actions example for useUpdate.

packages/ra-core/src/dataProvider/useQueryWithStore.ts, packages/ra-ui-materialui/src/list/Empty.tsx, packages/ra-ui-materialui/src/list/ListView.tsx
Fixes #5637.
Supersedes #5641.
=> Fix Empty Component Display When No Create

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix select empty option in AutocompleteInput does not reset the input 

packages/ra-ui-materialui/src/layout/Notification.tsx
This is a left over from #5710
=> Change Notification's error color from dark to main

packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
=> Allow MenuItemLink to receive TooltipPops

packages/ra-ui-materialui/src/detail/CreateView.tsx, packages/ra-ui-materialui/src/detail/EditView.tsx
=> Fix DOM warning when using <Edit transform>

packages/ra-data-json-server/README.md, packages/ra-data-json-server/src/index.ts
=> [Doc] Fix ra-data-json-server getMany is documented as multiple getOne calls

packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
=> Fix findDOMNode warning in StrictMode when using SimpleformIterator

packages/ra-core/src/core/useResourceContext.ts
=> Fix EditGuesser is broken

examples/demo/src/reviews/ReviewEdit.tsx
=> Fix demo Review Edit warning due to missing EditContext

packages/ra-ui-materialui/src/defaultTheme.ts
It shouldn't be required as we merge the provided theme with our default anyway
=> Relax the Theme interface

packages/ra-ui-materialui/src/types.ts
This works with JS but is not allowed in TS.
=> typescript async transform

cypress/integration/list.js, cypress/support/ListPage.js, examples/simple/src/posts/PostList.js, packages/ra-core/src/auth/usePermissions.spec.tsx, packages/ra-core/src/auth/usePermissions.ts, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
Reverts marmelab/react-admin#4447
=> Revert "Add cache to usePermissions to avoid uncessessary render"

packages/ra-core/src/actions/notificationActions.ts, packages/ra-ui-materialui/src/layout/Notification.tsx
Reverts marmelab/react-admin#5710
=> Revert "Add support for success notification type"

packages/ra-ui-materialui/src/layout/Notification.tsx
Reverts marmelab/react-admin#5724
=> Revert "Change Notification's error color from dark to main"

packages/ra-core/src/controller/useListController.ts, packages/ra-ui-materialui/src/list/List.tsx, packages/ra-ui-materialui/src/list/ListView.tsx, packages/ra-ui-materialui/src/types.ts
=> Fix syncWithLocation DOM warnings when using List

packages/ra-ui-materialui/package.json, packages/react-admin/package.json, yarn.lock
=> Fix form.restart is not a function error

packages/ra-ui-materialui/src/button/DeleteButton.tsx
=> Fix DeleteButton mutationMode handling

docs/List.md, docs/Show.md
=> [Docs] Fix typo in `<List aside>` example

packages/ra-core/src/controller/useListController.ts
=> Fix error when using <List> outside of a ResourceContext

packages/ra-ui-materialui/src/button/CreateButton.tsx
Related issue [here](https://github.com/marmelab/react-admin/issues/5865)
https://user-images.githubusercontent.com/17087167/106920462-03212a00-6703-11eb-871c-b01875605a5d.mov
=> rerender Create button on disabled prop change

docs/CustomApp.md
Add missing theme prop to ThemeProvider
=> Fix missing props in CustomApp.md

packages/ra-ui-materialui/src/button/ShowButton.tsx
Same problem as CreateButton #5866
=> Re-render ShowButton component on disabled prop change

packages/ra-core/src/util/hooks.ts
=> [TypeScript] Fix compilation fails with @types/react@17

packages/ra-core/src/actions/notificationActions.ts, packages/ra-ui-materialui/src/layout/Notification.tsx
Related to #5710
This time I've only added the `succes` type
=> Add success notification type

docs/CreateEdit.md
It is true there is still a problem whit this (#5695) but at least the docs should point to the right direction plus avoiding an error
=> [Doc] Fix scrollable TabbedForm example

packages/ra-ui-materialui/src/input/NullableBooleanInput.spec.tsx, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
=> Fix NullabelBooleanInput Ignores defaultValue

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/index.ts
Closes https://github.com/marmelab/react-admin/issues/5985
https://user-images.githubusercontent.com/17087167/110091540-75cc0680-7d90-11eb-9086-3b9d86d3b1d7.mov
=> Bugfix: Prevent TS error on CheckboxGroupInput label styles

packages/ra-ui-materialui/src/form/index.tsx
=> Export TabbedFormView

packages/react-admin/README.md
Now, `src/Readme.md` and `src/packages/react-admin/Readme.md` are the same
=> Update react-admin Readme file with project one

packages/ra-core/src/dataProvider/useGetList.ts
=> [TypeScript] Fix useGetList return type assumes data and ids are possibly undefined

packages/ra-ui-materialui/src/input/ArrayInput.tsx
=> Add helperText to ArrayInput

packages/ra-ui-materialui/src/form/FormTab.tsx, packages/ra-ui-materialui/src/form/FormTabHeader.tsx
=> Add ability to use an element as label in `<FormTab>`

packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
=> Fix FilterLiveSearch Loose its Value

packages/ra-ui-materialui/src/list/SingleFieldList.tsx
=> [TypeScript] Fix <SingleFieldList component> doesn't accept string components

packages/ra-ui-materialui/src/layout/UserMenu.tsx
=> Fix UserMenu Display Over Appbar

packages/ra-ui-materialui/package.json
=> Fix `ra-ui-material-ui` depency verion on `ra-core`

packages/ra-ui-materialui/src/layout/UserMenu.tsx
=> Fix UserMenu hides the scrollbar

packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
=> Fix RadioButtonGroupInput Warnings

packages/ra-ui-materialui/src/list/Placeholder.tsx, packages/ra-ui-materialui/src/list/SimpleListLoading.tsx
=> Fix warnings when SimpleList displays skeleton while loading

packages/ra-ui-materialui/src/field/types.ts
=> Fix <Field textAlign> prop doesn't accept center 

docs/Admin.md, examples/simple/src/index.tsx, packages/ra-core/src/core/RouteWithoutLayout.tsx, packages/ra-core/src/core/index.ts
=> Add RouteWithoutLayout component to enable TS-compatible routes with noLayout

docs/Actions.md
fix typo in Legacy Components section l748
=> docs (Actions): fix `useDataProvider` instead of `useProvider`

packages/ra-ui-materialui/src/button/BulkDeleteButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
=> Fix warning when using BulkDeleteButton without props

packages/ra-ui-materialui/src/layout/Notification.tsx
=> Fix Notification component undo color

packages/ra-ui-materialui/src/layout/Notification.tsx
Reverts marmelab/react-admin#6189
=> Revert "Fix Notification component undo color"

packages/ra-core/src/dataProvider/useGetMany.spec.tsx, packages/ra-core/src/dataProvider/useGetMany.ts
=> Fix useGetMany Does Not Respect Enabled Option

packages/ra-ui-materialui/src/layout/Notification.tsx
=> Fix Notification undo button's color on success type

packages/ra-core/src/form/FormWithRedirect.tsx
=> Fix custom mutators crash SimpleForm and TabbedForm

docs/List.md
=> [Doc] Fix DatagridRow example

docs/_layouts/default.html, docs/css/style-v11.css
=> Fix Documentation Prism Theme

packages/ra-core/src/i18n/TranslationMessages.ts
https://github.com/marmelab/react-admin/commit/f6b1341750a636ba25d24b451a7bef472136a633#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
=> Fix missing type

docs/Actions.md, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useGetMainList.tsx, packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyReference.ts, packages/ra-core/src/dataProvider/useGetMatching.ts, packages/ra-core/src/dataProvider/useGetOne.ts, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-core/src/dataProvider/useQuery.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.ts
=> [Doc] Fix dataProvider hooks incorrectly document error state as loaded=true instead of false

examples/crm/src/companies/CompanyCard.tsx, packages/ra-ui-materialui/src/field/SelectField.tsx
Add TypographyProps to SelectFieldProps
=> [TypeScript] Fix SelectField doesn't accept Typography props

docs/Inputs.md
closes: https://github.com/marmelab/react-admin/issues/6279
=> Feature: Fix useCreateSuggestion type

packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx
=> TabbedShowLayoutProps's tabs prop marked as optional

docs/Translation.md
New maintainer for https://www.npmjs.com/package/ra-language-polish
=> Update PL translation maintainer

docs/Inputs.md
=> [Doc] Fix mention of non-existent fullWith attribute in SelectArrayInput

examples/no-code/src/main.tsx, packages/ra-no-code/src/ApplicationsDashboard/ApplicationsDashboard.tsx, packages/ra-no-code/src/ResourceConfiguration/ConfigurationInputsFromFieldDefinition.tsx, packages/ra-no-code/src/ResourceConfiguration/FieldConfigurationFormSection.tsx, packages/ra-no-code/src/ResourceConfiguration/ResourceConfigurationContext.ts, packages/ra-no-code/src/ResourceConfiguration/getFieldDefinitionsFromRecords.ts, packages/ra-no-code/src/Root.tsx, packages/ra-no-code/src/builders/Create.tsx, packages/ra-no-code/src/builders/Edit.tsx, packages/ra-no-code/src/builders/List.tsx, packages/ra-no-code/src/builders/ReferenceInputChildFromDefinition.tsx, packages/ra-no-code/src/builders/Show.tsx, packages/ra-no-code/src/builders/getFieldFromFieldDefinition.tsx, packages/ra-no-code/src/builders/getInputFromFieldDefinition.tsx
=> ra-no-code Add support for simple references

packages/ra-ui-materialui/src/layout/AppBar.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx, packages/ra-ui-materialui/src/layout/index.ts
=> [TypeScript] Add UserMenuProps

docs/Fields.md
Dear Repo owner, I have made the fix, let me know once you push it to live. 
Closes #6363
=> Fix for Issue: 6363, documentation fix

docs/List.md
=> [Doc] Fix ListBase snippet doesn't explain how to override the title

examples/demo/src/fakeServer/graphql.ts
=> [Demo] Improve dataProvider logging in GraphQL demo

docs/List.md
=> [Doc] Fix BulkUpdateButton example

packages/ra-ui-materialui/src/input/ResettableTextField.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix TS definition of SelectInput classes

packages/ra-core/src/i18n/TranslationMessages.ts
https://github.com/marmelab/react-admin/commit/c7e46cd880edb2b36eb4abbc53ecc9cb62cc4f6f#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
https://github.com/marmelab/react-admin/commit/9baee449c156eac00c58ad9a213096c8c94e1393#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
=> Fix missing types

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
=> Fix props.options.labelWidth not being applied in SelectArrayInput

packages/ra-core/src/sideEffect/useRedirect.spec.tsx, packages/ra-core/src/sideEffect/useRedirect.ts
=> Add support for absolute URLs in useRedirect

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-ui-materialui/src/button/DeleteButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/index.ts
Both buttons don't need the undoable prop
=> Fix delete buttons props types

packages/ra-ui-materialui/src/button/BulkExportButton.tsx
=> Fix propType warning in BulkExportButton

packages/ra-ui-materialui/src/input/TextInput.tsx
=> Fix SearchInput variant="outlined" has hole in the outline

packages/ra-ui-materialui/src/layout/Error.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx
=> [TypeScript] Fix Error prop types

packages/ra-core/src/types.ts
=> [RFR] Fix DataResult type

examples/demo/src/categories/CategoryList.tsx
=> [Demo] Fix implicit any type prevents TypeScript compilation

docs/DataProviders.md
=> [Doc] Fix outdated link to Django REST Framework dataProvider

docs/Inputs.md
=> [Doc] fix AutocompleteArrayInput doc for arrays of objects

examples/crm/package.json, examples/demo/package.json, examples/simple/package.json, examples/tutorial/package.json, packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx, packages/ra-ui-materialui/src/button/Button.spec.tsx, packages/ra-ui-materialui/src/button/CloneButton.spec.tsx, packages/ra-ui-materialui/src/button/CreateButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/layout/Confirm.tsx, packages/ra-ui-materialui/src/layout/DeviceTestWrapper.tsx, packages/ra-ui-materialui/src/layout/Notification.tsx, packages/ra-ui-materialui/src/layout/createMuiTheme.ts, packages/ra-ui-materialui/src/list/List.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx, packages/ra-ui-materialui/src/list/pagination/Pagination.spec.tsx, packages/ra-ui-materialui/src/list/pagination/Pagination.tsx, packages/ra-ui-materialui/src/list/pagination/PaginationActions.tsx, packages/react-admin/package.json, yarn.lock
And bump the minimal 'material-ui/core' version to 4.12
Closes #6451
=> Fix MUI 4.12 deprecation warnings

packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
=> Fix refresh view on undoable bulk actions failure

packages/ra-ui-materialui/src/detail/editFieldTypes.tsx, packages/ra-ui-materialui/src/form/index.tsx, packages/ra-ui-materialui/src/input/ArrayInput/AddItemButton.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInputContext.ts, packages/ra-ui-materialui/src/input/ArrayInput/ReOrderButtons.tsx, packages/ra-ui-materialui/src/input/ArrayInput/RemoveItemButton.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorContext.ts, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItemContext.ts, packages/ra-ui-materialui/src/input/ArrayInput/index.ts, packages/ra-ui-materialui/src/input/ArrayInput/useArrayInput.ts, packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIterator.ts, packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIteratorItem.ts, packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIteratorStyles.ts, packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/index.ts
=> Refactor arrayinput context

docs/Fields.md, docs/List.md, examples/crm/src/contacts/ContactEdit.tsx, examples/crm/src/deals/DealListContent.tsx, packages/ra-data-graphql-simple/README.md, packages/ra-data-graphql/README.md, packages/ra-language-english/README.md, packages/ra-language-french/README.md, packages/ra-ui-materialui/src/input/DateInput.spec.tsx
=> [Doc] Fix typos in several examples

packages/ra-core/src/core/RouteWithoutLayout.tsx, packages/ra-core/src/types.ts
=> Fix some types (DataProvider & RouteWithoutLayout)

packages/ra-ui-materialui/src/input/TranslatableInputs.tsx
=> Fix TranslatableInputs props interface

packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
=> Fix datagrid usage inside reference array input

docs/Theming.md, packages/ra-ui-materialui/src/layout/Menu.tsx
=> Fix custom menu

packages/ra-data-graphql-simple/src/getResponseParser.test.ts, packages/ra-data-graphql-simple/src/getResponseParser.ts
=> graphql: Fix Simple Response Parser Modify all Objects

packages/ra-data-graphql-simple/src/getResponseParser.test.ts
=> graphql - add test for embedded objects

packages/ra-data-graphql/src/index.ts
=> graphql - add basic network error handling

.storybook/main.js, package.json, yarn.lock
=> Fix storybook

packages/ra-ui-materialui/src/button/DeleteButton.tsx
=> Fix include side effects in `DeleteButton` props type

package.json, yarn.lock
This initially addressed a security warning on a dev package, but ended up manually deduplicating packages... and reducing lock file by 5%.
=> Reduce package duplication

packages/ra-core/src/form/useWarnWhenUnsavedChanges.spec.tsx, packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
=> Fix SimpleForm warns of unsaved changes when the form is submitting

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
=> Fix useReferenceArrayInputController sets loading prop incorrecly

packages/ra-ui-materialui/src/layout/index.ts
=> Fix export missing components

packages/ra-ui-materialui/src/list/ListView.tsx, packages/ra-ui-materialui/src/types.ts
=> Fix List bulkActionButtons prop does not handle the value true

docs/Authentication.md
=> [Doc] Fix authProvider example

packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
Adds a class to RaFilterListItem to be able to override the makeStyles with my own team
=> [RFR] Adds RaFilterListItem class

docs/DataProviders.md
Hi guys! I would like to share a new data provider compatible with react-admin. This one is built for the awesome `blitzjs` framework, and utilizes it's underlying RPC API, making CRUD apps truly effortless.
Hope you like it, cheers!
=> [DOC] Add blitzjs data provider

packages/ra-no-code/src/Admin.spec.tsx
This test is quite long and may take more than 10s depending on the machine running it
=> Fix unstable ra-no-code test

.eslintrc, .gitattributes
=> fixed npm run build errors by changing eslint rules for crlf

docs/Admin.md, packages/ra-core/src/core/CoreAdmin.tsx, packages/ra-core/src/core/CoreAdminContext.tsx, packages/ra-core/src/types.ts, packages/react-admin/src/Admin.tsx
=> Add support for router basename

jest.config.js, package.json
This really helps in not re-building packages at testing time
=> Backport jest config from next

packages/ra-ui-materialui/src/list/ListActions.tsx
=> Fix ListActions useMemo dependencies

.gitattributes
This file is not supposed to be in next: https://github.com/marmelab/react-admin/pull/7000/files#r770407535
=> Fix Remove file

packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyAggregate.ts
**Problem:**
`ReferenceField` render can take up to several milliseconds when react-query cache contains large number of records (hundreds, thousands).
**Steps to reproduce:**
Load a datagrid with large number of `ReferenceField`s (e.g. more than a hundred per page), switch between pages to populate the cache. When the query cache grows to several hundreds/thousands records switching between pages will start feeling sluggish. `ReferenceField`s that refer to an already cached data will take visible amount of time to update in response to page changes.
**What's causing this:**
`useGetMany` and `useGetManyAggregate` prepare `placeholderData` to be displayed why `useQuery` is running. To do that they call `QueryClient.getQueryData(queryKey)`. This is reasonable and idiomatic usage, but …
=> Fast cache lookup for useGetMany(Aggregate) placeholderData

packages/ra-core/src/sideEffect/useRedirect.ts
=> Fix redirect false after save doesn't clear the form

packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
=> Fix BulkDeleteWithConfirm doesn't close confirm dialog

packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
=> Fix BulkDeleteWithUndoButton fails when used twice fast

cypress/integration/edit.js, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteSuggestionItem.tsx
=> Fix AutocompleteArrayInput  optionText function not supported with create item set

packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
=> Fix SelectArrayInput optionText function not fully supported with create item

docs/DataProviders.md
Hi!
Fixing dead link as we have migrated to TypeScript =]
Thanks!
=> Fix dead link in DataProviders.md

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix SelectInput css styles definition

packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
Reference: https://github.com/marmelab/react-admin/pull/7071#discussion_r784109458
=> Fix ReferenceArrayField styling

packages/ra-ui-materialui/src/layout/Notification.tsx
=> [4.0.0-alpha.2] Fix Notification CSS classes not being applied

examples/demo/src/layout/Menu.tsx, packages/ra-ui-materialui/src/defaultTheme.ts, packages/ra-ui-materialui/src/layout/Menu.tsx
=> [4.0.0-alpha.2] Fix Menu default width when closed

packages/ra-core/src/controller/list/useList.ts
This was causing an infinite re-render on `FilterList` story
=> [4.0.0-alpha.2] Fix useList's useEffect deps

packages/ra-core/src/auth/useLogout.ts
=> Fix race condition accessing redux store after logout

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> [4.0.0-alpha.2] Fix `AutocompleteInput` invalid empty option

UPGRADE.md, docs/CreateEdit.md
=> [4.0.0-alpha.2] Add bulkActionButtons change to upgrade guide

packages/ra-core/src/types.ts
=> Fix Resource prop types

.github/workflows/test.yml
Build both the e-commerce and crm demos on the CI to catch more issues
=> Builds the demos on CI

UPGRADE.md, examples/crm/src/companies/CompanyCard.tsx, examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/companies/GridList.tsx, examples/crm/src/contacts/Avatar.tsx, examples/crm/src/contacts/ContactList.tsx, examples/crm/src/contacts/TagsList.tsx
=> [4.0.0alpha.2] Demos fix useRecordContext usage

examples/demo/src/App.tsx, packages/ra-ui-materialui/src/layout/AppBar.tsx, packages/ra-ui-materialui/src/layout/CardActions.tsx, packages/ra-ui-materialui/src/layout/CardContentInner.tsx, packages/ra-ui-materialui/src/layout/Confirm.tsx, packages/ra-ui-materialui/src/layout/Error.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/LinearProgress.tsx, packages/ra-ui-materialui/src/layout/Loading.tsx, packages/ra-ui-materialui/src/layout/LoadingIndicator.tsx, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/MenuItemLink.tsx, packages/ra-ui-materialui/src/layout/NotFound.tsx, packages/ra-ui-materialui/src/layout/Notification.tsx, packages/ra-ui-materialui/src/layout/Sidebar.tsx, packages/ra-ui-materialui/src/layout/SidebarToggleButton.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx
Adding theme override support is more complicated than we thought and require more code.
We'll add more components once we have an answer to the following SO question: https://stackoverflow.com/questions/70927246/theme-override-support-for-custom-components
Fixes #7164, #7079
=> Fix theming regressions

UPGRADE.md
=> Document the change in custom form inputs in upgrade guide

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> [4.0.0-alpha3] Fix SelectInput proptypes

packages/ra-ui-materialui/src/layout/Notification.tsx
=> Fix notifications multiLine not working via useNotify hook

packages/ra-ui-materialui/src/button/DeleteButton.tsx
=> Fix DeleteButton does not appear in Datagrid

UPGRADE.md, packages/ra-core/src/form/useInput.ts, packages/ra-ui-materialui/src/input/BooleanInput.tsx
=> [4.0.0-alpha.3] Change BooleanInput's onChange signature

examples/demo/package.json, examples/demo/src/dashboard/OrderChart.tsx, examples/demo/src/layout/Menu.tsx, examples/demo/src/layout/themes.ts, packages/ra-core/src/store/useResetStore.ts, packages/ra-core/src/util/useEventCallback.ts, yarn.lock
=> Fix demo glitches

packages/ra-ui-materialui/src/detail/Tab.tsx
=> [4.0.0-alpha.3] Allow Tab label to be a react element

packages/ra-core/src/form/useInput.ts
=> Fix empty values treated as undefined in parse function

docs/FilteringTutorial.md
Adding this doc show that #7122 isn't required.
=> Add documentation about filter operators

packages/ra-core/src/types.ts
=> [4.0.0-alpha.3] Make DataProvider type generic over resource

packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/input/BooleanInput.stories.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, yarn.lock
=> Add CheckboxGroupInput stories

packages/ra-core/src/dataProvider/getFetchType.ts
=> Fix bad imports

packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/controller/saveContext/SaveContext.ts
=> Fix Form save handler return type

packages/ra-ui-materialui/src/field/ReferenceField.tsx
=> Fix missing `ReferenceField` children's link color

docs/Tutorial.md
maybe this part was missed in doc when switched to mui v5.
I am relearning how to get themes and styles working again.
=> [v4 b1 doc] fix customizing styles in tutorial

examples/crm/src/Header.tsx, packages/ra-ui-materialui/src/layout/LoadingIndicator.tsx
=> Fix LoadingIndicator

UPGRADE.md
=> Update upgrade guide for ArrayField

packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
=> Fix BulkUpdateButton color

packages/ra-ui-materialui/src/list/filter/Filter.spec.tsx, packages/ra-ui-materialui/src/list/filter/Filter.tsx
=> Fix Filter Element Make List Unusable

docs/Buttons.md, packages/ra-ui-materialui/src/button/Button.tsx, packages/ra-ui-materialui/src/button/DeleteButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
=> Add `translateOptions` prop to `DeleteWithConfirmButton`

examples/simple/src/i18n/en.ts, examples/simple/src/i18n/fr.ts
=> Add missing i18n keys in simple project

docs/CreateEdit.md
The entire CreateEdit.md needs some work
=> Fix margin and variant references

examples/simple/src/authProvider.tsx, packages/ra-ui-materialui/src/auth/LoginForm.tsx
https://user-images.githubusercontent.com/99944/156754223-e7a2d2e1-99b6-44fc-853a-e5dd03482312.mov
https://user-images.githubusercontent.com/99944/156754091-ed2f9a01-eb57-4d07-9554-e9b7734e0809.mov
=> Tweak default login form UI

packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
Fixes #7337
**Before**
**After**
=> Fix menus loosing active status on redirect

UPGRADE.md, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx, packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
Fixes #7191
Also remove the `margin` and `variant` props injection
=> Fix Wrong Default Value Handling in FilterForm

packages/ra-core/src/store/localStorageStore.ts
=> Fix window is not defined error

examples/demo/src/categories/CategoryEdit.tsx, examples/demo/src/categories/CategoryList.tsx, examples/demo/src/categories/LinkToRelatedProducts.tsx, examples/demo/src/configuration/Configuration.tsx, examples/demo/src/configuration/actions.ts, examples/demo/src/dashboard/Dashboard.tsx, examples/demo/src/dashboard/NewCustomers.tsx, examples/demo/src/dashboard/PendingOrder.tsx, examples/demo/src/dashboard/PendingOrders.tsx, examples/demo/src/dashboard/PendingReviews.tsx, examples/demo/src/invoices/InvoiceList.tsx, examples/demo/src/invoices/InvoiceShow.tsx, examples/demo/src/layout/AppBar.tsx, examples/demo/src/layout/Login.tsx, examples/demo/src/layout/Menu.tsx, examples/demo/src/orders/Basket.tsx, examples/demo/src/orders/MobileGrid.tsx, examples/demo/src/orders/OrderEdit.tsx, examples/demo/src/orders/OrderList.tsx, examples/demo/src/orders/TableCellRight.tsx, examples/demo/src/orders/Totals.tsx, examples/demo/src/visitors/Aside.tsx, examples/demo/src/visitors/FullNameField.tsx, examples/demo/src/visitors/VisitorEdit.tsx, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useIsDataLoaded.ts, packages/ra-ui-materialui/src/field/BooleanField.spec.tsx, packages/ra-ui-materialui/src/field/BooleanField.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx
=> Make e-commerce demo canonical 

docs/List.md
=> [Docs] Fix Datagrid example

packages/ra-ui-materialui/src/auth/Login.tsx
To be able to change the style of the login page.
=> fix: add missing sx prop type on Login

docs/Datagrid.md, packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
=> make datagrid row not clickable if rowClick returns false

.storybook/main.js, examples/simple/index-webpack.html, examples/simple/package.json, examples/simple/webpack.config.js, package.json, yarn.lock
https://codesandbox.io/s/github/marmelab/react-admin/tree/upgrade-webpack/examples/simple
=> Fix codesandbox for beta

UPGRADE.md, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
=> Fix Datagrid hasBulkActions mention in the Upgrade guide

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
=> Fix default styles of `SelectArrayInput`

packages/ra-ui-materialui/src/list/ListView.tsx
=> Fix List when dataProvider.getList returns an error

UPGRADE.md, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
=> Remove Transitions From SimpleFormIterator

packages/ra-core/src/routing/index.ts
=> Add missing exports

packages/ra-core/src/controller/list/useListParams.ts, packages/ra-core/src/util/hooks.ts
Closes #7368
Supersedes #7416, #7440
=> Fix race condition due to debounced setFilter

packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
=> Fix FilterForm reset

docs/Datagrid.md, packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
=> Prevent Datagrid rowClick function to be called on mount 

packages/ra-core/src/dataProvider/useCreate.ts
=> Fix useCreate params type

packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyAggregate.spec.tsx, packages/ra-core/src/dataProvider/useGetManyAggregate.ts
Closes #7458, #7438
Supersedes #7467
=> Fix useGetManyAggregate makes useless calls

packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
=> Fix ReferenceManyInput in FilterForm

packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
=> Fix FilterLiveSearch doesn't accept outlined variant

packages/ra-core/package.json
=> Fix history dependency

examples/simple/src/posts/PostCreate.tsx, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/FileInput.spec.tsx
=> Add isDirty state prop in the SaveButton disable logic

docs/Admin.md, packages/ra-core/src/core/CoreAdminRoutes.spec.tsx, packages/ra-core/src/core/CoreAdminRoutes.tsx
=> Fix custom routes not accessible by anonymous users

packages/ra-core/src/controller/record/useRecordContext.ts
=> Fix useRecordContext return type

docs/css/style-v11.css
https://user-images.githubusercontent.com/8268610/162437422-28891b5e-3822-4636-9d6f-3ba66fae24ca.mov
=> Make docs navbar fixed in mobile

docs/css/style-v11.css
=> Fix premium image shadow on mobile

packages/ra-core/src/util/hooks.ts
=> Fix list actions don't trigger a refetch

docs/Admin.md, packages/react-admin/src/Admin.tsx
Update docs & docblock.
fixes #7520
=> docs(Admin): document i18nprovider and store for AdminContext

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
=> Fix ArrayInput's form value set to undefined on unmount

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput Infinite Loop On Clear

packages/ra-core/src/form/getSimpleValidationResolver.spec.ts, packages/ra-core/src/form/getSimpleValidationResolver.ts
=> Allow arrays as field values in validator resolver

docs/Datagrid.md
=> [Doc] Fix Datagrid body snippet is missing RecordContextProvider

packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
=> Fix fullWidth prop sanitation error

docs/Upgrade.md
=> Update ListViews example to use RaRecord type

packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
=> Fix filter list race condition

docs/BooleanInput.md, docs/Upgrade.md, packages/ra-ui-materialui/src/input/BooleanInput.stories.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx
=> Fix BooleanInput props

packages/ra-ui-materialui/src/input/FileInput.tsx
=> Fix FileInput doesn't accept options prop

packages/ra-ui-materialui/src/list/SingleFieldList.tsx
=> Fix duplicate key error in SingleFieldList

docs/Edit.md
=> [Doc] Fix Edit component mentions unsupported prop

packages/ra-ui-materialui/src/input/FileInput.tsx
=> Fix FileInput name And id Props

packages/ra-ui-materialui/src/button/Button.tsx
We should support additional colors and custom palettes.
=> Fix button color warning

docs/Create.md
=> Fix Prefilling the Form example

packages/ra-ui-materialui/src/layout/DashboardMenuItem.tsx
I'd like to be able to change the menu icon for the dashboard.
=> Changeable icon for DashboardMenuItem

packages/ra-ui-materialui/src/layout/Loading.tsx
Fixes https://github.com/marmelab/react-admin/issues/7706
=> Add sx prop to Loading component

docs/Theming.md
Fixes a missing key in global theme overrides.
relates to #7604
=> Fix global theme overrides example in docs

packages/ra-core/src/core/useConfigureAdminRouterFromChildren.spec.tsx, packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
=> Fix useConfigureAdminRouterFromChildren when child function return null

docs/SelectArrayInput.md
=> Fix SelectArrayInput Documentation

docs/ReferenceArrayInput.md
Reverts marmelab/react-admin#7751
=> Revert "chg: :memo: Remove label from ReferenceArrayInput"

packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
=> Fix user cannot to load saved queries when alwaysOn filters are empty

docs/Theming.md
Fixes https://github.com/marmelab/react-admin/pull/7799#discussion_r893150837
=> Fix typo in doc update for useRecordContext

docs/DataProviderList.md
ra-data-treeql changed it's location.
See discussion @ itsjavi/ra-admin-guesser-treeql#2 for further information
=> Updated location of ra-data-treeql

packages/ra-ui-materialui/src/field/ImageField.tsx
=> Fix ImageField style is lost for single images

packages/ra-ui-materialui/src/field/FileField.tsx, packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/ImageInput.tsx
Add default MUI style to both components
=> Polish  `FileInput`and `ImageInput` font family, border-radius and color

packages/ra-ui-materialui/package.json
=> Fix css-mediaquery Dependency

packages/ra-ui-materialui/package.json, yarn.lock
=> Fix useFormState returns null with yarn pnp

docs/Buttons.md, docs/Theming.md
Fix https://github.com/marmelab/react-admin/issues/7898
=> [Documentation] Correct RaMenuItemLink active state configuration

packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.tsx
=> Fix ReferenceArrayInput does not fetch defaultValues applied on its child

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput Should Show Options After Selection

packages/ra-core/src/controller/index.ts, packages/ra-core/src/controller/useListPaginationContext.ts, packages/ra-ui-materialui/src/list/pagination/Pagination.spec.tsx, packages/ra-ui-materialui/src/list/pagination/Pagination.tsx
Fixes #7955  for 3.x version based on #7956
=> Fix <Pagination> cannot be used outside a ListContext for 3.x

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
=> Fix NumberInput field state isTouched is always false

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix SelectInput resettable background color glitch

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
=> Fix usage warning trigger in `CheckboxGroupInput`

packages/ra-ui-materialui/src/layout/DashboardMenuItem.tsx
=> Fix DashboardMenuItem Types

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput generates warning for identical label

examples/demo/src/categories/CategoryList.tsx
=> Fix: Update CategoryList to use RecodContext

examples/demo/src/dashboard/CardWithIcon.tsx, examples/demo/src/dashboard/PendingReviews.tsx
https://user-images.githubusercontent.com/18294269/182816921-32f7c5bc-75bf-47ca-90fd-50e5fc017dd0.mp4
=> Feat: Add filter redirection for pending reviews

docs/Store.md, packages/ra-core/src/store/localStorageStore.spec.tsx, packages/ra-core/src/store/localStorageStore.ts
Fix #7752
When you have multiple react-admin apps under the same domain, they'll share the same store which can lead to issues (one of them being the menu might be collapsed in an app that doesn't even have the toggle menu button).
=> [Fix] Add localStorage application key

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
=> Fix FormDataConsumer inside SimpleFormIterator adds empty value

docs/ReferenceInput.md
=> [Doc] Fix ambiguity about ReferenceInput label prop

packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
=> Fix ReferenceManyField record selection logic

packages/ra-ui-materialui/src/layout/HideOnScroll.tsx
=> Apply className prop to AppBar container

packages/ra-core/src/form/index.ts, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
Fixes #8190 
https://user-images.githubusercontent.com/41492953/192263783-f72b96ec-c706-4d4f-8298-3747dc924704.mov
=> Fix: FormTab not turning red after ArrayInput global validation error

packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx
=> Fix: <ReferenceField> generates a link even though there is nothing to link to

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
=> Add missing test for SimpleFormIterator

package.json, packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx, packages/ra-ui-materialui/src/list/BulkActionsToolbar.tsx, yarn.lock
- Updated lerna from 5.1 to 5.5
- Updated TypeScript from 4.5 to 4.8
=> Fix development dependencies causing security alerts

docs/RichTextInput.md
=> [Doc] Fix RichTextInput example

docs/Upgrade.md
=> Add upgrade information about Field in SimpleForm

packages/ra-core/src/dataProvider/index.ts
=> Fix useGetRecordId missing export

docs/Create.md, docs/CreateDialog.md, docs/CreateInDialogButton.md, docs/Edit.md, docs/EditDialog.md, docs/EditInDialogButton.md, docs/EditTutorial.md, docs/ShowInDialogButton.md, docs/navigation.html
The doc was a bit short, and hard to discover. I added cross-links and a bit more details. 
Follows #8271
=> [Doc] Fix links to EditInDialogButton and CreateInDialogButton

docs/Store.md
=> Fix documentation about localStorageStore

packages/ra-ui-materialui/src/button/RefreshIconButton.tsx, packages/ra-ui-materialui/src/button/ToggleThemeButton.tsx, packages/ra-ui-materialui/src/layout/SidebarToggleButton.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx
Reverts marmelab/react-admin#8350
=> Revert "Fix buttons props"

examples/no-code/package.json
- https://codesandbox.io/s/github/marmelab/react-admin/tree/fix-no-code-codesandbox/examples/no-code works, while
- https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/no-code doesn't work
Closes #7453
=> Fix no-code example codesandbox

packages/ra-ui-materialui/src/field/ReferenceManyField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
=> Fix ReferenceManyField does not show pagination when using partial pagination

packages/ra-input-rich-text/src/RichTextInput.tsx
=> Fix RitchTextInput cursor moves to the end while typing

packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.stories.tsx, packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
=> Fix `SelectColumnsButton` not being responsive

docs/Datagrid.md
=> [Doc] Fix improve `List` actions prop in `DatagridConfigurable` example

packages/ra-ui-materialui/src/form/SimpleForm.tsx, packages/ra-ui-materialui/src/form/TabbedForm.tsx
=> Fix remove old record prop references from Form components

packages/ra-ui-materialui/src/list/BulkActionsToolbar.tsx
=> Fix BullkActionButtons positioning

docs/Admin.md, docs/AuthProviderWriting.md, docs/Authentication.md
=> [Doc] Improve instructions for setting up a redirection url for third-party auth

packages/ra-core/src/form/useWarnWhenUnsavedChanges.spec.tsx, packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
Fixes https://github.com/marmelab/react-admin/issues/8338
=> Fix `warnWhenUnsavedChanges` when navigating to Show view

docs/useList.md
=> [Doc] Fix `useList` hook doc contains wrong examples

docs/DateTimeInput.md
Fixes https://github.com/marmelab/react-admin/issues/8548
=> [no ci] [Doc] Better explain how to build a `parse` fn with `DateTimeInput`

packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
Avoid application crash when the value is not an array
=> Make SelectArrayInput more resilient

docs/Community.md, docs/navigation.html
- Community page doesn't emphasize Discord server enough
- Community page misses links to dependencies
- Community page duplicates content from 'advanced tutorials' page
Make it better.
=> [Doc] Improve the community page

docs/Features.md, docs/FilteringTutorial.md, docs/ListTutorial.md, docs/NumberInput.md, docs/Realtime.md, docs/Reference.md, docs/SavedQueriesList.md, docs/SimpleList.md, docs/StackedFilters.md, docs/navigation.html, docs/useStore.md, packages/ra-core/src/store/useStore.ts, packages/ra-ui-materialui/src/button/BulkDeleteButton.tsx, packages/ra-ui-materialui/src/button/BulkExportButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx, packages/ra-ui-materialui/src/list/List.tsx, packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/filter/Filter.tsx
Doc ported and adapted from ra-form-layout
=> [Doc] Add StackedFilters chapter

packages/ra-core/src/controller/list/useList.spec.tsx, packages/ra-core/src/controller/list/useList.ts
=> Fix useList filter option not working with nested objects

docs/Breadcrumb.md, docs/Resource.md
=> [Doc] Add section about nested resources in `<Breadcrumb>` documentation.

packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
=> Fix Datagrid unselectable rows should show a disabled checkbox

docs/Remix.md
=> [doc] Fix Remix installation instructions

examples/simple/src/posts/PostCreate.tsx, packages/ra-ui-materialui/src/form/SimpleForm.tsx
=> Fix Save tool bar hiding content on mobile

docs/CheckboxGroupInput.md
=> [Doc] Improve CheckboxGroupInput translateChoice code example

packages/ra-ui-materialui/src/field/ArrayField.spec.tsx, packages/ra-ui-materialui/src/field/ArrayField.tsx
Fix https://github.com/marmelab/react-admin/issues/8658
=> Fix ArrayField breaking when value is null

docs/Routing.md
We have many people complaining about issues with the router - we should make the solution easier to find.
=> [Doc] Add troubleshooting section to Routing chapter

docs/Upgrade.md, examples/demo/src/layout/AppBar.tsx
=> [Doc] Fix `MenuItem` example usage in Upgrade guide

packages/ra-ui-materialui/src/preferences/Configurable.tsx
Closes #8418
https://mui.com/material-ui/api/modal/#props
=> Fix cannot edit a text field in the Inspector

docs/css/style-v14.css
=> [Doc] Fix Algolia popup style

packages/ra-ui-materialui/src/button/CreateButton.tsx, packages/ra-ui-materialui/src/button/ShowButton.tsx
=> Include the `to` prop in memoization check of `<CreateButton>` and `<ShowButton>`

README.md
Modified some of the language in the README for clarity and grammatical flow. Replaced ` - ` with em dashes (`—`) where appropriate.
=> Fix: Update grammar in README.md

docs/Reference.md
Little fix from https://github.com/marmelab/react-admin/pull/8681#discussion_r1147860491
=> [Docs] fix index page links

docs/FilterList.md
Making the filter customization more readable.
=> Update FilterList documentation with coherent example

docs/WithRecord.md
=> [Doc] Fix WithRecord usage in Datagrid to remind the label requirement

docs/DataProviderList.md
Hi there!
I have recently updated the data provider for StrapiJS to make it work with the latest version. It works with v3 and v4 now. Also, created a demo repo for reference. Can we please add the "v4" as well to it. Thank you!
=> Update DataProviderList.md with ra-strapi-rest v4

docs/Count.md, docs/FilteringTutorial.md
First ever PR on an open source project, lmk if there's anything I did wrong
=> [Doc] fix import statements in example code

docs/ReferenceField.md, packages/ra-core/src/controller/useReference.ts, packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx
Implements #8891
Supersedes #8892 (I messed up the other PR)
=> Add `queryOptions` prop to `ReferenceField`

docs/_layouts/default.html, docs/css/style-v16.css, docs/documentation.html
Fixes: https://github.com/marmelab/react-admin/issues/7589
Supersedes https://github.com/marmelab/react-admin/pull/8778
=> [Doc] Allow TOC sidebar to scroll vertically

packages/ra-ui-materialui/src/button/SaveButton.stories.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx
=> Fix `<SaveButton>` spinner while submitting

packages/ra-ui-materialui/src/field/RichTextField.spec.tsx, packages/ra-ui-materialui/src/field/RichTextField.tsx, packages/ra-ui-materialui/src/field/TextField.spec.tsx, packages/ra-ui-materialui/src/field/TextField.tsx
=> Fix `<TextField>` and `<RichTextField>` don't translate the `emptyText`

packages/ra-core/src/controller/create/CreateBase.tsx, packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/types.ts, packages/ra-data-localforage/src/index.ts, packages/ra-data-localstorage/src/index.ts, packages/ra-ui-materialui/src/detail/Create.tsx, packages/ra-ui-materialui/src/types.ts
=> Fix Create generic record type

packages/ra-ui-materialui/src/field/ReferenceField.tsx
=> Fix `<ReferenceField>` line height isn't consistent with other fields

packages/ra-ui-materialui/src/list/ListView.tsx
=> Fix ListView does not apply CSS classes to its child components

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/input/TextInput.tsx, packages/ra-ui-materialui/src/input/TimeInput.tsx
=> Prevent render InputHelperText if helperText props is false in Input components

packages/ra-ui-materialui/src/button/DeleteButton.stories.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
=> Fix delete button style

docs/Community.md, docs/_includes/newsletter.html, docs/_layouts/default.html, docs/css/newsletter.css, docs/documentation.html
=> [Doc] Add newsletter form

examples/simple/src/tags/TagEdit.tsx, packages/ra-ui-materialui/src/list/List.tsx
=> Fix remove unsupported propTypes

docs/_layouts/default.html, docs/documentation.html, docs/js/ra-doc-exec.js
Backport of https://github.com/marmelab/react-admin/pull/9121 to `master`
=> [Website] Fix newsletter script loading in doc pages - backport to  `master`

packages/ra-ui-materialui/src/field/FileField.tsx
Fix https://github.com/marmelab/react-admin/issues/9125
=> Fix `<FileField>` should not propagate click

packages/ra-core/src/controller/input/useReferenceInputController.ts, packages/ra-ui-materialui/src/detail/EditView.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.stories.tsx
=> Fix `<ReferenceInput queryOptions>` does not apply to getMany query

packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts, packages/ra-core/src/types.ts, packages/ra-data-json-server/src/index.ts
=> Fix withLifecycleCallbacks types

index.html, landing-page/index.html
Fix the following error in the landing pages:
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "video/mp2t".  Strict MIME type checking is enforced for module scripts per HTML spec.
Also, fix the video URL for the CRM demo.
Lastly, fixed a discrepancy in Sib Form labels between `landing-page/index.html` and `index.html`.
=> Website: Fix mimetype error in landing page

docs/List.md, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
=> [Doc] Fix `<List actions>` example throws an error

packages/ra-ui-materialui/src/list/BulkActionsToolbar.tsx
=> Fix bulk actions toolbar styling issue on mobile

packages/ra-ui-materialui/src/input/BooleanInput.stories.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInputItem.tsx, packages/ra-ui-materialui/src/input/NumberInput.stories.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
=> Fix `<NumberInput>` and `<BooleanInput>` programmatic focus

docs/RichTextInput.md
Just added a missing `x` letter
=> Fix typo in RichTextInput.md

docs/Admin.md, docs/Architecture.md, docs/EditTutorial.md, docs/Features.md, docs/Fields.md, docs/Inputs.md, docs/Tutorial.md
=> [Doc] Fix typos on Admin, Architecture, EditTutorial, Features, Fields, Inputs, and Tutorial pages

docs/Features.md
=> [Doc] Fix typo in Features example

.github/workflows/codeql-analysis.yml
Due to code analysis error (https://github.com/marmelab/react-admin/actions/runs/6219662400/job/16878156161), Update the action version
=> [Actions] Update code analysis version

examples/demo/src/reviews/ReviewListMobile.tsx
|---|---|
| ![localhost_8000_ (1)](https://github.com/marmelab/react-admin/assets/99944/f76de510-acd3-4db8-80b9-32b8069898b4) | ![localhost_8000_](https://github.com/marmelab/react-admin/assets/99944/009380af-c0ba-4f08-9ed5-a975713d97e2) |
=> [Demo] Fix ReviewList shows horizontal scrollbar on mobile

packages/ra-core/src/dataProvider/useCreate.spec.tsx, packages/ra-core/src/dataProvider/useCreate.ts
=> Fix `useCreate` does not refresh the list cache

docs/Datagrid.md, docs/SelectColumnsButton.md
Improvements suggested by https://stackoverflow.com/a/77001801/3975522
=> [Doc] Make adding a label to unlabeled columns in `DatagridConfigurable` more discoverable

packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
Reverts marmelab/react-admin#9357
=> Revert "Added type for `mutationMode` to `mutationOptions` prop for <BulkDeleteWithUndoButton>"

docs/StackedFilters.md
Improve StackedFilters documentation
=> doc: improve StackedFilters documentation

packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
Fix https://github.com/marmelab/react-admin/issues/9368
=> Fix `<SelectColumnsButton>` throws errors when reordering the columns

docs/AuthProviderList.md
https://github.com/raphiniert-com/ra-data-postgrest/issues/105
=> [doc] Removed postgrest from auth providers, see #105 of ra-data-postgrest

examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/companies/GridList.tsx, examples/crm/src/contacts/ContactEdit.tsx, examples/crm/src/contacts/ContactList.tsx, examples/crm/src/contacts/ContactShow.tsx, examples/crm/src/contacts/TagsListEdit.tsx, examples/crm/src/dashboard/DealsChart.tsx, examples/crm/src/dashboard/DealsPipeline.tsx, examples/crm/src/dashboard/HotContacts.tsx, examples/crm/src/dashboard/LatestNotes.tsx, examples/crm/src/deals/ContactList.tsx, examples/crm/src/deals/DealListContent.tsx, examples/crm/src/notes/NotesIterator.tsx, examples/demo/src/categories/CategoryList.tsx, examples/demo/src/dashboard/PendingOrder.tsx, examples/demo/src/dashboard/PendingReviews.tsx, examples/demo/src/orders/Basket.tsx, examples/demo/src/orders/MobileGrid.tsx, examples/demo/src/products/GridList.tsx, examples/demo/src/reviews/ReviewListMobile.tsx, examples/demo/src/visitors/MobileGrid.tsx, examples/simple/src/customRouteLayout.tsx, packages/ra-core/src/controller/list/useListController.ts, packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
Following #9473, we should use `isPending` in our demos (even though `isLoading` still works) as it's the best practice.
=> [Demo] Migrate `isLoading` to `isPending`

docs/MarkdownField.md
Improve MarkdownField doc by adding a screenshot
=> Doc: Improve MarkdownField doc

docs/DataProviderList.md
Add dataProvider to documentation.
=> Add LinuxForHealth FHIR to DataProviderList.md

packages/ra-ui-materialui/src/input/FileInputPreview.tsx
=> Fix FileInputPreview propTypes

Makefile
=> Fix `ra-i18n-i18next` broken package

packages/ra-ui-materialui/src/preferences/FieldToggle.tsx
so custom styles can be applied via theme
=> Fix FieldToggle cannot be styled using the application theme

docs/FilteringTutorial.md, docs/List.md, docs/useListContext.md, docs/useListController.md
=> [Doc] Add warning about using setFilters with other callbacks

docs/AuthProviderList.md
Images in AuthProviderList doc page couldn't load
Use relative path instead of absolute
=> [Doc] fix authProvider images

package.json, yarn.lock
Should fix https://github.com/marmelab/react-admin/security/dependabot/97
Seems like this dependency was not used for anything :shrug: 
(I have tested building, running the storybook and running the simple demo)
=> [chore] Remove unused dependency on wait-on

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
=> Fix Autocomplete loses focus on select

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
=> Fix AutocompleteArrayInput triggers an infinite loop when disabled

packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
This PR attempts to add MUI `variant` support for `<FilterButton>`
=> Add support of variant prop for FilterButton

landing-page/index.html
The ra-enterprise website has a new domain. This PR updates all the links in the landing page
=> Update landing page link to react-admin enterprise edition

packages/ra-ui-materialui/src/AdminContext.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkExportButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/IconButtonWithTooltip.tsx, packages/ra-ui-materialui/src/button/SortButton.tsx, packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/UpdateWithUndoButton.tsx, packages/ra-ui-materialui/src/detail/CreateActions.tsx, packages/ra-ui-materialui/src/detail/EditActions.tsx, packages/ra-ui-materialui/src/detail/EditView.tsx, packages/ra-ui-materialui/src/detail/ShowActions.tsx, packages/ra-ui-materialui/src/detail/ShowView.tsx, packages/ra-ui-materialui/src/list/Count.stories.tsx, packages/ra-ui-materialui/src/list/Count.tsx, packages/ra-ui-materialui/src/list/Empty.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridLoading.tsx, packages/ra-ui-materialui/src/list/datagrid/ExpandAllButton.tsx, packages/ra-ui-materialui/src/types.ts
Decrease TS compilation errors in strictNullChecks mode from 216 to 164.  Small steps.
=> [TypeScript] Make types more strict in ra-ui-materialui

packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
The  `<Basic>` of `<SimpleList>` is broken
Provide a resource context
=> Fix `<SimpleList>` `<Basic>` story

examples/crm/package.json, examples/crm/vite.config.ts, examples/demo/package.json, examples/demo/vite.config.ts, yarn.lock
Fixed the warnings about MUI sourcemap by following https://github.com/vitejs/vite/issues/15012#issuecomment-2049888711
=> Restore examples production profiling & fix build warnings

docs/Inputs.md
=> [Doc] Fix Input usage mentions disabled instead of readOnly

packages/ra-ui-materialui/src/list/ListView.tsx
=> Fix crash in ListView when inside a tab

examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/contacts/ContactAside.tsx, examples/crm/src/contacts/ContactList.tsx, examples/crm/src/contacts/ContactShow.tsx, examples/crm/src/contacts/index.tsx, examples/crm/src/dashboard/Dashboard.tsx, examples/crm/src/dashboard/HotContacts.tsx, examples/crm/src/dashboard/LatestNotes.tsx, examples/crm/src/dashboard/TasksList.tsx, examples/crm/src/dataGenerator/tasks.ts, examples/crm/src/notes/NewNote.tsx, examples/crm/src/tasks/AddTask.tsx, examples/crm/src/tasks/Task.tsx, examples/crm/src/tasks/TasksIterator.tsx, packages/ra-data-fakerest/src/index.ts
=> [Demo] Add task management to CRM app

examples/crm/src/App.tsx, examples/crm/src/companies/CompanyAside.tsx, examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/companies/LogoField.tsx, examples/crm/src/contacts/ContactAside.tsx, examples/crm/src/contacts/ContactCreate.tsx, examples/crm/src/contacts/ContactInputs.tsx, examples/crm/src/contacts/ContactList.tsx, examples/crm/src/contacts/constants.ts, examples/crm/src/dataGenerator/contacts.ts, examples/crm/src/dataGenerator/tasks.ts, examples/crm/src/dataProvider.ts, examples/crm/src/notes/NewNote.tsx, examples/crm/src/notes/Note.tsx, examples/crm/src/notes/NotesIterator.tsx, examples/crm/src/tasks/AddTask.tsx, examples/crm/src/tasks/Task.tsx, packages/ra-ui-materialui/src/input/useSupportCreateSuggestion.tsx
=> [Demo] Improve CRM demo 

docs/DataProviderWriting.md, docs/ListTutorial.md, docs/Tutorial.md, examples/demo/package.json, examples/demo/src/categories/LinkToRelatedProducts.tsx, examples/demo/src/dashboard/PendingReviews.tsx, examples/demo/src/segments/LinkToRelatedCustomers.tsx, jest.config.js, packages/ra-core/package.json, packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/controller/list/useListParams.spec.tsx, packages/ra-core/src/controller/list/useListParams.ts, packages/ra-core/src/dataProvider/fetch.ts, packages/ra-data-json-server/package.json, packages/ra-data-json-server/src/index.ts, packages/ra-data-simple-rest/package.json, packages/ra-data-simple-rest/src/index.ts, packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/button/CloneButton.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx, packages/ra-ui-materialui/src/list/filter/SavedQueryFilterListItem.tsx, yarn.lock
=> Revert query-string upgrade

docs/Features.md
`ra-audit-log` was updated to v5.0.0
Update OSS doc
=> [Doc] Update ra-audit-log documentation for v5

docs/Demos.md
=> [Doc] Add link to Codesandbox of the simple demo

packages/ra-core/src/controller/saveContext/useRegisterMutationMiddleware.stories.tsx
The stories have been migrated to the new middleware signature.
=> Fix useRegisterMutationMiddleware stories

packages/ra-core/src/dataProvider/combineDataProviders.spec.ts, packages/ra-core/src/dataProvider/combineDataProviders.ts
=> Fix combineDataProvider throws a runtime error

docs/SaveButton.md
Fix https://github.com/marmelab/react-admin/issues/9889
=> [Doc] Clarify `<SaveButton transform>` usage

packages/create-react-admin/package.json, packages/create-react-admin/src/SelectInputChoice.tsx, packages/create-react-admin/src/StepAuthProvider.tsx, packages/create-react-admin/src/StepDataProvider.tsx, packages/create-react-admin/src/StepGenerate.tsx, packages/create-react-admin/src/StepInstall.tsx, packages/create-react-admin/src/StepName.tsx, packages/create-react-admin/src/StepResources.tsx, packages/create-react-admin/src/StepRunInstall.tsx, packages/create-react-admin/src/app.tsx, packages/create-react-admin/src/generateAppFile.ts, packages/create-react-admin/src/generateAppTestFile.ts, packages/create-react-admin/src/generateProject.ts, packages/create-react-admin/src/useInstallDeps.ts, packages/create-react-admin/src/useRunFormatter.ts, packages/create-react-admin/templates/common/package.json, packages/create-react-admin/templates/ra-data-fakerest/package.json, packages/create-react-admin/templates/ra-data-json-server/package.json, packages/create-react-admin/templates/ra-data-simple-rest/package.json, packages/create-react-admin/tsconfig.json, yarn.lock
`create-react-admin` has not been updated for v5:
https://github.com/marmelab/react-admin/issues/9462#issuecomment-2174559652
- Upgrade ink so that we use react 18
- Upgrade the templates for latest rc
=> Fix create react admin

docs/AccordionForm.md, docs/Form.md, docs/LongForm.md, docs/SimpleForm.md, docs/TabbedForm.md, docs/WizardForm.md
=> Add a note about nested fields in Forms documentation

packages/ra-data-graphql-simple/package.json, packages/ra-data-graphql/package.json, packages/ra-data-simple-rest/package.json, packages/ra-input-rich-text/package.json, yarn.lock
=> Fix npm install error due to outdated peer dependencies

docs/Create.md, docs/Edit.md, docs/List.md, docs/Show.md, packages/ra-ui-materialui/src/detail/Create.spec.tsx, packages/ra-ui-materialui/src/detail/Create.stories.tsx, packages/ra-ui-materialui/src/detail/CreateView.tsx, packages/ra-ui-materialui/src/detail/Edit.spec.tsx, packages/ra-ui-materialui/src/detail/Edit.stories.tsx, packages/ra-ui-materialui/src/detail/EditView.tsx, packages/ra-ui-materialui/src/detail/Show.spec.tsx, packages/ra-ui-materialui/src/detail/ShowView.tsx, packages/ra-ui-materialui/src/list/List.spec.tsx, packages/ra-ui-materialui/src/list/List.stories.tsx, packages/ra-ui-materialui/src/list/ListView.tsx
=> Add ability to disable title in page components

packages/ra-data-graphql/src/index.ts
=> fix(ra-data-graphql): fix an issue with custom context being overwritten on queries

docs/Breadcrumb.md
Update `<Breadcrumb>` doc according V5 migration
=> [DOC] update `<Breadcrumb>` doc according V5 upgrade

docs/DatagridAG.md
=> [DOC] update `ra-datagrid-ag` doc according to V5

examples/crm/src/contacts/ContactAside.tsx, examples/crm/src/contacts/ContactListFilter.tsx
Last seen is not the right wording
Change wording
=> Feat(wording): Replace last seen to last activity

examples/crm/src/companies/CompanyForm.tsx, examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/dataGenerator/companies.ts, examples/crm/src/types.ts
=> Feat(crm): Add description for companies

examples/crm/src/companies/CompanyEmpty.tsx, examples/crm/src/companies/CompanyList.tsx, examples/crm/src/companies/GridList.tsx, examples/crm/src/misc/hasOtherFiltersThanDefault.ts, examples/crm/src/misc/useAppBarHeight.ts
How to Test
In companies page, open console. Set window._database.collections.comapnies.items = []
Refresh via the refresh button.
=> Feat(crm): Add empty companies page

examples/crm/src/contacts/ContactEmpty.tsx, examples/crm/src/deals/DealEmpty.tsx, examples/crm/src/deals/DealList.tsx, examples/crm/src/deals/DealShow.tsx, examples/crm/src/misc/hasOtherFiltersThanDefault.ts, examples/crm/src/misc/useAppBarHeight.ts
In deals page, open console. Set `window._database.collections.deals.items = []`
Refresh via the refresh button.
You can also test when no contacts with adding the 
`window._database.collections.contacts.items = []` and refresh.
=> Feat(crm): Add empty deals page

docs/js/ra-doc-exec.js
=> Fix(documentation): Verify if Beginning mode exist before add event

docs/ReferenceManyInput.md, docs/ReferenceManyToManyInput.md, docs/ReferenceOneInput.md
The inputs provided by `ra-relationships` have some limitations that are not mentioned in the documentation.
=> Update ra-relationships documentation

examples/crm/src/tasks/AddTask.tsx, examples/crm/src/tasks/Task.tsx, examples/crm/src/tasks/TaskEdit.tsx, examples/crm/src/tasks/TasksIterator.tsx, examples/crm/src/tasks/task.const.ts
=> Feat(crm): Add edit task

examples/crm/src/notes/Note.tsx
=> Feat(crm): Add option to delete attachment note

examples/crm/src/companies/CompanyAside.tsx
=> Feat(crm): Display only baseUrl for company aside

examples/crm/src/authProvider.ts, examples/crm/src/dataGenerator/index.ts, examples/crm/src/dataGenerator/sales.ts, examples/crm/src/dataGenerator/types.ts, examples/crm/src/dataProvider.ts, examples/crm/src/login/LoginPage.tsx, examples/crm/src/login/SignupPage.tsx, examples/crm/src/settings/SettingsPage.tsx, examples/crm/src/settings/UpdatePassword.tsx, examples/crm/src/types.ts, packages/ra-ui-materialui/src/layout/UserMenu.tsx
[Capture vidéo du 22-07-2024 10:20:05.webm](https://github.com/user-attachments/assets/e37a2a83-15b8-4736-ad10-be7a84cb295d)
=> Fix(crm): Use sales instead of users for login

examples/crm/src/activity/ActivityCompanyCreated.tsx, examples/crm/src/activity/ActivityContactCreated.tsx, examples/crm/src/activity/ActivityContactNoteCreated.tsx, examples/crm/src/activity/ActivityDate.tsx, examples/crm/src/activity/ActivityDealCreated.tsx, examples/crm/src/companies/CompanyActivityIterator.tsx, examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/consts.ts, examples/crm/src/contacts/Avatar.tsx, examples/crm/src/dataGenerator/index.ts, examples/crm/src/dataGenerator/tasks.ts, examples/crm/src/dataGenerator/types.ts, examples/crm/src/dataProvider.ts, examples/crm/src/tasks/task.const.ts, examples/crm/src/types.ts
=> Feat(crm): Add activity log support

examples/crm/src/contacts/ContactInputs.tsx, examples/crm/src/dashboard/DealsPipeline.tsx, examples/crm/src/dataGenerator/companies.ts, examples/crm/src/dataProvider.ts, examples/crm/src/deals/DealCreate.tsx, examples/crm/src/deals/DealForm.tsx, examples/crm/src/misc/getContactAvatar.spec.ts, examples/crm/src/tasks/TaskEdit.tsx, examples/crm/src/types.ts
- Fix(crm): Replace Edit with EditBase for Task
- Fix(crm): Update dataProvider for contact lifecycle
- Fix(crm): Remove uncessary throw inside Deal Form
- Fix(crm): Set context_links for companies optionnal
- Fix(crm): Mock hash function for getContactAvatar
=> Fix(crm): improve technical code

docs/TreeInput.md, docs/TreeWithDetails.md
The ra-tree package has been updated. The doc should be updated too.
Backport ra-tree updates and overhaul props
- run `make docker-doc`
=> [DOC] Backport ra-tree updates and overhaul props

examples/crm/src/deals/DealCreate.tsx, examples/crm/src/deals/DealEdit.tsx, examples/crm/src/deals/DealInputs.tsx
[Capture vidéo du 23-07-2024 16:46:07.webm](https://github.com/user-attachments/assets/917c97f0-edd2-48b9-86eb-c0cefae688a6)
=> Feat(crm): Add ability to get back to show from deal edit and on save

examples/crm/src/Header.tsx
Some users don't know how to get back to the reception area
Ajoute une redirection vers la home depuis le logo de l'application
[Screencast from 2024-07-24 21-04-15.webm](https://github.com/user-attachments/assets/c1c39acf-ad57-40ef-8190-0eab79e8a938)
=> Feat(crm): Adds a redirection to home from the application logo

examples/crm/src/contacts/TagsListEdit.tsx, examples/crm/src/deals/DealCreate.tsx, examples/crm/src/deals/DealEdit.tsx, examples/crm/src/deals/DealInputs.tsx, examples/crm/src/deals/DealShow.tsx, examples/crm/src/misc/DialogCloseButton.tsx, examples/crm/src/notes/Note.tsx, examples/crm/src/notes/NoteCreate.tsx, examples/crm/src/notes/NoteInputs.tsx, examples/crm/src/sales/TransferAdminRoleModal.tsx, examples/crm/src/tasks/AddTask.tsx, examples/crm/src/tasks/Task.tsx, examples/crm/src/tasks/TaskEdit.tsx
Sometimes “Save” and “Delete” buttons are reverse.
Harmonize all forms with primary “Save” button on the left and secondary “Delete” on the right
Add a cross to close all popup
[Screencast from 2024-07-25 14-35-19.webm](https://github.com/user-attachments/assets/6608d488-2ffb-4bd9-a74d-33bfb281cc51)
=> Feat(crm): Hamonize forms

examples/crm/src/deals/DealInputs.tsx
Future date validation for closing date was causing error when editing past deal
Remove future date validation
Update a deal with expired date
=> Fix(crm): Remove deal closing date future date validation

examples/crm/src/deals/DealShow.tsx
Deals archive and unarchive buttons should not be primary actions
Make those buttons secondary actions
Archive and unarchive a deal
=> Fix(crm): Make deals archive and unarchive buttons secondary

examples/crm/src/contacts/ContactAside.tsx, examples/crm/src/contacts/ContactCreate.tsx, examples/crm/src/contacts/ContactEdit.tsx, examples/crm/src/contacts/ContactInputs.tsx, examples/crm/src/dataGenerator/contacts.ts, examples/crm/src/types.ts
As a user, I want to reduce the number of clicks and understand the parts of the contact form at a glance
Before
After
=> Feat(crm): Display Contact inputs by category in columns and improve UX form

examples/crm/src/deals/DealList.tsx
The deals filter in list view was returning empty list
Changed the target field from `type` to `category`
Filter deals by category in list view
=> Fix(crm): Deals category filter is now applied to the category field

examples/crm/src/companies/CompanyInputs.tsx, examples/crm/src/deals/DealArchivedList.tsx, examples/crm/src/deals/DealEdit.tsx, examples/crm/src/notes/Note.tsx
=> Fix(crm):  improve user experience for deals

examples/crm/src/companies/CompanyCard.tsx, examples/crm/src/companies/CompanyInputs.tsx, examples/crm/src/companies/GridList.tsx, examples/crm/src/dashboard/Dashboard.tsx, examples/crm/src/dashboard/DashboardActivityLog.tsx, examples/crm/src/dashboard/DealsChart.tsx, examples/crm/src/dashboard/HotContacts.tsx, examples/crm/src/dashboard/TasksList.tsx, examples/crm/src/misc/ImageEditorField.tsx, examples/crm/src/notes/NoteInputs.tsx, examples/crm/src/notes/utils.ts, examples/crm/src/settings/SettingsPage.tsx
=> Fix(crm): Apply sugestions from review

examples/crm/src/authProvider.ts, examples/crm/src/dashboard/Dashboard.tsx, examples/crm/src/dashboard/DashboardStepper.tsx, examples/crm/src/login/SignupPage.tsx
As a user, given I open the application for the first time, I would like to know what I can do
Displays the user's 3 mains objectives
=> Feat(crm): Add onboarding for empty project

examples/crm/src/companies/CompanyInputs.tsx, examples/crm/src/deals/DealInputs.tsx, examples/crm/src/deals/DealShow.tsx, examples/crm/src/misc/DialogCloseButton.tsx, examples/crm/src/misc/ImageEditorField.tsx, examples/crm/src/settings/SettingsPage.tsx, examples/crm/src/tasks/AddTask.tsx
=> Fix(crm): Apply suggestions from code reviews

examples/crm/src/contacts/ContactList.tsx, examples/crm/src/contacts/ContactListContent.tsx, examples/crm/src/dashboard/DashboardActivityLog.tsx, examples/crm/src/dashboard/DealsChart.tsx, examples/crm/src/dashboard/HotContacts.tsx, examples/crm/src/dashboard/TasksList.tsx, examples/crm/src/dashboard/TasksListFilter.tsx, examples/crm/src/dashboard/Welcome.tsx, examples/crm/src/dataProvider.ts, examples/crm/src/deals/DealShow.tsx, examples/crm/src/misc/ImageEditorField.tsx, examples/crm/src/tasks/AddTask.tsx
=> Fix(crm): Improvement for UI + fix processCompanyLogo

docs/_layouts/default.html, docs/documentation.html
Remove v5 announcement in doc pages
=> [DNM] [Doc] Remove v5 annoucement banner

_layouts/default.html, doc/5.0/documentation.html, documentation.html, index.html, landing-page/index.html
Remove v5 announcement in doc pages
**Do not merge before August, 1st.**
=> [Doc] Remove all RA v5 teasing banners

examples/crm/src/companies/CompanyInputs.tsx, examples/crm/src/contacts/ContactInputs.tsx, examples/crm/src/dataProvider.ts, examples/crm/src/notes/NoteCreate.tsx, examples/crm/src/sales/SalesEdit.tsx, examples/crm/src/sales/SalesInputs.tsx, examples/crm/src/sales/SalesList.tsx, examples/crm/src/types.ts
As a user, I lose deleted user activity
Add a disabled boolean for Sale users.
=> Feat(crm): Add possibility to disable Sale

examples/crm/src/activity/ActivityLogNote.tsx, examples/crm/src/contacts/ContactInputs.tsx, examples/crm/src/dataGenerator/contactNotes.ts, examples/crm/src/dataGenerator/contacts.ts, examples/crm/src/dataGenerator/dealNotes.ts, examples/crm/src/dataGenerator/deals.ts, examples/crm/src/dataProvider.ts, examples/crm/src/deals/DealEmpty.tsx, examples/crm/src/deals/DealList.tsx, examples/crm/src/types.ts
Code modified to look more like Atomic Crm
=> Feat(crm): Code modified to look more like Atomic Crm

docs/Inputs.md
Refs https://github.com/marmelab/react-admin/pull/9637#issuecomment-2272256911
=> [Doc] Fix ReferenceInput usage

docs/FilteringTutorial.md
https://github.com/marmelab/react-admin/issues/10149
Fix https://github.com/marmelab/react-admin/issues/10149
=> [Doc] Improve types in QuickFilter doc

docs/Upgrade.md
=> Update Upgrade.md to fix the codemod filename extensions to "cjs"

index.html, landing-page/index.html
Vimeo will delete our e-commerce video.
Change publication platform for YouTube
=> Change Vimeo video for YouTube 

docs/Reference.md
`<DateRangeInput>`'s reference doesn't display any premium icon
Add it
Following #10202
=> [Doc] Fix `<DateRangeInput>`'s reference EE icon

packages/ra-ui-materialui/src/list/List.spec.tsx, packages/ra-ui-materialui/src/list/List.stories.tsx, packages/ra-ui-materialui/src/list/ListView.tsx
=> Fix List empty component wrongly appears when using partial pagination

docs/Create.md, docs/CreateBase.md, docs/Edit.md, docs/EditBase.md, docs/InfiniteList.md, docs/List.md, docs/ListBase.md, docs/Permissions.md, docs/Show.md, docs/ShowBase.md, docs/navigation.html, docs/useCreateController.md, docs/useEditController.md, docs/useListController.md, docs/useShowController.md
=> [Doc] Rewrite access control documentation

packages/ra-language-english/src/index.ts, packages/ra-ui-materialui/src/list/InfiniteList.stories.tsx, packages/ra-ui-materialui/src/list/ListNoResults.stories.tsx, packages/ra-ui-materialui/src/list/ListNoResults.tsx, packages/ra-ui-materialui/src/list/SimpleList/SimpleList.spec.tsx
=> Fix no results message has untranslated resource name

.github/ISSUE_TEMPLATE/Bug_report.md
Because of #10252, we created a repository that only includes the simple example. However, the bug report issue template does not mention it.
Update the bug report issue template
=> Update bug report issue template

docs/Readme.md
There was a typo in the readme
There is no more a typo in the readme
Open the readme (ie https://marmelab.com/react-admin/Readme.html#usage). 
Try to find the typo.
> The term "why" is a fundamental question word used to ask for the reason, purpose, or cause of something. It seeks an explanation behind an action, event, or situation. For example, in the sentence "Why did you do that?" the speaker is asking for the reason or motive behind a specific action.
"Why" is often used in both everyday conversations and more complex contexts, such as philosophical inquiries or scientific investigations, to understand underlying reasons or principles.
It can also be rhetorical, where the speaker isn't necessarily expecting a literal answer, but rather using it to express emotions like confusion, …
=> [doc] fix example in README

docs/Authentication.md
Fixes #10294, supersedes #10297
We have a incorrect link in the documentation
Fix the link
=> [Doc] Fix Authorization link in Authentication page

docs/Demos.md
Commit e0eb01564e126c919e0288e672b612bba164fea4 moved the location of the horizontal navigation source file without updating the sources.
PR updates the sources with changes.
=> [Doc] Update horizontal navigation reference

docs/DatagridAG.md
DatagridAG is now usable inside InfiniteList.
Document the feature.
=> [Doc] Document usage of DatagridAG inside an InfiniteList

packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
[This story](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-list-simplelist--error-in-fetch) fails:
https://react-admin-storybook-m0jiorrgs-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-simplelist--error-in-fetch
or
http://localhost:9010/?path=/story/ra-ui-materialui-list-simplelist--error-in-fetch
=> Fix `SimpleList` `ErrorInFetch` story

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Follow up of https://github.com/marmelab/react-admin/issues/7763#issuecomment-2232688294
=> Fix type of disableClearable prop for AutocompleteInput

docs/DatagridAG.md
DatagridAG has new features.
Update its documentation
=> [Doc] Introduce `<DatagridAG>` custom cell editors

docs/ReferenceManyToManyInput.md
EE doc was updated
Update OSS doc
=> [Doc]: Backport `ReferenceManyToMany`'s error support documentation

examples/tutorial/vite.config.ts
=> Fix tutorial has multiple conflicting MUI packages

docs/DatagridAG.md
We don't specify all the dependencies of AgGrid in our doc
Update doc to mention the dependency on `@ag-grid-community/styles`
=> [Doc] Update doc to mention the dependency on `@ag-grid-community/styles`

docs/CreateDialog.md, docs/CreateInDialogButton.md, docs/EditDialog.md, docs/EditInDialogButton.md
In our doc, we spoke about 2 cases but only one is important and documented
Stop to speak about the 2 cases
=> Fix dialogs doc for `warnWhenUnsavedChanges` sections

docs/FormFillerButton.md, docs/PredictiveTextInput.md, docs/SmartRichTextInput.md
The  `<FormFillerButton>` documentation does not really explain the dataProvider requirements like `<SmartRichTextInput>` does.
Improve `<FormFillerButton>` documentation by explaining the `dataProvider.getCompletion()`
=> [Doc] Improve `<FormFillerButton>` documentation by explaining the `dataProvider.getCompletion()`

docs/AutoSave.md, docs/InfiniteList.md
Document all `AutoSave` and `useAutoSave` props
=> [doc] Improve `AutoSave` and `useAutoSave`

docs/ShowDialog.md
=> [Doc] Fix typo in `ShowDialog` doc

packages/ra-i18n-polyglot/README.md, packages/ra-i18n-polyglot/src/index.stories.tsx, packages/ra-i18n-polyglot/src/index.ts, packages/ra-i18n-polyglot/tsconfig.json
Readme of ra-i18n-polyglot example code is wrong.
Write some stories to check for the example code.
Fix the documentation.
Just read the readme, and check the storybook 
=> Fix ra 18n polyglot doc

packages/ra-ui-materialui/src/list/InfiniteList.stories.tsx
The story for the select all limit was not working properly
Fix the story
Try the story https://react-admin-storybook-myrxixkwd-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-infinitelist--with-datagrid-and-select-all-limit
=> [chore] Fix `<SelectAllButton>` limit story

packages/ra-ui-materialui/src/list/SimpleList/SimpleListConfigurable.stories.tsx
The SimpleFieldList story is buggy
Fix `<SimpleListConfigurable>` story
https://react-admin-storybook-57v3iq24i-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-simplelistconfigurable--basic
=> [chore] Fix `<SimpleListConfigurable>` story

docs/DatagridAG.md
`ra-datagrid-ag` doc was updated
Backport documentation
=> [Doc] Backport `DatagridAG` doc

docs/Translate.md, packages/ra-core/src/i18n/Translate.spec.tsx, packages/ra-core/src/i18n/Translate.stories.tsx, packages/ra-core/src/i18n/Translate.tsx, packages/ra-i18n-i18next/src/index.stories.tsx, packages/ra-i18n-polyglot/src/index.stories.tsx
Some comments arrived on the merged PR #10605
Apply those comments
=> Improve implementation of the `Translate` component

docs/useCreate.md
Some section are considered code blocks when they shouldn't
Fix the code fences.
=> [Doc] Fix useCreate documentation

docs/Layout.md
=> [Doc] Fix `<Layout error>` documentation

examples/demo/src/dashboard/OrderChart.tsx
=> [Demo] Fix order chart currency

packages/ra-ui-materialui/src/input/SelectInput.stories.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
```tsx
<SelectInput source="foo" label={false} variant="outlined" />
```
=> Fix `<SelectInput>` shows gap in border when using no label with outlined variant

examples/crm/src/deals/OnlyMineInput.tsx
=> Remove unneeded check due to optional chaining

packages/ra-core/src/controller/list/useInfiniteListController.spec.tsx, packages/ra-core/src/controller/list/useInfiniteListController.ts, packages/ra-core/src/controller/list/useListController.spec.tsx, packages/ra-core/src/dataProvider/useInfiniteGetList.ts
Fix https://github.com/marmelab/react-admin/issues/10745
Run unit tests
=> Fix `useInfiniteListController` does not return response `meta`

.github/workflows/test.yml
Greenframe will be discontinued soon.
Remove the Greenframe CI job
=> [chore] Remove greenframe CI job

package.json, packages/ra-core/src/dataProvider/HttpError.ts, packages/ra-core/src/i18n/useTranslatable.ts, packages/ra-core/src/inference/InferredElement.ts, packages/ra-core/src/inference/assertions.ts, packages/ra-core/src/inference/inferElementFromValues.tsx, packages/ra-core/src/inference/inferTypeFromValues.ts, packages/ra-core/src/preferences/usePreference.ts, packages/ra-core/src/preferences/usePreferenceInput.ts, packages/ra-core/src/routing/useRestoreScrollPosition.ts, packages/ra-core/src/store/localStorageStore.ts, packages/ra-core/src/store/types.ts, packages/ra-core/src/store/useStore.ts, packages/ra-data-graphql-simple/src/buildVariables.ts, packages/ra-input-rich-text/src/buttons/ColorButtons.tsx, packages/ra-ui-materialui/src/layout/PageTitleConfigurable.tsx, tsconfig.json, yarn.lock
=> [Chore] Upgrade TypeScript to v5.8

packages/ra-core/src/controller/field/ReferenceManyFieldBase.stories.tsx, packages/ra-ui-materialui/src/detail/Create.tsx, packages/ra-ui-materialui/src/detail/Edit.tsx
There are linter warnings about unused imports.
Remove unused imports.
`make lint` -> no warnings!
=> Fix unused imports

packages/ra-core/src/dataProvider/useGetManyAggregate.spec.tsx, packages/ra-core/src/dataProvider/useGetManyAggregate.ts
When using `<ReferenceArrayInput>` with different `queryOptions.meta`, the `useGetManyAggregate` hook should not merge the calls.
Group calls by `resource` **and** `meta`.
Unit tests
=> Fix `useGetManyAggregate` merge queries with different `meta`
