marmelab/react-admin

docs/CreateEdit.md
`<TabbeForm>` into `<TabbedForm>`
=> doc: Fix typo in CreateEdit.md

packages/ra-ui-materialui/src/list/SimpleList.js
The main use case is to allow to decide wich action to take on each record by evaluating the record itself like the other `SimpleList` main props.
You can do that with the `Datagrid` for large screens easilly but for small screens the `SimpleList` doesn't have a simple way to do this.
```jsx
// in src/posts.js
import React from 'react';
import { useMediaQuery } from '@material-ui/core';
import { List, SimpleList, Datagrid, TextField, ReferenceField, EditButton } from 'react-admin';
export const PostList = props => {
const isSmall = useMediaQuery(theme => theme.breakpoints.down('sm'));
return (
{isSmall ? (
<SimpleList
primaryText={record => record.title}
secondaryText={record => `${record.views} views`}
tertiaryText={record => new …
```
=> [RFR]: Allow SimpleList linkType prop to be resolved as a function.

packages/ra-core/src/dataProvider/useQueryWithStore.ts
Using `useQueryWithStore` with the default parameters is not working as expected for the `total` state value (it was always `null`).
=> Fix default total selector in useQueryWithStore

packages/ra-ui-materialui/src/field/ReferenceField.tsx
A warning is displayed about the boolean type of `translateChoice` prop in a `ReferenceField`.
But it's not an error, this type can be func or bool.
Use nested `ReferenceField` in a list view.
```js
<List {...props} >
<Datagrid>
<DateField source="created_at" />
<ReferenceField
label="region_name"
source="customer_id"
reference="customers"
link={false}
>
<ReferenceField
source="customer_region_id"
reference="customer_regions"
>
</ReferenceField>
</ReferenceField>
</Datagrid>
</List>
```
The type of translateChoice can be func or bool in PropTypes
=> Fix translateChoice warning in ReferenceField

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Most AutocompleteInput tests threw console errors regarding initial state.
```
VM74:37 Warning: A component is changing a controlled input of type text to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. 
VM74:37 downshift: A component has changed the controlled prop "inputValue" to be - uncontrolled. This prop should not switch from controlled to uncontrolled (or vice versa). Decide - between using a controlled or uncontrolled Downshift element for the lifetime of the component. - More info: https://github.com/downshift-js/downshift#control-props 
in Downshift (created by AutocompleteInput)
in AutocompleteInput (at …
```
=> Set AutocompleteInput value to an empty string when it's selected item is null

packages/ra-core/src/controller/input/useGetMatchingReferences.spec.tsx, packages/ra-core/src/controller/input/useGetMatchingReferences.ts
=> Fix cryptic error message when using a ReferenceInput to a missing resource

packages/ra-core/src/controller/useEditController.spec.tsx, packages/ra-core/src/dataProvider/useGetOne.ts, packages/ra-ui-materialui/src/detail/Edit.spec.js, packages/ra-ui-materialui/src/detail/Show.spec.js
`useQuery` works even without a `<Resource>` because it doesn't rely on the Redux store. However, developers may want to use the more specialized hooks, like `useGetOne()`. These only work if there is a `<Resource>`, but for now if there is no resource the hook returns null - which is not a good developer experience.
This change throws an error in case of missing Resource for useGetOne. It's a start. It's a bit harder to do for other data Provider hooks, so let's start with this baby step/
=> Throw an error when useGetOne is called for an undefined resource

packages/ra-core/src/controller/useFilterState.ts
=> Fix ReferenceInput when using an object literal as filter prop

docs/List.md, examples/simple/src/posts/PostList.js, packages/ra-core/src/controller/useListController.ts, packages/ra-core/src/controller/useListParams.ts, packages/ra-core/src/controller/useSortState.ts, packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.tsx, packages/ra-ui-materialui/src/field/sanitizeRestProps.ts, packages/ra-ui-materialui/src/field/types.ts, packages/ra-ui-materialui/src/input/ReferenceInput.tsx, packages/ra-ui-materialui/src/list/Datagrid.js, packages/ra-ui-materialui/src/list/DatagridHeaderCell.js, packages/ra-ui-materialui/src/list/DatagridHeaderCell.spec.js
Closes #2736
In Lists, columns are always sorted by `ASC` order by default
Sometimes, it's not the main desired behaviour (recent dates before, .....)
```js
<TextField
source="title"
sortBy="title"
sortByOrder="DESC"
/>
```
=> Add a default order prop in List Fields

packages/ra-core/src/dataProvider/cacheDataProviderProxy.ts, packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
Fixes #4697
React-devtools uses `obj[Symbol.iterator] === 'function'` to decide whether an object is an iterator. If it is, react-devtools will call that `obj[Symbol.iterator]` function. Since a dataProvider proxy's GET trap always returns a function, the comparison will always be true. The real dataProvider doesn't have the `Symbol.iterator` property, so it throws an error. When `name` is `Symbol.iterator`, returning `undefined` can make react-devtools think the dataProvider is an object and won't call `obj[Symbol.iterator]`.
=> Fix components / hooks error in react-devtools

docs/List.md
I've changed the previous / next pagination example with a better implementation.
In the previous one, the icons were not working and the `labelPosition` prop doesn't exist.
Now, the texts are also translated and RTL is managed.
=> [Doc] Fix previous / next pagination

packages/ra-core/src/form/useInitializeFormWithRecord.ts
=> Fix initialValue is ignored in children of ArrayInput

docs/Ecosystem.md
Hey guys,
Adding [react-admin-firebase](https://github.com/benwinding/react-admin-firebase#auth-provider) to the "Authentication Providers" in Ecosystem.md. 
We've implemented various Authentication features which are now widely used:
- Login with: Google, Facebook, Github etc... ([Example Here](https://github.com/benwinding/react-admin-firebase/blob/master/src-demo/src/CustomLoginPage.js))
- A "Forgot password" button... ([Example Here](https://github.com/benwinding/react-admin-firebase/blob/master/src-demo/src/CustomForgotPassword.js))
Thought it might be good to put in the docs for new people.
Thanks for all your work on this amazing platform!
Cheers,
Ben
=> Docs: Add react-admin-firebase to Authentication Providers

packages/ra-core/src/form/useInitializeFormWithRecord.ts
Because, sadly, in JS:
```js
const value = 'string';
console.log(Object.keys(value).length);
// --> 6
```
=> Fix useInitializeFormWithRecord with an array of objects

packages/ra-data-graphql-simple/src/getResponseParser.js
=> Avoid treating null-values as objects with keys

packages/ra-core/src/controller/useEditController.ts, packages/ra-core/src/controller/useListController.ts, packages/ra-core/src/controller/useShowController.ts, packages/ra-core/src/dataProvider/useQuery.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix refresh button breaks useGetList result with application cache

docs/List.md, examples/demo/package.json, examples/demo/src/categories/CategoryEdit.tsx, examples/demo/src/categories/CategoryList.tsx, examples/demo/src/dashboard/Dashboard.tsx, examples/demo/src/dashboard/OrderChart.tsx, examples/demo/src/dashboard/Welcome.tsx, examples/demo/src/i18n/en.ts, examples/demo/src/i18n/fr.ts, examples/demo/src/orders/OrderList.js, examples/demo/src/products/GridList.js, examples/demo/src/products/ProductEdit.js, examples/demo/src/types.ts, examples/demo/src/visitors/VisitorCreate.tsx, examples/demo/src/visitors/VisitorEdit.tsx, examples/demo/src/visitors/VisitorList.tsx, examples/demo/src/visitors/VisitorListAside.tsx, packages/ra-core/src/controller/index.ts, yarn.lock
=> Improve demo

docs/DataProviders.md
`id` of deleted record is required in `selectedIdsReducer`.
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts#L51
Returning null as documentation stated, would raise Error:
```
index.js:1 TypeError: Cannot read property 'id' of null
at selectedIdsReducer (selectedIds.js:19)
at combination (redux.js:459)
at index.js:46
at Array.reduce (<anonymous>)
at index.js:40
at combination (redux.js:459)
at combination (redux.js:459)
at resettableAppReducer (createAdminStore.js:50)
at dispatch (redux.js:213)
at middleware.js:22
at redux-saga-core.esm.js:1410
at useDataProvider.js:291
```
=> Update documentation for delete

packages/ra-data-graphcool/src/buildVariables.js, packages/ra-data-graphcool/src/buildVariables.test.js
According to [documentation](https://marmelab.com/react-admin/Fields.html#referencemanyfield) ReferenceManyField should have ability to have pagination and sorting.
For now ra-data-graphcool don't allow to do this.
This PR is adding this ability for ra-data-graphcool
The idea is "borrowed" from ra-data-graphql-simple
=> ra-data-graphcool: Add ability to use pagination and orderBy in GET_MANY_REFERENCE 

docs/DataProviders.md
The maintainer of the current Firestore DataProvider in the docs ([rafalzawadzki/ra-data-firestore-client](https://github.com/rafalzawadzki/ra-data-firestore-client)) has agreed to retire his project and is advising people move to the newer Firestore DataProvider ([benwinding/react-admin-firebase](https://github.com/benwinding/react-admin-firebase)) which supports `react-admin` v3.
Comment from maintainer: https://github.com/benwinding/react-admin-firebase/issues/72#issuecomment-633595970
- Changed the Firestore provider to [benwinding/react-admin-firebase](https://github.com/benwinding/react-admin-firebase)
- Improved dataprovider labels, as they're both technically Firebase databases, but the names are a little more specific (to avoid confusion).
- Firebase Realtime Database is 
- …
=> [Docs] Changing Firestore Dataprovider

packages/ra-core/src/form/sanitizeEmptyValues.spec.ts, packages/ra-core/src/form/sanitizeEmptyValues.ts
Fixes #4726
This will not support an array of objects with different structure AND key reordering.
=> [RFR] Support array of objects in sanitizeEmptyValues

cypress/integration/create.js, cypress/support/CreatePage.js, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx
=> SaveButton renders disabled if Form is pristine.

cypress/support/ListPage.js, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/list/BulkActionsToolbar.js
=> Add ability to deselect rows in one click in BulkActionsToolbar

packages/ra-ui-materialui/src/field/EmailField.spec.js, packages/ra-ui-materialui/src/field/EmailField.tsx
=> Emailfield to Muilink

packages/ra-core/src/controller/button/index.ts, packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-core/src/controller/index.ts, packages/ra-ui-materialui/src/button/Button.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
I wanted a DeleteIconButton, and I found myself copying the DeleteButton logic code. Better move it to `ra-core`.
=> Add ability to create custom DeleteButton views without rewriting the logic

examples/demo/src/products/GridList.tsx
=> products GridList to typescript

docs/CreateEdit.md, examples/simple/src/posts/PostCreate.js, packages/ra-core/src/controller/SideEffectContext.tsx, packages/ra-core/src/controller/index.ts, packages/ra-core/src/controller/saveModifiers.tsx, packages/ra-core/src/controller/useCreateController.spec.tsx, packages/ra-core/src/controller/useCreateController.ts, packages/ra-core/src/controller/useEditController.spec.tsx, packages/ra-core/src/controller/useEditController.ts, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx, packages/ra-ui-materialui/src/detail/Create.js, packages/ra-ui-materialui/src/detail/Edit.js, packages/ra-ui-materialui/src/detail/Edit.spec.js, packages/ra-ui-materialui/src/form/SimpleForm.js
I wanted to force a refresh after save in a `<Create>` view. I found it super hard to do even though I know the react-admin internals. I realized it's probably impossible for someone who doesn't know react-admin. 
Also, there are ways to override the notification message in the Create/Edit view (`successMessage`) and ways to override the `redirect` in `SimpleForm`. These are both side effects that should be the responsibility of the main controller, not the form. These props allow a very granular customization, but don't allow adding another side effect.
Finally, the recent addition of the `onSave` prop requires too much documentation and too much boilerplate for most common use cases. 
Allow users to declare success and failure side effects at the controller side, and to override them …
=> Add create / edit side effects and transform

examples/demo/src/reviews/ReviewListMobile.js, packages/ra-ui-materialui/src/list/SimpleList.js
Checking the `loading` prop for rendering the `SimpleList` was wrong, it should be `!loading` or `loaded`.
The `ReviewMobileList` component in the demo has also been fixed (it's coming from the `SimpleList` component).
=> Fix mobile version of ReviewList on the example demo

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
The `AutocompleteArrayInput` renders without separation from whichever component precedes it, unless a margin is set manually.
`AutocompleteInput` and other input components [provide a sensible default for the margin](https://github.com/marmelab/react-admin/blob/9a5f1f10d049aaa24430b47826c0c3c1a72af5d9/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L111). This PR extends the same default to `AutocompleteArrayInput`.
=> Add default margin to AutocompleteArrayInput

packages/ra-ui-materialui/src/input/ArrayInput.tsx
Hi,
while trying to understand how `ArrayInput` works, I came across `UrlInput` which seems deprecated because the docs say `TextInput` handles a.o. URLs.
I am not sure if the `master` branch is the right one for the PR because `README` says to open PR into the `next` if its a feature, but did not find info what to do in case such minor changes like in this PR
=> docs: Replaced UrlInput with TextInput in ArrayInput comments

examples/demo/src/reviews/StarRatingField.tsx, examples/demo/src/visitors/FullNameField.tsx, examples/demo/src/visitors/SegmentsField.tsx, examples/demo/src/visitors/VisitorList.tsx, examples/simple/src/posts/PostList.js, packages/ra-ui-materialui/src/field/BooleanField.tsx
`<BooleanField>` makes all lines in a `<Datagrid>` taller. 
Make it smaller. Also, use smaller chips in `<ReferenceManyField>` in datagrids. This makes the grid data density consistent whether it contains `<BooleanField>` components or not.
=> Make boolean field less tall by default

packages/ra-ui-materialui/src/field/ArrayField.tsx
Hi,
When I am using `<SingleFieldList>` component as children of `<ArrayField>`, there seems to have a race condition that will make the whole `<List>` view of a resource crash sometime.
The error message is:
> TypeError: ids is undefined
I have traced the issue to its parent component. The useState hook is not initializing ids and data properly, setting them to undefined value. The useEffect hook will run during first render, but the state update function setIds and setData are asynchronous. This will cause the undefined ids to be passed down and ids.map function cannot be called properly.
The fix is also simple, just adding initial states.
Thank you
=> fix ArrayField initial state value

packages/ra-core/src/dataProvider/HttpError.ts
While trying to use `error.name`, I noticed that the HttpError used by react-admin has its name set to `Error` instead of `HttpError`. I believe this is probably due to https://github.com/Microsoft/TypeScript/issues/14099
Setting it explicitly seems like it would be fine in this case, but let me know if you prefer a different solution.
=> Set HttpError name to be HttpError

packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx
Fixes #4924
(as this supports choices rendered as react components)
=> Change id for RadioButtonGroupInputItem to use value rather than label

packages/ra-core/src/controller/useListController.ts
The problem was that the update or delete removes the cachedRequests from the store. The list controller properly uses the ids reducer in that case - but not the effect checking the validity of the pagination.
Closes #4902
=> Fix update or delete resets the pagination

packages/ra-data-graphql/src/introspection.js
Check for top level property before looking deeper into object, was throwing name not found because mutationType doesn't exist in schema object
=> Check for schema.queryType and schema.mutationType

packages/ra-ui-materialui/src/list/index.js
I need the `ExpandRowButton` in case I want to extend  react-admin `Datagrid` with my own behaviour, and keep the expandable grid lines.
=> Export ExpandRowButton for reuse

docs/Translation.md, examples/demo/src/i18n/en.ts, examples/simple/src/i18n/en.js, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/list/Empty.js
Closes #4783 
Resources names are always set to lower case in confirm messages and it doesn't match with all language synxates (ie : in German, names should be capitalized)
Allow to force case in translation file
=> Fix : Resource name case in confirm for multi-language

packages/ra-core/src/core/createAdminStore.ts, packages/ra-data-fakerest/src/index.ts
This allows the code to run safely in a non-DOM environment
=> Change conditional check for window to use typeof window

packages/ra-core/src/i18n/TranslationMessages.ts
see https://github.com/marmelab/react-admin/commit/0c360b05ee15caa78ce902a6b30c11e0f7381c4a
=> fix: Fix types to TranslationMessages

packages/ra-core/src/core/RoutesWithLayout.spec.tsx, packages/ra-core/src/core/RoutesWithLayout.tsx
=> Fix Dashboard components cannot use useGetOne hook

packages/ra-core/src/core/RoutesWithLayout.spec.tsx, packages/ra-core/src/core/RoutesWithLayout.tsx
Reverts marmelab/react-admin#4988
The problem was introduced in #4430, and the fix needs to be in `useGetOne`, and nowhere else.
=> Revert "Fix Dashboard components cannot use useGetOne hook"

packages/ra-ui-materialui/src/auth/Logout.tsx
=> Fix <LogoutButton >should not render as a <li> in Mobile menu

packages/ra-ui-materialui/src/input/SearchInput.tsx
=> Fix SearchInput with label prop renders incorrectly

docs/Admin.md
Fixes https://github.com/marmelab/react-admin/issues/4629
Follows https://github.com/marmelab/react-admin/pull/3907
=> Document dynamic resources

packages/ra-ui-materialui/src/button/CreateButton.tsx
I need the `CreateButton` to reflect the filter values to prefill the new item form. The use case is like this:
- filter the data by a couple of fields
- no expected data found
- press Create
- expect those two fields filled with the filter values
It worked almost fine except I needed to refresh the page after setting the filter to make the `to` property be in sync with the filter (. After some research I found out that this button is exported via `memo` and it's not updated if the `to` prop is changed. I replaced the `TopToolbar` in `List` and the button is declared like this:
```js
<CreateButton to={{
pathname: '/records/create',
search: `?source=${JSON.stringify({ organization_id: filterValues.organization_id, department_id: filterValues.department_id })}`,
}} />
```
When I used a …
=> Update CreateButton on 'to' prop change

packages/ra-core/src/controller/useListController.ts
In a List view with no custom exporter (e.g. the Users list in the simple demo), the export button no longer works
In 3.7, the ExporterContext was merged into the ListContext, but the default exporter was only set in ExporterContext
=> [RFR] Fix Export button fails to export data when using default exporter

packages/ra-core/src/controller/field/useReferenceManyFieldController.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix setFilter fails on ReferenceManyField

docs/Show.md
`EditButton` was imported in the code sample but without any purpose
=> Fix documentation : Remove unused import of EditButton

packages/ra-core/src/util/removeEmpty.ts, packages/ra-ui-materialui/src/input/FileInput.tsx
Continuing #4786
Boath functions are identical.
https://github.com/reduxjs/react-redux/blob/master/src/utils/shallowEqual.js
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/shallowEqual.js
As a side note, its now posible to remove `recompose` dependency from `ra-core`
=> Replace recompose's shallowEqual with react-redux's shallowEqual.

.eslintrc, examples/demo/src/dashboard/CardWithIcon.tsx, examples/demo/src/dashboard/PendingReviews.tsx, packages/ra-ui-materialui/src/field/BooleanField.tsx, packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx, packages/ra-ui-materialui/src/list/Empty.tsx, packages/ra-ui-materialui/src/list/ListToolbar.tsx, packages/ra-ui-materialui/src/list/SimpleList.tsx, packages/ra-ui-materialui/src/list/useDatagridStyles.tsx
This is a continuation of #4983. Apparently, I have been overly optimistic about ESLint's capability at configuration parsing and application, which lead to error reporting only on one of two restricted imports. This PR corrects it and also fixes all the issues this caused.
=> [RFR] Fix ESLint @material-ui/core rule configuration

packages/ra-ui-materialui/src/input/SelectInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/5037 - ReferenceInput adds a buggy DOM property "pagination" to the inner SelectInput
=> Fix - Sanitize the pagination prop passed to the SelectInput

docs/CreateEdit.md, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx, packages/ra-ui-materialui/src/form/SimpleForm.js, packages/ra-ui-materialui/src/form/TabbedForm.js, packages/ra-ui-materialui/src/form/Toolbar.js
Implements https://github.com/marmelab/react-admin/issues/4913
To build this feature I allow the user to pass a new prop named `alwaysEnableSaveButton` to the `<Toolbar>` which forces enabling ou disabling the `<SaveButton>`. If the user doesn't specify this prop, we keep the classic behaviour by disabling the button until the form is dirty. 
How to force enabling the `<SaveButton>` without rewriting the whole `<Toolbar>`:
``` js
import * as React from 'react';
import {
Create,
SimpleForm,
Toolbar,
} from 'react-admin';
import PostReferenceInput from './PostReferenceInput';
export const CommentCreate = props => (
<Create {...props}>
<SimpleForm redirect={false} toolbar={<Toolbar alwaysEnableSaveButton />}>
// Form goes here
</SimpleForm>
</Create>
);
```
If you don't pass the disabled …
=> Add ability to make the <SaveButton> not disabled by default

docs/Inputs.md, packages/ra-ui-materialui/src/form/SimpleFormIterator.js, packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.js
As mentioned in https://github.com/marmelab/react-admin/issues/4676
This is an enhancement that will allow us to pass our own custom add and remove buttons to the SimpleFormIterator component.
**Changes**
- feature: add addButton and removeButton as props in SimpleFormIterator
- refactor: moved the add and remove button logic to separate functions
- test cases: added test cases for addButton and removeButton props
- docs: added an example of the same in docs
Let me know if it requires any further updates.
=> enhancement: allow custom add and remove buttons in SimpleFormIterator

docs/DataProviders.md
Since the previous repo uses outdated RA 2.0 format and seems like not to be maintained anymore, maybe makes sense to update the link here.
https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider/issues/24
=> update nestjsx data provider

docs/Inputs.md
Follows https://github.com/marmelab/react-admin/pull/4818
=> Fix a typo in documentation about the <SimpleFormIterator>

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
Fixes https://github.com/marmelab/react-admin/issues/4943
It allows the usage of BulkDeleteButton with undoable=false in non-list pages
=> Fix bulk delete confirmation dialog does not close after success when using Datagrid in a non-list page

cypress/plugins/index.js, cypress/support/CreatePage.js, cypress/support/EditPage.js, docs/CreateEdit.md, docs/Show.md, examples/simple/src/posts/PostEdit.js, packages/ra-ui-materialui/src/detail/TabbedShowLayout.js, packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.js, packages/ra-ui-materialui/src/form/TabbedForm.js, packages/ra-ui-materialui/src/form/TabbedForm.spec.js, packages/ra-ui-materialui/src/form/TabbedFormTabs.js
Closes #1689 
A lot of tabs in TabbedForm or TabbedShow make all page wide and scrollable instead of using scrolling tab buttons.
Enable scrollable tabs by default, and add a prop to keep possibility to disable it
```js
<TabbedForm
scrollable={false}
>
```
=> Add scroll buttons to tabs when they go beyond the available space

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
as if you spread values when this is nothing in values, the second parameter to useEffect will have 1 entry.
when there is a something in values, the second parameter to useEffect will have 2 entries. By using lenghth,
there are always 2 entries in the array
=> Change to use length of values with useEffect in AutocompleteArrayInput

packages/ra-ui-materialui/src/layout/Layout.js, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/Sidebar.js
Nothing changes visually by default but it is now easier to have a full height sidebar with a different background. For example:
This only requires a little bit of styling using MUI overrides mechanism
=> Full height Layout & Sidebar margins

packages/ra-input-rich-text/package-lock.json, packages/ra-input-rich-text/package.json, packages/ra-input-rich-text/src/styles.ts
Updated styles for ra-input-rich-text for better dark mode compatibility.
Fixes #5112
[EDIT]
Screenshots
Before:
After:
=> Fix ra-input-rich-text dark theme compatibility 

docs/Reference.md, packages/ra-ui-materialui/src/button/DeleteButton.tsx
Replaces https://github.com/marmelab/react-admin/pull/5056
The `<DeleteButton>` has been built to be used as a child of a `<Toolbar>` in an edit or a list view. Or at least inside a component that injects to it a `record`, a `resource` and a `basePath` props.
But it's not always the case. For example, some user may want to use the `<DeleteButton>` inside the `<TopToolbar>` for styling purpose. And at some step of the loading process, the record could be equals to `null` or `undefined` (if the page is not yet loaded for example).
In the beginning, I thought it was the responsibility of the parent to be sure it passes a record to its child and that's true in general. But I changed my mind because of TypeScript.
If we take a look at the TypeScript type named `Props`, we saw that the record …
=> Prevent crash when passing an undefined record to the <DeleteButton>

docs/CustomApp.md
This update the documentation for "Not Using the `<Admin>` Components" to fix several problems.
- The example `authProvider` does not work (`const authProvider = () => Promise.resolve();`), because `authProvider` is now supposed to be an object instead of a function.
- No `locale` variable is defined.
- No `theme` is provided to the `<ThemeProvider>`.
- `PropTypes` does not exist so it must be imported from the `prop-types` package.
- The `withContext` expects `authProvider` to be a `PropTypes.object` instead of a `PropTypes.func`
- The `Notification` component is not included, while it is necessary for the data provider to work.
The last problem is probably [a bug](https://github.com/marmelab/react-admin/issues/5026) but I think it can be worth documenting it until the bug is fixed.
=> Update "Not Using the <Admin> Components" doc

cypress/integration/create.js, cypress/integration/tabs-with-routing.js, packages/ra-core/src/auth/useLogout.ts, packages/ra-ui-materialui/src/auth/Logout.tsx
=> Fix LogoutButton memorizes last visited page

packages/ra-ui-materialui/src/layout/Sidebar.js
Fixes #4407.
I needed to use custom classes and I did it like this.
I you have a better implementation I'm all ears.
=> Fix Sidebar component classes

cypress/support/ListPage.js, packages/ra-ui-materialui/src/list/Datagrid.tsx, packages/ra-ui-materialui/src/list/DatagridHeaderCell.js, packages/ra-ui-materialui/src/list/DatagridHeaderCell.spec.js
Fixes https://github.com/marmelab/react-admin/issues/5059
Several bugs are fixed:
- Fix the switch between `ASC` and `DESC` orders inside `<ReferenceManyField>` and `<ReferenceArrayField>`
- Fix sorting using another field than the default one or the first selected one
I introduced a new prop named `field` in the `<DatagridHeaderCell>` which contains the same data as the prop named `sort` which is now deprecated.
This renaming is motivated by the confusion introduced by two similar names (sort in `<Datagrid>` and sort in `<DatagridHeaderCell>`) containing different content. The first one contains an object `{ field: 'id', order: 'ASC' }` named `sort` and the second one `{ sort: 'id', order: 'ASC' }`.
=> Fix sorting a list using a <Datagrid> inside a <ReferenceManyField>

docs/CreateEdit.md, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-ui-materialui/src/form/SimpleForm.js, packages/ra-ui-materialui/src/form/TabbedForm.js
Because final-form removes empty / null attributes, SimpleForm needs to recreate them with a `null` value from its initial values.
This is a good default as most REST APIs requires all the fields.
That said, in particular cases, it might conflicts with expected attributes removal, for example:
- A HTTP PUT query that expects field absence to remove them
- A JSON input, that requires to remove a field in the JSON
Moreover, GraphQL APIs don't require all nullable fields to be present in the query.
A workaround would be to create your own form and coping the behavior of `<FormWithRedirect>` (that's what I did in the meanwhile), but I think this is a common enough case, and I this is a good opportunity to document this behavior.
Feel free to edit the PR!
=> Opt out sanitizeEmptyValues with SimpleForm and TabbedForm

packages/ra-core/src/form/FormWithRedirect.tsx
The PR #5077 introduced a DOM warning when using `sanitizeEmptyValues` in a form.
This PR just suppress the warning by destructuring the value from the props.
=> Fix sanitizeEmptyValues DOM warning

docs/Inputs.md
=> Documented <RichTextInput> options prop.

assets/styles.css
Fixes https://github.com/marmelab/react-admin/issues/5166
**Before**
**After**
=> Fix clicking on the documentation link on small screens

packages/ra-data-simple-rest/src/index.spec.ts, packages/ra-data-simple-rest/src/index.ts
Using the simple REST client, I noticed an issue on Chrome : it filters the `Content-Range` header in the response if no `Range` header is specified in the request, which sounds logic (even if perhaps too strict).
=> Send range header in simple REST client getList request

docs/List.md, packages/ra-ui-materialui/src/list/List.spec.js, packages/ra-ui-materialui/src/list/ListView.tsx, packages/ra-ui-materialui/src/types.ts
Fixes #5158
It's sometimes useful to be able to display an empty list instead of displaying a special "empty page" when there's no data to display.
So, here is a small change that allows to display an empty page when the list is empty.
=> Allows List Empty Page Disabling

packages/ra-data-simple-rest/README.md
A `POST` query should call `https://myapi.com/resource` because we cannot know the final record id before creating it.
- Fix the documentation
=> Fix a wrong documentation for the create verb in the simple REST Data Provider package

packages/ra-core/src/controller/ListFilterContext.tsx, packages/ra-core/src/controller/ListPaginationContext.tsx, packages/ra-core/src/controller/ListSortContext.tsx, packages/ra-core/src/controller/useListFilterContext.ts, packages/ra-core/src/controller/useListPaginationContext.ts, packages/ra-core/src/controller/useListSortContext.ts, packages/ra-ui-materialui/src/button/SortButton.tsx
The subcontexts of ListContext are made to avoid depending on the entire ListContext. Yet they are too tiny. the `resource`, for instance, is necessary for buttons. Adding a bit more data makes subcontexts enough for more cases, without adding more rerenders.
=> Fix List subcontext lack resource data

packages/ra-core/src/form/FormWithRedirect.spec.tsx, packages/ra-core/src/form/useInitializeFormWithRecord.ts
=> Fix Form Initialization from Record

packages/ra-ui-materialui/src/field/ChipField.tsx
Hi,
This pull request improves some of the user experience when using \<ChipField> as the child of \<ReferenceField>.
The original implementation of the ChipField uses \<div> to wrap around a \<span>. When the ChipField is used in Referencefield, only the margins of that \<div> will have cursor as pointer when moved to it, and the text in the ChipField will display default cursor. This is not very intuitive for user to click on that chip.
The patch will make \<div> in ChipField inherit the cursor and offer better user experience.
=> Make cursor inherit pointer in ChipField when wrapped in <ReferenceField>

packages/ra-ui-materialui/src/list/Datagrid.tsx, packages/ra-ui-materialui/src/list/DatagridBody.tsx, packages/ra-ui-materialui/src/list/DatagridCell.tsx, packages/ra-ui-materialui/src/list/DatagridRow.tsx
Close #5194 
`DatagridRow` ref doesn't cover expanded row. It can be controversial in my thought.
I made this commit on next branch because react guides [use of forwardRef is breaking change](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers).
=> Forward ref in data grid element

packages/ra-core/src/auth/useGetIdentity.ts
=> Fix useGetIdentity fails when there is no authProvider

packages/ra-core/src/dataProvider/useDataProvider.ts
Before this fix, if you had a `<List>` with a `<DeleteButton undoable>` on every line, deleting multiples records one after the other would end up with an invalid state. Removed items would still appear in the list even if the server call was made.
=> Fix Optimistic Effects Handling

packages/ra-ui-materialui/src/list/ListToolbar.tsx
When you define `actions={false}` in `<List />`, you have warning about ListToolBar proptypes. 
`<ListToolBar />` is create by `<ListView />`, I define the same props as [ListView propttypes](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/ListView.tsx#L112) and [List proptypes](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/List.tsx#L73).
=> fix: warning proptypes in ListToolBar component

packages/ra-data-simple-rest/README.md, packages/ra-data-simple-rest/src/index.spec.ts, packages/ra-data-simple-rest/src/index.ts
Historically, Simple REST Data Provider uses the http `Content-Range` header to retrieve the number of items in a collection. But this is a *hack* of the [primary role of this header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range).
And this can be problematic, for example within an infrastructure using a Varnish that may use, modify or delete this header. We also have feedback indicating that using this header is problematic when you host your application on [Versel](https://vercel.com/).
The solution is to use another http header to return the number of collection's items.
**This PR introduces a third optional parameter to the `simpleRestProvider` allowing to define this header.**
=> simpleRestProvider: using a custom http header to count items in a collection

packages/ra-core/src/form/getFormInitialValues.spec.ts, packages/ra-core/src/form/getFormInitialValues.ts
=> Support function for initialValues

packages/ra-ui-materialui/src/list/filter/FilterForm.tsx, packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
In lists pages, the filter form have a top margin that makes it highter than the inputs looks.
When placing something upper than the filer form, it is covered by this margin, and very difficult to click on.
Use css pointer properties to disable click on this invisible margin, and allow click on the components displayed under it.
=> Fix filter margin-top that create an invisible overlay

packages/ra-core/src/auth/useLogin.ts
=> Changed code to use pathName first (if exists) for redirect after login

docs/CreateEdit.md
Fixes https://github.com/marmelab/react-admin/issues/5195
=> Add onSuccess Callback Infos about undoable prop

examples/demo/src/reviews/BulkAcceptButton.tsx, examples/demo/src/reviews/BulkRejectButton.tsx, packages/ra-core/src/controller/useListController.ts
This fix avoid resetting current page (in a list) when the total is resetted (during loading phase).
This way, the demo "reviews" page don't go to the first page when we accept or reject a review.
I also removed the redirect to "/reviews" when we accept or reject reviews in bulk mode. This way we stay on the current page of reviews
=> Fix unexpected List Page Change

packages/ra-core/src/auth/useCheckAuth.spec.tsx, packages/ra-core/src/auth/useCheckAuth.ts, packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx, packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
=> Ability to disable notifications of useCheckAuth and useLogoutIfAccessDenied hooks

docs/Fields.md, packages/ra-ui-materialui/src/field/BooleanField.tsx
Implements https://github.com/marmelab/react-admin/issues/5283
=> Add ability to pass BooleanField custom icons to show as values

docs/DataProviders.md
Added a link to a data provider I added today, that is simply taking the ra-data-simple-rest provider and giving it a  configuration hash of resourceName:identityName values so that it can map between 'id' and the real identity property name in HTTP communication.  Simple.  And React-admin continues to work as it always has, but people get to avoid changing their server-side API.
=> Add documentation of Data Provider

docs/CreateEdit.md
Fixes https://github.com/marmelab/react-admin/issues/5220
The documentation about the `<SaveButton>` disable mechanism is confusing when the `<Toolbar>` is customized. So I added an explanation and an example about how to restore this mechanism.
=> Improve the documentation of the SaveButton when customizing the Toolbar

packages/ra-core/src/controller/useCreateController.ts, packages/ra-core/src/controller/useEditController.ts, packages/ra-core/src/controller/useShowController.ts, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/detail/Create.tsx, packages/ra-ui-materialui/src/detail/Edit.tsx, packages/ra-ui-materialui/src/detail/Show.tsx, packages/ra-ui-materialui/src/layout/index.ts
Many of the props are now optional because they are injected by react-admin. This was preventing usage such as passing a `Show` view inside an `expand`
=> More TS fixes

packages/ra-core/src/sideEffect/fetch.ts
Redux-saga-core can throw undefined as error.
=> Update fetch.js: handle null case

packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts
No code change necessary, I just used [an UTF8 Em Space character](https://www.compart.com/en/unicode/U+2003) in the translations. The fix will have to be done in each translation.
Refs #5311
=> Fix NullableBooleanInput empty value isn't selectable

index.html
In the [react-admin public website](https://marmelab.com/react-admin), the last testimonial is not reachable.
**Final testimonial is now reachable**
**Looping on the testimonials**
=> Fix the last testimonial which is not reachable

docs/Theming.md
I was getting this error when trying UserMenu customizaton:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
I changed how MyAppBar is passed to Layout. From `{<MyAppBar />}` to `{MyAppBar}` Seems ok now. It looks like Layout is not expecting component that way.
=> Fix theming docs UserMenu example

packages/ra-data-graphql/src/introspection.js, packages/ra-data-graphql/src/introspection.test.js
See https://github.com/marmelab/react-admin/issues/4933 for background info. But, right now all resources in the GQL data provider must implement both a GET_ONE and a GET_LIST for a resource to actually be considered a resource. This is very limiting because there is no workaround for a resource that only has a GET_ONE. 
What this PR does is move the include/exclude logic to before the check that a resource has a GET_ONE and GET_LIST. If a resource is included or excluded, it will short circuit and either include or exclude the resource, regardless of the GET_ONE/GET_LIST check. 
This solution is pretty solid in my opinion -- it is totally backward compatible, it allows users who want to include a resource that is a bit nonstandard to do so by explicitly setting a configuration object, …
=> ra-data-graphql: Update include/exclude introspection logic

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
Fixes #5309 
I don't see how to test the `<DeleteWithUndoButton onFailure={onFailure} />` use-case.
=> Add onSuccess and onFailure properties to DeleteButton

docs/Inputs.md, packages/ra-ui-materialui/src/input/NullableBooleanInput.spec.tsx, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
Hi, I would like to customize the labels of the options of the `NullableBooleanInput` control.
=> Allow the option labels of NullableBooleanInput to be customized

Makefile, docs/DataProviders.md, examples/demo/package.json, packages/ra-data-fakerest/src/index.ts, packages/ra-data-localstorage/README.md, packages/ra-data-localstorage/package.json, packages/ra-data-localstorage/src/index.ts, packages/ra-data-localstorage/tsconfig.json, yarn.lock
An admin can use localStorage for part of or all the underlying data. A localStorage dataProvider opens the possibility to build local-first admins.
```jsx
import localStorageDataProvider from 'ra-data-local-storage';
const dataProvider = localStorageDataProvider();
```
Uses `ra-data-fakerest` under the hood, synchronizing changes between the FakeRest (in-memory) and localStorage databases. It also hides warnings for undefined collections, and allows the addition of a record to an undefined collection.
Note that localStorage is limited to 5MB in size.
=> Add localStorage data provider

packages/ra-ui-materialui/src/detail/TabbedShowLayout.js, packages/ra-ui-materialui/src/detail/TabbedShowLayout.spec.js
=> Fix TabbedShowLayout resolves path incorrectly if first tab is null

docs/Reference.md
I always reach https://marmelab.com/react-admin/Reference.html . Not finding DateTimeInput here was confusing.
Thanks for this package.
=> Fix missing link to <DateTimeInput> in reference documentation

packages/ra-ui-materialui/src/detail/Tab.tsx, packages/ra-ui-materialui/src/detail/index.ts
=> Convert Tab component to TypeScript

examples/demo/README.md
src/App.js doesn't exist, src/App.tsx does.
=> Fix wrong link in shop demo's README

.gitpod.yml, README.md
This Pr updates the config to open the preview of port 8080 on Gitpod workspace startup with this change in place a workspace once started will look like the following:
Also I have added a Open in Gitpod button + a bit of description in the Readme so that more people can benefit from it.
=> add open in Gitpod button + update config to open preview of port 8080 on workspace startup.

packages/ra-core/src/form/useInitializeFormWithRecord.ts
Importing `lodash` instead of `lodash/merge` was having an impact in the `ra-core` import size for `examples/demo`.
This is `lodash` footprint before the change:
And after:
=> Strip down lodash footprint by loading only the required utility

packages/ra-core/src/controller/useCreateController.spec.tsx, packages/ra-core/src/controller/useEditController.spec.tsx, packages/ra-core/src/core/dataFetchActions.ts, packages/ra-core/src/dataProvider/useDataProvider.spec.js
=> Fix dataProvider fails silently when response has wrong type

packages/ra-ui-materialui/src/detail/Tab.tsx
I noticed the Tab component was missing a type for the `path` prop, which still works fine but makes TypeScript complain.
=> Add missing "path" type for Tab component

docs/DataProviders.md
=> [Doc] Add warning about inconsistent record shapes in custom data provider instructions

docs/CreateEdit.md
=> [Doc] Remove Input defaultValue syntax with a function

docs/Inputs.md
=> [Doc] Fix linking two inputs example

docs/List.md, examples/demo/src/categories/LinkToRelatedProducts.tsx, examples/demo/src/segments/LinkToRelatedCustomers.tsx
=> [Doc] Fix Link to filtered list snippet incorrectly requires all query parameters

packages/ra-ui-materialui/src/layout/HideOnScroll.tsx, packages/ra-ui-materialui/src/layout/index.ts
=> Fix missing TypeScript types for AppBar and other layout components

packages/ra-core/src/controller/useListController.ts, packages/ra-core/src/controller/useListParams.ts, packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
The `useListController` hook returned show and hide filter functions based on the debounced setFilters function. No need to debounce (and to wait for 500 millisecons) to show or hide a filter!
Also, the FiltrListItems (for the ListSidebar) don't need a 500ms delay either. 
This improves filtering UX in a noticeable way.
=> Speed up show & hide filter

packages/ra-data-graphql-simple/src/buildVariables.js
If the `id` field of an entity has a non null type like `Int!`, it cannot be edited with the `Edit` screen.
The problem was the `castType` function not handling types with `NON_NULL` kind which wraps the real type under a `ofType` property.
closes #5400
=> Fix non null id types handling

packages/ra-ui-materialui/src/defaultTheme.ts, packages/ra-ui-materialui/src/index.ts
Fixes #5426
This is only the beginning. Indeed there is a lot of work in order to provide type safe overrides.
See how MUI does it:  https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/overrides.d.ts#L103
I also wonder if our approach for the Sidebar `size` and `closedSize` configuration is correct. Maybe we should just rely on props with defaults (which can be overridden through the theme as well (https://material-ui.com/customization/globals/#default-props). This would lead to a single entry to customize the sidebar instead of two (`sidebar` at the theme root and `RaSidebar` in the `overrides`)
We would have to export the class keys for every component like this:
```ts
export type SidebarClassKey = keyof ReturnType<typeof useStyles>;
```
This could be a …
=> Add type for theme

packages/ra-core/src/dataProvider/Mutation.tsx, packages/ra-core/src/dataProvider/Query.spec.tsx, packages/ra-core/src/dataProvider/Query.tsx, packages/ra-core/src/dataProvider/getDataProviderCallArguments.ts, packages/ra-core/src/dataProvider/useDataProvider.spec.js, packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts, packages/ra-core/src/dataProvider/useMutation.spec.tsx, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-core/src/dataProvider/useQuery.ts
=> Relax useDataProvider signature to ease custom methods usage

docs/Theming.md, packages/ra-ui-materialui/src/layout/AppBar.tsx
Fixes https://github.com/marmelab/react-admin/issues/5419
> Sometimes applications are not required to have any users.
> For that purpose I think it would be a great idea to pass userMenu={false} as a prop in a custom AppBar component.
Using `false` without a `true` option may be confusing. So I use `null` instead.
```js
// examples/simple/src/Layout.js line 42
const MyAppBar = props => <AppBar {...props} userMenu={null} />;
```
=> Allow to disable the UserMenu without rewriting the AppBar

packages/ra-core/src/dataProvider/Query.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx
By reading Travis's logs, I saw some warnings. So I'm correcting them.
```
/home/travis/build/marmelab/react-admin/packages/ra-ui-materialui/src/field/ReferenceField.tsx
181:13  warning  The attribute aria-errormessage is not supported by the role presentation  jsx-a11y/role-supports-aria-props
```
=> Fix several eslint warnings

packages/ra-ui-materialui/src/layout/LoadingIndicator.js
The size of the spinner isn't exactly the same as the size of the refresh button. As a consequence, if the AppBar has a custom content, this content moves a bit when the app loads data.
Making the size of the two components match exactly fixes the bug.
=> Fix Appbar custom content flickers when loading

packages/ra-ui-materialui/src/layout/Sidebar.tsx
=> Fix Custom Menu doesn't always receive onMenuClick prop

docs/Fields.md, docs/Inputs.md, docs/_layouts/default.html, docs/css/style-v7.css
The fields and Inputs doc table of content are intimidating because they show too much content. Besides, the toc is too long and doesn't show the last elements on small screens
Users use the reference and full-text search to get to a given input doc anyway, so let's use heading levels for discoverability.
Add a new heading level and group Inputs and Fields by category
=> [Doc] Group Inputs and Fields in documentation to allow better discoverability

docs/List.md
- link to a section has a wrong title (confusing since the link text isn't in the ToC)
- typos
- wording
=> Minor doc fixes

examples/demo/src/dashboard/Dashboard.tsx, examples/demo/src/dashboard/NewCustomers.tsx, examples/demo/src/dashboard/OrderChart.tsx
=> [Demo] Fix chart gets empty at the end of the month

packages/ra-ui-materialui/src/detail/Show.tsx
Prevents having `hasShow` on a `div` element, because `React` complains about this
```
Warning: React does not recognize the `hasShow` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasshow` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by ShowView)
in ShowView (created by Show)
```
=> fix: add default value for hasShow in Show.tsx

examples/demo/src/visitors/Aside.tsx
=> [Demo] use stepper for customer actions

examples/demo/src/layout/Layout.tsx, examples/demo/src/layout/Menu.tsx, examples/demo/src/layout/themes.ts, packages/ra-core/src/core/CoreAdminRouter.tsx, packages/ra-core/src/core/CoreAdminUI.tsx, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/index.ts
=> Fix layout component type

packages/ra-ui-materialui/src/button/ShowButton.tsx
Identical to #5014, ShowButton doesn't update if 'to' prop changes. My goal was to make the edit and show buttons work consistently with tabbed layouts, when a tab is opened in the show view the edit button should open the same tab in the edit view. Due to memoizing it didn't always work and now it does.
=> Fix ShowButton does not update on 'to' prop change

packages/ra-core/src/inference/index.ts, packages/ra-core/src/inference/inferTypeFromValues.ts, packages/ra-core/src/inference/inferTypesFromValues.spec.ts
The inference helpers return React elements. That makes the inference logic impractical to serialize, store, and edit by the end user. 
Expose an inference helper that returns serialized types instead of elements.
=> Add ability to infer field type from data

examples/simple/src/users/UserEdit.js, packages/ra-core/src/dataProvider/useDataProvider.ts
=> Fix crash when navigating away during undo period

packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.tsx, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
As `<FieldTitle>` now uses `useRecordContext`, field and input titles in Reference element sis wrong unless we change the resource context.
Supersedes #5461
=> Change RecordContext in Reference elements

docs/Ecosystem.md, docs/Show.md
This proposal PR is in regards with a little plugin I have started building for the react-admin as I have used it extensively over the past year and decided to share privately developed components. 
Hope you will find it a useful project to the community and if it is not following any guidelines I will be more than happy to  refactor it's current state.
Wasn't sure if I should include it only on the Miscellaneous list in Ecosystem page but decided to rather place it in the Show page instead. I have noticed this is still quite hot topic on stackoverflow and people keep searching for ways to easily customize show layout. 
I am planning on sharing some more fields and inputs components but my intention is to link them to documentation anchors to the relative pages' third party sections like …
=> Added ra-compact-ui to ecosystem docs

UPGRADE.md, docs/CreateEdit.md, docs/Fields.md, docs/Inputs.md, docs/Resource.md, docs/Theming.md, examples/README.md, packages/ra-data-graphql/README.md
Some anchors referencing external libraries are kind of hidden in the docs.
I've changed them to show the anchor (blue) color
=> Improve some docs anchors visibility

packages/ra-core/src/dataProvider/getDataProviderCallArguments.ts, packages/ra-core/src/dataProvider/useDataProvider.spec.js
=> Fix useDataProvider throws options is undefined error when called without arguments

packages/ra-core/src/export/downloadCSV.ts
Recently I needed to change the output encoding (text/csv;charset=utf-8) of the csv file. I had to reimplement it at my side because currently there is no way to  plug in at the type sport and customize the output. 
That's why I am proposing this extended parameter with default value if nothing is passed in.
=> Extended downloadCSV helper with type paramater

examples/simple/src/comments/PostReferenceInput.js, packages/ra-core/src/controller/input/useReferenceInputController.ts
=> Fix useReferenceInputController sorting

docs/DataProviders.md
fixed "create" method endpoint url (removed /123)
=> [Doc} Fix sample REST translation of dataProvider calls 

docs/Tutorial.md
fixed "Create a record" endpoint url (removed /123)
=> [Doc] Fix sample REST translation of dataProvider calls in Tutorial

docs/Admin.md
This is the only way we can overcome the problem caused by a bug in one of our dependencies (`connected-react-router`). By the way, this dependency seems not to be actively maintained anymore, and this could cause further problems in the future. 
Closes #5450
=> Fix `<Admin history>` prop injection documentation misses package version constraint

docs/Theming.md
- typo
- no error page in example, so I removed the mention in the text
- I added a comment in the text itself, another occurrence of something mentioned in text that doesn't appear in code.
So I guess you have some fixing to do before merging.
=> Fix typos in Theming doc

packages/ra-core/src/core/CoreAdminRouter.tsx, packages/ra-core/src/core/CoreAdminUI.tsx, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/layout/LoadingPage.tsx, packages/ra-ui-materialui/src/layout/index.ts, packages/react-admin/src/AdminRouter.tsx, packages/react-admin/src/AdminUI.tsx
Hello !
I've seen the loading page miss my material-ui theme palette configuration and display the default "blue" color for the `<CircularProgress />` component
The issue is mainly caused because `<Loading />` component isn't wrapped in a `<ThemeUIProvider />` when used in `CoreAdminRouter`, so I created a `<LoadingPage />` handling this use case
=> Fix Loading route missing theme with LoadingPage

packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
If the filter value is a nested object, the component is unable to find out if it is selected.
=> Fix FilterListItem doesn't accept object values

packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx
=> Fix ReferenceField doesn't accept the emptyText prop

packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> Fix logout causes error in useGetList

packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
The `ReferenceArrayInput` component is not using the `getFieldLabelTranslationArgs` function like the `FieldTitle` component (used by the other inputs: `ReferenceInput`, `TextInput`, ...).
The difference is that, if no label is given and if there is no translation, the label is not humanized by default.
Before:
After:
=> Use getFieldLabelTranslationArgs in ReferenceArrayInput

packages/ra-core/src/auth/WithPermissions.tsx, packages/ra-core/src/auth/index.ts, packages/ra-core/src/auth/usePermissions.ts, packages/ra-core/src/auth/usePermissionsOptimized.ts
All react-admin routes (list, edit, create, etc) are wrapped by `WithPermissions`. This component renders the page content optimistically with empty permissions, then calls `authProvider.getPermissions()`, and passes the result to the child.
In many cases, this means the routes will render twice: once with empty permissions, and once with the permissions returned by the `authProvider`. 
`WithPermissions` calls `authProvider.getPermissions()` with empty params. In many cases, the result of this call is always the same.
`useGetPermissions` can cache the result from the first call, and initialize its state with it. 
that way, in most cases, the return from  `authProvider.getPermissions()` will be the same as the cached one, and we'll save a re-render.
This should git a short perf boost to …
=> Fix usePermissions always triggers a re-render even though the permissions are unchanged

packages/ra-core/src/dataProvider/useGetMany.ts
`ReferenceManyField` rerenders whenever something in the resource changes. even unrelated changes like selected ids. This wastes CPU time and slows down List page interactions (a bit).
Fix the data selector in `useGetMany`, which uses `reselect` to memoize the result... But has a too broad dependency  array.
Check the Tags column: all rows rerender when only one row is selected
Now only the selected row rerenders
=> Fix ReferenceManyField renders too often

examples/simple/src/Layout.js, examples/simple/src/posts/PostList.js, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/core/CoreAdminUI.tsx, packages/ra-ui-materialui/src/field/BooleanField.spec.tsx, packages/ra-ui-materialui/src/field/BooleanField.tsx, packages/ra-ui-materialui/src/layout/AppBar.tsx
These changers save some rerenders when profiling the simple app using the React profiler. Yet they have no perceivable effects on performance in ms.
So, let's consider this as a cleanup PR.
=> Fix useless AppBar rerenders

packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput.tsx
=> Add support for disabled in ArrayInput

docs/CreateEdit.md, docs/Inputs.md, examples/simple/src/users/UserCreate.js, packages/ra-core/src/form/validate.spec.ts, packages/ra-core/src/form/validate.ts, packages/ra-ui-materialui/src/input/ArrayInput.tsx
It's currently possible to pass an async validation function if, and only if, this is either the only validator or the last one inside the validation functions array.
This PR aims at providing real support for async validation functions.
=> Add better support for async validators

docs/Theming.md
Avoid all color changes when just changing sidebar size. See [this issue](https://github.com/marmelab/react-admin/issues/5426)
=> [Doc] Fix sidebar size change resets the theme color

packages/ra-ui-materialui/src/list/filter/FilterListItem.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
Fixes a regression introduced by #5559 
Added unit tests to avoid regressions in the future
=> Fix FilterListItem doesn't appear selected when more than one filter is applied

docs/Admin.md, examples/demo/src/App.tsx, packages/ra-core/src/core/CoreAdmin.tsx, packages/ra-core/src/core/CoreAdminUI.tsx, packages/ra-core/src/types.ts, packages/react-admin/src/Admin.tsx
In production, react-admin applications will send an anonymous request on mount to a telemetry server operated by marmelab. You can see this request by looking at the Network tab of your browser DevTools:
`https://react-admin-telemetry.marmelab.com/react-admin-telemetry`
The only data sent to the telemetry server is the admin domain (e.g. "example.com") - no personal data is ever sent, and no cookie is included in the response. The react-admin team uses these domains to track the usage of the framework.
You can opt out of telemetry by simply adding `disableTelemetry` to the `<Admin>` component:
```jsx
// in src/App.js
import * as React from "react";
import { Admin } from 'react-admin';
<Admin disableTelemetry>
// ...
</Admin>
);
```
=> Add domain telemetry on app mount

examples/demo/src/layout/Login.tsx, packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-core/src/controller/details/useCreateController.spec.tsx, packages/ra-core/src/controller/details/useCreateController.ts, packages/ra-core/src/controller/details/useEditController.ts, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/controller/field/useReferenceManyFieldController.ts, packages/ra-core/src/controller/useListController.ts, packages/ra-ui-materialui/src/auth/LoginForm.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
Server error messages are seldom translated. And the `useNotify` hook logs a warning in the console for every missing translation. This pollutes the console a great deal and harms developer experience. 
Provide default translation for dataProvider error notifications (the untranslated message). This will remove the warnings for untranslated server errors.
We do this in every call to useNotify in return to dataProvider errors instead of in useNotify itself, because useNotify is often called with error codes that need to be identified as mission transltions.
=> Fix "Missing translation" console error when the dataProvider fails

packages/ra-core/src/controller/useListParams.spec.tsx, packages/ra-core/src/controller/useListParams.ts
=> Fix Filter fails to show compound filters with no default value

docs/Fields.md
Added the Function type of the link parameter in the reference table under the section - ReferenceField.
=> [Docs] - Edited ReferenceField params table - link type description

packages/ra-ui-materialui/src/layout/Confirm.tsx
The `minWidth` style attribute in `<Confirm>` dialog should be removed. It doesn't make the dialog look much better and it adds a scroll bar for the contents on mobile.
Vanilla:
Fixed:
I use this component in my own code too and it's even worse when the confirmation text is long enough.
=> Remove min width in confirmation dialog

docs/Theming.md
=> [Doc] Fix custom theme doc doesn't explain how to override default theme

packages/ra-core/src/controller/useListController.ts, packages/ra-core/src/controller/useListParams.ts, packages/ra-ui-materialui/src/button/ExportButton.tsx, packages/ra-ui-materialui/src/types.ts
=> Fix ExportButton doesn't take permanent filter into account

packages/ra-ui-materialui/src/input/SearchInput.tsx
Reverts marmelab/react-admin#5684 because we may want the autocomplete activated for search. Besides, you can already override this by providing your own `InputProps`
=> Revert "Fix for autocomplete off #5620"

packages/ra-core/src/actions/notificationActions.ts, packages/ra-ui-materialui/src/layout/Notification.tsx
=> Add support for success notification type

packages/ra-ui-materialui/src/form/SimpleForm.tsx
Related to #5696.
So `CardContentInner` component could be overriden inside `SimpleForm` component.
I have to use `container` instead of `component` since react-final-form's `FormRenderProps` already has a `component` prop
=> Add component prop to SimpleForm

packages/ra-core/src/core/useResourceContext.ts, packages/ra-ui-materialui/src/detail/EditGuesser.tsx
Using EditGuesser as explained in the Tutorial throws the following error:
> TypeError: Cannot read property 'save' of undefined.
=> Fix EditGuesser is broken

docs/List.md
=> [Doc] Fix custom query with Datagrid example uses incorrect resource

packages/ra-core/src/controller/input/ReferenceInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceInputController.ts
To test this, I forced a `dataProvider` waiting longer for `getList` and `getMany`, and loaded the `CommentEdit` page in the simple example. I saw that no loader was shown. 
This is also mentioned as a gotcha in StackOverflow (https://stackoverflow.com/questions/65488613/react-admin-referenceinput-doesnt-show-loading-linearprogress-while-loading).
The fix uses the `loaded` state from the two `dataProvider` calls rather than the convoluted logic from `getDataStatus`.
=> Fix ReferenceInput does not show loader while possible values and reference record are loading

packages/ra-core/src/core/useResourceContext.ts, packages/ra-ui-materialui/src/detail/Create.tsx, packages/ra-ui-materialui/src/detail/Edit.tsx, packages/ra-ui-materialui/src/detail/Show.tsx
Closes #5662
Although the `<Create>`, `<Edit>` and `<Show>` components were never meant to be used outside of `<Resource>` props, developers have taken the habit to use them in standalone, passing the `resource` as prop. The fact that it worked was undocumented, but intuitive and practical.
The introduction of the `<ResourceContextProvider>` broke this. An attempt to use `<Create resource="foos">` fails - the user has to wrap the component in a `<ResourceContextProvider>`.
We recognize that `<Create>`, `<Edit>` and `<Show>` should be usable outside of `<Resource>`, so they should be able to create their own `<ResourceContextProvider>` when passed a `resource` prop.
=> Fix Create, Edit and Show cannot be used outside of a ResourceContextProvider

packages/ra-ui-materialui/src/layout/UserMenu.tsx
On login error or when cleaning the local storage, `identity` becomes `undefined`. As the `UserMenu` rendering occurred before the logout via `checkError` something else, we must check for `identity` existence before rendering the `UserMenu` to prevent the 
> Cannot read property 'fullName' of undefined
=> fix: identity can be undefined on error and must be checked

packages/ra-ui-materialui/src/detail/EditGuesser.tsx, packages/ra-ui-materialui/src/detail/ShowGuesser.tsx
Uniformize how guessers get their resource and record.
Properly get the resource from context.
=> Ensure Guessers properly retrieve their contexts

packages/ra-core/src/controller/input/ReferenceInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceInputController.ts
Reverts marmelab/react-admin#5731 as it bring another bug: #5757
The solution will be to give the loading status handling responsability to the ReferenceInput child
=> Revert "Fix ReferenceInput does not show loader while possible values and reference record are loading"

docs/Inputs.md
The doc added in #5396 was removed by mistake in 8f4c02bf75689c566478ce7e247909e1e5893674
=> [Doc] Fix <AutocompleteInput resettable> prop isn't documented

packages/ra-core/src/dataProvider/useDataProvider.ts
Closes #5685
This was introduced in #4291, where I used the same code for optimistic and non-optimistic calls. If it make sense to re-throw the error in non-optimistic mode (so that the dataProvider promise rejects), it doesn't make sense in optimistic mode, as the dataProvider promise already resolved. So the error mustn't be rethrown in optimistic mode.
=> Fix uncaught error when dataProvider fails on undoable forms

packages/ra-core/src/types.ts
ref https://github.com/marmelab/react-admin/pull/5771#issuecomment-760469318
The return type of `Exporter` has been wrong, this pull request fixes it.
=> Fix return type of Exporter

cypress/integration/navigation.js, cypress/package.json, cypress/support/ListPage.js, cypress/support/index.js, packages/ra-ui-materialui/src/layout/MenuItemLink.tsx, yarn.lock
I've tested this manually. 
I haven't added any unit tests, but I'll be happy to add an integration test that ensures that the menu item is reachable via the tab button.
https://user-images.githubusercontent.com/17087167/104582931-6960e280-5658-11eb-9a30-199813357f3b.mov
=> Make NavMenu Keyboard Navigable

cypress/integration/edit.js, cypress/support/EditPage.js, packages/ra-core/src/form/useInitializeFormWithRecord.ts
=> Fix Warning Avout Unsaved Change

packages/ra-core/src/actions/notificationActions.ts, packages/ra-core/src/auth/useLogin.ts, packages/ra-core/src/reducer/admin/notifications.ts
When an unlogged user tries to access a restricted page, the page calls the dataProvider, which returns a 403 response. This redirects the user to the login page with a "please login to continue" notification. This is correct, but:
- Users may enter and submit credentials faster than the notification hide delay
- The restricted page may make several calls to the dataProvider, each returning with a 403, and each pushing a new "please login to continue" notification to be displayed once the previous has hidden. 
In both cases, once the user has logged in, they still see the "Please login to continue" notification *while the page displays restricted data*, which is confusing.
Reset notifications upon login
=> Fix "Please login to continue" notification remains after login

packages/ra-data-json-server/README.md
The Create method API URL does not have an ID.  The resource is not
created yet.
Fixes #5792
=> Fix Create method API call URL example

packages/ra-data-graphql/src/index.js
Providers based on `ra-data-graphql` can throw sync errors when there is  problem. `useDataProvider` complains about that:
> Unhandled Rejection (Error): The dataProvider threw an error. It should return a rejected Promise instead.
Return a rejected Promise instead.
Closes #5788
=> Fix "dataProvider should return a rejected Promise" error in GraphQL providers

docs/CreateEdit.md, packages/ra-core/src/dataProvider/Mutation.tsx, packages/ra-core/src/dataProvider/useMutation.spec.tsx, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/form/useInitializeFormWithRecord.ts, packages/ra-ui-materialui/src/detail/CreateView.tsx, packages/ra-ui-materialui/src/detail/EditView.tsx, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/Labeled.tsx, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/input/TextInput.tsx
Fixes #4703.
Fixes #4351.
Returning a promise in the `submit` function is essential for handling correctly submission errors: https://final-form.org/docs/react-final-form/types/FormProps#3-asynchronous-with-a-promise.
It has been discussed in this issue too: #4351.
`useCreateController` and `useEditController` hooks are already returning a promise resolving to `undefined` for the `save` function: it will not break anything.
To handle submission errors, the custom `save` function could be implemented by using the `useDataProvider` hook, like this: https://github.com/bmihelac/react-admin/commit/1a9f02b65f1342c695a10b5aad7a6a63603fb9ba.
In order to be able to use the `useMutation` hook too, a `returnPromise` option has been added, like asked in @fzaninotto's comment: …
=> Handle submission validation errors

docs/CreateEdit.md
A reference to the `undoable` prop in the `Create` component was still present in the documentation.
=> [Doc] Undoable is for edit only

cypress/integration/navigation.js, cypress/support/ListPage.js, packages/ra-language-english/src/index.ts, packages/ra-ui-materialui/src/button/SkipNavigationButton.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx
I messed up the rebase, and I'm just opening up a new PR with the same changes. 
I've added a button inside of `Layout.tsx` that only displays when the first action a user performs on a RA site is pressing the tab button.
This moves the focus into the main content of the website, avoiding having to tab through the top and side menus.
While the functionality is complete, I'm going to write Cypress tests for this functionality.
Notes:
Because navigating to anchors via the `#` didn't seem to work nicely with `HashRouter`, I had to install an node module that exports a custom link. [Here's a link to the discussion](https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604)
Fortunately the module has no dependencies, and it works out of the box.
I implementing this …
=> Add skip navigation button

packages/ra-core/src/auth/usePermissionsOptimized.spec.tsx, packages/ra-core/src/auth/usePermissionsOptimized.ts
When an app has two components calling `<WithPermissions>` on the same render phase, a race condition used to lead the second call to never return the actual permissions.
```jsx
const Test = () => (
<>
<WithPermissions component={Foo} />
<WithPermissions component={Bar} />
</>
);
```
`Foo` was rendered once with empty permissions, then rerendered with the permissions Fetched from the authProvider.  
`Bar` was only rendered once, with empty permissions. 
This was a bug due to the permissions from the authProvider being compared to the cache rather than to the initial state.
=> Fix race condition in WithPermissions

docs/DataProviders.md
Hasura have replaced their original (V1) data provider with https://github.com/Steams/ra-data-hasura-graphql.
There is now only one Hasura data provider: https://github.com/hasura/ra-data-hasura
=> Update docs with latest Hasura Data Provider

cypress/integration/edit.js, cypress/support/EditPage.js, examples/simple/src/posts/PostEdit.js, packages/ra-core/src/form/useFormGroup.ts, packages/ra-ui-materialui/src/form/FormTab.tsx, packages/ra-ui-materialui/src/input/TranslatableInputsTab.tsx
=> Fix Regression on ArrayInput children validation

docs/Actions.md, docs/CreateEdit.md
=> [Doc] Fix onSuccess callback signature for optimistic and undoable queries

docs/List.md, examples/simple/src/tags/TagEdit.js
`ResourceContextProvider` should take a `value` prop, not `resource`
=> Fix typo in docs

docs/Fields.md, docs/Reference.md
Fixes https://github.com/marmelab/react-admin/issues/5801
=> [Doc] Add documentation for `linkToRecord`

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-core/src/controller/details/SaveContext.tsx, packages/ra-core/src/controller/details/useCreateController.ts, packages/ra-core/src/controller/details/useEditController.ts, packages/ra-core/src/controller/saveModifiers.tsx, packages/ra-core/src/dataProvider/performQuery/QueryFunctionParams.ts, packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts, packages/ra-core/src/dataProvider/useDeclarativeSideEffects.ts, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-core/src/dataProvider/useQuery.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/sideEffect/fetch.ts, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/form/TabbedForm.tsx, packages/ra-ui-materialui/src/types.ts
=> [TypeScript] Fix onSuccess / onFailure types

packages/ra-core/src/i18n/TranslationMessages.ts
Fix missing type for 'ra.navigation.skip_nav' translation message.
https://github.com/marmelab/react-admin/commit/d5d4a47e3f713cc1335a7032ca7ff17f27db078a#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
=> Fix missing type for 'ra.navigation.skip_nav' translation message

packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
=> Fix ArrayInput Always Override Inputs disabled Prop

packages/ra-core/src/dataProvider/useGetManyReference.ts
This fixes a nasty bug that is hard to reproduce. 
The bug occurs when a `ReferenceManyField` renders a second time after the reference data has been updated on the server-side, and if the children of the ReferencenceManyField don't work with an empty `record`. This causes a "Something Went Wrong" screen in production.
A more specific bug repro: 
- in `PostEdit`, change the final tab to 
```jsx
<FormTab label="post.form.comments">
<ReferenceManyField
reference="comments"
target="post_id"
addLabel={false}
fullWidth
perPage={2}
>
<Datagrid>
<FooField label="foo" />
</Datagrid>
</ReferenceManyField>
</FormTab>
```
with 
```
// this will fail if record is undefined
const FooField = ({ record }) => <span>{record.foo}</span>;
```
- go to posts list
- click on edit post 2
- go to comment list
- …
=> Fix ReferenceManyField throws error after insert

packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
In order to customise the layout of a form in `SimpleFormIterator`, I need to use the `classes` props. It works but the TS definition was not allowing it.
This simply adds the `classes` prop.
=> [Typescript] Add missing classes prop on SimpleFormIterator

packages/ra-core/src/form/useInput.ts
=> added possibility to pass isRequired as option to useInput hook

packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
Currently if we use `Datagrid` outside of `List` component (e.g. in a `Show` view), if we don't pass `selectedIds={[]}`, it throws such an error:
```
DatagridBody.js:52 Uncaught TypeError: Cannot read property 'includes' of undefined
at DatagridBody.js:52
at Array.map (<anonymous>)
at DatagridBody.js:32
at renderWithHooks (react-dom.development.js:14803)
at updateForwardRef (react-dom.development.js:16816)
at beginWork (react-dom.development.js:18645)
at HTMLUnknownElement.callCallback (react-dom.development.js:188)
at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
at invokeGuardedCallback (react-dom.development.js:292)
at beginWork$1 (react-dom.development.js:23203)
at performUnitOfWork (react-dom.development.js:22154)
at workLoopSync (react-dom.development.js:22130)
at …
```
=> fix(Datagrid): Let it work even when `selectedIds` is undefined

docs/List.md, packages/ra-ui-materialui/src/list/List.tsx
Hi, it's confusing to have two list of props defined in the docs, I think only one List props is sufficient under the l57 `Here are all the props accepted by the `<List>` component`.
Moreover in the second list it was missing `syncWithLocation` and `component` (that was missing in the two lists)
=> docs (List): clarifies accepted List props

packages/ra-core/src/controller/useListController.spec.tsx, packages/ra-core/src/controller/useListController.ts, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useGetMainList.tsx, packages/ra-core/src/reducer/admin/resource/list/cachedRequests.ts, packages/ra-core/src/reducer/admin/resource/list/ids.ts
This fixes a nasty bug that occurs when:
- A list contains a Field that doesn't check if the record is defined before rendering it (e.g. `FooField = ({ record }) => <>{record.foo}</>` instead of `FooField = ({ record }) => <>{record ? record.foo : null}</>`
- The user deletes a record from the list using bulk actions
In addition, this bug caused an additional List rerender, so this should also speed up lists a bit.
Note to self: never use both a dataProvider hook and a useSelector in the same function. Because dataProvider hooks rely on useEffect, they will return one tick later than useSelector, resulting in data inconsistencies (in this case: a list of `ids` containing the id of a record already removed from the `data` key).
=> Fix List view error after delete when using a field with no record test

packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/form/Toolbar.tsx
=> Fix DeleteWithConfirmButton Does Not Allow to Override resource

examples/simple/src/customRouteLayout.js, packages/ra-core/src/controller/details/useCreateContext.tsx, packages/ra-core/src/controller/details/useEditContext.tsx, packages/ra-core/src/controller/details/useShowContext.tsx, packages/ra-core/src/controller/useListContext.ts, packages/ra-ui-materialui/src/list/ListView.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
React-admin wraps lists, create, edit and show views inside contexts. The main goal is to avoid passing props from the top component to every child one by one.
For example an Edit View is composed of multiple layout elements:
- A form
- An action toolbar
- A title
...
And these layout elements are composed of atomic elements (and some of them are iterator displaying smaller elements):
- Datagrid (iterator)
- ArrayField (iterator)
- TextInput
- Select
Thanks to the modularity of react-admin, you can write your own atomic elements.
Nevertheless, from a developer perspective, it's difficult to know which props are implicitly injected from the top because there are too many levels of components. And the reason why we added the contexts.
For example, imagine you want to create a custom …
=> Fix warning when passing partial props to useListContext and other view context hooks

packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
The propTypes for `resource` was marked as required while the TS definition was marked as optional.
I'm getting a warning in my application when using `ReferenceArrayInput` without a `resource` because of this.
=> Fix ReferenceArrayInputView propTypes

docs/Authentication.md
Just fixed a typo in the Authentication doc
=> Typo fixed

packages/ra-core/src/types.ts
Only 3 param types required this
`UpdateParams`
`UpdateManyParams`
`CreateParams`
This small change allows us to pass through our data's types if we know what they'll be at this point, and defaulting to `any` if no type is passed through. The current types treat the `data` object as `any`.
As for naming, I'm not too keen on giving single letter names to the generic's arguments. I'll be happy to change `T` to `Data` or whatever you feel is most appropriate
=> Improve data provider types

cypress/integration/list.js, packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
Related to #5910.
I'm using the last selected item to detect if a single item or multiple items should be toggled. This is similar to Gmail's UX.
=> [RFR] Add support to select records with Shift + click

docs/Actions.md, packages/ra-core/src/dataProvider/getDataProviderCallArguments.ts, packages/ra-core/src/dataProvider/useDataProvider.spec.js, packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyReference.ts, packages/ra-core/src/dataProvider/useGetMatching.ts, packages/ra-core/src/dataProvider/useGetOne.ts, packages/ra-core/src/dataProvider/useQuery.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts, packages/ra-core/src/types.ts
Closes #5827
This PR introduces the `enabled` option to the `useQuery()`, `useQueryWithStore()` and all the corresponding specialised hooks. The goal is to be able to conditionally make a query. It can be useful for example for a query depending on another one
```ts
// fetch posts
const { ids, data: posts, loading: isLoading } = useGetList<Post>(
'posts',
{ page: 1, perPage: 20 },
{ field: 'name', order: 'ASC' },
{}
);
// then fetch categories for these posts
const { data: categories, loading: isLoading } = useGetMany<Category>(
'categories',
ids.map(id=> posts[id].category_id),
// run only if the first query returns non-empty result
{ enabled: ids.length > 0 }
);
```
- what should the return value contain when `enabled: false`? For now, it will contain the last value before `enabled: …
=> [RFR] Add enabled options to query hooks

packages/ra-ui-materialui/src/field/ReferenceField.tsx
Passing a React element is totally fine and is already allowed by the TS types.
=> ReferenceField: fix label proptype

packages/ra-ui-materialui/src/form/FormInput.tsx, packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
This can be useful when you want to display a component using a different resource in the form.
=> Ensure form children can override props

packages/ra-core/src/controller/field/ReferenceArrayFieldController.spec.tsx, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
=> Handle arrays in ReferenceArrayField filter

docs/DataProviders.md
I've created some provider plugins, this pull request will add their links:
1. **Loopback4 CRUD**: a provider fully compatible with [Loopback4 CRUD](https://github.com/loopback4/loopback-component-crud) component, supports `nested create`, `nested update`, `authentication`, `authorization`
2. **ProcessMaker3**: a provider for ProcessMaker3 BPMS
3. **Mixer**: a plugin for combining and merging other providers
=> docs: add lb4, processmaker3, mixer provider links

docs/List.md
Using `GET_LIST` as `type` for `useQuery` does not work. It needs `getList`
=> useQuery does not work with GET_LIST

docs/Inputs.md, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/controller/input/ReferenceArrayInputContext.ts, packages/ra-core/src/controller/input/ReferenceArrayInputContextProvider.tsx, packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx, packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx, packages/ra-core/src/controller/input/index.ts, packages/ra-core/src/controller/input/useReferenceArrayInputContext.ts, packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-core/src/util/index.ts, packages/ra-core/src/util/indexById.ts, packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
=> Add ListContext to ReferenceArrayInput

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
=> Fix ReferenceArrayInput Passing Wrong Props to Children

packages/ra-data-localstorage/README.md
As stated on the [npm package page](https://www.npmjs.com/package/ra-data-local-storage) the correct name of the package is ra-data-local-storage not ra-data-localstorage as stated in Installation. Current command makes the installation fail.
=> Fix npm package name in installation

docs/Tutorial.md
Remove unnecessary body from request. It even raises a TS error: `Property 'data' does not exist on type 'DeleteManyParams'.ts(2339)`
=> Fix dataProvider: rm HTTP req body from deleteMany

docs/Fields.md
The description of the `sortBy` property of the ReferenceField documentation was mixed up with the `link` property.
=> [Doc] Fix wrong `sortBy` prop prescription in ReferenceField documentation

packages/ra-ui-materialui/src/form/FormTabHeader.tsx, packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
=> Fix FormTabHeader Error State Display

docs/_layouts/default.html, docs/css/docsearch.css, docs/css/style-v9.css
With the last version of Algolia ([docsearch package](https://github.com/algolia/DocSearch/tree/next)), we can easily improve the search experience.
We can use the modal component that allows us to bookmark a search and see the history of your searches. The modal can be open with shortcut (`ctrl+l` or `/`), no need to go back to the top of the page to do a search.
Empty search: ![image](https://user-images.githubusercontent.com/2212144/109831807-1232c380-7c40-11eb-945f-0aad19f5a007.png)
"react context" search:
The text color is white now, the contrast note is higher. Empty search:
When I click on search button, the algolia modal appears:
When I search "react context":
=> [DOC] Improve design on search modal 

packages/ra-ui-materialui/src/button/DeleteButton.tsx
`<DeleteButton>`, when passed `undoable={false}`, calls its child `<DeleteWithConfirmButton>` and passes it the props.
Problem: `<DeleteButton>` `Props` inferface is missing (at least) 2 props that `<DeleteWithConfirmButton>` accepts, namely `confirmTitle` and `confirmContent`. This prevents code from typechecking.
Please find an quick fix in this PR.
=> Add missing field in interface of <DeleteButton> props

packages/ra-data-graphql-simple/src/buildVariables.js
Right now, if the naming of your filter parameter doesn't match the expected naming (`resourceFilter`) the data provider errors out because `type` is `undefined`. In our case, our filters are named `resourceFilterInput` which seems like a fairly common pattern see [kotlin docs](https://expediagroup.github.io/graphql-kotlin/docs/3.x.x/schema-generator/writing-schemas/arguments/#input-types) and [graphql docs](https://graphql.org/graphql-js/mutations-and-input-types/). I think ideally, it would take in a parameter to adjust the naming convention the same way it does for query naming but this seems like a good temporary solution to at least make the filters usable for "nonstandard" naming practices.
=> Graphql data simple data provider: handle if type can't be found

packages/ra-ui-materialui/src/form/SimpleForm.tsx, packages/ra-ui-materialui/src/form/SimpleFormView.tsx, packages/ra-ui-materialui/src/form/index.tsx
It Is handy to be able to use the `SimpleFormView` when overriding the entire `SimpleForm`
=> Export SimpleFormView Component

packages/ra-core/package.json, packages/ra-core/src/form/FormWithRedirect.spec.tsx, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/form/index.ts, packages/ra-core/src/form/useResetSubmitErrors.ts, packages/react-admin/package.json, yarn.lock
Fixes #5938.
Use https://github.com/ignatevdev/final-form-submit-errors to reset the submission error when the field is changed.
I'm not using the `SubmitErrorsSpy` component but a new hook instead to make it work in the `FormWithRedirect` component.
I've also opened a PR in https://github.com/ignatevdev/final-form-submit-errors to add the hook there: https://github.com/ignatevdev/final-form-submit-errors/pull/6.
=> Reset submission error when the field is changed

packages/ra-core/src/util/getFieldLabelTranslationArgs.ts, packages/ra-ui-materialui/src/button/SortButton.tsx
With no translation messages, `<SortButton>` label and choices look ugly
Use the same fallback to humanized field name as for the datagrid headers
=> Fix SortButton labels must have a valid translation message

packages/react-admin/src/defaultI18nProvider.spec.ts, packages/react-admin/src/defaultI18nProvider.ts
When a developer only needs English, and relies on components that pass their label through the translation layer (e.g. `<FilterListItem>`), they should not see warnings for missing translation labels. 
Disable translation warnings for default i18nProvider
=> Fix <Admin> with no i18nProvider logs warnings for missing translations

packages/ra-ui-materialui/src/detail/Edit.tsx, packages/ra-ui-materialui/src/detail/EditView.tsx, packages/ra-ui-materialui/src/detail/Show.tsx, packages/ra-ui-materialui/src/detail/ShowView.tsx
In an `<Edit>` view, developers can disable the actions toolbar altogether by passing `actions={false}` as prop. However, this logs a runtime proptype warning.
=> Fix actions={false] in a View component throws a runtime warning

packages/ra-ui-materialui/src/list/filter/FilterListItem.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
Text FilterListItems aren't always enough. How does one display the following filter items?
**Note**: it is actually possible to use an Element instead of a string with the current code in JS but TypeScript compilation fails. 
Accept a React element as label, and don't pass through translate in this case
=> Add ability to use an element as label in `<FilterListItem>`

packages/ra-ui-materialui/src/list/SingleFieldList.tsx
`<SingleFieldList>` uses a `<div>` as root component by default. When one wants to inline a singlefieldlist, they have to use custom styles. It's cumbersome.
Allow to override the root component
`<SingleFieldList component="span">`
=> singlefieldlist-component

packages/ra-ui-materialui/src/layout/AppBar.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx
---
appBar prop on `Layout` component did not accept `AppBarProps` interface
Fixes marmelab/react-admin#6019
=> Change Layout interface to use AppBarProps interface

packages/ra-core/tsconfig.json, packages/ra-data-fakerest/tsconfig.json, packages/ra-data-json-server/tsconfig.json, packages/ra-data-localstorage/tsconfig.json, packages/ra-data-simple-rest/tsconfig.json, packages/ra-i18n-polyglot/tsconfig.json, packages/ra-language-english/tsconfig.json, packages/ra-language-french/tsconfig.json, packages/ra-test/tsconfig.json, packages/ra-ui-materialui/tsconfig.json, packages/react-admin/tsconfig.json
Using Ctrl+click (or "Go to definition") in VSCode when hovering on a function name leads to the compiled Types file. It's really slowing us down when developing.
Output declarationMaps
=> Fix Go to definition goes to the compiled code in VSCode

packages/ra-core/src/controller/RecordContext.tsx, packages/ra-core/src/controller/details/CreateContextProvider.tsx, packages/ra-core/src/controller/details/EditContextProvider.tsx, packages/ra-core/src/controller/details/ShowContextProvider.tsx
`useRecordContext` wasn't coherent with all our other hooks. It was an issue with fields which were behaving differently depending on where they were used (Datagrid vs Show view for example).
It now accepts props and return either the record from the props or the one from the context
=> Fix RecordContext and UseRecordContext

examples/simple/src/comments/CommentList.tsx, packages/ra-core/src/controller/field/ReferenceArrayFieldController.spec.tsx, packages/ra-core/src/controller/field/ReferenceArrayFieldController.tsx, packages/ra-core/src/controller/field/getResourceLinkPath.ts, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/controller/field/useReferenceManyFieldController.ts, packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
When using a Field component outside of a Datagrid or a Form, users have to inject props manually. They can understand that they must inject `record` and `resource`, but they often forget to inject `basePath`. It is not a problem, except for Reference fields, where the `basePath` is used to build the links to the related records. Using these Fields without a `basePath` leads to a cryptic error:
> TypeError: Cannot read property 'replace' of undefined
The `basePath` property isn't well documented, and to be honest, it isn't very useful. In the most common case, the `basePath` equals `/${resource}`. 
If the `basePath` isn't set, use the resource name instead. That way, users can omit the `basePath` when using `ReferenceField`, `ReferenceArrayField`, and `ReferenceManyField` manually. …
=> Add ability to omit basePath in Reference fields

README.md, docs/Readme.md, packages/react-admin/README.md
I've just made some fixes, but the three README files are rather different.
I'm confused which data is the most updated or whether the three README files should have the same content
Let me know
=> [Doc] Synchronize Readme files

docs/List.md, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/layout/Confirm.tsx
Makes the `Confirm` component more flexible while retaining existing behaviour, `i.e.` if a string is passed through, the content is translated, otherwise simply render the component.
The video demonstrates this behaviour in action.
https://user-images.githubusercontent.com/17087167/109144902-b1941a00-7759-11eb-82b1-562c3d262904.mov
Note: While I updated the all of the uses of `Content` within the React Admin codebase, please let me know if there's anything else I need to consider.
I'll also be happy adding a cypress test too.
=> Feature: Confirm Dialog's `content` prop can receive `React.ReactNode`

packages/ra-core/src/controller/RecordContext.tsx
TypeScript doesn't compile code where `useRecordContext` is called with no argument.
```js
const record = useRecordContext();
------------------
expected 1 argument but got 0
```
But `useRecordContext` was designed to work even without props!
Make params optional
=> [TypeScript] Fix useRecordContext doesn't work without props

examples/simple/src/comments/CommentList.tsx, packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-core/src/controller/field/getResourceLinkPath.ts, packages/ra-core/src/core/useResourceContext.ts, packages/ra-ui-materialui/src/button/CloneButton.spec.tsx, packages/ra-ui-materialui/src/button/CloneButton.tsx, packages/ra-ui-materialui/src/button/CreateButton.tsx, packages/ra-ui-materialui/src/button/EditButton.tsx, packages/ra-ui-materialui/src/button/ListButton.tsx, packages/ra-ui-materialui/src/button/ShowButton.tsx
In the general case, we can infer the basePath from the resource, which is in the context. 
```diff
<CardActions className={classes.cardActions}>
-                           <EditButton
-                               resource="posts"
-                               basePath={basePath}
-                               record={data[id]}
-                           />
-                           <ShowButton
-                               resource="posts"
-                               basePath={basePath}
-                               record={data[id]}
-                           />
+                           <EditButton record={data[id]} />
+                           <ShowButton record={data[id]} />
</CardActions>
```
=> Add ability to omit basePath in buttons

docs/Translation.md
Hi Creators, Mainteners & Contributors,
I added document translation to rebuild a new Indonesian translation. I rebuilt with a typescript & fixed a missing type for the translated message 'ra.navigation.skip_nav'. I hope to merge & publish them.
Thanks.
=> Add docs translation for new indonesian translation

packages/ra-core/src/dataProvider/useGetList.ts
`useGetList` requires that users pass sort, pagination, and filter params. It's cumbersome.
Use sensible defaults
```diff
-const { ids, data, loaded } = useGetList('posts', { page: 1, perPage: 25 }, { field: 'id', order: 'DESC' }, {});
+const { ids, data, loaded } = useGetList('posts');
```
=> Add ability to call useGetList without pagination, sort, or filter params

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
Fixes #5815
Note: `useDeleteWithUndoController` hook already runs `event.stopPropagation()`
=> Fix stop propagation of click event on DeleteWithConfirmButton component

docs/Inputs.md, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Material-ui's `<Autocomplete>` uses the `theme.zIndex.modal` value by default for the z-index of their suggestion list (see https://github.com/mui-org/material-ui/blob/f23207bf2312eba2686522f904d72aea7d3c0a88/packages/material-ui/src/Autocomplete/Autocomplete.js#L276), so we should do the same.
Refs #2456, #4537, #5181, #5375
=> Fix <AutocompleteInput> and <AutocompletearrayInput> options appear behind dialog

packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.tsx
`<ReferenceArrayField>` relies on `dataProvider.getMany()` to retrieve the references, and to pass it them to its child (e.g. a `<SingleFieldList>`. When `getMany()` returns, for a brief moment, `loaded` is `true` and `data` is empty. If the child of `<SingleFieldList>` doesn't check for the existence of its injected `record` before looking up a field, it fails. 
```jsx
const WeakField = ({ record }: any) => <div>{record.title}</div>; // fails when record is undefined
...
<ReferenceArrayField
record={{ id: 123, barIds: [1, 2] }}
className="myClass"
resource="foos"
reference="bars"
source="barIds"
basePath="/foos"
>
<SingleFieldList linkType={false}>
<WeakField />
</SingleFieldList>
</ReferenceArrayField>
```
The bug comes from a race condition in `useReferenceArrayFieldController`. This …
=> Fix ReferenceArrayField passes empty data to child when loaded

packages/ra-ui-materialui/src/list/SimpleList.tsx, packages/ra-ui-materialui/src/list/SingleFieldList.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
`<SimpleList>` can be used without a `<ListContext>`, by passing the required values as props. But TypeScript complains in that case because the component signature doesn't allow passing these props.
(re-)Add the props in the component signature.
=> [TypeScript] Fix SimpleList and other list components can't be used without context

packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx
I think this is how it should be, otherwise the `fullWidth` prop isn't really being passed through to the underlying Material UI  components. However, we're looking at it to specifically help fix the visual layout on some more advanced show pages where we do something like the following:
```ts
<Show {...props}>
<SimpleShowLayout>
<ArrayField source="transactions" fullWidth label="Transactions">
<Datagrid>
<TextField source="id" label="Transaction ID" />
```
`fullWidth` ensures the container takes up 100%, which the data grid happily uses. Without passing it through, the data grid only takes up about 1/3 of the horizontal screen real estate.
=> Pass `fullWidth` to `Labeled`

packages/ra-ui-materialui/src/button/RefreshIconButton.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx, packages/ra-ui-materialui/src/button/index.ts, packages/ra-ui-materialui/src/form/index.tsx, packages/ra-ui-materialui/src/input/BooleanInput.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, packages/ra-ui-materialui/src/input/ImageInput.tsx, packages/ra-ui-materialui/src/input/InputHelperText.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/ResettableTextField.tsx, packages/ra-ui-materialui/src/input/SearchInput.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/input/index.ts
We have been trying to use some of these types but ended up copying them in our codebase because they were not exported.
This PR solves this problem and will hopefully be useful to some developers.
=> Export TS types

packages/ra-core/src/form/validate.spec.ts, packages/ra-core/src/form/validate.ts
=> Fix performance issue with composeValidators

packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-ui-materialui/src/form/SimpleFormView.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx
=> Fix FormWithRedirect Props

packages/ra-input-rich-text/tsconfig.json
=> [TypeScript] Fix ra-input-rich-text is missing types

packages/ra-core/src/core/useGetResourceLabel.ts, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Inner page components depending on the context render more often than before, and are significantly slower. 
The introduction of `useResourceLabel` in #6016 forced a rerender of each view whenever an action is dispatched. That's because this new hook depends on a bad selector that *creates* a new result each time it is called:
https://github.com/marmelab/react-admin/blob/f8df1eb65556ec99085b6fee70c156546a0b632b/packages/ra-core/src/reducer/admin/resource/index.ts#L77-L78
Therefore, in each of the main page controller (`useListController`, etc.), any change in the Redux store forces a re-run of the controller, which returns a new object, which updates the page context, which forces a rerender of all the components depending on it. 
Do not use `useSelector` with that bad selector. 
13 …
=> Fix performance regression

docs/List.md, examples/simple/src/customRouteLayout.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
=> Fix Datagrid requires too many props when used standalone

packages/ra-ui-materialui/src/layout/Error.tsx
When an error occurs, the "Something went wrong" screen displays too many warnings:
- MUI deprecation warnings about `ExpansionPanel` being renamed to `Accordion` (long before our current `peerDependency` of 4.11.2, see https://github.com/mui-org/material-ui/releases/tag/v4.11.0
- i18N warnings about missing translation for error message.
=> Fix console warnings from Error component

examples/simple/src/index.tsx, packages/ra-core/src/core/CoreAdminRouter.spec.tsx, packages/ra-core/src/core/CoreAdminRouter.tsx, packages/ra-core/src/types.ts
=> Fix customRoutes aren't used when the resources are empty

docs/CreateEdit.md, examples/simple/src/users/UserEdit.tsx, packages/ra-core/package.json, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/form/ValidationError.tsx, packages/ra-core/src/form/submitErrorsMutators.spec.tsx, packages/ra-core/src/form/submitErrorsMutators.ts, packages/react-admin/package.json, yarn.lock
In `react-admin`, errors might be objects with `message` and `args` properties which are used for translation.
The original `final-form-submit-errors` mutator was considering those errors as form nested fields such as `name.message` and `name.args`.
I introduced our own version of this mutator which detects those objects.
=> Fix validation documentation & Submission Errors Cannot Have Translatable Error Objects

packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
Prop hasBulkActions passed to DatagridBody was computed as "array" instead of boolean generating this console error:
`Warning: Failed prop type: Invalid prop hasBulkActions of type array supplied to ForwardRef, expected boolean.`
=> Fix hasBulkActions prop type passed to DatagridRow

examples/simple/src/dataProvider.tsx, packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx, packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
When the dataProvider returns with an auth error (e.g. a 403 response), react-admin triggers a redirection to the login page and a notification message that the auth params are no longer valid.
> Your session has ended, please reconnect
This happens when the API invalidates the user credentials.
Now, if a page needs more than one dataProvider Request, this will cause several logouts (not a problem) and several notifications about auth params (that's a problem).
Check that the user is authenticated before notifying that their auth params are no longer valid
=> Fix useLogoutIfAccessDenied may notify more than once

packages/ra-core/src/sideEffect/useRedirect.spec.tsx, packages/ra-core/src/sideEffect/useRedirect.ts
PR #5905 broke `useRedirect` when using a query string:
```jsx
const redirect = useRedirect();
// ...
redirect('/foo?bar=baz');
```
Because of the following change:
```diff
-           history.push(resolveRedirectTo(redirectTo, basePath, id, data));
+           history.push({
+               pathname: resolveRedirectTo(redirectTo, basePath, id, data),
+               state: { _scrollToTop: true },
+           });
```
Transform the redirection target to a react-router `location` object.
Closes #6141
Supersedes #6009
=> Fix useRedirect does not handle query strings

docs/Ecosystem.md
I open sourced a utility module, [ra-acl](https://github.com/andrico1234/ra-acl), to expand on the work done in ra-auth-acl, by adding a `useAcl` hook, as well as a handful of declarative components to abstract out the permission logic and keep the code clean 
Even though this module was added to GitHub recently, I've been using it internally for a month on a production RA application
=> Docs: Add ref to ra-acl

packages/ra-ui-materialui/src/input/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput.tsx
=> Fix array input validation

docs/Translation.md
New repository for ra-language-swedish with lastest additions + typescript
Couldn't get in contact with a maintainer for the old respository
=> [Doc] Fix outdated link for Swedish translation

docs/List.md, packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Implements @fzaninotto suggestion from [here](https://github.com/marmelab/react-admin/issues/6087)
Adds `empty` component to `Datagrid` so we can display a custom component if there are no records to render.
Example
```tsx
<Datagrid empty={<div>No records to show</div>} hasBulkActions>
<TitleField />
</Datagrid>
```
=> Feature: Add empty Datagrid component

packages/ra-ui-materialui/src/layout/AppBar.tsx
Menu icons in the navbar have been aligned with the closed sidebar icons now, for which I had opened an issue a couple of hours earlier @fzaninotto 
Closes #6159
=> Menu icon aligned with the close sidebar icons

cypress/integration/auth.js, cypress/support/ListPage.js, packages/ra-core/src/auth/Authenticated.spec.tsx, packages/ra-core/src/auth/useAuthenticated.spec.tsx, packages/ra-core/src/auth/useLogin.ts, packages/ra-core/src/auth/useLogout.ts, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
I tested this solution with my existing project and it worked fine with custom login page and external identity provider. I hope this quick fix will be sufficient. 
Fixes #6117
=> [RFR] Fix missing query string after successful login

packages/ra-test/README.md, packages/ra-test/src/TestContext.spec.tsx, packages/ra-test/src/TestContext.tsx, packages/ra-test/src/renderWithRedux.tsx
Added support for customReducers inside TestContext and renderWithRedux mentioned in #4644
=> Add customReducers to TestContext

docs/Actions.md, packages/ra-core/src/dataProvider/useCreate.spec.tsx, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useDelete.spec.tsx, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDeleteMany.spec.tsx, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-core/src/dataProvider/useUpdate.spec.tsx, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx, packages/ra-core/src/dataProvider/useUpdateMany.ts
```jsx
// build-time query
const [update] = useUpdate()
// call-time query
update('likes', record.id, diff, record)
```
Also, made all specialized mutation hooks generic:
```jsx
const [update, { data }] = useUpdate<Product>('products', record.id, diff, record)
\- data is Product
```
Closes #6047 
Refs #6143
=> Add ability to call specialized dataProvider hooks with specialized parameters

docs/UnitTesting.md
This PR fixes a broken link in the testing docs.
=> Docs: Fix broken link in UnitTesting.md

packages/ra-core/src/form/validate.spec.ts, packages/ra-core/src/form/validate.ts
composeValidators was always returning an aysnchronous validator even when all received validator were synchronous.
This change has it stay synchronous when possible.
This should  resolve #6049  when using synchronous validator.
=> refactor composeValidators to stay sync when possible

docs/Theming.md, packages/ra-ui-materialui/src/layout/AppBar.tsx
=> Add container prop to AppBar

packages/ra-ui-materialui/src/defaultTheme.ts
This just fixes TS type definition. The width options are already optional ( https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/Sidebar.tsx ).
=> fix(RaThemeOptions): Make sidebar width options optional

docs/DataProviders.md
I have just open-sourced an OData data provider that we are using for our react-admin implementation. It would be great if you could add it to the documentation.
=> [DOC] Add OData data provider

examples/data-generator/tsconfig.json
Publish `data-generator` typings so that it can be used directly within typescript without having to add own typings.
Worth adding `declarationMap` too?
=> Publish data-generator typings

packages/ra-ui-materialui/src/field/UrlField.tsx
Choosing between 
- displaying a link or a static text, 
- showing the value or the default,
are two distinct orthogonal decisions.
In my base my `value` was `undefined` and I didnt provide an `emptyText`.
Because of that `UrlField` tried to create a `Link` leading to an annoying console warning, because it doesnt like that `children` is undefined.
In the case the value is null, it is better to display an empty static text than an empty link.
=> Fix warning in UrlField when value is nullish and emptyText is empty

packages/ra-core/src/dataProvider/useMutation.ts
When you call `useMutation`, `payload` argument is already optional. However TS type definition forces you to pass `payload: {}` . This commit removes that requirement.
=> [TypeScript] Fix useMutation requires payload argument

packages/ra-ui-materialui/src/field/index.ts
In our admin app, we create a lot of our own custom `*Field` components. When defining them, we need to add typescript definitions for props like `addLabel?: boolean`, which aren't used directly by the field component, but by the components wrapping it (e.g. `Labeled`).
All props like that are currently nicely defined in `react-admin` as `PublicFieldProps` or `InjectedFieldProps`, but unfortunately we can't import them, as they aren't exported by the library.
This PR exports them, so they can be used.
=> Export `PublicFieldProps` and `InjectedFieldProps` types (so devs can use them to define their own field components)

packages/ra-core/src/controller/useListController.spec.tsx, packages/ra-core/src/controller/useListParams.spec.tsx, packages/ra-core/src/controller/useListParams.ts, packages/ra-core/src/reducer/admin/resource/list/queryReducer.spec.ts, packages/ra-core/src/reducer/admin/resource/list/queryReducer.ts
=> Fix hideFilter called repeatedly only registers the last call

packages/ra-core/src/util/getMutationMode.ts, packages/ra-core/src/util/index.ts, packages/ra-ui-materialui/src/button/DeleteButton.tsx
For retrocompatibility undoable=false should be on pessimistic mode, currently it is on undoable mode.
=> restore deprecated undoable prop original behavior

docs/Fields.md, packages/ra-ui-materialui/src/field/BooleanField.spec.tsx, packages/ra-ui-materialui/src/field/BooleanField.tsx
Implements #6022
Follow up of #6023
=> [RFR] Allow BooleanField component to evaluate its value in a non strict way

packages/ra-core/src/dataProvider/useQueryWithStore.spec.tsx, packages/ra-core/src/dataProvider/useQueryWithStore.ts
=> fix: useQueryWithStore Should Reset Loading State With Enabled Option

examples/crm/src/dashboard/DealsPipeline.tsx, examples/crm/src/dashboard/HotContacts.tsx, packages/ra-ui-materialui/src/list/SimpleList.tsx
Many of the `<SimpleList>` props are callback that expect a `Record` argument. But TypeScript complains when accessing fields of these records, and that forces to add `// @ts-ignore` flags.
Make `<SimpleList>` generic to accept a Record type.
=> [TypeScript] Add the ability to type SimpleList callbacks

docs/Theming.md, examples/demo/src/layout/Menu.tsx, examples/demo/src/layout/SubMenu.tsx, packages/ra-ui-materialui/src/layout/DashboardMenuItem.tsx, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/MenuItemLink.tsx, packages/ra-ui-materialui/src/layout/Sidebar.tsx
=> Fix logout button appears in two different menus

examples/no-code/src/main.tsx, packages/ra-no-code/src/Admin.spec.tsx, packages/ra-no-code/src/Admin.tsx, packages/ra-no-code/src/ApplicationContext.tsx, packages/ra-no-code/src/ApplicationsDashboard/ApplicationsDashboard.tsx, packages/ra-no-code/src/ApplicationsDashboard/NewApplicationForm.tsx, packages/ra-no-code/src/ApplicationsDashboard/applicationStorage.ts, packages/ra-no-code/src/ApplicationsDashboard/index.ts, packages/ra-no-code/src/ApplicationsDashboard/types.ts, packages/ra-no-code/src/Root.tsx, packages/ra-no-code/src/index.ts, packages/ra-no-code/src/ui/Appbar.tsx, packages/ra-no-code/src/ui/ExitApplicationMenu.tsx, packages/ra-no-code/src/ui/Layout.tsx, packages/ra-no-code/src/ui/UserMenu.tsx, packages/ra-no-code/src/ui/index.ts
=> ra-no-code - Introduce ApplicationsDashboard

packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/input/DateInput.spec.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx
=> Fix DateInput Initial Formatting Without Making Form Dirty

cypress/support/CreatePage.js, packages/ra-core/src/form/FormWithRedirect.spec.tsx, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/form/getFormInitialValues.ts, packages/ra-core/src/form/useInitializeFormWithRecord.ts, packages/ra-core/src/form/useInput.ts, packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/input/DateInput.spec.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx
Follow #6271 
Fixes #6198
We might have a breaking change as I reintroduced the difference between initialValue and defaultValue so that it behaves the same as FinalForm
=> Fix form default values

packages/ra-core/src/controller/details/useCreateContext.tsx, packages/ra-core/src/controller/details/useEditContext.tsx, packages/ra-core/src/controller/details/useShowContext.tsx, packages/ra-core/src/controller/input/useReferenceArrayInputContext.ts, packages/ra-core/src/controller/useListContext.ts, packages/ra-core/src/controller/useRecordSelection.ts, packages/ra-core/src/core/useResourceDefinition.ts, packages/ra-core/src/dataProvider/useDataProvider.spec.js, packages/ra-core/src/dataProvider/useMutation.ts, packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/useDatagridContext.ts
Our context hooks (e.g. `useListContext`) always return new items, even though nothing has changed. 
The problem is that they use lodash/merge, which is recursive. When merging complex objects, the result is almost always a new object.
~~Use lodash/extend instead~~. 
Use lodash/defaults instead (because extend considers undefined values as an override, see https://stackoverflow.com/a/33247597/1333479)
=> Fix performance regression causing unnecessary redraws

packages/ra-core/src/sideEffect/useRedirect.spec.tsx, packages/ra-core/src/sideEffect/useRedirect.ts
closes https://github.com/marmelab/react-admin/issues/6275
=> Allow useRedirect to set location state

packages/ra-data-simple-rest/README.md
This PR adds a small data example to help to get up and running with `ra-data-simple-rest`
I had trouble figuring out the correct data format, and it looks like [other people have too](https://stackoverflow.com/questions/60622649/ra-data-simple-rest-is-not-working-error-total-is-not-a-number-and-newrecords).
=> [Docs] Add data example for ra-simple-rest

docs/List.md, docs/Reference.md, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx, packages/ra-ui-materialui/src/button/index.ts
=> Added BulkUpdateButton component

packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/form/SimpleFormView.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx, packages/ra-ui-materialui/src/form/Toolbar.tsx
=> Disable <SaveButton/> while Inputs are being validated asynchronously

docs/Fields.md
This PR fixes a link that points to the french version of the MDN.
=> Docs: Fix wrong link in Fields documentation

packages/ra-core/src/reducer/admin/resource/list/queryReducer.spec.ts, packages/ra-core/src/reducer/admin/resource/list/queryReducer.ts
=> Fix filter with default value false is not working

packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
=> Fix Filter calls getList on change even when input is invalid

packages/ra-ui-materialui/src/types.ts
closes: https://github.com/marmelab/react-admin/issues/6350
adds `false` to `title` types for Create, Edit and Show components to match `title` type on List component (was added here: https://github.com/marmelab/react-admin/pull/6119)
=> [TypeScript] Fix type mismatch error on title prop for page components

.gitignore, packages/ra-core/src/auth/usePermissions.ts
there are probably other hooks as well that could use this modification but this is the one that bugs me the most in my project.
I would have made the default value "unknown", to make it more strict, but that would have probably broken a lot of code.
=> add TS generic support for usePermissions hook

packages/ra-test/README.md
Just added a 'should' to the case's explanation for consistency and better reading
=> Add should to ra-test docs test case's explanation

docs/Architecture.md, docs/Readme.md, docs/navigation.html
The react-admin codebase has evolved over the yeras, and sometimes it's hard to understand why a feature was designed that way.
While we try to have explicit Pull Request descriptions, it doesn't give the Big Picture about the code organization
Add a new Architecture section in the documentation.
=> [Doc] Add Architecture decisions

packages/ra-ui-materialui/src/layout/Error.tsx
The links only appear in development, just like the error and trace. Besides, the Error page is still overridable.
=> Add links to the Error page to help resolution

packages/ra-core/src/form/useInput.spec.tsx, packages/ra-core/src/form/useInput.ts
`<NumberInput>` changes its value to its `defaultValue` or `initialValue` when it reaches zero. 
If you try to do this: `<NumberInput source="test" min={-10} max={10} defaultValue={6} />`
It will go back to 6 when it reaches 0, like this
=> Fix useInput incorrectly set default value for numbers

docs/Show.md
=> [Doc] Fix `<Show aside>` prop format is component instead of element

packages/ra-core/src/controller/field/ReferenceArrayFieldController.spec.tsx, packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/controller/index.ts, packages/ra-core/src/controller/useList.spec.tsx, packages/ra-core/src/controller/useList.ts, packages/ra-core/src/util/hooks.ts, packages/ra-ui-materialui/src/list/ListView.tsx
Introduces a new hook that applies list filtering, sorting and pagination on the provided data, either in memory or through the provided function. This can be useful for example when you can't change some API routes which return enough data to make those features necessary but you can't or don't want to implement them in your dataProvider.
=> Introduce useList

packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts, packages/ra-core/src/controller/useList.spec.tsx, packages/ra-core/src/controller/useList.ts
Applied the the following adjustments:
- Remove the ids and data params - they don't make sens in that context
- remove the 'initial' prefix in all arguments. 
- update JSDoc accordingly
This should allow a simpler call, like:
```jsx
const listContext = useList({
data,
ids,
filter: { is_published: truev},
sort: { field: 'title', order: 'ASC' },
page: 1,
perPage: 10,
basePath: '/resource';
resource: 'resource';
});
=> Apply review on useList

docs/Actions.md
This PR fixes some of the examples that contain the wrong ending tag for some buttons. Moreover, this fixes the syntax highlighting of the code examples since the wrong closing tags broke it.
=> Docs: Fix wrong ending tags in Actions documentation

docs/Inputs.md, packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
Hopefully this finally works 😅 
Original PRs: #6292 #6294
=> Add SimpleFormIterator label function

docs/Fields.md, docs/Inputs.md, packages/ra-core/src/util/FieldTitle.spec.tsx, packages/ra-core/src/util/FieldTitle.tsx, packages/ra-input-rich-text/src/index.tsx, packages/ra-ui-materialui/src/input/ArrayInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, packages/ra-ui-materialui/src/input/InputPropTypes.ts, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx, packages/ra-ui-materialui/src/input/TextInput.tsx
Closes #6352
- Fixed label issue for `FieldTitle` component
- Updated prop type for label in all the components where `<FiledTitle />` component is used.
**Before** - `NumberInput` with `label={false}`
=> Add ability to hide input labels with label=false

docs/Actions.md, docs/Reference.md
=> [Doc] Improve the side effect hooks documentation

examples/simple/src/index.tsx, examples/simple/vite.config.js, packages/ra-ui-materialui/src/auth/Login.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/LoadingPage.tsx, packages/ra-ui-materialui/src/layout/createMuiTheme.ts, packages/ra-ui-materialui/src/layout/index.ts
=> Fix "Deprecated findDOMNode" warning in StrictMode

docs/Inputs.md, packages/ra-input-rich-text/README.md
=> [Doc] Add mention of <RichTextInput> display bug and userland fix

packages/ra-core/src/i18n/TranslatableContext.ts, packages/ra-core/src/i18n/useTranslatable.ts, packages/ra-ui-materialui/src/input/TranslatableInputsTabContent.tsx
=> Allow overriding label for input inside TranslatableInputs

examples/simple/src/data.tsx, package.json, packages/ra-core/src/controller/details/SaveContext.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, test-global-setup.js
=> Fix DateTimeInput does not include timezone

packages/ra-ui-materialui/src/list/SimpleList.tsx
By default, SimpleList expect avatar values to be initials. When passing a avatar URL, the avatar shows the end of the URL instead of the image. 
```jsx
const UserList = (props) => (
<SimpleList
primaryText={record => record.name}
secondaryText={record => record.role}
leftAvatar={record => record.avatar}
/>
</List>
);
```
To set an image as avatar in SimpleList, developers must return an `<img>` element. This isn't super intuitive.
```diff
const UserList = (props) => (
<SimpleList
primaryText={record => record.name}
secondaryText={record => record.role}
-           leftAvatar={record => record.avatar}
+           leftAvatar={record => <img alt="" src={record.avatar} />}
/>
</List>
);
```
Note: `user` records look like:
```
[
{
id: 1,
name: 'Logan …
```
=> Add support for image path value in <SimpleList leftAvatar>

docs/Inputs.md
ReactPage is a rich content editor and works nicely with React-admin. It provides a ready-to-use Input component for react-admin. You can further use react-admin's resources in ReactPage's form controls. We added a documentation and demo how this can look like (see commit)
Disclaimer: i am (main) contributor to ReactPage.
=> docs(Input): add link to ReactPage Integration

docs/Inputs.md
[Doc] added @bb-tech/ra-components - JsonInput which allows only valid JSON as input, JsonField to view JSON properly on show card and TrimField to trim the fields while showing in Datagrid in List component.
=> [Doc] added @bb-tech/ra-components

examples/crm/build.js, examples/crm/package.json, examples/demo/build.js, examples/demo/package.json, yarn.lock
Create-React-App uses the TerserPlugin to minimize the production build. One side effect is that it removes the React component names, which makes a poor learning experience in our demos since the React DevTools show all components as "Anonymous":
Override the Webpack TerserPlugin configuration to disable name mangling.
While this change increases the build size a bit (about +35kB), we don't really care as our demos are intended for learning. 
Bonus: I enabled the React Profiler in production mode, too.
These changes have already been pushed to the demos:
- e-commerce: https://marmelab.com/react-admin-demo/#/
- CRM: https://marmelab.com/react-admin-crm/#/
=> [Demo] Improve learning experience by keeping component names in React DevTools

examples/simple/src/comments/CommentEdit.tsx, packages/ra-core/src/util/index.ts, packages/ra-core/src/util/mergeRefs.ts, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Allows to provide an inputRef on AutocompleteInput & AutocompleteArrayInput

packages/ra-ui-materialui/src/input/TranslatableInputs.tsx, packages/ra-ui-materialui/src/input/TranslatableInputsTab.tsx, packages/ra-ui-materialui/src/input/TranslatableInputsTabContent.tsx, packages/ra-ui-materialui/src/input/TranslatableInputsTabs.tsx
The translatable input tabs take too much space for low information
Reduce the margins
=> Reduce TranslatableInputs margin

packages/ra-core/src/controller/useListParams.ts
=> Fix filter set via URL isn't persistent if set on the list page

docs/Fields.md
=> [Doc] Fix Syntax Error in linkToRecord code snippet

docs/List.md, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx, packages/ra-ui-materialui/src/list/datagrid/index.ts
To override the datagrid headers (e.g. to have a header span over 2 columns), one has to copy the entire Datagrid code. 
By default, `<Datagrid>` renders its header using `<DatagridHeader>`, an internal react-admin component. You can pass a custom component as the `header` prop to override that default. This can be useful e.g. to add a second header row, or to create headers spanning multiple columns.
For instance, here is a simple datagrid header that displays column names with no sort and no "select all" button:
```jsx
import { TableHead, TableRow, TableCell } from '@material-ui/core';
const DatagridHeader = ({ children }) => (
<TableHead>
<TableRow>
<TableCell></TableCell> {/* empty cell to account for the select row checkbox in the body */}
{Children.map(children, child => ( …
```
=> Add ability to override the Datagrid header row

packages/ra-core/src/controller/useList.spec.tsx, packages/ra-core/src/controller/useList.ts
The current implementation to calculate the total in useList is broken. `finalItems.ids.length` changes once pagination is rendered ([useList.ts#L192](https://github.com/marmelab/react-admin/blob/74606bf8d5c1c72ac3c54ba22be8c1fa7b592fd2/packages/ra-core/src/controller/useList.ts#L192)) . So the value of total equals perPage.
I think using the `ids.length` instead would be appropriate to fix this.
=> Fix useList pagination total

examples/demo/src/layout/Layout.tsx, examples/demo/src/layout/Menu.tsx, examples/demo/src/layout/SubMenu.tsx, examples/demo/src/layout/themes.ts, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/Sidebar.tsx
https://user-images.githubusercontent.com/99944/131044137-54867774-434d-4d34-b57c-05afdef3c499.mp4
I've decided not to shift the menu up when the appbar disappears, because in my tests this caused real UX problems (e.g. the menu just clicked moved down because the appbar reappeared and pushed the menu down). I'm not a big fan of the empty space on top of the menu, but we can live with it. 
The behavior is weird on Safari (a scroll on the menu scrolls the entire page, but a scroll on the content doesn't scroll the menu) but acceptable.
Closes #4684
Supersedes #4753
=> Update Sidebar to remain fixed 

docs/List.md, packages/ra-ui-materialui/src/list/SimpleList.spec.tsx, packages/ra-ui-materialui/src/list/SimpleList.tsx
SimpleList now wrap each item inside a record context and support React elements directly for the `primaryText`, `secondaryText` and `tertiaryText` props.
This allows to use any of the react-admin fields and make it way easier to display referenced records data:
```jsx
// in src/posts.js
import * as React from "react";
import { List, SimpleList } from 'react-admin';
const postRowStyle = (record, index) => ({
backgroundColor: record.nb_views >= 500 ? '#efe' : 'white',
});
export const PostList = (props) => (
<SimpleList
primaryText={<TextField source="title" />}
secondaryText={record => `${record.views} views`}
tertiaryText={
<ReferenceField reference="categories" source="category_id">
</ReferenceField>
}
linkType={record => record.canEdit ? …
```
=> Add record context in SimpleList

packages/ra-ui-materialui/src/field/ArrayField.tsx, packages/ra-ui-materialui/src/field/ChipField.tsx, packages/ra-ui-materialui/src/field/DateField.tsx, packages/ra-ui-materialui/src/field/EmailField.tsx, packages/ra-ui-materialui/src/field/NumberField.tsx, packages/ra-ui-materialui/src/field/RichTextField.tsx, packages/ra-ui-materialui/src/field/SelectField.tsx, packages/ra-ui-materialui/src/field/TextField.tsx, packages/ra-ui-materialui/src/field/UrlField.tsx
=> Fix `Field` components definitions

packages/ra-ui-materialui/src/field/BooleanField.tsx
Fixes #6549
If this is ok, I can do the same for the other fields
=> Fix BooleanField doesn't show label when used in a Show view

packages/ra-ui-materialui/src/field/EmailField.tsx
=> Fix EmailField font size differs from other fields

packages/ra-core/src/util/resolveRedirectTo.ts
As I was going through the redirect flow got wondering at one point why should we construct the same type of path at two places and as linkToRecord is already used and coupled - why not utilize to the fullest?
=> Fix resolveRedirectTo linkToRecord utilization

packages/ra-test/README.md
You helped me in https://github.com/marmelab/react-admin/issues/6597, so I figured I could make the docs better for future me and everyone.
I haven't tested the code to see if it works. Also, a few notes:
- contrarily to some test I've seen in the react-admin code base, I didn't need the `await act(async () => await new Promise(r => setTimeout(r)));` dance. It seems that simply `await`ing was enough to follow properly the event loop.
- I've simplified the `jest.fn().resolve` since the examples weren't using the mocked function for some assertions
- I've replace `queryBy` with `findBy` which is the asynchronous equivalent. In my own code, it's required or the rendered content is the inital one before the dataProvider was called.
Feel free to adjust the code before merging, there's no …
=> Fix examples of ra-test with fake dataProviders

docs/CreateEdit.md, docs/Show.md
`variant=scrollable` and `scrollButtons` must be passed
=> [Doc] Fix scrollable `TabbedForm` usage description

examples/demo/package.json, examples/demo/src/dataProvider/graphql.ts, packages/ra-data-graphql-simple/package.json, packages/ra-data-graphql-simple/src/buildQuery.test.js, packages/ra-data-graphql/package.json, packages/ra-data-graphql/src/buildApolloClient.js, packages/ra-data-graphql/src/introspection.js, yarn.lock
=> Upgrade graphql packages dependencies

packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/dataProvider/useQueryWithStore.ts, packages/ra-core/src/types.ts
=> Support custom DataProvider type with useDataProvider

packages/ra-data-graphql-simple/README.md
This PR updates the example in the README of the `ra-data-graphql-simple` data provider to use React function components as discussed in https://github.com/marmelab/react-admin/issues/6386.
There are no code changes at all, so no disruptive/breaking behavior is expected.
=> [RFR] Updated README of ra-data-graphql-simple.

packages/ra-ui-materialui/src/list/SimpleList.spec.tsx, packages/ra-ui-materialui/src/list/SimpleList.tsx
=> SimpleList: Add support for custom url

packages/ra-core/src/dataProvider/useDataProvider.ts, packages/ra-core/src/types.ts
We'll have to revisit some low levels hooks as well, such as the useQuery and useMutation hooks.
=> Improve useDataProvider types

packages/ra-core/src/i18n/TranslationMessages.ts
https://github.com/marmelab/react-admin/commit/fd895a840aa681efe7e49251573e3762a6523b9b#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
=> [TypeScript] Add missing types for TranslationMessages

packages/ra-core/src/i18n/TranslationMessages.ts
Because of the missing `StringMap` type you get a type error trying to use `TranslationMessages`.
You can see this in the `simple` project
=> Fix export TranslationMessages `StringMap` type

docs/_layouts/default.html, docs/navigation.html
We can't use multi-level menus on the doc navigation, because the doc uses static pages (jekyll), so every click on a menu link reloads the entire page and resets the menu state. If the menu sidebar was scrolled, or submenus open, they will reset to default state as soon as the user changes page. 
We need multi-level menus to split the documentation into more pages, and add more chapters.
https://user-images.githubusercontent.com/99944/139468190-4069ce59-54f6-48a8-900d-42ed42f19911.mp4
=> Keep sidebar state persistent during navigation 

docs/Architecture.md
Updated a spelling mistake, unless its an intended one to show how people don't actually read it!
=> Update spelling mistake

packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx, packages/ra-ui-materialui/src/detail/Tab.tsx, packages/ra-ui-materialui/src/input/Labeled.stories.tsx, packages/ra-ui-materialui/src/input/Labeled.tsx
Following the MUI migration, labels aren't properly positioned in show views, are truncated.
=> Fix Labeled puts label in wrong position

packages/ra-core/src/core/CoreAdminContext.tsx, packages/ra-core/src/core/createAdminStore.ts, packages/ra-core/src/reducer/index.ts, packages/ra-test/README.md, packages/ra-test/src/TestContext.spec.tsx, packages/ra-test/src/TestContext.stories.tsx, packages/ra-test/src/TestContext.tsx
It's very hard to test a component that uses the dataProvider hooks with TestContext, because of a Gotcha about Resource registration that no one knows about.
The first step is to document it. The second step is to move away from Redux for the dataProvider optimistic strategy (to be done in the future).
=> [Doc] Explain how to use dataProvider hooks in TestContext

packages/ra-ui-materialui/src/auth/Login.tsx
You can't use MUI styles hooks in the same component that sets up the ThemeProvider.
Fixes #6654
=> Ensure Login page is customizable through MUI theme

cypress/support/ShowPage.js, docs/FieldWithLabel.md, docs/ShowGuesser.md, docs/ShowTutorial.md, docs/SimpleShowLayout.md, docs/TabbedShowLayout.md, docs/WithRecord.md, docs/navigation.html, packages/ra-core/src/util/FieldTitle.tsx, packages/ra-ui-materialui/src/detail/FieldWithLabel.spec.tsx, packages/ra-ui-materialui/src/detail/FieldWithLabel.stories.tsx, packages/ra-ui-materialui/src/detail/FieldWithLabel.tsx, packages/ra-ui-materialui/src/detail/SimpleShowLayout.stories.tsx, packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx, packages/ra-ui-materialui/src/detail/Tab.tsx, packages/ra-ui-materialui/src/detail/index.ts
`<FieldWithLabel>` adds a label on top of its child if the child exposes a `label` prop, or if it's a field with a `source` prop. It's used in Show layouts, to display both a field and its label. 
`<FieldWithLabel>` is mostly an internal component - you don't need it if you're using `<SimpleShowLayout>` or `<TabbedshowLayout>`. But, in a custom layout, if you want to display a label on top of a field value, just wrap the Field component with `<FieldWithLabel>`. 
```jsx
import { Show, FieldWithLabel, TextField } from 'react-admin';
import { Card, Stack } from '@mui/material';
const BookShow = () => (
<Show>
<Card>
<Stack>
<FieldWithLabel>
<TextField source="title" />
</FieldWithLabel>
</Stack>
</Car>
</Show>
);
```
=> Replace Labeled with FieldWithLabel in show views

packages/ra-ui-materialui/src/input/DateInput.tsx
Fixes #6584, #6459, #6573
We introduced the `formatOnBlur` on `DateInput` to fix issues with Safari but this was the cause of the SimpleFormIterator issue. I checked with BrowserStack that the DateInput was still working on the latest safari.
=> Fix dateinput break simpleformiterator

packages/ra-core/src/sideEffect/useNotify.ts
This PR avoids throwing a warning if only a message is used in `useNotify` callback call, since everything else is optional.
```js
const  notify = useNotify();
// Warning: This way of calling useNotify callback is deprecated. Please use the new syntax passing notify("[Your message]", { ...restOfArguments })
notify('Showing a simple message');
=> Fix Don't show a warning if only one argument is passed to `useNotify`

packages/ra-core/src/form/FormWithRedirect.spec.tsx, packages/ra-core/src/form/FormWithRedirect.tsx, packages/ra-core/src/form/useInput.ts, packages/ra-core/src/form/useWarnWhenUnsavedChanges.spec.tsx, packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx, packages/ra-ui-materialui/src/form/TabbedForm.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx
Closes #6678.
The linked issue above was introduced by #6272 that fixed the issue ##6198 introduced by #6005.
However, all those workarounds were in fact necessary because of our implementation for warning users about potential data loss  if they tried to leave a page with a form with modified fields. Indeed, the `useWarnWhenUnsavedChanges` was saving the form changes when the form was unmounted because a location change happened. If users cancelled the navigation, then the hook would renavigate to the previous location and reapplied the saved changes.
However, re-navigating to the previous location means we refetched the data, reapplied initial values for the loaded record (in case of edit) then reapplied the saved changes. All this lead to several workarounds to manage dirty states that …
=> Fix warn when unsaved changes

packages/ra-core/src/dataProvider/useCreate.spec.tsx, packages/ra-core/src/dataProvider/useMutation.spec.tsx, packages/ra-core/src/dataProvider/useMutation.ts
=> Ensure calltime parameters all take priority in useMutation

examples/simple/package.json
=> Fix simple codesandbox

packages/ra-core/src/sideEffect/useNotify.spec.tsx, packages/ra-core/src/sideEffect/useNotify.ts
#6713 was fixing this problem but #6760 makes it happen again
Close #6767
=> Fix notify function when no type is passed

docs/DataProviders.md
I would like to share with the react-admin community a data provider for [GeoServer](http://geoserver.org/). This allows you to manage spatial data (geometry features) through the standard WFS API offered by GeoServer. I think it can be useful in managing entities with location data (points, lines, polygons...).
=> [DOC] Add GeoServer data provider

UPGRADE.md, docs/Admin.md, docs/Theming.md, examples/crm/src/Layout.tsx, packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/layout/Error.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx, yarn.lock
There's a downside. We used to display the error **inside** our layout. It's now **outside** it. I may revisit this later to make the integration nicer but this is on the critical path for react-router-v6 as there's no `withRouter` HOC anymore
=> Refactor error boundaries

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx
Fixes #6764
When `react-transition-group` change `findDOMNode` over `nodeRef`, now `nodeRef` should point to the transitioning child
Reference: [4.4.0](https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0)
=> Fix SimpleFormIterator transition animations on add and remove items

UPGRADE.md, packages/ra-ui-materialui/src/layout/Error.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/index.ts, packages/ra-ui-materialui/src/layout/useResetErrorBoundaryOnLocationChange.ts
=> Move ErrorBoundary Inside Layout

packages/ra-core/src/dataProvider/useMutation.spec.tsx, packages/ra-core/src/dataProvider/useMutation.ts
=> Fix useMutation not considering returnPromise option

docs/List.md
There were examples with `cloneElement()` function that had been used for creation of "Add Filters" button. While this might be ok for other cases these examples haven't work locally.
This PR simplifies examples by adding pure `FilterButton` component.
=> Fix List actions examples

jest.config.js, package.json, packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
Until now, when working for example on both `ra-core` and `ra-ui-materialui`, we had to stop the tests and rebuild `ra-core` for any changes to impact the `ra-ui-materialui` tests.
This is the jest equivalent of webpack aliases.
I configured it so that `ra-core` `ra-ui-materialui` and `ra-test` are aliased to their sources.
=> Configure jest to avoid rebuilding packages dependencies

packages/ra-core/src/controller/edit/useEditController.spec.tsx, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/controller/show/useShowController.spec.tsx, packages/ra-core/src/controller/show/useShowController.ts
=> Fix Throw an error if the `id` of a request doesn't match the response

packages/ra-ui-materialui/src/detail/Tab.tsx
=> Fix Tab component children missing fullWidth prop when addLabel was set

docs/Admin.md, docs/Authentication.md, docs/CustomApp.md, docs/Theming.md, examples/crm/src/App.tsx, examples/crm/src/Layout.tsx, examples/demo/src/layout/Login.tsx, examples/no-code/src/main.tsx
https://v4.mui.com/customization/theming/
https://github.com/mui-org/material-ui/pull/25992
When using the code in DOCS a warning appears, `CreateTheme` should be the function used instead.
=> update docs & example : createMuiTheme is out of date

lerna.json
On a clean install and build of the project, you don't get the `examples/simple/dist` folder needed by cypress to run the tests
=> Fix lerna config to build simple project

examples/no-code/vite.config.ts
Closes #6432 
Here is an example codesandbox project with the changed config file that is working:
https://codesandbox.io/s/affectionate-allen-0xqij?file=/vite.config.ts:0-187
=> Fix no-code-demo with correct config

packages/ra-ui-materialui/src/input/FileInput.tsx
DropzoneOptions props's accept can receive string[] type but, FileInputProps is can't because the redefined type is wrong.
I replace that as it uses inherited DropzoneOptions' props types if these are redefined of them.
=> 【Bugfix】accept prop of FileInput and ImageInput can't receive string array type 

packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx
=> Fix select all over multiple pages

packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
=> Fix Warn about unsaved changes when modifying CheckGroupInput and ArrayInput

UPGRADE.md, docs/Actions.md, docs/Authentication.md, docs/DataProviders.md, docs/Fields.md, docs/ShowTutorial.md, docs/useRecordContext.md, packages/ra-core/src/auth/useGetIdentity.ts, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/controller/record/RecordContext.tsx, packages/ra-core/src/controller/show/useShowController.ts, packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useGetOne.ts, packages/ra-core/src/dataProvider/useUpdate.optimistic.stories.tsx, packages/ra-core/src/dataProvider/useUpdate.pessimistic.stories.tsx, packages/ra-core/src/dataProvider/useUpdate.undoable.stories.tsx, packages/ra-test/README.md, packages/ra-test/src/TestContext.stories.tsx
To make it consistent with `useGetList`, `useUpdate`, and other dataProvider hooks to come. 
```diff
-const { data, isLoading } = useGetOne('posts', 123);
+const { data, isLoading } = useGetOne('posts', { id: 123 });
```
=> [BC Break] Update useGetOne signature to reflect the getOne signature

packages/ra-ui-materialui/src/form/SimpleForm.tsx, packages/ra-ui-materialui/src/form/SimpleFormView.tsx
Because the toolbar in the SimpleFormView renders based on a logical AND operator, it is possible to remove that element by passing "false" to the toolbar prop on a SimpleForm component, for the purpose of using RA Input components wrapped in a custom form that doesn't require the traditional toolbar.
However, passing false will throw a type error:
Type 'false' is not assignable to type 'ReactElement<any, string | JSXElementConstructor> | undefined'.ts(2322)
SimpleForm.d.ts(68, 5): The expected type comes from property 'toolbar' which is declared here on type 'IntrinsicAttributes & SimpleFormProps'
This PR alters the PropTypes and interface defined Types to allow for false as a value for "toolbar."
Thank you!
=> Allow "false" prop for SimpleList toolbar, removing element

packages/ra-core/src/controller/input/useReferenceInputController.ts
`input.value` should be compared with `record.id` instead of `record`.
Bug introduced in #6918.
=> Fix ReferenceInput: use id to add current value to possible sources

packages/ra-core/src/controller/field/ReferenceFieldController.tsx
It is necessary to have the label parameter to not throw an error on typescript as it is necessary in cases like this:
```
<ReferenceFieldController
basePath="/"
reference="friends"
resource="/"
source="friendsId"
link={false}
// @ts-ignore <-- needed as typescript throws an error
label="Family member"
>
{({ referenceRecord, ...props }) => {
return (
<ReferenceField
resource="/"
reference="family"
source="familyId"
record={referenceRecord || undefined}
link={false}
addLabel={false}
>
</ReferenceField>
);
}}
</ReferenceFieldController>
```
=> Add label field controller

docs/Show.md, docs/ShowBase.md, docs/ShowTutorial.md, docs/SimpleShowLayout.md, docs/TabbedShowLayout.md, packages/ra-ui-materialui/src/detail/Show.spec.tsx, packages/ra-ui-materialui/src/detail/Show.stories.tsx, packages/ra-ui-materialui/src/detail/ShowView.tsx, packages/ra-ui-materialui/src/detail/SimpleShowLayout.stories.tsx, packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx, packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx, packages/ra-ui-materialui/src/types.ts
I think we should revert the changes we made to detail views (Edit, Create and Show) in v4 to move the Card decoration to the content element (SimpleForm) instead of the container, and to remove the aside prop.
The reasoning behind the original change was to allow developers to put whatever they want as children of Show or List, letting them have 2-columns layouts without an extra prop. But in practice, it doesn't work, because the result of a view with several children looks bad because the actions (and pagination in the List view) still take the full width. 
partially reverts #6746
=> Revert main views don't render a Card

packages/ra-ui-materialui/src/list/filter/FilterButton.tsx, packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
=> Fix List Filter Menu is not accessible

packages/ra-ui-materialui/src/field/ArrayField.spec.tsx, packages/ra-ui-materialui/src/field/ArrayField.tsx
The `<ArrayField>` builds a list context by passing null as total. The `SimpleList` expects a total > 0 to be rendered. Both are incompatible.
I studied two solutions:
1. Compute the total using ids (chosen)
2. Remove the total > 0 condition
To not introduce breaking changes, and because it's cleaner, I choose the first solution.
Fixing https://github.com/marmelab/react-admin/issues/6974
=> Make possible to use a SimpleList as a child of an ArrayField

packages/ra-ui-materialui/src/input/ReferenceInput.tsx
When using a SelectInput as a child of a ReferenceInput, and using the prop "enableGetChoices" to prevent an initial call for options, a type error will be thrown:
```jsx
Warning: React does not recognize the `enableGetChoices` prop on a DOM element.
```
This PR sanitizes enableGetChoices on ReferenceInput's extant rest props sanitize function.
=> Sanitize enableGetChoices from ReferenceInput child component

examples/demo/src/dataProvider/graphql.ts, examples/demo/src/products/ProductCreate.tsx, examples/demo/src/visitors/VisitorCreate.tsx, packages/ra-data-graphql-simple/src/buildVariables.test.ts, packages/ra-data-graphql-simple/src/buildVariables.ts
=> Fix ra-data-graphql-simple update methods

CHANGELOG.md
Links to fixed issues on Changelog 3.19.4 update contained "githu" rather than "github", this commit fixes those links.
=> Fixed githu -> github in Changelog links

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix run input blur only when value changes

UPGRADE.md, docs/Actions.md, docs/Datagrid.md, examples/demo/src/reviews/BulkAcceptButton.tsx, examples/demo/src/reviews/BulkRejectButton.tsx, examples/simple/src/posts/ResetViewsButton.tsx, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx, packages/ra-core/src/dataProvider/useUpdateMany.ts, packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx, packages/ra-ui-materialui/src/detail/Edit.spec.tsx
```diff
-const [updateMany, { loading }] = useUpdateMany(
-   'posts',
-   [123, 456],
-   { likes: 12 },
-);
-updateMany(resource, id, data, previousData, options);
+const [updateMany, { isLoading }] = useUpdateMany(
+   'posts',
+   {
+       ids: [123, 456],
+       data: { likes: 12 },
+   }
+);
+updateMany(resource, { ids, data }, options);
```
=> [BC Break] Update useUpdateMany to use react-query

examples/crm/package.json, examples/demo/package.json, examples/tutorial/package.json, packages/ra-core/src/dataProvider/useGetList.spec.tsx, packages/ra-core/src/dataProvider/useQueryWithStore.spec.tsx, packages/ra-ui-materialui/src/form/Toolbar.tsx, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/FileInput.spec.tsx, packages/ra-ui-materialui/src/input/ImageInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectInput.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx, yarn.lock
This should slience some of the security warnings we have, that are due to development packages.
This only concerns the Demos.
=> [Demo] Update Create-React-App to V5

UPGRADE.md, docs/Actions.md, docs/CreateEdit.md, examples/crm/src/contacts/TagsListEdit.tsx, examples/crm/src/dataGenerator/types.ts, examples/crm/src/deals/DealCreate.tsx, examples/crm/src/notes/NewNote.tsx, examples/crm/src/types.ts, examples/simple/src/comments/CommentEdit.tsx, examples/simple/src/comments/PostQuickCreate.tsx, examples/simple/src/posts/TagReferenceInput.tsx, packages/ra-core/src/controller/create/CreateBase.spec.tsx, packages/ra-core/src/controller/create/CreateContext.tsx, packages/ra-core/src/controller/create/useCreateController.spec.tsx, packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useCreate.spec.tsx, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/sideEffect/useRedirect.ts, packages/ra-ui-materialui/src/detail/Create.spec.tsx, packages/ra-ui-materialui/src/detail/Create.tsx, packages/ra-ui-materialui/src/detail/CreateView.tsx, packages/ra-ui-materialui/src/types.ts
```diff
// useCreate
-const [create, { loading }] = useCreate(
-   'posts',
-   { title: 'hello, world!' },
-);
-create(resource, data, options);
+const [create, { isLoading }] = useCreate(
+   'posts',
+   { data: { title: 'hello, world!' } }
+);
+create(resource, { data }, options);
```
=> [BC Break] Migrate useCreate to react-query

packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
=> Fix `SelectArrayInput` create optionText

packages/ra-ui-materialui/src/input/SelectInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix `SelectInput` create optionText

UPGRADE.md, cypress/integration/list.js, docs/Actions.md, examples/crm/src/notes/Note.tsx, packages/ra-core/src/actions/listActions.ts, packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-core/src/dataProvider/index.ts, packages/ra-core/src/dataProvider/useDelete.optimistic.stories.tsx, packages/ra-core/src/dataProvider/useDelete.pessimistic.stories.tsx, packages/ra-core/src/dataProvider/useDelete.spec.tsx, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDelete.undoable.stories.tsx, packages/ra-core/src/dataProvider/useDeleteMany.spec.tsx, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useUpdateMany.ts, packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts, packages/ra-core/src/sideEffect/index.ts, packages/ra-core/src/sideEffect/useUnselect.ts, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/DeleteButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.spec.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
```diff
// useDelete
-const [deleteOne, { loading }] = useDelete(
-   'posts',
-   123,
-   { id: 123, title: "hello, world", likes: 122 }
-);
-deleteOne(resource, id, previousData, options);
+const [deleteOne, { isLoading }] = useDelete(
+   'posts',
+   {
+       id: 123,
+       previousData: { id: 123, title: "hello, world", likes: 122 }
+   }
+);
+deleteOne(resource, { id, previousData }, options);
// useDeleteMany
-const [deleteMany, { loading }] = useDeleteMany(
-   'posts',
-   [123, 456],
-);
-deleteMany(resource, ids, options);
+const [deleteMany, { isLoading }] = useDeleteMany(
+   'posts',
+   {
+       ids: [123, 456],
+   }
+);
+deleteMany(resource, { ids }, options);
```
=> [BC Break] Migrate useDelete and useDeleteMany to react query

docs/Actions.md, examples/simple/src/comments/PostPreview.tsx, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyAggregate.ts, packages/ra-core/src/dataProvider/useGetManyReference.ts, packages/ra-core/src/dataProvider/useGetOne.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.ts
The react-query cache key used by `useGetOne` doesn't reflect the signature of the `dataProvider.getOne()` call: it's 
`[’resource, 'getOne', id]`
instead of
`[resource, 'getOne', { id }]`. 
It's the only dataProvider hook that has a different key than the dataProvider query. There is no reason for that, and it's disturbing when manipulating cache entries. We should either document it or fix it. 
Use the same signature as `dataProvider.getOne`
=> Fix useGetOne query cache doesn't reflect the dataProvider call signature

packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx, packages/ra-core/src/auth/useLogoutIfAccessDenied.ts, packages/ra-core/src/dataProvider/performQuery/performOptimisticQuery.ts, packages/ra-core/src/dataProvider/performQuery/performPessimisticQuery.ts, packages/ra-core/src/dataProvider/performQuery/performUndoableQuery.ts
=> Fix loading indicator not updated on permissions error when logoutUser is false

packages/ra-core/src/dataProvider/useGetList.ts, packages/ra-core/src/dataProvider/useGetMany.ts, packages/ra-core/src/dataProvider/useGetManyAggregate.ts, packages/ra-core/src/dataProvider/useGetManyReference.ts
Running `getMany`/`getList` for a resource overwrites existing `getOne` caches for that resource. In a typical scenario `getOne` would be done after `getMany`/`getList` hiding this problem, but here is how I stumbled on it:
- Have a DataProvider where `getList` fetches only some of the fields, while `getOne` fetches all of them
- Have a resource with `Datagrid` whose `expand` is a `Show`.
- Open the `Datagrid`: calls `getList`
- Expand one row: calls `getOne`
- Go to another resource (expand state will be preserved)
- Go back: calls `getList` and `getOne` at the same time
- if `getList` response arrives first all is good
- if `getOne` response arrives first
- `getList` response will overwrite `getOne` "rich" record with a more "poor" version
- expanded `Show` ends up staying with only …
=> Don't optimistically overwrite getOne cache, only insert new entries

packages/ra-ui-materialui/src/auth/Logout.tsx, packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
A strange typing of `MenuItemProps` has been employed to work around mui-org/material-ui#16245
This was causing the following code to fail with a strange type error:
```typescript
createElement(AdminUI, {
layout: Layout,
dashboard: Dashboard,
catchAll: NotFound,
loginPage: Login as LoginComponent,
logout: Logout,
})
```
The issue has been resolved. The hack can be removed. Type error in my code was resolved, by removing it from `Logout`. I also found the same hack in `MenuItemLinkProps` and did the same change there, but haven't tested its effect.
=> Remove no longer necessary HACK around a @mui/material problem

packages/ra-core/src/i18n/TranslationMessages.ts
Fix missing type for TranslationMessages.
(`ra.action.open`)
https://github.com/marmelab/react-admin/commit/f94b669d9db3a0f13cb092666f3b11bd7ca424f5#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
=> Fix missing type for TranslationMessages

UPGRADE.md, docs/FieldsForRelationships.md, docs/navigation.html, examples/crm/src/companies/CompanyAvatar.tsx, examples/crm/src/companies/CompanyCard.tsx, examples/crm/src/companies/CompanyEdit.tsx, examples/crm/src/companies/CompanyShow.tsx, examples/crm/src/companies/LogoField.tsx, examples/crm/src/contacts/ContactAside.tsx, examples/crm/src/contacts/TagsList.tsx, examples/crm/src/contacts/TagsListEdit.tsx, examples/demo/src/visitors/ColoredNumberField.tsx, examples/demo/src/visitors/CustomerLinkField.tsx, examples/demo/src/visitors/FullNameField.tsx, packages/ra-core/src/controller/field/index.ts, packages/ra-core/src/controller/field/useReferenceOneFieldController.spec.tsx, packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.tsx, packages/ra-ui-materialui/src/field/index.ts
I started documenting the react-admin ReferenceXXXfFields, and found ReferenceOne to be a missing spot in our strategy.
=> [BC Break] Add ReferenceOneField

UPGRADE.md, docs/Inputs.md, docs/ListTutorial.md, docs/useList.md, docs/useListContext.md, docs/useListController.md, packages/ra-core/src/actions/listActions.ts, packages/ra-core/src/controller/field/useReferenceManyFieldController.ts, packages/ra-core/src/controller/input/ReferenceArrayInputContext.ts, packages/ra-core/src/controller/input/useReferenceArrayInputContext.ts, packages/ra-core/src/controller/input/useReferenceArrayInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-core/src/controller/input/useReferenceInputController.ts, packages/ra-core/src/controller/list/ListContext.tsx, packages/ra-core/src/controller/list/ListSortContext.tsx, packages/ra-core/src/controller/list/queryReducer.spec.ts, packages/ra-core/src/controller/list/queryReducer.ts, packages/ra-core/src/controller/list/useList.spec.tsx, packages/ra-core/src/controller/list/useList.ts, packages/ra-core/src/controller/list/useListContext.ts, packages/ra-core/src/controller/list/useListController.ts, packages/ra-core/src/controller/list/useListParams.ts, packages/ra-core/src/controller/useSortState.ts, packages/ra-ui-materialui/src/button/SortButton.tsx, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
=> [BC Break] Change setSort signature to make it consistent acrosse components

packages/ra-ui-materialui/src/button/Button.tsx
`hasCreate` property slips into the DOM causing a warning from react:
<details>
<summary>screenshot</summary>
</details>
Add `hasCreate` to `sanitizeButtonRestProps`.
Note: This solves the warning that I am geting, but I haven't looked into what change introduced this problem and whether the `hasCreate` also needs to be sanitized on some other levels.
=> Add hasCreate to list of button props that are injected by Toolbar

packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
Prop types of reference fields specify `label: PropTypes.string`, even though `type PublicFieldProps` says `label?: string | ReactElement | boolean`. A big red error is printed to the console when using an element as label.
Use common `fieldPropTypes.label` definition in each propType definition.
---
I am being a bit sloppy here, as this just fixes the warnings that bug me. But it makes the codebase a bit better and should be easy to merge. A bigger refactoring of propTypes is needed. The same issue is with inputs.
I didn't investigate why `Reference*Field` propTypes don't extend the `fieldPropTypes` like other fields do, probably they have to override something.
=> Fix propTypes.label for reference fields

packages/ra-ui-materialui/src/button/CreateButton.tsx
`_scrollToTop` not happening when clicking the mobile (FAB) version of `CreateButton`.
https://user-images.githubusercontent.com/79251424/149657631-f035901c-4e55-4736-8ce2-9c8f17b36290.mp4
[`Link`](https://reactrouter.com/docs/en/v6/api#link) expects `state` to be passed as a prop, not as a field of `to`. `Button` handles that through [`Button.getLinkParams`](https://github.com/marmelab/react-admin/blob/a57ff9f0374bf1b68920f2518a311c3af75e495a/packages/ra-ui-materialui/src/button/Button.tsx#L206).
Pass `location.state` as `state` and `location.pathname` as `to`.
---
Move the Fab-code into `Button`, handle its props with `getLinkParams`, allow making other buttons `Fab`-able (e.g. sensible for `EditButton` in the `Show` view, `SaveButton` in the `Edit` view, etc)
=> Fix CreateButton Fab _scrollToTop state prop

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
=> Fix `ArrayInput` could make the form dirty on initialization

docs/Inputs.md
ArrayInput / FormIterator has buttons to reorder items but the documentation is lacking details about the customization / disabling of these buttons. In cases where order doesn't matter they only confuse users.
This is a pure documentation update, the functionality was already there.
=> [Doc] customizing and disabling item reordering for ArrayInput

packages/ra-ui-materialui/src/layout/Error.tsx
=> Fix error messages can't be copied

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
=> Fix `SimpleFormIterator` assigns items indexes incorrectly

packages/ra-no-code/src/Admin.spec.tsx, packages/ra-no-code/tsconfig.json
I noticed that on my machine this test always failed with a timeout exception when running `yarn test-unit` in the root project.
It did not fail however when running `yarn test-unit --watch` because then it took just below the default 5000ms timeout setting of jest.
I have increased the timeout for this specific test and applied some best practices for this test.
I've also fixed the incorrect intellisense for the test files by explicitly setting `jest` in the required types in tsconfig.json so it doesn't look at mochas typescript definition files any longer.
=> Fix failing admin test when running all tests together

docs/Inputs.md
=> [Doc] Fix inputs initialValue description

packages/ra-ui-materialui/src/input/index.ts
It seems `BooleanInputProps` export has been forgotten.
=> fix: export BooleanInputProps

docs/CreateEdit.md, packages/ra-core/src/controller/edit/EditBase.spec.tsx, packages/ra-core/src/controller/edit/useEditController.spec.tsx, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/detail/Edit.spec.tsx
Closes #7054 
Add previous data argument transform method. My tests added is redundant because previousData always is passed and  asserted in every tests but, it's noting worth to keep description about expecting behavior, ready for this behavior is modified (however if you don't need it, I'll remove them).
=> Add previous data on transform

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
When using a SelectArrayInput as a child of a ReferenceArrayInput, DOM errors will be thrown for the props "emptyText" and "enableGetChoices". This commit sanitizes those props before they are passed to the FormControl component, which triggers the DOM error.
=> Sanitize emptyText, enableGetChoices @ SAI

packages/ra-data-graphql/src/index.test.ts, packages/ra-data-graphql/src/index.ts
Fixes #6953
I added a test to check for correct error handling when executing a mutation.
=> Add ApolloError in error body when handling errors

examples/simple/src/comments/CommentList.tsx, packages/ra-ui-materialui/src/detail/Edit.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/SearchInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Closes #6700
Setting a default width for selects is necessary in mui 5 as it was in mui 4, see https://github.com/mui-org/material-ui/issues/8778
Before:
After:
=> Fix SelectInput and AutocompleteInput default width

docs/CreateEdit.md, packages/ra-ui-materialui/src/form/Toolbar.tsx
=> Fix alwaysEnableSaveButton can accept false

packages/ra-core/src/form/useChoices.ts, packages/ra-core/src/form/useSuggestions.ts, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Having a `AutocompleteInput` with an `optionText` being set to a field that is not of type `string` throws an internal error
```jsx
<ReferenceInput
label={'Product'}
source={'category_id'}
reference={'products'}
>
{ /* record:
{ 
id: 7, // =>  type is number
name: 'Washed jacket', 
category_id: 5
}
*/ }
<AutocompleteInput optionText="id" /> /* While typeing, the input gets cleared */
</ReferenceInput>
```
This attempts to fix `optionText` of type `string` when the data type is not a `string` but it doesn't when `optionText` is of type `Function`.
May be related to #6214
=> Fix AutocompleteInput erases input while typing

packages/ra-core/src/i18n/TranslationUtils.spec.ts
Noticed a bug at `resolveBrowserLocale` tests during #7170 investigation to implement a new feature (#7193).
**Problem**:
As `navigator.language` is a **read-only property** (see [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) about it), it wasn't being affected by the `window.navigator = {}`. You can see that at `should return default locale if there's no available locale in browser` test, it is an invalid test.
**Solution**:
Implement correctly using `jest.spyOn` function, see this answer: https://stackoverflow.com/a/52870312
Should this fix enter before #7193 @WiXSL ?
=> Fix resolveBrowserLocale tests

package.json, yarn.lock
`cheerio` dependency has been removed from `master` branch, it's not used. In fact, is the only dependency that has been removed there (without counting library swapping like react-final-form => react-hook-form)
=> [4.0.0-alpha.3] Remove outdated dependency

docs/List.md, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
=> Fix `FilterButton` throws error if no filters are present 

packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useUpdate.ts
Related PR: https://github.com/marmelab/react-admin/pull/5778.
To be able to handle correctly submission validation errors, the returned functions from `useCreate` and `useUpdate` need to be able to return a promise.
Only then doing like it is described in the documentation would be possible:
https://github.com/marmelab/react-admin/blob/efc89692fdf839d1267e030595a52a1127b23d71/docs/CreateEdit.md?plain=1#L1524-L1531
=> Fix BC break v4: useCreate and useUpdate can return a promise

docs/Inputs.md
=> [Doc] Fix `DateInput` example of format and parse with Date object as value

UPGRADE.md, docs/Admin.md, docs/Authentication.md, docs/Buttons.md, docs/FAQ.md, docs/Theming.md, examples/crm/src/Header.tsx, examples/demo/src/layout/AppBar.tsx, examples/simple/src/Layout.tsx, packages/ra-core/src/core/CoreAdmin.tsx, packages/ra-core/src/core/CoreAdminRoutes.tsx, packages/ra-core/src/core/CoreAdminUI.tsx, packages/ra-core/src/types.ts, packages/ra-no-code/src/ui/Menu.tsx, packages/ra-ui-materialui/src/auth/Logout.tsx, packages/ra-ui-materialui/src/layout/AppBar.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/MenuItemLink.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx, packages/ra-ui-materialui/src/layout/UserMenuContext.ts, packages/ra-ui-materialui/src/layout/UserMenuContextProvider.tsx, packages/ra-ui-materialui/src/layout/index.ts, packages/ra-ui-materialui/src/layout/useUserMenu.ts, packages/react-admin/src/Admin.tsx
=> Avoid cloning elements in AppBar

packages/ra-ui-materialui/src/field/DateField.spec.tsx, packages/ra-ui-materialui/src/field/DateField.tsx
=> Fix DateField show wrong date on negative time zones

packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
=> Fix prevent `CheckboxGroupInput` from changing selected values type

packages/ra-core/src/core/CustomRoutes.tsx, packages/ra-core/src/core/Resource.tsx, packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
Fixes https://github.com/marmelab/react-admin/issues/7284.
Like [mui does](https://mui.com/guides/composition/#wrapping-components), introduce a `raName` static on some child elements (`CustomRoutes` and `Resource`) in order to filter them in `useConfigureAdminRouterFromChildren`.
It will allow to compose components (for instance API Platform Admin [ResourceGuesser component](https://github.com/api-platform/admin/blob/main/src/ResourceGuesser.tsx)) by setting the same static property.
=> fix: allow composition of child elements by using raName

packages/ra-core/src/form/useChoices.tsx
=> Fix useChoices error if key is not of type string

packages/ra-core/src/form/useChoices.ts, packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput optionText returning an element throws error

UPGRADE.md, docs/List.md, docs/ReferenceArrayInput.md, docs/ReferenceInput.md, packages/ra-core/src/controller/input/useReferenceArrayInputController.spec.tsx, packages/ra-core/src/controller/input/useReferenceArrayInputController.ts, packages/ra-core/src/controller/input/useReferenceInputController.ts, packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.tsx
=> Fix inconsistencies in `ReferenceInput` and `ReferenceArrayInput`

docs/Datagrid.md, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/useDatagridStyles.tsx
The datagrid override seems is forgotten in the first beta version.
This pull request also adds a table wrapper, so we can set a width for table and make a scroll bar appear right below the table.
(Previously in examples, the scrollbar always appears on the bottom of the page, when scrolling horizontally datagrid may cover the menu)
=> Update datagrid style overrides [RFR]

packages/ra-core/src/dataProvider/index.ts
=> fix: expose combineDataProviders to 'react-admin'

packages/ra-core/package.json, packages/ra-core/src/form/ValidationError.spec.tsx, packages/ra-core/src/i18n/TestTranslationProvider.tsx, yarn.lock
Core us used by most, so remove the ra-i18n-polyglot dev dependency.
This causes a dependency cycle while trying to build.
Implement a basic way of doing interpolation so we can test variables get passed correctly.
Closes: #7361
=> fix(core): Dependency loop on ra-i18n-polyglot

docs/Store.md, packages/ra-core/src/store/localStorageStore.ts
Code relyoing on stored values to have a certain shape may fail if used with an old value with a different shape
Add ability to specify a version number for the store, and invalidate the store if the version from the code differs from the version from the store.
=> Add Store invalidation system 

examples/demo/src/fakeServer/index.ts, packages/ra-core/package.json, packages/ra-input-rich-text/package.json, packages/ra-no-code/package.json, packages/ra-ui-materialui/package.json, packages/react-admin/package.json, yarn.lock
=> Allow usage with react 18

packages/ra-core/src/core/Resource.tsx, packages/ra-core/src/core/ResourceDefinitionContext.tsx, packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx, packages/ra-core/src/core/useRegisterResource.ts
Supersedes #7382
Thanks @alanpoulain for reporting this issue and suggesting the solution!
API Platform needs a custom Resource element to configure default views when users don't provide their own. However, because of how react-router v6 works, we have to register the resource definitions outside of the Resource components as they are rendered inside a route matching their name and registering their definition in their render method would only work for the rendered resource. This means we have to inspect the Resource props so views provided by a custom Resource element wouldn't be available at the registration time.
`Resource` elements must now provide a static `registerResource` method which is called with the props provided by the user and must return the `ResourceDefinition`. This …
=> Custom resource element

packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
If you try to render an icon different from the sort icon in a Datagrid's header cell, it will be hidden from view
=> Improve DatagridHeaderCell sort icon manipulation

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Before:
After:
It's probably because the `id` of the fields is changing (`id` is generated from [useFieldArray](https://react-hook-form.com/api/usefieldarray/)), and the `ref` needs to be changed as well (see http://reactcommunity.org/react-transition-group/transition/#Transition-prop-nodeRef).
Using the previous code from master is needed to solve this issue.
I needed to revert https://github.com/marmelab/react-admin/pull/7123 as well, I don't understand how the change in this PR can work.
=> fix: use right index for the transition in SimpleFormIterator

packages/ra-core/src/types.ts
This aim to solve two things:
1. Using object as type is not recommended as we can not access a
property without having Typescript yelling this one can not exist on
object (ts2339)
2. As specified on the documentation, the label options is available and
use by the react-admin ecosystem. It should be explicitly defined.
=> [RFR] fix(types): missing resource options label property

docs/Theming.md
`sidebarIsOpen` in _MenuItemLink_ component and `onMenuClick` in _Menu_ component has been deprecated in https://github.com/marmelab/react-admin/pull/6230 and they're no longer needed to create custom menu components.
Also there were some unused import statements, so I've clean them all.
Note that I've only updated the place where I referred, so there might be more deprecated / unused imports in the another lines of this file.
=> docs: remove deprecated props and unused imports

docs/UnitTesting.md
Add missing import reference to the `<TestContext />` inside a snippet on the Unit Testing page.
=> [Docs] Add missing import

cypress/integration/list.js, packages/ra-core/src/controller/useListParams.ts, packages/ra-core/src/util/hooks.ts
Backport of #7443 to v3
Closes #7368
=> [v3] Fix race condition due to debounced setFilter

packages/ra-core/src/core/index.ts
Some of CRM is able to create resource schema definitions dynamically
We sometimes will need to manually register resource under different components so it would be best to export this hook
=> Export register resource hook

docs/List.md
Following discussion in #7401, this PR adds information about list selection state being stored in a global store.
I added this information under the [`disablesyncwithlocation`](https://marmelab.com/react-admin/doc/4.0/List.html#disablesyncwithlocation) as I think this is where users trying to achieve truly local lists will look.
=> docs: add information about list selection state

packages/ra-core/src/routing/AdminRouter.tsx
Even though you wrapped your API with a Router, react-admin will still instantiate an history if you didn't provide one.
Extract the history instantiation in an internal router component.
I tested this on a local remix project with success
=> Fix SSR Support

docs/Datagrid.md, packages/ra-core/src/controller/list/useExpanded.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridContext.ts, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
This prop forces the `Datagrid` to have one row expanded at a time
=> Add `expandSingle` prop to Datagrid

cypress/integration/list.js, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Fix infinite rendering issues introduced after #7442
Fixes #7452
Remove superfluous dependency on `filters` in effect handling form reset in `FilterForm`
_Note :_ testing was done manually, didn't add a story for this case as declaring the filters inside the List component is not recommended by the docs
=> Fix filter form reset effect deps

docs/Datagrid.md, packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx, packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx, packages/ra-ui-materialui/src/list/datagrid/useDatagridStyles.tsx
We're adding classes to each datagrid row to let developers style them differently whether they're clickable, selectable, expandable, or not. 
Ideally, we should change the cursor by default when a row isn't clickable, selectable, or expandable, but this is for another PR.
Closes #7407
=> [Datagrid] Fix non clickable row can't be styled

docs/Admin.md, docs/Authentication.md, packages/ra-core/src/core/CoreAdmin.tsx, packages/ra-core/src/core/CoreAdminRoutes.spec.tsx, packages/ra-core/src/core/CoreAdminRoutes.tsx, packages/ra-core/src/core/CoreAdminUI.tsx, packages/react-admin/src/Admin.tsx
Auth check is optimistic by default.  In v3, one could turn auth check to pessimistic (i.e. display nothing until `dataProvider.checkAuth()` resolves) by implementing a custom `<Resource>`. But in v4, the authentication isn't in `<Resource>` anymore, but in the page controllers. As a consequence, it is not possible to make auth pessimistic. 
Add an option to `<Admin>` to make the app require authentication. 
This is something we must do before releasing v4, because otherwise it would prevent an entire class of features (and break ra-rbac).
Closes #5229
=> Add <Admin requireAuth> to hide the app until auth is checked

packages/ra-core/src/controller/RecordContext.tsx
[The doc mentions it](https://marmelab.com/react-admin/doc/4.0/useRecordContext.html#optimistic-rendering) but TS doesn't enforce it. I believe it should.
=> `useRecordContext` may return `undefined`

docs/Upgrade.md
Remove `render` prop from the new `Form` component examples in the v4 migration guide.
Fixes #7504
=> Doc fix: remove render prop from new Form component examples

docs/Validation.md
This was misleading:
> To validate values submitted by a form, you can add a validate prop to the form component, to individual inputs, **or even mix both approaches**.
See https://marmelab.com/react-admin/doc/4.0/Validation.html
=> Fix Validation documentation mentions mixing both global and field-level validation

docs/Admin.md, examples/simple/src/index.tsx, packages/ra-core/src/auth/useCheckAuth.spec.tsx, packages/ra-core/src/auth/useCheckAuth.ts, packages/ra-core/src/auth/useLogin.ts, packages/ra-core/src/auth/useLogout.ts, packages/ra-core/src/routing/useCreatePath.ts
Make the following auth hooks use basename in case of redirection:
- useLogin
- useLogout
- useCheckAuth
=> Make auth hooks use basename

docs/AuthRBAC.md
Current link (https://marmelab.com/ra-rbac) leads to a page that doesn't exist.
`GET https://marmelab.com/ra-rbac 404`
**NOT FOUND**
You just hit a route that doesn't exist... the sadness.
=> Fix the link to the ra-rbac module

packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Fixes #7540
The problem is in the `getFilterFormValues` return value, if a field is a Date, and has a `parse` function that returns a date (this is why it happens by default in DateTimeInputs and not in DateInputs), its value gets treated like a regular object, and ends up returning an empty object for that field, instead of the string representation of the date
=> Fix parsed date/date-time filter resets component

packages/react-admin/src/Admin.tsx
The `queryClient` prop is not passed into the application.
Merging this change will propagate the `queryClient`
=> Add queryClient prop to <Admin />

packages/ra-core/src/form/useChoices.tsx
=> Fix #7593, choices should indeed be `any[]`

docs/DataProviderWriting.md, packages/ra-data-graphql/README.md
We'll reintroduce the `ra-data-graphql` and `ra-data-graphql-simple` packages soon. In the meantime, the docs should make it clearer that developers can also implement their own GraphQL data provider by hand. 
Note: the code snippet is tested against a real Hasura instance. Fun fact: GitHub Copilot wrote about 80% of its code.
=> [Doc] Add an example GraphQL data provider

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
`ArrayInput` passes the props it doesn't use to its first underlying component, `FormControl`. This PR ensure the `ArrayInputProps` interface extends the `FormControlProps` interface. This allows to use the `sx` prop without TS complaining for instance
=> Fix ArrayInput Props Type

docs/Routing.md
=> [Doc] Fix instructions for using RA in a sub path

docs/ArrayField.md
Make it consistent with upgrade guide here https://marmelab.com/react-admin/Upgrade.html#arrayfield-does-not-accept-a-fieldkey-prop-anymore
=> [Doc] Remove deprecated fieldKey

packages/ra-core/src/form/index.ts, packages/ra-ui-materialui/src/button/SaveButton.tsx
=> Fix Form validation when SaveButton type is "button"

packages/ra-ui-materialui/src/button/Button.tsx
Per MUI documentation https://mui.com/material-ui/api/button/#props `icon` is no longer a prop
Also we are passing icon as children
=> Fix <Button/> type

packages/ra-data-graphql/src/index.ts
operationNames is set by default https://github.com/marmelab/react-admin/blob/03a0980ad801d753faa92d3a74ed18be43b926ec/packages/ra-data-graphql/src/index.ts#L60
=> Fix IntrospectionOptions exported type

packages/ra-core/src/controller/create/useCreateController.ts
Currently if `redirect` prop of useCreateController is set to false, it is ignored. This is probably not intentional and it makes difficult to disable redirects.
=> Add possibility to disable redirect in useCreateController

packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Resolves: https://github.com/marmelab/react-admin/issues/7629
Adding the following theme to the simple repo:
```js
const theme = merge({}, defaultTheme, {
components: {
RaSimpleFormIterator: {
styleOverrides: {
root: {
border: '1px solid red',
[`& .${SimpleFormIteratorClasses.indexContainer}`]: {
border: '1px solid hotpink',
},
[`& .${SimpleFormIteratorClasses.action}`]: {
border: '1px solid blue',
},
},
},
},
},
});
```
Results in the following (Mondrian-inspired 👩🏼‍🎨🖌🎨) appearance 😅 :
=> Bugifx: Allow style overrides for SimpleFormIterator

packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
=> Simplify useConfigureAdminRouterFromChildren permissions

packages/ra-core/src/util/getFieldLabelTranslationArgs.spec.ts, packages/ra-core/src/util/getFieldLabelTranslationArgs.ts, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorContext.ts, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx
=> Fix SimpleFormIterator Labels

docs/Form.md, docs/SimpleForm.md, docs/TabbedForm.md
Per MDN documentation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form
Buttons placed outside a form should accept `form` as the attribute instead of `formId` to associate with a form
=> [Doc] Update <SaveButton/> prop in <Form/> example

packages/ra-ui-materialui/src/button/Button.tsx
The "component" prop allows passing the tag or component that will be rendered as a button
`ReactNode` refers to a string, number, null, undefined, boolean, React element, fragment, or portal
`ElementType` refers to an HTML tag name, React class or functional component
=> Fix type of Button's "component" prop

docs/RichTextInput.md, docs/Upgrade.md, packages/ra-input-rich-text/README.md, packages/ra-input-rich-text/src/RichTextInput.tsx, packages/ra-input-rich-text/src/RichTextInputToolbar.tsx
`ra-input-rich-text` doesn't export any `RichTextInputLevelSelect`. It should be just `LevelSelect`.
=> Fix documentation for RichTextInputToolbar's LevelSelect

docs/NumberInput.md, packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.stories.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
`<NumberInput>` does not handle zero after comma correctly (cf #7530)
A controlled Number input cannot handle "transitive" values (e.g. "1.0" while typing "1.02") properly.
An uncontrolled input cannot handle reinitialization properly (this leads to problems e.g. when browsing from one record to the other in the same Edition view)
So the solution is to manage the string value locally, and only modify the form value on blur. This is the path taken by [react-aria's `useNumberField`](https://react-spectrum.adobe.com/react-aria/useNumberField.html#controlled), and I believe the only viable solution. 
Closes #7530, #7625
Supersedes #7537
Maybe we should also mention that `<input type="number" />` is problematic, [as pointed by this BBC …
=> Fix `<NumberInput>` edge cases

packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
=> Fix `<Filter>` shows filter button even though there is no filter to add

packages/ra-ui-materialui/src/form/FormTab.tsx, packages/ra-ui-materialui/src/form/FormTabHeader.tsx
Fixes https://github.com/marmelab/react-admin/issues/7678
=> Fix FormTab MUI props pass through

packages/ra-core/src/form/useInput.ts, packages/ra-ui-materialui/src/input/NumberInput.tsx
Hello,
I came across a bizarre issue while implementing the last version of react-admin. Indeed, if the content of a any Input containing text is "on" it will be replaced by "false" (the bug was case sensitive, it can be verified on the [demo login page](https://marmelab.com/react-admin-demo/#/login) for example).
I tried and fixed it in my personal repository, so i'm submitting this pull request to help other encoutering this issue.
=> Fixing textinput changing 'on' into 'false'

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/7685
=> Fix AutocompleteInput undefined choices

docs/Admin.md, docs/DataProviders.md
=> [Doc] Fix missing doc for `<Admin queryClient>` prop

packages/ra-ui-materialui/src/detail/EditGuesser.spec.tsx, packages/ra-ui-materialui/src/detail/EditGuesser.tsx, packages/ra-ui-materialui/src/detail/ShowGuesser.spec.tsx, packages/ra-ui-materialui/src/detail/ShowGuesser.tsx, packages/ra-ui-materialui/src/list/ListGuesser.spec.tsx, packages/ra-ui-materialui/src/list/ListGuesser.tsx
Guesser output can't be copy/pasted directly, as it misses the import part.
Add the imports
```diff
Guessed Show:
+
+import { DateField, ReferenceField, Show, SimpleShowLayout, TextField } from 'react-admin';
export const CommentShow = () => (
<Show>
<SimpleShowLayout>
<TextField source="id" />
<DateField source="author.undefined" />
<ReferenceField source="post_id" reference="posts"><TextField source="id" /></ReferenceField>
<TextField source="body" />
<DateField source="created_at" />
</SimpleShowLayout>
</Show>
);
```
=> Add imports to guesser output

docs/Create.md
=> Doc: fix Save And Add Another example

docs/useCreate.md, docs/useDelete.md, docs/useDeleteMany.md, docs/useUpdate.md, docs/useUpdateMany.md, packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.ts, packages/ra-ui-materialui/src/types.ts
Provides a way to set the expected type of the error instance that will be propagated to the related functions.
closes #7653
=> feat(hooks): mutation error typing

packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-ui-materialui/src/button/DeleteButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx
Missing parts of https://github.com/marmelab/react-admin/pull/7698
=> fix(typescript): missing use mutation error typing definition

docs/Create.md
=> docs(create): missing button type on custom save button

docs/Validation.md
Related to https://github.com/marmelab/react-admin/issues/7697
=> Doc: Fix Async Validation per Input example

docs/useGetOne.md
The previous doc incorrectly mentioned that, to aggregate `useGetOne` calls, one has to use `useGetMany`, while it is in fact `useGetManyAggregate`.
I took the opportunity to develop this doc chapter a little bit.
=> [Doc] Fix useGetOne section about query aggregation

packages/ra-ui-materialui/src/list/SingleFieldList.tsx
=> Fix Support For sx Prop in SingleFieldList

packages/ra-core/src/core/useConfigureAdminRouterFromChildren.spec.tsx, packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx, packages/ra-no-code/src/Admin.spec.tsx
It should not call its child function when permissions have not been retrieved yet
Fixes #7725
=> Fix useConfigureAdminRouterFromChildren 

docs/TabbedForm.md, packages/ra-ui-materialui/src/form/TabbedForm.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx
Fixes https://github.com/marmelab/react-admin/issues/7712
=> Add sx prop to TabbedForm and improve doc

packages/ra-ui-materialui/src/form/SimpleForm.stories.tsx, packages/ra-ui-materialui/src/form/SimpleForm.tsx, packages/ra-ui-materialui/src/form/TabbedForm.stories.tsx, packages/ra-ui-materialui/src/form/TabbedForm.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx
=> Fix Forms Components To Support false for toolbar prop

packages/ra-core/src/dataProvider/useUpdateMany.ts
=> Add Support For returnPromise in useUpdateMany

docs/Buttons.md, docs/Reference.md, docs/SortButton.md
=> [Doc] Fix `<SaveButton>` is documented in two different chapters

packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx
=> Fix DateTimeInput Validation

docs/ReferenceArrayInput.md
ReferenceArrayInput does not have a "label" props anymore as stated above on that same file.
=> chg: :memo: Remove label from ReferenceArrayInput

docs/LocalesMenuButton.md, docs/Translation.md, packages/ra-core/src/i18n/index.ts, packages/ra-core/src/i18n/useLocales.ts, packages/ra-core/src/types.ts, packages/ra-ui-materialui/src/button/LocalesMenuButton.tsx, packages/ra-ui-materialui/src/layout/AppBar.tsx
Supporting multiple locales is cumbersome:
- configure the i18nProvider in one file
- make a custom appbar to include the `LocalesMenuButton`
- remember to add the title in the appbar as it is not included automatically when passing custom children
- sync the i18nProvider locales with the `LocalesMenuButton` options
Defines the available locales in the same file they are added (the i18nProvider), thanks to a new `getLocales` method.
The Appbar will now include the `LocalesMenuButton` automatically if multiple locales are available
=> Add ability to specify available locales on the i18nProvider

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
Related to [issue 7763](https://github.com/marmelab/react-admin/issues/7763)
Fix missing transmission of generic types in `AutocompleteInput`
=> Allow disableClearable=true on AutocompleteArrayInput

docs/Fields.md
Same issue as https://github.com/marmelab/react-admin/pull/7773 
GET_MANY is [0] `posts?filter={"ids":[123,124,125]}` and ReferenceField uses GET_MANY, so the ReferenceField doc [1] shouldn't `posts?ids=[789,735]`
[0] https://github.com/marmelab/react-admin/blob/1.x/docs/RestClients.md?plain=1#L68
[1] https://github.com/marmelab/react-admin/blob/1.x/docs/Fields.md?plain=1#L432
=> Fix `Fields` doc reference to `getMany()` usage in v1.x

packages/ra-ui-materialui/src/field/FunctionField.tsx, packages/ra-ui-materialui/src/field/types.ts
Issue [https://github.com/marmelab/react-admin/issues/7702](https://github.com/marmelab/react-admin/issues/7702)
Type fix is based on [minimal resolution](https://github.com/marmelab/react-admin/issues/7702#issuecomment-1128936498) suggested by @fzaninotto
=> [Typescript] Fix `FunctionField` generic typing restriction

packages/ra-core/src/util/FieldTitle.tsx, packages/ra-ui-materialui/src/Labeled.tsx, packages/ra-ui-materialui/src/field/types.ts, packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
Fixes [Component <FilterLiveSearch> definition is missing the fullWidth parameter · Issue #7755 · marmelab/react-admin](https://github.com/marmelab/react-admin/issues/7755)
Harmonization of the `label` parameter type between `CommonInputProps` and `LabeledProps`
=> Fix in Typescript definitions

packages/ra-ui-materialui/src/layout/Menu.stories.tsx
A step towards complete visual testing through storybook cases.
=> Add a storybook case for `Menu` 

docs/AccordionForm.md, docs/Calendar.md, docs/CreateDialog.md, docs/EditDialog.md, docs/EditableDatagrid.md, docs/ReferenceManyToManyField.md, docs/ReferenceManyToManyInput.md, docs/TreeWithDetails.md, docs/WizardForm.md
React-admin EE v4 was released yesterday, and some of its components have changed their syntax.
=> [Doc] Fix Enterprise Edition modues syntax following 4.0 release

docs/Theming.md
=> [Doc] Fix Theming doc uses outdated syntax for conditional formatting example

docs/Buttons.md, packages/ra-ui-materialui/src/defaultTheme.ts
Fixes: https://github.com/marmelab/react-admin/issues/7771
https://user-images.githubusercontent.com/17087167/171428166-a9e90c03-c313-49a2-878f-3ac9114ab5dc.mov
https://user-images.githubusercontent.com/17087167/171428222-c88c5c02-646b-415b-b789-ccbaecaa57a2.mov
=> Add focus states to boolean and checkbox

packages/ra-core/src/dataProvider/useDataProvider.ts
Fixes https://github.com/marmelab/react-admin/issues/7815
=> Fix `useDataProvider` returning undefined value when unauthorized 401 error is thrown

docs/Inputs.md
Now that TipTap has become the default RichTextInput implementation
Refs https://github.com/marmelab/ra-richtext-tiptap/issues/2
=> [Doc] Remove link to third-party TipTap input component

examples/data-generator/package.json, packages/ra-core/package.json, packages/ra-data-fakerest/package.json, packages/ra-data-graphql-simple/package.json, packages/ra-data-graphql/package.json, packages/ra-data-json-server/package.json, packages/ra-data-localstorage/package.json, packages/ra-data-simple-rest/package.json, packages/ra-i18n-polyglot/package.json, packages/ra-input-rich-text/package.json, packages/ra-language-english/package.json, packages/ra-language-french/package.json, packages/ra-no-code/package.json, packages/ra-no-code/src/ResourceConfiguration/FieldConfiguration/FieldTypeInput.tsx, packages/ra-no-code/src/ResourceConfiguration/FieldConfiguration/FieldViewsInput.tsx, packages/ra-ui-materialui/package.json, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/react-admin/package.json, yarn.lock
Fixes #7811, #7580
Reverts #6993
=> Fix sourcemaps support with TS

packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Fix [7817](https://github.com/marmelab/react-admin/issues/7817)
Add missing `LabelPrefixContextProvider` in `FiltersForm` / kudos to @slax57
=> Fix ReferenceInput generated label in FilterForm

docs/AutocompleteArrayInput.md, docs/AutocompleteInput.md, docs/SelectArrayInput.md, docs/SelectInput.md
This has been bugging me for a while now and I finally figured it out! The data passed to onSuccess should not be deconstructed from props.
=> [Docs] Fix Creating New Choices examples

packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
Fix https://github.com/marmelab/react-admin/issues/7814
=> Fix Datagrid with expand element expands ALL rows when used as a child of ArrayField

docs/NumberInput.md, packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
The [Filter Button/Form combo](https://marmelab.com/react-admin/FilteringTutorial.html#the-filter-buttonform-combo) changes the filter value as the user types. But, as explained earlier in this page, `<NumberInput>` converts the input value to a number on blur.
This means that using `<NumberInput>` in a filter form will not work as expected. The filter will only change when the user presses the Enter key, which differs from the other input types.
In a filter form, you should use a `<TextInput type="number">` instead:
```jsx
import { TextInput } from 'react-admin';
const convertStringToNumber = value => {
const float = parseFloat(value);
return isNaN(float) ? null : float;
};
const productFilters = [
<TextInput label="Stock less than" source="stock_lte" type="number" …
```
=> Fix NumberInput seems buggy when used in a FilterForm

docs/Create.md, docs/Edit.md, docs/List.md, docs/Show.md, packages/ra-core/src/controller/create/useCreateController.spec.tsx, packages/ra-core/src/controller/create/useCreateController.ts, packages/ra-core/src/controller/edit/useEditController.spec.tsx, packages/ra-core/src/controller/edit/useEditController.ts, packages/ra-core/src/controller/list/useListController.spec.tsx, packages/ra-core/src/controller/list/useListController.ts, packages/ra-core/src/controller/show/useShowController.spec.tsx, packages/ra-core/src/controller/show/useShowController.ts, packages/ra-ui-materialui/src/detail/Show.stories.tsx, packages/ra-ui-materialui/src/list/List.stories.tsx, packages/ra-ui-materialui/src/types.ts
```jsx
import { Edit, SimpleForm } from 'react-admin';
const PostEdit = () => (
<Edit mutationOptions={{ meta: { foo: 'bar' } }}>
<SimpleForm>
...
</SimpleForm>
</Edit>
);
```
Closes #7357
Refs #7785, #7665
=> Add ability to set `meta` in page components

docs/AutocompleteInput.md, packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Fixes https://github.com/marmelab/react-admin/issues/7822
=> [Doc] Fix AutocompleteInput creation props and examples

packages/ra-input-rich-text/package.json, packages/ra-input-rich-text/src/RichTextInput.tsx, packages/ra-input-rich-text/src/RichTextInputToolbar.tsx, packages/ra-input-rich-text/src/buttons/ColorButtons.tsx, packages/ra-input-rich-text/src/buttons/ImageButtons.tsx, packages/ra-input-rich-text/src/buttons/index.ts, yarn.lock
As discussed in https://github.com/marmelab/react-admin/issues/7806, here is the PR to have both ColorButtons (including font and highlight color) and ImageButtons components for RichTextInput toolbar.
This is my first PR ever on any non-private repository, so please feel free to make me some feedbacks (english or french).
Plus, I noticed that the translation of all buttons (existing ones as well) do not exist, so even in french the titles are in english (default).
=> [RFR] Add rich text input toolbar buttons

packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Fix `<AutocompleteInput>` storybook does not select newly created option.
Applies the same fix as https://github.com/marmelab/react-admin/pull/7833 in the storybook.
=> Fix `<AutocompleteInput>` storybook does not select newly created option

docs/ReferenceField.md, packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx
=> Add support for <ReferenceField emptyText> when the reference is missing

packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
Fixes https://github.com/marmelab/react-admin/issues/7832
=> [TypeScript] Fix FilterLiveSearchProps should extend TextInputProps

packages/ra-ui-materialui/src/input/FileInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/7868
=> Fix `FileInput` propTypes for `label` prop

packages/ra-core/src/form/Form.spec.tsx, packages/ra-core/src/form/useAugmentedForm.ts
=> Fix Form throws error when passed a defaultValues function

packages/ra-core/src/controller/list/useListParams.ts
=> Fix useListParams might navigate to an old pathname

docs/Fields.md, docs/Inputs.md
This [third-party color input] (https://github.com/vascofg/react-admin-color-input) no longer works with react-admin v4 and is no longer maintained. So I ported the library and updated the react-admin documentation.
=> Update docs for new third party color input / field

packages/ra-data-graphql-simple/src/getResponseParser.ts
When a record has embedded arrays or objects that are not references, `ra-data-graphql-simple` still generates fields to handle references for them. This leads to invalid payloads sent to the backend when updating for instance
Check that embedded arrays and objects have identifiers before generating the field required for references. This is still not perfect but `ra-data-graphql-simple` shouldn't be used for real applications anyway
=> fix ra-data-graphql-simple response parser for embedded arrays and objects

packages/ra-data-simple-rest/src/index.ts
Update useCreateResult in the Simple REST Provider to return the API response data.
Fixes #7912
=> Fix simple dataProvider create does not return server data

docs/Tutorial.md, docs/useAuthProvider.md
Replacing useAuthProvider.getIdentity() to authProvider.getIdentity() in docs.
=> Fix use auth provider in docs

docs/CustomRoutes.md
Adding an import from "react-router-dom"
=> [Doc] Missing import in custom routes documentation

packages/ra-ui-materialui/src/layout/Layout.tsx, packages/ra-ui-materialui/src/layout/Sidebar.tsx
=> Fix AppBar jiggles when scrolling down rapidly

docs/EditBase.md, docs/useEditController.md
=> [Doc] Fix EditBase and useEditController unsupported `record` prop

docs/IconMenu.md, docs/Menu.md, docs/navigation.html
=> [Doc] Add IconMenu section

packages/ra-core/src/controller/list/useListPaginationContext.ts, packages/ra-ui-materialui/src/list/pagination/Pagination.spec.tsx, packages/ra-ui-materialui/src/list/pagination/Pagination.tsx
=> Fix <Pagination> cannot be used outside a ListContext

packages/ra-core/src/form/getSimpleValidationResolver.ts
The entire `lodash` package was imported in `getSimpleValidationResolver.ts`, preventing bundlers from properly tree-shaking unused modules at build time. 
Individually importing `lodash` modules can possibly reduce the bundle size of projects using `ra-core` by 500kb.
=> Fix: individually import lodash modules to reduce bundle size

examples/simple/src/posts/PostCreate.tsx, packages/ra-core/src/form/choices/useChoicesContext.ts
=> Fix useChoicesContext props should take precedence over context

packages/ra-core/src/core/CoreAdmin.spec.tsx, packages/ra-core/src/types.ts
=> [TypeScript] Fix `<Admin>` used with function child and fragment does not compile

packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
Note that on macOS, button is unreachable only when parent group list is unfocused but this behaviour will always occur on Linux and Windows Firefox versions.
https://user-images.githubusercontent.com/102964006/179513159-5d0b1296-b179-4de5-8e3f-9f4ff9dc0e23.mov
=> [Fix] Can't un-toggle filter through secondary action button in aside list

packages/ra-ui-materialui/src/layout/Theme/useTheme.spec.tsx, packages/ra-ui-materialui/src/layout/Theme/useTheme.ts
Fix https://github.com/marmelab/react-admin/issues/7805
React-Admin `useTheme` hook use the store, and when no data is available there, returns the default value specified as hook parameter.  As this default theme parameter is not available in theme data consumption, the best solution was to use MUI `useTheme` hook for reading purpose. This PR aims at automating this process and avoid misuses.
=> Fix `useTheme` returns undefined as value

docs/MultiLevelMenu.md, docs/navigation.html
=> [Doc] Add entry for MultiLevelMenu

docs/RichTextInput.md
Title is self-explanatory - this PR fixes a minor typo in the RichTextInput docs.
=> Fix typo in RichTextInput Docs

packages/ra-core/src/auth/useCheckAuth.spec.tsx, packages/ra-core/src/auth/useLogout.spec.tsx, packages/ra-core/src/auth/useLogout.ts
=> Fix error after being logged out and logging in again

docs/IfCanAccess.md, docs/Reference.md, docs/WithPermissions.md, docs/navigation.html, packages/ra-core/src/auth/WithPermissions.tsx
The previous docs has broken examples and broken links, which causes some confusion.
=> [doc]: fix `<WithPermissions />` and `<IfCanAccess />` doc

docs/Authenticated.md, packages/ra-core/src/auth/Authenticated.tsx, packages/ra-core/src/auth/useAuthState.ts, packages/ra-core/src/auth/useAuthenticated.ts
The `useAuthenticated()` hook and old `<Authenticated />` component is always optimistic, other auth hooks cannot be used directly inside `<Route element>` and causes boilerplate, and `<Admin requireAuth>` completely disallows anonymous access to all the pages.
This feature gives user finer granularity of control of which custom routes can be anonymously accessed, which can be optimistically rendered, and which should not leak the UI and does not have flash of UI.
=> Add `requireAuth` to <Authenticated /> component

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fix https://github.com/marmelab/react-admin/issues/7935
=> Fix leading character in AutocompleteInput can not be deleted

packages/ra-core/src/controller/input/useReferenceParams.ts
Corrects `Can't perform a React state update on an unmounted component error` while using ReferenceArrayInput in list filter.
Error appears in `CreateDialog` or `EditDialog` when dialog box is closed faster than the filters debounce delay of any autocomplete input.
=> Fix error in useReferenceParams

docs/AuthProviderWriting.md, packages/ra-core/src/auth/useLogin.spec.tsx, packages/ra-core/src/auth/useLogin.ts, packages/ra-core/src/types.ts
=> Add support for custom login redirection

packages/ra-ui-materialui/src/input/LoadingInput.tsx, packages/ra-ui-materialui/src/input/ReferenceArrayInput.stories.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.stories.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/input/index.ts
Closes #7975
https://user-images.githubusercontent.com/99944/180303089-c9d9620d-5cd6-471c-a777-be1ad5975622.mov
https://user-images.githubusercontent.com/99944/180305200-47dcbdf0-bd7e-4689-a757-72e39298fc8c.mov
=> Fix `<SelectInput>` loading UI to avoid visual jump

docs/Breadcrumb.md, docs/navigation.html
=> [Doc] Add breadcrumb documentation

docs/ReferenceInput.md
+  Providing prop `label` to ReferenceInput doesn't take any effect. It should be passed to its child *Input component.
=> [doc] Fix: Incorrect example code block of ReferenceInput

packages/ra-ui-materialui/src/layout/Menu.tsx
Using the `dashboard` property of the `Admin` component results in an error with the `Menu` component.
The `DashboardMenuItem` does not have a `key` set, hence React complains about missing unique-keys.
This PR defines a key (`default-dashboard-menu-item`) for the dashboard's menu item.
=> fix(menu): add unique key

README.md, docs/Actions.md, docs/Admin.md, docs/Caching.md, docs/Create.md, docs/DataProviders.md, docs/Edit.md, docs/Layout.md, docs/Upgrade.md, docs/useGetOne.md, packages/ra-core/src/dataProvider/useCreate.ts, packages/ra-core/src/dataProvider/useDelete.ts, packages/ra-core/src/dataProvider/useDeleteMany.ts, packages/ra-core/src/dataProvider/useUpdate.ts, packages/ra-core/src/dataProvider/useUpdateMany.ts, packages/react-admin/README.md
React Query new major version induced a change in their documentation, current PR fix all links pointing toward it.
=> [Doc] Fix react-query links in documentation

packages/ra-ui-materialui/src/input/DatagridInput.tsx, packages/ra-ui-materialui/src/input/DateInput.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.tsx, packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/InputPropTypes.ts, packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/SelectArrayInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx, packages/ra-ui-materialui/src/input/TextInput.tsx
- add element to label proptypes for inputs to eliminate browser console errors when passing an element as a label
- fix imports in DatagridInput (fixes https://github.com/marmelab/react-admin/issues/8018)
=> Input label proptypes and DatagridInput imports

docs/Search.md, docs/Theming.md, docs/navigation.html
=> [Doc] Add Search component

docs/Search.md
Missed the review of the [8021 PR](https://github.com/marmelab/react-admin/pull/8021)
=> [Doc] Fix few typos

packages/ra-core/src/i18n/TranslationMessages.ts, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/list/List.stories.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx, packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
Fix #7831
https://user-images.githubusercontent.com/102964006/181250139-e211c744-d1c9-46ac-b79d-974027f2450d.mov
=> Add a "Clear all filters" button

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.stories.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx, packages/ra-ui-materialui/src/input/TextInput.stories.tsx
`<NumberInput>` changes the form state on change, but only displays the string entered by the user. 
Closes #7919
=> Fix NumberInput state only changes on blur

packages/ra-ui-materialui/src/input/ArrayInput/AddItemButton.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
=> Fix ArrayInput Adding Previously Removed Item

docs/Buttons.md, packages/ra-core/src/controller/button/useDeleteWithConfirmController.spec.tsx, packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.spec.tsx, packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
Fix #8016
Kudos to @carlos-duran
[useMutation documentation](https://react-query-v3.tanstack.com/reference/useMutation).
=> Fix delete contexts don't send mutation `meta`

packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
When trying to export a component based on MenuItemLink, TypeScript complains with:
> Exported variable 'MenuItemLink' has or is using name 'Props$1' from external module 'a/file/path/node_modules/ra-ui-materialui/dist/index' but cannot be named. ts(4023)
I believe this is due to the `React.forwardRef` not being properly typed in that component.
=> [TypeScript] Fix MenuItemLink prop type isn't exported

packages/ra-ui-materialui/src/input/SelectInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectInput.stories.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Add ability to remove empty option in SelectInput for required fields

docs/AutocompleteInput.md, docs/SelectInput.md, examples/simple/src/comments/CommentCreate.tsx, packages/ra-core/src/controller/input/useReferenceInputController.ts, packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput suggestions flicker when used inside ReferenceInput

docs/Create.md, docs/Edit.md, docs/Inputs.md
From Trello 753
Mention `transform` and `parse`. `parse` is important because you might want that an input always apply this sanitize in all forms. You could re-export some or all react-admin inputs or views to set their parse or transform by default to sanitize empty values.
=> [Doc] Document how to sanitize form values

packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/FileInputPreview.tsx
=> Fix use custom preview component for FileInput and ImageInput

packages/ra-core/src/controller/input/useReferenceInputController.spec.tsx, packages/ra-core/src/form/useIsFormInvalid.ts
Fix #8049
`useIsFormInvalid` will only check if `useFormState` has errors.
Because `useFormState`does not return `isValid` state if `useForm` mode is null ([read more](https://react-hook-form.com/api/useformstate
))
https://user-images.githubusercontent.com/18294269/183671325-34926bf2-a8e6-46c3-80f6-734c1d744e40.mp4
=> [Fix] Validation errors don't show on `Edit` page

docs/JsonSchemaForm.md, docs/navigation.html
=> [Doc] Add JsonSchemaForm doc

packages/ra-core/src/form/index.ts, packages/ra-core/src/form/useAugmentedForm.ts, packages/ra-core/src/form/useNotifyIsFormInvalid.ts
Replace useIsFormInvalid by useNotifyIsFormInvalid. 
Form now display notification on each submit if form has errors
https://user-images.githubusercontent.com/18294269/183698273-b016ae3d-2673-4bc0-a575-8d95de6d2171.mp4
=> Fix Display notification on each submit if form has errors

packages/ra-core/src/store/useStore.spec.tsx, packages/ra-core/src/store/useStore.ts
Fix `useStore` hook not resetting its internal state when the key changes.
Issue identified while working on https://github.com/marmelab/react-admin/pull/8042
=> Fix useStore internal state reset when key changes

docs/navigation.html, docs/useGetTree.md
=> [Doc] Add useGetTree doc

docs/FileInput.md, docs/ImageInput.md, packages/ra-ui-materialui/src/input/FileInput.tsx, packages/ra-ui-materialui/src/input/ImageInput.tsx
=> Fix remove useless `RaFileInput-preview` and `RaImageInput-preview` classnames

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> [TypeScript] Add `resettable` prop to `SelectInputProps`

packages/ra-ui-materialui/src/layout/Notification.tsx
=> Fix: `multiLine` prop is not working in `Notification`

examples/tutorial/README.md
users get an error when they run without the make build command
=> [Doc] Fix installation instructions in tutorial project

docs/Upgrade.md
=> [Doc]  Fix typos in migration to v4 guide

docs/ReferenceArrayField.md
All components that write ReferenceField in the ReferenceArrayField document have been changed to ReferenceArrayField.
=> [Doc] Fix typos in `ReferenceArrayField`

packages/ra-core/src/core/CoreAdmin.tsx
`<CoreAdmin>` doesn't allow to override the default `store`. Only `<Admin>` does.
=> Fix `<CoreAdmin store>` prop is ignored

docs/Inputs.md
In the input doc, `transform` is not the right prop, replace it by `format`
=> [Doc] Fix upgrade guide still mentioning TextInput transform pop

docs/ArrayInput.md, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.stories.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx, packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIteratorStyles.ts
=> Add support for SimpleFormIterator inline and sx props

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Closes #8069
I'm not documenting the feature as the user experience isn't ideal. We should instead offer an alternative based on MUI's Autocomplete, with creation support. But it's non trivial, so in the meantime, let's let ArrayInput support scalar values.
=> Fix ArrayInput doesn't support scalar values

packages/ra-core/tsconfig.json, packages/ra-data-fakerest/tsconfig.json, packages/ra-data-graphql-simple/tsconfig.json, packages/ra-data-graphql/tsconfig.json, packages/ra-data-json-server/tsconfig.json, packages/ra-data-localstorage/tsconfig.json, packages/ra-data-simple-rest/tsconfig.json, packages/ra-i18n-polyglot/tsconfig.json, packages/ra-input-rich-text/tsconfig.json, packages/ra-language-english/tsconfig.json, packages/ra-language-french/tsconfig.json, packages/ra-no-code/tsconfig.json, packages/ra-ui-materialui/tsconfig.json, packages/react-admin/tsconfig.json, tsconfig.json
Source cannot be inspected in browser
=> Fix sourcemaps are missing from build

packages/ra-core/src/dataProvider/useGetRecordId.spec.tsx, packages/ra-core/src/dataProvider/useGetRecordId.ts
_ Add useGetRecordId in ra-core_
=> Feat: Add useGetRecordId in ra-core

packages/ra-core/src/inference/InferredElement.ts, packages/ra-core/src/inference/inferElementFromValues.spec.tsx, packages/ra-core/src/inference/inferElementFromValues.tsx, packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx, packages/ra-ui-materialui/src/input/index.ts, packages/ra-ui-materialui/src/list/ListGuesser.stories.tsx, packages/ra-ui-materialui/src/list/listFieldTypes.tsx
The guessers couldn't take advantage of the recordRepresentation introduced in 4.3 due to an override at the listTypes level.
=> Fix guesser for of ReferenceField and ReferenceArrayField

packages/ra-core/src/dataProvider/useGetList.spec.tsx, packages/ra-core/src/dataProvider/useGetList.ts
**Problem:** Providing a `onSuccess` side effect to `useGetList` overrides the default one set by react-admin. This results in the `'getOne'` react-query cache data not being populated as they should be (and causes bugs in some EE components).
**Solution:** Execute both the `onSuccess` side effects, as it is done in other hooks like `useUpdate` for instance
=> Fix `useGetList`'s `onSuccess` side effect overriding internal one

docs/ReferenceArrayField.md
#8104 contained a hidden enhancement: now `<ReferenceArrayField>` can work without children. The documentation should reflect that, and make the child-less syntax front and foremost.
=> [doc] Fix ReferenceArrayField doc to use a child-less syntax first

packages/ra-data-localstorage/README.md
This patch just corrects a minor code error in the README of ra-data-localstorage
=> Fix code error in *Usage* example of ra-data-localstorage README

docs/canAccess.md, docs/useCanAccess.md, docs/usePermissions.md
Fix some broken /rbac links in docs
=> Doc: Fix rbac links

docs/useList.md, packages/ra-core/src/controller/list/useList.spec.tsx, packages/ra-core/src/controller/list/useList.ts
I tried to make the adjustment to be able to meet this feature #7970
Any suggestion or consideration for making a change just let me know!
- Allow a callback to perform filters on the view ✅ 
- Test ✅ 
- Docs ✅
=> Add a custom filter property in useList

docs/FilterButton.md, packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
Maybe not the best code suggestion, but the idea would basically be to add a possible flag on the filterbutton to disable the save query. If you guys give me suggestions and allow me to continue with pr I can improve it
Closes #8062
=> feat: add option to hide savequery in filter button

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput `clearOnBlur` has no effect

packages/ra-core/src/dataProvider/useDataProvider.spec.tsx, packages/ra-core/src/dataProvider/useDataProvider.ts
=> fix: 🐛 return consistent data types from dataprovider on logout

docs/CustomRoutes.md, packages/ra-core/src/core/Resource.spec.tsx, packages/ra-core/src/core/Resource.tsx, packages/ra-core/src/types.ts
React admin makes it fast to develop admin-interfaces with react.
However, when resources get more and more functions it is a bit unhandy to pass CustomRoutes to <Admin/>
This PR adds children as a property of resources and makes it possible to define the whole resource with custom sub-routes in a seperate typescript module:
``` tsx
import ListView from "./list";
import CustomRoute from "./customroute";
const MyResource = () => {
return {
list: ListView,
children: <CustomRoute/>
}
}
```
=> [Feat] add 'children' prop to Resources

packages/ra-core/src/controller/useSortState.ts, packages/ra-ui-materialui/src/input/SelectInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
=> Fix SelectInput reorders choices by id

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix allow zero as value in AutocompleteInput

docs/Fields.md, packages/ra-ui-materialui/src/field/BooleanField.spec.tsx, packages/ra-ui-materialui/src/field/BooleanField.tsx, packages/ra-ui-materialui/src/field/ChipField.spec.tsx, packages/ra-ui-materialui/src/field/ChipField.tsx, packages/ra-ui-materialui/src/field/DateField.spec.tsx, packages/ra-ui-materialui/src/field/DateField.tsx, packages/ra-ui-materialui/src/field/EmailField.spec.tsx, packages/ra-ui-materialui/src/field/EmailField.tsx, packages/ra-ui-materialui/src/field/FileField.spec.tsx, packages/ra-ui-materialui/src/field/FileField.tsx, packages/ra-ui-materialui/src/field/ImageField.spec.tsx, packages/ra-ui-materialui/src/field/ImageField.tsx, packages/ra-ui-materialui/src/field/NumberField.spec.tsx, packages/ra-ui-materialui/src/field/NumberField.tsx, packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.tsx, packages/ra-ui-materialui/src/field/SelectField.spec.tsx, packages/ra-ui-materialui/src/field/SelectField.tsx, packages/ra-ui-materialui/src/field/UrlField.spec.tsx, packages/ra-ui-materialui/src/field/UrlField.tsx
Implementing the emptyTextt translation feature for issue #8044
I added useTranslate to always translate emptyText, if it doesn't find the translation it will display the text normally
- Code ✅ 
- Test ❌ 
- Documentation ❌ 
I was wondering what is expected of me to document and which test I should add. Can you help me @fzaninotto?
Closes #8044
=> feat: add translate in emptyText on ra-ui-material fields

cypress/integration/edit.js, docs/Translation.md, docs/TranslationSetup.md, docs/TranslationTranslating.md, examples/simple/src/Layout.tsx, examples/simple/src/i18nProvider.tsx, packages/ra-i18n-polyglot/src/index.ts, packages/react-admin/src/defaultI18nProvider.ts
=> Add support for getLocales in Polyglot i18nProvider

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/8153
=> Fix ArrayInput helperText not showing error message

packages/ra-ui-materialui/src/field/BooleanField.tsx, packages/ra-ui-materialui/src/field/ChipField.tsx, packages/ra-ui-materialui/src/field/DateField.tsx, packages/ra-ui-materialui/src/field/EmailField.tsx, packages/ra-ui-materialui/src/field/FileField.tsx, packages/ra-ui-materialui/src/field/ImageField.tsx, packages/ra-ui-materialui/src/field/NumberField.tsx, packages/ra-ui-materialui/src/field/ReferenceField.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.tsx, packages/ra-ui-materialui/src/field/SelectField.tsx, packages/ra-ui-materialui/src/field/UrlField.tsx
=> Fix warning in Field components

docs/Routing.md
Just noticed that this is missing on https://marmelab.com/react-admin/Routing.html#adding-custom-pages
=> Add missing Route import to Routing docs example

packages/ra-core/src/store/localStorageStore.ts
I have a unit test for it in the configurable branch - I haven't added ift here to avoi!d conflicts
=> Fix localStorageStore.reset() does not remove all items

docs/Inputs.md
=> fix parse  doc

docs/Authentication.md, docs/Theming.md, docs/Upgrade.md, docs/useLogout.md
Brings the examples in sync with the rest, e.g. https://marmelab.com/react-admin/Layout.html#appbar
This also seems to be needed to avoid rendering errors about components not rendering anything / missing returns
=> Add missing props in docs layout examples

docs/Upgrade.md
The upgrade example incorrectly uses an element compared to e.g. https://marmelab.com/react-admin/Theming.html#using-a-custom-logout-button
=> Fix layout prop of Admin component in upgrade example

docs/SimpleList.md, docs/SingleFieldList.md
There used to be documentation on the possible options with `linkType`, but this is from an [old PR](https://github.com/marmelab/react-admin/pull/490) and that part of the documentation changed with time since it's no longer a property in `ReferenceField`.
I have added documentation for the following options for `linkType`:
* `"show"`
* `"edit"`
* `false`
Though I did not add documentation for the empty string option `""`, because it has inconsistent behavior with `false` when used in `SimpleList`:
* `""` would not route to other pages, but the buttons will **still** be clickable.
* `false` would not route to other pages, and the buttons will **not** be clickable.
=> adjusted documentation for the `linkType` property found in `SimpleList` and `SingleFieldList` 

docs/Community.md, docs/navigation.html
... in which we're announcing our Discord server. I'm not sure about the invite link, please test and report here if it doesn't work:
* https://discord.gg/GeZF9sqh3N
=> [Doc] Add community page

docs/Inputs.md
=> [Doc] Fix FormDataConsumer usage example

packages/ra-core/src/controller/list/useListController.spec.tsx, packages/ra-core/src/controller/list/useListController.ts, packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx, packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Fixes https://github.com/marmelab/react-admin/issues/7986
=> Fix type error when queryOptions enable is set to false

docs/ReferenceInput.md, packages/ra-core/src/controller/input/useReferenceInputController.ts, packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx, packages/ra-ui-materialui/src/input/ReferenceInput.tsx
=> Add `queryOptions` prop to `ReferenceInput`

packages/ra-core/src/form/Form.spec.tsx, packages/ra-core/src/form/Form.tsx, packages/ra-core/src/form/useAugmentedForm.ts, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/DateInput.spec.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/FileInput.spec.tsx, packages/ra-ui-materialui/src/input/ImageInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/TimeInput.spec.tsx, packages/ra-ui-materialui/src/input/TranslatableInputs.spec.tsx
React-hook-form passes the event alongside the form values to the submit handler. It allows implementing things such as having multiple submit buttons with different values. See https://github.com/react-hook-form/react-hook-form/issues/5494#issuecomment-855224219
=> Pass all arguments from react-hook-form to onSubmit

packages/ra-core/src/auth/usePermissions.spec.tsx, packages/ra-core/src/auth/usePermissions.ts
I wanted to hook up the builtin permission system from react-admin and I experienced a ton of queries: one per permission check.
the docs have a hidden (pro/paid flagged) hint on how to solve this:
https://marmelab.com/react-admin/AuthRBAC.html#performance
since we are using react-query already all-over why don't we use it for the permission-fetching?
This adds a lot of sane defaults: re-fetch on window focus, cache invalidation on logout, retries with back-off, ...
I think the same could be applied to `useCheckAuth`, `useGetIdentity`,... but I'd like to hear your comments first.
=> [ra-core] use react-query useQuery for permissions fetching

packages/ra-core/src/form/Form.spec.tsx, packages/ra-core/src/form/Form.stories.tsx, packages/ra-core/src/form/getFormInitialValues.ts
=> Fix null values cause warning in forms

packages/ra-core/src/i18n/TranslationMessages.ts, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts
I noticed that `ra.configurable.templateError` was added in version 4.4.0 but is unused.
It seems that they deleted `translate(ra.configurable.templateError, ...)` when changed to translate instead of lodash.
https://github.com/marmelab/react-admin/commit/c4a6ac61599fe8dd48d74590a51a36f44205de13#diff-be8dc1889be155c57e45c5b1e0d96f8f05466f57a969429ef5cd766baedcde9aL22-L24
(deleted /packages/ra-core/src/preferences/useRenderTemplate.ts)
=> Remove unused TranslationMessage

examples/simple/src/Layout.tsx, packages/ra-ui-materialui/src/layout/Layout.tsx
MUI's `<CSSBaseline>` is crucial to get a good UI with react-admin, yet we never mention it in the documentation.
We do our tests with the Simple example, which uses CSSBaselaine, without realizing that for most users, without CSS Baseline, the UI is degraded.
Enable it by default 
Note the top margin between the AppBar and the content
=> Add CSSBaseline to the default layout for better UI

packages/ra-core/src/controller/input/useReferenceInputController.ts
**Problem:** to merge the possible choices with the current choice, `useReferenceInputController` checks if the current value is already in the possible values or not (https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/useReferenceInputController.ts#L125).
This check only works if `id` is of type string, because we check it against the current value coming straight from the form (with RHF's `useWatch`).
In the `/story/ra-ui-materialui-input-referenceinput--with-radio-button-group-input` story, we use ids that are number, which causes the merge to fail.
**Solution:** we should compare it with the id of the reference record fetched with `useReference`, which should be of the matching type
**Alternatives:**
- Replace `===` with `==` (but I was unsure if …
=> Fix `useReferenceInputController` all choices merge in case `id` is not a string

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.spec.tsx, packages/ra-ui-materialui/src/input/SelectInput.stories.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix SelectInput and AutocompleteInput change empty references

docs/AutocompleteInput.md, docs/SelectInput.md, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.stories.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix `<SelectInput emptyValue>` accepts null value

packages/ra-core/src/controller/edit/useEditController.spec.tsx, packages/ra-core/src/controller/edit/useEditController.ts
`useEditController` should return the redirectTo used to redirect (if any) or the default, just like `useCreateController` does it, not the default
=> Fix redirectTo returned by `useEditController`

docs/List.md, packages/ra-ui-materialui/src/list/pagination/Pagination.tsx
=> [Doc] Add  List's `perPage` and `pagination.rowsPerPages` props relationship note

.github/workflows/codeql-analysis.yml
Updates the build permissions for the CodeQL job, now that the github token default permission has been reduced to read-only.
Supersedes https://github.com/marmelab/react-admin/pull/8225
Credits go to [boahc077](https://github.com/boahc077) for raising the issue in the first place.
=> [chore] CI: update CodeQL-Build permissions following github token permissions change

packages/ra-ui-materialui/src/layout/Loading.tsx
The Loading component's secondary text has a trailing dot that prevents people from leaving empty that section.
=> Remove trailing dot from secondary loading text

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix AutocompleteInput input's value not updating correctly

packages/ra-ui-materialui/src/layout/Loading.tsx
Current behavior: 
If we omit the `loadingPrimary` and `loadingSecondary` props, the component still displays the translation keys (`ra.page.loading` and `ra.message.loading`) beneath the spinner. 
This fixes that.
=> Fix displaying texts in Loading in case of arguments are not passed

docs/EditTutorial.md, docs/Form.md, docs/SimpleForm.md, docs/TabbedForm.md, packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
React-router 6.4.0 removed support for `navigator.block`, which is necessary for the `warnWhenUnsavedChanges` feature (see https://github.com/remix-run/react-router/issues/9262).
This breaks existing applications using react-router >= 6.4 and a custom router. 
The `warnWithUnsavedChanges` feature fails silently when using with react-router >= 6.4 
Closes #8163
=> Remove support for warnWhenUnsavedChange when react-router doesn't allow it

packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
=> Fix `ArrayInput` throws an error when providing a `helperText`

packages/ra-ui-materialui/src/button/SaveButton.spec.tsx, packages/ra-ui-materialui/src/button/SaveButton.tsx, packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx, packages/ra-ui-materialui/src/input/TimeInput.spec.tsx
Fixes #8258
**PROBLEM**
`SaveButton` enable state may be true, even though no inputs have been changed.
This is because `useFormState().isDirty` might differ from `useFormState().dirtyFields` (https://github.com/react-hook-form/react-hook-form/issues/4740)
This is the expected behavior of `react-hook-form` and it may happen when you have a missing `defaultValue` for one of the inputs
· `dirtyFields` will mark the field dirty or not individually.
· `isDirty` will always do a deep equal against your defaultValues to determined form is dirty or not.
https://github.com/react-hook-form/react-hook-form/discussions/7860#discussioncomment-2208434
This is key, since `defaultValue` prop might be `undefined`, and in some cases you end up with `isDirty` being `true` but `dirtyFields` being an empty …
=> Fix improve SaveButton enable state

docs/CheckboxGroupInput.md, packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/CheckboxGroupInputItem.tsx
Add `labelPlacement` props so that the CheckboxGroupInput can have labels on the top of checkboxes.  It is useful when there is limited width for a checkbox group. For example,  a weekday checkbox group squeezes in `xs={4}`.
<del>I will continue on this PR for RadioGroupInput if you think this change is desirable.</del> I find `labelPlacement` in RadioGroupInput looks weird.  I will keep this PR only for `CheckboxGroupInput`.
=> Allow label position config in CheckboxGroupInput

docs/Create.md
The `TextInput` component expects the `multiline` prop to be lowercase while the `Create` docs have it written as 'multiLine`.
=> Docs: fix small typo in Create.md

packages/ra-data-simple-rest/README.md
A user complained that implementing an API fitting `ra-data-simplerest` REST dialect was error prone.
Add example calls with dataProvider syntax, REST request and response.
=> [Doc] Add example API calls to ra-data-simplerest

docs/EditTutorial.md, docs/Form.md, docs/Reference.md, docs/SaveButton.md, docs/SimpleForm.md, docs/TabbedForm.md
=> [Doc] Clarify incompatibility of SaveButton of type='button' with custom Form's onSubmit

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
`AutocompleteInput` should not display the empty choice when `validate={required()}`
=> Fix `AutocompleteInput` displays empty choice when `validate={required()}`

docs/ReferenceOneField.md, packages/ra-core/src/controller/field/useReferenceOneFieldController.spec.tsx, packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx, packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
=> ReferenceOneField accept sort & filter props

docs/AutocompleteInput.md, packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
=> Fix `AutocompleteInput` should only add an empty option when there is an `emptyText`

docs/404.html
**Problem**
`navigation.html` is included relatively to the current rendered path. But `404.html` is at the root, so it always includes the `navigation.html` file located at the root (hence the latest).
**Solution**
Use JS to dynamically fetch the navigation side panel and replace the html content by the one fetched. There is no way to do it statically because the current version can only be fetched from the URL, which is unavailable to Jekyll for a 404 error page.
**Screenshots**
=> [Doc] Fix navigation panel version in 404.html

packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx, packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/8297
=> Fix suggestions do not repopulate on blur in `AutocompleteInput` when used inside `ReferenceInput`

packages/ra-input-rich-text/src/RichTextInput.spec.tsx, packages/ra-input-rich-text/src/RichTextInput.tsx
=> Fix `RichTextInput` doesn't update when record field updates

packages/ra-core/src/store/localStorageStore.spec.ts, packages/ra-core/src/store/localStorageStore.ts
=> localStorageStore now delete only items prefixed on version change

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx, packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx, packages/ra-ui-materialui/src/input/SelectInput.tsx
=> fix: warn when choices prop is undefined

packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx, packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
Fixes #8277
Note: The related story already includes an alwaysOn filter
=> Fix List filter `Remove all filters` item not present on alwaysOn filters

docs/Vite.md
=> [Doc] Fix Vite tutorial default style

docs/LocalesMenuButton.md, packages/ra-ui-materialui/src/button/Button.tsx, packages/ra-ui-materialui/src/button/LocalesMenuButton.tsx, packages/ra-ui-materialui/src/button/RefreshIconButton.tsx, packages/ra-ui-materialui/src/layout/AppBar.tsx, packages/ra-ui-materialui/src/layout/LoadingIndicator.tsx, packages/ra-ui-materialui/src/layout/SidebarToggleButton.tsx, packages/ra-ui-materialui/src/layout/UserMenu.tsx
=> Fix `<Appbar>` buttons don't have consistent spacing

packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx, packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.spec.tsx, packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
=> Fix `<BulkDeleteButton>` doesn't clear selection when used inside `<ReferenceManyField>`

docs/Validation.md
Related to #7608
I've tried it on simple project's `UserCreate` component, and it works as expected
=> [Doc] Improve server side validation example

docs/Reference.md, docs/Upgrade.md, docs/useGetOne.md
=> [Doc] Fix `useReference` hook docs

packages/ra-core/src/auth/useLogout.ts, packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
This was possible in v3 since #6469, but it was broken when migrating to v4. 
It's necessary for OIDC / OAuth workflows.
=> Fix authProvider hooks support for redirectTo: absolute URL

docs/Menu.md, packages/ra-ui-materialui/src/layout/Menu.tsx, packages/ra-ui-materialui/src/layout/ResourceMenuItem.tsx, packages/ra-ui-materialui/src/layout/index.ts
Customizing the default menu items leads to boilerplate and copy paste
Introduce a dedicated component for resource menu items. 
```jsx
import { Menu } from 'react-admin';
import BookIcon from '@mui/icons-material/Book';
import ChatBubbleIcon from '@mui/icons-material/ChatBubble';
import PeopleIcon from '@mui/icons-material/People';
import LabelIcon from '@mui/icons-material/Label';
export const MyMenu = () => (
<Menu>
<Menu.DashboardItem />
<Menu.Item to="/posts" primaryText="Posts" leftIcon={<BookIcon />}/>
<Menu.Item to="/comments" primaryText="Comments" leftIcon={<ChatBubbleIcon />}/>
<Menu.Item to="/users" primaryText="Users" leftIcon={<PeopleIcon />}/>
<Menu.Item to="/custom-route" primaryText="Miscellaneous" leftIcon={<LabelIcon />}/>
</Menu>
);
```
```jsx
import { Menu } from …
```
=> Add `<Menu.ResourceItem>`component to facilitate menu customization

docs/useNotify.md
Match documentation and `NotificationType` in `node_modules/ra-core/src/notification/types.ts`
```ts
export type NotificationType = 'success' | 'info' | 'warning' | 'error';
```
=> [Doc] Add missing error type in `useNotify` 

docs/Tutorial.md
=> [Doc] Fix react-admin's vite tutorial CSS setup

packages/ra-ui-materialui/src/input/SelectInput.tsx
=> Fix sanitize `shouldUnregister` prop out of `SelectInput`

docs/AutocompleteArrayInput.md, docs/AutocompleteInput.md
I initially change the reference to point to `MUI Autocomplete` component, but the original reference was too specific of `react-autosuggest` `shouldRenderSuggestions` docs and becomes unnecessary to make that remark with `MUI Autocomplete` `options` prop.
Especially given the fact that it's mention later on in the docs that `AutocompleteInput`/`AutocompleteArrayInput` uses `MUI Autocomplete` underneath.
But I can add it back if that is what you want
=> [Doc] Remove reference to `react-autosuggest` component

packages/ra-data-graphql/package.json, yarn.lock
Allow ra-data-graphql to use graphql v16.
In ra-data-hasura we wanted to use graphql v16 but were getting the error "Conflicting peer dependency". I ran all the tests in the ra-data-graphql with v16 and they passed. Thank you!
=> Allow GraphQL v16

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.stories.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
=> `NumberInput` not passing `format` and `parse` props to `useInput` call

packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx, packages/ra-ui-materialui/src/form/TabbedFormView.tsx
Currently, when specifying the `toolbar` prop of the TabbedForm component `false`, React issues a warning:
```
Warning: Failed prop type: Invalid prop `toolbar` of type `boolean` supplied to `TabbedFormView`, expected a single ReactElement.
```
This PR fixes PropTypes validation for the `toolbar` prop, allowing the `false` value to be used like:
```jsx
<TabbedForm toolbar={false}>...</TabbedForm>
```
=> Fix prop-types validation for TabbedFormView's `toolbar` prop

docs/SimpleFormIterator.md, examples/tutorial/src/App.css, packages/ra-language-english/src/index.ts, packages/ra-language-french/src/index.ts, packages/ra-ui-materialui/src/input/ArrayInput/ClearArrayButton.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.stories.tsx, packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx, packages/ra-ui-materialui/src/input/ArrayInput/useSimpleFormIteratorStyles.ts
This PR is related to this issue : https://github.com/marmelab/react-admin/issues/8287
https://user-images.githubusercontent.com/47709344/197778765-ed7ac233-9d02-4bfd-8c92-a2fdcef60e59.mov
=> Feat: `SimpleFormIterator` clear item call action

packages/ra-ui-materialui/src/input/ReferenceArrayInput.tsx
=> [TypeScript] Fix `<ReferenceArrayInput>` props type marks children as required

packages/ra-core/src/form/useFormGroup.spec.tsx, packages/ra-core/src/form/useFormGroup.ts
=> Fix `useFormGroup` `isDirty` / `isTouched` state could have non-boolean values

docs/useEditContext.md
Fix a typo in the useRecordContext doc.
=> [Doc] Fix typo in `useEditContext` example

docs/SimpleFormIterator.md, packages/ra-core/src/form/FormDataConsumer.tsx
=> Fix `<FormDataConsumer>` usage with Field children

packages/ra-ui-materialui/src/input/ResettableTextField.tsx
Ripple effects had been disabled on resettable textfields, this removes the feedback during tabulation navigation.
=> Show focus on clear buttons in `ResettableTextfield`

examples/simple/package.json, packages/ra-core/package.json, packages/ra-input-rich-text/package.json, packages/ra-ui-materialui/package.json, packages/react-admin/package.json, yarn.lock
Fixes #7754
Reproduction case: https://stackblitz.com/edit/github-yb7hqu?file=package.json
1. Edit Post of id=1
Result: You get a `cannot read properties of null (reading 'map')` error.
To fix it, change `package.json` line 29 like so:
```diff
- "react-hook-form": "7.34.2",
+ "react-hook-form": "7.38.0",
```
and hard refresh the website
=> Fix ArrayInput doesn't allow null as value

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx, packages/ra-ui-materialui/src/input/NumberInput.tsx
fixes https://github.com/marmelab/react-admin/issues/8405
=> fix format does not get triggered after function change
