- packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
- packages/ra-ui-materialui/src/input/NumberInput.tsx
> Fix `<NumberInput>` parses 0 as string when used with a custom `parse` prop

- packages/ra-ui-materialui/src/list/filter/SavedQueryFilterListItem.tsx
Hi,
I get this in my url when I click on a saved filter; 
```
displayedFilters=%5Bobject%20Object%5D
```
I used the same code as in the FilterButton component that work.
Thanks!
> Fix `<SavedQueryFilterListItem>` sets wrong value for `displayedFilters` query parameter 

- packages/ra-ui-materialui/src/layout/ResourceMenuItem.spec.tsx
- packages/ra-ui-materialui/src/layout/ResourceMenuItem.tsx
Fixes https://github.com/marmelab/react-admin/issues/8469
Without the fix:
- `should not throw when used with a Function as <Admin> child` passes :heavy_check_mark: 
- `should not throw when used with only <Resource> as <Admin> child` fails :negative_squared_cross_mark: 
With the fix, both tests pass. :heavy_check_mark:
> Fix `<ResourceMenuItem>` throws an error when used with only `<Resource>` as `<Admin>` children

- packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
Fixes #8431
This commit fixes the broken referenceKey prop for the SelectColumnsButton.
> Fix broken referenceKey prop on SelectColumnsButton

- packages/ra-core/src/controller/input/useReferenceInputController.ts
- packages/ra-core/src/controller/useReference.ts
- packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx
This relates to #8191, reporting that meta isn't passed on with `ReferenceInput`.  The issue mentions `useGetList` only, however it also uses `useReference` (which in turn calls `getMany` on the data provider).
So #8192 changed `ReferenceInput` to pass meta to the `getList` call.  However still not using it with the `getMany` call which is triggered to resolve an already assigned value.
> Fix useReferenceInputController to pass meta to useReference

- packages/ra-core/src/controller/create/useCreateContext.tsx
- packages/ra-core/src/controller/edit/useEditContext.tsx
- packages/ra-core/src/controller/show/useShowContext.tsx
The Partial doesn't exist in useListContext, and is wrong. It leads to TypeScript error when accessing any property from the context without testing its existence first.
> [TypeScript] Fix return type of `useShowContext`, `useEditContext`, and `useCreateContext`

- packages/ra-core/src/core/useConfigureAdminRouterFromChildren.spec.tsx
- packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
- packages/ra-no-code/src/Admin.tsx
- packages/ra-no-code/src/ui/Layout.tsx
As a follow up of feature https://github.com/marmelab/react-admin/pull/7609 under the use case of defining an admin without resources but routes,
There seems to be a bug if additional routes are _lazily_ added to the list of child routes when user navigates in the app.
It triggers a rerender https://github.com/marmelab/react-admin/blame/master/packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx#L123 and it incorrectly redirects the user to `<Ready />` component
This pull requests adds additional checks similar to https://github.com/marmelab/react-admin/blame/master/packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx#L253
> Fix incorrect `<Ready>` page when dynamically load routes with no resources

- packages/ra-core/src/auth/useGetIdentity.spec.tsx
- packages/ra-core/src/auth/useGetIdentity.ts
Issue raised by https://github.com/marmelab/react-admin/pull/8372#discussion_r1050404542
> Fix `useGetIdentity` throws an error when no `authProvider.getIdentity` is provided

- packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
> Referenced items won't be selected when IDs type differ in `<ReferenceArrayInput>` and `<AutoCompleteInput>`

- cypress/e2e/edit.cy.js
- cypress/support/ListPage.js
- docs/DataProviderWriting.md
- docs/DataProviders.md
- docs/Reference.md
- docs/navigation.html
- docs/withLifecycleCallbacks.md
- examples/simple/src/comments/CommentList.tsx
- examples/simple/src/dataProvider.tsx
- packages/ra-core/src/dataProvider/index.ts
- packages/ra-core/src/dataProvider/withLifecycleCallbacks.spec.ts
- packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts
Developers must put their data handling / domain logic in the dataProvider, but that isn't very practical. The dataProvider quickly becomes a mess of `if(resource ==='...')` that is hard to read and to maintain. 
Allow developers to decorate an existing `dataProvider` with lifecycle callbacks.
```jsx
const dataProvider = withLifecycleCallbacks(baseDataProvider, [
{
resource: 'posts',
beforeDelete: async ({ id }) => {
// delete related comments
const { data: comments } = await baseDataProvider.getList(
'comments',
{
filter: { post_id: id },
pagination: { page: 1, perPage: 100 },
sort: { field: 'id', order: 'DESC' },
}
);
await baseDataProvider.deleteMany('comments', {
ids: comments.map(comment => comment.id),
});
return { id };
},
},
]);
```
> Add lifecycle callbacks to facilitate dataProvider customization

- docs/AuthRBAC.md
- docs/Permissions.md
- docs/Show.md
- docs/ShowTutorial.md
- docs/TabbedForm.md
- docs/TabbedShowLayout.md
- examples/demo/src/products/ProductCreate.tsx
- examples/demo/src/products/ProductEdit.tsx
- examples/simple/src/posts/PostEdit.tsx
- examples/simple/src/posts/PostShow.tsx
- examples/simple/src/users/UserCreate.tsx
- examples/simple/src/users/UserEdit.tsx
- examples/simple/src/users/UserShow.tsx
- packages/ra-ui-materialui/src/detail/Tab.tsx
- packages/ra-ui-materialui/src/detail/TabbedShowLayout.spec.tsx
- packages/ra-ui-materialui/src/detail/TabbedShowLayout.stories.tsx
- packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx
- packages/ra-ui-materialui/src/form/FormTab.spec.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.stories.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
`<Tab>` and `<FormTab>` aren't easy to remember. 
Expose the tab component as a sub component of the tabbed components, just like we do with the `<Menu.Item>`. This introduces two components:
- `<TabbedForm.Tab>`
- `<TabbedShowLayout.Tab>`
```diff
-import { Show, TabbedShowLayout, Tab, TextField } from 'react-admin';
+import { Show, TabbedShowLayout, TextField } from 'react-admin';
export const UserShow = () => {
const { permissions } = usePermissions();
return (
<Show>
<TabbedShowLayout>
-               <Tab label="user.form.summary">
+               <TabbedShowLayout.Tab label="user.form.summary">
{permissions === 'admin' && <TextField source="id" />}
-               </Tab>
+               </TabbedShowLayout.Tab>
{permissions === 'admin' &&
- …
```
> Add TabbedForm.Tab and TabbedShowLayout.Tab shortcuts

- packages/ra-ui-materialui/src/layout/Notification.tsx
Related to
- PR : https://github.com/marmelab/react-admin/pull/8519 
- Issue : https://github.com/marmelab/react-admin/issues/8510
It would be better to follow the same field name for `color` as well.
> Fix: notifications with type 'warning' should use the warning text color from the MUI palette

- packages/ra-ui-materialui/src/detail/Create.spec.tsx
- packages/ra-ui-materialui/src/detail/Create.tsx
- packages/ra-ui-materialui/src/detail/CreateView.tsx
- packages/ra-ui-materialui/src/list/List.spec.tsx
- packages/ra-ui-materialui/src/list/List.tsx
- packages/ra-ui-materialui/src/list/ListView.tsx
It's not possible to pass utility components as children of `<List>` in addition to a `<Datagrid>`. In particular, I need to pass a `<ListLiveUpdate>` component to watch for real-time changes in the list, and it needs access to the `ListContext`. 
Change the accepted type and proptype
```jsx
const PostList = () => (
<List>
<ListLiveUpdate />
<Datagrid>
// ...
</Datagrid>
</List>
);
```
Other page components (`<Edit>` and `<Show>`) already allow that.
> Add ability to pass multiple children to `<List>` and `<Create>`

- docs/Theming.md
Fix https://github.com/marmelab/react-admin/issues/8528
> [Doc] Better explain custom error page limitations

- docs/Admin.md
- docs/ContainerLayout.md
- docs/Layout.md
> [Doc] Fix `<ContainerLayout>` is hard to find.

- packages/ra-ui-materialui/src/list/ListGuesser.stories.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.tsx
- packages/ra-ui-materialui/src/list/listFieldTypes.tsx
> Fix `ListGuesser` links to Edit view even though there is only a ShowView

- docs/TabbedForm.md
- docs/TabbedShowLayout.md
- examples/demo/src/orders/OrderList.tsx
- examples/demo/src/products/ProductEdit.tsx
- examples/simple/src/posts/PostEdit.tsx
- examples/simple/src/posts/PostShow.tsx
- packages/ra-ui-materialui/src/detail/Tab.tsx
- packages/ra-ui-materialui/src/detail/TabbedShowLayout.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx
- packages/ra-ui-materialui/src/form/FormTab.tsx
- packages/ra-ui-materialui/src/form/FormTabHeader.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.stories.tsx
```jsx
const PostEdit = () => (
<Edit>
<TabbedForm>
<TabbedForm.Tab label="post.form.summary">
{/*...*/}
</TabbedForm.Tab>
<TabbedForm.Tab label="post.form.body">
{/*...*/}
</TabbedForm.Tab>
<TabbedForm.Tab label="post.form.miscellaneous">
{/*...*/}
</TabbedForm.Tab>
<TabbedForm.Tab
label="post.form.comments"
count={<ReferenceManyCount reference="comments" target="post_id" />}
>
{/*...*/}
</TabbedForm.Tab>
</TabbedForm>
</Edit>
);
```
> Add ability to pass a tab count in `<TabbedForm.Tab>` and `<TabbedShowLayout.Tab>`

- docs/ReferenceArrayInput.md
- docs/ReferenceInput.md
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fixes https://github.com/marmelab/react-admin/issues/8554
> Fix `AutocompleteInput` with `create` does not support nested `optionText` and fix `enableGetChoices` examples in doc

- docs/DataProviders.md
When you try to apply the instructions of [this section of the docs](https://marmelab.com/react-admin/DataProviders.html#adding-custom-headers) with TypeScript, after typing `options` to the provided `Options` type, you get the following error:
This PR fixes the example to avoid the error:
> [Doc] Make custom headers example compatible with TS

- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
`DatagridRow`'s `rowClick` property may be provided with a function, that may return a string (to trigger navigation) or `false` (in order to skip navigation).  At least the code would allow to do that, see https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx#L113
However typing restricts this (via `RowClickFunction`) to just support string return types (or promises there of).
This PR changes the type to allow `false` to be returned as well (both directly or with promise).
----
Please note that there are further inconsistencies with typing of `rowClick` on `Datagrid` itself and `DatagridBody`, which both disallow `rowClick={false}` (opposed to `DatagridRow`). Furthermore `DatagridRow.propTypes.rowClick` does not allow `false` …
> Fix RowClickFunction type to accept false.

- docs/DataProviders.md
- Reverts #8557 because `options.headers['X-Custom-Header'] = 'foobar'` and `options.headers.set('X-Custom-Header', 'foobar')` are **not** equivalent (the first expression doesn't set the header)
- Adds a dedicated TS example
> [Doc] Revert custom headers example (#8557) and add another for TS

- packages/ra-core/src/dataProvider/useCreate.ts
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-core/src/dataProvider/useDeleteMany.ts
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdateMany.ts
- packages/ra-core/src/store/useStore.ts
- packages/ra-core/src/util/index.ts
- packages/ra-core/src/util/useEvent.spec.tsx
- packages/ra-core/src/util/useEvent.ts
> Memoize mutation callbacks

- docs/AutocompleteArrayInput.md
Adds an additional tip that may save some future headaches, after having spent a bit of time yesterday trying to troubleshoot this myself. 
Source: #7792
> [Doc] - Add `disableCloseOnSelect` tip to AutoCompleteArrayInput

- docs/Demos.md
> [Doc] Add HelpDesk demo

- packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
- packages/ra-core/src/dataProvider/useGetManyAggregate.ts
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Fixes #8595
It actually has nothing to do with `parse` or `format`.
> Fix AutocompleteInput flickers inside ReferenceInput

- packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
- packages/ra-ui-materialui/src/input/NumberInput.tsx
Fix https://github.com/marmelab/react-admin/issues/8593
> Fix NumberInput should support entering a decimal number with a transitory invalid value

- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
> Fix AutocompleteArrayInput when value is not an array

- docs/CustomRoutes.md
- docs/Resource.md
- packages/react-admin/src/Resource.stories.tsx
React-admin doesn't support nested resources, but you can use the `<Resource children>` prop to render a custom component for a given sub-route. For instance, to display a list of posts for a given user:
```jsx
import { Admin, Resource } from 'react-admin';
import { Route } from 'react-router-dom';
export const App = () => (
<Admin dataProvider={dataProvider}>
<Resource name="users" list={UserList} edit={UserDetail}>
<Route path=":id/posts" element={<PostList />} />
<Route path=":id/posts/:postId" element={<PostDetail />} />
</Resource>
</Admin>
);
```
This setup creates four routes:
- `/users` renders the `<UserList>` element
- `/users/:id` renders the `<UserDetail>` element
- `/users/:id/posts` renders the `<PostList>` element
- `/users/:id/posts/:postId` renders the `<PostDetail>` …
> [Doc] Fix nested routes explanation and add more examples

- packages/ra-ui-materialui/src/button/CreateButton.tsx
- packages/ra-ui-materialui/src/button/EditButton.tsx
> Add classnames to Create and Edit buttons

- packages/ra-ui-materialui/src/input/FileInput.tsx
The label of the `<FileField>` is darker than the other input labels.
> Fix `<FileInput>` label color

- docs/RichTextField.md
- packages/ra-ui-materialui/package.json
- packages/ra-ui-materialui/src/field/RichTextField.spec.tsx
- packages/ra-ui-materialui/src/field/RichTextField.stories.tsx
- packages/ra-ui-materialui/src/field/RichTextField.tsx
- yarn.lock
`<RichTextField>` leverages the `dangerouslySetInnerHTML` attribute, expecting the value to be already sanitized server-side. 
If it is not, a malicious user can execute an XSS attack by injecting malicious data. 
Proof-of-concept:
```jsx
<RecordContextProvider
value={{
id: 1,
body: `
<p>
<strong>War and Peace</strong> is a novel by the Russian author
<a href="https://en.wikipedia.org/wiki/Leo_Tolstoy" onclick="document.getElementById('stolendata').value='credentials';">Leo Tolstoy</a>,
published serially, then in its entirety in 1869.
</p>
<p onmouseover="document.getElementById('stolendata').value='credentials';">
It is regarded as one of Tolstoy's finest literary achievements and remains a classic of world literature.
</p>
`,
}}
>
<RichTextField source="body" />
<hr />
<div>
<h4>Stolen …
```
> Fix `<RichTextField>` XSS vulnerability

- docs/Buttons.md
- packages/ra-ui-materialui/src/button/BulkExportButton.spec.tsx
- packages/ra-ui-materialui/src/button/BulkExportButton.tsx
- packages/ra-ui-materialui/src/button/ExportButton.spec.tsx
- packages/ra-ui-materialui/src/button/ExportButton.tsx
Fix https://github.com/marmelab/react-admin/issues/8635
> enable passing meta to ExportButton/BulkExportButton dataProvider #8635

- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
- CheckboxGroupInput helperText has a left margin that shows a wrong alignment with the label
- When required but not touched, the error message appears in grey instead of red
Supersedes #8627
> Fix CheckboxGroupInput helperText placement and color

- packages/ra-ui-materialui/src/input/NumberInput.stories.tsx
- packages/ra-ui-materialui/src/input/sanitizeInputRestProps.ts
> Fix shouldUnregister prop used in an Input logs a DOM warning

- docs/Tutorial.md
- examples/tutorial/src/authProvider.ts
Fix #8606
1. Moved the diff marker to the "posts" line, as expected.
2. Minor spell-checks.
3. Updated sample TypeScript in Tutorial to compile with `typescript@4.9.4`
> [Doc] Tutorial: Fix typos, snippets and file extensions

- examples/demo/src/layout/themes.ts
With the 'rounded' style of the MUI components (especially Cards) in the demo, having a bottom gutter on the latest row of the Datagrids is ugly.
Similar to [what they did in their own demo](https://mui.com/material-ui/react-table/#basic-table), this PR changes the style of the MuiTableRow to disable bottom border on the last row.
Before
After
> [Demo] Fix Datagrid style: remove last row gutter

- packages/ra-ui-materialui/src/layout/Notification.tsx
Fix #8664
Didn't add a test cause I'm not sure it would make sense to have a test ensuring MUI does not raise any warning (as it's pretty specific). But I can add one if you guys think otherwise.
The fix can be tested with the `Basic` story of the `Notification` storybook.
> Fix `Notification` raises a MUI warning when `message` is a string

- packages/ra-core/src/controller/saveContext/SaveContext.ts
- packages/ra-core/src/types.ts
Fix the `onError` type name to be Pascal cased like the others
> Fix onError type

- docs/Datagrid.md
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
The TS definition didn't accept `false` as a vaild value.
The documentation did not mention you can pass `false`.
> Fix `<Datagrid>` `rowClick` type and documentation

- packages/ra-ui-materialui/src/preferences/FieldToggle.tsx
Fix #8672
- [Issue description in stackoverflow](https://stackoverflow.com/questions/11656061/why-is-event-clientx-incorrectly-showing-as-0-in-firefox-for-dragend-event)
- [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=505521#c80)
- [Implemented solution](https://stackoverflow.com/a/24137885/3975522)
> Fix `DatagridConfigurable` column ordering feature does not work in Firefox

- docs/Tutorial.md
- docs/Vite.md
- Adding `window.global = window` to the Vite example allows to fix errors with some libs, e.g. react-floater, that would throw errors such as `Uncaught ReferenceError: global is not defined`
- Offering to install the Roboto font locally can help with local legislation compliance, such as the GDPR in Europe
> [Doc] Add `global` definition to the Vite example, and offer to install the Roboto font locally

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
**Issue**
`AutocompleteInput` uses `getMany` to fetch the records matching the already selected choices, and `getList` to fetch the other available choices.
If both methods do not render exactly the same record shape (e.g. if `getMany` records have extra fields compared to `getList` records), then when fetching for additional choices (e.g. while filtering), `AutocompleteInput` gets confused because it thinks the selected choice has changed, and ends up resetting the filterValue.
**Solution**
Instead of comparing the full records, only compare their `id` (or the field chosen as `optionValue`)
> Fix `AutocompleteInput` when record has a different shape between `getList` and  `getMany`

- packages/ra-core/src/export/downloadCSV.ts
Because `downloadCSV` function is exported by react-admin, it is good to make it typed rather than `any`.
> Type downloadCSV function

- docs/Tutorial.md
- docs/Vite.md
- examples/simple/index.html
> Fix documentation about Vite

- packages/ra-ui-materialui/src/field/UrlField.tsx
Fixes https://github.com/marmelab/react-admin/issues/8707
> Fix `<UrlField>` click is cancelled by `Datagrid`'s row click

- packages/ra-ui-materialui/src/button/SkipNavigationButton.tsx
- packages/ra-ui-materialui/src/input/InputHelperText.tsx
- packages/ra-ui-materialui/src/layout/ResourceMenuItem.tsx
Some components were translating labels twice. Besides the validation messages were translated twice as well. Fixing this requires a potential breaking change: when using the `InputHelperText` directly, the error message isn't translated anymore unless it's an object with a `message` property. I believe this is a very rare usage if it even exists.
FIxes #8662
> Avoid double translations

- packages/ra-core/src/dataProvider/useGetManyAggregate.ts
- packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceInput.stories.tsx
Fixes #8684 and supersedes #8717
> Fix `ReferenceInput` throws an error when referencing the same resource as `Edit` and the reference is undefined

- docs/ReferenceManyField.md
Fixes https://github.com/marmelab/react-admin/issues/8704
> [Doc] Better document `ReferenceManyField`'s `source` prop

- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
fixes #8515 
This PR fixes 2 issues with `SelectArrayInput`:
- Removes hardcoded value for `size` prop
- Fixes label display issue when variant is set to `outlined`
`size` prop on `SelectArrayInput` was hardcoded to `small` which was preventing modifying size of the input through MUI's theming system. 
Additionally, when setting `SelectArrayInput` variant to `outlined` label of the input wasn't showing correctly. This is fixed by adding `input` prop with `OutlinedInput` component when variant is set to `outlined`.
Before:
After:
> Modifiable size prop for SelectArrayInput

- docs/AuthProviderList.md
- docs/DataProviderList.md
Hi,
I write a package for a an AuthProvider and a DataProvider for SurrealDB.
> [Doc] Add AuthProvider and DataProvider for SurrealDB.

- docs/useRecordContext.md
> [Doc] Fix useRecordContext explanation for forms

- examples/tutorial/sandbox.config.json
Without this file, codesandbox uses Node 10 which is incompatible with the tools we use.
> Add a codesandbox config for the tutorial

- packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx
Fixes #8750 
Tested on my local environment, and nothing has changed visually, while the link works properly now.
> Fix `ReferenceManyCount` rendering link incorrectly

- packages/ra-core/src/form/getSimpleValidationResolver.spec.ts
- packages/ra-core/src/form/getSimpleValidationResolver.ts
- packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
- packages/ra-ui-materialui/src/form/SimpleForm.stories.tsx
Fixes https://github.com/marmelab/react-admin/issues/8744
> Fix form `validate` function no longer applies translation

- docs/AppBar.md
> [Doc] Fix `<AppBar>` example

- packages/ra-core/src/types.ts
Update a type definition to make `UpdateParams` is consistent with the definition in `GetOne` and `GetMany`. Similar to https://github.com/marmelab/react-admin/pull/8208
Because `UpdateParams` includes `previousData: T`. So I think we shall have `T extends RaRecord` to fit the type of `previousData`.
> [TypeScript] Fix UpdateParams id type doesn't use generic type

- packages/ra-core/src/controller/input/useReferenceInputController.spec.tsx
- packages/ra-core/src/controller/input/useReferenceInputController.ts
Fixes https://github.com/marmelab/react-admin/issues/8182
> Fix MUI Autocomplete warning on deselection with ReferenceInput

- packages/ra-core/src/form/FormDataConsumer.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
This is a copy of this one: https://github.com/marmelab/react-admin/pull/8787
The `SimpleFormIterator` actually is defaulting every input inside a `FormDataConsumer` to an empty string. So if I have some arrays, objects, or numbers inside, they default to the empty strings when I add new elements to the array.
I propose to make the default equal to null instead. I know this is a kind of breaking change but I think is more consistent, in case we don't have enough information to determine the right return type null should be better.
This should also solve this issue: https://github.com/marmelab/react-admin/issues/8785 because it will default to null when no default value will be provided.
Let me know what you think about it!
> [SimpleFormIterator] default to null instead of empty string

- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> Fix FilterForm infinite loop when used in a ReferenceManyField

- packages/ra-ui-materialui/src/layout/Layout.tsx
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
Its a fix of the configuration introduced in 48e4a91f4fc85a68e7b4d9ce23fc4db387b1c96f.
I am not sure it was intended, but it make more sense to me.
> fix: layout padding inconsistency on low resolution screens

- packages/ra-core/src/controller/input/useReferenceArrayInputController.spec.tsx
- packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
> Fix `useReferenceArrayInputController` does not pass meta to `getMany`

- packages/ra-core/src/routing/useCreatePath.spec.tsx
- packages/ra-core/src/routing/useCreatePath.ts
- packages/ra-core/src/routing/useRedirect.spec.tsx
- packages/ra-core/src/routing/useRedirect.ts
Provide hints for shortcuts values but still allow to provide a string, false or a function:
> Better types for useRedirect and useCreatePath

- packages/ra-core/src/auth/addRefreshAuthToAuthProvider.spec.ts
- packages/ra-core/src/auth/addRefreshAuthToAuthProvider.ts
> Fix addRefreshAuthToAuthProvider should not try to call getIdentity if it does not exist on the original AuthProvider

- packages/ra-core/src/core/ResourceDefinitionContext.tsx
- packages/ra-core/src/core/useResourceDefinition.ts
- packages/ra-core/src/core/useResourceDefinitions.ts
- packages/ra-core/src/form/useInput.ts
- packages/ra-core/src/types.ts
Just a couple of generics that should be there.
> Add some utility generics for better typings

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
`<Datagrid>` does not apply `className` to its root element, but rather to its nested `Table` element.
This creates a discrepancy between styles applied via `sx` and styles applied via `styled`.
This is among others visible with the (EE) `<EditableDatagrid>` component.
`sx` and `className` should be applied to the same component, i.e. `<DatagridRoot>`.
:warning: :warning: :warning: **Breaking change** :warning: :warning: :warning: 
This change is technically a BC. But it should be really minor as it would affect only people that use `styled` to apply styles to the `Datagrid` component. People applying styles via `sx` shouldn't be affected.
Before
After
> [Minor BC] Fix `<Datagrid>` does not apply `className` to its root element

- docs/TranslationLocales.md
`chen4w/ra-language-chinese` unable to support the latest ReactAdmin version.
The new version of RA has added some fields.
`haxqer/ra-language-chinese` support the latest ReactAdmin version.
> add chinese(zh) locale

- packages/ra-input-rich-text/src/RichTextInput.tsx
Hi !
`editorOptions.editorProps` is currently ignored in RichTextInput. This makes it impossible to do things like this (customizing ProseMirror className for example) :
```jsx
<RichTextInput
editorOptions={{
extensions: [
// ...
],
// https://tiptap.dev/api/editor#editor-props
editorProps: {
attributes: {
class: 'my-custom-css-class',
},
},
}}
// ...
/>
```
> [RFR] Allow `editorProps` attribute in RichTextInput `editorOptions` props

- packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
> Fix ReferenceOneField shows wrong sort order when used in a Datagrid

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- docs/CheckboxGroupInput.md
- docs/RadioButtonGroupInput.md
- docs/SelectArrayInput.md
- docs/SelectInput.md
- packages/ra-core/src/dataProvider/useGetList.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/LoadingInput.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
- packages/ra-ui-materialui/src/layout/LinearProgress.tsx
For `<SelectInput>` and other selection inputs, we document fetching related records by advertising the solution ("using in `<ReferenceInput>` rather than the problem ("Fetching choices"). 
As a consequence, newcomers struggle to understand that `ReferenceInput` thing. 
Write the doc the other way around.
> [Doc] Improve usage examples for `<ReferenceInput>` and `<ReferenceArrayInput>`

- docs/Form.md
- docs/Inputs.md
- docs/SimpleForm.md
- docs/TabbedForm.md
- docs/Upgrade.md
- docs/useInput.md
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/FormDataConsumer.tsx
- packages/ra-core/src/form/useAugmentedForm.ts
- packages/ra-core/src/form/useFormValues.ts
Fix https://github.com/marmelab/react-admin/issues/8799
> Fix Form should only trigger field validation on submit if not told otherwise

- docs/EditGuesser.md
Fixing a small typo in the docs.
> Fix typo in EditGuesser.md

- packages/ra-ui-materialui/src/field/DateField.spec.tsx
- packages/ra-ui-materialui/src/field/DateField.tsx
Clarifies the types for `DateField`. Both `locales` and `options` are expected to be used in `.toLocaleDateString`, which has more specific (and built-in/native) types we can leverage. Setting to more explicit types provides useful auto-correct and documentation.
> Clarify DateField types

- packages/ra-ui-materialui/src/button/Button.stories.tsx
- packages/ra-ui-materialui/src/button/Button.tsx
- packages/ra-ui-materialui/src/button/CreateButton.tsx
> Fix `<Button>` accepts user defined MUI color palettes as `color` property

- packages/ra-ui-materialui/src/field/ImageField.tsx
If you have many menu items, navigating between them can produce temporary invalid records with empty sourceValue, in this case sometimes we received this error **valid value for prop `sx` on <div> tag** related to the usage of `ImageField` with specification of `sx` prop. 
To avoid this we replaced standard `div` with `Typography` that can accept sx without problems.
> fix: valid value for prop `sx` on <div> tag using ImageField

- packages/ra-ui-materialui/src/button/LocalesMenuButton.spec.tsx
- packages/ra-ui-materialui/src/layout/Title.tsx
Fix https://github.com/marmelab/react-admin/issues/7745
> Fix AppBar Title disappears on locale change

- packages/ra-data-graphql/src/buildApolloClient.ts
We need to pass credentials and headers to HttpLink to correctly build a fetch instance
CoAuthored with @dgopsq
> fix: credentials and headers belong to HttpLink

- docs/FileInput.md
- docs/ImageInput.md
- packages/ra-ui-materialui/src/input/FileInput.stories.tsx
- packages/ra-ui-materialui/src/input/FileInput.tsx
- packages/ra-ui-materialui/src/input/FileInputPreview.tsx
- packages/ra-ui-materialui/src/input/ImageInput.stories.tsx
> make the remove icon of the file preview configurable and default to RemoveCircle 

- packages/ra-core/src/auth/useHandleAuthCallback.spec.tsx
- packages/ra-core/src/auth/useHandleAuthCallback.ts
The default `AuthCallback` handles the error by showing a message.
The previous `onError` was preventing that and triggered an infinite loop
> Fix infinite redirection loop in useHandleCallback

- docs/CustomRoutes.md
> [Doc] Fix wrong parameter `to` for `Menu.ResourceItem`

- packages/ra-core/src/controller/create/useCreateController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx
Fix https://github.com/marmelab/react-admin/issues/8819
Supersedes https://github.com/marmelab/react-admin/pull/8859
The idea is that changing the way the save side-effects should be called is a BC.
Instead, this PR aims at fixing the `useWarnWhenUnsavedChanges` hook.
The fix is working well (tested manually and with Jest).
However it does seem a bit hacky, so let's discuss!
> Fix custom redirect in pessimistic `Edit` or `Create` when using `warnWhenUnsavedChanges` (new approach)

- docs/Datagrid.md
> Update Datagrid's `isRowSelectable` description and examples

- docs/RichTextField.md
- packages/ra-ui-materialui/package.json
- packages/ra-ui-materialui/src/field/RichTextField.stories.tsx
- packages/ra-ui-materialui/src/field/RichTextField.tsx
- yarn.lock
Also document how to open all links in a new tab in a secure way, by [adding a hook to DOMPurify](https://github.com/cure53/DOMPurify/issues/317#issuecomment-698800327).
> Add `purifyOptions` prop to `<RichTextField>`

- packages/ra-ui-materialui/src/form/SimpleForm.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.tsx
Necessary since https://github.com/marmelab/react-admin/pull/8911 which allows the new `resetOptions` prop
> Fix `SimpleForm` and `TabbedForm` do not sanitize the `resetOptions` prop

- packages/ra-core/src/controller/create/useCreateController.spec.tsx
- packages/ra-core/src/controller/create/useCreateController.ts
- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
This is used, among other, by ra-editable-datagrid's `<RowForm>` to pass the `meta` param from the `mutationOptions`
> Fix create and edit controller's `save` callback should use calltime `meta` param

- docs/Tutorial.md
- docs/css/prism.css
Now that create-react-admin is the default installation mode, the "Getting Started" tutorial need a few adjustments.
> [Doc] Fix tutorial with create-react-admin

- packages/ra-core/src/notification/NotificationContext.ts
- packages/ra-core/src/notification/NotificationContextProvider.tsx
In our use case, we have a customized notification center.
We would like to let users acknowledge some of the notifications, so that would require us to expose the setNotifications method in order to rewrite some of the values stored in the notification context
> Expose setNotifications methods in notification contexts

- packages/ra-language-french/package.json
Some tools might use it even when not needed. Besides, that's the only misconfigured package
> Fix ra-language-french package.json to avoid including tsconfig

- packages/ra-core/src/dataProvider/useGetList.spec.tsx
- packages/ra-core/src/dataProvider/useGetList.ts
Fix https://github.com/marmelab/react-admin/issues/8940
> Fix `useGetList` default `onSuccess` throws when the query is disabled

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
**Problem**
When provided with a `matchSuggestion` and used in a `<ReferenceInput>`, `<AutocompleteInput>` does actually do the filtering twice: once immediately client-side, and then once server-side.
The client-side filtering does not make much sense because it's done only on a subset of the data, and besides it leads to UI flickering when the server-side results arrive.
**Solution**
Actually this is a bug, we shouldn't call `getSuggestions()` when used inside a reference, at all.
We already do this to disable MUI's Autocomplete default filtering fn, so I just extended this behavior to `getSuggestions()`.
I also had to adapt the error message warning the user that they can't use `optionText` without `matchSuggestion`, to only trigger when **not** used in a reference. Indeed, in a …
> Fix `<AutocompleteInput>` should not use `matchSuggestion` when in a `<ReferenceInput>`

- packages/ra-core/src/dataProvider/validateResponseFormat.ts
The error displayed when `total` and `pageInfo` properties are missing in the response does not accurately say correct solution. This PR fixes that
> Fix `getList` and `getManyReference` error to take partial pagination into account.

- packages/ra-ui-materialui/src/field/FunctionField.stories.tsx
- packages/ra-ui-materialui/src/field/FunctionField.tsx
Fixes https://github.com/marmelab/react-admin/issues/8960
I originally intended to fix the types properly, by setting the type to be `Record<string, any>` in case `RecordType` was not provided, but couldn't find a way to do so. :frowning: 
So I had to resort to using `any` as the default type.
Nevertheless, autocompletion works when setting the type either to `<FunctionField>` or to `render`'s `record` param, and TS no longer throws an error. :slightly_smiling_face:
> [TypeScript] Fix regression in type of `<FunctionField>` `render`

- docs/Inputs.md
- docs/SimpleFormIterator.md
Fix https://github.com/marmelab/react-admin/issues/8958
> [Doc] Better explain the type of `getSource` and `scopedFormData` in `<FormDataConsumer>`

- packages/ra-ui-materialui/src/Link.tsx
We use a custom `<Link>` tag, which combines MUI and react-router Links. 
This tag uses a custom style to disable the underline. 
When users use the `underline` prop to force the underline, this fails. 
Use the `underline` prop instead of custom styles
> Update `<Link>` to honor the `underline` prop

- docs/Confirm.md
> [Doc] Fix Confirm prop table overflows

- docs/AccordionForm.md
- docs/ArrayInput.md
- docs/Features.md
- docs/Form.md
- docs/Inputs.md
- docs/LongForm.md
- docs/SimpleForm.md
- docs/SimpleFormIterator.md
- docs/TabbedForm.md
- docs/Upgrade.md
- docs/Validation.md
- docs/WizardForm.md
- docs/useInput.md
- docs/useRecordContext.md
- packages/ra-core/src/form/Form.tsx
- packages/ra-core/src/form/useFormValues.ts
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInputContext.ts
- packages/ra-ui-materialui/src/input/ArrayInput/useArrayInput.ts
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Dunno if it's temporary (and intentional) or not, but the RHF doc is now under www.react-hook-form.com instead of react-hook-form.com, so this PR changes the links accordingly
EDIT
According to https://github.com/react-hook-form/documentation/issues/971, the path has to be changed to `/docs`, so this is what this PR does.
> [Doc] Fix links to react-hook-form's doc

- examples/demo/src/orders/NbItemsField.tsx
- packages/ra-core/src/controller/record/WithRecord.tsx
- packages/ra-core/src/types.ts
- packages/ra-ui-materialui/src/field/FunctionField.tsx
**Problem**
https://github.com/marmelab/react-admin/pull/8963 introduced a change to `<WithRecord>`, which allowed the `render` prop return a `ReactNode` instead of a `ReactElement`.
But since `<WithRecord>` currently returns the result of the `render` function without wrapping it in JSX first, we get the following TS error:
**Solution**
Wrap the result of the `render` function in a React Fragment.
Also, I removed the the `RenderRecordFunction` type because to me `FunctionField` and `WithRecord` do not share the same `render` function signature.
> Fix `<WithRecord>` `render` prop type

- packages/ra-ui-materialui/src/button/ToggleThemeButton.tsx
Currently, the JSDoc for the deprecated `lightTheme` prop appear as `Set the lightTheme in the component instead.`, which does not make much sense.
This PR fixes it to be `Set the lightTheme in the <Admin> component instead.`
Same for `darkTheme` of course.
> [JSDoc] Fix ToggleThemeButton deprecated props JSDoc

- docs/AppBar.md
- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- docs/CustomRoutes.md
- docs/Layout.md
- docs/RichTextField.md
- docs/SelectInput.md
- docs/Theming.md
- docs/Title.md
- docs/Upgrade.md
- docs/useStore.md
Updated links that redirect to old React documentation (legacy.reactjs.org) to new documentation (react.dev)
> Doc: update React links

- packages/create-react-admin/templates/local-auth-provider/authProvider.ts
- packages/ra-core/src/auth/usePermissions.ts
- packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
When creating a React Admin App with `create-react-admin`, and choosing to add an `authProvider`, the provider is created with this method: `getPermissions: () => Promise.reject("Unknown method"),`.
This leads to an error log in browser devtools console (e.g: `Unknown method`), even the app doesn't need permission anywhere. 
Reproduce:
- Create a React Admin App with [`create-react-admin`](https://marmelab.com/react-admin/CreateReactAdmin.html)
- Run the app, go on the app with a browser and open browser devtools
- Wait some second and see the error throws in the console
~~Fix: Call `authProvider.getPermissions` only when a [child function exist](https://marmelab.com/react-admin/Permissions.html#restricting-access-to-resources-or-views) and only when the hook `usePermissions` is used in …
> Fix: query permissions at startup only when a child function exist

- docs/NextJs.md
- packages/react-admin/src/Admin.tsx
Reverts marmelab/react-admin#8990 as it doesn't work
> Revert "Fix `<Admin>` fails when used in Next.js server components"

- docs/NextJs.md
> Fix broken link in Next installation tutorial

- docs/Remix.md
> Add documentation for Remix v2routing conventions

- docs/_layouts/default.html
- docs/css/prism.css
- docs/css/style-v17.css
- docs/js/ra-doc-exec.js
- docs/useDataProvider.md
Done client side and only when needed.
I compared locally with the previous docs and didn't notice any difference even with CPU throttling x6 on slow 3G
- Open AccordionForm.md
- Click on the AccordionForm.Panel section 
- Scroll down
- The first snippet is bi-lingual
> Automatically convert TS examples to JS

- docs/NextJs.md
https://github.com/marmelab/react-admin/pull/9014 is not enough to fix the Next.js integration. Let's keep the `"use client"` directive in the doc for now.
> Partially revert "Fix Next.js integration"

- docs/List.md
- docs/useListController.md
- packages/ra-core/src/controller/list/useInfiniteListController.ts
- packages/ra-core/src/controller/list/useListController.storeKey.spec.tsx
- packages/ra-core/src/controller/list/useListController.storeKey.stories.tsx
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/list/useListParams.ts
- packages/ra-ui-materialui/src/list/List.stories.tsx
For one-off lists (e.g. in dashboards), `<ListBase>` does the fetching and puts the data in a  `<ListContext>`, so it’s fine.
But as it uses the store by default, a list for a given resource will be affected by the actions of the user in other lists of the same resource.
It’s possible to specify a different `storeKey` to avoid that, but it’s silly to have to define a store key when what I want is to disable the use of the store altogether.
It’s also possible to use `disableSyncWithLocation`, but the name of that prop isn’t clearly related to the store.
Allow to set `storeKey` to `false` to disable the store altogether
> Allow disabling store persistence of the list parameters

- packages/ra-core/src/controller/edit/EditBase.spec.tsx
- packages/ra-core/src/form/validate.spec.ts
- packages/ra-data-graphql-simple/src/getResponseParser.ts
- packages/ra-ui-materialui/src/auth/Logout.tsx
- packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
- packages/ra-ui-materialui/src/detail/CreateActions.tsx
- packages/ra-ui-materialui/src/detail/CreateView.tsx
- packages/ra-ui-materialui/src/detail/EditActions.tsx
- packages/ra-ui-materialui/src/detail/EditView.tsx
- packages/ra-ui-materialui/src/detail/Show.stories.tsx
- packages/ra-ui-materialui/src/detail/ShowView.tsx
- packages/ra-ui-materialui/src/detail/editFieldTypes.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Reduce linter warnings from 150 to 40
> Fix linter warnings

- docs/useGetTree.md
Fix a typo in sentence `This package recomments do add`
> [DOC] - Fix typo on  useGetTree documentation

- docs/TranslationLocales.md
The packages previously provided are either no longer maintained or not obtainable anymore. We have created a package providing both formal ("Sie") as well as informal ("du") translation, so that the user can choose what fits best. We are committed to keep the package up-to-date.
> [RFR] Add maintained ra-language-german

- packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
https://github.com/marmelab/react-admin/issues/9029
1. Extended BulkUpdateWithUndoButtonProps and BulkUpdateWithConfirmButtonProps to inlude mutation options
2. Passing the props to the underlying useUpdateMany calls
> Mutation options on bulk update buttons

- docs/useList.md
In the example of useList, with page: 1 in option, 
```js
const { total, data } = useList({
data: [
{ id: 1, name: 'Arnold' },
{ id: 2, name: 'Sylvester' },
{ id: 3, name: 'Jean-Claude' },
],
perPage: 2,
page: 1,
});
```
the data result will be
```js
[
{ id: 1, name: 'Arnold' },
{ id: 2, name: 'Sylvester' },
]
```
and not 
```js
[
{ id: 3, name: 'Jean-Claude' },
]
```
> [Doc] Correct an example in useList doc, with page option

- docs/AuthRBAC.md
On first reading, I didn't see that `{ action: 'write', resource: 'products.tab.description' },` allowed to display corresponding tab with the name `description`. Same for panel, section and step.
I added some comments to make things clearer and fix a typo
> [Doc] Improve description of rbac tab, panel, section, and step

- docs/TabbedForm.md
- Fix a little typo in _tweak th UX_: missing e to the
- Fix another little typo: appreciate instead of appreviate
> [Doc] Fix a typo:  missing e to the

- docs/TabbedShowLayout.md
`<TabbedShowLayout>` reads `RecordContext` by default and when passing `record` props
> [Doc] - Correct Controlled Mode explanation in TabbedShowLayout

- examples/crm/package.json
- examples/crm/vite.config.ts
- examples/demo/package.json
- examples/demo/vite.config.ts
- yarn.lock
The `yarn analyze` command fails on the CRM and ecommerce demos, as some source maps can't be interpreted since the upgrade to Vite
Use the rollup plugin for source map visualization, and open the dataviz on build.
> Fix demos don't allow to visualize source maps

- packages/ra-ui-materialui/src/input/BooleanInput.tsx
Cast `field.value` passed to `checked` prop in boolean, to avoid `checked` prop to be `<empty string>` in `<BooleanInput>`
Fix #9042
> Fix: string value supplied to BooleanInput checked prop

- docs/Actions.md
- docs/Admin.md
- docs/Create.md
- docs/Edit.md
- docs/PredictiveTextInput.md
- docs/ReferenceArrayInput.md
- docs/ReferenceField.md
- docs/ReferenceInput.md
- docs/ReferenceOneField.md
- docs/Upgrade.md
- docs/useGetIdentity.md
- docs/useGetOne.md
- docs/useInfiniteGetList.md
- docs/usePublish.md
Replaced dead links to React Query documentation V3, with working links to React Query documentation V3
> [Doc] fix links to TanStack Query V3 doc

- docs/Inputs.md
Problem :
To me, the sentence `Defaults to the humanized source when omitted.` when talking about input label is not clear.
Solution : 
Change the sentence
> [Doc] clearer explanation for input label

- packages/ra-core/src/form/useInput.spec.tsx
- packages/ra-core/src/form/useInput.ts
I'm updating a project from ra-v3 to ra-v4 where the value of change inputs is taken from the Form state within the onChange / onBlur event handler (instead of its `e.target.value` argument), and it doesn't have the updated value.
I found out that :
In react-admin **v3** inputs run custom event handlers **after** react-final-form ones.
In react-admin **v4** inputs run custom event handlers **before** react-hook-form ones.
So, changing this order of execution to match ra-v3 allows `useFormContext().getValues()` to have the latest value inside the custom event handlers.
Supersedes #8903
> Fix custom input's onChange handlers should have access to updated context value

- docs/Tutorial.md
- docs/js/ra-doc-exec.js
- examples/tutorial/src/main.tsx
- packages/create-react-admin/templates/common/src/index.tsx
Update `js` and `jsx` snippets to `ts` and `tsx` in __Getting Started / Tutorial__
> [Doc] Update Tutorial to use TypeScript by default

- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
Fix https://github.com/marmelab/react-admin/issues/9089
Bug introduced by https://github.com/marmelab/react-admin/pull/8090, which caused a conflict between the default values reset logic for scalar arrays and array input with a FormDataConsumer.
> Fix `SimpleFormIterator` with `FormDataConsumer` should not re-apply default values

- landing-page/index.html
Move https://github.com/marmelab/react-admin-landing-pages/pull/1 to the right place. Same as #9087.
> [Doc] Improve reference to Material UI

- examples/crm/src/deals/DealColumn.tsx
- examples/crm/src/deals/DealListContent.tsx
- examples/crm/src/deals/stages.ts
Changes inspired by the work on https://github.com/marmelab/ra-example-kanban and the (upcoming) related blog post.
> [Demo] Improve CRM Demo Kanban code

- packages/ra-core/src/dataProvider/useGetManyReference.ts
Applies same fix as https://github.com/marmelab/react-admin/pull/8941 to `useGetManyReference`.
Pointed out by https://github.com/marmelab/react-admin/issues/8940#issuecomment-1641805782
> Fix `useGetManyReference` default `onSuccess` throws when the query is disabled

- docs/AuthProviderWriting.md
- packages/ra-core/src/auth/usePermissions.spec.tsx
- packages/ra-core/src/auth/usePermissions.ts
When declaring resources at runtime, we don't check for authorization related errors and as no resources were returned, RA displays an empty page.
When `getPermissions` rejects, pass the error to `checkError` to allow redirecting to the login page
> Call checkError when getPermissions fails

- packages/ra-core/src/form/useUnique.spec.tsx
- packages/ra-core/src/form/useUnique.stories.tsx
- packages/ra-core/src/form/useUnique.ts
> Fix useUnique should allow value if the only matching record is the current one

- docs/Datagrid.md
- docs/Fields.md
- docs/FilterList.md
- docs/List.md
- docs/ListBase.md
- docs/Reference.md
- docs/ReferenceField.md
- docs/ReferenceOneField.md
- docs/SimpleShowLayout.md
- docs/useListContext.md
- docs/useListController.md
In doc chapters, I'm trying to keep the same order of sections:
0. screenshot
1. usage
2. list of props
3. one section for each prop
4. additional features
5. "How To" sections, starting with a verb in gerund
I modified chapters edited in #9086 to reflect that.
> [Doc] Fix HowTos order and syntax in various chapters

- docs/List.md
The bulkActionButtons prop is deprecated on both List and ListView https://github.com/marmelab/react-admin/blob/0155a34f7d70535b21a385e5c0b18370ed071e64/packages/ra-ui-materialui/src/list/ListView.tsx#L124
Update the doc to pass the prop to Datagrid component.
> [Doc] Fix deprecated bulkActionButtons prop of List component

- packages/ra-ui-materialui/src/field/ArrayField.tsx
- packages/ra-ui-materialui/src/field/ChipField.tsx
Fixes errors such as the following in `ArrayField.stories.tsx`:
```
Type '{ children: Element; record: { id: number; books: { id: number; title: string; author_id: number; }[]; }; source: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
Property 'record' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.ts(2322)
```
Basically, if the `children` prop type is not exactly the same as what React expects (`ReactNode | undefined`), the type of the component will be `React.FunctionComponent<{}>` instead if the declared type (and hence every additional prop is not recognized)
> [TypeScript] Fix TS errors with `<ArrayField>` and `<ChipField>` in stories

- docs/Confirm.md
The declared interface here 
https://github.com/marmelab/react-admin/blob/f568a52d2b20f8c7e4a1c91155d197cb28bb5df3/packages/ra-ui-materialui/src/layout/Confirm.tsx#L122
expects component for these prop
> [Doc] Fix confirm and cancel icon type

- docs/useList.md
https://github.com/marmelab/react-admin/blob/f568a52d2b20f8c7e4a1c91155d197cb28bb5df3/packages/ra-core/src/controller/list/useList.ts#L64
> [Doc] Fix default perPage value of useList

- docs/useList.md
- packages/ra-core/src/controller/list/useList.spec.tsx
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
Closes #9106
FilterLiveSearch used react-admin's `<Form>`, which did too many things and caused the bug. Switching to a simple form powered by `useForm` fixes the issue. 
I had to augment `useList` to make a real-life filterable list and unit test `<FilterLiveSearch>` .
> Fix FilterLiveSearch reset button does not reset the value

- docs/FilterList.md
- packages/ra-ui-materialui/src/list/filter/FilterList.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterListItem.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
Adds an `icon` prop to FilterListItem, which is displayed to the left of the item's label.
resolves #9146.
> Add an icon to FilterListItem

- docs/WizardForm.md
In the documentation, the snippet about using a custom progress bar in `<WizardForm>` component does not work.
Update this snippet with the correct implementation
> [no-ci][Doc] Fix snippet to use a custom progress bar in WizardForm

- docs/AccordionForm.md
- docs/EditTutorial.md
- docs/LongForm.md
- docs/SimpleForm.md
- docs/TabbedForm.md
When I tried to use AutoSave toolbar, as described in the documentation, TS throw an error `Type '() => JSX.Element' is not assignable to type 'false | ReactElement<any, string | JSXElementConstructor<any>> | undefined'`
> [no-ci][Doc] fix AutoSaveToolbar is not a ReactElement

- packages/ra-ui-materialui/src/defaultTheme.ts
- packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
- packages/ra-ui-materialui/src/input/inputs.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
- packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
Closes #8795
| -------|------|
| ![localhost_9010_iframe html_args= id=ra-ui-materialui-input--all-inputs t=0 957211720134413 viewMode=story(iPhone 12 Pro) (2)](https://github.com/marmelab/react-admin/assets/99944/db72dfed-5927-478c-bcaf-60c0005145fc) | ![localhost_9010_iframe html_args= id=ra-ui-materialui-input--all-inputs t=0 957211720134413 viewMode=story(iPhone 12 Pro) (1)](https://github.com/marmelab/react-admin/assets/99944/3de32cf5-5465-487b-aba7-9205bbc6d92a)|
Also works on filters
> Make inputs full width on mobile

- packages/ra-ui-materialui/src/list/ListToolbar.tsx
The usability of list views on mobile is poor, because the action buttons appear below the filters. In particular, the filters are separated from the content by the actions.
Invert the order between filter form  and actions on mobile
| before | after |
| -------|------|
| ![localhost_8000_(iPhone 12 Pro) (2)](https://github.com/marmelab/react-admin/assets/99944/72188664-9b3b-4200-979f-e657b753b81c) | ![localhost_8000_(iPhone 12 Pro) (1)](https://github.com/marmelab/react-admin/assets/99944/1d0930fe-51ee-4fcb-bba3-1b0bfe589867) |
> Display actions first in the List view on mobile

- docs/AppBar.md
- docs/Layout.md
- docs/Title.md
- packages/ra-ui-materialui/src/layout/TitlePortal.stories.tsx
- packages/ra-ui-materialui/src/layout/TitlePortal.tsx
The `<TitlePortal>` component fixes the page title style without possibility to customize it. 
Accept extra props
```jsx
export const MyAppBar = () => (
<AppBar>
<TitlePortal variant="body2" component="h3" />
<SettingsButton />
</AppBar>
);
```
Closes #8871
> Add ability to customize the page title style

- docs/Datagrid.md
- docs/SimpleList.md
- examples/demo/src/reviews/ReviewListDesktop.tsx
- examples/demo/src/reviews/rowSx.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
This PR intends to substitute `rowStyle` by `rowSx` for styling the `Datagrid` and `SimpleList` rows for two reasons:
1. `Sx` is more common in mui instead of `style` to style.
2. `rowStyle` will apply to the whole row. If one wants to highlight specific cells in the datagrid body, for example highlight duplicate phone numbers, they have to write their own `DatagridBody` and `DatagridBodyRow`. Meanwhile, `rowSx` can fix the problem.
Follow up of https://github.com/marmelab/react-admin/pull/8630
> Replace rowStyle with rowSx

- docs/ArrayField.md
- docs/SingleFieldList.md
- packages/ra-ui-materialui/src/field/ArrayField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.tsx
> Fix SingleFieldList children don't use default link color

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.tsx
Closes #9134
The problem occurs in all select inputs:
- `SelectInput`
- `SelectArrayInput` 
- `AutocompleteInput`
- `AutocompleteArrayInput`
- `RadioButtonGroupInput`
- `CheckboxGroupInput`
The doc doesn't need to be updated, as it already states that the choices aren't translated when inside `ReferenceInput`.
> Fix SelectInput translates choices even inside a ReferenceInput

- packages/ra-core/src/form/choices/useChoicesContext.ts
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
There are 2 problems:
- `useChoicesContext` doesn't pass the `isLoading` prop to `useList`
- `useChoicesContext` returns the `isLoading` prop it receives directly
This leads to a race condition where `isLoading` is already `false` while `allChoices` isn't updated yet (due to `useEffect` in `useList`). 
Pass the `isLoading` from prop to `useList`, and return the `isLoading` from `useList`
Closes #9138
> Fix `<SelectInput>` throws error when fetching choices manually

- docs/Fields.md
- packages/ra-ui-materialui/src/field/ArrayField.tsx
- packages/ra-ui-materialui/src/field/BooleanField.tsx
- packages/ra-ui-materialui/src/field/ChipField.tsx
- packages/ra-ui-materialui/src/field/DateField.tsx
- packages/ra-ui-materialui/src/field/EmailField.tsx
- packages/ra-ui-materialui/src/field/FileField.tsx
- packages/ra-ui-materialui/src/field/FunctionField.tsx
- packages/ra-ui-materialui/src/field/ImageField.tsx
- packages/ra-ui-materialui/src/field/NumberField.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
- packages/ra-ui-materialui/src/field/RichTextField.tsx
- packages/ra-ui-materialui/src/field/SelectField.tsx
- packages/ra-ui-materialui/src/field/TextField.tsx
- packages/ra-ui-materialui/src/field/UrlField.tsx
- packages/ra-ui-materialui/src/field/WrapperField.tsx
- packages/ra-ui-materialui/src/field/types.ts
Fixes https://github.com/marmelab/react-admin/issues/9102
> Fix Fields Record Type Parameter

- docs/FilterLiveSearch.md
- examples/crm/src/companies/CompanyListFilter.tsx
- examples/crm/src/contacts/ContactListFilter.tsx
- examples/demo/src/products/Aside.tsx
- examples/demo/src/visitors/VisitorListAside.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
Closes #9175
This could be considered as a minor change, but since the doc was never up to date, and since it's easy to override, I think we can accept it as a bugfix.
> Fix `<FilterLiveSearch>` uses label as placeholder by default

- docs/NumberInput.md
> [Doc] Fix `<NumberInput>` usage in Filter Forms

- packages/ra-core/src/i18n/TranslationMessages.ts
Add missing types for TranslationMessages.
https://github.com/marmelab/react-admin/pull/9059/files#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b
> Add missing types for TranslationMessages

- docs/UpdateButton.md
- packages/ra-ui-materialui/src/button/UpdateButton.stories.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.spec.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.tsx
> Fix UpdateButton with custom notification doesn't close the confirmation dialog

- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
> Fix ArrayInput Does Not Apply Default Values Set On Inputs

- packages/ra-core/package.json
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/Form.stories.tsx
- packages/ra-core/src/form/ValidationError.spec.tsx
- packages/ra-core/src/form/ValidationError.tsx
- packages/ra-core/src/form/useGetValidationErrorMessage.ts
- packages/ra-core/src/form/useInput.ts
- packages/ra-core/src/form/useUnique.stories.tsx
- packages/ra-core/src/form/useUnique.ts
- packages/ra-core/src/i18n/TestTranslationProvider.tsx
- packages/ra-ui-materialui/src/form/SimpleForm.spec.tsx
- packages/ra-ui-materialui/src/input/InputHelperText.tsx
- packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
- yarn.lock
> Fix validation errors from resolvers are not translated

- docs/js/ra-doc-exec.js
The TS to JS transpilation in the doc pages works well… except when a snippet contains only types. In this case, the transpiled JS is empty.
When the transpiled JS is empty, replace the content with the following comment:
```
// TypeScript-only snippet, please select the TS language ↗️
```
> Doc: display a comment inviting to switch to TS if transpiled code is empty

- docs/useInfiniteGetList.md
useInfiniteGetList was missing a letter in one of the import blocks
> [Doc] Fixed Typo in useInfiniteGetList.md

- docs/PrevNextButtons.md
- examples/demo/src/orders/OrderEdit.tsx
- packages/ra-core/src/controller/usePrevNextController.ts
- packages/ra-ui-materialui/src/button/PrevNextButtons.spec.tsx
- packages/ra-ui-materialui/src/button/PrevNextButtons.stories.tsx
- packages/ra-ui-materialui/src/button/PrevNextButtons.tsx
`<PrevNextButtons>` has to fetch the entire list to determine the previous and next id. This may be costly in network and server time (on the client-side, iven with a list of 1000 items, the time is negligible). 
Check if the previous and next id can't be determined from the cache first, so that users coming from a list page don't need to fetch the entire list of records
When a user reaches the end of the list cache, update the list params in the store to increment or decrement the page.
> Update `<PrevNextButtons>` to fetch less aggressively

- packages/ra-ui-materialui/src/detail/EditGuesser.spec.tsx
- packages/ra-ui-materialui/src/detail/EditGuesser.tsx
- packages/ra-ui-materialui/src/detail/ShowGuesser.spec.tsx
- packages/ra-ui-materialui/src/detail/ShowGuesser.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.spec.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.tsx
Guessers are convenient for tests... except they log their output to the console
- Disable guessers log outside development by default
- expose a prop to set the logging behavior
> Fix Guessers should not log in CI by default

- packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
- packages/ra-ui-materialui/src/list/filter/FilterFormInput.tsx
The Remove button on filter inputs is confusing when there are more than one input - it's hard to determine if it relates to the input on the left or on the right
And on mobile, the remove button breaks the layout
- Move the remove button after the input, so that it comes first in the focus order, and the layout is clearer
- Change the remove icon so that it is not too close to the clear icon in resettable text inputs
- automatically focus an input after being added to save 1 click
https://github.com/marmelab/react-admin/assets/99944/bbe88607-b660-457b-8770-9fcccc468d92
| -- | -- |
| ![127 0 0 1_8000_(iPhone 12 Pro) (1)](https://github.com/marmelab/react-admin/assets/99944/44dce1f3-869b-4018-9037-8b231a7a3666) | ![127 0 0 1_8000_(iPhone 12 …
> Update Filter Form to show remove button after the input

- docs/ReferenceManyToManyInput.md
ReferenceManyToManyInput doc explained how to use the component with artist resource while examples use band resource
Fix the doc
> [Doc] Fix explanations context in ReferenceManyToManyInput documentation

- greenframe-confirm-file.txt
- index.html
- landing-page/index.html
- landing-page/public/greenframe-confirm-file.txt
Added on bottom right corner
No real preview available before activation, sorry
But would look like that :
> Add greenframe widget on landing page

- examples/demo/src/invoices/InvoiceList.tsx
- packages/ra-core/src/controller/input/useReferenceParams.ts
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/list/useListParams.ts
- packages/ra-core/src/controller/useSortState.ts
- packages/ra-core/src/types.ts
- packages/ra-data-simple-rest/src/index.spec.ts
- packages/ra-ui-materialui/src/button/ExportButton.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
- packages/ra-ui-materialui/src/list/InfiniteList.tsx
- packages/ra-ui-materialui/src/list/List.tsx
- packages/ra-ui-materialui/src/list/ListActions.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
Currently `order` in `SortPayload` type definition is a general string, but it shall be `ASC` or `DESC` in accordance with the docs and sort clicks in `Datagrid`  This PR changes the definition of `order` to `ASC|DESC`
I also changed some `desc` in spec or demo files to `DESC`, because, if we use `Datagrid` from the react-admin, then our order would be predefined `DESC` or `ASC`, not the small cased `desc` or `asc`.
> Change the definition of sort order to ASC|DESC

- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
`<ReferenceManyField>` throws the error: `target and id are required` when it’s used in an `aside` of an `<Edit>` component.
Checking if record does not exist with `useRecordContext` solves the problem.
`useReferenceManyFieldController` should check if the record exist before calling `useGetManyReference`
> Fix useReferenceManyFieldController fails with error when the record is not yet present

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Closes https://github.com/marmelab/react-admin/issues/9239
> fix AutocompleteInput's onInputChange is never called

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
If we want to react to a change in `<AutocompleteInput>`'s value, all we can have in `onChange` is the selected value (i.e. its id in most cases).
If we want to use another field of the selected record, we first need to fetch the record by its id (for instance using `useGetOne`), which is cumbersome, especially knowing the full record is already available in the ChoicesContext.
Add a second argument to `onChange` to pass the full record, which allows the developer to use any field of it.
- This was also implemented in `<AutocompleteArrayInput>`
- However I could not implement it in `<SelectInput>` nor in `<SelectArrayInput>`, because they both rely on HTML's `<select>`, which only provides the option's `value` in `event.target.value`. It may be still doable by using the ChoicesContext, …
> Include full record in `<AutocompleteInput>` and `<AutocompleteArrayInput>`'s `onChange`

- examples/crm/src/Layout.tsx
- examples/crm/src/deals/DealList.tsx
- examples/crm/src/deals/index.ts
Large apps need to do code splitting. It turns out it's not as simple as using `React.lazy()`, as the layouts don't use `Suspense` by default. 
Update the CRM demo example to illustrate the way to do it.
> [Demo] Add lazy loading to CRM demo to illustrate code splitting

- docs/RichTextInput.md
- examples/demo/src/products/ProductCreate.tsx
- examples/demo/src/products/ProductEdit.tsx
The `<RichTextInput>` component depends on TipTap, which in turns depends on ProseMirror. Together, these libraries represent about 120kB of minified JavaScript. If you don't use `<RichTextInput>` on all your forms, you can lazy load it to reduce the size of your bundle.
To do so, replace the import:
```jsx
import { RichTextInput } from 'ra-input-rich-text';
```
with a dynamic import:
```jsx
const RichTextInput = React.lazy(() =>
import('ra-input-rich-text').then(module => ({
default: module.RichTextInput,
}))
);
```
Once compiled, your application will load the `<RichTextInput>` only when needed.
> [Doc] Explain how to lazy load `<richTextInput>`

- examples/crm/src/App.tsx
- examples/demo/src/App.tsx
If this application is installed on the same domain as other demo applications. The store is overridden. The data are not synchronized anymore.
Add a custom store with a dedicated application key.
> [Demo] Fix preferences are shared between demos

- packages/ra-ui-materialui/src/layout/TopToolbar.tsx
Fix https://github.com/marmelab/react-admin/issues/9108
> Fix `<TopToolbar>`: React does not recognize the hasCreate prop on a DOM element

- docs/ReferenceManyToManyInput.md
The ReferenceManyToManyInput documentation is almost empty.
Improve and reorder ReferenceManyToManyInput documentation in the way of the other documentation pages
> [Doc] Improve and reorder ReferenceManyToManyInput documentation

- packages/ra-input-rich-text/src/RichTextInput.tsx
Fix https://github.com/marmelab/react-admin/issues/9265
> Fix `<RichTextInput>` does not trigger `onBlur`

- packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceArrayField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
`<ReferenceArrayField>` does not support `queryOptions`
Add `queryOptions` support for `<ReferenceArrayField>` and  `useReferenceArrayFieldController`
> Add queryOptions support for ReferenceArrayField

- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> Fix filters not matching inputs are ignored without syncWithLocation

- packages/ra-ui-materialui/src/button/PrevNextButtons.stories.tsx
- packages/ra-ui-materialui/src/button/PrevNextButtons.tsx
- `<PrevNextButton>` takes the entire line by default. It should be inline instead of block
- `<PrevNextButton>` doesn't use the base Typography
- `<PrevNextButton>` adds useless markup
Use `<Stack>` with custom styling
The change of inner class name is technically a breaking change, but I suggest to accept it because the feature is very recent and wasn't properly styled before.
> Fix `<PrevNextButton>` default style

- docs/useRegisterMutationMiddleware.md
found a little typo at the first paragraph from this page: https://marmelab.com/react-admin/useRegisterMutationMiddleware.html
> [Doc] Fix typo in useRegisterMutationMiddleware introduction part

- docs/canAccess.md
By default, RBAC disables menu items the user cannot access to.
But `canAccess` provide a way to disable menu items instead of not render them. 
This PR attempt to add a section in the documentation to explain how to disable menu item with RBAC and `canAccess`
> [Doc] Explain how to disable menu item with RBAC

- packages/ra-core/src/form/useInput.ts
Fix https://github.com/marmelab/react-admin/issues/9261
Actually this is a workaround, since the root issue has to be fixed on RHF's side (https://github.com/react-hook-form/react-hook-form/issues/10907)
Cannot be tested automatically.
To test:
- Upgrade to RHF >= 7.46.0
- Upgrade to React 18
- Set `disabled={false}` somewhere in the demo
> Fix inputs with `disabled={false}` throw an error (workaround)

- packages/ra-data-graphql-simple/src/index.ts
Resolves #9278, same as #9279 but targeting `next` instead of `master`
Without writing a complete build query factory it's not possible to customize `ra-data-graphql-simple`'s default build query. If we only want to modify the response parser for example, we would need to write build GraphQL query and variables logic as well.
Export `buildQueryFactory`, `buildGqlQuery`, `buildVariables` and `getResponseParser` from the package to allow for more granular customization.
> Additional exports for customization in ra-data-graphql-simple

- docs/Inputs.md
- docs/useInput.md
This PR adds an i18n section to the Inputs.md doc instructing users on the use of the `InputHelperText` component.
A **tip** referencing the use of said component has also been added to useInput.md.
I also removed a redundant `formState` reminder from useInput.md
Thanks!
> Add i18n InputHelpterText section to Inputs/useInputs docs

- packages/ra-input-rich-text/package.json
- packages/ra-input-rich-text/src/RichTextInput.stories.tsx
- packages/ra-input-rich-text/src/RichTextInput.tsx
- yarn.lock
When adding tiptap extensions that relies on the current record, you have to update the `editorOptions`. However the changes aren't reflected.
This PR solves this by passing the `editorOptions` as `useEditor` dependencies
> Fix RichTextInput does not update when its editorOptions prop changes

- docs/Inputs.md
Clone of #9301 , which seems to have been closed because I initially targeted 'next'
The Third-Party Components section of the docs previously directed users seeking DateInput components to a now-deprecated library which had not been maintained since react-admin v3, and was not compatible with MUI v5.
This PR updates the docs to direct users to a package that I have deployed to npm, containing the pickers which I have used in my current project for the last couple of years. These pickers are fully MUI v5-compatible and use the latest react-admin standards (InputHelperText component, current patterns of useInput, etc.).
Thanks!
> [Docs] Update third-party component section; new date/time inputs

- packages/ra-core/src/form/useUnique.spec.tsx
- packages/ra-core/src/form/useUnique.ts
- packages/ra-core/src/form/validate.ts
While using `useUnique` in an non required input, and when sending the form with empty value within this input, `useUnique` search for data with `null` value and returns results that indicates the record is not unique and indeed, cause errors on form.
This issue happens with some DBMS and DataProvider
Do not send request to the API if value tested by useUnique is empty.
> Fix useUnique send request even if the field value is empty

- docs/Buttons.md
- packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/DeleteButton.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.stories.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/layout/Confirm.tsx
> [RFR] Pass confirmColor from DeleteButton to Confirm

- docs/FilteringTutorial.md
- docs/StackedFilters.md
The examples showing how to use <StackedFilters> do not explain well. They do not use the right prop.
```
<List
filters={
<StackedFilters config={documentsListFilters} />
}
>
```
It should be:
```
<List
actions={
<TopToolbar>
<StackedFilters config={documentsListFilters} />
<ExportButton />
</TopToolbar>
}
>
```
> [doc] show how to use StackedFilters well

- README.md
@djhi, Even though it's still possible to link a yarn 3 project to a yarn 1 project by setting the `YARN_IGNORE_PATH` environment variable as mentioned in https://github.com/marmelab/react-admin/issues/9331 , I don't think it is a recommended way to do it.
Let's consider dropping the yarn v1 version support. 
Dropping yarn v1 support in the documentation is not a breaking change IMO because the yarn version bump https://github.com/marmelab/react-admin/commit/8fe89469d1ad44056215e66ff2cd84aa72b2c595 commit already happened in react-admin v4 alpha.
> update yarn linking instruction

- packages/ra-ui-materialui/src/preferences/FieldToggle.tsx
- packages/ra-ui-materialui/src/preferences/FieldsSelector.tsx
When configuring the `DatagridConfigurable` using its editor, one can drag and drop a field outside the list of fields (for instance below the button)
Wrap the items list in a `ul` element and double check users drop the column inside it
> Fix DatagridConfigurable editor allows to drag fields outside its list

- packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
\<BulkDeleteWithUndoButton> prop `mutationOptions` does not have sufficient types.
It lacks MutationMode. It is in fact hardcoded but it can be also overwritten by `otherMutationOptions`. 
https://github.com/marmelab/react-admin/blob/6afaa0a64b4fa9d9fc11c499395ce23a43efc42f/packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx#L30-L32
https://github.com/marmelab/react-admin/blob/6afaa0a64b4fa9d9fc11c499395ce23a43efc42f/packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx#L69-L74
The use case is utilization of existing bulk delete button without confirmation but with pessimistic mode.
> Added type for `mutationMode` to `mutationOptions` prop for <BulkDeleteWithUndoButton>

- examples/demo/src/i18n/en.ts
- examples/demo/src/i18n/fr.ts
- examples/demo/src/orders/OrderList.tsx
- examples/demo/src/reviews/reviewFilters.tsx
- examples/demo/src/visitors/Aside.tsx
The current customer aside doesn't allow to list all orders or reviews, and the timeline is clunky
Reorganize the information in the aside
Before:
After:
> [Demo] Improve customer aside

- docs/PasswordInput.md
The doc doesn't explain how to use `<PasswordInput>` in Edit view. This may lead developers to expose passwords in clear.
Be very clear about never exposing password, even in the Edition view.
> [Doc] Explain how `<PasswordInput>` can be used to update a password

- packages/ra-ui-materialui/src/input/BooleanInput.tsx
fixes #9360
Following the template used in issue: 
```tsx
export const theme: ThemeOptions = {
components: {
MuiSwitch: {
defaultProps: {
color: 'warning',
},
},
},
};
```
```tsx
<p>
Switch
<Switch color="success" />
</p>
<p>
BooleanField
<BooleanInput source="id" color="success" />
</p>
```
> fix: <BooleanInput> color property should be configurable globally through MUI defaultProps system.

- packages/ra-core/src/dataProvider/useGetList.spec.tsx
- packages/ra-core/src/dataProvider/useGetList.ts
**Solution**: only pre-populate the `getOne` query cache when there is a reasonable number of records returned, say 100.
> Fix `useGetList` optimistic cache update leads to ui freeze when too many records are returned

- docs/SelectInput.md
From the docs, it says you can pass in an options props but trying to do that throws a TS error because that isn't supported.
Remove this point of the documentation
Fixes #9352
> [Doc] Remove unsupported `<SelectInput options>` prop from the doc

- docs/LocalesMenuButton.md
- packages/ra-ui-materialui/src/button/LocalesMenuButton.stories.tsx
- packages/ra-ui-materialui/src/button/LocalesMenuButton.tsx
If you want to customize the `<LocalesMenuButton>` icon, you have to rewrite it. This PR adds an optional `icon` prop.
> Locales button icon

- docs/Features.md
- docs/FilterButton.md
- docs/FilterForm.md
- docs/FilteringTutorial.md
- docs/List.md
On the documentation, videos, pictures and gifs are showing `<SearchInput />` element, but in the code it's writed `<TextInput label="Search" />` as this:
Match code and illustrations by apllying `<SearchInput />` everywhere.
> match code and illustrations for SearchInput

- docs/Features.md
- docs/Inputs.md
- docs/Readme.md
- docs/Tutorial.md
- examples/simple/src/comments/CommentEdit.tsx
- examples/simple/src/posts/PostEdit.tsx
- examples/simple/src/users/UserEdit.tsx
Since `react-hook-form` v7.46.0 and https://github.com/react-hook-form/react-hook-form/pull/10805, a `disabled` input makes the form dirty. This isn't going to change, so we may as well warn our users about it.
Closes #9378
> [Doc] Add gotcha about `<Input disabled>` usage and `isDirty` form state

- packages/ra-core/src/controller/list/useInfiniteListController.spec.tsx
- packages/ra-core/src/dataProvider/useInfiniteGetList.ts
- total should return 0 if the data is empty;
Closes #9388
> Fix total in `useInfiniteGetList` for empty results

- packages/ra-ui-materialui/src/button/UpdateButton.stories.tsx
- packages/ra-ui-materialui/src/button/UpdateWithUndoButton.spec.tsx
- packages/ra-ui-materialui/src/button/UpdateWithUndoButton.tsx
UpdateButton cannot be used in a List because it does not allow to stop the propagation of the click event, hence it redirects to the Edit view. We should add a way to prevent this.
Stop the propagation and add test and story
> Fix update button cannot be used in a list

- packages/ra-i18n-i18next/src/stories-en.ts
- packages/ra-i18n-i18next/src/stories-fr.ts
- packages/ra-i18n-i18next/src/useI18nextProvider.ts
The bulk actions toolbar label doesn’t replace the token with the value
Change the variable name from `count` to `smart_count` on the i18nextProbider
> Fix i18next translation provider fails to use smart count in BulkActionsToolbar

- docs/Search.md
- docs/SearchWithResult.md
- docs/navigation.html
The new `<SearchWithResult>` EE component deserves a documentation in the OSS documetation. 
This PR add this documentation.
> [Doc] introduce SearchWithResult component ducumentation

- docs/canAccess.md
Update the [`canAccess` action](https://marmelab.com/react-admin/canAccess.html#action) doc to match the example in the Enterprise Edition doc
> [Doc] Update canAccess doc

- packages/ra-ui-materialui/src/button/CreateButton.tsx
> Fix `<CreateButton>` keeps state between pages

- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
FilterLiveSearch input with "Enter" keyboard event change url from `myUrl/#/myTab?filter={"q"%3A"test"}` to `myUrl/?q=test#/myTab?filter={"q"%3A"test"}`
Catch the natural form submit actions (with e.preventDefault)
Fix #9387
> Fix bad url upon `<FilterLiveSearch>` submission

- docs/Create.md
The chapters of the Create redirect section don't list function option as it show redirect Edit section while react-admin also admit that option.
Add that options as Edit redirect chapters
> [Doc] Improve the Create redirect section

- packages/ra-ui-materialui/src/layout/LoadingIndicator.tsx
As requested in #9418
This makes it possible to invoke a callback when a user clicks the `LoadingIndicator` to trigger a refresh, primarily to address this use-case: https://github.com/marmelab/react-admin/issues/3617#issuecomment-525812935
I didn't find any existing unit tests for this part of the code, but I'm happy to add a unit test if somebody can point me to where it should go.
> Add `onClick` prop to `<LoadingIndicator>`, allowing to trigger actions (like a refresh) on click

- docs/EditInDialogButton.md
> [Doc] Document `<EditInDialogButton>` deletion side effect

- packages/ra-core/src/auth/addRefreshAuthToAuthProvider.ts
- packages/ra-core/src/auth/addRefreshAuthToDataProvider.ts
When you have a custom dataProvider with custom methods, passing it to the `addRefreshAuthToDataProvider` method loose its type. Same for the `addRefreshAuthToAuthProvider`.
Declare a type parameter. You don't have to specify the type, it's inferred
> Allow to pass custom provider types to addRefreshAuth functions

- docs/Form.md
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/Form.tsx
- packages/ra-core/src/form/useAugmentedForm.ts
- packages/ra-core/src/form/useNotifyIsFormInvalid.ts
> [RFR] add disabling invalid form notification

- docs/CheckForApplicationUpdate.md
- packages/ra-core/src/util/useCheckForApplicationUpdate.ts
- packages/ra-ui-materialui/src/layout/CheckForApplicationUpdate.tsx
Fix issue in https://github.com/marmelab/react-admin/issues/9432
> Fix `<CheckForApplicationUpdate>` may check a stale copy in cache for update

- docs/SolarLayout.md
The `<SolarMenu>`'s `sx` and `className` props are missing in the documentation
Document these props
Plus: add screenshots to demonstrate custom appBar and `sx`
> [Doc] introduce classname and sx prop for SolarMenu component

- docs/AccordionForm.md
- docs/Buttons.md
- docs/Create.md
- docs/CreateInDialogButton.md
- docs/Edit.md
- docs/EditInDialogButton.md
- docs/EditTutorial.md
- docs/Features.md
- docs/FileInput.md
- docs/Form.md
- docs/Inputs.md
- docs/List.md
- docs/ListTutorial.md
- docs/LongForm.md
- docs/MarkdownField.md
- docs/ReferenceManyToManyField.md
- docs/SaveButton.md
- docs/Show.md
- docs/ShowBase.md
- docs/SimpleForm.md
- docs/TabbedForm.md
- examples/demo/src/reviews/ReviewEdit.tsx
Props forwarding is no longer necessary since 4.0 (except for the Layout component).
> [Doc] Fix various snippets containing props forwarding

- packages/ra-ui-materialui/src/layout/CheckForApplicationUpdate.tsx
Fix suggested in https://github.com/marmelab/react-admin/pull/9437#issuecomment-1808727199
> [Typescript] Fix `<CheckForApplicationUpdate>` props type should allow `onNewVersionAvailable`

- docs/SingleFieldList.md
- examples/crm/src/contacts/ContactList.tsx
- examples/crm/src/contacts/TagsList.tsx
- examples/simple/src/posts/PostList.tsx
- examples/simple/src/posts/PostShow.tsx
- packages/ra-ui-materialui/src/field/ChipField.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.spec.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.stories.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.tsx
`<SingleFieldList>` has many issues:
- It still clones its children (we don't do this since 3.x)
- It forces users to pass children, while most of the time it's a `<ChipField>`
- It renders kind of a `Stack`, except it's not a `Stack`
- It doesn't support the `empty` prop
- `<SingleFieldList>` now renders a real `<Stack>`, and supports all its props
- `<SingleFieldList>` used without children renders a `<ChipField>` with the `recordRepresentation`
- `<SingleFieldList>` supports an `empty` prop
```jsx
const PostList = () => (
<List>
<Datagrid>
<TextField source="id" />
<TextField source="title" />
<DateField source="published_at" />
<BooleanField source="commentable" />
<NumberField source="views" />
<ReferenceArrayField label="Tags" reference="tags" source="tags">
<SingleFieldList /> …
```
> Update `<SingleFieldList>` to make it more powerful

- docs/Remix.md
In the Remix tuto, RA had a decoding error (net::ERR_CONTENT_DECODING_FAILED) on query that have less than 10 results.
Add accept `Accept-Encoding` prop to header of the query
Closes #9445
> [Doc] Fix api implementation in Remix tutorial throws a decoding error when less than 10 records are returned

- docs/Breadcrumb.md
- docs/CustomRoutes.md
- docs/Datagrid.md
- docs/Features.md
- docs/List.md
- docs/ListTutorial.md
- docs/RealtimeDataProvider.md
- docs/Resource.md
- docs/Tutorial.md
- packages/ra-ui-materialui/src/button/PrevNextButtons.spec.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.spec.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
- packages/ra-ui-materialui/src/list/listFieldTypes.tsx
`<Datagrid>` should be smarter than having `rowClick` default to `false`.
It can use the resource definition to look for an existing Show or Edit view, and default to those instead.
This PR changes the default value to be a bit smarter.
`<Datagrid>` will now make the rows clickable as soon as a Show or Edit view is declared on the resource.
If you previously relied on the fact that the rows were not clickable by default, you now need to explicitly disable the `rowClick` feature:
```diff
-<Datagrid>
+<Datagrid rowClick={false}>
...
</Datagrid>
```
> Use resource definition to set default `<Datagrid rowClick>` value

- docs/Configurable.md
- docs/WrapperField.md
Just adding a comment regarding the `Inspector` component. If this doesn't exist on a custom layout the configuration feature does not seem to work i.e the popup fails to appear
> docs: inspector component details for configuration feature

- packages/ra-ui-materialui/src/list/pagination/PaginationActions.tsx
Material-ui v5.15.18 introduced a new prop injected to `PaginationAction`, `slotProps`, which isn't supposed to be passed down to the `Pagination` component.
Refs https://github.com/mui/material-ui/pull/39353
Closes `<Pagination>` logs a warning #9470
> Fix `<Pagination>` logs a warning

- docs/AdvancedTutorials.md
- docs/Features.md
Since the "Features" and the "advanced tutorials" pages are indexed by our full-text search engine, adding more content there may help answer questions from users. 
I also simplified the "advanced tutorials" page as it became hard to scan.
> [Doc] Add link to tutorial for headless admin

- docs/Admin.md
- docs/DataProviderWriting.md
> [Doc] Fix snippets fails to render in JS

- examples/crm/package.json
- examples/demo/package.json
- examples/simple/package.json
- packages/ra-core/package.json
- packages/ra-no-code/package.json
- packages/ra-ui-materialui/package.json
- packages/react-admin/package.json
- yarn.lock
Reverts marmelab/react-admin#9480
The react-router team has published a fix on their side in 6.20.1, so the version constraint on `react-router-dom` is no longer necessary.
https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6201
> Revert "Fix TabbedForm and TabbedShowLayout tab navigation: limit react-router version to 6.18.0 as a workaround"

- packages/ra-data-graphql-simple/README.md
- packages/ra-data-graphql-simple/src/buildGqlQuery.test.ts
- packages/ra-data-graphql-simple/src/buildGqlQuery.ts
- packages/ra-data-graphql-simple/src/buildVariables.test.ts
- packages/ra-data-graphql-simple/src/buildVariables.ts
- packages/ra-data-graphql-simple/src/getResponseParser.test.ts
- packages/ra-data-graphql-simple/src/getResponseParser.ts
- packages/ra-data-graphql-simple/src/index.ts
- packages/ra-data-graphql/src/index.ts
The goal here is to add an alternative to the virtual `DELETE_MANY` and `UPDATE_MANY` actions that trigger multiple `DELETE` and `UPDATE` requests under the hood. If the GraphQL Schema supports bulk deletes / updates, the Data Provider can be initialized with the `bulkActionsEnabled` option (turned off by default) and bulk `DELETE_MANY` and `UPDATE_MANY` will light up.
> GraphQL Simple Data Provider DELETE_MANY and UPDATE_MANY Support

- packages/create-react-admin/src/generateProject.ts
- packages/create-react-admin/templates/common/src/Layout.tsx
Add a Layout component in the project template, overriding the default layout by adding the CheckForApplicationUpdate component.
> Feat(cra): Add layout to handle CheckForApplicationUpdate

- packages/ra-ui-materialui/src/theme/useTheme.spec.tsx
- packages/ra-ui-materialui/src/theme/useTheme.ts
> Fix `useTheme` may return `undefined`

- docs/useInput.md
> Fix `useInput` documentation regarding errors display

- packages/ra-ui-materialui/src/detail/Tab.tsx
Before:
After:
I applied the same styles as the `SimpleShowLayout`
Fixes #9405
> Fix `<TabbedShowLayout>` displays its fields as full width blocks

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Some props such as `startAdornment`, `disabled` etc are not applied to the renderer input of the `<AutocompleInput>` component, because `TextFieldProps` are not applied.
Re-order props to avoid `TextFieldProps` to be overloaded
> fix: AutocompleteInput TextFieldProps are not applied

- docs/ReferenceManyField.md
- packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
> Fix `useReferenceManyFieldController` does not debounce `setFilters`

- docs/Show.md
Fixes this issue in the [docs](https://marmelab.com/react-admin/Show.html#queryoptions):
> [Doc] Fix typo in `<Show queryOptions>` doc

- docs/Upgrade.md
> [Doc] Document React Query codemods

- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
All react-admin choices inputs use the `recordRepresentation` defined on the `<Resource>` as the default `optionText`. Except the `<SelectArrayInput>` component. This forces users to define the `optionText` everytime they use it.
Use the `recordRepresentation` as every other inputs.
> fix: SelectArrayInput does not use recordRepresentation

- docs/AccordionForm.md
- docs/MarkdownInput.md
The documentation for MarkdownInput is short and doesn't show the power of that component. 
https://marmelab.com/react-admin/MarkdownInput.html
Expand it
> Doc: Improve MarkdownInput documentation

- packages/ra-core/src/dataProvider/useInfiniteGetList.spec.tsx
- packages/ra-core/src/dataProvider/useInfiniteGetList.ts
Just like `useGetList`, `useInfiniteGetList` shouldn’t prepopulate the `getOne` cache when dealing with large responses, for performance reasons.
**Solution**
> Update `useInfiniteGetList` to skip `getOne` cache population for large responses

- docs/Configurable.md
- docs/Reference.md
- packages/ra-core/src/preferences/usePreference.ts
- packages/ra-ui-materialui/src/preferences/Configurable.stories.tsx
> Feat(usePreference): Throw an error if used outisde right context

- packages/create-react-admin/src/ProjectState.ts
- packages/create-react-admin/src/StepAuthProvider.tsx
- packages/create-react-admin/src/StepDataProvider.tsx
- packages/create-react-admin/src/StepInstall.tsx
- packages/create-react-admin/src/app.tsx
- packages/create-react-admin/src/cli.tsx
The `create-react-admin` currently requires user to make choices interactively, preventing automated usages
Add flags for all parameters
> Make create-react-admin usable in non-interactive mode

- packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
With this merge request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170 introduced into @types/react 18.2.43, `placeholder` prop is no longer in `HTMLAttributes`.
Somehow since 18.2.43 the `<MenuItemLink>` requires us to pass the `placeholder` prop to the `<a>` tag below, where there are no such prop defined in [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
Closes #9507
> Fix `<MenuItemLink>` type by omitting `placeholder` prop

- examples/simple/assets/app.css
- examples/simple/src/Layout.tsx
The ReactQueryDevtools button is too big
> style: narrowing ReactQueryDevtools button

- packages/ra-core/src/controller/record/WithRecord.tsx
This PR aims to align the types used in `FunctionField` and `WithRecord`. Currently, `FunctionField` utilizes `Record<string, any>`, whereas `WithRecord` employs `Record<string, unknown>`. The proposed change seeks to standardize these types.
I came across this change (https://github.com/marmelab/react-admin/pull/9092) and noticed that the `WithRecord` prop type hasn't been updated yet.
Given the discussion in this comment (https://github.com/marmelab/react-admin/pull/8963#discussion_r1213580943), maintaining type consistency between `FunctionField` and `WithRecord` seems crucial.
> Ensure type consistency between `WithRecord` and `FunctionField`

- packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
Hi @fzaninotto,
After applying your review from https://github.com/marmelab/react-admin/pull/9555 , I built and tested it locally with `yarn link` to my own project. Omitting from just `MenuItemProps` won't fix the problem. 
It seems we have to omit the `placeholder` from the union of `LinkProps` and `MenuItemProps`. Both of them seems has some issue require a non-existent `placeholder`.
> Follow up fix of `<MenuItemLink>` `placeholder` prop type

- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
Reverts marmelab/react-admin#9532 since it introduced a regression:
When `SelectArrayInput` is used inside a reference input, and targets a resource that does not have a record representation: we used to use the `'name'` field, whereas now the record representation will be `#${record.id}` which is less informative.
> Revert "fix: SelectArrayInput does not use recordRepresentation"

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx
This adds stopPropagation() to the entire DataGrid, to avoid propagation when clicking anywhere in the grid.
Currently, clicking the select all checkbox or an empty space  on the header still triggers the click on the parent element (e.g. nest 2 DataGrids and the select all button will trigger the rowClick of the parent DataGrid).
If this approach seems too much, then we could move this line to the checkbox in DataGridHeader.
> Fix click on `<Datagrid>` Select All button bubbles up to parent Datagrid

- examples/crm/src/dataGenerator/deals.ts
- examples/crm/src/deals/DealCreate.tsx
When a user creates a new deal, it's not displayed in the list, as if it had not been created.
Additionally, when creating several deals, they do not appear in a logical order.
https://github.com/marmelab/react-admin/assets/7949510/0604bf7e-bab3-4b74-915e-13096408197f
https://github.com/marmelab/react-admin/assets/7949510/3133752e-5d42-491f-8c94-55ba4d5c4991
> Fix new deals do not appear in the crm demo

- docs/Edit.md
- docs/Resource.md
I didn't run this locally, but my research points to me that this should fix the issue of 
`<Edit mutationOptions={{ onSuccess }} mutationMode="pessimistic">`
being displayed as 
`<Edit mutationOptions= mutationMode="pessimistic">`
> [Doc] fix jekyll trying to parse jsx code on <Edit> mutationOptions

- docs/Fields.md
- examples/crm/src/deals/DealList.tsx
- examples/crm/src/deals/OnlyMineInput.tsx
- examples/demo/src/i18n/en.ts
- examples/demo/src/i18n/fr.ts
- examples/demo/src/orders/MobileGrid.tsx
- examples/demo/src/orders/NbItemsField.tsx
- examples/demo/src/orders/OrderList.tsx
- examples/demo/src/products/ProductRefField.tsx
- examples/demo/src/products/ProductReferenceField.tsx
- examples/demo/src/reviews/ReviewEdit.tsx
- examples/demo/src/reviews/ReviewListDesktop.tsx
- examples/demo/src/reviews/ReviewListMobile.tsx
- examples/demo/src/visitors/CustomerLinkField.tsx
- examples/demo/src/visitors/VisitorList.tsx
- examples/simple/src/comments/CommentList.tsx
- packages/ra-ui-materialui/src/input/NumberInput.tsx
React discourages the use of defaultProps and may one day remove support for it. They aren't even documented in the latest version of the React docs. 
Our demos contain custom components that don't really need defaultProps, so this PR replaces it with real props.
Some custom components with defaultProps remain in the demo (StarRatingField, ColoredNumberField, etc) because removing defaultProps for them would lead to a lot of repetition. These currently need defaultProps and there is no better alternative for now.
> [Demo] Remove useless defaultProps usage

- examples/crm/src/dataGenerator/deals.ts
- examples/crm/src/deals/DealCreate.tsx
- examples/crm/src/deals/DealList.tsx
> [Demo] Fix new deal does not appear in the correct order in CRM

- docs/TranslationLocales.md
- Add Vietnamese messages for React-Admin v4.16.6
- Support TypeScript
> docs: update Vietnamese link to replace the deprecated package

- packages/ra-core/src/i18n/useTranslateLabel.ts
- packages/ra-ui-materialui/src/input/TranslatableInputs.spec.tsx
When introducing the `SourceContext`, we also introduced a regression on the label inference (when no translations are provided). We pass the modified `source` to the inference function (eg: `title.en`) instead of the input `source` (eg: `title`).
This results in wrong label like `Title en` instead of `Title`
> Fix label inference regression

- docs/404.html
- packages/ra-ui-materialui/src/layout/Error.tsx
- packages/react-admin/README.md
The page https://marmelab.com/react-admin/Readme.html is no longer maintained an isn't the documentation root anymore. Yet it is visited by users who find links elsewhere in the documentation. 
We can't remove this page though, as existing installations of react-admin will still point to it in the Error page.
> [Doc] Fix link to documentation root

- docs/Tutorial.md
- examples/tutorial/src/MyUrlField.tsx
> [Doc] Fix Tutorial misses URL scheme in custom Field

- packages/ra-ui-materialui/src/list/ListGuesser.stories.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.tsx
> Fix `<ListGuesser>` flashes when changing sort or pagination

- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-ui-materialui/src/list/pagination/Pagination.spec.tsx
- packages/ra-ui-materialui/src/list/pagination/Pagination.stories.tsx
- packages/ra-ui-materialui/src/list/pagination/Pagination.tsx
> [TypeScript] Fix `<Pagination rowsPerPageOptions>` doesn't accept an array of objects

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
In a `<Datagrid>`, the header of sortable columns has a tooltip that is the same for all columns: "Sort". It's not explicit enough, and it's even confusing for screen readers.
Reuse the title logic from `<SortButton>`, which already solves this problem.
Closes #9541
> Fix Datagrid Header Sort Tooltip

- docs/Datagrid.md
- packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
- packages/ra-ui-materialui/src/button/BulkUpdateButton.stories.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
When writing a bulk action button based on `useUpdateMany` with the default mutation mode (pessimistic), the list data doesn't get refreshed after the mutation ends. 
You can reproduce it in the following Stackblitz: https://stackblitz.com/edit/github-4g364g?file=src%2Fposts%2FResetViewsButton.tsx
1. Select a few posts in the list
2. Click on "reset views"
3. When the notification confirms the mutation success, the views of the selected rows don't reset. 
There is a bug in `useUpdateMany`because we use the variable name `data` at several places.
> Fix `useUpdateMany` doesn't properly update cache in pessimistic mode

- docs/CreateReactApp.md
- docs/Tutorial.md
- docs/navigation.html
- [Create-React-App](https://github.com/facebook/create-react-app) is abandonware. We shouldn't encourage developers to use it.
- The doc index on the sidebar is super crowded. We need to remove useless entries.
- Remove the entry in the navigation
- add a warning in the Create-React-App page
- Keep the page to avoid 404 for external links
> [Doc] Remove create-react-app chapter

- docs/FunctionField.md
- docs/WrapperField.md
- add video
- reorganize content
- add more examples
- add TS tip
> [Doc] Improve FunctionField documentation

- docs/SolarLayout.md
RA-EE SolarMenu doc was updated
Update OSS doc
> [Doc] Update SolarMenu doc

- README.md
- docs/Community.md
We now have a YouTube channel who is not shown in the our documentation
> [Documentation] Add doc section

- docs/SolarLayout.md
The SearchWithResult page mentions integration worth SolarLayout
[React-admin - The SearchWithResult Component](https://marmelab.com/react-admin/SearchWithResult.html)
But the opposite isn’t true
[React-admin - The SolarLayout Component](https://marmelab.com/react-admin/SolarLayout.html)
How are users supposed to discover this integration?
Update doc
> [Doc] Update doc SolarLayout with SearchWithResult

- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
> Fix DeleteWithConfirmButton raises an error when the record is not loaded

- packages/ra-core/src/auth/useGetIdentity.ts
- packages/ra-core/src/auth/useHandleAuthCallback.ts
- packages/ra-core/src/core/useResourceDefinitions.ts
- packages/ra-core/src/dataProvider/fetch.ts
- packages/ra-core/src/form/useUnique.ts
Fixes the following TS compilation errors when enabling `strickNullChecks`:
```
3  src/auth/useGetIdentity.ts:51
2  src/auth/useHandleAuthCallback.ts:15
1  src/core/useResourceDefinitions.ts:24
1  src/dataProvider/fetch.ts:103
1  src/form/useUnique.ts:109
```
In master, this reduces the number of strict null check errors from 246 to 238.
Refs #9622
> [TypeScript] Fix some strict null checks errors in core

- packages/ra-core/src/form/Form.tsx
- packages/ra-core/src/util/LabelPrefixContextProvider.spec.tsx
- packages/ra-core/src/util/LabelPrefixContextProvider.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
`<LabelPrefixContextProvider>` concatenates previous prefix if it is inside a `LabelPrefixContext`.
It's lead to return translation key such as `resources.posts.fields.title.resources.comments.fields.body` but it make more sense to simply return `resources.comments.fields.body` even `LabelPrefixContext` is nested inside another.
`<LabelPrefixContextProvider>` was introduce used in this #7710 but keeping previous prefix seems to be useful. 
Do not keep previous prefix
> Fix field label translation concatenates previous prefix

- docs/AccordionForm.md
The EE doc for AccordionForm and AccordionFormPanel was updated
Update OSS doc
> Update AccordionForm and AccordionFormPanel docs

- docs/RecordRepresentation.md
- docs/useGetRecordRepresentation.md
- packages/ra-core/src/controller/record/RecordRepresentation.spec.tsx
- packages/ra-core/src/core/useGetRecordRepresentation.spec.tsx
- packages/ra-core/src/core/useGetRecordRepresentation.ts
- packages/ra-i18n-i18next/src/index.spec.tsx
- packages/ra-ui-materialui/src/detail/Edit.spec.tsx
- packages/ra-ui-materialui/src/detail/Show.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.tsx
useGetRecordRepresentation could be smarter when there is no record representation on the resource.
It could contain a list of fields that can be used as record representation by default, such as:
1. name
2. title
3. label
4. reference
5. id
This PR is the continuation of #9643
> Make use get record representation smarter

- packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceInput.tsx
> Fix `<ReferenceInput>` accepts a validate prop while it should not

- docs/Datagrid.md
- docs/SelectColumnsButton.md
In [React-admin - The Datagrid Component](https://marmelab.com/react-admin/Datagrid.html#configurable) , we don’t mention that you should pass the same preferenceKey to the SelectColumnsButton. That leads to unexpected behaviors when users forget it.
Update the documentation and add an example
> Update Datagrid documention regarding preferenceKey

- examples/simple/src/data.tsx
Raised the following warning in the console:
```
Value of field 'tags' is not an array.
```
> [Demo] Fix missing tags field in simple example fake dataset raises a warning

- docs/Caching.md
Correcting typo in caching docs:
> [Doc] Fix typo in Caching documentation

- packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
Tangentially related to #9587, if 2 inputs are used in filters with the same source then they end up with duplicate keys even when those components already provide their own unique keys.
> Use elem.key from filter elements

- docs/List.md
jsonexport is a JSON to CSV converter.  Not a CSV to JSON converter. Minor note but it is confusing as written.
> Fix  typo in jsonexport

- yarn.lock
cf https://github.com/advisories/GHSA-78xj-cgh5-2h22
This is not a security vulnerability in react-admin, as the `ip` package is only used in development
```
➜  react-admin git:(fix-ip-dependency) yarn why -R ip
├─ demo@workspace:examples/demo
│  └─ vite@npm:3.2.8 [216a7] (via npm:^3.2.0 [216a7])
│     ├─ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 (via patch:fsevents@~2.3.2#~builtin<compat/fsevents>)
│     │  └─ node-gyp@npm:8.4.1 (via npm:latest)
│     │     └─ make-fetch-happen@npm:9.1.0 (via npm:^9.1.0)
│     │        └─ socks-proxy-agent@npm:6.1.1 (via npm:^6.0.0)
│     │           └─ socks@npm:2.6.2 (via npm:^2.6.1)
│     │              └─ ip@npm:1.1.9 (via npm:^1.1.5)
│     └─ rollup@npm:2.79.1 (via npm:^2.79.1)
│        └─ …
```
> Fix vulnerable dev dependency ip

- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Autocomplete accepts TextFieldProps, which allows to override the props of the inner TextField (see https://mui.com/material-ui/api/text-field/). This ability was lost in #9559
> Fix AutocompleteInput ignores TextFieldProps

- docs/FilteringTutorial.md
- docs/Upgrade.md
- docs/useListContext.md
- docs/useListController.md
- examples/demo/src/orders/NbItemsField.tsx
- examples/demo/src/orders/OrderList.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/input/useReferenceParams.ts
- packages/ra-core/src/controller/list/InfiniteListBase.stories.tsx
- packages/ra-core/src/controller/list/ListBase.stories.tsx
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/list/useListParams.ts
- packages/ra-core/src/form/choices/ChoicesContext.ts
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
- packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
The `setFilters` callback returned by `useListController` is debounced by default. This creates numerous WTF issues (e.g. #4189). This default makes sense for the Filter form/button combo, but not for the other filters.
Besides, the `setFilters` returned by other controllers (`useList`, etc) isn’t debounced by default.
Make the `setFilters` default to `debounce=false`. Force the debounce in `FilterForm`.
Also, revert #9639 as these explanations are no longer necessary
> Remove list's setFilters default debounce

- packages/ra-core/src/dataProvider/combineDataProviders.spec.ts
- packages/ra-core/src/dataProvider/combineDataProviders.ts
Closes #9675
The current implementation doesn't work with dataProvider methods with more than 2 parameters.  According to documentation, the method parameter format is not strictly typed, so it is possible to add as many params as needed and then guess why combineDataProviders doesn't work
> [WIP] add use of rest parameters in combineDataProviders

- packages/ra-ui-materialui/src/input/ReferenceInput.tsx
Since #9637, using `<ReferenceInput validate>` fails at runtime. this is unexpected
Fail at build time instead.
This may break existing apps, so I'm pulling against `next`.
> [TypeScript] Forbid `<ReferenceInput validate>`

- packages/ra-ui-materialui/src/button/SortButton.tsx
Fix https://github.com/marmelab/react-admin/issues/9692
> Fix `<SortButton>` should use the provided `resource` prop to build its label

- packages/ra-ui-materialui/src/input/ReferenceInput.tsx
Since #9637, users see an error in production while the app isn't broken
Only throw in development.
> Fix `<ReferenceInput>` throws a recoverable error in production

- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
We have a rather large form, in which we for optimization reasons unmount parts of the form when not visible. This doesn't work to well with `<ArrayInput />` however, which clears all state (errors, touched, etc.) when it is unmounted, which both means that the general valid/invalid state of the form is no longer correct.
To reproduce:
1. Setup a react-admin project with an `<ArrayInput />` that can be unmounted and some field that can have errors as child
2. Open, enter an invalid value, try to save, field gets marked as error
3. Trigger unmounting and remounting of `<ArrayInput />`
4. The error is gone, despite the value still being invalid
Here is a reproducible example: https://stackblitz.com/edit/github-ntzyud-hb8uu4?file=src%2Fposts%2FPostEdit.tsx (note that tabbed forms have a …
> Keep errors and other state on ArrayInput unmount

- docs/Search.md
- docs/SearchWithResult.md
Search and SearchWithResult components now ignore the `historySize` and `options` props
Update the doc
> [Doc] Update doc for Search and SearchWithResult

- docs/Layout.md
When mentioning custom themes, the Layout doc points to the AppTheme page. The custom theme is a section in this page: https://marmelab.com/react-admin/AppTheme.html#writing-a-custom-theme 
Update the link to include the anchor.
> [Doc] Fix Layout doc links to wrong anchor

- docs/Upgrade.md
> [Doc] Fix upgrade guide suggest using defaultProps override in theme for react-admin components

- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/useSupportCreateSuggestion.tsx
> Fix `<AutocompleteInput createLabel>`

- docs/SimpleShowLayout.md
- packages/ra-ui-materialui/src/detail/SimpleShowLayout.stories.tsx
- packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx
Writing a custom show layout by hand is cumbersome, because we have to decorate each field with `<Labeled>`.
Allow users to nest `<SimpleShowLayout>` of various `direction`.
```jsx
export const BookShow = () => (
<Show>
<SimpleShowLayout>
<TextField source="title" />
<TextField source="summary" />
<SimpleShowLayout
direction="row"
sx={{
padding: 0,
'& .ra-field-id': { width: 50 },
'& .ra-field-author': { width: 150 },
}}
>
<TextField source="id" />
<TextField source="author" />
<NumberField source="year" />
</SimpleShowLayout>
</SimpleShowLayout>
</Show>
);
```
> Add ability to set `<SimpleShowLayout direction>`

- docs/ReferenceManyToManyInput.md
Explain in documentation that `<ReferenceManyToManyInput>` cannot be used as a Filter.
> [Doc] Update `<ReferenceManyToManyInput>` doc

- docs/Upgrade.md
- examples/simple/src/posts/PostList.tsx
- examples/simple/src/users/UserEditEmbedded.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
This undocumented feature forces us to use a `cloneElement`, which we try to avoid.
> Remove props injection in `<Datagrid expand>` components

- docs/CreateDialog.md
- docs/Datagrid.md
- docs/EditableDatagrid.md
- docs/InfiniteList.md
- docs/List.md
- docs/Upgrade.md
- docs/useDeleteMany.md
- examples/simple/src/posts/PostList.tsx
- examples/simple/src/posts/ResetViewsButton.tsx
- examples/simple/src/tags/TagEdit.tsx
- packages/ra-ui-materialui/src/button/BulkDeleteButton.tsx
- packages/ra-ui-materialui/src/button/BulkExportButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx
- packages/ra-ui-materialui/src/list/BulkActionsToolbar.tsx
- packages/ra-ui-materialui/src/list/Empty.tsx
- packages/ra-ui-materialui/src/list/InfiniteList.tsx
- packages/ra-ui-materialui/src/list/List.stories.tsx
- packages/ra-ui-materialui/src/list/List.tsx
- packages/ra-ui-materialui/src/list/ListToolbar.tsx
- packages/ra-ui-materialui/src/list/ListView.tsx
Wenever we use `cloneElement`, developers find it hard to swap the component with their own as they don't know which props are injected. 
Remove `cloneElement` and make child elements pull data from the context. 
Applied to List components. 
Note: there are still some `cloneElement` to support the deprecated `<List filters={<Filter>...</Filter>} />` syntax (instead of `<List filters={[...]} />`). The discussion is open to determine if we should remove those. 
To force a List view to display a Create button even though the corresponding resource doesn't have a `create` component, pass a custom actions component to the List component:
```diff
-import { List } from 'react-admin';
+import { List, ListActions } from 'react-admin';
const PostList = () => (
-   <List hasCreate>
+   <List …
```
> Remove `cloneElement` in list actions and bulk actions

- docs/AccordionForm.md
- docs/EditTutorial.md
- docs/Form.md
- docs/LongForm.md
- docs/SimpleForm.md
- docs/TabbedForm.md
- docs/Upgrade.md
- docs/WizardForm.md
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/Form.stories.tsx
- packages/ra-core/src/form/Form.tsx
- packages/ra-core/src/form/WarnWhenUnsavedChanges.ts
- packages/ra-core/src/form/index.ts
- packages/ra-core/src/form/useAugmentedForm.ts
The reimplentation of the `warnWhenUnsavedChanges` feature with react-router's `useBlocker` in #9657 created a breaking change. As `useBlocker` throws an error when not called in a DataRouter, and since we cannot call hooks conditionally, this meant that react-admin MUST be used inside a data router.
By moving the `warnWhenUnsavedChanges` logic from the `useAugmentedForm` hook to a custom component, we can now call the component conditionally - and avoid calling it when not inside a data router.
> Fix react-admin requires custom routers to be data routers

- docs/AuthRBAC.md
In ra-enterprise RBAC package documentation, we now mention the ability to define permissions on an array of resources
> [Doc] Update RBAC to mention ability to define permissions on an array of resources

- packages/ra-ui-materialui/src/button/Button.stories.tsx
- packages/ra-ui-materialui/src/button/Button.tsx
Ref https://github.com/marmelab/react-admin/issues/9706#issuecomment-1988799584
> Add ability to set Button default props via theme

- docs/ReferenceManyField.md
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
`<ReferenceManyField>` does not support `queryOptions`
Add `queryOptions` support for `<ReferenceManyField>` and  `useReferenceArrayFieldController`
Closes #9669
> Add queryOptions support for ReferenceManyField

- docs/List.md
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/list/useInfiniteListController.ts
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/list/useRecordSelection.spec.tsx
- packages/ra-core/src/controller/list/useRecordSelection.ts
- packages/ra-core/src/controller/list/useUnselect.ts
- packages/ra-core/src/controller/list/useUnselectAll.ts
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
> Disable all store interactions for a list with storeKey set to false (sort, pagination, filters and now also selection state).

- packages/ra-core/src/auth/useGetIdentity.ts
Fix `useGetIdentity` regression introduced by #9644 that makes it returns a `defaultIdentity` even when an `authProvider` supporting `getIdentity` is provided
> Fix `useGetIdentity` regression

- packages/ra-core/src/controller/field/ReferenceFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.stories.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.tsx
- packages/ra-core/src/controller/field/ReferenceFieldContext.tsx
- packages/ra-core/src/controller/field/index.ts
- packages/ra-core/src/controller/field/useReferenceFieldController.ts
- packages/ra-core/src/core/ResourceContextProvider.tsx
- packages/ra-core/src/util/useFieldValue.ts
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
While working on the alternative UI libraries demos, we had to re-implement all the reference fields and inputs logic.
Add core headless versions for these components
This PR introduces only the `ReferenceFieldBase`.
> Introduce ReferenceFieldBase

- docs/JsonSchemaForm.md
The `JsonSchemaForm` doc is not up to date with the EE one.
Backport EE doc to OSS
> [Doc] Improve `JsonSchemaForm` doc

- .github/workflows/test.yml
- docs/Admin.md
- docs/_config.yml
**problem**
The CI does not fail when we forget to wrap code snippets with `{% raw %}`/`{% endraw %}`
**solution**
- Add a CI job to build the Jekyll doc
- Change the Jekyll config to fail on Liquid errors
> chore: add a doc check ci job

- docs/AuthRBAC.md
Update the OSS doc following an update in ra-rbac docs
> [Doc] Better explain the difference between the built-in actions in ra-rbac

- docs/SimpleForm.md
Minor correction to SimpleForm page to update RichTextInput reference
> [Doc] Fix `<RichTextInput>` import in SimpleForm doc

- docs/Search.md
- docs/SearchWithResult.md
RA-Enterprise doc for `ra-search` was update in `<Search>` and `<SearchWithResult>` parts (to introduce `queryOptions`).
Update OSS documentation.
> [Doc] Update `ra-search` doc for `<Search>` and `<SearchWithResult>` to introduce `queryOptions`

- Makefile
- examples/data-generator/src/categories.ts
- examples/data-generator/src/commands.ts
- examples/data-generator/src/customers.ts
- examples/data-generator/src/finalize.ts
- examples/data-generator/src/index.ts
- examples/data-generator/src/invoices.ts
- examples/data-generator/src/products.ts
- examples/data-generator/src/reviews.ts
- examples/data-generator/src/types.ts
- examples/data-generator/src/utils.ts
- examples/demo/package.json
- examples/demo/src/data-generator-retail.d.ts
- examples/demo/src/fakeServer/graphql.ts
- examples/demo/src/fakeServer/rest.ts
- examples/demo/src/orders/OrderList.tsx
- examples/demo/src/types.ts
- examples/demo/src/visitors/Aside.tsx
- package.json
- yarn.lock
When using the `data-generator-retail` package, the generated is not typed, making consumers declare the generated types themselves.
Provide types
Wait for next version of `json-graphql-server` or the GQL demo won't work
> Add better types to data-generator

- packages/ra-core/src/auth/LogoutOnMount.ts
- packages/ra-core/src/auth/index.ts
- packages/ra-core/src/core/CoreAdminRoutes.spec.tsx
- packages/ra-core/src/core/CoreAdminRoutes.tsx
`<Admin requireAuth>` is used to forbid anonymous anonymous users to see the UI while the auth status is being checked.
But anonymous users should be able to see the custom routes with no layout, e.g. to let them access a registration page, or a "forgot my password" page.
This currently doesn't work. `CoreAdminRoutes` does display custom routes with no layout when accessed by an anonymous user, but it redirects anonymous users to login immediately.
`CoreAdminRoutes` calls `checkAuth` with `logoutOnFailure` set to true, so anonymous users will be logged out even when accessing a custom route with no layout. 
https://github.com/marmelab/react-admin/blob/6b78433893e0f7fc48db69c63a529b3c2e3d5c60/packages/ra-core/src/core/CoreAdminRoutes.tsx#L41-L49
- Do not log users out on auth check failure …
> Fix `<Admin requireAuth>` forbids access to custom routes with no layout

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
See e.g. https://github.com/react-admin/ra-enterprise/actions/runs/8865814086
> Fix CI action warnings

- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
`<SimpleList data={data}>` always renders an empty list regardless of the data. 
Test the [ra-ui-material-ui/list/simplelist/basic](https://react-admin-storybook-git-next-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-list-simplelist--basic) story to see the bug.
Even when the `data` prop is set, this condition forces the rendering of the empty component because `total` is also undefined. 
https://github.com/marmelab/react-admin/blob/a402c381f52a29aafa23708d9c9468c312e4ccd6/packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx#L123-L129
The condition is different in `<Datagrid>`:
https://github.com/marmelab/react-admin/blob/a402c381f52a29aafa23708d9c9468c312e4ccd6/packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx#L219-L225
Remove the test on `total` in `<SimpleList>` …
> Fix `<SimpleList>` always returns empty when controlled

- docs/Upgrade.md
- examples/demo/src/dataProvider/graphql.ts
- packages/ra-data-graphql-simple/README.md
- packages/ra-data-graphql-simple/src/index.ts
- packages/ra-data-graphql/README.md
- packages/ra-data-graphql/src/index.ts
Setting up the GQL dataProviders is cumbersome as the builders return a promise. However, this was only kept for backward compatibility as intropection is now done on the fly.
Make builders return the dataProvider synchronously.
> Simplify GQL dataProviders

- packages/ra-core/src/controller/usePrevNextController.ts
- packages/ra-ui-materialui/src/button/PrevNextButtons.tsx
- packages/ra-ui-materialui/src/field/BooleanField.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/layout/Menu.stories.tsx
Following the advice at https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment, I fixed the few named imports from `@mui/material-icons` and replaced them with default imports for individual icons.
The results are spectacular. The `npx jest` command now takes a fraction of the time. 
On my laptop:
* Before: 118s
* After: 41s
On the CI:
* Before: 4m58s
* After: 3m28s
> [Dev] Speed up unit tests by not using MUI Icons barrel files

- packages/ra-ui-materialui/src/button/BulkUpdateButton.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx
The "Select all" checkbox in the `<Datagrid>` header doesn't have the label on the correct element
```html
<span class="..." aria-label="Select all">
<input class="..." type="checkbox" data-indeterminate="false">
```
```html
<span class="...">
<input class="..." type="checkbox" data-indeterminate="false" aria-label="Select all">
```
Check out the BulkUpdateButton story. I also added a unit test.
> Fix Datagrid uses wrong element for "Select All" label

- docs/TranslationLocales.md
I created a new repository for Italian translation because the previous one (https://github.com/stefsava/ra-italian) is obsolete and it seems to be no longer maintained, so I updated the reference in `docs/TranslationLocales.md`.
Nothing more than this.
> docs: update italian locale reference

- docs/Fields.md
- examples/demo/src/visitors/ColoredNumberField.tsx
- examples/demo/src/visitors/MobileGrid.tsx
- examples/demo/src/visitors/VisitorList.tsx
- packages/ra-ui-materialui/src/field/NumberField.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
- packages/ra-ui-materialui/src/field/types.ts
- packages/ra-ui-materialui/src/list/datagrid/DatagridCell.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridConfigurable.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
- packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.stories.tsx
React 19 removes support for `defaultProps` and React 18.3 display warnings about it.
The temporary solution is to introduce some other static props for `textAlign` and `sortable`
Closes #9815
> Fix warning about defaultProps in React 18.3

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
No story exists to demonstrate a custom `<DatagridRow>`
Add a story
> Add a story of a custom `<DatagridRow>`

- packages/ra-core/src/core/useResourceDefinition.ts
**Problem**
`useResourceDefinition` used to return `Omit<ResourceDefinition, 'name'>` which is wrong (because `name` is actually present in the returned value most of the time) and causes issues in existing code using that hook.
**Solution**
Change the return type to be `ResourceDefinition`.
> [TypeScript] Fix `useResourceDefinition` return type

- docs/Upgrade.md
- docs/Validation.md
- packages/ra-core/src/controller/create/useCreateController.spec.tsx
- packages/ra-core/src/controller/create/useCreateController.ts
- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/Form.stories.tsx
- packages/ra-core/src/form/useNotifyIsFormInvalid.ts
When validating server side, you can’t provide a global error message and react-admin displays a default non customizable one.
In some cases (depending on the React version) users could use the error's `message` field to render a custom message in the notification, but due to a race condition between the 2 notifications, it would not always work.
In `useCreateController` and `useEditController`, check if there are validation errors and if we are in pessimistic mode, and don't notify in this case (as it will be done by `useNotifyIsFormInvalid`).
In `useNotifyIsFormInvalid` notify with the `root.serverError` message if available (otherwise fall back to 'ra.message.invalid_form' like currently).
> Fix race condition between http error notification and server-side validation error notification

- .github/workflows/test.yml
Parallelize the CI steps to avoid rebuilding the project several times. This should reduce the total number of CI minutes consumed for each build, at the price of a slightly longer build (because we need to reinstall yarn dependencies).
Build time
| -- | -- |
| 4m 35s | 5m 38s |
Total build time
| -- | -- |
| 22m 08s | 16m 17s |
> Optimize CI

- docs/Upgrade.md
- packages/ra-core/src/auth/AuthContext.tsx
- packages/ra-core/src/auth/useAuthProvider.ts
- packages/ra-core/src/auth/useCheckAuth.ts
- packages/ra-core/src/auth/useGetPermissions.ts
- packages/ra-core/src/auth/useLogin.ts
- packages/ra-core/src/auth/useLogout.ts
- packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
- packages/ra-core/src/core/CoreAdminContext.tsx
Fixes BC introduced by https://github.com/marmelab/react-admin/pull/9760#discussion_r1605238420
> Fix `useAuthProvider` may return `undefined` when no `authProvider` is available

- packages/ra-core/src/controller/create/useCreateController.ts
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/controller/saveContext/useMutationMiddlewares.ts
- packages/ra-core/src/controller/saveContext/useRegisterMutationMiddleware.spec.tsx
- packages/ra-core/src/dataProvider/useCreate.spec.tsx
- packages/ra-core/src/dataProvider/useCreate.stories.tsx
- packages/ra-core/src/dataProvider/useCreate.ts
- packages/ra-core/src/dataProvider/useUpdate.optimistic.stories.tsx
- packages/ra-core/src/dataProvider/useUpdate.pessimistic.stories.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdate.undoable.stories.tsx
By the time optimistic and undoable mutations dataProvider calls are really executed, the calling component might have been unmounted leading to the middlewares being unregistered and hence, not applied.
When the mutation is called, keep the current callbacks in a closure
> Refactor middlewares to handle optimistic cases

- packages/react-admin/package.json
- yarn.lock
With `npm`, react-admin v5 requires React 18.0.0... and no other version. 
Relax peer dependency of the `react-admin` package
> Fix React requirement is too strict on npm

- packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
- packages/ra-core/src/controller/input/useReferenceInputController.ts
- packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx
- packages/ra-ui-materialui/src/input/ReferenceInput.stories.tsx
When rendering a ReferenceInput inside an ArrayInput, the current value is never fetched.
The current value is grabbed by `useReferenceInputController` as follows:
```jsx
const currentValue = useWatch({ name: source });
```
The problem is, the source is no longer modified by the parent ArrayInput. So when using:
```jsx
<ArrayInput source="basket">
<ReferenceInput source="product_id" reference="products" />
<NumberInput source="quantity" />
</ArrayInput>
```
ReferenceInput will get the current value from `product_id` instead of `basket.0.product_id`.
cf https://github.com/marmelab/react-admin/blob/51e8a7c1ac90011b83d8cd8d2c4e39d9d2c4effa/packages/ra-core/src/controller/input/useReferenceInputController.ts#L71
Use the `useWrappedSource` hook
> Fix ReferenceInput in ArrayInput

- docs/NextJs.md
Remove trailing slash after `v1`
- ❌ `${process.env.SUPABASE_URL}/rest/v1/${requestUrl}`
- ✅ `${process.env.SUPABASE_URL}/rest/v1${requestUrl}`
If this is not removed the resulting URL contains a double slash before the endpoint, e.g
`https://abc123.supabase.co/rest/v1//users?offset=0&limit=10&order=id.asc`
> docs: remove trailing slash on url

- packages/ra-ui-materialui/src/field/TextField.spec.tsx
- packages/ra-ui-materialui/src/field/TextField.tsx
Rationale: `JSON.stringify` displays a 'technical' representation of an object, while `toString` is more optimized to display a string representation of its content (e.g. when it is an Array or a Date).
This also has the benefit of keeping the same behavior as RA v4.
> Fix `<TextField>` should call `toString` instead of `JSON.stringify` for non-string values

- packages/ra-core/src/dataProvider/useDelete.spec.tsx
- packages/ra-core/src/dataProvider/useDelete.ts
The `useDelete` hook does not delete the record if its id is zero. However, a record with 0 as identifier could exist.
Introduced by #9741 [here](https://github.com/marmelab/react-admin/pull/9741/files#diff-cd53d268c8805400093877effffadd54241b534266a80e1ab0bed1646cf51c59R208)
Allow deletion of record with id 0
> Fix `useDelete` doesn't delete record if its id is zero

- packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
This input didn't leverage `recordRepresentation` for the choices texts.
> Update `<SelectArrayInput>` to use default record representation when used inside `<ReferenceArrayInput>`

- packages/ra-ui-materialui/src/AdminUI.tsx
- packages/ra-ui-materialui/src/layout/Error.tsx
As we can see in the story `react-admin`/`Admin`/`DefaultError`, the background of the error boundary doesn't take full height of the page.
___
---
---
> Make ErrorBoundary take fullHeight of the page

- packages/ra-ui-materialui/src/input/SelectInput.tsx
When clicking the reset button on a `<SelectInput resettable>`, the value comes back to the default one instead of the empty value. 
https://github.com/marmelab/react-admin/assets/99944/9bfbc03d-2f9a-4037-b636-2d855832abc9
> Fix `<SelectInput resettable>` does not reset the value

- packages/ra-ui-materialui/src/layout/AppBar.stories.tsx
- packages/ra-ui-materialui/src/layout/Error.tsx
- packages/ra-ui-materialui/src/layout/Layout.stories.tsx
- packages/ra-ui-materialui/src/list/List.spec.tsx
- packages/ra-ui-materialui/src/list/ListView.tsx
The `<Error>` component is designed for runtime errors. We shouldn't use it for fetch errors. Besides, developers often want to customize the Error component. It wan't possible to do so with List. Finally, both `Error` and `List` set the page title, which resulted in an incorrect title.
This also reverts #9904, which did nothing.
> Fix `<List>` should not render Error component on fetch error

- packages/ra-core/src/core/CoreAdminUI.tsx
Supersedes #9904
How to test: In the storybook, got to React-admin > Admin > Default Error
> Fix default Error background in global ErrorBoundary

- cypress/e2e/mobile.cy.js
- packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
When filters with a complex object as defaultValue the "empty value" was not considered empty by the UI. This commit ensure we don't display empty filters on the UI.
Refs: #9893
> Fix filters with complex object are not removed from the UI

- packages/ra-core/src/core/SourceContext.tsx
- packages/ra-core/src/core/useWrappedSource.ts
- packages/ra-core/src/form/FormDataConsumer.spec.tsx
- packages/ra-core/src/i18n/TestTranslationProvider.tsx
- packages/ra-core/src/i18n/TranslatableContext.ts
- packages/ra-core/src/i18n/useTranslatable.spec.ts
- packages/ra-core/src/i18n/useTranslatable.ts
- packages/ra-core/src/i18n/useTranslateLabel.ts
- packages/ra-core/src/util/useFieldValue.spec.tsx
- packages/ra-core/src/util/useFieldValue.ts
- packages/ra-ui-materialui/src/field/ArrayField.tsx
- packages/ra-ui-materialui/src/field/TranslatableFields.tsx
- packages/ra-ui-materialui/src/field/TranslatableFieldsTabContent.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx
- packages/ra-ui-materialui/src/input/TranslatableInputsTabContent.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
- test-setup.js
`<ArrayInput>` and `<SimpleFormIterator>` are still cloning their children. Besides, `<SimpleFormIterator>` throws an Error when used without a source prop.
Migrate both components to support the `SourceContext` and no longer require cloning their children.
This is a BC so this needs to be done before the v5 release.
> `<ArrayInput>` uses `SourceContext` instead of cloning children

- packages/create-react-admin/src/generateAppTestFile.ts
1. Build create-react-admin and install the CLI
```sh
make build-create-react-admin install
```
2. Run the CLI from another directory
```sh
../react-admin/node_modules/.bin/create-react-admin
```
3. Select `ra-data-fakerest`, fake `authProvider` and `yarn`
4. Run the tests
```sh
yarn test
```
> Fix create-admin-app generated tests

- packages/ra-core/src/form/useFormGroup.spec.tsx
- packages/ra-core/src/form/useFormGroup.ts
When a component reads different form group dynamically (e.g the `NextButton` in `WizardForm`), it always receives the first group state.
Include the group name in the state update effect dependencies.
> Fix useFormGroup does not update when its group changes

- packages/ra-ui-materialui/src/list/List.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
When using a React element as `label` for a field, the datagrid header tooltip displays `Sort by [object Oject] descending`.
Fallback to the default inferred label
> Fix DatagridHeader Tooltip when using React element as a field label

- packages/ra-core/src/controller/list/useListParams.spec.tsx
- packages/ra-core/src/controller/list/useListParams.ts
- yarn.lock
addressing https://github.com/marmelab/react-admin/issues/9932
remove unnecessary query param sanitisation to keep any custom params in the url.
run `make test`
> Preserve extra query parameters in List view

- packages/ra-core/src/controller/field/useReferenceFieldController.ts
- packages/ra-core/src/routing/index.ts
- packages/ra-core/src/routing/types.ts
- packages/ra-core/src/routing/useGetPathForRecord.ts
- packages/ra-core/src/routing/useGetRouteForRecord.ts
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
`<ReferenceField>` renders a link to the edit view by default. When a resource has a show view but no edit view, and the developer hasn't specified the `link` type, a `<ReferenceField>` targeting that resource doesn't show any link. 
Also, when there is a conflict between the `<ReferenceField link>` and the associated `<Resource>` (e.g. when the developer specified that the `ReferenceField` should link to the `edit` view even though the `Resource` doesn't defined such a view), react-admin ignores the developer choice and removes the link. Yet the developer may want to link to a nested `CustomRoute` that matches the `link`. 
Make `<ReferenceField>` default to `show` when `link` is undefined and there are both an edit and a show view. 
Make `<ReferenceField>` smarter so that it can link to …
> Update `<ReferenceField>` to render a link to the show view when relevant

- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
`useUpdate` throws an error when record id is a valid falsy value such as zero
Introduced in https://github.com/marmelab/react-admin/pull/9741
Fix the condition to check only for `null` or `undefined`
> Fix useUpdate throws an error when record id is a valid falsy value such as zero

- docs/Routing.md
Our documentation about using React-Admin in a sub path is wrong and can lead to Not Found errors
Fix the documentation
> Update Routing Documentation Regarding `basename`

- docs/Admin.md
- docs/Routing.md
Our documentation about using React-Admin in a sub path is wrong and can lead to Not Found errors
Fix the documentation
> Update routing documentation

- packages/create-react-admin/src/generateAppTestFile.ts
- packages/ra-core/src/dataProvider/useDelete.pessimistic.stories.tsx
- packages/ra-core/src/dataProvider/useDelete.spec.tsx
> Fix flaky tests

- packages/ra-data-fakerest/src/index.ts
> Fix logging of queries in ra-data-fakerest

- examples/demo/src/reviews/ReviewListDesktop.tsx
When clicking on a review to edit it in the demo, the page scrolls back to the top. This is because, scrolling to the top of the page when navigating is the default.
Don't use the default redirect and implement it specifically for this page.
- run the demo
- navigate to the review list
- set its page size to `50`
- scroll down
- click on a review
=> Observe the page does not scroll to the top anymore
> Fix ReviewList scrolls to top when editing a review

- docs/ReferenceArrayInput.md
- packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
> Fix `<ReferenceArrayInput>` should forward `queryOptions` to `getMany`

- packages/ra-core/src/dataProvider/useGetManyReference.spec.tsx
- packages/ra-core/src/dataProvider/useGetManyReference.ts
The discriminated union of the return type by state doesn't work for this hook because of `Omit`. This `Omit` is an error and shouldn't be here. Removing it solves the problem.
| Before | After | 
| --- | --- |
| <img width="569" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/59b90c12-6fca-4c36-b887-a1cb95fe9c1c"> | <img width="522" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/cc5eead0-1c5b-4028-b586-ce8c339c2b28">|
This problem was introduced in dc1938768b58addce2b1dc8cce63028981b19537
> [TypeScript] Fix useGetManyReference return type

- docs/Title.md
- packages/ra-ui-materialui/src/layout/PageTitle.tsx
- packages/ra-ui-materialui/src/layout/PageTitleConfigurable.tsx
- packages/ra-ui-materialui/src/layout/Title.tsx
- packages/ra-ui-materialui/src/layout/TitlePortal.stories.tsx
This addresses https://github.com/marmelab/react-admin/issues/8776
Testing:
Added storybook entry
> Allow <Title /> to be nonConfigurable

- packages/ra-core/src/core/SourceContext.tsx
- packages/ra-core/src/i18n/useTranslateLabel.spec.tsx
- packages/ra-core/src/i18n/useTranslateLabel.stories.tsx
- packages/ra-ui-materialui/src/Labeled.stories.tsx
- packages/ra-ui-materialui/src/detail/SimpleShowLayout.spec.tsx
- packages/ra-ui-materialui/src/detail/SimpleShowLayout.stories.tsx
- packages/ra-ui-materialui/src/form/SimpleForm.stories.tsx
The default SourceContext introduced by 4d9820d5931c3eb992010035c23c00935f194047 breaks default field labels.
Closes #9965
> Fix `<SimpleShowLayout>` uses a wrong translation key for field labels

- packages/ra-core/src/core/CoreAdminUI.tsx
- packages/ra-data-fakerest/src/index.ts
- packages/ra-data-fakerest/tsconfig.json
- packages/ra-data-graphql/src/buildApolloClient.ts
- packages/ra-data-graphql/src/index.ts
- packages/ra-data-graphql/src/introspection.ts
- packages/ra-data-graphql/tsconfig.json
- packages/ra-data-json-server/src/index.ts
- packages/ra-data-json-server/tsconfig.json
- packages/ra-data-localforage/tsconfig.json
- packages/ra-data-localstorage/src/index.ts
- packages/ra-data-localstorage/tsconfig.json
- packages/ra-data-simple-rest/src/index.ts
- packages/ra-data-simple-rest/tsconfig.json
Since third-party data providers stem from ours, we should provide data providers that compile with strictNullChecks
> [TypeScript] Fix data provider packages export non-strict types

- packages/ra-ui-materialui/src/field/ReferenceField.tsx
This confusing type was introduced by https://github.com/marmelab/react-admin/commit/43f8e72461869fd6779c00488d52dc36ac1c8183#diff-bcb8a95735be07f07a5fe05f577626392756002e0c6350fcc0e1e8a17dbea8d9, at a moment when `source` was optional. It's no longer necessary.
> [TypeScript] Fix ReferenceField Props type is confusing

- docs/Upgrade.md
Codemod are now in CJS but the samples in the doc are in JS
Update codemod snippets according to react-query doc
> [DOC] Fix react-query codemod snippets

- packages/ra-core/src/dataProvider/useCreate.ts
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-core/src/dataProvider/useDeleteMany.ts
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdate.undoable.stories.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
Although we did include `isLoading` in the mutations results to avoid breaking changes, we did not update the types.
Update the mutations results types
> Update mutations results types to include `isLoading`

- packages/ra-core/src/controller/list/useListController.ts
When passing an array of inputs to the `filter` prop, the list component behave weirdly and developers might loose time finding that they should have used `filters` instead.
Check that developers have pass either an element or an array of elements and throw an error
- Open the simple example `PostList` file and change `filters` to `filter`in `PostListDesktop`
- Run the example
> Fix `filter` vs `filters` warning

- packages/ra-ui-materialui/src/auth/Login.stories.tsx
- packages/ra-ui-materialui/src/auth/Login.tsx
This is a pull request for issue #9916. It adds an avatarIcon property to the Login component w/ a default of the Lock icon. This allows for overriding the icon without having to copy the complete component.
Ideally, this would be included as part of a v4 point release. This is my first pull request, so please let me know if there is anything else needed.
--
Fix https://github.com/marmelab/react-admin/issues/9916
> Add avatar icon as login property w/ default.

- packages/ra-ui-materialui/src/field/WrapperField.spec.tsx
- packages/ra-ui-materialui/src/field/WrapperField.tsx
`WrapperField` [documentation](https://marmelab.com/react-admin/WrapperField.html) marks `source` props as not required, however changes in #9620 makes it required. This PR reverts the change for `WrapperField` only
> Fix(WrapperField): source props should not be required

- .github/pull_request_template.md
- packages/ra-ui-materialui/src/layout/PageTitleConfigurable.tsx
Reintroduce changes from #9930 and #9931 that somehow got lost on `master`
> [no ci] [chore] Reintroduce changes from #9930 and #9931

- docs/Remix.md
> Fix Remix Documentation

- docs/EditableDatagrid.md
I found some issues in the doc
Fix them
> [DOC] improve `<EditableDatagrid>` doc

- examples/crm/src/contacts/TagsListEdit.tsx
- packages/ra-core/src/dataProvider/useGetMany.spec.tsx
- packages/ra-core/src/dataProvider/useGetMany.ts
- packages/ra-core/src/dataProvider/useGetManyAggregate.ts
- packages/ra-core/src/dataProvider/useGetOne.spec.tsx
- packages/ra-core/src/dataProvider/useGetOne.ts
- packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts
- packages/ra-core/src/types.ts
- packages/ra-data-localforage/src/index.ts
TypeScript complains when `useGetOne` is called with an undefined `id`. This is fine, except when using the `enabled` option:
This is a consequence of the strictNullCheck flag in ra-core. 
1. Use type overloads to allow optional id when enabled is specified. This forces the developer to set teh enabled flag when id may be undefined - not ideal.
2. Change input type for the data provider hooks to allow an undefined id, and set the enabled flag in the hook accordingly. this offers a better DX as TypeScript won't complain but user land code won't break either. 
We choose solution 2.
> [TypeScript] Fix useGetOne and useGetMany params type when id param is undefined

- docs/Datagrid.md
- docs/Upgrade.md
> [Doc] Fix `<Datagrid>` standalone usage misses required `resource` prop

- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx
If you have both a `<FilterLiveSearch>` and a `<FilterButton>`, clicking on 'Remove all filters' in the `<FilterButton>` doesn't clear the `<FilterLiveSearch>` text input (although the filters are indeed cleared).
Similarily, updating the filter value for the field targeted by `<FilterLiveSearch source>` doesn't update the `<FilterLiveSearch>` text input (although the filter is applied).
Use `values` instead of `defaultValues` when declaring the form for `<FilterLiveSearch>`, which makes it reactive.
- 2 unit tests are added
- 1 story is added (`WithFilterButton`)
> Fix `<FilterLiveSearch>` should react to filter values change

- examples/crm/src/deals/DealCreate.tsx
- examples/crm/src/deals/DealShow.tsx
Change `start_at` label for deals.
Set `start_at` input as read-only.
> Feat(crm): Wording start deal

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fixes #9993
1. Navigate to [this story](https://react-admin-storybook-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-autocompleteinput--create-label)
2. Fill the input with a choice that does not exist
3. Click the clear button -> it should delete the new choice
4. Fill the input again with a choice that does not exist
5. Click the clear button -> it should now delete the new choice
> fix `<AutocompleteInput>` clear button does not clear new choice 

- packages/ra-core/src/dataProvider/defaultDataProvider.ts
- packages/ra-core/src/dataProvider/testDataProvider.ts
defaultDataProvider behaviour changed in V5. the change was intended to just support the tests. this affect the end users if they use the exported `defaultDataProvider` in their implementation which means one extra migration step for them and one extra migration documentation entry point react-admin team has to add.
Implement testing-related changes for the `defaultDataProvider` in the right place `testDataProvider` and revert the `defaultDataProvider` to its original behaviour (which is dummy responses but at least it doesn't throw)
I implemented the refactoring in 30 seconds, then I spent almost half an hour trying to make the `defaultDataProvider` work with the `DataProvider` type but I failed. I would appreciate if one of the core members can explain to me what I miss here or how to …
> separate test and default data providers

- docs/Buttons.md
In the OSS doc for buttons, we (briefly) document EditButton and CreateButton
https://marmelab.com/react-admin/Buttons.html
But there is no mention of the Dialog alternatives (EditInDialog and CreateInDialog).
It’s a pity, because these components have their own doc chapter.
https://marmelab.com/react-admin/EditInDialogButton.html
https://marmelab.com/react-admin/CreateInDialogButton.html
Add a reference to the Dialog alternative
- ~[ ] The PR targets `master` for a bugfix, or `next` for a feature~
> [Documentation] Mention dialogs in Buttons doc

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- docs/CheckboxGroupInput.md
- docs/RadioButtonGroupInput.md
- docs/SelectArrayInput.md
- docs/SelectInput.md
- packages/ra-core/src/form/choices/useChoicesContext.ts
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
For `SelectInput` and other selection inputs, sometimes the list of options is simply an array of strings. Doing the conversion to an array of option objects isn't intuitive. 
Support string choices by default. 
```jsx
<SelectInput source="gender" choices={['Male', 'Female']} />
```
This concerns the following components:
- `SelectInput`
- `SelectArrayInput`
- `AutocompleteInput`
- `AutocompleteArrayInput`
- `RadioButtonGroupInput`
- `CheckboxGroupInput`
> Update SelectInput to support an array of strings as choices

- docs/Buttons.md
On #10039, a batch with a mistake was applied. 
Wrong applied comment: https://github.com/marmelab/react-admin/pull/10039#discussion_r1687593274
Fix that documentation
> [Doc] Fix wrong link in `CreateButton` usage

- examples/crm/src/companies/CompanyEmpty.tsx
- examples/crm/src/contacts/ContactEmpty.tsx
- examples/crm/src/deals/DealEmpty.tsx
The spacing of the empty components is not the same
Adds a similar gap and modifies the typography
Clear all data and navigate on `Contact`, `Company` or `Deal` pages.
Object.keys(window._database.collections).forEach(key => {window._database.collections[key].items = []})
> Fix(crm): Add concordance between the empty components

- examples/crm/src/deals/DealEdit.tsx
Deleting a deal does not ask for confirm from edit page
Add confirm modal when deleting a deal
Try to delete a deal from edit page
> Fix(crm): Ask for confirm when deleting a deal

- examples/crm/src/dataProvider.ts
- examples/crm/src/deals/DealArchivedList.tsx
- examples/crm/src/deals/DealList.tsx
- examples/crm/src/deals/DealShow.tsx
- examples/crm/src/deals/stages.ts
The current Kaban is based on `update_at`, which is problematic because when a position is changed, the map always resets itself first. But we only want to behave when we unarchived a map.
Reset sorting to default index. 
When a deal is unarchived, each index of the current stage is reset. We put the unarchived in first position.
> Fix(crm): Create a custom dataprovider for unarchive deal

- examples/crm/src/deals/DealCard.tsx
- examples/crm/src/deals/DealColumn.tsx
- examples/crm/src/deals/DealEdit.tsx
- examples/crm/src/deals/DealShow.tsx
If the Deal list contains many items and we have to scroll, we lose the scroll position as soon as we open the view or edit popup.
Overloading the scrollToTop option for useRedirection
[Screencast from 2024-07-24 20-43-08.webm](https://github.com/user-attachments/assets/4d0238b8-e68c-4799-b683-9e787f2706f4)
> Feat(crm): Update redirect calls to disable scrolling to top for deals dialogs

- examples/crm/src/contacts/ContactShow.tsx
- examples/crm/src/dashboard/LatestNotes.tsx
- examples/crm/src/dashboard/Welcome.tsx
- examples/crm/src/deals/ContactList.tsx
- examples/crm/src/deals/DealShow.tsx
- examples/crm/src/notes/Note.tsx
- examples/crm/src/notes/NoteCreate.tsx
- examples/crm/src/notes/NoteInputs.tsx
- examples/crm/src/notes/NotesIterator.tsx
- examples/crm/src/notes/note.ts
- examples/crm/src/sales/TransferAdminRole.tsx
- examples/crm/src/tasks/Task.tsx
The new note form is always displayed in deals and contacts. But it has many fields (text, date, temperature, attachment) that push the rest of the content downwards.
Display only the text content field and the submit button, and a link above the submit button allowing to display the other fields
Go on any Contact or Deal show view.
Before 
After
> Feat(crm): Improve UX for Note form + Harmonize application text size

- examples/crm/src/deals/ContactList.tsx
- examples/crm/src/deals/DealCard.tsx
- examples/crm/src/deals/DealColumn.tsx
The company attached to a deal is highlighted by its logo, but the contact isn’t.
Display the avatar before contact name and add a margin between to lighten the interface
Before
After
> Feat(crm): Improve UI for contacts attached to a deal

- examples/crm/src/deals/DealEdit.tsx
When editing a Deal, the save action cause a scroll top.
Add custom mutationOptions for Edit component.
> Fix(crm): Prevent scroll to top when edit and save a Deal

- examples/crm/src/deals/DealCreate.tsx
- examples/crm/src/deals/DealEdit.tsx
Dialogs for Deal CRUD are small
Set dialog titles as h6
> Fix(crm): Set edit and create dialog title for Deal as h6

- examples/crm/src/deals/DealEdit.tsx
- examples/crm/src/deals/DealShow.tsx
In the CRM demo, when I save a deal, I expect the show view to update with the new data.The updated content is first displayed, then removed by the older one, and the, once the update is persisted is shown back.
Use pessimistic mode
Edit a deal
[Capture vidéo du 25-07-2024 17:13:18.webm](https://github.com/user-attachments/assets/daf72f09-aa49-4104-98c1-628326bac653)
> Fix(crm): Use pessimistic update when saving a deal to avoid old data to display

- examples/crm/src/activity/ActivityLogNote.tsx
Uses can make a mistake between see more and load more buttons on activity log
Replace see more button to a see more link
Go to activity log on dashboard or on any company
> Fix(crm): Replace see more button with a link in activity log

- docs/ReferenceManyField.md
When rendering a list of related records in a ReferenceManyField, editing and creating a related element isn’t straightforward. One can use CreateButton, but the user experience is clunky.
Add a “Adding a related record” section, showing the use of CreateInDialog button.
cf [https://react-admin.github.io/ra-enterprise/?path=/story/ra-form-layout-dialogform-createindialogbutton--in-reference-field](https://react-admin.github.io/ra-enterprise/?path=/story/ra-form-layout-dialogform-createindialogbutton--in-reference-field "smartCard-inline")
> [Doc] Mention `CreateInDialog` in `ReferenceManyField` doc

- examples/crm/src/companies/CompanyInputs.tsx
- examples/crm/src/contacts/ContactInputs.tsx
- examples/crm/src/dataProvider.ts
- If I need to reach a contact or a company, I always want to know which colleague is responsible for them.
- Company creation would create an error with activity log
Create or edit a company or a contact
> Fix(crm): sales is now required for contacts and companies

- examples/crm/src/contacts/ContactImportButton.tsx
AdBlock blocked the sample CSV for contact import
Removed `target="_blank"` to the sample download link
Download sample CSV in contact import modal.
> Fix(crm): Removed target="_blank" to the sample download link

- examples/crm/src/dashboard/DealsChart.tsx
- examples/crm/src/dataGenerator/deals.ts
- examples/crm/src/dataProvider.ts
- examples/crm/src/deals/DealCreate.tsx
- examples/crm/src/deals/DealInputs.tsx
- examples/crm/src/deals/DealShow.tsx
- examples/crm/src/types.ts
The deal show view can show labels for fields with no value, providing no information
Open deals show and forms
[Capture vidéo du 26-07-2024 11:28:40.webm](https://github.com/user-attachments/assets/5e1de3be-1369-4578-9480-2b8234f518c1)
> Fix(crm): Hide fields labels when empty in deals show

- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx
The inputs created by `SimpleFormIterator` have a left padding that is hard to remove.
Remove this padding by default. 
| --- | --- |
|<img width="899" alt="image" src="https://github.com/user-attachments/assets/6476a5f2-0f34-40b5-a6ed-d489b8dddc09">| <img width="903" alt="image" src="https://github.com/user-attachments/assets/d4510587-96a9-4c10-abe8-d51905a01ef6"> | 
Open the [Storybook at Ra-ui-materialui / input / SimpleFormIteratir / Basic](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-input-simpleformiterator--basic)
- ~~[ ] The PR includes **unit tests** (if not possible, describe why)~~(visual only)
> Fix `<SimpleFormIterator>` adds a left padding when there is no label

- examples/crm/src/activity/ActivityLogContactNoteCreated.tsx
- examples/crm/src/activity/ActivityLogDealNoteCreated.tsx
- examples/crm/src/companies/CompanyInputs.tsx
- examples/crm/src/dataGenerator/contactNotes.ts
- examples/crm/src/dataGenerator/dealNotes.ts
- examples/crm/src/dataProvider/activity.ts
- examples/crm/src/deals/DealCard.tsx
- examples/crm/src/types.ts
> Fix(crm): Apply suggestions from code review

- examples/crm/src/contacts/ContactAside.tsx
- examples/crm/src/root/defaultConfiguration.ts
- examples/crm/src/types.ts
I can subscribe/unsubscribe a contact to a newsletter but I should edit the contact to know if he is subscribed or not.
In the contact sidebar, display “Subscribed to newsletter” if the toggle is true, don’t display anything if the toggle is false.
Display it after the email, without icon.
Harmonize “Personal info” by adding an icon before the gender.
> Feat(crm): Display gender icon + newseletter info for Contact

- examples/crm/src/dashboard/HotContacts.tsx
Only with a first and last name and an avatar, it's too complicated to remember who is who in the “Hot contacts” list. Know the company of the contact could help me.
In “Hot contacts” section, display the company of the contact.
> Feat(crm): Display company name and title for Hot Contact

- examples/crm/src/companies/CompanyShow.tsx
- examples/crm/src/contacts/ContactAside.tsx
- examples/crm/src/contacts/ContactEdit.tsx
As a user, I want to delete a contact from the company page easily
Add a Delete button at the end of the sidebar of a contact
When the user deletes the contact, and that it comes from the company page, redirect it on the company page else redirect it on the contacts list
Remove “Delete” button on the contact form which is now no longer so necessary
[Screencast from 2024-07-29 17-58-48.webm](https://github.com/user-attachments/assets/bc0d8071-ed96-4401-b52a-5bbc5c757677)
> Feat(crm): Redirect on company page when deleting an user from company

- examples/crm/src/dashboard/TasksList.tsx
- examples/crm/src/deals/DealInputs.tsx
- examples/crm/src/misc/ContactOption.tsx
- examples/crm/src/tasks/AddTask.tsx
As a user, I don’t know how create a task
Add a button secondary “New task” on the homepage that opens the task creation popup with a contacts selector.
Contacts selector is required.
Contacts selector shouldn’t appears on the other popup (edit, creation from the contacts page)
[Screencast from 2024-07-29 19-11-23.webm](https://github.com/user-attachments/assets/ad892a20-fe26-4995-b80d-f61546e32a5e)
> Feat(crm): Allow quick task create from Dashboard

- examples/crm/src/settings/UpdatePassword.tsx
There should not be a client-side validation for the current password (“Current password is incorrect”), this is impossible in the real-life as we should never store passwords in plain text.
Remove validation
> Fix(crm): Remove client-side validation for the current password

- examples/crm/src/companies/CompanyInputs.tsx
- examples/crm/src/contacts/ContactInputs.tsx
- examples/crm/src/deals/DealCreate.tsx
- examples/crm/src/deals/DealEdit.tsx
- examples/crm/src/deals/DealInputs.tsx
- examples/crm/src/deals/DealShow.tsx
Keyboard navigation is in a different order to that intuitively imagined
Reorganises fields into two columns and a vertical separator across the entire column.
> Feat(crm): Display Forms at a glance

- packages/ra-core/src/controller/list/queryReducer.spec.ts
- packages/ra-core/src/controller/list/queryReducer.ts
The `setOrder` callback apply the opposite order for the same column, even if `order` is defined
Apply `order` defined by the user
> Fix setSort ignores the sort order when the chosen field is the current one

- packages/ra-core/src/i18n/useTranslatable.spec.ts
- packages/ra-core/src/i18n/useTranslatable.ts
> Fix <TranslatableInputs> throws error when used with null value

- packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceManyField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
Follow #10133
When you have multiple `ReferenceManyField` targeting the same resource, their children share the store for selection.
Allow to provide a `storeKey`
Open the storybook `StoreKey` story for `ReferenceManyField`
> Add `<ReferenceManyField storeKey>` to allow more than one reference for the same resource

- packages/ra-data-graphql/src/index.ts
https://github.com/marmelab/react-admin/issues/10052 - the check whether the `override` prop was used is faulty and warns even when not appropriate.
As suggested in the comments, instead of checking whether `override` is `!= null`, we check whether it has keys in it. This way, its default value - `{}` won't pass this check, and no warning gets logged.
I used `Object.keys(override).length > 0` instead of `Object.keys(override).length` before I favor explicitness over the somewhat wonky JavaScript coercion. I can change this, though.
Follow the steps described in https://github.com/marmelab/react-admin/issues/10052 with this fixed version.
> adjusted check for use of the override option

- docs/ReferenceManyField.md
`<ReferenceManyField storeKey>` prop was introduced by https://github.com/marmelab/react-admin/pull/10132 but not documented.
Update the docs to mention this prop.
> [Doc] Document `<ReferenceManyField storeKey>` prop

- docs/AccordionForm.md
- docs/DatagridAG.md
- docs/EditableDatagrid.md
- docs/StackedFilters.md
Some references to webm videos still remained after https://github.com/marmelab/react-admin/pull/10127
Remove them
> [Doc] Remove more references to ra-enterprise webm videos

- packages/ra-core/src/controller/usePrevNextController.ts
- packages/ra-ui-materialui/src/button/PrevNextButtons.spec.tsx
Fix https://github.com/marmelab/react-admin/issues/10136
Fix the index computation in case the data comes from the query cache and page > 1
The fix can be tested in Storybook or in the E-commerce Demo
> Fix `<PrevNextButtons>` index when using paginated results

- docs/DataProviderList.md
- docs/img/backend-logos/nestjs-query.svg
There was no [`Nestjs-query`](https://tripss.github.io/nestjs-query/) data provider available.
I wrote one and added it to the list of supported backends.
https://github.com/marmelab/react-admin?tab=readme-ov-file#documentation-1
Serve the documentation like it is suggested in the `README.md` file and look at the `DataProviderList.md` file. There should be 3 GraphQL data providers in the list, with the last one being the one I added.
> [DOCS] Add ra-data-nestjs-query to DataProviderList.md

- packages/ra-core/src/form/useInput.spec.tsx
- packages/ra-core/src/form/useInput.ts
When passing a [custom validator function](https://marmelab.com/react-admin/Validation.html#per-input-validation-custom-function-validator) to an input, the `source` prop it recieves is the original `source` prop declared on the input, instead of the 'final' source computed using the `<SourceContext>`.
This is an issue when the input is inside a component wrapping it with a custom `<SourceContext>`, such as `<SimpleFormIterator>`.
Example:
```tsx
<ArrayInput source="posts">
<TextInput source="title" validate={validator} />
</ArrayInput>
```
In that case, `validator` will be called like so: `validator("value", { posts: [{ title: "value" }] }, { source: "title", /* ... */ })`
Although it should have been: `validator("value", { posts: [{ title: …
> Fix: `useInput` should call a custom validator with the final source in respect to the `<SourceContext>`

- docs/Features.md
- docs/FilteringTutorial.md
Some links to video assets in the docs are broken, because they link to webm videos that were removed from the EE website in favor of mp4 videos.
There is also a link that targets a GIF file that no longer exists.
Replace those assets with their mp4 counterparts.
`make docker-doc`
> [Doc] Features and Filtering Tutorial: Fix links to video assets

- packages/ra-data-json-server/src/index.ts
> Add support for computed fields in `ra-data-json-server`'s `dataProvider.create()`

- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
> Fix Datagrid row does not appear clickable although it is

- test-setup.js
Could not use matcher like `expect(...).toBeDisabled` in test.
initialize (import) `@testing-library/jest-dom` in jest test setup.
Try to use testing library expect method, like toBeDisabled or toHaveAttribute.
> expand expect with testing-library helper for all tests

- docs/Remix.md
- docs/Vite.md
- examples/crm/index.html
- examples/demo/index.html
- examples/no-code/index.html
- examples/simple/index.html
- examples/tutorial/src/index.css
- examples/tutorial/src/main.tsx
- packages/create-react-admin/templates/common/index.html
- packages/ra-ui-materialui/src/AdminUI.tsx
- packages/ra-ui-materialui/src/button/ToggleThemeButton.spec.tsx
For new apps, developers need to reset the body margin manually, unless they use `create-react-admin`. This is cumbersome and, in many cases, leads to ugly admins because users have missed one step in the setup. 
Use MUI's `CssBaseline` instead of `ScopedCssBaseline`. 
This might be a breaking change in some very particular situations where react-admin is included in a div and some other content is rendered ion the same page. 
Compile the `create-react-admin` package and use it to create a new app. Run the app. If should have correct margins.  
- ~~[ ] The PR includes **unit tests**~~ (only design)
- ~~[ ] The PR includes one or several **stories**~~ (existing FullApp stories still work)
Also, please make sure to read the [contributing …
> Add global Reset CSS

- examples/simple/package.json
- packages/ra-core/package.json
- packages/ra-core/src/form/useFormGroup.ts
- packages/ra-core/src/form/useInput.spec.tsx
- packages/ra-core/src/form/useInput.ts
- packages/ra-input-rich-text/package.json
- packages/ra-ui-materialui/package.json
- packages/react-admin/package.json
- yarn.lock
- Disabled and re-enabled fields did not update their dirty state, causing validation to run after they have been re-enabled.
Related issues:
Closes #10156
Closes #9870 
- This fix addresses the issue remove the workaround and making sure that a boolean value is passed to `react-hook-form` controller.
- Verify that input fields with validation are correctly marked as dirty and trigger validation when they are re-enabled after being disabled.
> Fix input validation and dirty state after re-enabling disabled fields

- docs/SimpleFormIterator.md
Closes #10171
Update of the documentation
Check the md
> [Doc]: Fix SimpleFormIterator add and remove buttons snippets

- packages/ra-core/src/form/useFormGroup.ts
With the latest version of react-hook-form (7.53.0 at the time of writing), `useFormGroup` no longer returns validation errors correctly.
This causes issues such as the TabbedForm Tab header not being colored in red when there is a validation error on one of the inputs inside the Tab.
An issue was opened on RHF repo to let them know about this regression: https://github.com/react-hook-form/react-hook-form/issues/12217
However, it seems this issue also highlights that we may not being using the form state correctly to compute the form group state, hence we figured we may as well improve the `useFormGroup` hook to be compatible with all versions of RHF.
1. Update RHF to its latest version `yarn up react-hook-form`
2. Run the test `TabbedForm.spec.tsx > should set the style of any Tab button …
> Fix `useFormGroup` doesn't return validation errors with react-hook-form 7.53.0

- packages/ra-core/src/form/useInput.ts
Currently `useInput` is generating erroneous warnings when using `ArrayInput` with `TextInput` without source. The source is provided by `useWrappedSource`
```
<ArrayInput source="users">
<TextInput source="" />
</ArrayInput>
```
Change conditional check to finalSource
Create an ArrayInput as indicated
> Avoid "no source" warning when theres a finalSource in useInput

- docs/DataProviderWriting.md
- docs/List.md
- docs/WithListContext.md
- docs/useGetList.md
- docs/useGetManyReference.md
- docs/useInfiniteGetList.md
- docs/useListContext.md
- packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/list/ListBase.stories.tsx
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/dataProvider/useGetList.stories.tsx
- packages/ra-core/src/dataProvider/useGetList.ts
- packages/ra-core/src/dataProvider/useGetManyReference.ts
- packages/ra-core/src/dataProvider/useInfiniteGetList.ts
- packages/ra-core/src/types.ts
- packages/ra-ui-materialui/src/list/List.stories.tsx
Closes #9569
Even though some API backends return additional data in the `getList` results (e.g. facets and other aggregations), there is currently no way to access them.
Update `useGetList` and `ListContext` to return any `meta` property present in the API response.
> Add support for response metadata in dataProvider.getList()

- packages/ra-core/src/i18n/TranslationMessages.ts
- packages/ra-language-english/src/index.ts
- packages/ra-language-french/src/index.ts
- packages/ra-ui-materialui/src/list/ListNoResults.spec.tsx
- packages/ra-ui-materialui/src/list/ListNoResults.stories.tsx
- packages/ra-ui-materialui/src/list/ListNoResults.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.spec.tsx
When coming back to a list page with active filters and no results, the default message (“no results found”) is misleading when the active filters aren’t visible enough.
If the list is empty **AND** there is an active filter,
- Replace “No [data] found” with “No [data] found using the current filters. Clear filters.”
- Add a link on “Clear filter” which removes all active filters
~- [ ] The **documentation** is up to date~
> Update `<Datagrid>` and `<SimpleList>` empty message when a filter is active

- packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButton.stories.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
There is no way to differentiate between filter choices and filter actions (such as save current query) in the FilterButton
when you select a filter, it disappears from the list, which changes the place of each choice item and makes it hard to remember where is the filter you want to enable ; same for the actions (Remove all filters)
~- [ ] The **documentation** is up to date~
> feat(ra-ui-materialui): Improve FilterButton UX

- packages/ra-ui-materialui/src/list/ListView.tsx
The default empty list page, which is an invite to create new elements, appears even when some elements already exist.
Here is a repro that can be tested in the [simple example](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple):
1. Go to the post list (in a large screen to show the datagrid version)
2. Select all rows using the top left checkbox
3. Hit the bulk delete button
The empty page shows up, even though there are remaining posts (in the following page).
This bug was introduced by #8945, which fixed a bug with partial pagination.
The condition for displaying the empty page is wrong, as it only counts the number of results in the current page (`data.length`) instead of the total number of results: …
> Fix List shows empty page too often

- packages/ra-core/src/auth/useCanAccess.spec.tsx
- packages/ra-core/src/auth/useCanAccess.stories.tsx
- packages/ra-core/src/auth/useCanAccess.ts
- packages/ra-core/src/auth/useCanAccessResources.spec.tsx
- packages/ra-core/src/auth/useCanAccessResources.stories.tsx
- packages/ra-core/src/auth/useCanAccessResources.ts
As we use react-query for the canAccess hooks, users may see at least one rerender because it run asynchronously.
Detect there is no support for canAccess and return a fake react-query result if needed.
The `useCanAccess` and `useCanAccessResources` have stories with and without an AuthProvider that shows the behavior.
> Avoid unnecessary rerenders with canAccess hooks when there is no authProvider

- packages/ra-ui-materialui/src/list/filter/FilterButton.spec.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.spec.tsx
The FilterButton is not accessible
add `menuitemcheckbox` role (see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemcheckbox_role)
Tests for FilterButton uses the role and pass
> Fix filter button accessibility

- docs/DataProviderWriting.md
The doc states:
> As a consequence, you should always use isPending to determine if you need to show a loading indicator.
It should be consistent with itself.
1. Some of the stories still uses isLoading
2. useList still uses isLoading here https://github.com/marmelab/react-admin/blob/f2fc70f42ec8f7209e5fa24f12330276a7ddd788/packages/ra-core/src/controller/list/useList.ts#L173
3. In some enterprise components we pass isPending to the isLoading prop which is confusing https://github.com/marmelab/react-admin/blob/f2fc70f42ec8f7209e5fa24f12330276a7ddd788/docs/Features.md?plain=1#L988
> [Doc] Doc needs to be consistent with itself regarding isPending vs isLoading

- cypress/package.json
- yarn.lock
We have two versions of express in our dev devs, one of which is outdated and raises security warning
Relax the requirements to have only 1 instance.
> Fix duplicated dependencies in dev packages

- docs/Calendar.md
`<Calendar>` and `<CompleteCalendar>`'s enterprise doc was updated but the OSS was not.
Update OSS doc
> [Doc] Update `<Calendar>` doc to explain custom event format

- docs/List.md
- docs/useListController.md
- examples/simple/src/customRouteNoLayout.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.stories.tsx
- packages/ra-core/src/controller/input/ReferenceInputBase.stories.tsx
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-ui-materialui/src/list/List.spec.tsx
- packages/ra-ui-materialui/src/list/List.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
Additional follow ups of https://github.com/marmelab/react-admin/pull/9473
Update most of the docs to use isPending (except EE components, wait until the docs over [there](https://react-admin-ee.marmelab.com/documentation) to be updated)
Update stories and examples to use isPending
Update useList to use isPending
> Fix more cases that should use isPending

- docs/DataProviderList.md
I recently decided to test out [supabase](https://supabase.com/) for a quick microservice my team was spinning out. We use react-admin for a lot of custom dashboards so I decided to run with vite, react-admin and cloudflare pages on the front end. The combo of supabase and react-admin proved to be powerful--fast, flexible, robust. I also wanted to try out the auto generated supabase GQL interface (via [pg_graphql](https://supabase.github.io/pg_graphql/)). I noticed there is a REST supabase dataprovider in [ra-supabase](https://github.com/marmelab/ra-supabase), but couldn't find a GQL dataprovider so I went ahead and wrote one ([repo here](https://github.com/maxschridde1494/ra-data-graphql-supabase)).
> add @groovestack/ra-data-graphql-supabase to data provider list docs

- docs/CreateDialog.md
- docs/EditDialog.md
"standalaone usage" doc section are present in EE doc for dialog views but not in OSS.
Backport it
~- [ ] The PR includes **unit tests** (if not possible, describe why)~
~- [ ] The PR includes one or several **stories** (if not possible, describe why)~
> [Doc] Add "standalaone usage" doc section in dialog views

- packages/ra-data-simple-rest/src/index.spec.ts
- packages/ra-data-simple-rest/src/index.ts
Records may have ids with characters that break the Simple REST Data Provider paths if not escaped. 
For example, a record with id "Post#123" has a getOne path of '/posts/Post#123' which is not desired.
IDs like this can occur when using single table inheritance with DynamoDB or with other document data stores.
The solution is to escape IDs in paths for getOne, update, updateMany, delete and deleteMany. An example path with escaped id is '/posts/Post%23123'.
Closes #10207
Perform getOne, update, updateMany, delete and deleteMany with records that have escape-requiring ids e.g. 'Post#123'. 
- [ x ] The PR targets `master` for a bugfix, or `next` for a feature
- [ x ] The PR includes **unit tests** (if not possible, describe why)
- [ x ] The **documentation** is up to date
Also, please make …
> Fix for ids not being escaped in paths in the Simple Rest Data Provider

- README.md
- docs/Demos.md
- docs/Readme.md
- examples/data-generator/README.md
- examples/demo/README.md
- packages/ra-data-fakerest/README.md
- packages/ra-data-json-server/README.md
- packages/ra-data-simple-rest/README.md
- packages/ra-i18n-polyglot/README.md
- packages/ra-language-english/README.md
- packages/ra-language-french/README.md
- packages/react-admin/README.md
Vimeo will delete our e-commerce video.
Change publication platform for YouTube
> [Doc] Change Vimeo video for YouTube

- docs/Upgrade.md
> [Doc] Update migration guide with `useRecordSelection` changes

- examples/simple/src/posts/PostEdit.tsx
- packages/ra-core/src/dataProvider/useUpdate.optimistic.stories.tsx
- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.stories.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
- packages/ra-data-fakerest/src/index.ts
React-hook-form sets the value of `disabled` inputs to `undefined`. For most data providers, this isn't a problem (except the disabled field won't be sent in the update).
But FakeRest is local, so it receives the `undefined` value, and uses it to override the existing value. In effect, this erases the value.
```jsx
dataProvider.update(123, data: { id: undefined }); // erases the id with FakeRest
```
I also noticed that we made the same mistake in optimistic updates.
This can be seen e.g. in the simple example, by changing the first input of PostEdit to `<TexuInput source="id" disabled" />`
Remove `undefined` values from the edit payload:
Supersedes #10242
> Fix `disabled` inputs temporarily erase values

- docs/Authenticated.md
- docs/Authentication.md
- docs/useAuthState.md
- docs/useAuthenticated.md
- packages/ra-core/src/auth/Authenticated.spec.tsx
- packages/ra-core/src/auth/Authenticated.tsx
- packages/ra-core/src/auth/WithPermissions.tsx
- packages/ra-core/src/auth/useAuthenticated.ts
- packages/ra-ui-materialui/src/layout/NotFound.tsx
`<Authenticated>` displays its child while the auth status is being checked. It may potentially render restricted content to anonymous users.
Make it render nothing while loading.
Part of #10222
> Make Authenticated component secure by default

- docs/Edit.md
- docs/EditTutorial.md
- docs/Show.md
- packages/ra-ui-materialui/src/detail/Edit.spec.tsx
- packages/ra-ui-materialui/src/detail/Edit.stories.tsx
- packages/ra-ui-materialui/src/detail/EditView.tsx
The Show and List components support that prop, not the Edit.
Add support for `<Edit emptyWhileLoading>`
~- [ ] The PR includes **unit tests** (if not possible, describe why)~
> ui-materialui: Add support for `<Edit emptyWhileLoading>`

- packages/ra-core/src/auth/useGetPermissions.ts
- packages/ra-core/src/auth/usePermissions.spec.tsx
- packages/ra-core/src/auth/usePermissions.stories.tsx
- packages/ra-core/src/auth/usePermissions.ts
- packages/ra-core/src/types.ts
Even though using permissions in React-Admin is optional, the AuthProvider type required users to implement the `getPermissions` method.
Make the `getPermissions` method optional.
This also allows us to optimize the `usePermissions` hook.
Stories and tests
> Make authProvider.getPermissions optional

- packages/ra-core/src/auth/WithPermissions.stories.tsx
- packages/ra-core/src/auth/WithPermissions.tsx
- packages/ra-core/src/auth/index.ts
- packages/ra-core/src/auth/useIsAuthPending.ts
- packages/ra-core/src/controller/create/CreateBase.spec.tsx
- packages/ra-core/src/controller/create/CreateBase.stories.tsx
- packages/ra-core/src/controller/create/CreateBase.tsx
- packages/ra-core/src/controller/edit/EditBase.spec.tsx
- packages/ra-core/src/controller/edit/EditBase.stories.tsx
- packages/ra-core/src/controller/edit/EditBase.tsx
- packages/ra-core/src/controller/list/InfiniteListBase.spec.tsx
- packages/ra-core/src/controller/list/InfiniteListBase.stories.tsx
- packages/ra-core/src/controller/list/InfiniteListBase.tsx
- packages/ra-core/src/controller/list/ListBase.spec.tsx
- packages/ra-core/src/controller/list/ListBase.stories.tsx
- packages/ra-core/src/controller/list/ListBase.tsx
- packages/ra-core/src/controller/show/ShowBase.spec.tsx
- packages/ra-core/src/controller/show/ShowBase.stories.tsx
- packages/ra-core/src/controller/show/ShowBase.tsx
- packages/ra-core/src/core/CoreAdminRoutes.tsx
- packages/ra-ui-materialui/src/detail/Create.tsx
- packages/ra-ui-materialui/src/detail/Edit.tsx
- packages/ra-ui-materialui/src/detail/Show.tsx
- packages/ra-ui-materialui/src/list/InfiniteList.tsx
- packages/ra-ui-materialui/src/list/List.tsx
All CRUD views currently starts to render optimistically even though authentication and optionally authorization checks are pending. This is a security issue.
Make sure the base components for all CRUD views verify that no auth checks are pending before rendering.
Introduce a loading prop accepting a ReactNode on those components that is displayed while auth checks are pending.
> Access control: pessimistic rendering in CRUD views

- packages/ra-ui-materialui/package.json
- yarn.lock
Fixes #10260
`@mui/utils` is used here https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/theme/defaultTheme.ts#L2
But it is not explicitly declared as peerDependency here https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/package.json#L54
Explicitly declare it as peerDependency
Add a dependency on react-admin using pnpm 9.3.0
> Fix pnpm error Module not found: Can't resolve '@mui/utils'

- docs/Admin.md
- docs/Routing.md
Current docs is outdated, does not work [data APIs](https://reactrouter.com/en/main/routers/picking-a-router#using-v64-data-apis)
React-router recommends user to update to use new API.
We should let user use [`warnWhenUnsavedChanges`](https://marmelab.com/react-admin/Upgrade.html#warnwhenunsavedchanges-changes) when they perform their setup with latest best practice
> [Doc] Update docs related to router to be consistent with migration guide

- docs/StackedFilters.md
`<StackedFilters>` doc was updated for `ra-form-layout` v5.2.0
Update `<StackedFilters>` doc
~- [ ] The PR includes **unit tests** (if not possible, describe why)~
~- [ ] The PR includes one or several **stories** (if not possible, describe why)~
> [Doc] Update `<StackedFilters>` doc for `ra-form-layout` v5.2.0

- docs/AutoSave.md
`<AutoSave>` is currently incompatible with `warnWhenUnsavedChanges`.
Warn about it in the documentation.
> [Doc] Warn about `<AutoSave>` incompatibility with `warnWhenUnsavedChanges`

- docs/DataProviderWriting.md
- docs/DataProviders.md
- docs/Features.md
- docs/Fields.md
- docs/ReferenceField.md
- examples/simple/src/comments/CommentList.tsx
- examples/simple/src/comments/CommentShow.tsx
- examples/simple/src/dataProvider.tsx
- packages/ra-core/src/dataProvider/populateQueryCache.ts
- packages/ra-core/src/dataProvider/useDataProvider.spec.tsx
- packages/ra-core/src/dataProvider/useDataProvider.stories.tsx
- packages/ra-core/src/dataProvider/useDataProvider.ts
- packages/ra-core/src/types.ts
- packages/ra-data-fakerest/README.md
- packages/ra-data-fakerest/src/index.ts
- packages/ra-data-json-server/README.md
- packages/ra-data-json-server/src/index.ts
Pages aggregating data from more than one resource always have to fetch more than one API endpoint in cascade, and with a slow backend this leads to an incomplete and blinking UI.
For example, the Comment list page in the simple example shows the post for each comment. So it has to fetch `dataProvider.getList('comments')`, then `dataProvider.getMany('posts', { ids: [comment postIds] })` (via `<ReferenceField>`).
Some backends are capable of embedding related records (e.g. the post of a comment). However, populating the cache based on these embeds is cumbersome.
- Allow developers to embed related data in the main data
- Allow developers to prefetch related records and populate the cache with it
- ~~[ ] Add support for embedding and prefetching to `ra-data-simplerest`~~(out of scope) …
> Add support for embedding and prefetching

- packages/ra-core/package.json
- packages/ra-core/src/types.ts
- packages/ra-core/src/util/useFieldValue.ts
- packages/ra-ui-materialui/package.json
- packages/ra-ui-materialui/src/field/FileField.tsx
- packages/ra-ui-materialui/src/field/ImageField.tsx
- packages/ra-ui-materialui/src/field/types.ts
- yarn.lock
Fixes https://github.com/marmelab/react-admin/issues/9849
Records paths inferred from type using `hotscript` aren't compatible with those inferred by `react-hook-form`
Declare our own types for path inference that currently just re-export those from `react-hook-form`, making us more resilient to future changes.
- Open the `InvoiceShow` of the CRM demo and add a type parameter to the `TextField` of the Order reference. The `TextField` `source` should be valid and trying to replace it should trigger the IDE autocompletion, showing all `Order` fields
> Make records paths inferred from type compatible with react-hook-form

- packages/ra-core/src/auth/useAuthState.ts
Calling `useAuthState()` should not logout the user is anonymous. Yet, in some situations, it does. 
In particular, calling `useAuthState` in a CRUD page (e.g. `<Edit disableAuthentication>`) logs the user out. 
```jsx
export const UserEdit = () => {
const {isLoading, authenticated} = useAuthState();
if(isLoading) {
return <Loading></Loading>;
}
return (
<Edit disableAuthentication>
<SimpleForm>
// ...
</SimpleForm>
</Edit>
);
};
```
In this case, there are two calls to `authProvider.checkAuth`with the same params (and the same query key):
- one from `useCheckAuth()` with `logoutOnFailure = false`. The auth provider returns an error, which should not be used to logout
- one from `<Edit disableAuthentication>`, which should not execute the `authProvider.checkAuth` as the …
> Fix useAuthState may logout even though logoutOfFailure is false

- packages/ra-core/src/core/NavigateToFirstResource.tsx
This PR addresses issue #10262 with navigation in the React Admin application, where users experience redirect loops when transitioning from the admin panel to the first resource.
The solution involves adding the `replace={true}` prop to the `<Navigate>` component in the `NavigateToFirstResource`. This change ensures that the navigation history is correctly updated, allowing users to return to their previous page without being redirected again.
Closes #10262
1. Navigate to the non-RA part of the application.
2. Go to the /admin path.
3. Verify that navigating back returns you to the previous page without redirects to the first resource.
>  [Fix] Add replace prop to <Navigate> in NavigateToFirstResource 

- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
AutocompleteInput displays a 'Create' option for choices that already exist when the `createLabel` prop is provided.
Can be reproduced in the Storybook: https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-input-autocompleteinput--create-label
Fix the condition under which the 'Create' option appears.
Run the story `/story/ra-ui-materialui-input-autocompleteinput--create-label` locally, or run the unit tests.
> Fix `<AutocompleteInput>` displays 'Create' option for choices that already exist when `createLabel` is provided

- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.stories.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/controller/show/useShowController.spec.tsx
- packages/ra-core/src/controller/show/useShowController.stories.tsx
- packages/ra-core/src/controller/show/useShowController.ts
Fixes #10158. React-router fixed an issue where params weren't properly decoded. However, react-admin still tried to decode them, leading to invalid ids.
Remove the decoding from `useEditController` and `useShowController`
There are new stories and tests
> Fix double decoding of ids in URLs

- packages/ra-core/src/core/useGetResourceLabel.spec.tsx
- packages/ra-core/src/core/useGetResourceLabel.ts
- packages/ra-ui-materialui/src/list/ListNoResults.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.spec.tsx
#10291 introduces translation of the resource name in the no results message. Nevertheless, when there is no results, the smart count used for the translation should be 0.
Update smart_count when calling `getResourceLabel` function.
> Fix smart count for no results message

- docs/SimpleFormIterator.md
`<SimpleFormIterator>` doc still says that the component clones its children, which is no longer true since v5.
Remove this unnecessary warning from the doc.
> [Doc] Remove outdated warning about `<SimpleFormIterator>` cloning its children

- docs/TabbedForm.md
- docs/TabbedShowLayout.md
There are some typos in TabbedForm and TabbedShowLayout pages.
Fix the typos.
- why: I fixed only docs.
- why: I fixed only docs.
> [Doc] Fix typo in TabbedForm and TabbedShowLayout

- packages/ra-core/src/routing/useGetPathForRecord.spec.tsx
- packages/ra-core/src/routing/useGetPathForRecord.stories.tsx
- packages/ra-core/src/routing/useGetPathForRecord.ts
- packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
Closes #10301
Supersedes #10304
> Fix ReferenceField link is wrong when the record is not yet loaded

- docs/FileInput.md
- docs/ImageInput.md
Some links to the react-dropzone docs are dead (e.g. https://react-dropzone.netlify.com/#proptypes)
Update the links to the new doc location
> [Doc] Fix links to react-dropzone doc pages

- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/core/CoreAdminContext.tsx
- packages/ra-core/src/dataProvider/index.ts
- packages/ra-core/src/dataProvider/undo/AddUndoableMutationContext.tsx
- packages/ra-core/src/dataProvider/undo/TakeUndoableMutationContext.tsx
- packages/ra-core/src/dataProvider/undo/UndoableMutationsContextProvider.tsx
- packages/ra-core/src/dataProvider/undo/index.ts
- packages/ra-core/src/dataProvider/undo/types.ts
- packages/ra-core/src/dataProvider/undo/useAddUndoableMutation.tsx
- packages/ra-core/src/dataProvider/undo/useTakeUndoableMutation.tsx
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-core/src/dataProvider/useDelete.undoable.stories.tsx
- packages/ra-core/src/dataProvider/useDeleteMany.ts
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdate.undoable.stories.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
- packages/ra-ui-materialui/src/detail/Edit.spec.tsx
- packages/ra-ui-materialui/src/layout/Notification.spec.tsx
- packages/ra-ui-materialui/src/layout/Notification.stories.tsx
- packages/ra-ui-materialui/src/layout/Notification.tsx
> Fix undo logic not working when doing multiple deletions one by one

- packages/ra-ui-materialui/src/list/ListNoResults.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.spec.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
Since #10184, published in 5.2.0, `<SimpleList>` and `<Datagrid>` throw an error when used in standalone mode (i.e., outside of a ListContext) with an empty `data`.
> useListContext must be used inside a ListContextProvider
The problem comes from `ListNoResults`, which reads the `ListContext` to determine if there is an active filter.
https://github.com/marmelab/react-admin/blob/caca09ec556fa3052941071a4d19cd5eed2ea5ea/packages/ra-ui-materialui/src/list/ListNoResults.tsx#L15
Use the alternative `useListContextWithProps` instead of `useListContext`.
> Fix `<SimpleList>` throws an error when no data in standalone mode

- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/dataProvider/useUpdate.ts
> Fix `<Edit>` ignores mutation meta when updating the `getOne` cache

- packages/ra-ui-materialui/src/input/sanitizeInputRestProps.ts
I think (not 100% sure) that 'initialValue' is deprecated so it should also be removed from here?
> Remove deprecated 'initialValue' from sanitizeInputRestProps

- docs/StackedFilters.md
EE doc for `<StackedFilters>` has been updated.
Updated OSS doc.
~- [ ] The PR includes **unit tests** (if not possible, describe why)~
~- [ ] The PR includes one or several **stories** (if not possible, describe why)~
> [Doc] Update `<StackedFilters>` documentation for `defaultValue`

- docs/useUpdate.md
`useUpdate` is a powerful hook, but it's not apparent when reading its documentation. 
The doc if its options is to be found in the "querying the API" chapter, but that's not necessarily where developers will look for it. 
Develop the `useUpdate` doc, sometimes by duplicating part of the doc for "Querying the API".
> [Doc] Improve `useUpdate` usage instructions

- packages/ra-data-graphql-simple/src/buildVariables.test.ts
- packages/ra-data-graphql-simple/src/buildVariables.ts
Fixes #10317.
The sparse fields functionality works by reading the `meta.sparseFields` array. But for create and update mutations it looked for the `sparseFields` value in `data.meta`.
Return the `meta` object in `buildCreateUpdateVariables` which is used for both create and update mutations.
Can be tested by setting the `meta` object for a create or update mutation and setting sparse fields on it:
```ts
{
meta: { sparseFields: ['id'] }
}
```
Trigger the mutation and the generated selection should only include fields specified in `sparseFields`.
- Not UI related, affects data provider. I'm not aware that it has any stories.
> fix(ra-data-graphql-simple): Unify meta location in buildVariables

- packages/ra-ui-materialui/src/input/DateInput.spec.tsx
- packages/ra-ui-materialui/src/input/DateInput.stories.tsx
- packages/ra-ui-materialui/src/input/DateInput.tsx
- packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx
- packages/ra-ui-materialui/src/input/DateTimeInput.stories.tsx
- packages/ra-ui-materialui/src/input/DateTimeInput.tsx
`<DateInput>` and `<DateTimeInput>` do not react to form changes. For instance if you use react-hook-form hooks to set the value.
Fixes #10320
Make sure we update the internal value when it changes from outside. 
There are two new stories and matching tests:
- DateTimeInput: https://react-admin-storybook-c6qu3ea65-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-input-dateinput--external-changes
- DateInput: http://localhost:9010/?path=/story/ra-ui-materialui-input-dateinput--external-changes
~~- [ ] The **documentation** is up to date~~
> Fix `<DateInput>` and `<DateTimeInput>` do not react to form changes

- .eslintrc
- examples/crm/src/types.ts
- packages/ra-core/src/controller/create/useCreateController.ts
Using named imports from `@mui/icons-material` or `lodash` can cause performance issues.
See
- https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment
- https://github.com/marmelab/react-admin/pull/9828
Currently the project's tooling doesn't protect against such mistakes.
Improve the ESLint rules config to mark such imports as errors.
Use a [custom rule](https://github.com/slax57/ast-talk-examples/blob/eslint-solution/eslint/custom-rules/enforce-default-import.js) (in a custom ESLint plugin), which would have had the benefit of automatically suggesting a fix when an error is detected.
But the project is still using the legacy configuration file (as opposed to [new](https://eslint.org/docs/v8.x/use/configure/configuration-files-new)), which makes it cumbersome …
> [chore] Improve ESLint config to restrict imports from @mui/icons-material and lodash

- docs/DataProviders.md
Solves #10342
React-admin v5 uses a new version of TanStack React Query compared to v4. The devtools are not bundled in the package anymore and have to be installed separately. Related documentation was not updated.
Update the related docs to match with the new changes.
Follow the steps and confirm devtools is shown.
- No unit tests as it's a doc update.
- No stories as it's a doc update.
> [Doc] Fix react-query devtools documentation

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
Datagrid has built-in acess control. If the user cannot access the current resource with the `delete` action, the `BulkDeleteButton` doesn't appear. 
But the bulk action toolbar is still displayed in that case... empty. 
Check the delete rights before setting the default `bulkActionToolbar` value to hide the checkboxes when the user hasn't defined custom bulk actions and they don't have the delete rights.
> Fix Datagrid bulkActionButtons shows empty toolbar when user cannot access the delete action

- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
`linkType` should only remove the onClick action but it breaks the UI.
> Fix `<SimpleList linkType={false}>` UI

- packages/ra-ui-materialui/src/list/filter/FilterList.stories.tsx
The `FilterListItem story features an example with an empy value using `null`: 
```jsx
<FilterListItem
label="21st"
value={{ year_gte: 2000, year_lte: null }}
/>
```
This example doesn't work, as selecting the "21st" filter item doesn't mark it as active. 
https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-list-filter-filterlist--full-app
The right syntax is to use `undefined`:
```jsx
<FilterListItem
label="21st"
value={{ year_gte: 2000, year_lte: undefined }}
/>
```
> Fix `FilterListItem` story shows wrong way of resetting a filter

- docs/AppBar.md
The curent example for a custom user menu doesn't compile in TS, and misses a link.
Fix it
> [Doc] Fix `<AppBar userMenu>` example usage

- docs/useRegisterMutationMiddleware.md
Code examples in [React-admin - useRegisterMutationMiddleware](https://marmelab.com/react-admin/useRegisterMutationMiddleware.html)  are erroneous because they do not return the next mutation result, although this is necessary for most main mutations handled by react admin (either create or update).
Fix the documentation.
~~- [ ] The PR includes one or several **stories** (if not possible, describe why)~~
> [Doc] Fix `useRegisterMutationMiddleware` documentation

- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorContext.ts
Fix https://github.com/marmelab/react-admin/issues/10355
Wrong `add`-function type.
Add missing parameter.
There seems to be no mention in the documentation that a function can be given a parameter. However, I'm not able to produce good enough English to put it in the documentation so I didn't try to add it.
> [TypeScript] Add missing parameter to `add` function type of `<SimpleFormIteratorContextValue>`

- docs/CanAccess.md
- docs/Permissions.md
The current doc for securing custom pages with access control misses two things:
1. The AccessDenied page (the current syntax only shows an empty page when the user doesn't have access)
2. Instructions for tweaking the Menu
Improve the doc
> [Doc] Improve Access Control for Custom Pages

- packages/ra-core/src/auth/useCanAccessResources.ts
`useCanAccessResources` currently uses `useQueries`. As such, it doesn't accept `useQuery` options like `enabled`.
Refactor it to use `useQuery` instead.
- All tests should pass without modification
~~- [ ] The PR includes one or several **stories** (if not possible, describe why)~~
~~- [ ] The **documentation** is up to date~~
> Fix `useCanAccessResources` cannot have react-query options

- docs/DateRangeInput.md
EE documentation was updated to explain how to use `<DateRangeInput>` as a filter.
Document is on OSS doc
> [Doc] Document `<DateRangeInput>` as a filter

- packages/ra-ui-materialui/src/button/SortButton.tsx
This is a regression caused by #10337
- Launch the ecommerce demo
- Go to the posters list
- See the sort button
> Fix SortButton default translation

- docs/DataProviderList.md
Updated the Supabase link format for better consistency by moving "(GraphQL)" inside the clickable link text.
> docs: fix Supabase link formatting in `DataProviderList.md`

- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/list/useList.ts
We used an alternative to `setState` called `safeSetState` that disabled some React linter warnings. This silenced a problem of effect running too often in `useList` and `useReferecneManyFieldController`.
The removal of `safeSetState` in  #10341 revealed the problem, which is now reported by a linter warning (e.g. , https://github.com/marmelab/react-admin/pull/10370/files#diff-66e51c85b7ef7a61bc686a09a730355d6cc188a86670eb5d710d0d41d74ad5fe)
Add the required dependencies
> Fix ReferenceManyField executes filter reset filter too often

- docs/AutocompleteArrayInput.md
The following tip is now useless because this prop is now applied by default
Remove the tip
> [Doc] Remove an useless tip from the doc

- packages/ra-core/src/auth/CanAccess.spec.tsx
- packages/ra-core/src/auth/CanAccess.stories.tsx
- packages/ra-core/src/auth/CanAccess.tsx
- packages/ra-core/src/auth/useRequireAccess.spec.tsx
- packages/ra-core/src/auth/useRequireAccess.stories.tsx
- packages/ra-core/src/auth/useRequireAccess.tsx
- packages/ra-ui-materialui/src/layout/ResourceMenuItem.spec.tsx
- packages/ra-ui-materialui/src/layout/ResourceMenuItem.stories.tsx
- packages/ra-ui-materialui/src/layout/ResourceMenuItem.tsx
- packages/react-admin/src/Admin.stories.tsx
When using the `basename` prop on `<Admin>`, access control redirects don't work.
Also, `ResourceMenuItem` should not render in case of access control error
Fixes #10380
- Use the `basename` in those redirects.
- Fix `ResourceMenuItem` should not render in case of access control error
- Unit tests
- http://localhost:9010/iframe.html?args=&id=react-admin-admin--access-control-in-sub-path
> Fix access control basename handling

- packages/ra-core/src/controller/field/useReferenceFieldController.ts
- packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
Fixes #10379
`ReferenceArrayField`'s `queryOptions` required `queryFn` and `queryKey` props even though these should be optional.
Update types to omit the above two fields.
Also aligned the types between `ReferenceField`, `ReferenceArrayField` and `useReferenceFieldController`.
Create a `<ReferenceArrayField queryOptions={{}} />` and confirm no type errors occur on `queryOptions` stating that `queryFn` and `queryKey` are required.
- Didn't see an existing unit test yet, should a new one be added?
- Unsure if story is required for this change. Please let me know if you have an idea.
> Align queryOptions type in reference components and controller

- packages/ra-ui-materialui/src/input/TextInput.stories.tsx
We don't show (in storybook) the behavior of `TextInput` when we trigger a server error
Add a story
https://react-admin-storybook-fcemgnwhn-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-textinput--server-error
https://react-admin-storybook-fcemgnwhn-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-textinput--server-validation-error
> Add a story when `TextInput` trigger a server error

- packages/ra-core/src/auth/useLogin.spec.tsx
- packages/ra-core/src/auth/useLogin.stories.tsx
- packages/ra-core/src/auth/useLogin.ts
Consider an Admin that has some pages that allow anonymous access, and also a `authProvider.getPermissions()` implementation, that, say, returns `'user'` when the user is logged in, and `undefined` when the user is not logged in.
If the user first accesses the anonymous parts of the Admin, the cached permission will be `undefined`. But if he then logs in, without leaving the Admin, then the cache is not updated, and the permissions still return `undefined` instead of `'user'`.
Invalidate the `getPermissions` cache after a successful login, to force a refetch of the permissions.
https://react-admin-storybook-31pnpeyju-marmelab.vercel.app/?path=/story/ra-core-auth-uselogin--permissions-state
Also, please make sure to read the [contributing …
> Fix `useLogin` should invalidate the `getPermissions` cache

- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fixes #10274
When entering a unknown value in an `<AutocompleteInput>` or `<AutocompleteArrayInput>` that supports creation, users have to click on the creation menu item. This is cumbersome as MUI `<AutoComplete>` supports creating items by pressing `Enter`
Properly handle the case in our `onChange` handler.
Check any of the stories that supports creation, enter a new item and validate it with `Enter`. For instance:
- https://react-admin-storybook-git-improve-array-input-c-cedec7-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-input-autocompleteinput--on-create
- https://react-admin-storybook-git-improve-array-input-c-cedec7-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-input-autocompleteinput--on-create-prompt
- https://react-admin-storybook-git-improve-array-input-c-cedec7 …
> Fix: Improve AutocompleteInput creation support

- docs/SimpleList.md
- packages/ra-core/src/routing/useGetPathForRecord.ts
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.spec.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
- packages/ra-ui-materialui/src/list/SimpleList/SimpleListItem.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
- packages/ra-ui-materialui/src/list/datagrid/index.ts
- packages/ra-ui-materialui/src/list/index.ts
- packages/ra-ui-materialui/src/list/types.ts
Supersedes #10349
> The linkType for SimpleList provides less functionality than the rowClick for DataGrid. And also the inconsistency makes it harder to use.
> Implement rowClick prop as it works for Datagrid.
Keep the linkType prop working as previously, but show it as deprecated. If both are set, linkType takes precedence (because it will be simpler to remove from the code later that way).
It also fixes an issue introduced by #10343 that produced nested `li` which is invalid HTML.
- `linkType`: https://react-admin-storybook-2x9vrs84o-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-list-simplelist--link-type
- `rowClick`: https://react-admin-storybook-2x9vrs84o-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-list-simplelist--row-click
- Fix for invalid html: …
> Introduce SimpleList rowClick

- docs/DateRangeInput.md
Fix the import of `DateRangeInput` in the OSS doc
> [Doc] Fix `<DateRangeInput>` import syntax

- docs/TreeWithDetails.md
`<TreeWithDetails>` now supports a `filter` prop for permanent filters.
Update `<TreeWithDetails>` documentation to mention it.
> [Doc] Update `<TreeWithDetails>` documentation

- packages/ra-ui-materialui/src/input/FileInput.stories.tsx
- packages/ra-ui-materialui/src/input/FileInput.tsx
Fix https://github.com/marmelab/react-admin/issues/10401
The issue only happens after upgrading `react-dropzone` to the latest version (14.3.5 at the time of writing). Version 14.2.3 does not show the issue.
At first I thought it seemed like a regression from the `react-dropzone` lib, but on second thought, I think we should not forward the `onChange` prop to the wrapping `<Labeled>` anyways. We should only call `onChange` ourselves, to make sure it's always fed with a `File` object or array.
Exclude the `onChange` prop from the `...rest` parameters.
Locally update the `react-dropzone` version: `yarn up react-dropzone`.
Then, run one of the following stories, and make sure they only trigger `onChange` once, with either a `File` object or array.
- …
> Fix `<FileInput>` triggers `onChange` twice with latest version of `react-dropzone`

- docs/ReferenceManyToManyField.md
- docs/ReferenceManyToManyInput.md
The EE doc was updated and we have some issues with our `markdownlint`.
Backport this new doc and fix those issues
> [Doc] Backport `<ReferenceManyToManyField  queryOptions>` and `<ReferenceManyToManyInput  queryOptions  mutationOptions>` doc

- packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
Fixes #10394
#10102 introduced a regression that prevents `rowClick` functions to return `expand` or `toggleSelection`
Fix the regression and add tests
- Unit tests
- story: https://react-admin-storybook-git-fix-datagrid-row-click-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-list-datagrid--full-app (use the storybook controls to tweak the `rowClick`)
> Fix `<Datagrid>` `rowClick` function cannot expand or select

- docs/ShowBase.md
Fix #10411
Remove section documenting `<ShowBase emptyWhileLoading>` from the docs since the prop does not exist.
> [Doc] Remove `<ShowBase emptyWhileLoading>` from the docs

- packages/ra-core/src/form/FormDataConsumer.tsx
- packages/ra-ui-materialui/src/form/FormDataConsumer.stories.tsx
Fixes #10415
Keep a stable reference to the children function
- Story before the fix: https://react-admin-storybook-jis75yi0c-marmelab.vercel.app/?path=%2Fstory%2Fra-core-form-formdataconsumer--basic. Enter a title then select a user. Notice the flicker each time you change the  user value. You might have to set a CPU throttle in your devtool to notice it.
- Story after the fix: https://react-admin-storybook-lyoclo2wi-marmelab.vercel.app/?path=%2Fstory%2Fra-core-form-formdataconsumer--basic
> Fix form data consumer flicker

- docs/Create.md
- docs/Edit.md
- docs/Reference.md
- docs/navigation.html
- docs/useGetRecordRepresentation.md
- docs/useRecordFromLocation.md
- packages/ra-core/package.json
- packages/ra-core/src/controller/create/useCreateController.spec.tsx
- packages/ra-core/src/controller/create/useCreateController.ts
- packages/ra-core/src/controller/edit/useEditController.stories.tsx
- packages/ra-core/src/core/SourceContext.stories.tsx
- packages/ra-core/src/form/Form.spec.tsx
- packages/ra-core/src/form/Form.stories.tsx
- packages/ra-core/src/form/FormDataConsumer.spec.tsx
- packages/ra-core/src/form/index.ts
- packages/ra-core/src/form/useAugmentedForm.ts
- packages/ra-core/src/form/useRecordFromLocation.spec.tsx
- packages/ra-core/src/form/useRecordFromLocation.ts
- yarn.lock
There's no way to redirect to an Edit form with modifications. This makes it cumbersome to prefill an EditForm (see e.g. ra-history Revert button).
We already have a mechanism to prefill a form from the location state or search query in `useCreateController` that we leverage for cloning.
- https://react-admin-storybook-git-allow-record-override-76c9cb-marmelab.vercel.app/?path=%2Fstory%2Fra-core-form-form--multi-routes-form
> Allow record override from location everywhere

- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
This PR fixes a bug where the `meta` param was not used to construct the query keys when updating the cache, if the `meta` param was passed at call time, and the mutation mode was set to pessimistic.
Supersedes https://github.com/marmelab/react-admin/pull/10418
run the unit tests
> Fix `useUpdate` ignores `meta` when populating the query cache in pessimistic mode

- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
Fixes #9661
We had a workaround for adding validation on the ArrayInput itself (like min/max number of items) that triggered a register/unregister of the input in react-hook-form inside a `useEffect`. This effect is run twice in StrictMode. 
It appears the workaround isn't needed anymore to have validation on the ArrayInput.
- https://react-admin-storybook-61vioyrs6-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-input-arrayinput--basic To check the `isDirty`. Run the story locally for React.StrictMode
- https://react-admin-storybook-61vioyrs6-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-input-arrayinput--validation To check validation is still working
> Fix ArrayInput makes the form dirty in strict mode

- docs/Fields.md
The code example in the documentation is not valid code.
Corrected example to valid code.
\-
> Fix invalid code example in Fields-docs

- docs/AppTheme.md
- examples/demo/index.html
- packages/ra-ui-materialui/src/theme/nanoTheme.ts
Apps using the Nano theme aren't very usable due to poor legibility of buttons and menus.
Tweak the theme for better legibility.
Before:
After:
> Adjust Nano theme for better legibility

- packages/ra-ui-materialui/src/field/ArrayField.stories.tsx
An [ArrayField story](https://react-admin-storybook-r2j0z2ksd-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-arrayfield--in-show-layout) crashes following the introduction of access control.
Fix the story.
Open https://react-admin-storybook-kn7qen7tb-marmelab.vercel.app/?path=%2Fstory%2Fra-ui-materialui-fields-arrayfield--in-show-layout
> Fix ArrayField Story

- docs/Tutorial.md
> [Doc] Add video to the Getting Started tutorial

- .github/workflows/test.yml
- Makefile
- scripts/check-documentation-videos-format.sh
We had many issues in the past with incompatible video formats or codecs on video assets used in the documentation (e.g. not readable on Firefox or Ubuntu+Chrome)
We risk doing the same error in the future, as our screen capture tools seem to produce erroneous videos by default
Add a CI step to check the video asset files
- Create a video with a wrong format (use something like https://convertio.co/ to convert a video into HEVC format)
- run the script: `make check-documentation-videos-format`
- It should print a warning:
```
Invalid codec for ./docs/img/test/test.mp4
Convert it to avc1 with:
ffmpeg -i ./docs/img/test/test.mp4 -c:v libx264 -c:a copy ./docs/img/test/test_avc1.mp4
rm ./docs/img/test/test.mp4
mv ./docs/img/test/test_avc1.mp4 ./docs/img/test/test.mp4
make: *** [Makefile:180: …
```
> Add a check for videos format in CI

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- examples/simple/src/comments/CommentEdit.tsx
- examples/simple/src/posts/PostCreate.tsx
- examples/simple/src/posts/TagReferenceInput.tsx
With an `<Autocomplete>` which has a create component opening a Dialog, the list of choices reopens after clicking Create, which hides the Dialog.`
Fix https://github.com/marmelab/react-admin/issues/10427
- Document the issue
- Fix the simple example
- Open the simple example in dev mode
- Edit a post and go to the *Miscellaneous* tab
- Create a new tag
=> No issue as we now have `openOnFocus` set to `false`
> [Doc] Explain `openOnFocus` in `<AutocompleteInput>` with StrictMode

- packages/ra-core/src/dataProvider/useDelete.pessimistic.stories.tsx
- packages/ra-core/src/dataProvider/useDelete.spec.tsx
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-ui-materialui/src/button/DeleteButton.stories.tsx
Whe using pessimistic mode, a call to the delete callback of `useDelete` does not invalidate active queries. 
As a consequence, lists aren't refreshed. This creates buggy behaior in some cases.
For instance, in a list where each row has a DeleteButton in pessimistic mode, clicking on a delete button properly removes the deleted row, but does not update the list, which therefore has less rows than the `perPage`.
https://github.com/user-attachments/assets/33c748ae-7b8c-4843-a1b8-7176e1997005
Related queries (getList, getMany, etc) are only invalidated on success on optimistic and undoable mode. They should be invalidated in all modes. 
https://github.com/user-attachments/assets/73766a3a-e18b-4177-b138-1a789245b99a
http://localhost:9010/?path=/story/ra-ui-materialui-button-deletebutton--in-li …
> Fix useDelete does not invalidate cache in pessimistic mode

- packages/ra-data-graphql/README.md
- packages/ra-data-graphql/src/index.test.ts
- packages/ra-data-graphql/src/index.ts
See #9403
A GraphQL backend may support functionality that extends beyond the default Data Provider methods. One such example of this would be implementing GraphQL subscriptions and integrating [ra-realtime](https://marmelab.com/ra-enterprise/modules/ra-realtime) to power realtime updates in your React-Admin application. However, graphql dataFrovider implementations can't have access to the introspection made by `ra-data-graphql` and may have to reimplement the same logic.
- Update `ra-data-graphql` so that the dataProvider has a `getIntrospection` method allowing custom implementations to leverage the introspection.
- Update `ra-data-graphql` so that the dataProvider has a `client` property allowing custom implementations to access the Apollo client easily whether it was provided or …
> Allow graphql dataProviders to leverage the introspection results

- packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
- packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx
- packages/ra-core/src/controller/create/CreateController.tsx
- packages/ra-core/src/controller/edit/EditContextProvider.tsx
- packages/ra-core/src/controller/edit/EditController.tsx
- packages/ra-core/src/controller/edit/useEditContext.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
- packages/ra-core/src/controller/field/useReferenceFieldController.ts
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx
- packages/ra-core/src/controller/list/ListController.tsx
- packages/ra-core/src/controller/list/useInfiniteListController.ts
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-core/src/controller/list/useListContext.ts
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/show/ShowController.tsx
- packages/ra-core/src/controller/show/useShowContext.tsx
- packages/ra-core/src/controller/show/useShowController.ts
- packages/ra-core/src/controller/useReference.ts
- packages/ra-core/src/dataProvider/useGetList.ts
- packages/ra-core/src/dataProvider/useGetMany.ts
- packages/ra-core/src/dataProvider/useGetManyAggregate.ts
- packages/ra-core/src/dataProvider/useGetManyReference.ts
- packages/ra-core/src/dataProvider/useGetOne.ts
- packages/ra-core/src/dataProvider/useInfiniteGetList.ts
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
Many of our hooks do not allow to provide the `Error` type.
Allow providing error type in dataProvider and controllers hooks
> [TypeScript] Allow providing error type in dataProvider and controllers hooks

- docs/TimeInput.md
We recommend a community package that is not maintained since 7 years.
Remove this line from the doc
> [Doc] Remove mention of obsolete time input community package

- docs/Vite.md
Replaces https://github.com/marmelab/react-admin/pull/9332 since we no longer have issues in !9332
In Vitest 3, the browser mode is finally added. We don't need to rely on jsdom and module resolution for server. Everything will be tested and run exactly the same in a browser.
> Add vitest tutorial

- docs/ReferenceManyToManyInput.md
> Fix the `<ReferenceManyToManyInput mutationOption={{onError}}>` doc

- packages/ra-data-localforage/README.md
- packages/ra-data-localforage/src/index.stories.tsx
- packages/ra-data-localforage/src/index.ts
Setting up the `ra-data-local-forage` dataProvider is cumbersome.
You have to manage a state and initialize it in a `useEffect`.
Simplify the setup.
https://react-admin-storybook-git-ra-data-localforage-s-a105c6-marmelab.vercel.app/?path=/story/ra-data-local-forage--basic
- build the project
- create a new react-admin app using the fakerest dataprovider
- copy the `ra-data-local-forage` inside the new project `node_modules`
- Setup the dataProvider instead of fakerest
> Simplify ra-data-local-forage setup

- packages/ra-core/src/routing/index.ts
- packages/ra-core/src/routing/useSplatPathBase.ts
- packages/ra-ui-materialui/src/detail/Tab.tsx
- packages/ra-ui-materialui/src/detail/TabbedShowLayout.stories.tsx
- packages/ra-ui-materialui/src/form/FormTabHeader.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
- packages/ra-ui-materialui/src/form/TabbedFormView.tsx
- test-setup.js
Fix #10458
React-router v7 reintroduced the change they introduced in 6.19.0, which was reverted in 6.20.1 due to it causing [issues](https://github.com/remix-run/react-router/issues/11052) in many apps, including react-admin.
Introduce `useSplatPathBase` hook, which allows to compute the splat route's base path, allowing react-admin to create absolute paths for tabs (as opposed to relative paths previously), which will work both with react-router v6 and v7.
Wrap the `<Admin>` in the simple example with a `<HashRouter>`.
Then, you can set `<HashRouter future={{ v7_relativeSplatPath: true }}>` to test with the feature enabled (which is the default in v7), or set it to `false` to disable the feature.
Then, use `PostEdit` and `PostShow` to confirm the tabs are working OK.
Also, please make …
> Fix TabbedForm and TabbedShowLayout with react-router v7

- docs/Vite.md
- packages/create-react-admin/templates/common/vite.config.ts
- packages/create-react-admin/templates/ra-data-fakerest/vite.config.ts
In production, even with sourcemaps enabled, only the ESM sources are loaded in the devtool.
- Document how to enable sourcemaps with TS source files
- Do it automatically in new create-react-admin apps
- `make build-create-react-admin`
- `./node_modules/.bin/create-react-admin myadmin --data-provider ra-data-fakerest --auth-provider local-auth-provider --install npm`
- `cd myadmin`
- `npm run dev`: verify that debugging react-admin files still happen in TS files
- `npm run build && npm run serve`: verify that debugging react-admin files still happen in TS files
> [Doc] Document how to have sourcemaps in production

- packages/ra-core/src/auth/useHandleAuthCallback.spec.tsx
- packages/ra-core/src/auth/useHandleAuthCallback.ts
Many authentication providers do not accept calling their methods for validating authentication callbacks multiple times. We had the case with `ra-auth-auth0` and `ra-keycloak` (maybe even `ra-supabase`).
Our solution until now was to implement the necessary logic in the `authProvider` implementation (storing ongoing promise in the `authProvider` closure). This is fine but it means custom implementations must do it themselves too and this is not trivial for many.
Make the `useHandleCallback` resilient to `StrictMode`. Implement the logic that won’t call `authProvider.handleCallback` if another call is already ongoing.
Revert the fix in [useHandleAuthCallback.ts](https://github.com/marmelab/react-admin/compare/fix/useHandleCallback_compatible_StrictMode?expand=1#diff-4713b2324817c4e79d55087 …
> Make useHandleCallback compatible with StrictMode

- test-setup.js
Add a `console.error('foo', 'bar')` in a test and run it.
> Make the CI fail on `console.error` in tests

- packages/create-react-admin/src/cli.tsx
To get a non-interactive \`create-react-admin\`, one must pass all options:
```
npx create-react-admin my-admin -- \
--data-provider none
--auth-provider none
--resource skip
--install skip
```
This is super verbose, especially in documentation.
Add a `--basic` option that replaces all the others
```
npm init react-admin test-admin1 -- --basic
```
On the `xx` branch, build the cli:
```
make build-create-react-admin
```
Create a new project with npx:
```
npx create-react-admin test-admin-npx -- \
--data-provider none
--auth-provider none
--resource skip
--install skip
```
Create another one with the local version of the cli:
```
./node_modules/.bin/create-react-admin test-admin-local --basic
```
Compare folders:
```
diff test-admin-npx test-admin-local
```
- ~[ ] The PR includes **unit …
> Add a `--basic` flag to the `create-react-admin` package to skip interactive steps

- docs/useList.md
> [Doc] Fix useList usage contains incorrect code snippet

- examples/crm/vite.config.ts
- examples/simple/vite.config.ts
The Simple and CRM demos have a Vite config that no longer works with Node 18
Apply the same fix as https://github.com/marmelab/react-admin/commit/d095b8f4b4d53c068367b29f7abee51311507146
Run the demos locally
`make run`
`make run-crm`
> [Demo] Fix vite config in Simple and CRM demos

- docs/DatagridAG.md
DatagridAG docs were updated to add a Working with Dates section.
Update the OSS docs too.
> [Doc] Add Working with Dates section to DatagridAG docs

- packages/create-react-admin/src/cli.tsx
- packages/create-react-admin/src/generateAppFile.ts
We want that the `basic` flag of the `create-react-admin` downloads the `node_modules` with `npm`
> Make the `basic` flag use `npm`

- examples/demo/vite.config.ts
Although the demo seems to build fine, it actually doesn't work when you run `vite preview`. It seems it loads multiple versions of `react-router`. This is only an issue in our monorepo setup.
Add aliases so that Vite correctly resolve the react-router versions we want in the demo (v7)
- `make run-demo` => check it runs fine in development
- `make build-demo` => check it still builds fine
- `cd examples/demo && yarn preview` => check the production build runs fine
> Fix demo build

- Makefile
- packages/react-admin/package.json
We currently include a copy of the `docs` directory in the published `react-admin` package. This makes it quite heavy and is probably useless.
- remove the command that copy the `docs` directory when building the package.
- remove the `docs` directory from the included files of the `package.json` for `react-admin`
> Remove doc from published react-admin package

- packages/create-react-admin/src/app.tsx
- packages/create-react-admin/src/generateAppFile.ts
Fixes #10493
- `create-react-admin` ignore custom resources when using `ra-data-fakerest`
- The generated `App.tsx` file is incorrectly formatted:
```tsx
import { Admin, Resource, ListGuesser, EditGuesser, ShowGuesser } from 'react-admin';
import { Layout } from './Layout';
import { dataProvider } from './dataProvider';
export const App = () => (
<Admin
layout={Layout}
dataProvider={dataProvider}
>
<Resource name="books" list={ListGuesser} edit={EditGuesser} show={ShowGuesser} />
<Resource name="authors" list={ListGuesser} edit={EditGuesser} show={ShowGuesser} />
</Admin>
);
```
- Allow to override resources by specifying them using the CLI `resource` option
- Fix formatting
1. `make build-create-react-admin install`
2. `./node_modules/.bin/create-react-admin myadmin --data-provider …
> Fix create react admin fakerest

- docs/DateInput.md
- packages/ra-ui-materialui/src/input/DateInput.stories.tsx
- packages/ra-ui-materialui/src/input/DateInput.tsx
Problem is described [here](https://github.com/marmelab/react-admin/issues/10474), there is no way to manipulate the value coming from dataprovider because it will always win
use `format` prop
Tested on storybook
> [DateInput] Update docs to mention `format` prop for timezone adjustment

- docs/CreateDialog.md
- docs/CreateInDialogButton.md
- docs/EditDialog.md
- docs/EditInDialogButton.md
`warnWhenUnsavedChanges`'s EE doc was updated
Update `warnWhenUnsavedChanges`'s doc on dialog forms
> [Doc] Update `warnWhenUnsavedChanges`'s doc on dialog forms

- lerna.json
Lerna doesn't update `yarn.lock` on publish, which leads to having the commit on which the version tag is put fail the CI.
This prevents steps like greenframe and codesandbox update from running.
Fix the lerna configuration.
You can run the following command locally to simulate what lerna does when publishing a new version, without actually publishing it to npm neither pushing the commits to git:
```
./node_modules/.bin/lerna version --force-publish --no-push --no-git-tag-version
```
You will see that with the fixed configuration, the `yarn.lock` is also updated.
> [chore] Fix lerna doesn't update yarn.lock on publish

- docs/DatagridAG.md
EE doc was updated to document `<DatagridAG>` and `<DatagridAGClient>` access control
Backport those doc
> [doc] Backport `<DatagridAG>` and `<DatagridAGClient>` access control's doc

- docs/CreateDialog.md
- docs/CreateInDialogButton.md
- docs/EditDialog.md
- docs/EditInDialogButton.md
- docs/ShowInDialogButton.md
EE doc was updated to document the support of `title={false}` in dialog components
Backport `<XxxxDialog title={null} />`'s doc
> [doc] Backport `title={null}`'s doc on dialog components

- packages/ra-core/src/form/FilterLiveForm.spec.tsx
- packages/ra-core/src/form/FilterLiveForm.stories.tsx
- packages/ra-core/src/form/FilterLiveForm.tsx
- packages/ra-ui-materialui/src/list/filter/FilterLiveForm.stories.tsx
Fixes #10512. It seems that when calling `unset` which remove the property matching the filter input source from the filters, the value get re-added by react-hook-form.
Set the filter value to an empty string which correctly removes it from the filter context.
In ra-core:
- https://react-admin-storybook-8h3fdlb89-marmelab.vercel.app/?path=/story/ra-core-form-filterliveform--parse-format
- Enter a number and removes it character by character until empty
- Enter a number then select the input value and remove it
- Enter a number then click the clear button
In ra-ui-materialui:
- https://react-admin-storybook-8h3fdlb89-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-filter-filterliveform--parse-format
- Enter a number and removes it character by character until empty
- Enter a number …
> Fix FilerLiveForm does not allow to clear filters

- .github/workflows/test.yml
https://github.com/marmelab/react-admin/pull/10514 was not enough to run the CI jobs that are supposed to trigger on a new tag.
The issue is that those jobs depend on the `e-commerce` job, which does not trigger on a new tag.
Also trigger the `e-commerce` job on a new tag.
We could probably test this  with a fake tag, but the change is so simple it can probably wait the next release to be tested.
> [chore] Fix CI jobs that run on new tag

- docs/Features.md
- docs/FormFillerButton.md
- docs/Reference.md
- docs/navigation.html
`ra-ai` introduced a new `<FormFillerButton>` component which is not yet documented in OSS.
Add `<FormFillerButton>` documentation
> [Doc] Add `<FormFillerButton>` documentation

- docs/ArrayInput.md
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
`<ArrayInput disabled>` isn't supported since v5 (see https://marmelab.com/react-admin/Upgrade.html#simpleformiterator-no-longer-clones-its-children). 
Yet the component prop type still supports it, and the documentation says nothing about it. 
This leads to developers wondering why this prop does nothing. 
- Update the type to fail compilation when readOnly or disabled are used
- Update the doc to explain how to disable an ArrayInput
- Fix remaining stories
> Update ArrayInput to throw an error when using outdated disabled prop

- docs/DatagridAG.md
In the `<DatagridAGClient>`'s doc, we speak about the `<DatagridAG>`'s behavior (with access control) instead of the `<DatagridAGClient>`'s behavior.
Fix this typo
> [Doc] Fix `<DatagridAGClient>` access control's doc

- .github/workflows/test.yml
Follow up to https://github.com/marmelab/react-admin/pull/10525
It turns out the CI workflow configuration still contained errors
Fix the remaining configuration mistakes
One way to test is by using https://github.com/nektos/act.
A 'tag pushed' event can be simulated like so:
1. Create a `push_tag_event.json` file:
```json
{
"ref": "refs/tags/v1.0.0",
"ref_type": "tag",
"repository": {
"full_name": "marmelab/react-admin"
},
"event_name": "push"
}
```
2. Edit the workflow jobs so that they don't do too much stuff (typically, only echo something for instance)
3. Run `act` with the event file:
```bash
act -e push_tag_event.json -W .github/workflows/test.yml
```
4. Make sure the `GreenFrame` and `update-sandbox-repository` jobs are triggered
> [chore] Fix CI jobs that run on new tag, again

- packages/create-react-admin/src/cli.tsx
`create-react-admin` does not detect the package manager used to run it correctly.
Leverage the `process.env.npm_config_user_agent` environment variable to detect it, just like [`create-vite`](https://github.com/vitejs/vite/blob/main/packages/create-vite/src/index.ts#L315C36-L315C69)
Difficult to test without a release as you have to modify the global cache of the package manager.
- For bun it's in `$HOME/.bun/install/cache` and the package is unzipped into `create-react-admin@5.6.0@@@1`
- For yarn it's in `$HOME/.yarn/berry/cache` and the package is not unzipped but renamed to `create-react-admin-npm-5.6.0-941ece3bdb-10c0.zip`
> Fix create react admin detect package manager

- packages/create-react-admin/src/cli.tsx
When specifying `supabase` as the `--data-provider` option and `local` as the `--auth-provider` option, `create-react-admin` says it will ignore the `--auth-provider` but actually doesn't.
- `make build-create-react-admin install`
- `/node_modules/.bin/create-react-admin myadmin --data-provider supabase --auth-provider local`
- check that the CLI does not mention anything about how to use the local auth provider
- check that the generated app does not include a custom auth provider
> Fix create-react-admin does not ignore auth-provider when specified and using supabase

- docs/CreateDialog.md
- docs/EditDialog.md
- docs/EditInDialogButton.md
- docs/ShowInDialogButton.md
We have some typos in dialog `title`'s sections
Fix those typos
> [Doc] Fix dialogs `title` doc

- packages/ra-core/src/form/useInput.ts
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
- packages/ra-ui-materialui/src/input/NumberInput.tsx
> Fixed onBlur callback on NumberInput and AutocompleteInput

- docs/ReferenceInput.md
`<ReferenceInput enableGetChoices>` example returns `undefined` when `q` is `undefined`, which will still fire the query (because `enable: undefined`) does not disable the query in react-query. It has to return `false` instead.
Fix the example to return a boolean all the time.
> [Doc] Fix `<ReferenceInput enableGetChoices>` example

- examples/demo/src/layout/Menu.tsx
- examples/demo/src/layout/SubMenu.tsx
- examples/demo/src/themes/themes.tsx
- packages/ra-ui-materialui/src/layout/Sidebar.tsx
- packages/ra-ui-materialui/src/theme/bwTheme.ts
When using the B&W theme, the collapsed menu looks off
Fix the theme.
> Fix collapsed menu in B&W theme

- packages/ra-ui-materialui/src/form/TabbedForm.spec.tsx
- packages/ra-ui-materialui/src/form/TabbedForm.stories.tsx
- packages/ra-ui-materialui/src/form/TabbedFormView.tsx
> Make `<TabbedForm tabs>` use the `onChange` prop

- scripts/release.sh
Release script introduced by https://github.com/marmelab/react-admin/pull/10516 let lerna create the git tag for the version, but the changelog was updated afterwards so it was not included in the tag.
Delete the tag created by lerna, and recreate it ourselves after the changelog was updated.
Cannot really be tested without doing a real release.
However individual commands can be tested manually.
> [chore] Fix release script does not include the changelog in the tag

- docs/ReferenceManyInput.md
- `<ReferenceManyInput>` documentation examples don't explain you have to set the `disableReordering` prop on `<SimpleFormIterator>`
- `<ReferenceManyInput>` documentation does not mention the reordering limitation
Update `<ReferenceManyInput>` documentation to mention it cannot reorder its items and improve the examples.
> [Doc] Update `<ReferenceManyInput>` documentation to mention it cannot reorder its items

- docs/MarkdownInput.md
The version of `dompurify` used by `@toastui/editor` is vulnerable to a cross-site scripting (XSS) attack (see Github security advisory [GHSA-vhxf-7vqr-mrjg](https://github.com/advisories/GHSA-vhxf-7vqr-mrjg)). This vulnerability has been fixed in `dompurify` version 3.2.4. But `@toastui/editor` is not up to date.
Document how to address this vulnerability, by using npm's `override` or yarn's `resolutions` feature to force the installation of a fixed version of `dompurify`.
> [Doc] Update `<MarkdownInput>` doc to address vulnerability in `dompurify`

- packages/ra-ui-materialui/src/theme/ThemeTester.stories.tsx
- packages/ra-ui-materialui/src/theme/bwTheme.ts
Buttons in B&W theme in dark mode aren't visible enough due to a too high transparency of the border.
Decrease the border transparency in dark mode. 
I added a ThemeTester story that allows to test various components in various themes. 
https://react-admin-storybook-git-themetester-marmelab.vercel.app/?path=/story/ra-ui-materialui-theme-themetester--theme-tester
- ~~[ ] The PR includes **unit tests** (if not possible, describe why)~~(only theming)
> Fix B&W theme buttons in dark mode

- packages/create-react-admin/src/generateProject.ts
- packages/create-react-admin/templates/resolutions/package.json
- packages/create-react-admin/templates/yarn/.yarnrc.yml
For some reason, yarn v1 install multiple versions of the dependencies for which we support multiple major versions.
This leads to an error page as soon as you run the generated application.
When the chosen installer is `yarn`, detect the installed version and if it is v1, add resolutions to the generated `package.json` file
- `make build-create-react-admin install`
- `cd ..` Required to avoid yarn errors when it runs in our monorepo
- `./react-admin/.bin/react-admin/node_modules/.bin/create-react-admin myadmin --install yarn`
- `cd myadmin`
- `cat package.json` check resolutions are present
- `yarn run dev` check the app runs
> Fix create-react-admin generated package.json when using yarn

- packages/ra-core/src/controller/list/useInfiniteListController.spec.tsx
- packages/ra-core/src/controller/list/useInfiniteListController.stories.tsx
- packages/ra-core/src/controller/list/useListController.stories.tsx
- packages/ra-core/src/i18n/useTranslateLabel.ts
- packages/ra-core/src/util/FieldTitle.tsx
- packages/ra-ui-materialui/src/layout/AppBar.tsx
- packages/ra-ui-materialui/src/layout/CardContentInner.tsx
- packages/ra-ui-materialui/src/layout/DeviceTestWrapper.tsx
- packages/ra-ui-materialui/src/layout/ThemeTestWrapper.tsx
- packages/ra-ui-materialui/src/list/datagrid/Datagrid.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridCell.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.spec.tsx
- packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx
- packages/ra-ui-materialui/src/list/datagrid/index.ts
- packages/ra-ui-materialui/src/list/datagrid/types.ts
- packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
- packages/ra-ui-materialui/src/list/filter/FilterButtonMenuItem.tsx
- packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
`JSX.Element` is type JSX which is not tied to react (JSX can be used in other frameworks). We should use the correct types from React.
- Replace usage of `JSX.Element` by their React equivalent.
- Use `ReactNode` instead of `ReactElement` where it makes sense.
> [TypeScript] Remove usage of JSX.Element

- packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx
- packages/ra-ui-materialui/src/button/BulkExportButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
- packages/ra-ui-materialui/src/button/Button.tsx
- packages/ra-ui-materialui/src/button/CloneButton.tsx
- packages/ra-ui-materialui/src/button/CreateButton.tsx
- packages/ra-ui-materialui/src/button/DeleteButton.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/DeleteWithUndoButton.tsx
- packages/ra-ui-materialui/src/button/EditButton.tsx
- packages/ra-ui-materialui/src/button/ExportButton.tsx
- packages/ra-ui-materialui/src/button/ListButton.tsx
- packages/ra-ui-materialui/src/button/RefreshButton.tsx
- packages/ra-ui-materialui/src/button/RefreshIconButton.tsx
- packages/ra-ui-materialui/src/button/SaveButton.tsx
- packages/ra-ui-materialui/src/button/ShowButton.tsx
- packages/ra-ui-materialui/src/button/SortButton.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/UpdateWithUndoButton.tsx
There's no reason to not accept a `ReactNode` for the `icon` prop. This would allow to pass `null` to remove the icon altogether.
Fix the icon prop type.
> [TypeScript] Fix buttons `icon` prop type

- packages/ra-ui-materialui/src/layout/Error.tsx
The styled component in error.tsx should accept sxprops to customize its styles
> [typescript] Add SxProps to Error component

- docs/DateTimeInput.md
- packages/ra-ui-materialui/src/input/DateTimeInput.stories.tsx
Fix https://github.com/marmelab/react-admin/issues/10375
Document how to return `Date` object with `<DateTimeInput>`.
And add a story to prove it works.
http://localhost:9010/?path=/story/ra-ui-materialui-input-datetimeinput--as-date-object
> [Doc] Document how to return `Date` object with `<DateTimeInput>`

- docs/CreateReactAdmin.md
- packages/create-react-admin/README.md
`create-react-admin` doc is not up to date
Rewrite `create-react-admin` documentation
> [Doc] Rewrite `create-react-admin` documentation

- docs/Reference.md
- docs/Tree.md
- docs/TreeWithDetails.md
- docs/navigation.html
ra-tree v10 was just published and their new doc too
Backport doc
> [Doc] Backport ra-tree v10 doc

- packages/ra-core/src/routing/useRedirect.spec.tsx
- packages/ra-core/src/routing/useRedirect.stories.tsx
- packages/ra-core/src/routing/useRedirect.ts
Fixes #10489
- check for leading `/` and only add one when needed
- https://react-admin-storybook-dhj951475-marmelab.vercel.app/?path=/story/ra-core-routing--use-redirect
> Fix useRedirect might include two slashes in the final pathname

- packages/ra-ui-materialui/src/input/InputHelperText.tsx
- packages/ra-ui-materialui/src/input/TextInput.stories.tsx
Fixes #10562
Use the story control to check the last input behavior:
https://react-admin-storybook-6oudqo8iz-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-textinput--helper-text
> Fix helperText has wrong height when passing an empty string

- packages/create-react-admin/src/generateProject.ts
Fixes #10567
Add a project generation step specific to fakerest that generate a `data.json` file for the provided resources.
- `make build-create-react-admin install`
- `./node_modules/.bin/create-react-admin myadmin --data-provider fakerest --resource posts --resource comments` should still generate a working app with tests
- `./node_modules/.bin/create-react-admin myadmin --data-provider fakerest --resource books --resource authors` should generate a working app with a `data.json` file containing entries for `books` and `authors` but no tests.
> Fix create-react-admin should correctly generate data.json for fakerest

- .env.template
- scripts/release.sh
There are still too many manual steps when releasing a new react-admin version
Automate one more step: building and testing enterprise packages automatically when possible.
You can override the enterprise directory path by setting the `RA_ENTERPRISE_PATH` environment variable.
Then run:
```
```
When this is done, don't forget to revert the commit created by lerna to update the versions:
```
git reset --hard HEAD~1
```
> [chore] Improve release script by  automating enterprise packages tests

- .env.template
- scripts/copy-ra-oss-docs.sh
- scripts/release.sh
There are still too many manual steps when releasing a new react-admin version.
Follow #10574 
Automate one more step: updating the documentation automatically when possible:
- Copy the new doc to the `react-admin-doc` sibling directory if it exists
- Update the latest version in `react-admin-doc/_data/versions.yml`
- Add a new minor entry if necessary in `react-admin-doc/_data/versions.yml`
You can override the documentation directory path by setting the `RA_DOC_PATH` environment variable.
Then run:
``` …
```
> [chore] Improve release script by automating documentation update

- scripts/release.sh
Running the release script in dry mode actually pushes the documentation changes.
Skip this step in dry mode
> [chore] Skip pushing the documentation changes in release script when in dry mode

- scripts/release.sh
When the release script create the tag, it opens the editor to enter a message.
Add the message automatically
> [chore] Add the tag message in release script

- package.json
- scripts/release.sh
- scripts/update-create-react-admin-deps.ts
When we release a new minor version, we have to manually update `create-react-admin` templates dependencies.
- Automatically update create-react-admin templates when releasing a new minor version
Then run:
```
```
Select the new minor version when Lerna asks for it.
When this is done, don't forget to revert the commit created by lerna to update the versions:
```
git reset --hard HEAD~1
```
> [chore] Automatically update create-react-admin templates when releasing a new minor version

- scripts/release.sh
The script adds the latest minor version in the list of previous minor versions
Add the previous minor in the list of previous minor versions
Then run:
```
```
Select the new minor version when Lerna asks for it.
When this is done, don't forget to revert the commit created by lerna to update the versions:
```
git reset --hard HEAD~1
```
> Fix release script add wrong minor in documentation versions list

- docs/AutoSave.md
Missing documentation for warnWhenUnsavedChanges on `<AutoSave>`
Add the doc 
Read the doc
> doc: add documentation for warnWhenUnsavedChanges

- docs/EditInDialogButton.md
- docs/ShowInDialogButton.md
Missing documentation for emptyWhileLoading prop for EditInDialogButton
Add missing doc.
> doc: add emptyWhileLoading prop doc

- packages/ra-i18n-i18next/README.md
Documentation of ra-i18n-i18next talk about `convertRaMessagesToI18next`  instead of `convertRaTranslationsToI18next`, and the example has ts errors.
change the name of the function, fix the example and check the ts error are gone.
Read the doc
> fix: use correct function name `convertRaTranslationsToI18next`

- packages/ra-ui-materialui/src/field/ChipField.spec.tsx
- packages/ra-ui-materialui/src/field/ChipField.stories.tsx
- packages/ra-ui-materialui/src/field/ChipField.tsx
When passing an empty value (undefined or null), a `<Chip>` is rendered with nothing in it.
If the value is an empty string, render the emptyText instead (just like the DateField does).
If the emptyText is an empty string, the component should return null.
- Unit tests should be green.
- https://react-admin-storybook-7jlxn1ynw-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-chipfield--basic
> feat: handle empty `emptyText` for `<ChipField>`

- Makefile
- Updated the description for `build-crm` in Makefile.
- Previously labeled as "run the crm example", but it actually builds the example.
- Now correctly labeled as "build the crm example".
> [chore] Fix incorrect description for build-crm in Makefile

- packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
When you add some inputs such as the `MarkdownInput` from `ra-enterprise`, they may overflow horizontally.
Add a `min-width: 0` to the inputs containers to ensure they adapt to their children size. 
See https://www.bigbinary.com/blog/understanding-the-automatic-minimum-size-of-flex-items#the-solutions
I can't reproduce this issue with any other inputs than `MarkdownInput` but I tested this solution in the enterprise storybook. It does not have any other side effects.
> Fix SimpleFormIterator does not display some components correctly

- docs/Admin.md
- docs/DataProviderWriting.md
- docs/DataProviders.md
Some users do not know that throwing an httpError will show a notification and it’s is not mentioned in the doc
Mention it
> [Doc] Mention that `httpError` triggers a notification

- docs/List.md
In the List page of the doc, the link to useQuery documentation is broken.
> [Doc] fix broken link to useQuery documentation

- packages/ra-input-rich-text/src/RichTextInput.stories.tsx
- packages/ra-input-rich-text/src/RichTextInput.tsx
This is probably the only input that isn’t full width by default. As we can’t override its props with the theme, it’s cumbersome.
- Make it full width by default (in a minor)
- Fix the stories in dark mode
> Make `<RichTextInput>` fullWidth by default

- docs/FAQ.md
Users are still regularily getting errors because of duplicate version of react-hook-form or react-router.
Example: https://stackoverflow.com/q/79464423/3975522
Create an entry in the [FAQ](https://marmelab.com/react-admin/FAQ.html) for these issues.
- `make doc`
- http://0.0.0.0:4000/FAQ.html#i-get-an-error-about-control-being-null
> [Doc] Add a FAQ entry for duplicate react-hook-form versions

- packages/ra-core/src/dataProvider/useGetOne.ts
Using `useGetOne` with a `null` (or `undefined`) `id`, and providing the `enabled` option (e.g. setting it to `false` to manually trigger the query with `refresh()`) will return a never resolving `Promise`, hence keeping the global query status loading forever.
This `Promise` was added to solve a TS complaint when adding strict null checks ([original PR](https://github.com/marmelab/react-admin/pull/9971)). But as stated this Promise will never resolve.
Instead, we can replace this by a Promise that will reject instantly, saying `useGetOne` requires `id` to be defined.
```ts
const { refetch } = useGetOne("url", { id: null }, { enabled: false });
refetch();
```
> Fix `useGetOne` returns a never resolving Promise when `id` is `null`

- docs/js/ra-doc-exec.js
- docs/js/ra-navigation.js
The tips don't load in production due to absolute paths.
Fix the paths
- `make doc`: tips should still load
- check in production :scream:
> [Doc] Fix tips loading in production

- packages/create-react-admin/templates/pnpm/vite.config.ts
The `vite.config.ts` file for pnpm has an unnecessary import.
Remove it.
> [chore] Fix create-react-admin pnpm template

- scripts/copy-ra-oss-docs.sh
The release script does not copy all assets
Make it copy all assets
> Fix release script does not update documentation completely

- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx
Instead of all other inputs, `ArrayInput` doesn't provide a default `defalutValue`.
This is an issue when calling the react-hook-form `reset` method as react-hook-form will not reset fields that don't have default values.
Apply a default `defalutValue` on `ArrayInput`
> Fix: Apply a default `defalutValue` on `ArrayInput`

- docs/OldVersions.md
- scripts/release.sh
This is an unnecessary manual step.
Automate it
Then run:
```
```
Select the new minor version when Lerna asks for it.
When this is done, don't forget to revert the commit created by lerna to update the versions:
```
git reset --hard HEAD~1
```
> Improve release script old version doc

- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Closes https://github.com/marmelab/react-admin/issues/10645
Apply styling workaround automatically (i.e. set width of `<legend>` to 0)
http://localhost:9010/?path=/story/ra-ui-materialui-input-autocompleteinput--outlined-no-label
> Fix `<AutocompleteInput>` has hole in the outline when no `label`

- packages/ra-ui-materialui/src/auth/AuthLayout.stories.tsx
- packages/ra-ui-materialui/src/auth/AuthLayout.tsx
- packages/ra-ui-materialui/src/auth/index.ts
When building several pages linked to authentication, we have to repeat Several elemens between pages.
- https://react-admin-storybook-hczd4x6ow-marmelab.vercel.app/?path=/story/ra-ui-materialui-auth-authlayout--basic
> Introduce `<AuthLayout>`

- docs/TranslationLocales.md
The current Portuguese (pt-pt) translation could benefit from improvements and updates.  
This PR updates the Portuguese (pt-pt) translation with:
- Refined and merged content from:
- [@henriko202](https://github.com/henriko202)'s ra-language-portuguese
- [@gucarletto](https://github.com/gucarletto)'s ra-language-pt-br
- Additional internal improvements used in production at our company
- Published as an NPM package here: [`@acmp5/ra-language-portuguese-pt`](https://www.npmjs.com/package/@acmp5/ra-language-portuguese-pt)
1. Replace the current pt-pt translation with this version.
2. Run the admin interface with Portuguese (pt-pt) as the selected locale.
3. Navigate through common pages (list, show, edit, create, etc.) to verify translation quality and consistency.
> Update TranslationLocales.md (Portuguese pt-pt)

- packages/ra-core/src/form/useApplyInputDefaultValues.ts
- packages/ra-core/src/form/useInput.spec.tsx
- packages/ra-core/src/form/useInput.stories.tsx
When a record has a field set to `null`, `useInput` overrides it with its default value.
Don't override `null`
- https://react-admin-storybook-8z1fjtwi0-marmelab.vercel.app/?path=/story/ra-core-form-useinput--default-value
- Use the controls that define the initial record value
> Fix `useInput` default value overrides `null`

- docs/Remix.md
We document how to setup Vite for easier debugging in production. We should do the same for Remix
Add a section similar to the one in Vite documentation
> [Doc] Document how to setup Remix for production debugging

- docs/Forms.md
- docs/Inputs.md
#10665 revealed we were not very clear about the cases where default values applies.
Improve documentation
> [Doc] Explain how React admin handles empty values

- packages/ra-ui-materialui/src/detail/EditGuesser.tsx
When using `EditGuesser` in a module's default export we get the following TS error:
```
Default export of the module has or is using private name 'EditGuesserProps'.
```
Export `EditGuesserProps`.
This can be reproduced in the simple demo, by replacing the content of the file `examples/simple/src/posts/index.tsx`:
```tsx
import BookIcon from '@mui/icons-material/Book';
import PostCreate from './PostCreate';
import PostEdit from './PostEdit';
import PostList from './PostList';
import PostShow from './PostShow';
import { EditGuesser } from 'react-admin';
export default {
list: PostList,
create: PostCreate,
edit: EditGuesser,
show: PostShow,
icon: BookIcon,
recordRepresentation: 'title',
};
```
> Fix TS error when using `EditGuesser` in module's default export

- docs/CreateDialog.md
- docs/EditDialog.md
Dialog Forms examples still use the v4 syntax for the `hasCreate` prop.
Use the v5 syntax
> [Doc] Fix Dialog Forms examples regarding `hasCreate`

- packages/ra-ui-materialui/src/field/RichTextField.spec.tsx
- packages/ra-ui-materialui/src/field/RichTextField.stories.tsx
- packages/ra-ui-materialui/src/field/RichTextField.tsx
`<RichTextField>` does not render `emptyText` when the value is equal to `''`.
Fix `<RichTextField>` to render `emptyText` when the value is an empty string.
Unit test + new Story
> Fix `<RichTextField>` should render `emptyText` when value is an empty string

- docs/Architecture.md
- docs/Buttons.md
- docs/Confirm.md
- packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx
- packages/ra-core/src/core/useGetRecordRepresentation.ts
- packages/ra-language-english/src/index.ts
- packages/ra-language-french/src/index.ts
- packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.stories.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.spec.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.stories.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.tsx
- packages/ra-ui-materialui/src/layout/Confirm.tsx
`<DeleteButton>` and `<UpdateButton>` confirmation dialog titles show a very generic message but we can do better thanks to the record representation.
- If a resource has a string record representation, use it.
- To avoid breaking changes, introduce new translation keys where needed
- https://react-admin-storybook-j5tx6l6fc-marmelab.vercel.app/?path=/story/ra-ui-materialui-button-deletewithconfirmbutton--basic
- https://react-admin-storybook-j5tx6l6fc-marmelab.vercel.app/?path=/story/ra-ui-materialui-button-deletewithconfirmbutton--no-record-representation
- https://react-admin-storybook-j5tx6l6fc-marmelab.vercel.app/?path=/story/ra-ui-materialui-button-deletewithconfirmbutton--with-custom-dialog-content
- https://react-admin-storybook-j5tx6l6fc-marmelab.vercel.app/?path=/story/ra-ui-mater …
> Improve `<DeleteButton>` and `<UpdateButton>` confirmation wording using record representation

- packages/ra-ui-materialui/src/detail/EditGuesser.spec.tsx
- packages/ra-ui-materialui/src/detail/ShowGuesser.spec.tsx
- packages/ra-ui-materialui/src/detail/showFieldTypes.tsx
- packages/ra-ui-materialui/src/list/ListGuesser.spec.tsx
The console.log for reference arrays is wrong:
```tsx
<ReferenceArrayField source="tags_ids" reference="tags"><TextField source="id" /></ReferenceArrayField>
```
It should be:
```tsx
<ReferenceArrayField source="tags_ids" reference="tags" />
```
> Fix `<ShowGuesser>` print incorrect code for reference arrays

- docs/useNotify.md
The `autohideDuration: 0` is wrong, it should be `autohideDuration: null`
> [Doc] Fix `useNotify` custom notification with close example

- packages/create-react-admin/templates/common/package.json
- packages/create-react-admin/templates/resolutions/package.json
#10639 brought support for MUI v7.
To help minimizing technical debt, all new react-admin apps should start using that version right away.
But create-react-admin still uses MUI v6 by default.
Upgrade create-react-admin to generate projects that use MUI v7 by default.
**Testing with yarn**
It's the easiest way to test, since we force the version of MUI packages using yarn resolutions.
1. `make build-create-react-admin`
2. `./packages/create-react-admin/node_modules/.bin/create-react-admin my-admin -i`
3. select yarn as package manager
4. `cd my-admin`
5. `yarn run dev`
6. Make sure you are using MUI v7 (`yarn list @mui/material`) and that the app runs fine
**Testing with npm/pnpm/bun**
It's more complex to test, because react-admin 5.7.3 still requires MUI <= 6, and react-admin 5.8.0 has …
> create-react-admin: Upgrade to MUI v7

- packages/ra-ui-materialui/src/layout/Loading.tsx
`Loading` component is difficult to re-use because it has a hard-coded one second timeout inside of it.
Supersedes #10687
Add a `timeout` prop default to one second to make it more flexible
> Fix Loading component timeout

- packages/ra-core/src/controller/create/useCreateController.security.stories.tsx
- packages/ra-core/src/controller/create/useCreateController.spec.tsx
- packages/ra-core/src/controller/create/useCreateController.ts
- packages/ra-core/src/controller/edit/useEditController.security.stories.tsx
- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/controller/list/useInfiniteListController.spec.tsx
- packages/ra-core/src/controller/list/useInfiniteListController.stories.tsx
- packages/ra-core/src/controller/list/useInfiniteListController.ts
- packages/ra-core/src/controller/list/useListController.security.stories.tsx
- packages/ra-core/src/controller/list/useListController.spec.tsx
- packages/ra-core/src/controller/list/useListController.stories.tsx
- packages/ra-core/src/controller/list/useListController.ts
- packages/ra-core/src/controller/show/useShowController.security.stories.tsx
- packages/ra-core/src/controller/show/useShowController.spec.tsx
- packages/ra-core/src/controller/show/useShowController.ts
Setting `disableAuthentication` to `true` should prevent all calls to the authProvider, i.e. calls to `checkAuth` but also `canAccess`.
However in some cases, if `checkAuth` was already called earlier and the result is already in the react-query cache, a call to `canAccess` might still be fired.
Fix the condition under which `canAccess` is called from the controllers.
Unit tests and stories were added in this PR.
> Fix `canAccess` is called even when `disableAuthentication` is `true`

- docs/AutocompleteInput.md
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Current examples of <AutocompleteInput create> in the docs leverage useCreate, and require calling create manually with data coming from self-managed controlled inputs.
It’s actually simpler to leverage <CreateBase>, which removes the need to call create directly, and opens the ability to use <Form> along with RA Input components.
Update the doc examples to use <CreateBase> instead.
the story to test: http://localhost:9010/?path=/story/ra-ui-materialui-input-autocompleteinput--inside-reference-input-with-creation-support
> [Doc] improve AutocompleteInput create example

- docs/AutocompleteArrayInput.md
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
Current examples of <AutocompleteArrayInput create> in the docs leverage useCreate, and require calling create manually with data coming from self-managed controlled inputs. 
https://marmelab.com/react-admin/AutocompleteArrayInput.html#creating-new-choices:~:text=OptionRenderer%20/%3E%3B-,Creating%20New%20Choices,-The%20%3CAutocompleteArrayInput%3E
It’s actually simpler to leverage <CreateBase>, which removes the need to call create directly, and opens the ability to use <Form> along with RA Input components.
http://localhost:9010/?path=/story/ra-ui-materialui-input-autocompletearrayinput--inside-reference-array-input-with-creation-support
Also, please make sure to read the [contributing …
> [DOC] Rewrite autocompletearray input create doc example

- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.spec.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.stories.tsx
- packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.spec.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.stories.tsx
- packages/ra-ui-materialui/src/button/UpdateWithConfirmButton.tsx
#10654 introduced an issue: when passing string to the `title` or `content` props that are not translation keys, the default translation is displayed.
Don't pass a default translation when those props are provided.
- https://react-admin-storybook-j1btyffi3-marmelab.vercel.app/?path=/story/ra-ui-materialui-button-deletewithconfirmbutton--with-custom-title-and-content
- https://react-admin-storybook-j1btyffi3-marmelab.vercel.app/?path=/story/ra-ui-materialui-button-updatewithconfirmbutton--with-custom-title-and-content
> Fix `<Confirm>` ignore simple string `title` and `content` props

- docs/SelectInput.md
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
Current examples of <SelectInput create> in the docs leverage useCreate, and require calling create manually with data coming from self-managed controlled inputs. 
https://marmelab.com/react-admin/SelectInput.html#create
It’s actually simpler to leverage <CreateBase>, which removes the need to call create directly, and opens the ability to use <Form> along with RA Input components.
http://localhost:9010/?path=/story/ra-ui-materialui-input-selectinput--inside-reference-input-with-creation-support
> [DOC] selectInput create example + storie

- docs/SelectArrayInput.md
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
Current examples of <SelectArrayInput create> in the docs leverage useCreate, and require calling create manually with data coming from self-managed controlled inputs. https://marmelab.com/react-admin/SelectInput.html#create
It’s actually simpler to leverage <CreateBase>, which removes the need to call create directly, and opens the ability to use <Form> along with RA Input components.
http://localhost:9010/?path=/story/ra-ui-materialui-input-selectarrayinput--inside-reference-array-input-and-creation-support
> [DOC] Rewrite select array input create doc

- docs/CreateReactAdmin.md
Documentation says we can use either `npx` or `npm create` with create-react-admin. However newcomers may get confused when passing additional arguments to the CLI, as both commands have a different syntax.
Document this gotcha and provide an example.
> [Doc] Document how to pass extra options to create-react-admin when using npm create

- packages/ra-ui-materialui/src/form/SimpleForm.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/DateInput.stories.tsx
- packages/ra-ui-materialui/src/input/DateInput.tsx
- packages/ra-ui-materialui/src/input/DateTimeInput.stories.tsx
- packages/ra-ui-materialui/src/input/DateTimeInput.tsx
- packages/ra-ui-materialui/src/input/NullableBooleanInput.stories.tsx
- packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
- packages/ra-ui-materialui/src/input/NumberInput.stories.tsx
- packages/ra-ui-materialui/src/input/NumberInput.tsx
- packages/ra-ui-materialui/src/input/TimeInput.stories.tsx
- packages/ra-ui-materialui/src/input/TimeInput.tsx
- packages/ra-ui-materialui/src/input/inputs.stories.tsx
Outlined inputs with no label show a gap in the outline. This prevents form layouts where the label is on the side. 
Apply the same fix to other inputs than TextInput. And now we can have side labels:
- ~~[ ] The PR includes **unit tests**~~ (UI only)
> Fix outlined inputs when label is false

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- docs/SelectArrayInput.md
- docs/SelectInput.md
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
- `<AutocompleteArrayInput>` and `<SelectArrayInput>` _**Creating New Choices**_ sections were updated in https://github.com/marmelab/react-admin/pull/10711 and https://github.com/marmelab/react-admin/pull/10700, but the `create` sections were forgotten
- The code can be simplified by passing `onCreate` directly to `onSuccess`
- Some import statements were wrong
All these issues were fixed in the docs and stories.
`make storybook` and test stories like `InsideReferenceInput...`
> [Doc] Fix remaining `<AutocompleteArrayInput>` and `<SelectArrayInput>` `create` examples

- packages/create-react-admin/src/cli.tsx
If I run `npx create-react-admin --help`, the help view will be displayed.
If I run `npx create-react-admin my_project --help`, the help view won’t be displayed. We will directly create your new project
Make `--help` override every options
- run `npx create-react-admin my_project --help` and see that the project is created
- run `make build-create-react-admin` and `./react-admin/node_modules/.bin/create-react-admin my-admin --help` and see that the project is **not** created but the help flag is now usefull
- ~~[ ] The **documentation** is up to date~~
> Fix `create-react-admin --help` does not show help consistently

- packages/ra-core/src/form/choices/useChoices.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
Fix https://github.com/marmelab/react-admin/issues/8402
Using `<AutocompleteInput>` with `optionValue` and either `create` or `onCreate` logs a React warning in the console when rendering the _create_ option:
```
Warning: Each child in a list should have a unique "key" prop.
```
Fix the option items key to support both options with the `optionValue` (e.g. `'_id'`) as `key`, but also the _create_ option which always uses `'id'` as `key`.
1. Open http://localhost:9010/?path=/story/ra-ui-materialui-input-autocompleteinput--on-create&args=optionValue:_id
2. Type something to see the _create_ option
3. Make sure there are no errors in the console about 'Each child in a list should have a unique "key" prop.'
Also, please make sure to read the [contributing …
> Fix `<AutocompleteInput>` with `optionValue` and create raises a React warning

- docs/SelectInput.md
The documentation has a typo.
Correct the typo.
Check the documentation with the code.
> fix: Typo in disabled choices example

- docs/AutoPersistInStore.md
The EE doc was updated
Update the OSS one
- ~~[ ] The PR includes **unit tests** (if not possible, describe why)~~
- ~~[ ] The PR includes one or several **stories** (if not possible, describe why)~~
> [Doc] Backport `AutoPersistInStore` doc update

- docs/Fields.md
Add a new third-party component huyanhvn/react-admin-clipboard-field.
None. This is just a suggestion.
Hello team, I've created this wrapper for TextField that copies the text into clipboard. I've been finding it quite useful. If you think it can be useful for others too, please accept this suggestion into the docs. Thank you.
Just copy `src/clipboard-field.tsx` to your source directory and use ClipboardField anywhere you would use a TextField.
> [Doc] Add a new third-party component `huyanhvn/react-admin-clipboard-field`

- docs/CreateReactAdmin.md
- docs/Tutorial.md
- packages/create-react-admin/README.md
- packages/create-react-admin/src/cli.tsx
`yarn create react-admin@latest` doesn't work but we document it
document `yarn create react-admin@latest` instead
> [Doc] Remove bad indication for "yarn create react-admin@latest"

- packages/ra-data-local-forage/src/index.ts
- packages/ra-data-local-storage/src/index.ts
Most JavaScript objects inherit the properties of the built-in Object.prototype object. Prototype pollution is a type of vulnerability in which an attacker is able to modify Object.prototype. Since most objects inherit from the compromised Object.prototype object, the attacker can use this to tamper with the application logic, and often escalate to remote code execution or cross-site scripting.
> Fix potential prototype-polluting assignment in `ra-data-local-storage`

- packages/ra-core/src/auth/useLogout.ts
The e-commerce demo was rendering a blank page with many redirects to the logout page when loading the page for the first time. After a many seconds, the login form would render due to an `history.pushState` abuse.
Delay the store to avoid a race condition in `useLogout` that would cause the `CoreAdminRoutes` component to rerender the `LogoutOnMount` component leading to an infinite loop.
Start the e-commerce demo with the following command:
```sh
make run-demo
```
The login page should load fast and no warning about `history.pushState` should be seen in the console.
> Fix(logout): avoid an infinite loop when loading the demo apps for the first time

- packages/ra-i18n-i18next/src/convertRaTranslationsToI18next.ts
Outdated mention of `convertRaMessagesToI18next`, to rename to `convertRaTranslationsToI18next`.
Rename `convertRaMessagesToI18next` to `convertRaTranslationsToI18next`.
> Rename convertRaMessagesToI18next to convertRaTranslationsToI18next

- docs/DataTable.md
Some videos in DataTable docs are not working.
Fix videos file names.
> Fix videos in DataTable docs

- packages/ra-core/src/util/Ready.tsx
Images in buttons are not centered. I think it only occurs when setting up React Admin without using create-react-admin. I saw this using shadcn-admin-kit.
Add margin auto and ensure display block (display block wasn't actually required in my case but it's probably safer to enforce it).
Setup a shadcn admin kit project with this app:
```tsx
import { Admin } from "@/components/admin";
function App() {
return <Admin></Admin>;
}
export default App;
```
> Fix image alignment in ready page in some contexts

- docs/Resource.md
- packages/ra-core/src/core/Resource.spec.tsx
- packages/ra-core/src/core/Resource.stories.tsx
- packages/ra-core/src/core/Resource.tsx
- packages/react-admin/src/Resource.stories.tsx
If a resource declares both a list view and an edit view
```tsx
<Resource name="posts" list={PostList} edit={PostEdit} />
```
Then it's impossible to declare other routes (such as the create or show routes) from within the list view, because they overlap with the route declared for the edit view.
This prevents notably from being able to use a CreateDialog with a regular Edit view.
Hence this note in the [EE doc](https://react-admin-ee.marmelab.com/documentation/ra-form-layout#basic-usage-based-on-routing):
> **Note**: You can't use the `<CreateDialog>` and have a standard `<Edit>` specified on your `<Resource>`, because the `<Routes>` declarations would conflict. If you need this, use the `<CreateInDialogButton>` instead.
Do not register the edit route if the location matches the create …
> Fix limitation preventing to declare create and show routes from the list view

- packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx
- packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
Undefined redirectTo values throws error
Fix #10177 
Create a handleRedirect function to properly handle either valid URL or undefined URLS
Follow steps from #10177 
> fix(useLogoutAccessDenied): handle errors without redirect

- package.json
Some tests were not working locally as I have a machine configured in a different language than
Override environment to always use `LANG=en_US.UTF-8` to run tests in a consistent environment.
`LANG=fr_FR.UTF-8 make test` and it's still working.
> Ensure tests are working in all environments by running them in US english

- packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.stories.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
`useUpdateMany` currently does not support middlewares (only `useUpdate` and `useUpdate` do).
That's an issue for EE components like `BulkUpdateFormButton` + `InputSelectorForm`.
Implement support for middlewares in `useUpdateMany`.
- http://localhost:9010/?path=/story/ra-core-dataprovider-useupdatemany--with-middlewares&args=mutationMode:pessimistic
- play with the controls
- unit tests
> Add support for middlewares to `useUpdateMany`

- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
Fix https://github.com/marmelab/react-admin/issues/10789
With MUI v6 or v7, passing custom input slot props to `<AutocompleteInput>` breaks its autocomplete feature (the dropdown list doesn't open anymore)
With MUI v6 or v7 the InputProps need to be forwarded as `slotProps.input` (as opposed to `InputProps` with MUI v5). With the previous implementation, passing custom `slotProps.input` as `TextFieldProps` would completely override the `slotProps` and hence loose the params injected by MUI.
The solution consists in injecting the input props at both places, to support all MUI versions.
The only catch is we should only pass a `slotProps` prop if one was passed to `TextFieldProps` (i.e. if the user is using the v6/v7 syntax), otherwise we would get a warning about unknow prop `slotProps` …
> Fix `<AutocompleteInput>` should not break when overriding input slot props

- packages/ra-ui-materialui/src/layout/Notification.spec.tsx
- packages/ra-ui-materialui/src/layout/Notification.stories.tsx
- packages/ra-ui-materialui/src/layout/Notification.tsx
When triggering multiple consecutive notifications, only the last one is displayed.
- Unit tests
- https://react-admin-storybook-h3l9433az-marmelab.vercel.app/?path=/story/ra-ui-materialui-layout-notification--consecutive-notifications
> Fix only the last notification is displayed when triggering consecutive notifications

- docs/AuthProviderList.md
Appwrite is mentioned in the DataProvider list but not the AuthProvider list, although ra-appwrite also provides an auth provider.
Add Appwrite to the list of AuthProvider
> [Doc] AuthProvider List: Add Appwrite

- docs/DataTable.md
We mention and link the prop `hiddenColumns` but we didn’t write anything about it.
Write a section of the `DataTable` on the `hiddenColumns` prop.
> Add docs about `<DataTable hiddenColumns>`

- vercel.json
- Our config is using obsolete properties
- When pushing go the `gh-pages` branch, vercel tries to deploy the demo and storybook, sending error notifications
Fix the vercel config
> [chore] Avoid vercel deployment for `gh-pages` branch

- docs/DataTable.md
`<DataTable.Col align>` doc section gets it the other way around (left instead of right and vice-versa)
Fix the default value and example
> [Doc] Fix `<DataTable.Col align>` default value and example

- docs/js/ra-navigation.js
When navigating a page that does not have a storybook frontmatter, an error is thrown. Navigating to any page that should have a TOC doesn't display the TOC anymore.
1. `make doc`
2. go to http://0.0.0.0:4000/documentation.html : there should be no error in console
3. click the _Admin_ link in the sidebar: it should load, display the TOC and the storybook link
4. click the _Vite_ link in the sidebar: there should be no error in console, it should display a TOC without storybook link
> [Doc] Fix storybook detection and handling on client-side navigation

- docs/CheckboxGroupInput.md
- docs/RadioButtonGroupInput.md
- packages/ra-core/src/form/choices/useChoices.tsx
- packages/ra-ui-materialui/src/field/SelectField.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
- packages/ra-ui-materialui/src/input/CheckboxGroupInputItem.tsx
- packages/ra-ui-materialui/src/input/DatagridInput.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.stories.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
- packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
- packages/ra-ui-materialui/src/input/SelectInput.tsx
> Add disable support for `RadioButtonGroupInput` and `CheckboxGroupInput` choices

- packages/ra-core/src/controller/button/useDeleteWithConfirmController.spec.tsx
- packages/ra-core/src/controller/button/useDeleteWithUndoController.spec.tsx
`useDeleteWithUndoController` had a test failing, but it wasn't showing up as the waitFor wasn't awaited.
`await` the `waitFor` and trigger the mutation so the test can pass.
`make test-unit`
- ~[ ] The **documentation** is up to date~
> [chore] Fix a failing test not showing up in useDeleteWithUndoController

- packages/ra-core/src/controller/input/useReferenceInputController.spec.tsx
- packages/ra-core/src/controller/input/useReferenceInputController.ts
> Fix useReferenceInputController params type

- packages/ra-ui-materialui/src/input/DatagridInput.stories.tsx
- packages/ra-ui-materialui/src/input/DatagridInput.tsx
- packages/ra-ui-materialui/src/input/sanitizeInputRestProps.ts
Regression introduced in https://github.com/marmelab/react-admin/pull/10772/files#diff-ac33f5830e4b132ca41269e194567542c51b45e341898c200b547516d2696028R44
- Fixed: https://react-admin-storybook-90sll8xaw-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-textinput--non-full-width
- Broken: https://react-admin-storybook-478wf3y4m-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-textinput--non-full-width
> Fix `fullWidth` is not propagated anymore

- examples/crm/vite.config.ts
- examples/demo/src/dashboard/Dashboard.tsx
- examples/demo/src/dashboard/OrderChart.tsx
- examples/demo/vite.config.ts
The ecommerce demo bundle is quite large.
> Improve commerce demo bundle

- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
Added complementarity tests and stories to `SelectInput` and `SelectArrayInput` components, as I did for #10821
This time in `master` since these components already have the `disableValue` prop
> Added `SelectInput` and `SelectArrayInput` disable choices test and story

- docs/Create.md
Typo in the notification translation key
The correct key is `created`, not `create` according to https://github.com/marmelab/react-admin/blob/440f71f3ba8e81c32f6813071ecb08cdfa4d182b/packages/ra-core/src/controller/create/useCreateController.ts#L99
> Fix typo in Create.md

- packages/ra-core/src/controller/edit/EditBase.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.spec.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
- packages/ra-ui-materialui/src/detail/Edit.spec.tsx
Although `useEditController` do pass all variables to `useUpdate` at declaration time, it actually overrides them at call time. However, it does not pass all of them (`previousData` is missing). This is an issue when your dataProvider update function or your side effects depends on the previous values (e.g. depending on the previous status, etc)
Fix `useEditController` so that it passes everything as expected.
- unit tests
> Fix `useEditController` does not pass all variables to `useUpdate`

- CHANGELOG.md
- docs/List.md
- examples/simple/package.json
- packages/ra-core/package.json
- packages/ra-core/src/auth/useAuthState.ts
- packages/ra-core/src/auth/useCanAccess.ts
- packages/ra-core/src/auth/usePermissions.ts
- packages/ra-core/src/controller/input/useReferenceInputController.ts
- packages/ra-core/src/dataProvider/useGetList.ts
- packages/ra-core/src/dataProvider/useGetManyReference.ts
- packages/ra-core/src/dataProvider/useInfiniteGetList.ts
- packages/ra-no-code/package.json
- packages/ra-ui-materialui/package.json
- packages/ra-ui-materialui/src/list/List.stories.tsx
- packages/react-admin/package.json
- yarn.lock
We received some requests and questions for enabling list components data fetching conditionally.
It's actually easier to do with react-query versions more recent than the one we install by default.
- https://react-admin-storybook-rarckfjb1-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-list--conditional-data-fetching
> Update react-query depency to require at least v5.83

- docs/Tree.md
- docs/TreeWithDetails.md
ra-tree's doc was updated about this:
> Support recordRepresentation defined at resource level, and keep titleField to override it for Tree, TreeWithDetails, TreeInput
Backport it
- ~~[ ] The PR includes **unit tests** (if not possible, describe why)~~
- ~~[ ] The PR includes one or several **stories** (if not possible, describe why)~~
> [Doc] Backport Tree's doc

- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-core/src/controller/show/useShowController.ts
Fix https://github.com/marmelab/react-admin/issues/10842
If `getOne` rejects, Show and Edit controllers will trigger a redirect to the list view, and also force refreshing the react-query cache with `useRefresh()`.
This can lead to creating a redirect loop because `refresh` will trigger a `getOne` call again, which will fail again and trigger this side-effect again, etc.
This issue only seems to appear when using react-router v7.
https://github.com/marmelab/react-admin/pull/10776 already attempted to fix this issue, but according to my tests it doesn't work (and actually seems to have no effect) so I reverted the changes it brought.
Simply remove calling `refresh()` from the side-effects, as redirecting to the list view will refresh the data anyway thanks to react-query.
We need a demo …
> Fix Show and Edit controllers can trigger a redirect loop with react-router v7 if getOne rejects

- packages/ra-core/src/dataProvider/useCreate.spec.tsx
- packages/ra-core/src/dataProvider/useCreate.ts
- packages/ra-core/src/dataProvider/useDelete.spec.tsx
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-core/src/dataProvider/useDeleteMany.spec.tsx
- packages/ra-core/src/dataProvider/useDeleteMany.ts
- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
In order to support offline scenarios, our mutations must have a `mutationKey`.
Add `mutationKey` to all mutations.
**Note**: for offline support to work, the `resource` must be provided at declaration time.
- unit tests
> Add `mutationKey` to all mutations

- packages/ra-ui-materialui/src/input/DateInput.tsx
Just a doc formatting
BEFORE:
AFTER:
> [DateInput] Fix example doc

- packages/ra-core/src/form/validation/validate.ts
Some users need those types but they are not exported so they had to duplicate them in their code.
Export them with better names.
> Export `ValidationMessageFuncParams` and `ValidationMessageFunc` types

- docs/Edit.md
- docs/EditBase.md
- packages/ra-core/src/controller/edit/EditBase.spec.tsx
- packages/ra-core/src/controller/edit/EditBase.stories.tsx
- packages/ra-core/src/controller/edit/EditBase.tsx
- packages/ra-core/src/controller/edit/useEditController.ts
- packages/ra-ui-materialui/src/detail/Edit.stories.tsx
- packages/ra-ui-materialui/src/detail/Edit.tsx
- packages/ra-ui-materialui/src/detail/EditView.tsx
- [`<EditBase>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-core-controller-editbase--offline)
- [`<Edit>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-ui-materialui-detail-edit--offline)
- Tests
> Add offline support to `<EditBase>` and `<Edit>`

- docs/ReferenceManyFieldBase.md
- packages/ra-core/src/controller/field/ReferenceManyFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceManyFieldBase.stories.tsx
- packages/ra-core/src/controller/field/ReferenceManyFieldBase.tsx
- packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
- packages/ra-core/src/controller/list/useListController.ts
- [`<ReferenceManyFieldBase>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-core-controller-field-referencemanyfieldbase--offline)
- Tests
> Add offline support to `<ReferenceManyFieldBase>`

- packages/ra-ui-materialui/src/list/datatable/ColumnsButton.spec.tsx
- packages/ra-ui-materialui/src/list/datatable/ColumnsButton.tsx
- packages/ra-ui-materialui/src/list/datatable/ColumnsSelector.tsx
- packages/ra-ui-materialui/src/preferences/FieldToggle.tsx
- Although it's possible to open the `<ColumnsButton>` menu with _space_, it's impossible to reach its items using the keyboard.
- It also produce invalid HTML when adding the filter (not rendered inside a `li` element)
**Note:** Drag and dropping the items to reorder columns has not been implemented yet.
- [Story](https://react-admin-storybook-njkolog9u-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-datatable--full-app)
- Click in the background around the list t ofocus the story iframe
- Press _Tab_ until the `<ColumnsButton>` is active
- Press  _Space_ to open its menu
- Press _Tab_ to loop through its items, toggling them with _Space_
- Press _Escape_ to close the menu
> Fix `<ColumnsButton>` cannot be used with keyboard

- docs/Scheduler.md
`<Scheduler>` props table still refers to `resourcesName` and `eventName` props, but they have been replaced by `resources`.
- ~The PR includes **unit tests** (if not possible, describe why)~
- ~The PR includes one or several **stories** (if not possible, describe why)~
> Update obsolete documentation of <Scheduler> properties

- packages/ra-ui-materialui/src/field/ChipField.spec.tsx
- packages/ra-ui-materialui/src/field/ChipField.stories.tsx
- packages/ra-ui-materialui/src/field/ChipField.tsx
Fixes #10875
#10591 introduced an issue for value equal to zero.
- Unit tests
- [Story](https://react-admin-storybook-mtvbs0jhk-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-chipfield--basic&args=value:zero;emptyText:provided)
> Fix `ChipField` consider zero to be empty

- docs/AutocompleteArrayInput.md
- docs/AutocompleteInput.md
- docs/SelectArrayInput.md
- docs/SelectInput.md
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
- packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
- packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
- packages/ra-ui-materialui/src/input/SelectInput.stories.tsx
- packages/ra-ui-materialui/src/input/common.tsx
- packages/ra-ui-materialui/src/input/useSupportCreateSuggestion.tsx
Customizing the label for creating a new choice in AutocompleteInput with more than just text is not possible without rewriting the whole component.
Accept a `ReactNode` in `createLabel` prop, and a function returning a `ReactNode` in `createItemLabel` prop.
- Story: [AutocompleteInput](https://react-admin-storybook-8z2fzdbt1-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-autocompleteinput--create-item-label-rendered)
- Story: [AutocompleteArrayInput](https://react-admin-storybook-8z2fzdbt1-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-autocompletearrayinput--create-item-label-rendered)
- Story: [SelectInput](https://react-admin-storybook-8z2fzdbt1-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-selectinput--create-label-rendered)
- Story: …
> Support ReactNode as create label

- docs/ReferenceField.md
- docs/ReferenceFieldBase.md
- packages/ra-core/src/controller/field/ReferenceFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.stories.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.tsx
- packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx
- packages/ra-core/src/controller/useReference.spec.tsx
- packages/ra-core/src/controller/useReference.ts
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.tsx
- [`<ReferenceFieldBase>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-core-controller-field-referencefieldbase--offline)
- [`<ReferenceField>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-referencefield--offline)
- Tests
> Add offline support to `<ReferenceFieldBase>` and `<ReferenceField>`

- docs/ReferenceOneField.md
- docs/ReferenceOneFieldBase.md
- packages/ra-core/src/controller/field/ReferenceOneFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceOneFieldBase.stories.tsx
- packages/ra-core/src/controller/field/ReferenceOneFieldBase.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
- [`<ReferenceOneFieldBase>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-core-controller-field-referenceonefieldbase--offline)
- [`<ReferenceOneField>`](https://react-admin-storybook-oyp7ya93k-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-referenceonefield--offline)
- Tests
> Add offline support to `<ReferenceOneFieldBase>` and `<ReferenceOneField>`

- packages/ra-core/src/auth/useAuthState.ts
- packages/ra-core/src/auth/useCheckAuth.ts
- packages/ra-core/src/auth/useLogoutIfAccessDenied.ts
When a developer forgets to return a Promise in `authProvider.checkAuth()` or `authProvider.checkError()`, they see a cryptic error message:
> Cannot read properties of undefined (reading 'then')
Although the doc (and typescript) specifies that these methods must be async, react-admin can be more permissive and not throw any error in this case, by using async methods instead of promises. 
Update the authProvider in the simple example to use sync methods:
```js
checkError: ({ status }) => {
if (status === 401 || status === 403) {
throw new Error();
}
},
checkAuth: () => {
if (localStorage.getItem('not_authenticated')) {
throw new Error();
}
},
```
The simple example should still work. 
- ~~[ ] The PR includes **unit tests** (if not possible, describe why)~~
- ~~[ ] The PR includes one or …
> Fix error when authProvider check methods are not async

- packages/ra-core/src/dataProvider/useCreate.spec.tsx
- packages/ra-core/src/dataProvider/useCreate.stories.tsx
- packages/ra-core/src/dataProvider/useCreate.ts
- packages/ra-core/src/dataProvider/useDelete.optimistic.stories.tsx
- packages/ra-core/src/dataProvider/useDelete.pessimistic.stories.tsx
- packages/ra-core/src/dataProvider/useDelete.spec.tsx
- packages/ra-core/src/dataProvider/useDelete.stories.tsx
- packages/ra-core/src/dataProvider/useDelete.ts
- packages/ra-core/src/dataProvider/useDelete.undoable.stories.tsx
- packages/ra-core/src/dataProvider/useDeleteMany.spec.tsx
- packages/ra-core/src/dataProvider/useDeleteMany.stories.tsx
- packages/ra-core/src/dataProvider/useDeleteMany.ts
- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.stories.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
- packages/ra-core/src/dataProvider/useUpdateMany.spec.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.stories.tsx
- packages/ra-core/src/dataProvider/useUpdateMany.ts
The mutation hooks currently put the `mutationMode` and `params` they receive at _declaration time_ in a ref but never update them from their props.
Add effects that sync the refs with the props.
- stories
- tests
> Make all mutations react to their declaration time options changes

- docs/Edit.md
- docs/ReferenceArrayField.md
- docs/ReferenceArrayFieldBase.md
- packages/ra-core/src/controller/field/ReferenceArrayFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceArrayFieldBase.stories.tsx
- packages/ra-core/src/controller/field/ReferenceArrayFieldBase.tsx
- packages/ra-core/src/controller/field/useReferenceArrayFieldController.stories.tsx
- packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
- packages/ra-core/src/controller/field/useReferenceManyFieldController.stories.tsx
- packages/ra-core/src/controller/list/useList.ts
- packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.stories.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.tsx
- [`<ReferenceArrayFieldBase>`](https://react-admin-storybook-q8f806rod-marmelab.vercel.app/?path=/story/ra-core-controller-field-referencearrayfieldbase--offline)
- [`<ReferenceArrayField>`](https://react-admin-storybook-q8f806rod-marmelab.vercel.app/?path=/story/ra-ui-materialui-fields-referencearrayfield--offline) 
- Tests
> Add offline support to `<ReferenceArrayFieldBase>` and `<ReferenceArrayField>`

- packages/ra-core/src/controller/list/index.ts
- packages/ra-core/src/export/index.ts
- packages/ra-core/src/export/useBulkExport.spec.tsx
- packages/ra-core/src/export/useBulkExport.stories.tsx
- packages/ra-core/src/export/useBulkExport.ts
- packages/ra-ui-materialui/src/button/BulkExportButton.tsx
The bulk export logic is currently in `<BulkExportButton>` inside `ra-ui-materialui` package. That leads to code duplication in other UI packages such as `shadcn-admin-kit`.
- Introduce a `useBulkExport` hook
- Use the hook in `<BulkExportButton>`
- Unit tests
- [Story](https://react-admin-storybook-c22j54u9d-marmelab.vercel.app/?path=/story/ra-core-export-usebulkexport--basic)
> Use bulk export

- docs/LockOnMount.md
- docs/LockStatus.md
- docs/navigation.html
- docs/useLockCallbacks.md
- docs/useLockOnCall.md
- docs/useLockOnMount.md
`ra-realtime@5.2.0` introduced new hooks and components. 
- `make doc`
> [Doc] Update ra-realtime documentation for 5.2.0

- docs/ListBase.md
- packages/ra-core/src/controller/edit/EditBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceArrayFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceManyCountBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceManyFieldBase.spec.tsx
- packages/ra-core/src/controller/field/ReferenceOneFieldBase.spec.tsx
- packages/ra-core/src/controller/input/ReferenceArrayInputBase.spec.tsx
- packages/ra-core/src/controller/input/ReferenceInputBase.spec.tsx
- packages/ra-core/src/controller/list/ListBase.spec.tsx
- packages/ra-core/src/controller/list/ListBase.stories.tsx
- packages/ra-core/src/controller/list/ListBase.tsx
- packages/ra-core/src/controller/show/ShowBase.spec.tsx
- packages/ra-core/src/core/IsOffline.spec.tsx
- packages/ra-ui-materialui/src/detail/Show.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyCount.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceManyField.spec.tsx
- packages/ra-ui-materialui/src/field/ReferenceOneField.spec.tsx
- packages/ra-ui-materialui/src/list/List.spec.tsx
When using iterator like components as direct children of `ListBase`, they have to check the `isPending` state.
- Introduce `emptyWhileLoading` on `<ListBase>` so they don't have to.
- Also fix offine tests impacting other tests
- [Story With Children](https://react-admin-storybook-i70jjdpns-marmelab.vercel.app/?path=/story/ra-core-controller-list-listbase--empty-while-loading)
- [Story With render prop](https://react-admin-storybook-i70jjdpns-marmelab.vercel.app/?path=/story/ra-core-controller-list-listbase--empty-while-loading-render)
- Unit tests
> Introduce `emptyWhileLoading` on `<ListBase>`

- packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.spec.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.stories.tsx
- packages/ra-ui-materialui/src/list/SingleFieldList.tsx
Fixes #10900
Using `<ListIterator>` in `ra-ui-materialui` introduced regressions.
As we're in the process of rewriting `<ListIterator>` in `ra-core`, we chose to revert those changes for now.
- Current tests should work as before
- Added a test on `<SingleFieldList>` to detect regressions
> Revert usage on `<ListIterator>` in `ra-ui-materialui`

- examples/crm/src/providers/fakerest/dataProvider.ts
- examples/crm/src/providers/fakerest/fakeServer.ts
- examples/demo/src/dataProvider/graphql.ts
- examples/demo/src/dataProvider/rest.ts
- examples/demo/src/fakeServer/index.ts
- examples/demo/src/fakeServer/rest.ts
Demo / CRM examples are not working in production when using Safari.
Use https://crm.api.marmelab.com / https://demo.api.marmelab.com instead of http://localhost:4000 for the fake server handled by MSW.
Visit https://marmelab.com/react-admin-crm and https://marmelab.com/react-admin-demo with Safari.
> Fix demos with MSW

- packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
BulkDeleteWithConfirmButton has different color than BulkDeleteWithUndoButton.
Use the same color for both buttons.
Include both buttons in a `bulkActionButtons` prop and visually compare.
> Fix BulkDeleteWithConfirmButton color

- packages/ra-ui-materialui/src/list/datatable/DataTable.stories.tsx
- packages/ra-ui-materialui/src/list/datatable/DataTableCell.tsx
It's not possible to customize the styles of `<DataTable>` cells by following the [documentation](https://marmelab.com/react-admin/DataTable.html#sx-css-api).
Apply the `RaDataTable-rowCell` CSS class to `<DataTableCell>`
- [Story](https://react-admin-storybook-6bbr3ecng-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-datatable--sx)
- The cells should have a red text color
~~- [ ] The PR includes **unit tests** (if not possible, describe why)~~ Design only
> Fix `RaDataTable-rowCell` CSS class is not applied on `<DataTable>` cells

- packages/ra-core/src/controller/input/useReferenceInputController.spec.tsx
- packages/ra-core/src/controller/input/useReferenceInputController.ts
- packages/ra-ui-materialui/src/input/AutocompleteInput.stories.tsx
When using the `enableGetChoices` prop of `<ReferenceInput>`, it won't return the currently selected record even though it was fetched.
- Return the currently selected record if present.
- Fix the existing test for `enableGetChoices` to also check the options passed to the `ChoicesContext`
- [Story](https://react-admin-storybook-64wcppxiv-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-autocompleteinput--inside-reference-input-with-disable-choice)
- It should display the current value (_Leo Tolstoy_)
- Clicking on the dropdown button should show an empty list of choices until 4 characters are entered (for instance _baud_)
> Fix `<ReferenceInput>` don't return currently selected choice when `enableGetChoices` returns `false`

- docs/Features.md
- docs/Theming.md
First video of https://marmelab.com/react-admin/Theming.html doesn't play on iPhones.
Same with video in https://marmelab.com/react-admin/Features.html#not-ugly
Fix video type
`make docker-doc` and browse locally with an iPhone (or BrowserStack)
> [Doc] Fix some incorrect video types

- docs/ReferenceManyInput.md
We added support for editing the order of multiple references but it's not documented in OSS.
- `make doc`
> [Doc] Update `<ReferenceManyInput>` documentation to mention `rankSource`

- packages/ra-core/src/dataProvider/useUpdate.spec.tsx
- packages/ra-core/src/dataProvider/useUpdate.ts
On a successful update, the getManyReference data update was only copying the data and total from the original response, losing other properties like `meta` and `pageInfo`.
Copy the full response like it is done for the getList response.
Have a page that both uses a `ReferenceManyField` components and updates the same resource with `useUpdate`
> Fix update removing meta and pageInfo properties from getManyReference result

- packages/ra-core/src/dataProvider/useMutationWithMutationMode.spec.tsx
- packages/ra-core/src/dataProvider/useMutationWithMutationMode.ts
After #10857, when passing parameters at declaration time to a mutation hook in `optimistic` or `undoable` mode, those params may be modified by the side effects before the actual mutation is called.
For instance, if you pass the `selectedIds` from the `ListContext` to a `useUpdateMany` hook and use the `useUnselectAll` hook to reset the `selectedIds` in the `onSuccess` side effect, then the actual mutation will be called with an empty array of ids.
You can see the issue like this:
- https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple
- select multiple rows and click the _Reset views_ button
- check the dataProvider call in the console and check the call to `updateMany`
- beside, the views are back to their initial values once the mutation is actually called …
> Fix `useMutationWithMutationMode` in `optimistic` and `undoable` mode may pass invalid parameters to the mutation
