marmelab/react-admin

package.json

1) Install
```
create-react-app foo
cd foo
npm install --save admin-on-rest
```
2) Edit `src/App.js`:
```javascript
import React, {Component} from "react";
import {jsonServerRestClient, Admin, Resource} from "admin-on-rest";
<Admin restClient={jsonServerRestClient('http://jsonplaceholder.typicode.com')}>
<Resource name="posts" />
</Admin>
);
export default App;
```
3) `npm start`
You get lots of errors like this one:
```
Error in ./~/admin-on-rest/lib/util/fetch.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in d:\foo\node_modules\admin-on-rest\lib\util
@ ./~/admin-on-rest/lib/util/fetch.js 8:16-56
```
```
npm install --save babel-runtime
```
As the documentation of Babel says:
> In most cases, you should install …

Cannot resolve module 'babel-runtime/helpers/extends'

---

README.md
docs/Tutorial.md
example/comments.js
example/posts.js
src/mui/list/List.js

Pros:
* Explicit
* Same structure as for `<ReferenceManyField>`
* Allows using another view (like a thumbnail list)
Cons:
* More verbose
* Longer to explain/understand
Before:
```html
export const PostList = (props) => (
<List {...props} filter={PostFilter}>
<TextField label="id" source="id" />
<TextField label="title" source="title" />
<DateField label="published_at" source="published_at" />
<TextField label="average_note" source="average_note" />
<TextField label="views" source="views" />
<EditButton />
</List>
);
```
After:
```html
export const PostList = (props) => (
<List {...props} filter={PostFilter}>
<Datagrid>
<TextField label="id" source="id" />
<TextField label="title" source="title" />
<DateField label="published_at" source="published_at" />
<TextField label="average_note" …
```

[RFR][BC Break] Make Datagrid usage explicit in <List>

---

README.md

Using `npm link` creates two versions or React, and causes the dreadful error:
> Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

[RFR] Remove bad advice about npm link

---

src/mui/list/FilterForm.js
src/mui/list/List.js
src/reducer/resource/list/queryReducer.js
src/reducer/resource/list/queryReducer.spec.js
src/sideEffect/saga/crudFetch.js

There is one weird bug remaining, linked to redux-form: sometimes, when emptying a filter form, the list doesn't refresh. I've traced that down to the call to `getFormValues('filterForm')(state)` returning undefined in some cases (?), therefore defaulting to the previous filter value. To be treated in a future PR.

[RFR] Fix and speedup filters

---

example/index.html
src/mui/input/RichTextInput.css

Without this PR, we can't distinguish bold from unbold text in RTE.

[RFR] Fix bold in rich text editor

---

src/mui/field/ReferenceManyField.js
src/mui/input/Labeled.js
src/mui/input/SelectInput.js

React checks the presence of required props before render. Since we
clone some components and pass them the required props at render time,
this creates alerts while there shouldn't be. The solution is to remove
the requirements in PropTypes.

[RFR] Remove required props warnings

---

docs/Inputs.md
example/package.json
example/webpack.config.js
package.json

Using `peerDependencies` is too much hassle for the user, and the number of admins *without* rich text editing is probably not worth it. Let's move `quill` to `dependencies`.
Closes #89 
Supersedes #90

[RFR] Move quill as dependency

---

src/mui/list/Datagrid.js
src/mui/list/List.js
src/reducer/resource/list/queryReducer.spec.js

The filter equality test in componentWillReceiveProps() failed when
there was no filter attribute passed to the List component because then
the filter value was taken from the URL instead of the filter form. In
that case, the filter value is always "{}", but deserializing it leads
to a new object every time, forcing a setFilter() which resets the page.
Closes #103

[RFR] Fix Pagination when list has no filter

---

example/posts.js
src/mui/list/Datagrid.js

Replace Material UI's `<Table>` component with a native table, to let the browser compute column dimensions based on content.
Before: 
After:

[RFR] Real table

---

docs/RestClients.md
docs/_layouts/default.html
src/rest/jsonServer.js
src/rest/simple.js
src/util/fetch.js

Closes #127
Both the `simpleRestClient` and the `jsonServerRestClient` functions now accept an http client function as second argument. By default, they use admin-on-rest's `fetchUtils.fetchJson()` as http client. It's similar to HTML5 `fetch()`, except it handles JSON decoding and HTTP error codes automatically.
That means that if you need to add custom headers to your requests, you just need to *wrap* the `fetchJson()` call inside your own function:
```js
import { simpleRestClient, fetchUtils, Admin, Resource } from 'admin-on-rest';
const httpClient = (url, options) => {
if (!options.headers) {
options.headers = new Headers({ Accept: 'application/json' });
}
// add your own headers here
options.headers.set('X-Custom-Header', 'foobar');
return fetchUtils.fetchJson(url, options);
}
const …
```

[RR] Add ability to intercept HTTP request and add custom headers

---

src/mui/list/List.js

Was caused by the `debounce` sometimes answering after the user navigated away.
Note to self: *always cancel debounce on unmount*
Closes #137

[RFR] Fix infinite redirect bug

---

package.json

... to fix React 15.4.0 compatibility). 
[react-v15.4.0](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html) broke `react-tap-event-plugin@v1`, which got updated to 2.0.1. just now at https://github.com/zilverline/react-tap-event-plugin/pull/82. See the change set here: https://github.com/zilverline/react-tap-event-plugin/pull/82/files. It only changes the paths to `react-dom`.
https://www.npmjs.com/package/react-tap-event-plugin

Update react-tap-event-plugin to 2.0.1

---

package.json

Reverts marmelab/admin-on-rest#153
The npm install warns against semver incompatibilities:
```
npm WARN react-tap-event-plugin@2.0.1 requires a peer of react@^15.4.0-0 but none was installed.
npm WARN react-tap-event-plugin@2.0.1 requires a peer of react-dom@^15.4.0-0 but none was installed.
npm WARN react-addons-create-fragment@15.4.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN react-addons-transition-group@15.4.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 …
```

Revert "Update react-tap-event-plugin to 2.0.1"

---

src/mui/list/Datagrid.js

Before:
After:
Now works on smaller screens, too:

[RFR] Reduce datagrid margins to accomodate more content

---

src/mui/input/SelectInput.js

This PR is a proposal to use optionValue as key for the iteration of choices in the SelectInput UI component. Since this UI element is also used for Foreign Key selection it is not guaranteed that the `optionText` is different which will lead to a duplicate key error in React. Since `optionValue` is already used in the comments for containing a unique id value it would be a better choice for the `key`

[RFR] Adding optionValue as key for MenuItem iteration.

---

package.json

When we install `admin-on-rest` with yarn, we're currently facing with this error:
```
error parchment@1.0.1: The engine "node" is incompatible with this module. Expected version "^5.3".
error Found incompatible module
```
The root cause comes from the dependency `quill`. Now, this issue was fixed as mentioned [here](https://github.com/quilljs/quill/issues/1041) and [here](https://github.com/yarnpkg/yarn/issues/812#issuecomment-253190930) as well as released in the latest version of `quill`.
Please consider upgrading the dependency `quill` to latest version `1.1.5`.

Update quill version to fix yarn engine `node` incompatible

---

src/mui/layout/Notification.js

Closes #177 
Although [the material ui theme doc](http://www.material-ui.com/#/customization/themes) advises using the `muiThemeable` hoc for that purpose, I found it easier to mmake it by hand since the component is already decorated and has default props.

[RFR] Use theme colors in notifications

---

example/posts.js
src/mui/list/Datagrid.js

[RFR] Datagrid cells default to white-space: normal instead of nowrap

---

docs/Inputs.md
docs/RestClients.md
docs/Tutorial.md
docs/_layouts/default.html
example/comments.js
package.json
src/actions/dataActions.js
src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/RadioButtonGroupInput.spec.js
src/mui/input/ReferenceInput.js
src/mui/input/ReferenceInput.spec.js
src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js
src/mui/input/index.js
src/mui/list/FilterForm.js
src/reducer/references/possibleValues.js
src/reducer/resource/data.js
src/rest/jsonServer.js
src/rest/simple.js
src/rest/types.js

[RFR] Improve <ReferenceInput> field

---

docs/RestClients.md
docs/_layouts/default.html
example/app.js
example/package.json
package.json

To facilitate tests, use [marmelab/aor-json-rest-client](https://github.com/marmelab/aor-json-rest-client) instead of `simpleRestClient` + `fakerest` +  `fetch-mock`.

[RFR] Use Json REST client in example

---

docs/Inputs.md
src/mui/detail/RecordForm.js
src/mui/input/AutocompleteInput.js
src/mui/input/BooleanInput.js
src/mui/input/DateInput.js
src/mui/input/DisabledInput.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/NullableBooleanInput.js
src/mui/input/NumberInput.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/ReferenceInput.js
src/mui/input/RichTextInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js

By making the decoration by redux-form `<Field>` component optional, it becomes much easier to create custom (and composite) input components. 
Tests are hard - due to redux-form usage of `context` and all.
```js
// in LatLongInput.js
import { Field } from 'redux-form';
import { NumberInput } from 'admin-on-rest/lib/mui';
const LatLngInput = () => (
<span>
<Field name="lat" component={NumberInput} label="latitude" />
&nbsp;
<Field name="lng" component={NumberInput} label="longitude" />
</span>
);
LatLngInput.defaultProps = {
includesLabel: true,
};
export default LatLngInput;
// in ItemEdit.js
const ItemEdit = (props) => (
<Edit {...props}>
<DisabledInput source="id" />
<LatLngInput />
</Edit>
);
```

[RFR] Make custom input components easier

---

docs/Inputs.md
src/mui/detail/RecordForm.js
src/mui/detail/RecordForm.spec.js
src/mui/detail/Show.js
src/mui/field/BooleanField.js
src/mui/field/ChipField.js
src/mui/field/DateField.js
src/mui/field/EmailField.js
src/mui/field/FunctionField.js
src/mui/field/NumberField.js
src/mui/field/ReferenceField.js
src/mui/field/ReferenceManyField.js
src/mui/field/RichTextField.js
src/mui/field/TextField.js
src/mui/field/UrlField.js
src/mui/input/AutocompleteInput.js
src/mui/input/BooleanInput.js
src/mui/input/DateInput.js
src/mui/input/DisabledInput.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/NullableBooleanInput.js
src/mui/input/NumberInput.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/ReferenceInput.js
src/mui/input/ReferenceInput.spec.js
src/mui/input/RichTextInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js

Until now, a label was added by default to all Input component unless the component opted out with `includesLabel: true`. That lead to WTF moments, as when defining a custom input as follows:
```js
// in SexInput.js
import SelectField from 'material-ui/SelectField';
import MenuItem from 'material-ui/MenuItem';
const SexInput = ({ input, meta: { touched, error } }) => (
<SelectField
floatingLabelText="Sex"
errorText={touched && error}
{...input}
>
<MenuItem value="M" primaryText="Male" />
<MenuItem value="F" primaryText="Female" />
</SelectField>
);
SexInput.defaultProps = {
includesField: false, // require a <Field> decoration
};
export default SexInput;
```
This perfectly looking code would produce a runtime error:
> Cannot create label for component SexInput: You must set either the …

[RFR] [BC Break] Rename input props includesLabel and includesField to add-

---

src/mui/form/TabbedForm.js
src/util/validate.js
src/util/validate.spec.js

`<TabbedForm>` used the same technique as `<SimpleForm>` to merge `validation` props from `<Input>` fields: iterating over the children. But it doesn't work for `<TabbedForm>`, since its children are `<FormTab>` components, not `<Input>` components. So validation was broken in `<TabbedForm>`.
This PR fixes it.

[RFR] Fix form validation from input prop in TabbedForm component

---

example/posts.js
package.json
src/mui/button/EditButton.js
src/mui/detail/Show.spec.js
src/mui/field/BooleanField.js
src/mui/field/BooleanField.spec.js
src/mui/field/ChipField.js
src/mui/field/DateField.js
src/mui/field/DateField.spec.js
src/mui/field/EmailField.js
src/mui/field/FunctionField.js
src/mui/field/NumberField.js
src/mui/field/NumberField.spec.js
src/mui/field/RichTextField.js
src/mui/field/TextField.js
src/mui/field/UrlField.js
src/mui/layout/AppBar.js
src/mui/layout/Layout.js
src/mui/layout/Menu.js
src/mui/list/Datagrid.js
src/mui/list/DatagridBody.js
src/mui/list/DatagridCell.js
src/mui/list/DatagridHeaderCell.js
src/mui/list/List.js
src/mui/list/Pagination.js

First step towards performance improvements
Measurements show a great improvement when updating the list (change sort, add filter change page): 630ms => 154ms.
The datagrid body no longer rerenders *before* fetching data. We still rerender the list heading (to update the sort icon before fetching), but only for columns that need it.
before:
after:

[RFR] Avoid useless rerenders in Layout and Datagrid

---

src/reducer/resource/list/params.js
src/reducer/resource/list/params.spec.js

It especially fixes a weird behavior:
* Go on page 2 of posts list,
* Refresh your browser,
* Click on "Posts" menu item,
* List is not refreshed.

[RFR] Fix default list state

---

src/mui/list/Pagination.js

Depending on a race condition, the pagination sometimes temporarily receives NaN as
page number. In that case, it shouldn't try to render a page button with
NaN as a label.

[RFR] Fix pagination error in console

---

src/mui/detail/Edit.js
src/mui/list/List.js

To force fetching again data in inner components (e.g. in `<ReferenceField>`), we change the value of the `key` prop on reload.
(`forceUpdate()` should also work, but a) [it's discouraged](http://stackoverflow.com/a/35004739/1333479), and b) it doesn't work for some reason)
Note: This doesn't work on the blog example (i.e. no refreshing of the referenne fields) because `aor-json-rest-client` returns always the same record and therefore passes the strict equality check. I'll fix that in the related repository.
Fixes #279

[RFR] Fix Refresh button doesn't refresh reference fields

---

src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js
src/mui/input/ReferenceInput.js
src/mui/input/ReferenceInput.spec.js
src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js

Hi,
marmelab/admin-on-rest#253
- AutocompleteInput: still some validation issues, but it needs refactoring
- ReferenceInput
- SelectInput
~[Line 65 of SelectInput.js](https://github.com/marmelab/admin-on-rest/pull/289/files?diff=split#diff-5470e5c0cbc29b42c57d5cdfd5170621L65)~

Fix validation on some inputs

---

docs/Tutorial.md

`create-react-app` now uses `yarn` instead of `npm`, so our tutorial reflects that.

[RFR] In the tutorial, use yarn instead of npm

---

src/mui/button/CreateButton.js
src/mui/button/DeleteButton.js
src/mui/button/EditButton.js
src/mui/button/ListButton.js
src/mui/button/RefreshButton.js
src/mui/button/SaveButton.js
src/mui/button/ShowButton.js

Apparently, the empty string is a valid key for polyglot.js, so it complains that there is no translation. If you want my opinion, it's a polyglot bug, but the maintainers disagree:
https://github.com/airbnb/polyglot.js/pull/85
So we're relmoving the warnings from the admin-on-rest side.

[RFR] Remove translate warnings when using empty label on buttons

---

docs/AdminResource.md
docs/CustomApp.md
src/Admin.js

Closes #283
To register your own routes, create a function returning a [react-router](https://github.com/ReactTraining/react-router) `<Route>` component:
```js
// in src/customRoutes.js
import React from 'react';
import { Route } from 'react-router';
import Foo from './Foo';
import Bar from './Bar';
export default () => (
<Route>
<Route path="/foo" component={Foo} />
<Route path="/bar" component={Bar} />
</Route>
);
```
Then, pass this function as `customRoutes` prop to the `<Admin>` component:
```js
// in src/App.js
import React from 'react';
import { Admin } from 'admin-on-rest';
import customRoutes from './customRoutes';
<Admin customRoutes={customRoutes} restClient={jsonServerRestClient('http://jsonplaceholder.typicode.com')}>
...
</Admin>
);
export default App; …
```

[RFR] Add the ability to add custom routes

---

src/sideEffect/saga/crudFetch.js

The current code prevents custom sagas/reducers to get all the needed data about a crud action.

[RFR] Ensure actions are not modified

---

src/mui/layout/AppBar.js
src/mui/layout/Layout.js
src/mui/layout/Menu.js

Not dealing with the small screen use case as in #322. This would require switching to a `<Drawer>` component for the menu in small screens, which is possible, but demands more work. Besides, admin-on-rest isn't fitted for small screens, yet (see #282).
Closes #258

[RFR] Handle sidebar toggle

---

docs/List.md
src/mui/defaultTheme.js
src/mui/list/Datagrid.js
src/mui/list/DatagridBody.js
src/mui/list/DatagridCell.js

We didn't use material-ui's `<Table>` component because it divided the table width in equal columns. It turns out [that's configurable, but undocumented](https://github.com/callemall/material-ui/issues/4366#issuecomment-279841386). 
Therefore, we have no longer any reason not to use their components (apart from the fact that they're a bit slow, but that's not a big deal for datagrids our size). By switching to mui tables, we earn many options, like the ability to make striped rows, hover effect, fixed header, etc. Besides, their `<Table>` supports theming way better than our custom one.
The default design changes a bit, but not too much.
Before:
After:
Closes #308

[RFR] Use mui <Table> element for datagrid

---

src/util/fetch.js

The app nevers logout because the status is missing from the error.
The status is needed here :
https://github.com/marmelab/admin-on-rest/blob/master/src/sideEffect/saga/auth.js#L7
don't know if it's the best way to define the custom error like this.
Maybe we could just throw a simple object ?

Missing status in fetch when error is thrown

---

src/mui/button/EditButton.js
src/mui/button/ShowButton.js
src/mui/layout/AppBar.js
src/mui/layout/Layout.js

Avoid rendering the entire `<AppBar>` on every refresh by moving the loader out of it (saves about 30ms).

[RFR] Improve loader rendering speed

---

src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js
src/reducer/resource/data.js

Our optimistic rendering strategy used to conflict with redux-form. When navigating to an `<Edit>` view, we use the current state (usually filled up by the `<List>` view) to prefill the form via redux-form's `initialValues`. Then we fetch the up-to-date record via a `CRUD_GET_ONE` action. When the REST server arrives, we update the state with the updated record, which updates the (connected) `<Edit>` view. 
But rerendering the `<Edit>` view just updates the ùinitialValues`, and by default redux-form doesn't listen to changes of this attribute (see https://github.com/erikras/redux-form/issues/176 and http://redux-form.com/6.5.0/examples/initializeFromState/). Passing `enableReinitialize: true` solves the problem.
Closes #305

[RFR] Fix Edit view shows stale data

---

Makefile

As we moved the RTE into a dedicated repository, there is no more need to copy CSS, as there is no more.

[RFR] No need to copy CSS files anymore

---

src/actions/dataActions.js

Enables fetching multiple resources in one go in custom forms/pages

Allow overriding cancelPrevious on crudGetList

---

docs/Authentication.md
src/Admin.js

I would like to differentiate where to redirect users when auth check fails. If user is not logged in, the default redirect to `/login` is fine, but when user is logged in and authorization fails, I would like to redirect to e.g `/no-access`.
I'm not 100% comfortable with the suggested implementation, but at least it's a conversation starter.

Allow to override redirect path when auth check fails

---

docs/RestClients.md
example/package.json
src/reducer/references/oneToMany.js
src/reducer/resource/data.js
src/rest/jsonServer.js
src/rest/simple.js

This changes the expected return format of the `restClient`. Now it must systematically return an object with a `data` property.
```diff
Type                 | Response format
-------------------- | ----------------
`GET_LIST`           | `{ data: {Record[]}, total: {int} }`
-`GET_ONE`            | `{Record}`
-`CREATE`             | `{Record}`
-`UPDATE`             | `{Record}`
-`DELETE`             | `{Record}`
-`GET_MANY`           | `{Record[]}`
-`GET_MANY_REFERENCE` | `{Record[]}`
+`GET_ONE`            | `{ data: {Record} }`
+`CREATE`             | `{ data: {Record} }`
+`UPDATE`             | `{ data: {Record} }`
+`DELETE`             | `{ data: {Record} }`
+`GET_MANY`           | `{ data: {Record[]} }`
+`GET_MANY_REFERENCE` | `{ data: {Record[]}, total: {int} }`
```
This removes a …

[RFR] [BC Break] Update REST response format

---

src/mui/input/ImageInput.js
src/mui/input/ImageInput.spec.js

Currently, if we dispatch a new form value via `redux-form` like the following:
``` js
import { change } from 'redux-form';
import { put } from 'redux-saga/effects';
put(change('record-form', 'landscapeImage.url', mainImage.url)),
```
The image preview doesn't update, as it is only updated in `<ImageInput />` constructor. This PR fixes that.

[RFR] Update image preview when dispatching new form value

---

docs/Inputs.md
src/mui/input/NumberInput.js
src/mui/input/NumberInput.spec.js
src/mui/input/TextInput.js
src/mui/input/TextInput.spec.js

Indeed, Redux Form sends `FOCUS` and `BLUR` actions on focus and blur respectively. It is especially used for asynchronous form validation.
This PR does **not** fix all inputs, but only the Text and Number inputs. Indeed, it would need additional work, especially for the `<Autocomplete />` field.

[RFR] Allow to pass custom onBlur, onChange and onFocus on Number and Text inputs

---

src/actions/dataActions.js
src/sideEffect/saga/crudResponse.js

I'm making a form where users can batch create multiple resources at once. This change lets me reuse existing actions, but wait with notification/redirect until all resources are created. 
It's a bit annoying to get redirected say ten times in a couple of seconds:)

Allow to execute crud actions without redirect

---

src/rest/jsonServer.js

GET_MANY expects { data: {Record[]} } and not {Record[]} anymore.

jsonServer GET_MANY implementation with new format

---

README.md
docs/Actions.md
docs/AdminResource.md
docs/CreateEdit.md
docs/CustomApp.md
docs/Fields.md
docs/Inputs.md
docs/List.md
docs/Theming.md
docs/Tutorial.md
docs/index.md
example/app.js
example/comments.js
example/posts.js
src/index.js

We initially thought that we'd offer support for other UI Kits than material ui. This made `imports` systematically harder, since developers had to think whether the script they imported was mui related or not. Also, we probably won't do it ourselves, and there are other ways to bundle another version of admin-on-rest with a different ui kit.
By exporting the `mui` components in the root, every import is simpler.

[RFR] Simplify imports by exporting mui in the project root

---

example/comments.js
example/posts.js
src/mui/input/AutocompleteInput.js
src/mui/input/ReferenceInput.js
src/mui/input/SelectInput.js
src/mui/list/FilterForm.js

The custom style was required when using SelectInput as a Filter.
Switching to Flex solves the problem.
Closes #447

[RFR] Fix SelectInput error text position

---

docs/CreateEdit.md
src/i18n/messages.js
src/mui/detail/Create.js
src/mui/detail/Edit.js
src/mui/form/validate.js
src/mui/form/validate.spec.js

This uses the new form validators, that's why it's committed to `next` rather than `master`.
Closes #307

[RFR] Translate error messages

---

src/mui/layout/Layout.js

Before:
After:
See:
- https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items
- https://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/
Fix #467

Layout: fix IE11 compatibility

---

docs/Inputs.md
src/mui/input/ImageInput.js
src/mui/input/ImageInput.spec.js

Add a `dropAreaLabel` property which can contains any node.
Used to render the `Dropzone` label on `ImageInput`.

Allow use of custom label for ImageInput drop area

---

docs/Tutorial.md

The URI in the document was not pointing to the right location on JSON placeholder, so I corrected it.

Point Users link to the right URI on JSONPlaceholder

---

docs/Fields.md
src/mui/field/ReferenceField.js
src/mui/field/ReferenceField.spec.js

Supersedes #486 by fixing coding standards and documentation, and adding tests.
Fixes #247.

[RFR] Add `linkType` to ReferenceField

---

src/mui/input/NullableBooleanInput.js
src/mui/input/NullableBooleanInput.spec.js

Our own `<SelectInput>` doesn't have an `errorText` prop, but it expects a `meta` prop.
Closes #507

[RFR] Fix NullableBooleanInput

---

src/mui/detail/Edit.js
src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js

Closes #451 
The problem was that we increment the `<Card>` component `key` to force remounting of all input components, which should trigger fetching of related records for `<ReferenceInput>` fields (see #290).
So far so good, but what's surprising is that React first *mounts* the new Card version, then *unmounts* the old Card version. And this is not good for the enclosed form:
1. A new instance of the `<SimpleForm>` component is mounted
2. Because it shares the same form name (`record-form`), the reduxForm instance is unchanged
3. The old instance of the `<SimpleForm>` component is unmounted 
4. Upon unmount, the reduxForm instance is destroyed. Unfortunately, it's the same as before, because it has the name `record-form`
5. All further updates on the form fail because the form is …

[RFR] Fix refresh on Edit clears data

---

src/mui/detail/Edit.js
src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js

Reverts marmelab/admin-on-rest#527, which breaks the Creation view. I'll post a new PR without side effects.

Revert "[RFR] Fix refresh on Edit clears data"

---

package.json
src/mui/list/Filter.js
src/mui/list/FilterForm.js
src/mui/list/List.js

Allows to use a custom `<Filter>` component, e.g. to force filter form submission before issuing REST request. Also, this allows to customize the filter debounce delay. Lastly, it allows to move filter-related logic out of the `<List>` component.

[RFR] Refactor Filters to use redux-form new onChange method

---

src/Admin.js

Hi there,
Just a little fix that prevents the `Admin` component from crashing at render time when the first `Resource` wasn't (yet) loaded.
Also as the children node isn't marked as required, it should be fair to allow no children at all.
In such case, the resources variable was undefined, as the [`React.children.map` doc](https://facebook.github.io/react/docs/react-api.html#react.children.map) suggests.

Fix Admin component crash while rendering if first resource isn't loaded yet

---

docs/CreateEdit.md
docs/Inputs.md
docs/Tutorial.md
src/mui/form/SimpleForm.js
src/mui/form/TabbedForm.js
src/mui/input/LongTextInput.js
src/mui/input/NumberInput.js
src/mui/input/TextInput.js

Hi, I think `validation` props is no longer valid, so I've updated docs and input/forms.

Reflect validation changes to docs and prop types for input/form

---

src/mui/list/List.js

When page and perPage are taken from the url query, they will be strings, this can cause problems downstream in the rest client, which expects ints

Ensure pagination params are integers

---

src/sideEffect/saga/auth.js

Hello again :)
When authclient reject with `string` reason, I think AOR should show that `string` message as error message.

Show rejected reason as error message if the type is string

---

src/mui/delete/Delete.js
src/mui/detail/Edit.js
src/mui/detail/Show.js

This PR fixes decoding id with special chars like "/" in `Show`, `Edit` and `Delete` components.
`react-router` v4 requires manually decoding uris as opposed to previous version.
Without this change id with special chars are broken in v1.0.0.
Related PR: #209

decode id uri component matched from react router

---

src/Admin.js
src/mui/layout/Layout.js

Given that MUI accept "node" proptype for "title" props on the AppBar. We should change it in AOR to avoid warnings.
https://github.com/callemall/material-ui/blob/master/src/AppBar/AppBar.js#L134

[RFR] Remove warning for "non-string" title prop

---

src/sideEffect/saga/auth.js

Based on #582, this small change will send the result of `AUTH_LOGIN`'s resolve as a payload on `USER_LOGIN_SUCCESS`. This way we can integrate, in a simple way, integrate the login with redux.
In my case I just wanted to save user's profile on the store.
Based on the discussion seem that there are some more complex ideas around but this change is enough for what I need and this is my suggestion.
( Replaces PR #615 )

AUTH_LOGIN's resolve's result goes as payload on USER_LOGIN_SUCCESS

---

src/mui/field/DateField.spec.js

Fixes #614
Not fan of the logic duplication but I can't think of another way to ensure those tests pass on all systems.

[RFR] Ensure DateField tests can pass on all systems

---

src/mui/layout/Sidebar.js

The `flex` property was ignored with default MUI theme as it does not specify the width units by default (`256`)

[RFR] Fix sidebar styles

---

src/mui/field/RichTextField.js

If you don't enter anything in a `RichTextInput`, the sent string is `undefined` and will break `removeTags`. I fix it by returning an empty string for any falsey value.
Obviously, a robust form will avoid this by validating against such values, but this doesn't hurt either and is probably the expected behavior.

Fix edge case in RichTextField when string is falsey value

---

docs/Authentication.md
src/Admin.js

When a user logs out, the redux store still holds potentially sensitive data. this resets the store to its initial state.
if there is an alternative or cleaner way to achieve this without changing core code, please let me know :)
based on [this answer](http://stackoverflow.com/a/35641992).

[RFR] Add reset state after logout

---

docs/CreateEdit.md
src/mui/button/SaveButton.js
src/mui/button/SaveButton.spec.js
src/mui/form/SimpleForm.js
src/mui/form/SimpleForm.spec.js
src/mui/form/TabbedForm.js
src/mui/form/TabbedForm.spec.js
src/mui/form/Toolbar.js

I needed this functionality because I've added `react-google-maps` with the `<Searchbox/>` to my form. But if the user was selecting from the searchbox by pressing enter on the keyboard and not by clicking on one of the results, the form got submitted. 
I found this comment https://github.com/erikras/redux-form/issues/572#issuecomment-268905929 on how to disable this auto submit behaviour.
~~I added `simple-mock` as a dependency as I needed spying on methods, I chose this one over `sinon` because this is smaller and has no dependencies. If you have anything against this library or if I have missed that there is already a mocking lib included I can amend the code.~~
I realised `sinon` was already added as a dependency.
This change doesn't break backward compatibility.
ps: awesome project! …

Adding switch to submit on enter behaviour to <SimpleForm> and <TabbedForm>

---

src/mui/button/EditButton.js
src/mui/button/ShowButton.js

Bug fix for an issue that can be reproduced by the following step:
1. run example app `make run`
2. open `http://localhost:8080/#/posts/13` (and refresh broswer).
3. the show button links to `http://localhost:8080/#/posts/undefined/show` rather than `http://localhost:8080/#/posts/13/show`

fix show(edit) button in edit(show) page

---

e2e/pages/EditPage.js
e2e/tests/edit.js
example/data.js
example/posts.js
src/mui/input/DateInput.js
src/mui/input/DateInput.spec.js

~~issue: onBlur causes redux-form to fetch raw value (for example
12/08/2017) from DatePicker.~~
I checked both redux-form and material-ui. 
Currently, DatePicker's event flow is like this:
1. User click on the input triggers `onBlur`
2. User close the input without  selecting value triggers `onDismiss`
3. User select a value triggers `onChange`
And for redux-form:
1. `onBlur` is used to update value(if event param is provided) and validate the field.
2. `onChange` is used to update value.
#691

[RFR] Fix a redux-form onBlur related issue

---

src/mui/input/SelectArrayInput.js

Having a function as `optionText` does work on `SelectArrayInput` but gives a console warning:

[RFR] Fix SelectArrayInput prop types

---

docs/Inputs.md
src/mui/input/BooleanInput.js

I need to set right position for label for BooleanInput and find that there is not properties which responsible for it. I think that this commit will be useful.
Thanks for chance to take participating in this project.

[RFR] Pass options to BooleanInput for Toggle

---

example/posts.js

Because example does not support custom tag, creating new tag by pressing enter should be disabled. 
(with custom tag, the field value may look like `[1,2,'A Tag']`).

Disable creating new tag by pressing enter

---

src/mui/list/Actions.js
src/mui/list/Filter.js
src/mui/list/FilterForm.js
src/mui/list/List.js

The commit efccc73d179 introduced the usage of flexbox to properly align
the filter form. It also introduced a regression with mobile device.
The issue was due to a mixed usage of flexbox and floating div.
This commit add flexbox layout for the whole list header:
* title
* add filter/create/refresh buttons
* filter form.
Some small changes are observed, the main one is the alignement of the
"Refresh" button on the right on mobile.
Closes: #754

list; use flexbox for all the header items

---

src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js
src/mui/input/CheckboxGroupInput.js
src/mui/input/CheckboxGroupInput.spec.js
src/mui/input/RadioButtonGroupInput.js
src/mui/input/RadioButtonGroupInput.spec.js
src/mui/input/SelectArrayInput.js
src/mui/input/SelectArrayInput.spec.js
src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js

Our REST server returns JSON with nested fields like:
```javascript
[
{ "id": "M", "foobar": { "name": "Male" } },
{ "id": "F", "foobar": { "name": "Female" } }
]
```
I'd like to use the "name" value in "foobar" as `optionText` of `SelectInput` within `ReferenceInput`. Although we can specify a function as `optionText` in this case, I'd like to specify a string "foobar.name" for simplicity.

Handle deep paths for optionText and optionValue

---

docs/CreateEdit.md
src/mui/form/validate.js

Closes #768
I didn't add the ability to `required` and `email` because that's a BC break.

[RFR] Custom validator messages

---

docs/Tutorial.md
src/rest/jsonServer.js
src/rest/simple.js
src/util/fetch.js
src/util/fetch.spec.js

According to [json-server's README](https://github.com/typicode/json-server#filter), it supports multiple query parameters with a same name (e.q. `GET /posts?id=1&id=2`). However, current `queryParameters({ foo: ['bar', 'bar'] })` returns a string `"foo=bar%2Cbaz"`, not `"foo=bar&foo=baz"`.
Note that I might be a good idea to replace `queryParameters` to `stringify` directory and remove the `queryParameters` function.

Use stringify to generate a query string

---

src/mui/input/AutocompleteInput.js
src/mui/input/DateInput.js
src/mui/input/Labeled.js
src/mui/input/LongTextInput.js
src/mui/input/NumberInput.js
src/mui/input/SelectArrayInput.js
src/mui/input/SelectInput.js
src/mui/input/TextInput.js

Decorating an aor `Input` component invariably leads to a very frustrating error:
> Cannot read property 'touched' of undefined
`undefined` in that case refers to the `meta` prop, which is supposed to be passed to the component by a redux-form `<Field>` component. The reason is that all aor `<Input>` components must be embedded inside a `<Field>`. To avoid repetition, we chose to let `<SimpleForm>` and `<TabbedForm>` do the `<Field>` decoration whenever they see an `Input` components with the `addField` prop set to `true`. But this doesn't work for decorated inputs:
```js
const MyInput = props => <LongTextInput source="teaser" validate={required} {...props} />;
```
This input has no `addField` default prop, and therefore will not be decorated by a `<Field>`. To fix that, the developer …

[RFR] Replace "Cannot read property 'touched' of undefined" error by a more meaningful one

---

Makefile
example/package.json
package.json

We don't need webpack in the main project, only in the example. Moving the related dependencies to emphasize that admin-on-rest is bundle agnostic.

[RFR] Move webpack to example

---

src/mui/input/RadioButtonGroupInput.js

The **RadioButtonGroupInput** wasn't translating its label, and I've found out why. The `resource` prop was undefined, so it would never find the correct translation. I think this also fix #454.

[RFR] Fix RadioButtonGroupInput label translation

---

src/mui/form/TabbedForm.js

`TabbedForm` children are `FormTab`, not inputs, therefore we must gather `FormTab` children to get their default values

[RFR] Fix TabbedForm initialValues gathering

---

src/mui/detail/TabbedShowLayout.js

same as https://github.com/marmelab/admin-on-rest/issues/567, but for `TabbedShowLayout`

Fix translation warning on TabbedShowLayout's tab names

---

src/sideEffect/saga/crudFetch.js
src/util/HttpError.js
src/util/fetch.js

This PR adds the possibility to pass the response body to a HttpError instance. This response body is then passed in `*_FAILURE` actions so it can be used elsewhere in the app.
I coded this because I needed to get server validations errors (which are in the response) in my app.

Add response body to HttpError

---

docs/Tutorial.md
docs/_layouts/default.html

I just changed a few instances of the word 'edtion' to 'editing' or 'edit', which I think is clearer (I did not change the link to the image with Edition name).

Changed 'Edition' to Editing or Edit, etc

---

docs/Admin.md
src/Admin.js

At this time, when using the `customRoutes` prop, the routes are rendered in the default Layout.
While this is the expected behavior, a user might need to add routes which are not rendered inside the default layout (i.e: password forgot dance, or user registration). The only way of doing that is to follow the [custom app tutorial](https://marmelab.com/admin-on-rest/CustomApp.html) which comes at other expenses (maintenance, loss of dev speed). 
At a quick glance on the code, it was pretty easy to add a `layoutlessRoutes` props which are rendered outside of the default Layout. This is the purpose of this PR. Feedbacks are welcome :)

[RFR] Layoutless routes

---

src/mui/auth/Login.js
src/reducer/loading.js
src/reducer/loading.spec.js

#394 added functionality for locking the login form and showing a spinner when the user presses *Sign In*. But as you can see [here](https://github.com/marmelab/admin-on-rest/pull/394#discussion_r104874927) this requires the `onSubmit` function to return a `Promise`. This is not the case after using saga for auth side-effects.
So in this PR I attempt to change to `loading reducer` to also work for `auth actions` (not sure if this is appropriate if a separate reducer should be used) and use `loading` instead of redux-form's `submitting` as an indicator.

[RFR] Fix login form-lock and loader after saga refactoring

---

package.json

The current version `full-icu@1.0.3` fails to install with `yarn`. This rendered me and perhaps other people unable to use yarn for admin-on-rest. `full-icu@1.1.3` fixes this.
This time without updating `selenium-webdriver` and `chromedriver`.

[WIP] Update full-icu to 1.1.3 to support yarn

---

src/reducer/references/possibleValues.js

Because the list of selected ids can come from checkboxes, whose values are always strings
Closes #870

[RFR] Check inclusion using non-strict equality

---

package.json
src/mui/list/Filter.js
src/rest/jsonServer.js
src/util/fetch.js
src/util/fetch.spec.js
src/util/removeEmpty.js
src/util/removeEmpty.spec.js

There are two problems when a deep property is specified in `Filter` like:
```javascript
const MyFilter = props => (
<Filter {...props}>
<TextInput source='foo.bar' label='Foo' />
</Filter>
);
const MyList = props => (
<List {...props} filters={<MyFilter />}
...
</List>
);
```
* Invalid query string (E.g. `"foo=%5Bobject%20Object%5D"`) is generated for json server. This should b flatten like `"foo.bar=val"`.
* When the text input value is cleared, the filter value is not removed from filter parameters.

Support nested filter object

---

src/mui/input/Labeled.js

Another way to tackle this would be check for error inside the FileInput. This would give us more control over the error message placement.
Haven't noticed any regressions on the other inputs
Fix #825

[RFR] Ensure FileInput validation messages are displayed

---

src/mui/form/TabbedForm.js
src/mui/form/TabbedForm.spec.js

Fixes #960
When the tab with errors is inactive:
When the tab with errors is active:
We don't apply the error style on active tab to avoid displaying errors on non yet dirty fields

[RFR] Fix TabbedForm errors are hidden for inactive tabs

---

src/util/fetch.js

..., this way it is possible to use **fetchJson** in own rest clients. In our case we had to fork this, because we use **'application/merge-patch+json'** and **'application/json-patch+json'** in the server, to differentiate between the both formats.

[fetchJson] check for "Content-Type" already set, before setting automatically

---

src/mui/input/SelectInput.js
src/mui/input/SelectInput.spec.js

The problem was that when `allowEmpty` was false, we inserted a `false` element in the `SelectField`. However, there are no check for null or false children inside the MUI component which does some introspection on its children for keyboard navigation: [Menu](https://github.com/callemall/material-ui/blob/master/src/Menu/Menu.js#L386)
Fixes #952

[RFR] Fix SelectInput selection via keyboard

---

docs/Admin.md
src/mui/layout/Sidebar.js

On medium devices onMenuTap will be undefined. Since onMenuTap is a required prop of MenuItemLink this leads to a "Warning: Failed prop type..." in the Chrome React console.

Correct the Menu.js example in Admin.md

---

docs/Ecosystem.md

This PR adds the following packages to the documentation
- [aor-embedded-array](https://github.com/MhdSyrwan/aor-embedded-array)
- [aor-rest-client-router](https://github.com/MhdSyrwan/aor-rest-client-router)

Adds aor-embedded-array and aor-rest-client-router

---

docs/Admin.md
docs/CreateEdit.md
docs/List.md
docs/Show.md
src/AdminRoutes.js
src/AdminRoutes.spec.js
src/mui/detail/Create.js
src/mui/detail/Edit.js
src/mui/detail/Show.js
src/mui/list/Filter.js
src/mui/list/List.js
src/mui/withChildrenAsFunction.js
src/mui/withChildrenAsFunction.spec.js
src/util/getMissingAuthClientError.js

Allows to use the function as child pattern in components that support it, without an authClient.
This function might return a promise.
Fixes #1009

[RFR] Function as children without permissions

---

docs/Resource.md
docs/_layouts/default.html

[RFR] Documentation fixes

---

src/mui/input/FileInput.js
src/mui/input/FileInput.spec.js

This PR introduces a breaking change:
When allowing only a single file, `onChange` will be called with a single file (instead of an array containing a single file).

[RFR] [BC Break] Review FileInput handling when allowing only a single file

---

src/i18n/messages.js
src/mui/layout/NotFound.js

This PR proposes two small updates regarding `src/i18n/messages.js`.
1. Removed space before `?` for `aor.message.are_you_sure`.
2. Moved the trailing `.` from `src/mui/layout/NotFound.js` to `aor.message.not_found` instead to allow proper i18n for languages that don't typically use `.` for sentence ends, e.g. Japanese and Chinese.

[RFR] Minor copywriting updates

---

src/mui/button/EditButton.js
src/mui/button/ShowButton.js

nextProps.record is potentionally undefined
- ie. it happens when hot reloading

[RFR] fix shouldUpdate for EditButton and ShowButton

---

docs/Ecosystem.md

if you feel react-admin-java-rest should be under Miscellaneous that's fine too

add component factory and java rest building blocks to Ecosystem.md

---

packages/react-admin/src/mui/form/FormField.js

This bug is also visible in the example app, edit a post title (which is required) and remove all text. The validation error will not appear and the post is saved.

Bug: Validate not being passed on redux-form field.

---

docs/Actions.md

In 'Writing Actions', the suggested styling for `CommentEditActions` (`float: right`) leads to the custom actions being non-clickable.  I've updated the styles to mirror those suggested in the documentation for [CreateEdit](https://github.com/marmelab/admin-on-rest/blob/master/docs/CreateEdit.md#actions).

Documentation update for 'Writing Actions'

---

src/mui/layout/Layout.js

Which is not possible when content height e.g number list items exceeds the screen height.
https://github.com/marmelab/admin-on-rest/issues/1165

#1165 Fixed vertical scroll issue on page on IE11

---

src/Admin.js

Using a-o-r as part of a gatsbyjs app, this change makes it possible to build.

Check that window exists before checking for devToolsExtension

---

packages/react-admin/src/AdminRoutes.spec.js
packages/react-admin/src/auth/WithPermissions.js

When an user logs out, the permissions of `WithPermissions` should be reevaluated.

[RFR]: Reevaluate permissions on user logout.

---

packages/react-admin/src/AdminRoutes.js

Resources aren't reloaded after logout (@see https://github.com/marmelab/admin-on-rest/pull/1306), because of `isLoggedIn` not being checked correctly. This PR fixes that.
Then I saw that `setState` is called in `componentWillUpdate`; The react docs say not to call `setState` within `componentWillUpdate`: https://reactjs.org/docs/react-component.html#componentwillupdate. 
This PR fixes that as well.

[Fix]: User logout & setState moved away from componentWillUpdate

---

docs/CreateEdit.md

The docs seem to use "validation" and "validate" as the prop name.  I believe the prop is always "validate", is that correct?  I think the help docs section title "Validation" is fine, but the prop definition list and examples should use validate.

Prop name is validate not validation

---

packages/ra-data-fakerest/package.json
packages/ra-data-graphcool/package.json
packages/ra-data-graphql/package.json
packages/ra-dependent-input/package.json
packages/ra-input-rich-text/package.json
packages/ra-realtime/package.json

The plugins shouldn't dependent on react-admin but rather have a peerDependency on it. For testing it should be added to devDependencies.

[RFR] Change dependencies to peerDependencies

---

src/mui/input/AutocompleteInput.js

The `AutocompleteInput` when used in conjunction with `ReferenceInput` does not populate for existing values when initially rendered if the `allowEmpty` property is true for `ReferenceInput`. However, if you force a re-render (for example by navigating away and back) the field will be populated as expected.
I think the bug was introduced in this commit: 0432a56c6edf9ec7930ac6226116465383a0cb17
**Steps to reproduce:**
You can reproduce the bug in this application: https://codesandbox.io/s/m46njp1r6p
When you first view the "Edit" action for any "Comment" resource, you should notice that the "Post" field does not get populated. If you remove the `allowEmpty` property though, it will be populated.
**Environment**
* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue: …

AutocompleteInput does not render text for existing value on initial render

---

src/mui/layout/Title.js

Fixes #1236
This is because onlyUpdateForKeys does not work for deep objects. See https://github.com/acdlite/recompose/issues/166

[RFR] Fix title is not updated when record changes

---

src/i18n/messages.js
src/mui/list/List.js
src/mui/list/List.spec.js

Fix #1370 
From a paginated list, if user delete the last item of the current page, he is redirected to that same empty page.
This PR allows to redirect to the previous page a paginated list when it is displayed after a redirection caused by aor.
If the empty page is explicitly displayed by the user (i.e. with query params), a warning message will now be displayed.

[RFR] Redirect to correct page after Delete

---

src/i18n/messages.js
src/sideEffect/saga/crudResponse.js

Fix #1027 
Display error notification when fetch bad record, simple backport from PR #1125 done on `next`.

[RFR] Bad element error

---

src/mui/input/DisabledInput.js

I needed to use the following code to stretch the field in full width and I could not.
````
options={{
fullWidth: true,
}}
````

Add 'options' to DisabledInput too

---

src/mui/list/List.js

To fix the problem with NaN, it was merged on 'next' but not on 'master'

Fix List default pagination to avoid displaying NaN

---

docs/Inputs.md
packages/react-admin/src/mui/input/ReferenceArrayInput.js
packages/react-admin/src/mui/input/ReferenceArrayInput.spec.js
packages/react-admin/src/mui/input/ReferenceInput.js
packages/react-admin/src/mui/input/ReferenceInput.spec.js
packages/react-admin/src/mui/input/SelectInput.js
packages/react-admin/src/reducer/admin/index.js
packages/react-admin/src/reducer/admin/references/index.js
packages/react-admin/src/reducer/admin/references/possibleValues.js
packages/react-admin/src/reducer/admin/resource/index.js
packages/react-admin/src/reducer/index.js

When working with the autosuggest item I encountered several issues with the `ReferenceInput` components, I separated them in this dedicated PR:

[RFR]: Reference input issues

---

packages/react-admin/src/mui/input/ReferenceArrayInput.js
packages/react-admin/src/mui/input/ReferenceInput.js
packages/react-admin/src/reducer/admin/index.js
packages/react-admin/src/reducer/admin/references/index.js
packages/react-admin/src/reducer/admin/references/possibleValues.js
packages/react-admin/src/reducer/admin/references/possibleValues.spec.js
packages/react-admin/src/reducer/admin/resource/index.js
packages/react-admin/src/reducer/admin/resource/index.spec.js
packages/react-admin/src/reducer/index.js

[RFR] Refactor reference selectors

---

packages/react-admin/src/mui/list/DatagridCell.js
packages/react-admin/src/mui/list/DatagridCell.spec.js

Fixes #800
It allows to overwrite the `basePath` of an `EditButton` inside a `Datagrid`:
```js
<Datagrid>
<EditButton basePath="anything" />
</Datagrid>
</List>
```
I read the documentation but I'm not sure where to add this additional prop. Any help?

[RFR] Allow to overwrite basePath on actions inside Datagrid

---

docs/List.md
packages/react-admin/src/mui/field/ReferenceField.js
packages/react-admin/src/mui/field/ReferenceField.spec.js
packages/react-admin/src/mui/list/SingleFieldList.js
packages/react-admin/src/mui/list/SingleFieldList.spec.js
packages/react-admin/src/util/linkToRecord.js
packages/react-admin/src/util/linkToRecord.spec.js

[RFR] SingleFieldList now accepts a linkType prop

---

docs/Inputs.md
docs/Tutorial.md
example/comments.js
example/posts.js
src/i18n/messages.js
src/mui/input/ReferenceArrayInput.js
src/mui/input/ReferenceArrayInput.spec.js
src/mui/input/ReferenceError.js
src/mui/input/ReferenceInput.js
src/mui/input/ReferenceInput.spec.js
src/mui/input/ReferenceLoadingProgress.js
src/reducer/admin/references/possibleValues.js
src/reducer/admin/references/possibleValues.spec.js

Fix #953 
Fix #1153 
`allowEmpty` should only be used to add or not an empty choice in the choices list, with a value of null.
It must not interfere with the fetch of references.
The reference selectors must indicate either that the reference fetch is in progress, that the reference fetch has failed, or display the *choice component* with choices based on the fetched references.

[RFR] Decoupling allowEmpty prop from reference selectors

---

src/i18n/messages.js
src/mui/input/AutocompleteInput.js
src/mui/input/AutocompleteInput.spec.js

[RFR] Fix AutocompleteInput

---

docs/Ecosystem.md

The old one is not maintained.

Use new repo for GraphQL

---

packages/ra-ui-materialui/src/list/BulkActions.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/ListActions.js

Before:
After:
Supersedes #1547

[RFR] Improve checkbox design

---

Makefile
packages/ra-core/src/reducer/admin/references/oneToMany.js

References to a non-declared Resource is a common error in ng-admin and admin-on-rest (see #1393).
The current error message is pretty misleading.
I improved it a bit with a description of what is happening and how to resolve it.
For example, now if you remove the resource `tags` of the simple example:

[RFR] Better error messages for references of undeclared Resources

---

packages/ra-ui-materialui/src/auth/Logout.js
packages/ra-ui-materialui/src/button/DeleteButton.js
packages/ra-ui-materialui/src/defaultTheme.js
packages/ra-ui-materialui/src/delete/Delete.js
packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/layout/AppBar.js
packages/ra-ui-materialui/src/layout/AppBarMobile.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/Loading.js
packages/ra-ui-materialui/src/layout/LoadingIndicator.js
packages/ra-ui-materialui/src/layout/Menu.js
packages/ra-ui-materialui/src/layout/MenuItemLink.js
packages/ra-ui-materialui/src/layout/Responsive.js
packages/ra-ui-materialui/src/layout/Responsive.spec.js
packages/ra-ui-materialui/src/layout/Sidebar.js
packages/ra-ui-materialui/src/layout/ViewTitle.js

Before:
After:
Supersedes #1542

[RFR] Improve colors, sidebar, and layout

---

packages/ra-ui-materialui/src/layout/Layout.js

The layout grabbed the theme *after* mounting mui's ThemeProvider. As a consequence, the theme wasn't available in the layout - only to sub components.
This was especially visible in the "dark" theme on the demo:
Before:
After:

[RFR] Fix theme is not available in layout

---

examples/simple/posts.js
packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/list/Datagrid.js

Leave more space to the content and less to the chrome.
Before:
After:

[RFR] Reduce datagrid toolbar horizontal spacing

---

e2e/tests/permissions.js
examples/simple/posts.js
examples/simple/users.js
packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/field/sanitizeRestProps.js
packages/ra-ui-materialui/src/layout/Confirm.js
packages/ra-ui-materialui/src/list/BulkActions.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/DatagridCell.js
packages/ra-ui-materialui/src/list/DatagridHeaderCell.js
packages/ra-ui-materialui/src/list/DatagridHeaderCell.spec.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/FilterButton.js
packages/ra-ui-materialui/src/list/Pagination.js

Since we implemented the components with early versions of material-ui 1.0, their have implemented features that we also implemented on our side.
Let's catch up by using their features instead of ours. Benefits: less code to maintain, better alignment of header and content in datagrid.
Before:
After:

[RFR] Use material ui features

---

e2e/pages/CreatePage.js
examples/simple/app.js
examples/simple/dataProvider.js
packages/ra-core/src/reducer/admin/resource/data.js
packages/ra-core/src/reducer/admin/resource/list/ids.js
packages/ra-core/src/reducer/admin/resource/list/total.js
packages/ra-core/src/sideEffect/saga/crudResponse.js
packages/ra-core/src/sideEffect/saga/crudSaga.js
packages/ra-core/src/sideEffect/saga/index.js
packages/ra-core/src/sideEffect/saga/optimistic.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/List.js

The idea is to accelerate the rendering of the admin after the user saves some changes by using optimistic rendering, i.e. updating the local store and rerendering *before* the server acknowledges the change.
In the following screencast, notice how the two selected items disappear right after clicking on "Delete" - and way before the Snackbar, which displays the server confirmation, appears.

[RFR] Optimistic Updates

---

docs/Ecosystem.md

Current version support only `create` new module.
Upcoming features:
> - Updating an existing module
> - Adding tests
> - Prompt-based cli on version `2.0.0`
> - `aor init` to initiate an ejected `create-react-app` with `admin-on-rest` pre-configured and database selector on the cli interface

Update Ecosystem.md : Add aor-cli package

---

packages/ra-core/src/CoreAdminRouter.js
packages/ra-core/src/RoutesWithLayout.js
packages/ra-ui-materialui/src/layout/AppBar.js

Changed some proptypes and use `cloneElement` when title is an element. This allows the element to use the correct `theme` (themeprovider is initialized in the layout).

[RFR]: Allow title to be an element

---

e2e/pages/EditPage.js
e2e/tests/edit.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Fixes #1613.
A bug is present from the upgrade to React16:
1. Edit a post on /#/posts/5,
2. Change URL and go on /#/comments/5 instead
Comment form is empty. This is due to the way React16 handle component lifecycle: it mounts the new component, then unmount the previous one. Hence, our form values are first initialized during the mounting of the new component, and then destroyed by the unmounting. As we are using the same name, it raises the issue.
We may either change form names, or never unmount our forms. As the first solution would break a lot of ecosystem plug-in (for instance [aor-dependant-input](https://github.com/marmelab/aor-dependent-input)), we choose the latter solution. Memory footprint should not be too much increased, as we only have two different forms: `filtersForm` and …

[RFR] Fix form unmount issues

---

packages/ra-ui-materialui/src/list/ListActions.js

The page breaks (with error message), when using `bulkActions` prop as a boolean `false` (for hiding the checkboxes):
```
<List
{...props}
title={<TitleList />}
bulkActions={false}
>
```
This PR fixes this problem.

Fix 'bulkActions' boolean functionality

---

packages/ra-ui-materialui/src/field/ChipField.js
packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.spec.js

The simple example shows : 
```
<ReferenceArrayInput reference="tags" source="tags">
<SelectArrayInput>
<ChipField source="name" />
</SelectArrayInput>
</ReferenceArrayInput>
```
This make me think that the `SelectArrayInput` uses `ChipField` to render, but it doesn't. Currently it renders a `<Chip >` field. This PR changes this to clone the child element instead.

[RFR]: SelectArrayInput render child instead of Chip

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/ReferenceInput.js

For `ReferenceInput` and `ReferenceArrayInput` remove passing through rest props to Labelled component. Is gives a lot of errors in the console, because `Loading` does support there props.

[RFR]: Remove passing through rest props to Labelled component

---

packages/ra-core/src/actions/undoActions.js
packages/ra-core/src/sideEffect/undo.js
packages/ra-core/src/sideEffect/undo.spec.js
packages/ra-ui-materialui/src/layout/Notification.js

So a user be like: let me check the notification in the snackbar by hovering my mouse over it. After a couple of seconds he/she understands the message and decides to undo the action, but it does not work, the record is already removed. see screenshot: 
This PR removes the `delay` from the saga and allows the UI to call the complete: 
As you can see nothing happens while the mouse is over the snackbar.

[RFR]: Use ui to trigger undoable complete action

---

packages/ra-ui-materialui/src/layout/Menu.js

The Menu used to be rerendered at least 4 times on each page, because it was rerendered each time the data changed in the resources.
Before:
After:

[RFR] Prevent Menu rerenderings

---

docs/RestClients.md

The GET_MANY_REFERENCE example code was broken because of a `;` before the `.then`, probably carried over from the previous example.

[RFR] fix GET_MANY_REFERENCE example in RestClients.md

---

package.json
packages/ra-core/src/controller/ListController.js
packages/ra-core/src/controller/ListController.spec.js
packages/ra-ui-materialui/src/list/Filter.js
yarn.lock

Currently, `setFilters` is debounced only in Material UI package. As a consequence, when implementing a custom theme without the `ra-ui-materialui` package, we also need to add manually a debounce. Otherwise, editing a text input filter would spam API (see tests for a real world scenario).
As I can't see any scenario where we would need to spam API (causing network slowness), let's move it to the core package.

[RFR] Move `setFilters` debounce to core

---

UPGRADE.md
docs/Authorization.md
docs/CreateEdit.md
examples/demo/src/products/index.js
examples/simple/comments.js
examples/simple/posts.js
examples/simple/users.js
examples/simple/validators.js
packages/ra-core/src/form/FormField.js
packages/ra-core/src/form/validate.js
packages/ra-core/src/form/validate.spec.js
packages/ra-language-english/index.js

Allow to customize each validation message and allow message to be a function. 
The later is useful if the user wants to allow lazy initialization of the error message (useful for nested lookups). 
It's a breaking change, because `required` validator should now be used as `required()`, `number` as `number()` and `email` as `email()`. This is inline with all other validators.

[RFR]: Allow custom validation message and allow message to be a function

---

packages/ra-ui-materialui/src/input/SelectInput.js

Closes #1604
Before:
After:
Refs https://github.com/mui-org/material-ui/issues/8778

[RFR] Display SelectInput with a minimum width

---

docs/Actions.md
examples/demo/src/reviews/AcceptButton.js
examples/demo/src/reviews/ApproveButton.js
examples/demo/src/reviews/RejectButton.js
examples/demo/src/reviews/reviewActions.js
examples/demo/src/reviews/reviewSaga.js
packages/ra-core/src/actions/dataActions.js
packages/ra-core/src/sideEffect/error.js
packages/ra-core/src/sideEffect/fetch.js
packages/ra-core/src/sideEffect/notification.js

Action creators can now declare failure side effects alongside success side effects, in the `meta` property:
```js
export const crudDeleteMany = (resource, ids, basePath, refresh = true) => ({
type: CRUD_DELETE_MANY,
payload: { ids },
meta: {
resource,
fetch: DELETE_MANY,
onSuccess: {
notification: {
body: 'ra.notification.deleted',
level: 'info',
messageArgs: {
smart_count: ids.length,
},
},
basePath,
refresh,
unselectAll: true,
},
onFailure: {
notification: {
body: 'ra.notification.http_error',
level: 'warning',
},
refresh: true,
},
},
});
```
This removes the need for custom sagas in many cases.

[RFR] Introduce onFailure meta to handle failure side effects

---

packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectInput.js

The translate option did not check if the optionText is a component. Component clones should not be translated. Added `translate` prop to clone properties.

[RFR]: SelectArrayInput don't translate when optionText is a React Component

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js

[RFR] ReferenceArrayInput label not rendered, because it's initialized with empty string

---

packages/ra-ui-materialui/src/layout/Notification.js

When a saga calls `hideNotification` and the `Notification` component is visible, the `notification.undoable` check fails. This PR ensures notification exists.

[RFR]: Notification can be undefined when hidden through saga

---

packages/ra-core/src/util/DependsOn.spec.js

Test fails because a static date is used in a test

[RFR]: Don't use static date values in test

---

packages/ra-core/src/controller/input/ReferenceInputController.js

ReferenceInputController this.props missing in componentWillMount so it will not fetch the options on mount.

[RFR] ReferenceInputController this.props missing in componentWillMount

---

packages/ra-ui-materialui/src/button/SaveButton.js

The `redirect` is defaulted in `EditController` and should be passed down to `SaveButton`. The `defaultProp` in `SaveButton` overrides this.
```
<Edit>
<SimpleForm redirect={false}>
</SimpleForm>
</Edit>
```
This currently does not work, the redirect still is `list`. (I know I can pass custom `toolbar`).

[RFR]: Default redirect disables passing redirect to SimpleForm

---

examples/simple/src/posts.js
packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.spec.js

Because it would make it unusable in most use cases, and because the documentation is not updated at all.
Reverts #1549
Closes #1690

[RFR] Remove support for children component in SelectArrayInput

---

docs/Translation.md

Added ra-language-slovak translation package for react-admin
and removed aor-language-slovak from previous version list.

Added slovak translations for react-admin

---

src/mui/input/BooleanInput.js

Closes #1667
No need to backport to `next`

[RFR] Fix boolean input label color does not use theme

---

examples/demo/src/fakeServer/rest.js
packages/ra-data-fakerest/src/index.js
packages/ra-ui-materialui/src/list/DatagridBody.js

When used in a form, `<ReferenceManyField>` does not pass a `version` prop to its child. The caching of `<Datagrid>` is optimized for when it receives a `version`... So the `<ReferenceManyField>` does not refresh properly (see #1648).
This change introduces larger, yet less powerful, caching rules for `<DatagridBody>`.
Closes #1648

[RFR] Fix DatagridBody too aggressive cache rules

---

examples/simple/package.json
examples/simple/webpack.config.js
yarn.lock

On my laptop:
- 1st run: 26s (no change)
- 2nd run: 4s
The plugin logs a warning in the console:
> DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
But, as it's already a [known issue](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/299), we can imagine that it will be fixed in a minor release soon.

[RFR] Speed up webpack build in simple example

---

packages/ra-ui-materialui/src/list/FilterButton.js

It does not seem to be used in the `<Button>` component.
Rather, it seems that a similar "paddingLeft" is used by default.
So its existence is deemed unnecessary.
Not sure about it though.

Remove 'label' class

---

docs/Authorization.md

In the documentation, there is no return in the `AUTH_GET_PERMISSIONS` part of the first example.
https://marmelab.com/react-admin/Authorization.html#configuring-the-auth-client

[RFR] Fix typo in Authorization documentation

---

packages/ra-ui-materialui/src/layout/Layout.js

The change introduced by #1721 has a nasty side effect: it breaks the overflow of the main content. We'll need to find another fix for #1689.
Closes #1784

[RFR] Revert #1721

---

docs/List.md
examples/simple/src/posts/PostList.js

Hiding columns on small screens used to be a ng-admin feature. It's easy to replicate using only CSS in react-admin - here is how.

[RFR] Add responsive column to simple example

---

packages/ra-ui-materialui/src/list/Datagrid.js

[RFR] Fix select all checkbox selects rows twice

---

yarn.lock

Just ran `yarn`, which I forgot to do after fa174b343599948ca5683f7aa3729cc6293dfee4

[RFR] Fix yarn.lock to match packages.json

---

packages/ra-core/src/form/validate.js

Refers to #1850. 
If we define validation functions directly in JSX, it will result in a new function at every render, and then trigger infinite re-render, as explained in [documentation](https://marmelab.com/react-admin/CreateEdit.html#validation). This PR memoizes every built-in validator to such an issue.
This way, we would be able to add some validations such as:
```js
<TextInput validate={required()} />
```
Instead of:
```js
const textValidation = required();
<TextInput validate={textValidation} />
```
Note it only affects react-admin validators. If we use some custom validators, we still need to pass via a variable. That's why I didn't update the documentation.

[RFR] Memoize built-in validator to prevent some infinite renders

---

packages/ra-ui-materialui/src/list/Datagrid.js

fix checkbox ripple height in Datagrid

---

packages/ra-data-graphql/src/buildApolloClient.js

I was having a hard time trying to set the Authorization header with ra-data-graphql-simple dataprovider. In buildApolloClient.js in ra-data-graphql the provided cache and link parameters in clientOptions are effectively ignored and setting link causes Apollo to complain about missing cache with "In order to initialize Apollo Client, you must specify link & cache properties on the config object.". This PR fixes the issue for me.
It seems to me like a simple mistake and not intended behavior, since "otherOptions" will never contain link or cache, so finalLink and finalCache will always be initialized to undefined here.

Allow override of link and cache parameter in ra-data-graphql

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.js

**Steps to reproduce:**
Using the following code:
```jsx
<ReferenceArrayInput source="tag_ids" reference="tags">
<CheckboxGroupInput optionText="name" />
</ReferenceArrayInput>
```

[RFR] Remove warnings when using CheckboxGroupInput into ReferenceArrayInput

---

packages/ra-ui-materialui/src/input/SelectArrayInput.js

**Steps to reproduce**
- use `SelectArrayInput` with props `optionText` containing a function or a React element
- select one element: `Chip` will be empty
I don't know how to test this fix.

[RFR] Fix SelectArrayInput Chip label should render same as selected menu item option

---

e2e/pages/EditPage.js
e2e/tests/permissions.js
packages/ra-ui-materialui/src/form/FormTab.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js
packages/ra-ui-materialui/src/input/ArrayInput.spec.js

Closes #1866
Cons: the whole form is rerendered on state change, and not only the active tab, so this will slow down Edition and Creation forms a bit... Nothing noticeable during my tests, though.

[RFR] Fix global validation on TabbedForm

---

docs/Admin.md
docs/CustomApp.md
docs/Reference.md
docs/Theming.md
docs/_layouts/default.html
packages/ra-core/src/CoreAdmin.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/react-admin/src/Admin.js

Also, deprecating the ability to customize the menu from the `<Admin>` component, as it makes more sense to use a custom Layout instead.
Your custom layout can simply extend the default `<Layout>` component if you only want to override the appBar, the menu, or the notification component. For instance:
```jsx
// in src/MyLayout.js
import { Layout } from 'react-admin';
import MyAppBar from './MyAppBar';
import MyMenu from './MyMenu';
import MyNotification from './MyNotification';
const MyLayout = (props) => <Layout 
{...props}
appBar={MyAppBar}
menu={MyMenu}
notification={MyNotification}
/>;
export default MyLayout;
```

[RFR] Add ability to customize Layout components (menu, appbar, notification)

---

packages/ra-core/src/sideEffect/accumulate.js

When you use GraphQl, id as Int and ReferenceField in DataGrid you get error:
* Object.keys changes type of id to string 
* Object.values don't change type
* Uniqueness not affected

[RFR] Fix changing id type in accumulate

---

docs/DataProviders.md

`react-admin/` was missing in multiple links in the Data Providers doc page. This pull request fixes those broken links.

Fix multiple broken links in DataProviders doc

---

docs/Fields.md
docs/List.md
packages/ra-core/src/controller/field/ReferenceArrayFieldController.js
packages/ra-core/src/controller/field/ReferenceFieldController.js
packages/ra-core/src/controller/field/ReferenceManyFieldController.js
packages/ra-ui-materialui/src/field/ArrayField.js
packages/ra-ui-materialui/src/field/BooleanField.js
packages/ra-ui-materialui/src/field/ChipField.js
packages/ra-ui-materialui/src/field/DateField.js
packages/ra-ui-materialui/src/field/EmailField.js
packages/ra-ui-materialui/src/field/FileField.js
packages/ra-ui-materialui/src/field/FunctionField.js
packages/ra-ui-materialui/src/field/ImageField.js
packages/ra-ui-materialui/src/field/NumberField.js
packages/ra-ui-materialui/src/field/ReferenceArrayField.js
packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/field/ReferenceManyField.js
packages/ra-ui-materialui/src/field/RichTextField.js
packages/ra-ui-materialui/src/field/SelectField.js
packages/ra-ui-materialui/src/field/TextField.js
packages/ra-ui-materialui/src/field/UrlField.js
packages/ra-ui-materialui/src/field/sanitizeRestProps.js
packages/ra-ui-materialui/src/list/DatagridHeaderCell.js

Reopen of https://github.com/marmelab/react-admin/pull/1746
:rocket: Add optional sortBy to ReferenceField to sort by other than source of reference
I could think of two ways to solve issue #1361:
- Add an optional field to ReferenceField that is used to generate the link in case it is present and let it always sort by `source`.
- Add an optional field to ReferenceField that is used to sort by in case it is present and let the link always be generated by `source`.
I opted for the second option here but implementing the first is also possible. Please let me know what you think and if you have any preferences with regards to the API of this project.

Add optional sortBy to ReferenceField

---

examples/demo/src/products/GridList.js

As we were really not using the `<EditButton>` as it was intended to be used, I switched to a custom link. It has the benefit of illustrating how to create a link without the react-admin buttons.
Closes #1945

[RFR] [Demo] Fix edit icon in product gridlist on smaller screens

---

examples/demo/src/categories/LinkToRelatedProducts.js

Closes #1951 
Note that there is still a bug somehow: the page should work without sort.

[RFR] [Demo] Fix warning in Link to filtered list

---

packages/ra-ui-materialui/src/form/TabbedForm.js

The problem occurs when using `<LontTextInput>` inside a `<TabbedForm>`, but not if it's used in the first tab... The bug is due to a conjunction of:
- material-ui, which computes the field height based on the `scrollHeight` value of a dummy textarea,
- the way we hide inactive tabs with `display=none`, which makes all `scrollHeight` computation return 0
- the fact that we decorate fields with redux-form's `<FormField>`, which decorates the field with `connect()` and therefore makes them pure, and prevents a rerender when the tab becomes active.
I must confess the bug wasn't easy to locate, but the fix is a one liner. 
Closes #1956

[RFR] Fix LongTextInput when used inside a TabbedForm

---

cypress/integration/tabs-with-routing.js
cypress/support/EditPage.js
cypress/support/ShowPage.js
examples/demo/src/visitors/ShowPage.js
examples/simple/src/users/UserEdit.js
examples/simple/src/users/UserShow.js
packages/ra-core/src/Resource.js
packages/ra-ui-materialui/src/detail/Tab.js
packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/form/FormTab.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js

This PR adds support for routing driven tab selection both in `TabbedForm` and `TabbedShowLayout`.

[RFR] Support routing in TabbedForm & TabbedShowLayout

---

docs/CreateEdit.md
docs/_layouts/default.html
examples/simple/src/comments/CommentCreate.js
examples/simple/src/posts/PostShow.js

I think the `<CreateController>` should support `location.state` by default... But that would be a new feature, to be added to the `next` branch, while this PR documents the `master` branch.
Edit: well, implementing `location.state` support is a must have to enable #1892, so I guess I'll implement it (in another PR).
Closes #1930

[RFR] Document how to prefill a create form based on another record

---

packages/ra-core/src/form/validate.js
packages/ra-core/src/form/validate.spec.js

fixes #1989 
Add `.prettierrc` with the settings take from `.eslintrc` makes vscode (and all the other related tools?) more happy

Fix validators memoization

---

docs/Actions.md
examples/simple/src/comments/PostQuickCreate.js
packages/ra-core/src/sideEffect/admin.js
packages/ra-core/src/sideEffect/callback.js
packages/ra-core/src/sideEffect/index.js

For newcomers, Redux makes it particularly hard to trigger a custom function *after* a fetch action has succeeded. 
1. Support `.then()` on async actions (requires a custom middleware / hack)
2. Add a new `callback` side effect
The second solution makes the action not entirely serializable, which may interfere with debug tools. But it really make things easier.
```diff
handleSave = values => {
-        const { fetchStart, fetchEnd, onSave } = this.props;
-
-        fetchStart();
-        dataProvider(CREATE, 'posts', { data: values })
-            .then(({ data }) => {
-                onSave(data);
-            })
-            .catch(error => {
-                this.setState({ error });
-            })
-            .finally(() => {
-                fetchEnd();
-            });
+ …
```

[RFR] Introduce the callback side effect

---

examples/demo/src/categories/LinkToRelatedProducts.js
examples/demo/src/products/GridList.js
examples/demo/src/reviews/AcceptButton.js
examples/demo/src/reviews/RejectButton.js
examples/demo/src/segments/LinkToRelatedCustomers.js
examples/graphcool-demo/src/categories/LinkToRelatedProducts.js
examples/graphcool-demo/src/reviews/AcceptButton.js
examples/graphcool-demo/src/reviews/RejectButton.js
examples/graphcool-demo/src/segments/LinkToRelatedCustomers.js
examples/simple/src/posts/PostShow.js
packages/ra-ui-materialui/src/Link.js
packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/button/CloneButton.js
packages/ra-ui-materialui/src/button/CreateButton.js
packages/ra-ui-materialui/src/button/EditButton.js
packages/ra-ui-materialui/src/button/ListButton.js
packages/ra-ui-materialui/src/button/ShowButton.js
packages/ra-ui-materialui/src/layout/CardActions.js
packages/ra-ui-materialui/src/list/ListActions.js

The small version of action buttons shows not only on mobile, but also on desktop, on smaller screens. In these devices, we can use the "hover" behavior to add a tooltip and make the UI clearer.
I was exploring this approach after adding the `ExportButton`, because there are more and more cases when, on desktop, the action button breaks into 2 or 3 lines. We may have to consider using the small version all the time if we week adding buttons.

[RFR] Add Tooltips To Icon Buttons

---

cypress/integration/create.js
cypress/support/CreatePage.js
docs/Actions.md
docs/CreateEdit.md
docs/_layouts/default.html
examples/simple/src/i18n/en.js
examples/simple/src/posts/PostCreate.js
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/Toolbar.js
packages/ra-ui-materialui/src/input/BooleanInput.js

> No breaking changes, `handleSubmitWithRedirect` is still passed
Having a custom save button which alter the values before actually saving them (see the `Save as Commentable` button in the `PostCreate` component of the `simple` example)
It's currently not possible to alter the form values before dispatching the save action:
- Dispatching a `redux-form` `change` action is asynchronous so we can't submit directly after changing the value
- Custom saga doesn't work either as it is not possible to dispatch a `redux-form` `submit` action because we don't have an `onSubmit` on our forms
Passing the `redux-form` `handleSubmit` function to the buttons allows the user to do whatever he wants and still benefits from the default validation mechanisms

[RFR] Pass handleSubmit directly to buttons

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js
packages/ra-ui-materialui/src/input/ArrayInput.js

Imagine that `resource` is `posts`, `record` is `{ id: 123, comments: [{ id: 456, body: 'foobar' }] }`.
`<ArrayInput source="comments">` properly injects the `record` and `source` to `<SimpleFormIterator>`. But `<SimpleFormIterator>` injects this record (`{ id: 123, comments: [{ id: 456, body: 'foobar' }] }`) directly to its children, while in fact they're only interested in the sub records (`{ id: 456, body: 'foobar' }`).
This PR fixes that.
Closes #1835

[RFR] Fix record value in SimpleFormIterator children

---

examples/demo/src/products/GridList.js
packages/ra-ui-materialui/src/field/ReferenceField.js

ReferenceField links have lost their color since #2033

[RFR] Fix link color in ReferenceField

---

Makefile

I received an error message that the 'docs' directory already exists in packages, when updating the project with a new make (i.e. the folders were already there).

Fix the 'directory already exists' issue when re-making the project

---

examples/simple/src/comments/CommentEdit.js

This is necessary to test a recent regression in form initialization

[RFR] Add link to related post from Comment edit view

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Reverts marmelab/react-admin#2037, which caused errors when navigating betweens forms

Revert "[RFR] Fix form keep values after navigation"

---

cypress/cypress.json
cypress/integration/create.js
cypress/plugins/index.js
cypress/start.js
examples/simple/src/posts/PostCreate.js
packages/ra-core/src/form/FormField.js
packages/ra-core/src/form/FormField.spec.js
packages/ra-core/src/form/index.js
packages/ra-core/src/form/withDefaultValue.js
packages/ra-core/src/form/withDefaultValue.spec.js
packages/ra-ui-materialui/src/form/SimpleFormIterator.js
packages/ra-ui-materialui/src/input/ArrayInput.js
packages/ra-ui-materialui/src/input/ArrayInput.spec.js

[RFR] Fix ArrayInput defaultValue

---

packages/ra-core/src/CoreAdmin.js
packages/ra-core/src/form/formMiddleware.js

Related to this redux-form bug: https://github.com/erikras/redux-form/issues/3435#issuecomment-359371803

[RFR] ensure redux-form does not destroy forms after they are remounted

---

packages/ra-ui-materialui/src/detail/SimpleShowLayout.js
packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/Toolbar.js

In form and show layouts, the title, content and buttons weren't properly aligned because we didn't use the material design recommended margins for content. This PR fixes that.
Before:
After:

[RFR] Use material design recommended margin for content

---

packages/ra-input-rich-text/src/index.js

When a `RichTextInput` is below the fold, Quill autofocuses it and it makes the page scroll to it.
This fix prevents Quill from autofocusing.
See zenoamaro/react-quill#317 for details.

[RFR] Fix Quill autofocus

---

docs/Inputs.md

Another option would be to get the DropZone supported props from the props transparently (using DropZone.propTypes).
Fix #2083

[RFR] Fix FileInput documentation

---

docs/Tutorial.md

Prop types have become an external dependency so we should instruct a first-time user to install this externally using yarn. This change does just that adding two lines in order to complete this need.

Tutorial.md adding prop-types package external dependency

---

docs/CustomApp.md
packages/ra-core/src/CoreAdmin.js
packages/ra-core/src/createAdminStore.js
packages/ra-core/src/form/index.js
packages/ra-core/src/index.js

Despite offering the ability to pass `customReducers` and `customSagas`, users always ask for more customization of the Redux store. Some want to add custom middlewares, enhancers, or override the react-admin reducers... The best example is probably adding local persistance for the state through the redux-persist middleware.
This PR allows the `<Admin>` to be used inside an external `<Provider>`, which skips the creation of the store completely. 
```jsx
<Provider
store={createAdminStore({
authProvider,
dataProvider,
i18nProvider,
history,
})}
>
<Admin
authProvider={authProvider}
history={history}
title="My Admin"
>
<Resource name="posts" list={PostList} create={PostCreate} edit={PostEdit} show={PostShow} />
<Resource name="comments" list={CommentList} …
```

[RFR] Allow to use <Admin> inside an external <Provider>

---

cypress/support/ListPage.js
docs/Theming.md
examples/demo/src/AppBar.js
examples/demo/src/Layout.js
examples/demo/src/Menu.js
packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/auth/Logout.js
packages/ra-ui-materialui/src/button/RefreshIconButton.js
packages/ra-ui-materialui/src/button/index.js
packages/ra-ui-materialui/src/detail/EditActions.js
packages/ra-ui-materialui/src/detail/ShowActions.js
packages/ra-ui-materialui/src/layout/AppBar.js
packages/ra-ui-materialui/src/layout/AppBarMobile.js
packages/ra-ui-materialui/src/layout/LoadingIndicator.js
packages/ra-ui-materialui/src/layout/UserMenu.js
packages/ra-ui-materialui/src/layout/index.js
packages/ra-ui-materialui/src/list/ListActions.js

The `RefreshButton` has a global action (it increases the app's `version`, used everywhere as `key` prop, and therefore forcing a reload) but it's positioned in the content, not in the shell. We should remove it from the content. That would free up space for content (especially in the List view, where there are too many buttons already).
Move the RefreshButton to the AppBar.
But then the AppBar is too crowded, so we use the IconButton version instead of the Text+icon version (using tooltip and aria-label to make it still readable), and we place it over the loading indicator to take less space. But then the refresh button is dangerously close to the logout button so we put the logout button inside a User menu, and by the way why not allow users to add their own menu items there?
There, …

[RFR] Move Refresh to AppBar, Introduce UserMenu

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

The suggestions simply don't appear anymore on my machine... There must be something more to do. In the meantime, I revert.
Reverts marmelab/react-admin#2123

Revert "[RFR] Fix Autocomplete list is cut off by content area"

---

docs/CreateEdit.md

Fix the link to "Altering the Form Values before Submitting is dead" (on Actions page)

[RFR] Link to : Altering the Form Values before Submitting is dead

---

packages/ra-ui-materialui/src/list/DatagridHeaderCell.js

Material-ui table sort labels reserve space for the sort icon even when the column isn't the active sort. This prevents layout changes when clicking on a column for sorting, but this also uses horizontal space. I think the icon should be hidden rather than of 0% opacity (ref https://github.com/mui-org/material-ui/issues/12561).
The effect only appears on columns with a low width content (like `NumberField`), where the header is usually larger than the content, and on tables with many columns.
Before|After
----|-----

[RFR] Hide the datagrid sort icons when not active

---

cypress/support/ListPage.js
docs/List.md
packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/list/Pagination.js
packages/ra-ui-materialui/src/list/Pagination.spec.js
packages/ra-ui-materialui/src/list/PaginationActions.js
packages/ra-ui-materialui/src/list/PaginationActions.spec.js
packages/ra-ui-materialui/src/list/PaginationLimit.js

Note that this slightly changes the design of the pagination, to make it more material-design compliant.
Before:
After:

[RFR] [Pagination] Add the ability to set the number of rows per page

---

packages/ra-data-graphql-simple/README.md

Hi!
"client" is not used in example, so const client = new ApolloClient() can be removed

Remove const client = new ApolloClient();

---

packages/ra-data-fakerest/README.md

The current install snippet for the `ra-data-fakerest` package is wrong.
This corrects the misnaming.

Corrects package name in readme

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

The fix introduced by #2123 has been reverted by #2159. This PR apply the fix again, correctly setting the z-index this time.
Fixes #2097
Before:
After:

[RFR] Fix Autocomplete list is cut off by content area

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js

An error was  thrown when using ReferenceInput insite ArrayInput. 
When adding new records, prop "record" was indefined. This change initiaizes new record to an empty object.

Fixes error when using ReferenceInput in SimpleFormIterator

---

cypress/integration/list.js
cypress/support/ListPage.js
docs/Theming.md
docs/_layouts/default.html
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/layout/AppBar.js
packages/ra-ui-materialui/src/layout/Headroom.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/Sidebar.js
packages/ra-ui-materialui/src/layout/index.js
yarn.lock

We have some issue on AppBar component like #1819. 
In fact, we don't follow [ the material design guidelines](https://material.io/design/components/app-bars-top.html#behavior), which specify that the scrollbar should hide on scroll down, and show up (fixed) on scroll up (see https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar/standard for an example).
A discussion on the same subject in the [material-ui tracker: mui-org/material-ui#12337](https://github.com/mui-org/material-ui/issues/12337).
I implement [react-headroom](https://github.com/KyleAMathews/react-headroom) container in AppBar component. I export `<Headroom />` component which is already configure for react-admin.
fix #1819

[RFR] Implement Headroom in AppBar

---

packages/ra-language-french/README.md

This should be how texans people write "french".

[RFR] Fix typo on ra-language-french

---

examples/simple/src/comments/CommentList.js
packages/ra-ui-materialui/src/field/ReferenceField.js

The `className` specified on the child of a `ReferenceField` used to be overridden, which prevented a custom style.
```jsx
<ReferenceField source="post_id" reference="posts">
<TextField source="title" className={classes.title} />
</ReferenceField>
```

[RFR] Fix ReferenceField does not respect its child's className

---

docs/Translation.md

As translators added their packages to the new list, they forgot to remove them from the old list... this PR fixes that.

[RFR] Remove obsolete translation packages

---

examples/demo/src/Login.js
packages/ra-ui-materialui/src/auth/Login.js

[RFR] Use Lock instead of LockOutline icon to be compatible with material-ui v1 and v3

---

docs/Theming.md
examples/demo/src/Layout.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/layout/Menu.js
packages/ra-ui-materialui/src/layout/Sidebar.js

Until now, changing the sidebar width (to accommodate shorter or longer resource names) used to require a lot of boilerplate. No more!
```jsx
const MyLayout = props => <Layout {...props} sidebarWidth={200} />;
```

[RFR] Allow changing the sidebar width using a Layout prop

---

packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/layout/Layout.js

Fixes #2094
As decided with the core team, we won't try to do anything special regarding horizontal scroll. We display everything and the horizontal scroll-bar of the window will be displayed normally.

[RFR] Fix TabbedLayout, TabbedForm and List display regarding scroll

---

packages/ra-core/src/form/FormDataConsumer.js
packages/ra-core/src/form/FormDataConsumer.spec.js

It should only be displayed when the `FormDataConsumer` is used inside an `ArrayInput`.
Also do not pass `ArrayInput` related props if not needed

[RFR] Fix wrong warning on FormDataConsumer

---

packages/ra-input-rich-text/src/index.js

pass fullWidth in RichTextInput to FormControl be able to make the wysiwyg full width
port of #2247 from `master` to `next`

[RFR] RichTextInput - allow fullWidth

---

examples/graphcool-demo/src/commands/Basket.js
examples/graphcool-demo/src/dataProvider.js
packages/ra-data-graphcool/README.md
packages/ra-data-graphcool/src/index.js
packages/ra-data-graphql-simple/README.md
packages/ra-data-graphql-simple/src/index.js
packages/ra-data-graphql/README.md
packages/ra-data-graphql/src/index.js
packages/ra-data-graphql/src/introspection.js

[RFR] GraphQL providers enhancements

---

.babelrc
.gitignore
Makefile
examples/data-generator/package.json
examples/simple/webpack.config.js
package.json
packages/ra-core/package.json
packages/ra-data-fakerest/package.json
packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql/package.json
packages/ra-data-json-server/package.json
packages/ra-data-simple-rest/package.json
packages/ra-input-rich-text/package.json
packages/ra-realtime/package.json
packages/ra-tree-core/package.json
packages/ra-tree-ui-materialui/package.json
packages/ra-ui-materialui/package.json
packages/react-admin/package.json

Fixes #2204 
As explained in #2204, the goal of this PR is to expose ES modules from the `react-admin` packages in order to enable the usage of Tree Shaking by webpack.
To do so, I take the following measures:
- The assets are now transpiled twice, once in `lib/` for **CommonJS** and once in `esm/` for **ES Modules** (thanks to the `BABEL_ENV` variable and the config in `.babelrc`)
- In all `package.json`, the `esm` folder is now included to the NPM package
- In all `package.json`, a new key `module` tells to consumers that ES modules are available at `esm/index.js`
- In all `package.json` again, the `sideEffects` is set to `false` telling that nothing is done at the import phase (useful to webpack for tree shaking)
<details>
<summary>Tested codebase and configurations</summary>
- Default …

[RFR] Expose ES modules in order to enable tree shaking

---

packages/ra-ui-materialui/src/button/SaveButton.js

Fix SaveButton misaligned CircularProgress on saving (because of the icon's paddingRight)
before:
after fix:

[RFR] Fix SaveButton misaligned CircularProgress

---

packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/package.json
yarn.lock

It's a temporary fix until the following PR is published on `graphql-ast-types` https://github.com/imranolas/graphql-ast-types/pull/8

Temporary fix graphql-ast-types package

---

packages/ra-ui-materialui/src/list/Pagination.js
packages/ra-ui-materialui/src/list/Pagination.spec.js

Somehow `rowsPerPageOptions` was lost and does not work anymore. 
The PR fixes the issue.

fixes rowsPerPageOptions

---

docs/DataProviders.md

As you can see in [this SO question](https://stackoverflow.com/questions/52247855/react-admin-edit-form-not-prefilled-with-existing-attributes/52253320), the AOR Data Providers are no longer supported by the React Admin core but are still documented.
Another solution would be to mark them as deprecated. As you want!

[RFR] Remove AOR Data Providers From The Doc

---

docs/CreateEdit.md
docs/List.md
docs/Show.md
examples/simple/src/users/Aside.js
examples/simple/src/users/UserCreate.js
examples/simple/src/users/UserEdit.js
examples/simple/src/users/UserList.js
examples/simple/src/users/UserShow.js
packages/ra-core/src/util/TestContext.js
packages/ra-core/src/util/index.js
packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/Create.spec.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/detail/Edit.spec.js
packages/ra-ui-materialui/src/detail/Show.js
packages/ra-ui-materialui/src/detail/Show.spec.js
packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/List.spec.js
test-setup.js

Users may need to see info related to the current content, but secondary. Using tabs for that has one drawback: it is contained in the form, and the presence of the "save" button  makes the content not secondary.
Besides, adding a second column requires overriding the View, which is advanced customization. 
The `aside` prop is style agnostic, and allows for all sorts of customizations thanks to flexbox.
```jsx
const Aside = () => (
<div style={{ width: 200, margin: '1em' }}>
<Typography variant="title">App Users</Typography>
<Typography variant="body1">
Eiusmod adipisicing tempor duis qui. Ullamco aliqua tempor incididunt aliquip aliquip qui ad minim aliqua. Aute et magna quis pariatur irure sunt. Aliquip velit consequat dolore ullamco laborum voluptate cupidatat. Proident minim …
```

[RFR] Add aside support in List, Edit, and Show views

---

packages/ra-core/package.json
packages/ra-core/src/auth/WithPermissions.js
packages/ra-core/src/form/FormDataConsumer.js
packages/ra-core/src/i18n/translate.js
packages/ra-core/src/util/index.js
packages/ra-core/src/util/warning.js
packages/ra-ui-materialui/src/layout/Title.js
yarn.lock

[RFR] Add warnings to translate HOC when used directly to translate a string

---

packages/ra-data-json-server/README.md
packages/ra-data-simple-rest/README.md

[RFR] ·Add documentation on the data returned from create requests 

---

docs/FAQ.md

I struggled for hours with this and by chance found the issue talking about it but the next person might not have the same luck I did thus I think documenting the possible bug is important.

Add a section about production build ui bug in docs

---

packages/ra-input-rich-text/src/index.js
packages/ra-ui-materialui/src/input/CheckboxGroupInput.js
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.js

Add's error prop to FormHelperText, to mark it as error on error meta
Makes the error text red (well, the error color defined by theme) like other errors in TextInput's
changes RichTextInput, RadioButtonGroupInput, CheckboxGroupInput and SelectArrayInput
note: added as pull to master instead of next as i consider it a bug that these components have inconsistent way to display error with other input's
**edit: maybe i should add some borderBottom to make it even more consistent?
edit2: added images**
before:
after (in this PR):
with borderBottom (not in this PR, shpuld i add it?):

[RFR] Add error prop to FormHelperText, to mark it as error on error meta

---

docs/Inputs.md
docs/_layouts/default.html
packages/ra-core/src/form/addField.js
packages/ra-ui-materialui/src/input/DateTimeInput.js
packages/ra-ui-materialui/src/input/index.js

~~Due to the way `<input type="datetime-local" /> works on Chrome, I had to store a local draft state and couldn't resort to redux-form's `parse` and `format` (see commit list).~~~
I managed to make it a stateless component thanks to redux-form's `parse` and `format`.

[RFR] Add <DateTimeInput>

---

docs/List.md
examples/simple/src/users/UserList.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/DatagridRow.js

Some users require datagrids with many columns. The Edit or Show button takes a significant share of the horizontal space. As an alternative to adding an `<EditButton>`, developers can now enable the `rowClick` option on the `<Datagrid>` component:
```jsx
const UserList = props => (
<Datagrid rowClick="show">
<TextField source="id" />
<TextField source="role" />
</Datagrid>
</List>
);
```

[RFR] Introduce Datagrid rowClick

---

docs/CreateEdit.md
packages/ra-ui-materialui/src/form/Toolbar.js

Removing the delete button from the Edit toolbar used to require to create a Toolbar component from scratch. 
Refs #2319
With this PR, it's as easy as passing just the `<SaveButton>` as only child of a custom `<Toolbar>`:
```jsx
const PostEditToolbar = props => (
<Toolbar {...props} >
<SaveButton />
</Toolbar>
);
export const PostEdit = (props) => (
<Edit {...props}>
<SimpleForm toolbar={<PostEditToolbar />}>
...
</SimpleForm>
</Edit>
```
There is a slight BC break here: people with custom Toolbar for Edit views used to have the Delete button displayed even though it wasn't in their custom toolbar. With that change, the Edit button will disappear. I think, with proper warning in the release notes, we can assume this BC break (on a feature that is very young and probably not very widely …

[RFR] [BC break] Easier custom toolbar

---

packages/ra-data-graphql-simple/README.md

Update the documented return type of the example `deletePost` mutation
to match what `ra-core` expects.
Fixes #2338

Fix example simple GraphQL schema for delete

---

packages/ra-ui-materialui/package.json
yarn.lock

I fixed the bug in the react-headroom dependency in https://github.com/KyleAMathews/react-headroom/pull/151
Closes #2337

[RFR] Fix AppBar sometimes doesn't appear when scrolling up

---

packages/ra-ui-materialui/src/button/ExportButton.js

Filter nullable fields in `fetchRelatedRecords` before building the array of uniq ids.
https://github.com/marmelab/react-admin/issues/2353

[RFR] Filter nullable fields in fetchRelatedRecords

---

packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/button/CreateButton.js
packages/ra-ui-materialui/src/form/FormInput.js
packages/ra-ui-materialui/src/input/BooleanInput.js
packages/ra-ui-materialui/src/input/CheckboxGroupInput.js
packages/ra-ui-materialui/src/input/FileInput.js
packages/ra-ui-materialui/src/input/Labeled.js
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js

This allows material-ui to bind labels to their inputs using the `for` attribute, simplifying e2e tests with libraries such as `react-test-utils` and providing better accessibility.
For example, using [`cypress-testing-library`](https://github.com/kentcdodds/cypress-testing-library) in `cypress`, with an input written as:
```jsx
<TextInput source="first_name" />
```
We can now write tests like:
```js
cy.getByLabelText('First Name').type('Gildas');
```
Before, for the same result, we would have written the input as:
```jsx
<TextInput id="first_name" source="first_name" />
```
*NOTE*: it is still possible to provide override the default `id` inferred from the `source` prop

[RFR] Automatically add id attribute on input if not specified and accessibility fixes

---

packages/ra-ui-materialui/src/list/Pagination.js
packages/ra-ui-materialui/src/list/Pagination.spec.js
packages/ra-ui-materialui/src/list/PaginationLimit.js

We don't display the "out of boundaries" message anymore. Instead, we get back to page 1 (when page < 1) or to the last page (when page > last Page) without showing any notice.
The first check is done in our `Pagination`'s `componentDidUpdate`, the second check is done in material-ui's `<TablePagination>`.
The `ra.navigation.page_out_of_boundaries` message is still required by `Pagination.handlePageChange`, so I didn't remove it from translation files.
Closes #2350

[RFR] Fix out of boundaries pagination does not allow pagination

---

packages/ra-core/src/controller/CreateController.js
packages/ra-core/src/controller/CreateController.spec.js

The current behavior ([default](https://github.com/sindresorhus/query-string#arrayformat) of `query-string`) prevent passing an array with a single value as it will be considered as a field of the value's type instead of an array of that type.
This prevents passing array of references containing a single reference.

[RFR] Correctly parse array values from query-string in Create

---

docs/DataProviders.md

Hey!
First of all: Awesome project.
I needed a data provider for my JSONAPI backend and first tried this client:
[moonlight-labs/aor-jsonapi-client](https://github.com/moonlight-labs/aor-jsonapi-client)
Unfortunately this project is deprecated and does not seem to be maintained anymore.
It was already marked as deprecated with this pull request a couple of days ago:
https://github.com/marmelab/react-admin/pull/2300
So I've written my own:
[henvo/ra-jsonapi-client](https://github.com/henvo/ra-jsonapi-client)
The client is now in a reasonably stable state and I would like to submit this to the third-party data providers.
Let me know what you think and have a great day.

Add ra-jsonapi-client to third-party Data Providers

---

docs/Actions.md
docs/Authentication.md
docs/Authorization.md
docs/CreateEdit.md
docs/DataProviders.md
docs/Inputs.md
docs/List.md
examples/README.md

Address a few spelling errors found in throught project documentation.

Fix Documentation Spelling & Grammar Errors

---

packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/button/RefreshIconButton.js
packages/ra-ui-materialui/src/layout/UserMenu.js

| react-admin version |
| ------------------- |
| 2.3.3 |
This PR fixes three small typos for the `aria-label` attributes in `IconButton`s.

Fixed typo for aria attribute

---

packages/ra-ui-materialui/src/button/Button.js

If you provide no label to Button, then on mobile mode there is empty tooltip visible
and on desktop mode the icon is not center due to empty span with padding
this PR fixes that
btw. no idea if this should go to next or master, so made it for next first

[RFR] Button - don't display empty label and center icon if no label

---

packages/ra-data-graphql/src/introspection.js

Fixes #2397 
Not very trivial to test with jest, as it's a browser-only issue. The change mimics the behaviour already already in place for regular graphql queries (See issue).

Use 'network-only' apollo option for graphql introspection.

---

docs/Theming.md
packages/ra-ui-materialui/src/layout/UserMenu.js

The idea is to let the user choosing the Icon but also the Component without rewriting the whole UserMenu.
**Changing UserMenu icon**
**Changing UserMenu component**

[RFR] Custom User Menu icon

---

packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js

Closes #2395
Incidentally, this bug teaught me that material-ui now handles the required label at the `FormControl` level. We'll have to use that in the future.

[RFR] Fix double asterix on required RadioButtonGroupInput

---

packages/ra-input-rich-text/src/index.js

Error property expects a boolean but receives a string.
Changed to a null and undefined check.

Fix Validation issues on RichTextInput [2371]

---

docs/List.md

Updated "posts.map" to "records.map" as this appears produce the intended result.

Fix typo in exporter example

---

README.md
docs/index.md

Because we publish a lot of articles about react-admin, but people aren't aware of them

[RFR] Add link to news in Readme and documentation

---

packages/ra-core/src/controller/ListController.js

I made the mistake of using `<List filter={<PostFilters />} />` (notice the missing s) and the error message was not explicit enough. I think we can help the developer a bit more in that case.

[RFR] Throw an explicit error if the developer used the wrong prop name for filters

---

packages/ra-data-graphql/src/introspection.js
packages/ra-data-graphql/src/introspection.test.js

Checking for queryType and mutationType instead opens up the possibility for data providers to make use of GraphQL endpoints where the type name for query and mutation types are not 'Query' and 'Mutation'.

Update introspection type check with queryType and mutationType

---

packages/ra-ui-materialui/src/Link.js
packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/list/SingleFieldList.js

[RFR] Fix ReferenceField in Datagrids using rowClick

---

docs/Ecosystem.md
docs/_layouts/default.html

This is a follow up PR for https://github.com/marmelab/react-admin/pull/2386 where we switched the data provider for JSONAPI and forgot to change this also in the 'Ecosystem' chapter.
Also a small typo fix.

Switch jsonapi data provider in ecosystem chapter

---

packages/ra-ui-materialui/src/button/ExportButton.js
packages/ra-ui-materialui/src/button/ExportButton.spec.js

[RFR] Add support for arrays of references in fetchRelatedRecords

---

packages/ra-ui-materialui/src/layout/CardContentInner.js

making bottom padding for last child to be 70px for xs media size
Fix #2463

Fix Edit toolbar hides the last form item on mobile

---

docs/CreateEdit.md
docs/List.md
docs/Show.md

Double brackets (`{{`) declare an instruction in Liquid. We must use `{% raw %}` around code snippets using them, or the conent isn't rendered in the gh-pages docs.

[RFR] Fix missing styles in rendered documentation

---

docs/Ecosystem.md

Even though the graphcool link was with the correct name, the link was wrong.

fix: link for graphcool data provider on docs

---

packages/ra-ui-materialui/src/layout/Notification.js

Allow to override SnackBar style in Notification Component

---

packages/ra-data-graphcool/package.json
packages/ra-data-graphcool/src/buildGqlQuery.js
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql-simple/src/buildGqlQuery.js
yarn.lock

Fixes #2398
In order to let the offline users (or those who use a mirror of NPM's registry) install react-admin, I just published a clone of `graphql-ast-types` that is transpiled for browsers.
I'll remove this package as soon as https://github.com/imranolas/graphql-ast-types/issues/7 is fixed.

[RFR] Temporarily use graphql-ast-types-browser instead of graphql-ast-types

---

packages/ra-core/src/controller/field/ReferenceManyFieldController.js
packages/ra-core/src/reducer/admin/references/oneToMany.js
packages/ra-ui-materialui/src/field/ReferenceManyField.js
packages/ra-ui-materialui/src/list/SimpleList.js

Since we refactored the `List` component, its children expect a `total` prop to be passed to them. But the same children can also be used as children of the `<ReferenceManyField>` component, which didn't pass the `total` prop. this caused a regression in 2.4.0.
This PR lets the `<ReferenceManyField>` grab the `total` of the references from the store, and pass it to its children - so it solves the issue when `<ReferenceManyField>` is used with `<SimpleList>` as child.
Closes #2462 
Supersedes #2467

[RFR] Pass total to ReferenceManyField

---

docs/CustomApp.md

[RFR] Fix non-Admin snippet in custom app documentation

---

docs/CreateEdit.md
docs/Show.md

[RFR] Fix Aside doc for undefined record

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

This PR allows for the creator of an `<AutocompleteInput />` to pass in an optional `shouldRenderSuggestions` function. This function is supported by `react-autosuggest` and is documented here: https://github.com/moroshko/react-autosuggest#should-render-suggestions-prop
ex: `<AutocompleteInput shouldRenderSuggestions={(val) => { return val.trim() > 2 }} />` would not render any suggestions until the 3rd character was entered.

Should render suggestions

---

packages/ra-ui-materialui/src/list/Datagrid.js

This fixes the issue I described in #2506. It didn't look like there are any automated tests around this so I checked it in the app built by `make run-simple`. Let me know if there is anything else I can help with around this issue.

Fix Datagrid header cell padding

---

docs/Tutorial.md

So basically I found and fixed a typo in **Adding Creation and Editing Capabilities** section.

Fix typo in tutorial

---

packages/ra-ui-materialui/src/list/PaginationActions.js

_See #2399 for context._
The import
```
import TablePaginationActions from '@material-ui/core/TablePaginationActions';
```
does not work anymore in material-ui’s more recent versions, as per
https://github.com/mui-org/material-ui/pull/13524.
This commit makes transitioning from `material-ui@1.4.1` to `material-ui@3.5.1` easier.

[#2399] chore: hardcode TablePaginationAction proptypes

---

docs/CustomApp.md
packages/ra-core/src/reducer/index.js
packages/ra-core/src/sideEffect/auth.js
packages/ra-ui-materialui/src/layout/Menu.js

This change enables react-admin to be included in an app that uses connected-react-router

[RFR] Change routing state key from routing to router

---

docs/Inputs.md
examples/demo/src/commands/CommandEdit.js
packages/ra-ui-materialui/src/input/SelectInput.js
packages/ra-ui-materialui/src/input/SelectInput.spec.js

Add disabled option in SelectInput

---

packages/ra-core/src/controller/ListController.js

The `has*` props aren't really required anyway, because the `ListController` treats an empty value as falsy. And since all the other controllers consider these props as non-required, the change is also about making the controllers consistent.
Refs #2485

Fix custom app snippet leads to warnings for missing props

---

packages/ra-core/src/i18n/TranslationProvider.tsx

Initializing the translate function in `componentDidMount` instead of `constructor` makes the app render with the identity function for `translate`. Due to how validation works in redux-form, the `translate` function must be the right one during the first render.
Closes #2536

[RFR] Fix translation provider first loads with identity translate

---

packages/ra-ui-materialui/src/detail/editFieldTypes.js

[RFR] Fix JSX syntax error in code suggested by EditGuesser

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/Toolbar.js

[RFR] Add background to toolbar

---

README.md

Previously, the README stated that react-admin should be included as a dev dependency. Now, the README states that react-admin should be included as a production dependency.

Changed include type from dev to production

---

packages/ra-core/package.json

Node polyglot has some issues with Farsi locale in version 2.2.0 and it is fixed in 2.3.0. But as I looked tag version in ra-core is 2.2.0 and creates conflicts with 2.3.0. I suggest using ^2.2.0 to fix this issue.

Change node polyglot dependency tag

---

docs/List.md
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js

By default, `<Datagrid>` renders its body using `<DatagridBody>`, an internal react-admin component. You can pass a custom component as the `row` prop to override that default. And by the way, `<DatagridBody>` has a `row` property set to `<DatagridRow>` by default for the same purpose. `<DatagridRow>` receives the row `record`, the `resource`, and a copy of the datagrid children. That means you can create a custom datagrid logic without copying several components from the react-admin source.
For instance, to show the selection checkbox only for records that have a `selectable` field set to true, you can override `<DatagridRow>` and `<DatagridBody>` as follows:
```jsx
// in src/PostList.js
import { Datagrid, DatagridBody, List, TextField } from 'react-admin';
import TableCell from …
```

[RFR] Allow override of Datagrid Body and Row elements

---

packages/ra-ui-materialui/src/button/BulkDeleteButton.js
packages/ra-ui-materialui/src/button/CloneButton.js
packages/ra-ui-materialui/src/button/CreateButton.js
packages/ra-ui-materialui/src/button/DeleteButton.js
packages/ra-ui-materialui/src/button/EditButton.js
packages/ra-ui-materialui/src/button/ExportButton.js
packages/ra-ui-materialui/src/button/ListButton.js
packages/ra-ui-materialui/src/button/RefreshButton.js
packages/ra-ui-materialui/src/button/RefreshIconButton.js
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/button/ShowButton.js

We had the need to customize the icon shown on the `ShowButton`.
This commit changes just the `ShowButton`, so that you comment whether you like this change or not.
If you agree with this, let me know so that we also update the rest of the buttons located inside the `button` folder.
Thanks.

Add 'icon' prop to buttons

---

examples/simple/src/posts/PostEdit.js
packages/ra-core/src/controller/input/ReferenceArrayInputController.js

[RFR] Fix ReferenceArrayInput ignores default filter on search

---

packages/ra-ui-materialui/src/layout/MenuItemLink.js

As documented in `react-router`, the `<NavLink>` component can have either `string` or `object` type for its `to' property:
https://reacttraining.com/react-router/web/api/Link
Some developers use it as such:
```
<MenuItemLink
to={{
pathname: '/departments',
}}
primaryText="departments"
title="departments"
onClick={onMenuClick}
leftIcon={<BusinessIcon />}
/>
```

Allow 'object' propType in 'to' prop of 'MenuItemLink'

---

packages/ra-ui-materialui/src/layout/MenuItemLink.js

Much needed, because we could not use `e.preventDefault()` at the header item of an "accordion submenu" in the Menu.

Fix 'handleMenuTap' (onClick) to also pass the event to the 'onClick' prop

---

packages/ra-ui-materialui/src/auth/Login.js

CSS background image block the main thread when loading an image.
On the default Login page, we load a HUGE image and it makes the login form unresponsive with a slow internet connection.
This PR makes the background image loading async so that it don't block the interactivity.

[RFR] Speed Up Default Login Page Time To Interactive

---

packages/ra-data-json-server/src/index.js

[WIP] Change HTTP PATH method by PUT on UPDATE_MANY action

---

packages/ra-ui-materialui/src/auth/Login.js

This was a bad idea to push this in a rush.

[RFR] Fix login background url style

---

docs/Admin.md
docs/Theming.md
packages/ra-ui-materialui/src/auth/Login.js

Even though the React doc ensure the ref creation is done before the
componentDidMount, it can happen that the ref is set to null until the
next render.
So, to handle this case the component will now try to load the image on
the componentDidMount, but if the ref doesn't exist, it will try again
on the following componentDidUpdate. The try will be done only once.
Refs:
- https://reactjs.org/docs/refs-and-the-dom.html

[RFR] Login Background Image: handle empty ref

---

packages/ra-data-fakerest/package.json
packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql/package.json
packages/ra-data-json-server/package.json
packages/ra-data-simple-rest/package.json
packages/ra-realtime/package.json

This is to avoid too many reeexports, and a better dependency management in Lerna.

[RFR] Change dependencies of secondary packages to ra-core

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

See the official MUI demo using Popper for autocomplete inputs: https://material-ui.com/demos/autocomplete/
I tried it on a project and it does solve the issue

[RFR] Fix Autocomplete suggestions positioning is sometimes not recalculated properly

---

docs/UnitTesting.md
packages/ra-core/src/util/TestContext.js
packages/ra-core/src/util/TestContext.spec.js

* Add children as a renderProp option
* return the store if the `children` is a function
* Add `enableReducers` prop option
* will allow dispatching of actions
> these are opt-in change, not breaking changes.
fixes #2613
fixes #2612

Add enableReducers and renderProp option to TestContext to help with integration testing

---

docs/List.md
packages/ra-ui-materialui/src/list/ListActions.js

Related to this issue https://github.com/marmelab/react-admin/issues/2483

[RFR] Disable the Export button when there is nothing to export

---

docs/CustomApp.md
packages/ra-core/src/createAdminStore.ts

Closes #2632
This Pull Request removes the deprecation warning visible in latest versions of React Admin.
(The links points to https://github.com/zalmoxisus/redux-devtools-extension#usage)

[#2632] Fix deprecated Redux Dev Tools extension warning

---

docs/Inputs.md

fix error with shouldRenderSuggestions in documentation.

[DOC] fix syntax error with shouldRenderSuggestions

---

packages/ra-data-fakerest/README.md

Pass `true` as second argument to log the requests made to the provider in the console. This is very helpful to debug the requests made by an app using this data provider.
```jsx
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
import fakeDataProvider from 'ra-data-fakerest';
const dataProvider = fakeDataProvider({ /* data here */ }, true);
<Admin dataProvider={dataProvider}>
// ...
</Admin>
);
```

[RFR] Fix missing documentation for ra-data-fakerest logging abilities

---

packages/ra-core/src/form/FormDataConsumer.js
packages/ra-core/src/form/FormDataConsumer.spec.js

[RFR] Fix FormDataConsumer not working with custom form name

---

examples/demo/package.json
examples/demo/src/index.js

Fixes #2653
CRA 2.0 needs polyfills to work with IE11, so I followed [this doc](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) and everything seems to be back up for IE11.

Fix demo application for IE 11

---

packages/ra-ui-materialui/src/detail/Tab.js
packages/ra-ui-materialui/src/form/FormTab.js

For issue #2651.
I looked at every component that used `Link` and decided that `Tab` and `FormTab` were the only components where this ability really made sense.
I briefly considered adding docs for this prop, but `Tab` and `FormTab` are not documented and neither are their properties, so I thought it best to leave that for a different pull request.
Thank you.

Fix extra FormTab/Tab props are passed to two different components

---

packages/ra-language-english/README.md
packages/ra-language-french/README.md

The examples in the README are misleading because they are outdated since the migration to the i18nProvider. I fixed the examples to avoid future errors. There is still a few more documentation to be updated.

Updated documentation

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

I'm wondering whether we should adopt the same pattern for overriding the `TextInput` props: instead of passing them directly in options, putting them under a `textInputProps` key.
Fixes #2370

[RFR] Allow to override the Popper props in AutocompleteInput

---

packages/ra-ui-materialui/src/button/EditButton.js

Fixes a similar issue to #2457 where clicking on an Edit Button inside of a Datagrid with rowClick set to "show" doesn't handle the button event properly.

Fix EditButton in Datagrids using rowClick

---

docs/Show.md

[RFR] Fix outdated SimpleShowLayout doc about custom styles

---

packages/ra-core/src/reducer/admin/resource/data.js
packages/ra-core/src/reducer/admin/resource/data.spec.js

Context: https://marmelab.com/react-admin/Actions.html#using-a-custom-action-creator
We were relying on the action type to handle optimistic effects. This prevent custom actions to be handled optimistically too. 
Consider the following case: I have an `ACCEPT_CHANGE` and `REJECT_CHANGE` actions. Both will remove their targeted item from the `change` resource but will be caught by a custom saga to be applied on another resource. From the `change` resource perspective, they should be removed after being either accepted or rejected.
```js
export const acceptChange = (
id: string,
previousData: any,
basePath: string
) => ({
type: ACCEPT_CHANGE,
payload: { id, previousData },
meta: {
resource: 'changes',
fetch: DELETE,
onSuccess: {
notification: {
body: 'myapp.notification.accepted',
level: …
```

[RFR] Rely on meta to handle optimistic actions

---

packages/ra-ui-materialui/src/button/ShowButton.js

Fixes a similar issue to #2457 and #2686 where clicking on a Show Button inside of a Datagrid with rowClick doesn't handle the button event properly.
Requested by @fzaninotto

Fix ShowButton in Datagrids using rowClick

---

packages/ra-ui-materialui/src/button/Button.js

With Material UI, it is not possible to wrap a disabled `IconButton` inside a `Tooltip`.
```
<Tooltip title={translate(label, { _: label })}>
<IconButton
aria-label={translate(label, { _: label })}
color={color}
disabled // This is not allowed
>
{children}
</IconButton>
</Tooltip>
```
The PR https://github.com/marmelab/react-admin/pull/2595 causes this issue when there are not data to export.

[RFR] Fix warning when disabling a button on small devices

---

docs/Translation.md

In order to keep the same package structure of react-admin, I created a new github repository, ra-italian, which contains the translations in Italian into two lerna packages, ra-language-italian and ra-tree-language-italian.

update italian translation url

---

docs/UnitTesting.md
examples/simple/jest.config.js
examples/simple/package.json
examples/simple/src/test/configureEnzyme.js
examples/simple/src/users/UserShow.spec.js
package.json
yarn.lock

I saw a really good question on SO: [How to mock RA in order to unit test permission-based views?](https://stackoverflow.com/questions/54029681/how-do-i-pass-mock-data-to-a-list-component-in-react-admin)
So, instead of answer it directly, I wrote some doc.
EDIT: ~Aaaaaaaaaaand.. I broke the tests.~ It should be fixed.

[RFR] Permission unit testing (doc + example)

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.js

Fixes https://github.com/marmelab/react-admin/issues/2750
In `CheckboxGroupInput.js` file

[RFR] Fix CheckboxGroupInput design

---

packages/ra-core/src/reducer/admin/resource/list/ids.js
packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts
packages/ra-core/src/reducer/admin/resource/list/total.js
packages/ra-ui-materialui/src/input/CheckboxGroupInput.js

Some issues were introduced by #2684. Optimistic deletions and updates were not handled correctly in some reducers

[RFR] Fix incomplete optimistic handling from #2684

---

packages/ra-core/src/controller/field/ReferenceManyFieldController.js

Component ReferenceManyField takes filter prop but now it doesn't call fetching new data if filter changed. This PR can fix it.

Fix ReferenceManyField doesn't rerender when the filter props changes

---

packages/ra-input-rich-text/src/styles.js

Fixes #2675
The underlying problem is in the [css-vendor](https://github.com/cssinjs/css-vendor) library, specifically in the cssVendor.supportedValue method that breaks on IE11 with content and '' as parameters.
the `content: ''` attribute is currently not working on Chrome either.

Fix <RichTextInput> not working on IE11

---

packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.js

After facing the same problems as #2317, this PR allows to pass props through `<TabbedShowLayout>` to material-ui's `<Tabs>`. This way the user can enable all the different Tabs modes (such as `scrollable`, `centered`), and pass other props that might be useful. This is done through the `options` prop in `<TabbedShowLayout>`.

[RFR] Add options prop to TabbedShowLayout

---

docs/Fields.md
packages/ra-core/src/util/FieldTitle.js
packages/ra-core/src/util/getFieldLabelTranslationArgs.js
packages/ra-core/src/util/getFieldLabelTranslationArgs.spec.ts
packages/ra-core/src/util/index.js
packages/ra-ui-materialui/src/field/BooleanField.js
packages/ra-ui-materialui/src/field/BooleanField.spec.js

Currently, there is no way for a screen reader or an e2e test to know what's the field value as it only contains an icon.

[RFR] BooleanField accessibility

---

packages/ra-core/src/form/validate.js

The validators code is hardly readable due to the use of memoization, so inline JSDoc becomes necessary.

[RFR] Add JSDoc to validators for easier debugging

---

packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts

Hi and happy new year to you 😄 
I'm opening this pull request as I encountered a bug.
When I'm selecting rows in `<List>` and using the default "bulk delete" button, the rows disappear but the "header" still show "X item selected", until I refresh the page.
I investigated and found the issue. 
It seems this code is not working as we are passing an `array` to `indexOf`.
```js
const index = previousState.indexOf(action.payload.ids);	
if (index === -1) {	
return previousState;	
}
```
I deleted it as this test seems useless in DELETE_MANY case.
Hope this is good ! 👌 
Don't hesitate to tell me if I can do something more with this PR.

fix: delete-many keep selected items 

---

packages/ra-core/src/controller/CreateController.js
packages/ra-core/src/controller/EditController.js
packages/ra-core/src/controller/ListController.js
packages/ra-core/src/controller/ShowController.js
packages/ra-core/src/controller/checkMinimumRequiredProps.js

When we forgot to pass the props from the parent to the controller, the app displays a huge error.
```js
// For example:
const PostShow = () => (
<Show title={<PostTitle />} />
);
// Instead of:
const PostShow = props => (
<Show title={<PostTitle />} {...props} />
);
```

[RFR] Check minimum required props are passed to controllers

---

packages/ra-ui-materialui/src/layout/Notification.js

Closes #2721 
See [Material-ui's documentation of the `disableWindowBlurListener` Snackbar prop](https://v1-5-0.material-ui.com/api/snackbar/).

[RFR] Fix optimistic actions never get sent when changing tabs

---

packages/ra-core/src/sideEffect/admin.js
packages/ra-core/src/sideEffect/index.js
packages/ra-core/src/sideEffect/unload.ts

[RFR] Add an alert preventing data loss when a user closes the app while in optimistic mode

---

examples/simple/package.json
yarn.lock

https://nvd.nist.gov/vuln/detail/CVE-2018-14732
No vulnerability found in production bundle - this only concerns webpack-dev-server, which we use internally for testing purposes.

[RFR] Fix vulnerability in development tools

---

docs/DataProviders.md

Added Hasura's official repository link as a Data Provider for `react-admin`
It is available on npm at [http://npmjs.com/package/ra-data-hasura](http://npmjs.com/package/ra-data-hasura)

Add Hasura Data Provider

---

docs/DataProviders.md

Added a third-party repository supporting the Firestore database.

Firestore Data Provider

---

packages/ra-ui-materialui/src/button/DeleteButton.js

Sepecifying the `redirect` prop as a boolean was trigerring a warning in console

[RFR] Fix sanitization of DeleteButton props

---

docs/Translation.md

`pimschaaf` recently transferred ownership of both the `ra-language-dutch` repo and npm packages to me. Thought I'd change the URL in the docs too.

Update link to Dutch translation package

---

packages/ra-core/src/actions/dataActions.js

After making an delete, by default you must refresh.
Closes #2425

Fix DeleteButton undoable={false} in List does not refresh List

---

packages/ra-ui-materialui/src/input/SelectInput.js

Property with undefined value was passed to asyncValidation when onBlur event occured

[RFR] Fix undefined issue in asyncValidation for SelectInput

---

cypress/integration/list.js
packages/ra-core/src/controller/ListController.js
packages/ra-core/src/controller/ListController.spec.js

[RFR] Fix default filter values cannot be removed by user

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

[RFR] Fix AutocompleteInput reopen after selection

---

cypress/integration/create.js
packages/ra-ui-materialui/src/input/AutocompleteInput.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.js

The main issue was that when used in a `ReferenceInput`, whenever the filter changed,  the `AutocompleteInput` first checked if one of the already available choices matched and if only one was found, it would not even try to fetch others from the `dataProvider`.
As we also had numerous complaints about the auto-selection feature, we decided to remove it completely.
Fixes #2688, #2346

[RFR] Fix AutocompleteInput by removing auto selection

---

packages/ra-ui-materialui/src/button/CreateButton.js

The `CreateButton` is using an optimization to re-render only a certain set of keys change. However, the `translate` prop was not part of that. This was causing the component to not re-render when the translate function was updated due to language having changed.
This is now fixed by specifying the `translate` as being a prop change that causes a re-render.
Fixes #2830

Fix `CreateButton` not being re-translated when language change at runtime

---

docs/Translation.md

In the section `Translate your own components`

Removed React context mention in the documentation

---

docs/Fields.md

This fixes a small mistake in a code snippet of the `SelectInput` section of the documentation.

Fix SelectField example snippet on the docs

---

docs/UnitTesting.md

The previous import location threw an error for me as it couldn't be found.

Update Unit Testing documentation

---

packages/ra-data-json-server/src/index.js

I think using the [json-server](https://github.com/typicode/json-server) `like` feature is not what we want here, since an `id_like=2|33|444` will match 2, 33, 444 but also 23, 133 and so forth.
We could restrict the match with delimiters (`^` and `$`) but since it supports multiple filters query, it would be simpler to use just that.

Fix GET_MANY in ra-data-json-server data provider returns too many results

---

packages/ra-ui-materialui/src/input/ArrayInput.js

It wasn't letting arrays through, even though they work absolutely fine.

Corrected prop types for ArrayInput

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js

This merge request solves the problem reported in issue #2259.
The problem happens because the **`Popper`** component used to render the **`choices`** is a stateless component. Since the **`Popper`** component receives a reference to the **`inputEl`** component, the render method is unable to detect when the original **`inputEl`** moved to another place.
I noticed that when the original **input** element moves, React is keeping the old **`Popper`** component without forcing it to redraw.
My solution is based on this example from **`Material-UI`** docs:
https://v1-5-0.material-ui.com/utils/popper/#faked-reference-object
I'm keeping an object that has a reference to the last position of the **`inputEl`** and updating this object only when the **`inputEl`** moves. Doing this we only force …

Fix position of choices container when input element moves to another location

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js

The problem described in issue #2361 happens because, sometimes, the **input** component has an **empty string** as a default value, but the **`AutocompleteArrayInputChip`** component only accepts an **`Array`** as a value.
Enforcing **`state.inputValue`** to be an **`Array`** solves the issue.
Fixes #2361.

Fix error thrown by ChipInput component generated by AutocompleteArrayInput

---

packages/ra-core/src/i18n/TranslationProvider.tsx
packages/ra-core/src/i18n/translate.tsx

The following warning occurs when the translate method tries to translate an empty string. This is possible for example for the empty default choice in autocomplete inputs.
> Warning: Missing translation for key: ""
The solution is to declare an empty translation for empty string `'' => ''` in `TranslationProvider`.

[RFR] Fix warning about missing translation for empty key

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

This merge request solves the problem reported in issue #2259 also for **`AutocompleteInput`** component.
The changes are the same applied on **`AutocompleteArrayInput`** (#2860).
Fixes #2259.

Fix position of suggestions container on AutocompleteInput

---

docs/Show.md
packages/ra-ui-materialui/src/detail/index.js

PR to export and document the component created in https://github.com/marmelab/react-admin/pull/2740.

[RFR] Export and document TabbedShowLayoutTabs

---

docs/Authorization.md

There is no 'permissions' in the Menu props, and it is not used in this example.

There is no 'permissions' in the Menu props

---

docs/CreateEdit.md
examples/simple/src/users/UserEdit.js
examples/simple/src/users/UserList.js
packages/ra-ui-materialui/src/button/BulkDeleteButton.js
packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.js
packages/ra-ui-materialui/src/button/DeleteButton.js
packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithUndoButton.js
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/button/index.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/Toolbar.js
packages/ra-ui-materialui/src/layout/Confirm.js

Refs #2866 
By default, the Save and Delete actions are undoable, i.e. react-admin only sends the related request to the data provider after a short delay, during which the user can cancel the action. This is part of the "optimistic rendering" strategy of react-admin ; it makes the user interactions more reactive.
You can disable this behavior by setting `undoable={false}`. With that setting, clicking on the Delete button displays a confirmation dialog. Both the Save and the Delete actions become blocking, and delay the refresh of the screen until the data provider responds.
```jsx
const PostEdit = props => (
<Edit undoable={false} {...props}>
...
</Edit>
```
**Tip**: If you want a confirmation dialog for the Delete button but don't mind undoable Edits, then pass a [custom …

Non-undoable delete buttons show confirmation dialog

---

docs/Actions.md

FlatButton doesn't appear to exist anymore
https://material-ui.com/guides/migration-v0x/#where-should-i-start-in-a-migration

FlatButton => Button

---

docs/DataProviders.md
docs/Ecosystem.md

* Django Rest Framework
* HAL
* JSON HAL
* REST-HAPI
* Sails.js
* Spring Boot
Not all of them are open-source, but they are all a good starting point.
Thanks npmjs.com for the list of dependent packages.

[RFR] Add 6 new data providers to the Ecosystem

---

packages/ra-ui-materialui/src/layout/Layout.js

Following up from Pull Request #2763 
I work with @phacks and I found another solution to fix the layout problem.
@fzaninotto we can't see the additional scrollbar at the bottom anymore.
<details>
<summary>Internet Explorer 11 (Windows)</summary>
</details>
<details>
<summary>Mozilla Firefox (Windows)</summary>
</details>
<details>
<summary>Safari 12 (MacOS)</summary>
</details>
<details>
<summary>Edge (Windows)</summary>
</details>
<details>
<summary>Opera (Windows)</summary>
</details>
<details>
<summary>Comment List in chrome (MacOS)</summary>
</details>

Fix IE11 layout problem caused by missing `flex-basis: 0`

---

packages/ra-core/src/sideEffect/auth.ts

Closes #2939 
**Proposed solution:**
Proposed solution: Use `takeLatest` instead of `takeEvery` saga effect to handle authentication errors.

Fix multiple redirect events on auth error

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/SelectInput.js
packages/ra-ui-materialui/src/input/SelectInput.spec.js

#2234 introduced a breaking change for our application. This change adds an optional custom value which is used when allowEmpty is set.
Previously `null` was set as an empty value, now you can set null again.

Add an optional emptyValue to SelectInput

---

packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js

A late refactoring in Confirm introduced a bug in the DeleteWithConfirm button: the function called upon confirm doesn't receive any event. So clicking on "confirm" on the dialog raised an error and made the deletion impossible:
> Uncaught TypeError: Cannot read property 'stopPropagation' of undefined

Fix DeleteWithConfirmButton

---

examples/demo/package.json
examples/demo/src/dataProvider/graphql.js
packages/ra-data-graphcool/package.json
packages/ra-data-graphql-simple/package.json
packages/ra-data-graphql/package.json
yarn.lock

Fixes #2990
This was most probably caused by the CRA update which updated babel. Upgrading the graphql dependencies fixed it.
I also fixed the demo which had a new `invoices` resource added in the REST provider but not the graphql one.

Fix the graphql demo

---

cypress/integration/edit.js
packages/ra-ui-materialui/src/input/AutocompleteInput.js

Fix AutocompleteInput choices are displayed again after selection

---

packages/ra-ui-materialui/src/layout/Menu.js

Fix warning when creating custom Menu based on source

---

packages/ra-data-graphql/README.md

Fix missing mention of compulsory buildQuery param in ra-data-graphql

---

examples/demo/src/dataProvider/graphql.js
packages/ra-data-graphcool/src/buildQuery.js
packages/ra-data-graphcool/src/buildQuery.test.js
packages/ra-data-graphql-simple/src/buildQuery.js
packages/ra-data-graphql-simple/src/buildQuery.test.js
packages/ra-data-graphql-simple/src/index.js
packages/ra-data-graphql/src/index.js

Fix ra-data-graphql-simple handling of UPDATE mutations

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

Fix AutocompleteInput crashes when a choice doesn't have a string value

---

packages/ra-ui-materialui/src/button/CloneButton.js

Fix CloneButton double redirection when used in Datagrid with rowClick

---

docs/Translation.md

This PR adds a link to the translation section. It refers to a new standalone package for the German translations of the ra-tree-ui-materialui package as propsed in PR #2998.
Due to problems with my local repo I had to recreate the fork. Thus, PR #3011 is obsolete and can be continued here.

[RFR] Update documentation with German translation package

---

packages/ra-input-rich-text/src/index.js

Closes #3022 
Enhancing toolbar Proptypes to accept [quill container and handlers](https://quilljs.com/docs/modules/toolbar/)

Fix RichTextInput toolbar PropsType

---

packages/ra-core/src/controller/ListController.tsx
packages/ra-core/src/reducer/admin/resource/list/queryReducer.spec.ts
packages/ra-core/src/reducer/admin/resource/list/queryReducer.ts

new PR related to https://github.com/marmelab/react-admin/pull/2855

change SET_SORT reducer to accept a order value.

---

docs/Actions.md
packages/ra-core/src/util/Query.spec.tsx
packages/ra-core/src/util/Query.tsx

As explained on [the documentation](https://marmelab.com/react-admin/DataProviders.html#response-format), the dataProvider can return two keys `data` and `total`:
As of now, `<Query>` can only return `data`, and this is very restrictive, especially when dealing with lists or references.
This PR aims to pass the prop `total` with the data, but also test and document the usage of <Query> with lists.

[RFR] Allow <Query> to pass all results from dataProvider

---

packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js

Fixes https://github.com/marmelab/react-admin/issues/3040
Follows https://github.com/marmelab/react-admin/pull/2955
We use to singularize the confirm message in the `BulkDeleteWithConfirmButton` component. But we often select more than one component. The solution is to use [inflect](https://github.com/dreamerslab/node.inflection#inflectioninflect-str-count-singular-plural-) to select wisely between pluralize or singularize.

[RFR] Pluralize the confirmation message in BulkDeleteWithConfirmButton

---

docs/Tutorial.md

`List ` component is used in the example but never imported.

Missing component import in tutorial

---

packages/ra-tree-ui-materialui/src/TreeNode.js

On certain material-ui versions, the expand icon stretches the whole TreeNode width, because we set it to `left: ...` but material-ui sets it to `right: ...`.
I am force to use 3.9.2, but this was already the case in the used version 1.4.0.
This is fixed in material-ui 4 in this commit: https://github.com/mui-org/material-ui/commit/7b0f7d5afae78303c43545573bd1433094921e7e
until then, setting `right: auto` on the expandIcon in the TreeNode will fix it for every version

fix: expand icon overlaps actions in tree view

---

packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/detail/Show.js
packages/ra-ui-materialui/src/list/ListToolbar.js

Previously, it was impossible to write: `<Show basePath="/foo" actions={<ShowActions basePath="/foo/bar" />} />` because we were not tolerating `props` on `DefaultActions`, making the API/props useless/broken.

Fix custom actions cannot override basePath

---

packages/ra-data-graphql-simple/src/buildVariables.js

The fix for GraphQL version 14.0.0+ related scalar value coercion. The current version doesn't work correctly. GraphQL changes: https://www.libupdate.com/libs/1c88bd1e-024d-41aa-9241-c29cd6d5f0c5

Fixed wrong scalar types into variables for ra-data-graphql-simple

---

packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/ListActions.js
packages/ra-ui-materialui/src/list/ListToolbar.js

[RFR] Fix Export button ignores permanent filter from List

---

packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js

[RFR] Fix resource translation in delete confirmation dialog

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/Bug_report.md
README.md
examples/tutorial/src/App.js

[RFR] Fix links to CodeSandbox become outdated rapidly

---

examples/data-generator/LICENSE.md
examples/data-generator/README.md
examples/data-generator/package.json
examples/demo/package.json
examples/demo/src/fakeServer/graphql.js
examples/demo/src/fakeServer/rest.js

- When learning react-admin, developers often need a fake API. jsonplaceholder isn't perfect (it doesn't accept mutations), so developers use JSONServer or json-graphql-server, but they need data.
- The demo doesn't run on CodeSandbox as is because of the dependency to an internal package. Having the demo run in CodeSandbox would ease bug reports
- Who doesn't need fake data?

[RFR] Turn data generator for demo into a public repository

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js

If no `id` is passed to `RadioButtonGroupInput` component, the input is given the id `undefined_optionvalue`. Consider the case where two fields have the same choices, but different `source`. They will be given the same id, and the form control labels will interfere, which is not nice.
Updated the component to not put `undefined_optionvalue` into the id of the node, and added a note to the docs.

Fix undefined id in RadioButtonGroupInput

---

docs/Translation.md

I have forked [motro/aor-language-hebrew](https://github.com/motro/aor-language-hebrew) which was the Hebrew translation for `admin-on-rest` and converted it to `react-admin`. 
You can see my project [here](https://github.com/ak-il/ra-language-hebrew/tree/v1.0.0)
It's also [published on npm](https://pastebin.com/9JKFGyMk) though I can't see it on [npmjs](https://www.npmjs.com/search?q=ra%2Dlanguage%2Dhebrew) at the moment of creating this pull request.

Add link to ra-language-hebrew

---

docs/Tutorial.md
docs/index.md

[RFR] Suggestions for improving tutorial

---

docs/FAQ.md
examples/demo/package.json
examples/simple/package.json
examples/tutorial/package.json
packages/ra-ui-materialui/package.json
packages/ra-ui-materialui/src/auth/Login.tsx
packages/ra-ui-materialui/src/field/BooleanField.js
packages/ra-ui-materialui/src/field/BooleanField.spec.js
packages/ra-ui-materialui/src/input/BooleanInput.spec.js
packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.js
packages/ra-ui-materialui/src/input/DateInput.js
packages/ra-ui-materialui/src/input/DateInput.spec.js
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.js
packages/ra-ui-materialui/src/input/SelectArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.spec.js
packages/ra-ui-materialui/src/list/Pagination.js
packages/ra-ui-materialui/src/list/Pagination.spec.js
yarn.lock

This allows usage of material ui v3, which is backwards compatible with v1 (Firefox 45 aside).
I tested the simple and demo example: they work perfectly. 
Now I regret we didn't do this earlier (!)

[RFR] Relax material ui version dependency

---

packages/ra-core/src/util/Query.spec.tsx
packages/ra-core/src/util/Query.tsx
packages/ra-core/src/util/TestContext.tsx

[RFR] Fix query component does not fetch again when updated

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.js

Same as #2678, but for `AutocompleteArrayInput` component

[AutocompleteArrayInput] Allow to override Popper props

---

package.json
packages/ra-input-rich-text/src/index.js
packages/ra-input-rich-text/src/index.spec.js
test-setup.js
yarn.lock

Hi,
in ra-input-rich-text,
whenever the text changes, below is the sequence of events happening.
Original text `<p>test</p>`
1. User change text to `<p>test1</p>`
2. `onTextChange` fired
3. `componentDidUpdate` fired
4. update happens as previous prop value is still `<p>test</p>`, but unecessary
5. `onTextChange` fired again.
6. stops there as the prevProp input value is the same as current prop input value
2nd issue is that, it seems quilljs is always adding additional `<p>` after this method
```
this.quill.setContents(
this.quill.clipboard.convert(this.props.input.value)
)
```
***ONLY*** for the text that has special characters, i.e ```ARTÍCULO 1.- El presente reglamento es de observancia obligatoria``` after you bold ```ARTÍCULO 1```
fixes …

Fix unnecessary update of ra-input-rich-text on edit

---

packages/ra-core/src/i18n/TranslationProvider.tsx
packages/ra-core/src/sideEffect/i18n.ts

These changes do two things:
- When receiving a new locale and messages it's not only checked if the locale has changed but also if the messages have changed. This fixes #3139 .
Object comparison might not be the best use here, but I think that the messages object won't be too large for it to still be performant.
- It will start showing the fetch spinner before loading the translations and end it afterwards. This is useful when translations are loaded async. When it takes longer, the user doesn't know that anything is happening and then suddenly the strings switch. 
This might be improved to delay it for a short while, so there is no spinner when the messages are returned immediately.

[RFR] Improve translation loading

---

packages/ra-core/src/controller/field/ReferenceManyFieldController.tsx

All the `...Field` components can accept a compound source property to enable the display of nested record properties, with the exception of `ReferenceManyField`. This PR fixes that.
Unfortunately I haven't been able to get tests working so far and can't spend any more time on it right now, so I'm hoping someone else can add the one extra test to test this specific capability of the source property.
I don't think any extra documentation is required, as this is merely bringing the behaviour of this field in line with all the other field components.

Support nested records in source property of ReferenceManyField

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInputChip.js

When using `AutocompleteArrayInput` with lots of chips, view gets wider and wider.
This PR enables chips wrapping to avoid this problem.
Before:
After:

[AutocompleteArrayInput] wrap chips instead of increasing view width

---

packages/ra-data-graphql-simple/src/buildGqlQuery.js
packages/ra-data-graphql-simple/src/buildGqlQuery.test.js

The path prevents the `buildFields` method from circular dependencies, so that `linkedTypes` are only processed if they aren't  analyzed before.

Prevent ra-data-graphql-simple from circular dependencies issue

---

packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/Create.spec.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/detail/Edit.spec.js
packages/ra-ui-materialui/src/detail/Show.js
packages/ra-ui-materialui/src/detail/Show.spec.js
packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/List.spec.js

When using `ShowController` and `ShowView` instead of single `Show` component, `Show` styles aren't used anymore.
This makes `aside` component appear under show view (when using `Show` component, `aside` is on the right).
Wrapping `ShowView` with styles HOC resolves the issue. Also, it makes more sense, since styles are related to *view* component, not `Show` component, which is simply composition of controller and view.

[List, Edit, Create, Show] Wrap view components into styles HOC instead of wrapping main components

---

docs/Authentication.md

The docs mention `checkCredentials` but it was removed in afda4b2d47a667a0b5264539a0819da3008b80c6

docs: remove mention of checkCredentials

---

examples/demo/src/reviews/RejectButton.js

Looks like there was some copy-and-paste error, so RejectButton
was defined as AcceptButton. This commit renames references to
properly to "Reject..."
Fixes Issue #3178
Signed-off-by: Eric Brown <browne@vmware.com>

Rename improperly named RejectButton class name

---

packages/ra-input-rich-text/src/index.js

[ra-input-rich-text] Do not show error message, if input isn't touched

---

examples/demo/package.json
examples/demo/src/layout/Login.js
examples/demo/src/routes.js
packages/ra-core/package.json
packages/ra-core/src/sideEffect/accumulate.spec.ts
packages/ra-core/src/sideEffect/accumulate.ts
packages/ra-core/src/sideEffect/undo.spec.ts
packages/ra-realtime/package.json
yarn.lock

[RFR] Upgrade redux saga

---

cypress/integration/edit.js
packages/ra-core/src/actions/listActions.ts
packages/ra-core/src/controller/CreateController.spec.tsx
packages/ra-core/src/controller/CreateController.tsx
packages/ra-core/src/controller/EditController.tsx
packages/ra-core/src/controller/ListController.spec.tsx
packages/ra-core/src/controller/ListController.tsx
packages/ra-core/src/controller/ShowController.tsx
packages/ra-core/src/controller/checkMinimumRequiredProps.tsx
packages/ra-core/src/types.ts

I believe the first step before migrating our controller components to custom hooks is to make them use hooks in the first place.

[RFR] Use hooks in controllers

---

packages/ra-core/src/reducer/admin/references/oneToMany.spec.ts
packages/ra-core/src/reducer/admin/references/oneToMany.ts

When a `<ReferenceManyField>` displays a `<DataGrid>` with a `DeleteButton` on each row, optimistically deleting a reference will set its row into loading state but won't actually remove it until the action is resolved.
Handle the `DELETE` effects in the `oneToMany` reducer by checking whether we have references related to the deleted item resource and removing the deleted item from them.

[RFR] Fix handling of deleted references

---

packages/ra-input-rich-text/src/styles.js

`RichTextInput` has hardcoded color, which doesn't look good when using non-default theme colors.

[RichTextInput] Use color from theme

---

packages/ra-core/src/controller/ListController.spec.tsx
packages/ra-core/src/controller/field/ReferenceFieldController.spec.tsx
packages/ra-core/src/controller/field/ReferenceFieldController.tsx
packages/ra-core/src/controller/field/index.ts
packages/ra-core/src/controller/field/useReference.ts
packages/ra-core/src/fetch/Mutation.spec.tsx
packages/ra-core/src/fetch/Query.spec.tsx
packages/ra-core/src/i18n/useTranslate.spec.tsx
packages/ra-core/src/util/FieldTitle.spec.tsx
packages/ra-core/src/util/TestContext.tsx
packages/ra-core/src/util/index.ts
packages/ra-core/src/util/renderWithRedux.tsx
packages/ra-ui-materialui/src/detail/Create.spec.js
packages/ra-ui-materialui/src/detail/Edit.spec.js
packages/ra-ui-materialui/src/detail/Show.spec.js
packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/field/SelectField.spec.js
packages/ra-ui-materialui/src/list/FilterForm.spec.js
packages/ra-ui-materialui/src/list/List.spec.js

Refactor ReferenceFieldController using hooks and introduce useReference hooks.
ReferenceMany will follow.

[RFR] Reference hooks

---

cypress/package.json
cypress/plugins/index.js
cypress/support/index.js
yarn.lock

This PR upgrades `cypress` to 3.2.0 and adds [cypress-skip-and-only-ui](https://github.com/bahmutov/cypress-skip-and-only-ui) plugin.
Note, that additional buttons appear only when whole test suite ends.
Still, it's better than `it.only` option, since it's easy to forget and commit to repo - see https://github.com/marmelab/react-admin/pull/3223#discussion_r284576949

upgrade cypress and add ability to run single test

---

.prettierrc
package.json
tslint.json

Hello !
I noticed a duplication in the tslint and prettier configuration, so I factorized it in a prettierrc configuration file.
Thanks for your awesome project !

[RFR] Factorize prettier logic to prettierrc

---

docs/Reference.md

`<FunctionField>` was present twice in list

Remove duplicated item in references

---

packages/ra-ui-materialui/src/input/BooleanInput.js
packages/ra-ui-materialui/src/input/BooleanInput.spec.js

This is a rework of https://github.com/marmelab/react-admin/pull/3115
* display error on MUI BootstrapInput
* adapt tests (defaultProps)
Closes https://github.com/marmelab/react-admin/pull/3115

[RFR] [Rework] Display errors on mui BooleanInput

---

packages/ra-core/src/util/Query.spec.tsx
packages/ra-core/src/util/Query.tsx

This is a rework of https://github.com/marmelab/react-admin/pull/3176
- Changed shallowEqual to deepEqual in Query to accommodate for possible deep props.
- Changed the placement of myPayload variable.
When myPayload is global the objects are indeed identical and the script worked did pass. However, this assumes independency from props, which is not desired. This can easily lead to endless loops.
Fixes #3174
Closes https://github.com/marmelab/react-admin/pull/3176

[RFR] [Rework] Fix sending request by Query with deep props on every update

---

docs/List.md
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/DatagridRow.spec.js

This is a rework of https://github.com/marmelab/react-admin/pull/3120
* Allow `rowClick="toggleSelection"` option on DatagridRow
* Add corresponding documentation
* Add tests for all the `rowClick` options
Closes https://github.com/marmelab/react-admin/pull/3120

[RFR] [Rework] Datagrid rowclick toggle

---

packages/ra-core/src/RoutesWithLayout.tsx
packages/ra-ui-materialui/src/layout/NotFound.js

[RFR] Authenticate NotFound page

---

packages/ra-core/src/reducer/admin/resource/data.ts
packages/ra-core/src/util/getFetchedAt.ts

When you have a call with many identifiers then the getFetchedAt took a lot of time.

optimize getFetchedAt.ts

---

packages/ra-ui-materialui/src/auth/LoginForm.tsx
packages/ra-ui-materialui/src/button/SaveButton.js

The `<CircularProgress />` icon in Login Form is too close to the text and too big.  The solution is to add a margin and reduce its size.
**Before**
**After**

[RFR] Fix design of icon loaders

---

docs/Inputs.md

Example in the doc was using prop from the latest version of `<Checkbox>` component from Material Ui and also a link of `<Checkbox>` documentation was pointing to the latest Material Ui version, and Material Ui version used by `ra-ui-materialui` does not support many props from the latest version, so the confusion for users.
Changed both prop example and link to version (1.5.1) used by `ra-ui-materialui`.
Resolves #2883

[RFR] Doc update of <CheckboxGroupInput>

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

Disable both `MuTextField` and `IconButton` when `disabled` prop is passed to `<ResettableTextField>`
Fixes #2619

[RFR] Add disabled prop to clear IconButton in <ResettableTextField>

---

examples/simple/src/comments/CommentEdit.js
examples/simple/src/comments/CommentList.js
examples/simple/src/comments/PostPreview.js
examples/simple/src/comments/PostQuickCreate.js
examples/simple/src/comments/PostQuickCreateCancelButton.js
examples/simple/src/comments/PostReferenceInput.js
examples/simple/src/posts/PostCreate.js
examples/simple/src/posts/PostList.js
examples/simple/src/posts/ResetViewsButton.js
examples/simple/src/tags/TagList.js
examples/simple/src/users/UserEdit.js

Review with "Hide whitespace changes" params

[RFR] Migrate simple example to hooks

---

examples/simple/src/posts/PostList.js

Fixes https://github.com/marmelab/react-admin/issues/3278

[RFR] Add exporter for posts list in demo app

---

packages/ra-ui-materialui/src/list/FilterButton.js
packages/ra-ui-materialui/src/list/FilterButton.spec.js
packages/ra-ui-materialui/src/list/FilterForm.js
packages/ra-ui-materialui/src/list/FilterForm.spec.js

Fixing a bug from this issue: https://github.com/marmelab/react-admin/issues/2722

fix filter condition to work with nested object paths

---

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx

Fixes https://github.com/marmelab/react-admin/issues/3108

[RFR] Remove duplicate API call in ReferenceArrayInput

---

packages/ra-ui-materialui/src/input/AutocompleteInput.js

Hi,
This is a PR to fix AutocompleteInput issue #2428. I added the prop focusInputOnSuggestionClick by default to false, and since the input loses focus on suggestion selection, i had to change the state when calling handleSuggestionSelected().
Best Regards.

fixed AutocompleteInput popup to re-render after choice is selected

---

packages/ra-ui-materialui/src/layout/Layout.js

While reverting #3262 on #3312, I broke the layout component injection which should still use components and not elements.

[RFR] Fix Layout component injection

---

packages/ra-core/src/sideEffect/auth.ts
packages/ra-language-english/index.js
packages/ra-language-french/index.js

Show notification on USER_CHECK error in auth.
I used google translate to convert from English to French, please correct me if I am wrong.
Fixes #2967

[RFR] Show notification on USER_CHECK error

---

examples/demo/src/reviews/ReviewList.js
packages/ra-core/src/controller/ListController.tsx
packages/ra-core/src/controller/useListParams.ts
packages/ra-core/src/fetch/useGetList.ts
packages/ra-core/src/fetch/useQueryWithStore.ts
packages/ra-core/src/util/index.ts
packages/ra-core/src/util/useWhyDidYouUpdate.ts
packages/ra-ui-materialui/src/layout/Responsive.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/ListActions.js
packages/ra-ui-materialui/src/list/ListToolbar.js

The hooks migration degraded performance of the List views. I've managed to get the performance almost on par with master with a few changes. 
I've also added a `usewhyDidYouUpdate` hook that turns out to be a precious assistant (because the React DevTools Profiler sucks at telling why a component re-rendered).

[RFR] List performance optimizations

---

cypress/integration/create.js
cypress/integration/edit.js
cypress/support/CreatePage.js
cypress/support/EditPage.js
examples/simple/src/posts/PostCreate.js
packages/ra-input-rich-text/src/index.js

As suggested in https://github.com/marmelab/react-admin/pull/3209#issuecomment-492273806, I've added tests.
Fixes #3206, #3207 and https://github.com/marmelab/react-admin/pull/3209#issuecomment-492246926
Closes #3209, #3221 and #3208 patches, since it contains them all.

[RichTextInput] add tests and fix bugs

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js

AutoCompleteArrayInput was not showing up error message when there is a validation error. It shows up the input in red color but the error message is not shown. 
Fixing the code to follow the same patten as SelectInput and AutocompleteInput.

Fix AutoCompleteArrayInput not showing error message

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.js

[RFR] Add suggestionLimit prop to <AutocompleteArrayInput>

---

docs/CreateEdit.md
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js
packages/ra-ui-materialui/src/form/TabbedFormTabs.js
packages/ra-ui-materialui/src/form/TabbedFormTabs.spec.js
packages/ra-ui-materialui/src/form/index.js

[RFR] Add tabs prop to <TabbedForm> to allow injecting custom Tabs component

---

UPGRADE.md
docs/Fields.md
packages/ra-core/src/controller/field/ReferenceFieldController.spec.tsx
packages/ra-core/src/controller/field/ReferenceFieldController.tsx
packages/ra-core/src/controller/field/useReference.ts
packages/ra-ui-materialui/src/field/ReferenceField.js
packages/ra-ui-materialui/src/field/sanitizeRestProps.ts

Fixes https://github.com/marmelab/react-admin/issues/2288
* enable linkType function for ReferenceField
* update docs
PR to `next` as it is a new feature

[RFR] Add link function to ReferenceField

---

packages/ra-ui-materialui/src/form/TabbedForm.js

**The Issue**: When trying to use TabbedForm inside a dialog modal, and click on Cancel button, I got the following error. `TypeError: Cannot read property 'url' of null`.
**The Bug Reason**: When the button cancel is clicked, the `match`object return `null`.
**The Solution**: Set the `location.pathname` instead when `match` returns null.

Fixing issue where the URL validation is getting an error

---

examples/demo/src/categories/LinkToRelatedProducts.js
examples/demo/src/configuration/Configuration.js
examples/demo/src/dashboard/CardIcon.js
examples/demo/src/dashboard/MonthlyRevenue.js
examples/demo/src/dashboard/NbNewOrders.js
examples/demo/src/dashboard/Welcome.js
examples/demo/src/layout/AppBar.js
examples/demo/src/orders/MobileGrid.js
examples/demo/src/orders/OrderEdit.js
examples/demo/src/orders/OrderList.js
examples/demo/src/products/GridList.js
examples/demo/src/products/Poster.js
examples/demo/src/products/ProductCreate.js
examples/demo/src/products/ProductEdit.js
examples/demo/src/products/ProductList.js
examples/demo/src/products/ThumbnailField.js
examples/demo/src/reviews/ReviewEdit.js
examples/demo/src/reviews/ReviewEditToolbar.js
examples/demo/src/reviews/ReviewFilter.js
examples/demo/src/reviews/ReviewListDesktop.js
examples/demo/src/reviews/ReviewListMobile.js
examples/demo/src/segments/LinkToRelatedCustomers.js
examples/demo/src/visitors/MobileGrid.js
examples/demo/src/visitors/SegmentInput.js
examples/demo/src/visitors/VisitorCreate.js
examples/demo/src/visitors/VisitorEdit.js
examples/demo/src/visitors/VisitorList.js

Use `makeStyles` on demo
Review with "Hide whitespace changes" options in Github

[RFR] Use makeStyles hooks on examples demo

---

examples/demo/package.json
package.json
packages/ra-core/package.json
packages/ra-core/src/controller/field/useReferenceArray.ts
packages/ra-core/src/controller/field/useReferenceMany.ts
packages/ra-core/src/controller/useListParams.ts
packages/ra-core/src/controller/useRecordSelection.ts
packages/ra-core/src/fetch/useGetList.ts
packages/ra-ui-materialui/package.json
yarn.lock

Requires changes in useSelector due to breaking change in react-redux 7.1.0-alpha.5 (see https://github.com/reduxjs/react-redux/releases/tag/v7.1.0-alpha.5).
Without this upgrade, TypeScript will fail to build after a yarn fresh install, because the new DefinitelyTyped types for react-redux enforce the `useSelector` signature of 7.1.0 final.

[RFR] Upgrade react-redux to version 7.1

---

docs/Actions.md

Fixes #3355
This PR fixes the dead link to the `Bulk Action Buttons` implementation example in https://marmelab.com/react-admin/Actions.html#list-bulk-actions
```
"You can find a complete example of a custom Bulk Action button in the List documentation, 
in the Bulk Action Buttons section." <--- Here
```
- Clicking on the link should navigate the user to the `Bulk Action Buttons` implementation example in `List markdown` instead of displaying a `Not Found` page
- N/A
- Navigate to [here](https://marmelab.com/react-admin/Actions.html#list-bulk-actions)
- Click on `Bulk Action Buttons`
- The page should navigate to [here](https://marmelab.com/react-admin/List.html#bulk-action-buttons) instead of displaying a `Not Found` page 
References …

[RFR] Fix Dead Link to Bulk Action Buttons in Docs

---

packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js

Fixes #3359
When the DeleteWithConfirm modal was closed, it behaved like we clicked
on the Datagrid row (triggering the `rowClick` handler of Datagrid)

[RFR] Prevent Event propagation after Delete Confirm modal close

---

packages/ra-ui-materialui/src/layout/DashboardMenuItem.js

When (re)using the component `<DashboardMenuItem>`, if pass it a `className` prop it is supressed by the component and not passed to its children `MenuItem`.
1. Pass the `className` prop to its children
2. or, let this one in the default props passed in the children
I choose the second one, because this prop isn't used anyway.

[RFR] Fix DashboardMenuItem className prop

---

docs/Tutorial.md

I followed the tutorial from scratch and got the following error, which this fixes.
```
./src/App.js
Line 2:  'Resource' is defined but never used     no-unused-vars
```

Remove unused import

---

README.md
docs/Admin.md
docs/Fields.md
docs/Inputs.md
docs/List.md
docs/Theming.md
docs/Tutorial.md
docs/index.md
packages/ra-core/src/actions/notificationActions.ts
packages/ra-ui-materialui/README.md
packages/react-admin/README.md

[RFR] Fix broken links to material ui v1 documentation

---

packages/ra-core/src/controller/ListController.spec.tsx
packages/ra-core/src/controller/ListController.tsx
packages/ra-core/src/controller/index.ts
packages/ra-core/src/controller/useListController.tsx
packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/ListGuesser.js

It helps remove one level in the component tree for lists, and makes the return type explicit. Also, it's easier to understand.
```jsx
import {useListController } from 'react-admin';
import ListView from './ListView';
const MyList = props => {
const controllerProps = useListController(props);
return <ListView {...controllerProps} {...props} />;
}
```
The `ListController` component remains for backward compatibility, and to be able to test `useListController`. 
There will be more such controllers (`useEditController`, etc) but Rome wasn't built in one day.

[RFR] Add useListController hook

---

packages/ra-ui-materialui/src/layout/MenuItemLink.js

This PR is related to #3390. I forgot to add the `sidebarIsOpen` to the sanitized props before passing them to `@material-ui/core/MenuItem`. Without the fix the prop is passed to a HTML element which causes an unknown-prop warning on the console.

[RFR] Prevents passing the sidebarIsOpen prop to the MenuItem

---

docs/Actions.md
packages/ra-core/package.json
packages/ra-core/src/controller/EditController.tsx
packages/ra-core/src/controller/ListController.tsx
packages/ra-core/src/controller/index.ts
packages/ra-core/src/controller/useEditController.spec.tsx
packages/ra-core/src/controller/useEditController.ts
packages/ra-core/src/controller/useListController.spec.tsx
packages/ra-core/src/controller/useListController.ts
packages/ra-core/src/fetch/Mutation.spec.tsx
packages/ra-core/src/fetch/Mutation.tsx
packages/ra-core/src/fetch/Query.tsx
packages/ra-core/src/fetch/index.ts
packages/ra-core/src/fetch/useMutation.spec.tsx
packages/ra-core/src/fetch/useMutation.ts
packages/ra-core/src/fetch/useUpdate.ts
packages/ra-core/src/util/TestContext.tsx
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/detail/EditGuesser.js
packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/ListGuesser.js

Removes one level of indentation in the React tree for Edit views.
I also introduced a new specialized mutation hook, `useUpdate`. This addresses #2952 for the `crudUpdate` action.
```jsx
import { useEditController } from 'react-admin';
import EditView from './EditView';
const MyEdit = props => {
const controllerProps = useEditController(props);
return <EditView {...controllerProps} {...props} />;
}
```
The only difference between `useEditController` and `EditController` is that the former doesn't inject `translate` (just like for `useListController`).

[RFR] Add useEditController hook

---

examples/demo/src/invoices/InvoiceShow.js
examples/simple/src/comments/index.js
examples/simple/src/posts/PostShow.js
packages/ra-core/src/controller/ShowController.tsx
packages/ra-core/src/controller/index.ts
packages/ra-core/src/controller/useShowController.ts
packages/ra-ui-materialui/src/detail/Show.js
packages/ra-ui-materialui/src/detail/ShowGuesser.js

```jsx
import { useShowController } from 'react-admin';
import ShowView from './ShowView';
const MyShow = props => {
const controllerProps = useShowController(props);
return <ShowView {...controllerProps} {...props} />;
}
```

[RFR] Add useShowController hook

---

examples/simple/src/users/UserCreate.js
packages/ra-core/src/controller/CreateController.tsx
packages/ra-core/src/controller/index.ts
packages/ra-core/src/controller/useCreateController.spec.tsx
packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/fetch/index.ts
packages/ra-core/src/fetch/useCreate.ts
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/detail/Create.js

```jsx
import { useCreateController } from 'react-admin';
import CreateView from './CreateView';
const MyCreate = props => {
const controllerProps = useCreateController(props);
return <CreateView {...controllerProps} {...props} />;
}
```

[RFR] Add useCreateController hook

---

examples/demo/src/layout/Login.js
examples/demo/src/orders/Basket.js
examples/demo/src/reviews/BulkAcceptButton.js
examples/demo/src/reviews/BulkRejectButton.js
examples/demo/src/reviews/ReviewList.js
examples/simple/src/customRouteNoLayout.js
packages/ra-ui-materialui/src/field/ReferenceManyField.js

- Use `makeStyles` on demo
- Use function component
- fix `}` render in ReferenceManyField.js 
Review with "Hide whitespace changes" options in Github

[RFR] Use hooks on demo (last PR)

---

packages/ra-ui-materialui/src/field/EmailField.tsx

Similar to a54acf0152745ebb9bb262ccbec82f2862a3a011.
Let's say we have a user list with an email field.
Without this fix, clicking on the email was redirecting to user/edit
before launching the mailto action.
Now, it just execute the mailto action.

fix(EmailField): prevent click bubbling in a datagrid with rowClick

---

docs/Authentication.md
packages/ra-core/src/actions/clearActions.ts
packages/ra-core/src/actions/index.ts
packages/ra-core/src/createAdminStore.ts
packages/ra-core/src/sideEffect/auth.spec.ts
packages/ra-core/src/sideEffect/auth.ts

[RFR] Delegate the redirection after logout to authProvider

---

docs/Actions.md
docs/_layouts/default.html
examples/simple/src/users/UserEdit.js
packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/controller/useEditController.ts
packages/ra-core/src/controller/useListController.ts
packages/ra-core/src/controller/useShowController.ts
packages/ra-core/src/fetch/index.ts
packages/ra-core/src/fetch/useCreate.ts
packages/ra-core/src/fetch/useDataProvider.ts
packages/ra-core/src/fetch/useDelete.ts
packages/ra-core/src/sideEffect/fetch.ts
packages/ra-core/src/sideEffect/index.ts
packages/ra-core/src/sideEffect/useNotify.ts
packages/ra-core/src/sideEffect/useRedirect.ts
packages/ra-core/src/sideEffect/useRefresh.ts
packages/ra-core/src/sideEffect/useUnselectAll.ts
packages/ra-ui-materialui/src/button/Button.js
packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithUndoButton.js

This is totally backwards compatible - delerative side effect objects are still interpreted by the Redux saga.
Closes #3413. 
This change does not reduce the code in controllers, but makes it more understandable. There are less moving parts, it's more idiomatic to modern React, and it bypasses some of the redux-saga logic.
It allows to customize side effects quite easily, e.g. to display a custom notification message in case of failed HTTP request.
```jsx
const MyEdit = props => {
const editControllerProps = useEditController(props);
const [update, { loading: isSaving }] = useUpdate(
props.resource,
props.id,
{}, // set by the caller
editControllerProps.record
);
const save = useCallback(
(data: Partial<Record>, redirectTo = 'list') =>
update(
null,
{ data },
{
onSuccess: () => { …
```

[RFR] Declare fetch side effects as function

---

docs/_layouts/default.html
docs/css/style.css

Much better UX: autocomplete, section highlighting, and... speed!

[RFR] Switch search engine to Algolia

---

examples/demo/src/reviews/AcceptButton.js
examples/demo/src/reviews/BulkAcceptButton.js
examples/demo/src/reviews/BulkRejectButton.js
packages/ra-core/src/dataProvider/useDataProvider.ts
packages/ra-core/src/dataProvider/useMutation.ts
packages/ra-core/src/dataProvider/useQuery.ts

[RFR] Fix Review accept / reject in demo

---

.github/ISSUE_TEMPLATE/Bug_report.md

Simple thing, but include the CodeSandbox link IN the template and outside of a comment.
That way, it will be more visible and less easy to miss.

[RFR] Improve bug report template

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/SelectInput.js
packages/ra-ui-materialui/src/input/SelectInput.spec.js

To address https://github.com/marmelab/react-admin/issues/3392

Add emptyText prop to SelectInput

---

packages/ra-core/src/controller/ListController.spec.tsx
packages/ra-core/src/controller/ListController.tsx

[RFR] Ensure List Data Update when Default Filters Change

---

docs/Inputs.md
examples/simple/src/posts/PostEdit.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.js
packages/ra-ui-materialui/src/input/ReferenceArrayInput.js

[RFR] Fix AutocompleteArrayInput options

---

packages/ra-ui-materialui/src/list/DatagridHeaderCell.js

[RFR] add check for sortable in shouldUpdate

---

packages/ra-ui-materialui/src/list/Datagrid.js

Fix the remaining warning with the material UI v4 migration.
> Warning: Material-UI: theme.spacing.unit usage has been deprecated.
> It will be removed in v5.
> You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.

[RFR] Fix theme.spacing warning

---

packages/ra-ui-materialui/src/auth/Login.tsx
packages/ra-ui-materialui/src/layout/Notification.js
packages/ra-ui-materialui/src/layout/Notification.tsx

Refs #3453
This PR converts the remaining components from #3461.

[RFR] Replace withStyles with useStyles

---

packages/ra-core/src/actions/dataActions/crudUpdate.ts

related to #2425 
superseed's #2823

[RFR] Trigger refresh after crudUpdate

---

packages/ra-core/src/CoreAdminRouter.spec.tsx
packages/ra-core/src/CoreAdminRouter.tsx

[RFR] check if authProvider is defined

---

packages/ra-ui-materialui/src/input/DateTimeInput.js

We should probably deprecate this Input in favor of the `DateInput` with props

[RFR] Migrate DateTimeInput to use useInput

---

packages/ra-ui-materialui/src/input/SelectInput.spec.tsx
packages/ra-ui-materialui/src/input/SelectInput.tsx

[RFR] Migrate SelectInput to TypeScript

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx

The key prop is missing in the mapping to `CheckboxGroupInputItem` in `choices.map`.  This results in console.warn.  This can be seen in the JavaScript console of simple example app after clicking the Edit on any of the Posts.
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `CheckboxGroupInput`. See https://fb.me/react-warning-keys for more information.
in CheckboxGroupInputItem (created by CheckboxGroupInput)
in CheckboxGroupInput (created by PostEdit)
in div (created by FormInput)
in FormInput (created by WithStyles(FormInput))
in WithStyles(FormInput) (created by FormTab)
in span (created by FormTab)
```

Set key prop on CheckboxGroupInputItem

---

examples/simple/src/comments/CommentCreate.js
examples/simple/src/comments/CommentEdit.js
examples/simple/src/comments/PostQuickCreate.js
examples/simple/src/posts/PostCreate.js
examples/simple/src/posts/PostEdit.js

This is to fix console.warns of `LongTextInput` being deprecated and to use `TextInput` instead in the `examples/simple` app.
To see these error message:
```
make run-simple
// Navigate to http://localhost:8080
// Open the JavaScript console and try to Add a Post
```

[RFR] Change LongTextInput to TextInput in examples/simple

---

examples/demo/src/visitors/VisitorCreate.js
examples/demo/src/visitors/VisitorEdit.js

Changed the two uses of `LongTextInput` in the examples/demo app to `TextInput`.

Change LongTextInput to TextInput in examples/demo app

---

docs/Admin.md
packages/ra-core/src/CoreAdmin.tsx
packages/ra-core/src/createAdminStore.ts

to prevent undefined behaviour
fixes having undefined state instead of new state
ie. if you have some inital data from localStorage, then you dont wanna forget them on logout
and if initialState is function, call it to get the state

[RFR] createAdminStore - set initialState on logout

---

packages/ra-ui-materialui/src/list/SimpleList.js

When `linkType` is set to false, the `ListItems` are still styled as buttons. This seems like undesired behavior for a non-interactive item. Instead, do not style as buttons if linkType is false (or null).
Another solution would be to add a new prop to List to explicitly declare whether ListItems were styled as buttons if there was concern about altering existing behavior.

Fix SimpleList showing ListItem as button even though linkType is false

---

packages/ra-ui-materialui/src/layout/CardContentInner.js

Change to useStyles for ra-ui-materialui `CardContentInner` component

[RFR] Change to useStyles for CardContentInner component

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js
packages/ra-ui-materialui/src/input/ReferenceInput.spec.js
packages/ra-ui-materialui/src/layout/LinearProgress.js

Change from withStyles to useStyles  for ra-ui-materialui's `LinearProgress` component.
Also fixed two tests in `ReferenceInput.spec.js` and `ReferenceArrayInput.spec` by removing the HOC wrap `WithStyles` of `LinearProgress`

[RFR] Change to useStyles for LinearProgress component

---

docs/DataProviders.md
packages/ra-core/src/dataFetchActions.ts
packages/ra-core/src/sideEffect/fetch.ts
packages/ra-data-json-server/src/index.js
packages/ra-data-simple-rest/src/index.js

Ok, I checked for both `DELETE` and `DELETE_MANY` actions.
- `DELETE` doesn't require to have an identifier (`{ data: { id: 'id' } }`) but needs to have a data key, which should be returned by the data provider
- `DELETE_MANY` should return a data as a array, but do not require to have something in that array. If the API doesn't return a response, the data provider will return an empty array
Note : It is possible for the data provider to return the ids or resources sent with the request thanks to the `params` argument, but since react admin does nothing with this data, I preferred to remove not require it.

[RFR] Support API empty response on DELETE and DELETE_MANY actions

---

docs/DataProviders.md
docs/Tutorial.md

[RFR] Fix typos in DataProvider's documentation

---

packages/ra-tree-ui-materialui/src/NodeView.js

Change to useStyles for NodeView component

[RFR] Change to useStyles for NodeView component

---

packages/ra-tree-ui-materialui/src/TreeNode.js

Change to useStyles for TreeNode component

[RFR] Change to useStyles for TreeNode component

---

packages/ra-ui-materialui/src/field/BooleanField.tsx
packages/ra-ui-materialui/src/field/ChipField.spec.js
packages/ra-ui-materialui/src/field/ChipField.tsx
packages/ra-ui-materialui/src/field/FileField.spec.js
packages/ra-ui-materialui/src/field/FileField.tsx
packages/ra-ui-materialui/src/field/ImageField.spec.js
packages/ra-ui-materialui/src/field/ImageField.tsx

ref: #3453 
Converts following components:

[RFR]: use makeStyles in Field Components

---

docs/CreateEdit.md
packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/controller/useEditController.ts
packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/Edit.js

Allow~ changing success message in Create/Edit

[RFR] Create/Edit allow changing success message

---

examples/simple/src/posts/PostList.js
packages/ra-core/src/dataProvider/useGetMany.ts
packages/ra-core/src/reducer/admin/resource/data.ts
packages/ra-ui-materialui/src/layout/Menu.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/DatagridLoading.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/ExpandRowButton.tsx

Various list perf improvements following a profiling sessions.
After an initial render of the datagrid from store, avoids a rerendering of each datagrid row once an unchanged response comes from the dataprovider.
Also, I believe we'll have to support Component injection in some places to avoid forced renders due to the fact that *elements* are always different.

[RFR] List perf improvements

---

examples/simple/src/posts/PostCreate.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Our forms rerender all fields each time one of the values change - this is not good. I'm proposing a better default - having SimpleForm and TabbedForm subscribe only to submissions.

[RFR] Improve form performance

---

packages/ra-tree-ui-materialui/src/DragPreview.js

This is a conversion to `useStyles` but it is the first that I've done that has life-cycle method `shouldComponentUpdate` that just returns `false`.
I did not try to add any memoization because I wouldn't really be understanding whether it worked. Would very much appreciate an explanation how `shouldComponentUpdate` for this seemingly trivial case should be handled.
Thanks!

[RFR] Convert DragPreview component to useStyles

---

packages/ra-tree-ui-materialui/src/RootDropTarget.js

Convert RootDropTarget component to useStyles
- Used React.memo in `export default` to replace `shouldComponentUpdate`

[RFR] Convert RootDropTarget component to useStyles

---

packages/ra-ui-materialui/package.json

Fixes #3597
We export `DeviceTestWrapper` which uses the `css-mediaquery` package but it was a dev dependency

[RFR] Fix css-mediaquery Dependency

---

packages/ra-ui-materialui/src/layout/AppBar.js

Convert AppBar to use useDispatch, useSelector, useWidth.
The `useWidth` was taken from material-ui documentation example: https://material-ui.com/components/use-media-query/#migrating-from-withwidth
Maybe `useWidth` should be defined in `ra-core/src`  whereby it can be exported for other components that need it.
Done by request in #3582

[RFR] Convert AppBar to use useDispatch, useSelector, useWidth

---

packages/ra-ui-materialui/src/list/PaginationActions.js
packages/ra-ui-materialui/src/list/PaginationActions.spec.js

Convert `PaginationActions` to hooks.
This was mostly straightforward conversion done step-by-step (running `make test-unit` at every step). One note though...  I removed the HOC `recompose/pure` along with the non-default export. Using the pure-wrapped component does not pass the `PaginationActions.spec`.   Let me know if I got this wrong.

[RFR] Convert PaginationActions to hooks

---

packages/ra-tree-ui-materialui/src/NodeForm.js

Convert NodeForm component to hooks

[RFR] Convert NodeForm component to hooks

---

packages/ra-ui-materialui/src/layout/MenuItemLink.js

Convert MenuLinkItem component to useStyles. #3453

[RFR] Convert MenuLinkItem component to useStyles

---

packages/ra-ui-materialui/src/list/DatagridBody.js

If hasBulkActions prop changed dynamically, DataGrid renders Checkbox only in the DataGridHeader and doesn't render Checkbox in every row because useMemo ignores this prop change.

Add hasBulkActions to useMemo inputs

---

packages/ra-ui-materialui/src/input/FileInput.tsx

without defined input type as file,
the react-dropzone does not open on click and work's only on drop

[RFR] Fix FileInput - need to define type

---

packages/ra-core/src/CoreAdminRouter.tsx

sometimes when you make error in authprovider, the app just goes into cycle of login and logout
and you don't even know why
so its better to report the error to console, so you can fix the problem

[RFR] CoreAdminRouter - log initializeResources errors

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

Convert ResettableTextField component to useStyles.  #3453

[RFR] Convert ResettableTextField component to useStyles

---

UPGRADE.md
docs/List.md
packages/ra-ui-materialui/src/button/ExportButton.js
packages/ra-ui-materialui/src/button/ExportButton.tsx

As expected in #3623, using the new hooks changes the signature of the `exporter` function, but for the best.
```diff
-const exportComments = (data, fetchRelaterRecords, dispatch) => {
+const exportComments = (data, fetchRelaterRecords, dataProvider) => {
// ...
}
```
This is a small BC break, because using the `dispatch` parameter in the exporter function was really cumbersome, and I doubt anyone has ever used it. 
Also, people wishing to customize the export more deeply (with custom side effects, etc) can easily write their own. Here is the simplified version of the `ExportButton` component:
```jsx
import {
downloadCSV,
useDataProvider,
useNotify,
GET_LIST,
} from 'react-admin';
import jsonExport from 'jsonexport/dist';
const ExportButton = ({ sort, filter, maxResults = 1000, resource …
```

[RFR] [BC Break] Migrate export button

---

docs/Admin.md
docs/Authorization.md
docs/Theming.md
docs/UnitTesting.md
examples/demo/src/configuration/Configuration.js
examples/demo/src/layout/Layout.js
examples/demo/src/layout/Menu.js
packages/ra-core/src/dataProvider/withDataProvider.tsx
packages/ra-core/src/form/withDefaultValue.tsx
packages/ra-ui-materialui/src/button/RefreshButton.js
packages/ra-ui-materialui/src/button/RefreshIconButton.js
packages/ra-ui-materialui/src/button/SaveButton.js
packages/ra-ui-materialui/src/button/SaveButton.spec.js
packages/ra-ui-materialui/src/layout/LoadingIndicator.js

Cleanup PR. These components are the low hanging fruits. The remaining uses of `connect` are harder to migrate.

[RFR] Replace connect by hooks in a few components

---

docs/List.md
packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js
packages/ra-ui-materialui/src/layout/Confirm.js

Closes #3241, #3645
This is a breaking change because it changes the responsibility for the loading state.

[RFR] Fix Confirm dialog loading bug

---

packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/input/Labeled.tsx

[RFR] Fix margins are too small in Show views 

---

packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithUndoButton.js

We must not pass the action payload (the record and its identifier) at the hook declaration time to avoid errors for people using the button in a component which may not have the record loaded immediately (for exemple in the actions of an Edit component)

[RFR] Ensure DeleteButton is usable when record is not defined at mount time

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js

object means it's error's for children so we can ignore it as children will display the errors by themself's
fixes error - passing object to react

[RFR][v3] SimpleFormIterator - don't display error if its object

---

packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
packages/ra-ui-materialui/src/input/NumberInput.tsx

the new version of material-ui in v3 does not pass all props to native input
so the step needs to be passed in inputProps to work

[RFR][v3] NumberInput - step needs to be passed in inputProps

---

docs/Inputs.md
packages/ra-core/src/form/FormDataConsumer.tsx

by default subscribe's to all changes like it is now
but user could change it by passing the subscription prop

[RFR][v3] FormDataConsumer - add subscription prop to the FormDataConsumer

---

docs/List.md
examples/demo/src/layout/Login.js
examples/simple/src/comments/index.js
packages/ra-core/src/controller/input/useGetMatchingReferences.spec.tsx
packages/ra-core/src/controller/usePaginationState.ts
packages/ra-core/src/controller/useShowController.ts
packages/ra-core/src/dataProvider/useGetMany.spec.tsx
packages/ra-core/src/dataProvider/useGetMany.ts
packages/ra-ui-materialui/src/Link.tsx
packages/ra-ui-materialui/src/field/FileField.tsx
packages/ra-ui-materialui/src/field/ImageField.tsx
packages/ra-ui-materialui/src/input/CheckboxGroupInputItem.tsx
packages/ra-ui-materialui/src/list/BulkDeleteAction.js
packages/ra-ui-materialui/src/list/Filter.js
packages/ra-ui-materialui/src/list/FilterButton.js
packages/ra-ui-materialui/src/list/FilterButton.spec.js
packages/ra-ui-materialui/src/list/FilterButtonMenuItem.js
packages/ra-ui-materialui/src/list/SingleFieldList.spec.js

Converted a few more components to hooks, removed linter warnings

[RFR] Code cleanup

---

packages/ra-data-graphql-simple/src/buildGqlQuery.js

This PR simply adds support for `Interface` types.
For example if you have a similar GraphQL schema
```
interface Device {
...    
}
type MotionSensor implements Device {
...    
}
type TemperatureSensor implements Device {
...
}
```
`Device` will then be picked up as a resource.

Support for GraphQL Interface type

---

UPGRADE.md
docs/CustomApp.md
docs/Translation.md
packages/ra-core/src/i18n/TestTranslationProvider.tsx
packages/ra-core/src/i18n/TranslationContext.ts
packages/ra-core/src/i18n/useSetLocale.spec.js
packages/ra-core/src/i18n/useSetLocale.tsx
packages/ra-core/src/i18n/useTranslate.spec.tsx
packages/ra-core/src/i18n/useTranslate.ts
packages/ra-core/src/types.ts
packages/ra-core/src/util/TestContext.tsx
packages/ra-i18n-polyglot/src/index.ts
packages/ra-language-english/README.md
packages/ra-language-french/README.md
packages/ra-tree-ui-materialui/README.md

Refs #3686
```ts
export type I18nProvider = {
translate: Translate;
changeLocale: (locale: string, options?: any) => Promise<void>;
[key: string]: any;
};
```

[RFR] Replace I18nProvider function by object

---

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx
packages/ra-core/src/controller/input/referenceDataStatus.ts
packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
packages/ra-core/src/dataProvider/index.ts
packages/ra-core/src/dataProvider/useGetMatching.ts

[RFR] Introduce useGetMatching and useReferenceArrayInputController

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js
packages/ra-ui-materialui/src/input/ArrayInput.spec.tsx

aka. use same format as FieldTitle to get translated labels in SImpleFormIterator from source without the need to write label's manually

[RFR][v3][BC break] SimpleFormIterator - use resource fields label

---

docs/CreateEdit.md

I put the easy way to do validation first followed by advanced, custom validation methods.
We had custom ``required()`` validators all over our code since that's the first way validation is described in the docs. Hopefully this reordering will help others avoid the extra, custom work when built-in functionality already exists to cover common cases.

[RFR] Docs: Move built-in validators above custom validation

---

packages/ra-core/src/CoreAdminRouter.tsx

to prevent warning about setting state when unmounted, as the component can be unmounted before resolveChildren returns
( happens to me when i load permissions asynchronously )

[RFR][v3] CoreAdminRouter - use useSafeSetState

---

packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js

Fix TabbedForm does not detect errors when source is a path on v2

---

packages/ra-ui-materialui/src/layout/Notification.tsx

the default black font color is hard to see, so use MUI defined contrastText color

[RFR][v3] Notification - fix text color

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx

[RFR] Fix RadioButtonGroupInput and CheckboxGroupInput Error Display

---

packages/ra-ui-materialui/src/list/FilterForm.js
packages/ra-ui-materialui/src/list/FilterForm.spec.js

[RFR] Fix FilterForm Submit

---

packages/ra-core/src/auth/types.ts
packages/ra-core/src/types.ts

Applied discriminated union type for auth actions to make the code more uniform

[RFR] Discriminated union type for auth action

---

packages/ra-ui-materialui/src/layout/Layout.js

Avoids the React warning about deprecated `componentWillReceiveProps`

[RFR] Refactor Layout

---

packages/ra-ui-materialui/src/input/SelectInput.tsx

When using a `SelectInput` inside a `ReferenceInput`, `choices` prop should not be required as this is the job of the `ReferenceInput` to provide them, not the user

[RFR] Fix SelectInput Warnings

---

UPGRADE.md
docs/Admin.md
docs/Translation.md
packages/ra-core/src/CoreAdmin.tsx
packages/ra-core/src/i18n/TestTranslationProvider.tsx
packages/ra-core/src/i18n/TranslationContext.ts
packages/ra-core/src/i18n/TranslationProvider.tsx
packages/ra-core/src/i18n/useTranslate.spec.tsx
packages/ra-core/src/types.ts
packages/ra-i18n-polyglot/src/index.ts

[RFR] i18nProvider - initial locale

---

UPGRADE.md
docs/CreateEdit.md
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/getFormInitialValues.js
packages/ra-ui-materialui/src/form/index.js

Supersedes #3636
Fixes #3627
@natrim I had to rebase it and wasn't able to do it on your fork

[RFR] SimpleForm/TabbedForm - deprecate defaultValue

---

cypress/integration/edit.js
examples/simple/src/posts/PostEdit.js
packages/ra-core/src/form/index.ts
packages/ra-core/src/form/sanitizeEmptyValues.ts
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/input/SelectInput.tsx

Supersedes #3656
Fixes #3551, #3660

[RFR] Fix Forms Remove Empty Values

---

docs/Actions.md

The documentation does not use the right action 'onFailure', it uses 'onError'. So if an exception occurs the notification is never shown.

[RFR] fix doc - dataProvider uses onFailure instead of onError

---

packages/ra-core/src/controller/useListController.spec.tsx
packages/ra-core/src/dataProvider/useMutation.ts
packages/ra-core/src/dataProvider/useQuery.ts
packages/ra-core/src/dataProvider/useQueryWithStore.ts

we need to set loading to true ( like in withMutation ) to support reload
without it the loading is then always false on subsequent re-renders
and withMutation fix loaded being undefined for while

[RFR][v3] useQuery/useQueryWithStore - fix loading state not resetting

---

packages/ra-core/src/CoreAdminRouter.tsx

Fix Welcome message should be visible on narrow screens

---

package.json
packages/ra-core/src/util/fetch.spec.ts
packages/ra-core/src/util/fetch.ts
test-setup.js
yarn.lock

Add Content-Type header only for non GET requests.

---

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx

Change filter extend order in ReferenceInputController

---

UPGRADE.md

[RFR] Add precisions to Upgrade.md

---

examples/simple/src/comments/CommentCreate.js
packages/ra-core/src/controller/input/ReferenceInputController.spec.tsx
packages/ra-core/src/controller/input/useReferenceInputController.ts

[RFR] Fix ReferenceInput Ignore its sort prop

---

packages/ra-core/src/controller/useListParams.ts

Closes #3703 
Proposed solution: refresh local query variable inside `changeParams` (now it uses outdated values from closure).
P.S: This is a sort of ad-hoc solution, but works.

Fix pagination reset after filtering

---

CHANGELOG.md
docs/Inputs.md
packages/ra-input-rich-text/README.md
packages/ra-input-rich-text/src/index.js

- Implementing the changes mentioned in https://github.com/marmelab/react-admin/pull/3653 
- Documenting changes in ra-rich-text-input/README.md
- Documenting changes in docs/Inputs.md
- Requesting pull into `next` branch

Allowing for more fine tuning of Quill without rewriting RichTextInput

---

packages/ra-data-graphcool/src/buildVariables.js
packages/ra-data-graphql-simple/src/buildVariables.js
packages/ra-tree-core/src/getTreeFromArray.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Improved code and fixed 2 potential bugs

Code enhancement: applied sonarqube recommendations

---

docs/List.md
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/index.js

[RFR] Fix Datagrid can't handle dynamic children

---

packages/ra-ui-materialui/src/input/FileInput.js
packages/ra-ui-materialui/src/input/ImageInput.js

Background color for FileInput dropzone is hardcoded.
In dark theme, it still keeps a light background.
With this code, it will use color issued from the theme to be uniform with the rest of the design.
Of course, in light theme, it will use theme colors too.
Before:
After:

feat(file-input): use theme for dropzone background

---

docs/Admin.md
docs/CreateEdit.md
docs/CustomApp.md
examples/demo/src/reviews/ReviewList.js
examples/simple/src/index.js
packages/ra-core/src/auth/Authenticated.spec.tsx
packages/ra-core/src/auth/useAuthenticated.spec.tsx
packages/ra-core/src/auth/useLogin.ts
packages/ra-core/src/auth/useLogout.ts
packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/controller/useListParams.ts
packages/ra-core/src/sideEffect/useRedirect.ts
packages/ra-core/src/types.ts
packages/ra-core/src/util/TestContext.tsx
packages/ra-ui-materialui/src/auth/Login.tsx
packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.js
packages/ra-ui-materialui/src/field/ReferenceArrayField.spec.js
packages/ra-ui-materialui/src/field/ReferenceField.spec.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/form/TabbedForm.spec.js
packages/ra-ui-materialui/src/form/TabbedFormTabs.js
packages/ra-ui-materialui/src/form/TabbedFormTabs.spec.js
packages/ra-ui-materialui/src/layout/Layout.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/DatagridRow.spec.js
packages/ra-ui-materialui/src/list/List.spec.js

As discussed in #3821, the import of routing components 
Not: This is a *partial* fix to #3821 in that it encourages users to import the `react-router-dom` library correctly (making occurrence of the issue less likely).
This PR does not address the other part of a fix, in which `react-router-dom` needs to be a peer dependency.
There's one difficulty here. `react-router`'s `StaticContext` is used in the typing system, but [it's not part of the public API](https://github.com/ReactTraining/react-router/issues/6733), and therefore not re-exported from `react-router-dom`. So I've had to leave that as being from `react-router`, and hope that doesn't defy the point of all this.

Unified imports of routing components to react-router-dom

---

examples/demo/public/index.html
examples/demo/src/orders/OrderList.js
examples/demo/src/reviews/ReviewListDesktop.js
examples/demo/src/visitors/SegmentsField.js
examples/demo/src/visitors/VisitorList.js
examples/simple/src/posts/PostList.js
examples/simple/src/users/UserList.js
packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridLoading.js
packages/ra-ui-materialui/src/list/DatagridRow.js
packages/ra-ui-materialui/src/list/SingleFieldList.js
yarn.lock

Fix Datagrid has no padding when disabling bulk actions

---

packages/ra-data-graphql/src/index.js

Previously custom fetch types which queried data were not supported, only those which mutated data.

Support custom queries in ra-data-graphql

---

packages/ra-core/package.json
packages/react-admin/package.json

Can't update from 3.0.0-beta.0 to 3.0.0-beta.2
```
/app/node_modules/ra-core/esm/util/renderWithRedux.js
Module not found: Can't resolve '@testing-library/react' in '/app/node_modules/ra-core/esm/util'
```
The issue comes from https://github.com/marmelab/react-admin/pull/3763

Add @testing-library/react in peerDep on ra-core packages

---

docs/Show.md

As of material-ui v4, tabs are made scrollable by using `variant="scrollable"`
instead of `scrollable={true}`

Update TabbedForm readme

---

docs/Theming.md
examples/demo/src/layout/AppBar.js

[RFR] Fix custom user menu does not close after selecting an item in the demo

---

packages/ra-input-rich-text/src/index.js
packages/ra-input-rich-text/src/index.spec.js

After migrating to react-final-form the `RichTextInput` is no longer showing the `helperText`. This PR fixes this bug and also converts it into a functional component.

[RFR] Convert RichTextInput to a functional component

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

In general, the clear icon hover background wasn't centered with
the icon itself. Also, on a SelectInput, the clear icon was
overlapping with the select's arrow:
Before:
After:

Tweak ResettableTextField adornment style

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js

The issue:
Now destroyOnUnregister configuration of react-final-form has problem.
If set destroyOnUnregister to true on Form component of react-final-form, the following problems arise.
Of course I can use it wrapped, but I modified it myself cuz I wanted to use SimpleForm that the react-admin provides as it is.
The fixed:
Remove destroyOnUnregister configuration on SimpleForm.
please check and accept my pull request. :)

Fix error occur when use SimpleForm with ArrayInput

---

packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
packages/ra-core/src/dataProvider/useGetMany.ts
packages/ra-core/src/dataProvider/useGetMatching.ts
packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/SelectArrayInput.tsx

[RFR] Fix ReferenceArrayInput does not work in Filters

---

packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

For consistency with other inputs
Should it also default to not being fullWidth ? Or even leverage `ResttableTextInput` to have the same visual aspect ?
Here's a codesandbox showing both side by side: https://codesandbox.io/s/practical-chandrasekhar-869ep

Autocomplete defaults to margin="dense" prop

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

The following error was logged in the console:
`Warning: Material-UI: the key 'selectAdornment' provided to the classes prop is not implemented in ForwardRef(TextField). ...`

Class throw error in ResettableTextField.

---

packages/ra-core/src/core/components.ts
packages/ra-core/src/core/index.ts
packages/ra-core/src/dataProvider/useDataProvider.ts

Fix #3924, #3428 
I spent an hour on the problem. I have no idea why this bug appears, and I don't know why my fix works either. In my opinion, it's a TypeScript bug. :speak_no_evil:

[RFR] Fix missing core constants

---

docs/Translation.md

[RFR] Add documentation for allowMissing Polyglot option

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

Today, when a `SelectInput` is `resettable`, the end adorments prevents clicking on the select arrow on the right to open the dropdown (see https://codesandbox.io/s/intelligent-almeida-24cm2).
I also removed the padding on the right in order to avoid a zone where clicking isn't captured

Fix resettable SelectInput with value doesn't show options on click

---

packages/ra-ui-materialui/src/input/AutocompleteSuggestionList.tsx

Not sure why, but it fixes the problem. Must be a Popper bug in material-ui. 
Closes #3940

[RFR] Fix AutocompleteInput suggestion list placement

---

packages/ra-core/src/form/useSuggestions.spec.ts
packages/ra-core/src/form/useSuggestions.ts
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

[RFR] Fix autocompleteinput allowempty

---

packages/ra-ui-materialui/src/form/TabbedFormTabs.js

validTabPaths needs to contain all valid elements indexed by existence
else conditional tabs leave space and are not considered valid for active tab
problem was that Children.toArray(children) strips them before map so the indexes are different from the rendering Children.map
repo: https://codesandbox.io/s/simple-i0xmz
1) edit post
2) try clicking tabs
3) you will see the index starting at 2
4) and comments not working right

[RFR][V3] TabbedFormTabs - validTabPaths fix index

---

packages/ra-core/src/form/useSuggestions.spec.ts
packages/ra-core/src/form/useSuggestions.ts

if default value is undefined it crashes on String.replace
> useSuggestions.js:77 Uncaught TypeError: Cannot read property 'replace' of undefined
>     at escapeRegExp (useSuggestions.js:77)
>     at useSuggestions.js:91
>     at useSuggestions.js:151
>     at Array.filter (<anonymous>)
>     at useSuggestions.js:150

[RFR][v3] useSuggestions - don't crash on empty value

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx

[RFR] Fix RadioButtonGroupInput label size

---

packages/ra-core/src/dataProvider/useGetMany.ts
packages/ra-core/src/dataProvider/useQueryWithStore.ts

I use useGetManyReference to get referenced data.
```
const { data, ids, error, loaded } = useGetManyReference(
"decks",
"branchId",
branch.id,
{ page: 1, perPage: 200 },
{ field: "id", order: "ASC" },
{},
"branches"
);
```
When get fails at first call I got this log (from last render):
```
data: undefined, error: Error: ra.notification.data_provider_error, loading: false, loaded: false
```
In this case we show error text because data is undefined and error is present.
When get fails after some success calls before I got this log (from last render):
```
data: [object Object], error: Error: ra.notification.data_provider_error, loading: false, loaded: true
```
In this case we show error text, because error is present. Even if data is present and loaded is true, because this data may be …

useQueryWithStore and useGetMany returns error: null when success after firs fail

---

docs/CreateEdit.md

[RFR] Fix Field in form does not like the variant prop

---

packages/ra-ui-materialui/src/input/ResettableTextField.js

[RFR] Fix SelectInput variant="standard" shows warning for unknown class

---

packages/ra-ui-materialui/src/auth/LoginForm.tsx

Fix this:
Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?
in div (created by FormControl)
in FormControl (created by WithStyles(FormControl))
in WithStyles(FormControl) (created by TextField)
in TextField (created by renderInput)
in renderInput (created by ConnectedField)
in ConnectedField (created by Connect(ConnectedField))
in Connect(ConnectedField) (created by Field)
in Field (created by LoginForm)
in div (created by LoginForm)
in div (created by LoginForm)
in form (created by LoginForm)
in LoginForm (created by Form(LoginForm))
in Form(LoginForm) (created by Connect(Form(LoginForm)))
in Connect(Form(LoginForm)) (created by ReduxForm)
in ReduxForm (created by Connect(ReduxForm))
in Connect(ReduxForm) (created by Context.Consumer)
in …

Fix typo, autocomplete to autoComplete

---

docs/List.md

Following the discussion in #3725

📚 [documentation] list Pagination props

---

docs/List.md
packages/ra-ui-materialui/src/layout/Confirm.js

This has been discussed and apparently abandoned at #3471

Add custom icons for Confirm action buttons.

---

docs/Theming.md

Fix wrong syntax in custom menu example

---

packages/ra-core/src/util/escapePath.ts
packages/ra-core/src/util/index.ts
packages/ra-ui-materialui/src/detail/TabbedShowLayout.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Fix TabbedForm and TabbedShowLayout do not support parenthesis in id

---

packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/TabbedForm.js
packages/ra-ui-materialui/src/list/DatagridLoading.js

Patch prop types missing.

---

docs/Inputs.md
packages/ra-core/src/form/useSuggestions.spec.ts
packages/ra-core/src/form/useSuggestions.ts
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx

Following https://github.com/marmelab/react-admin/pull/2912 and fixes https://github.com/marmelab/react-admin/issues/2311.
In React-admin 3, it's not possible to have duplicated values anymore for the `AutocompleteArrayInput`. However it could be useful to allow this behavior in some cases.

[RFR] Add allowDuplicates for AutocompleteArrayInput

---

packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
packages/ra-core/src/dataProvider/defaultDataProvider.ts

Some time ago, we added an optimization to avoid refetching already selected items each time a new item is selected. This is fine, except that we need to grab the already selected items from the store to get their option text...
closes #4021

Fix AutocompleteArrayInput inside ReferenceArrayInput

---

packages/ra-core/src/controller/field/ReferenceManyFieldController.spec.tsx
packages/ra-core/src/controller/useEditController.spec.tsx
packages/ra-core/src/controller/useListController.spec.tsx
packages/ra-core/src/dataProvider/Mutation.spec.tsx
packages/ra-core/src/dataProvider/Query.spec.tsx
packages/ra-core/src/dataProvider/useGetMany.spec.tsx
packages/ra-core/src/dataProvider/useMutation.spec.tsx
packages/ra-core/src/reducer/admin/index.ts
packages/ra-core/src/reducer/admin/references/index.ts
packages/ra-core/src/reducer/admin/resource/list/index.ts
packages/ra-ui-materialui/src/field/ImageField.spec.js
packages/ra-ui-materialui/src/field/ReferenceField.spec.js
packages/ra-ui-materialui/src/input/NullableBooleanInput.spec.tsx
packages/ra-ui-materialui/src/list/List.spec.js
packages/ra-ui-materialui/src/list/Pagination.spec.js

I removed almost all errors in unit tests. I don't understand the last one, that we can leave for now.

Fix console errors in tests

---

docs/Fields.md
packages/ra-ui-materialui/src/field/BooleanField.spec.js
packages/ra-ui-materialui/src/field/BooleanField.tsx

Replace hidden text in BooleanField by tooltip

---

cypress/integration/create.js
examples/simple/src/posts/PostCreate.js
packages/ra-ui-materialui/src/form/SimpleFormIterator.js
packages/ra-ui-materialui/src/input/ArrayInput.tsx

Fix ArrayInput validation

---

packages/ra-ui-materialui/src/list/Datagrid.js
packages/ra-ui-materialui/src/list/DatagridBody.js
packages/ra-ui-materialui/src/list/DatagridRow.js

`DatagridRow` components of a `<Datagrid/>` will show a checkbox if `canSelectRow` prop returns true.
Solves the select all problem described here: https://github.com/marmelab/react-admin/issues/3470#issuecomment-551280562.
```jsx
<Datagrid
{...props}
canSelectRow={ record => record.id > 300 } 
>
...
</Datagrid>
```

[RFR] Added canSelectRow function prop to Datagrid component.

---

packages/ra-core/src/form/sanitizeEmptyValues.spec.ts
packages/ra-core/src/form/sanitizeEmptyValues.ts

Fix Form breaks when setting undefined value to object

---

packages/ra-ui-materialui/src/layout/LoadingIndicator.js

Please double-check as I may be doing a mistake.
I haven't been able to use `isLoading`, according to `<CircularProgress />` [documentation](https://material-ui.com/api/circular-progress/), the `props.isLoading` is not used by mui nor `<LoadingComponent />`

fix(LoadingIndicator): remove unused isLoading props (https://material-ui.com/api/circular-progress/)

---

UPGRADE.md

Fix missing mention about AUTH_GET_PERMISSIONS in Upgrade guide

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Closes #4093 for `AutocompleteInput` and `AutocompleteArrayInput`
Now, these two inputs work like all the other components and accept a `fullWidth` property.
To enable fullWith on `AutocompleteInput`:
- When used standalone, add the `fullWidth` attribute to the `AutocompleteInput`:
```jsx
<AutocompleteInput
source="foo"
choices={[
{ id: 1, name: 'foo' },
{ id: 2, name: 'bar' },
]}
fullWidth
/>
```
- When used inside a `ReferenceInput`, set the `fullWidth` prop on the `ReferenceInput`:
```jsx
<ReferenceInput source="post_id" reference="posts" fullWidth>
<AutocompleteInput optionText="title" />
</ReferenceInput>
```

Fix fullWidth support on AutoCompleteInput

---

packages/ra-core/src/controller/input/useReferenceArrayInputController.ts

Fix regression in ReferenceArrayInput (idsToGetFromStore error)

---

cypress/integration/list.js
packages/ra-ui-materialui/src/input/BooleanInput.tsx
packages/ra-ui-materialui/src/list/FilterFormInput.js

Closes #4091
`FilterFormInput` used to decorate Input components with `Field`, which is not necessary since every Input component has to do the decoration themselves. Also, this double decoration made `checked` computation by final-form fail.

Fix FilterForm doesn't use default values for BooleanInput

---

packages/ra-core/src/form/sanitizeEmptyValues.spec.ts
packages/ra-core/src/form/sanitizeEmptyValues.ts

Fix form values sanitization messes with JSON values

---

docs/Inputs.md

`fullWith` -> `fullWidth` on docs

Fix typo in documentation

---

packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/controller/useEditController.ts
yarn.lock

`useCreateController` accepts a onSuccess and a onFailure props, but `useEditController` don't
So, I made this PR to have the same behavior for both of them

[RFR] Allow to extend useEditController

---

docs/List.md
packages/ra-ui-materialui/src/list/Pagination.js
packages/ra-ui-materialui/src/list/PaginationActions.js

Make pagination more extendable

---

packages/ra-ui-materialui/src/form/FormTab.js
packages/ra-ui-materialui/src/form/FormTab.spec.js
packages/ra-ui-materialui/src/form/SimpleForm.js
packages/ra-ui-materialui/src/form/SimpleForm.spec.js
packages/ra-ui-materialui/src/form/TabbedForm.js

Fix Input elements ignore variant prop

---

packages/ra-ui-materialui/src/input/RadioButtonGroupInput.spec.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx

fix RadioButtonGroupInput onChange props

---

packages/ra-ui-materialui/src/field/ReferenceField.js

Closes #4124
The bug is a bit tricky: FormInput decorates Field components with Labeled, passing them their props. Then, it renders the Field, passing them the `record`. 
```jsx
export const FormInput = ({ input, classes: classesOverride, ...rest }) => {
const classes = useStyles({ classes: classesOverride });
return input ? (
<div
className={classnames(
'ra-input',
`ra-input-${input.props.source}`,
input.props.formClassName
)}
>
{input.props.addLabel ? (
<Labeled
id={input.props.id || input.props.source}
{...input.props}
{...sanitizeRestProps(rest)}
>
{React.cloneElement(input, {
className: classnames(
{
[classes.input]: !input.props.fullWidth,
},
input.props.className
),
id: input.props.id || input.props.source,
...rest,
})}
</Labeled>
) : (
React.cloneElement(input, {
className: …
```

Fix ReferenceField when used inside form

---

docs/Inputs.md

Fix deprecated useField documentation

---

UPGRADE.md

Fix upgrade guide misses redux-saga version requirement

---

docs/List.md

Fix cellClassName shortcoming isn't documented

---

packages/ra-core/package.json
packages/ra-data-json-server/package.json
packages/ra-data-simple-rest/package.json
yarn.lock

Fix duplicate query-string package

---

docs/Inputs.md

By default using `allowEmpty` on `SelectInput` will add a choice with `''` as value and not `null`.

[RFR] [Doc] `emptyValue` prop is `''` by default on `SelectInput`

---

docs/List.md
docs/Translation.md
packages/ra-language-english/index.js
packages/ra-language-french/index.js
packages/ra-ui-materialui/src/list/Empty.js
packages/ra-ui-materialui/src/list/EmptyState.js
packages/ra-ui-materialui/src/list/List.js
packages/ra-ui-materialui/src/list/List.spec.js

[RFR] Invite to create the first record

---

docs/Tutorial.md

Instead of globally installing `create-react-app` with npm we can use [Yarn's create command](https://yarnpkg.com/lang/en/docs/cli/create/) to do this.
Yarn is already assumed to be installed since it's used in the next step.
Create React App has also [written that globally installing it is not supported](https://create-react-app.dev/docs/getting-started#quick-start) any more and `npx` or `yarn create` should be used instead.
Read more about `yarn create` here: https://yarnpkg.com/lang/en/docs/cli/create/

docs: use Yarn create command in tutorial

---

packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx

- Dropping the required flag since a default value is provided when destructuring. Proptypes complains when component is child of a `ReferenceArrayInput` component.
- Pull out loaded attribute from `rest` to avoid fieldet from complaining. 
`index.js:1375 Warning: Received `true` for a non-boolean attribute "loaded".`

Fix remove props warnings in CheckboxGroupInput 

---

docs/Reference.md
docs/Theming.md
packages/ra-ui-materialui/src/auth/Logout.tsx

**Goal**
For an admin web application I'm building I have applied quite some theming to the default `react-admin` layout and style. A bit of work, but it is supported quite well and also documented surprisingly well.
I wanted to use a different icon for the logout button. By default it uses the `<ExitIcon />` (power symbol). I personally prefer using a different icon to represent the logout action in applications: `<ExitToAppIcon/>`.
With help of the documentation I found that it was only possible to achieve this by using a completely custom login button component. So I copied the source of the original `Logout` component and I changed the icon in my application. All good! But not great.
**Motivation**
The `Logout` component contains quite a bit of logic. All this logic is now in my …

[RFR] Add icon props to Logout component

---

packages/ra-core/src/i18n/translate.tsx

fix #4208 
In translate hoc prevent component props to overrides injected translate and locale.

Fix withTranslate HOC uses defualt translate prop instead of the one from context

---

packages/ra-ui-materialui/src/layout/DashboardMenuItem.js
packages/ra-ui-materialui/src/layout/Menu.js

**Issue**
When I was applying custom styling to the sidebar menu, I noticed that the `Dashboard` menu item didn't always have the same styling as the other menu items.
**Cause**
When looking in detail, I discovered that the regular menu items dynamically get a `dense` value set, but that the `DashboardMenuItem` doesn't get this value. Besides that it configures the `dense` prop to always be true.
**Changes described**
I modified the `DashboardMenuItem` so it doesn't configure the `dense` prop itself, but it instead relies on the props passed. I changed the `Menu` so it passes the `dense` prop to the `DashboardMenuItem` just like it does for the other menu items.

[RFR] Also pass the dense prop from the Menu to the DashboardMenuItem

---

packages/ra-ui-materialui/src/detail/Create.js
packages/ra-ui-materialui/src/detail/Edit.js
packages/ra-ui-materialui/src/detail/Show.js

Sanitize translate props injected by the controller components inside views

---

examples/demo/src/layout/Login.tsx
packages/ra-core/src/controller/useCreateController.ts
packages/ra-core/src/controller/useListController.ts
packages/ra-ui-materialui/src/layout/NotFound.js
packages/ra-ui-materialui/src/list/List.js

Update remaining places where location is passed in to ignore/handle it but use `useLocation` hook instead.

Remove required location property

---

docs/Theming.md

I think that the userMenu prop for the custom AppBar MyAppBar should be passed as a component, or it will trigger an "Error: Element type is invalid"

[RFC] Theming documentation: MyUserMenu passed as component

---

docs/CreateEdit.md

Updated the example of useCreate, if you use just data, no data will be sent to the backend.

Fix typo in CreateEdit.md missing payload key in create call.

---

packages/ra-core/src/core/CoreAdminContext.tsx
packages/ra-core/src/i18n/TranslationProvider.tsx
packages/ra-ui-materialui/src/layout/Title.js

It doesn't seem like SSR is supported, and the process is complicated when it involves data fetching. Maybe it will never be supported out of the box, but I'm hoping I can make some changes to make it possible with a custom setup.
These are two small changes just to allow rendering to be successful server side (even though data is incomplete).
- `ConnectedRouter` interferes with `StaticRouter` and can just be ignored server side.
https://github.com/supasate/connected-react-router/pull/322
- `Title` component was assuming `document` exists. Now it just silently fails, which is the same as not finding the `#react-admin-title` container. 
What we really need here is a portal implementation that works server side. There's some POCs for this, but they are just that. I'm still thinking about a …

Small fixes for SSR

---

packages/ra-core/src/reducer/admin/resource/data.spec.ts
packages/ra-core/src/reducer/admin/resource/data.ts
packages/ra-core/src/reducer/admin/resource/list/ids.spec.ts
packages/ra-core/src/reducer/admin/resource/list/ids.ts

fixes #4245, #3727, #3227 
To fix the issue, I add to change the reducer so as to never remove data not impacted by an action even if it is outdated.
For example a GET_ONE would update the other items of the same resources removing all outdated value.
Same for GET_REFERENCE_MANY that would replace all the previous items.
The issue is that if we display an edit form along the list.
Then by opening this edit form (that trigger a GET_ONE) Then this GET_ONE would remove all items except the edited one as well as all reference linket to these items
As an added bonus, now if we are on an edit page and return on the list after the cache has expired: The old list will first be displayed, before fetching the new data and if the data did not change, we get no rerender. As opposed to displaying the …

Fix cache timeout reload list

---

packages/ra-core/src/controller/useListController.ts
packages/ra-core/src/controller/useListParams.ts
packages/ra-core/src/controller/useRecordSelection.ts

Ensure resource data in redux store is initialized bebfore using it.

---

packages/ra-ui-materialui/src/layout/DashboardMenuItem.tsx
packages/ra-ui-materialui/src/layout/Menu.tsx
packages/ra-ui-materialui/src/layout/MenuItemLink.tsx

I wanted to make an addition to the Menu component, when going into the source I discovered that it was still written in JavaScript and not yet converted to TypeScript. Therefore I have now first converted the existing component to TypeScript. Later a pull request will follow with an addition to the Menu.
I converted the Menu and its MenuItem and DashboardMenuItem child components to TypeScript. The functionality and interfaces have stayed the same.

[RFR] Convert the Menu, MenuItem and DashboardMenuItem to TypeScript

---

docs/Inputs.md

Fixes linting issues of https://github.com/marmelab/react-admin/pull/4274
`{% raw %}` should not be surrounded by blank lines because it ruins the readability.

Improve the readability of the Input documentation

---

packages/ra-ui-materialui/src/layout/NotFound.js

This could happend from `RoutesWithLayout.tsx`.
```jsx
...
<Route
render={routeProps =>
createElement(catchAll, {
...routeProps,
title,
})
}
/>
...

Fix warning on catchall page due to improper sanitization in <NotFound> component.

---

packages/ra-ui-materialui/package.json
yarn.lock

#3812 introduced PropTypes.elementType, which is only available as of prop-types 15.7. We need to update the version required by ra-ui-material-ui to avoid an error.
Closes #4283

Fix error in Confirm due to bad prop-types package version

---

docs/DataProviders.md
packages/ra-core/src/dataProvider/useDataProvider.spec.js
packages/ra-core/src/dataProvider/useDataProvider.ts
packages/ra-core/src/dataProvider/useDataProviderWithDeclarativeSideEffects.ts
packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.js
packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx

Add explicit error in useDataProvider hook when the dataProvider throws a sync error

---

packages/ra-ui-materialui/src/list/DatagridLoading.js
packages/ra-ui-materialui/src/list/Placeholder.tsx
packages/ra-ui-materialui/src/list/SimpleList.js
packages/ra-ui-materialui/src/list/SimpleListLoading.tsx
packages/ra-ui-materialui/src/list/index.js

It adapts depending on :
- left/right icon/avatar is specified 
- secondary or tertiary text is specified.

SimpleList Skeleton for First Load

---

docs/CreateEdit.md

📝 update doc about prefilled forms

---

docs/Theming.md
packages/ra-core/src/actions/notificationActions.ts
packages/ra-core/src/sideEffect/useNotify.ts

Notification component autoHideDuration prop not being used.

---

packages/ra-ui-materialui/src/layout/Sidebar.js

Closes #4304
Before:
After:
Note: The fact that the menu items look smaller is due to [a change in material-ui 4.5](https://github.com/mui-org/material-ui/pull/17332) (that I consider a regression, but that's their call...).

Fix Menu overlapps the AppBar with material-ui > 4.8

---

packages/ra-core/src/core/CoreAdminUI.tsx

All "required" props had default values, which means they aren't required.

Fix types on CoreAdminUI

---

packages/ra-core/src/controller/input/useGetMatchingReferences.ts

Fix #4313
The `useGetMatchingReference` hook has an unused property: `filter`. So I just remove it.

Remove the unused filter prop which in useGetMatchingReference

---

docs/CustomApp.md

Fix missing basePath prop in Custom App doc

---

docs/FAQ.md

Fix outdated mention of aor-dependent-input in the FAQ

---

docs/List.md

The previous version of example in documentation was not actual and didn't work in version 3+. I spent an hour to understand it, make a research and get the code from sources. I hope it will help community.

Updated an example custom "actions" of component List

---

packages/ra-core/src/controller/useEditController.ts

Like useCreateController does.
This is useful when you decorate form components and override their submit handler.

Ensure useEditController specifies a default redirect to its caller 

---

UPGRADE.md

Fix upgrade documentation about form handling

---

packages/ra-data-graphcool/README.md
packages/ra-data-graphql-simple/README.md

I was reading the docs and found this typo.

Fix typo in ra-data-graphcool and ra-data-graphql-simple README's.

---

packages/ra-core/src/controller/input/index.ts

This will avoid duplication in addons related to references.
@fzaninotto Should I target the `next` branch ?

Export Reference Utilities

---

packages/ra-ui-materialui/src/list/DatagridHeaderCell.js

Fix Datagrid column headers don't update sort indicator when used in ReferenceManyField

---

cypress/integration/create.js
examples/demo/src/ra-input-rich-text.d.ts
packages/ra-input-rich-text/src/index.js
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
packages/ra-ui-materialui/src/input/BooleanInput.tsx
packages/ra-ui-materialui/src/input/CheckboxGroupInput.spec.tsx
packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
packages/ra-ui-materialui/src/input/DateInput.tsx
packages/ra-ui-materialui/src/input/DateTimeInput.tsx
packages/ra-ui-materialui/src/input/FileInput.tsx
packages/ra-ui-materialui/src/input/InputHelperText.spec.tsx
packages/ra-ui-materialui/src/input/InputHelperText.tsx
packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx
packages/ra-ui-materialui/src/input/NumberInput.tsx
packages/ra-ui-materialui/src/input/RadioButtonGroupInput.tsx
packages/ra-ui-materialui/src/input/TextInput.tsx

This PR makes the helper text space always reserved in forms inputs (even if there isn't any error or help text). This prevent forms to change height brutally upon validation, and the submit buttons to move under the mouse pointer.
Forms will be a bit taller than before with this change

Fix Helper place on Inputs to avoid clipping/unclipping Forms

---

docs/Theming.md
packages/ra-ui-materialui/src/auth/Login.tsx

Replace default unsplash image for Login component by a simple gradient.
Demo login is unchanged.
Preview:

Reduce the default app weight by removing the image background on the Login screen

---

docs/Inputs.md
examples/simple/src/comments/CommentEdit.js
packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx
packages/ra-ui-materialui/src/input/AutocompleteInput.tsx

Closes #4281
When an autocomplete use a custom Component as `optionText`, The selected value can't be display in the filter TextField.
When you want to pass a custom component as `optionText` to an Autocomplete, 
you also have to pass a text rendering function returning the filter text to be displayed for your custom component
This `inputText` function must return a `string` which can be similary to the displayed component, or totally different
```jsx
const OptionRenderer = ({ record }) => (
<span>
{record.title}-{record.id}
</span>
);
const inputText = record => `${record.title}-${record.id}`;
<AutocompleteInput
matchSuggestion={(filterValue, suggestion) => true}
optionText={<OptionRenderer />}
inputText={inputText}
options={{ fullWidth: true }}
/>
```

Fix Autocomplete selection display with custom Component

---

packages/ra-ui-materialui/src/input/InputHelperText.tsx
packages/ra-ui-materialui/src/list/FilterFormInput.js

Fix FilterForm layout broken by bottom margin on Inputs

---

packages/ra-ui-materialui/src/layout/Layout.js

Right now, it's not possible to target the `Layout` component via a custom theme.
This PR aims to fix that, thus making code like the following work:
```jsx
const theme = createMuiTheme({
overrides: {
RaLayout: {
root: {
display: 'contents'
},
appFrame: {
marginTop: '5rem'
}
}
}
});
export default function Home() {
return (
<Admin theme={theme}>
{/* your Resources here */}
</Admin>
);
}
```
Otherwise, you would need to create a custom `<Layout />` component using `withStyles()` to merge the changes and pass this custom component to the `<Admin />` component.

[RFR] Add `name` property to Layout

---

examples/demo/src/layout/themes.ts

React-admin Demo is not lisible in dark theme due to bad constrast
Closes #4180 
Change main color to be lighter in demo custom theme

Enhance dark theme contrast in demo

---

cypress/integration/create.js
cypress/support/CreatePage.js
packages/ra-input-rich-text/src/index.js
packages/ra-ui-materialui/src/button/SaveButton.spec.tsx
packages/ra-ui-materialui/src/button/SaveButton.tsx
packages/ra-ui-materialui/src/input/ReferenceInput.tsx

Closes #4170 
- The Create or Edit Forms can now be validated with a click or with the Enter key
- The helperText place is reserved for all inputs to ensure the Save button won't move down if a requirement text fires at validation.
- It's possible to disable this default helperText by adding helperText={false} on inputs
- The ReferenceInputs in Filters won't have a bad margin anymore.
- ReferenceInput doesn't accept an helperText value, it should be set on the child component

Fix saveOnEnter : Use normal click on Save button and fix helperText linked issue 

---

cypress/integration/edit.js
examples/simple/src/dataProvider.js
packages/ra-core/src/controller/useEditController.ts

Fix the Refresh of Lists when an optimistic update fails

---

packages/ra-ui-materialui/src/input/BooleanInput.tsx

Closes #4424 
Adding disabled property in BooleanInput component must disable it.
But this prop is ignored
Add disabled prop to BooleanInput

Add support for disabled prop in BooleanInput

---

packages/ra-core/src/core/RoutesWithLayout.spec.tsx
packages/ra-core/src/form/FormDataConsumer.spec.tsx
packages/ra-core/src/form/FormField.spec.tsx
packages/ra-ui-materialui/src/button/CloneButton.spec.tsx
packages/ra-ui-materialui/src/detail/SimpleShowLayout.spec.js
packages/ra-ui-materialui/src/field/FunctionField.spec.js
packages/ra-ui-materialui/src/field/ReferenceManyField.spec.js
packages/ra-ui-materialui/src/input/ReferenceArrayInput.spec.js
packages/ra-ui-materialui/src/layout/Responsive.spec.js
packages/ra-ui-materialui/src/list/DatagridCell.spec.js
packages/ra-ui-materialui/src/list/PaginationActions.spec.js
packages/ra-ui-materialui/src/list/SingleFieldList.spec.js
test-setup.js

This PR migrates to react-testing-library all test cases that still use enzyme.
TODO

[RFR] Migrate tests to react-testing-library

---

packages/ra-ui-materialui/src/list/SimpleList.js

You get an error using `<SimpleListLoading>` component :
```
Material-UI: the key `link` provided to the classes prop is not implemented in undefined.
You can only override one of the following: primary,tertiary. 
in SimpleListLoading (created by SimpleList)
in SimpleList (at licencia.js:61)
in LicenciaList (created by WithPermissions)
in WithPermissions (created by Router.Consumer)
in Router.Consumer (created by Route)
in Route (created by ResourceRoutes)
in ResourceRoutes (created by Resource)
in Resource (at App.js:47)
in App (at src/​index.js:7)`
`link` style is defined in `<SimpleList>`

Fix <SimpleListLoading> `link` style is not implemented error.

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js
packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.js

Closes #2489
Closes #3249
When we use the `SimpleFormIterator` inside an array of scalar values (`ArrayInput`) displayed as `TextInput`, the famous `[Object object]` value is displayed on "+ Add" click. 
Example:
```
import { SimpleFormIterator } from "react-admin";
/* recipients = ["foo@bar.com", "bar@foo.com", ....] */
<ArrayInput source="recipients">
<TextInput />
</ArrayInput>
```
Results to:
So, to avoid this, we should inject `undefined` instead of an empty `{}`.
Here is a temporary workaround for those who are having the same problem:
```
import React from "react";
import { SimpleFormIterator } from "react-admin";
export const SimpleFormIteratorWithUndefinedDefault = props => {
const originPush = props.fields.push;
props.fields.push = data …
```

Fix Default SimpleFormIterator Push Value

---

docs/Fields.md
packages/ra-ui-materialui/src/field/ArrayField.tsx
packages/ra-ui-materialui/src/field/types.ts

**Is your feature request related to a problem? Please describe.**
using JSON.stringify results with a very large key. Passing a fieldKey when available reduces the overhead

Add fieldKey prop to <ArrayField> to improve performance on large arrays

---

docs/Inputs.md

Add documentation for use of Fields inside SimpleFormIterator

---

docs/Inputs.md
packages/ra-ui-materialui/src/input/ReferenceInput.tsx

I believe the `filterToQuery` prop on [`ReferenceInput`](https://marmelab.com/react-admin/Inputs.html#referenceinput) is passed onto the children prop as `setFilter`, as the doc states in this section:
> The child component receives the following props from \<ReferenceInput\>:
> - setFilter: function to call to update the filter of the request for possible values
This seems to only matter to the [`AutocompleteInput`](https://marmelab.com/react-admin/Inputs.html#autocompleteinput). But the examples all use a [`SelectInput`](https://marmelab.com/react-admin/Inputs.html#selectinput), which (as far as I'm aware) doesn't do anything with it. Correct me if I'm wrong, but I guess it was meant to be using an `AutocompleteInput` instead.

Doc: Use AutocompleteInput instead of SelectInput in filterToQuery examples 

---

cypress/integration/list.js
packages/ra-core/src/actions/listActions.ts
packages/ra-core/src/controller/useListController.ts
packages/ra-core/src/controller/useListParams.ts
packages/ra-core/src/reducer/admin/resource/list/queryReducer.spec.ts
packages/ra-core/src/reducer/admin/resource/list/queryReducer.ts
packages/ra-ui-materialui/src/list/FilterButton.js
packages/ra-ui-materialui/src/list/FilterForm.js

Closes #4308 
Displayed filters were lost when reloading a page because nothing was keeping information through user navigation
Keep list of displayed filters in url, next to filters value. This allow to separe value of values and presence of filters

Fix to keep displayed filters through navigation, even if they are empty

---

packages/ra-ui-materialui/src/input/SelectInput.tsx

By default, the empty option in SelectInput has a very small height and is barely clickable. This PR fixes this problem. 
Before
After

Fix empty item option height in SelectInput

---

packages/ra-ui-materialui/src/list/FilterForm.js

Filter form inputs didn't appear at the same height whether the form contained a search input or not. This PR fixes it. 
These 4px make a huge difference, believe me.

Fix filter form inputs appear too high when there is no search input

---

packages/ra-ui-materialui/src/list/FilterFormInput.js

Issue introduced by the persistency of the empty filters that was implemented.
defaultValue of a FormInput can be set by mistake if this situation :
- Add a displayed filter containing a defaultValue in your list
- Clean it's value (but don't remove the filter)
- Navigate elsewere
- Come back in the initial list
=> The defaultValue has been set again, and the filter is "un-removable"
Ignore defaultValue in Field because it is always set at Form level
https://github.com/final-form/react-final-form/issues/387

Fix override of defaultValue in FormInput

---

packages/ra-ui-materialui/src/list/PaginationActions.js

this PR will change the chevron direction in PaginationActrions for RTL, as in the gist suggested in #3348. But using hooks to get the theme.

Fix pagination buttons are in the wrong direction in RTL languages

---

packages/ra-input-rich-text/package.json

Hi there,
Thank you for such a nice library!
I don't know too much about lerna but I learnt that for the build to work I
need to add a dependency from ra-input-rich-text to ra-ui-materialui. 
I don't know if this is exactly the right thing to do, but I'd appreciate any feed back.
Regards
`npm run build` fails on a fresh checkout
Cannot find module **'ra-ui-materialui** when building **ra-input-rich-text**
```
> ra-input-rich-text@3.2.0 build C:\dev\oss\react-admin\packages\ra-input-rich-text
> yarn run build-cjs && yarn run build-esm
yarn run v1.15.2
$ rimraf ./lib && tsc
src/index.tsx(11,33): error TS2307: Cannot find module 'ra-ui-materialui'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
at …
```

Fix build of ra-input-rich-text

---

docs/Theming.md
packages/ra-ui-materialui/src/layout/AppBar.js

[RFR] Add color prop to AppBar

---

packages/ra-ui-materialui/src/input/ReferenceArrayInput.js
packages/ra-ui-materialui/src/input/ReferenceInput.tsx
packages/ra-ui-materialui/src/input/SelectInput.tsx
packages/ra-ui-materialui/src/list/FilterForm.spec.js
packages/ra-ui-materialui/src/list/FilterFormInput.js

Closes #4499 
FilterFormInput has always allowEmpty=true despite of input props
We should allow to have filter not emptiable.

Add support for allowEmpty=false in Filter Inputs

---

cypress/integration/edit.js
cypress/integration/list.js
cypress/support/EditPage.js
examples/simple/src/posts/PostEdit.js
examples/simple/src/posts/TagReferenceInput.js
packages/ra-core/src/controller/input/ReferenceArrayInputController.spec.tsx
packages/ra-core/src/controller/input/useReferenceArrayInputController.ts

Closes #4466 
When you change the filter of a ReferenceArrayInput and reset its selected value using useForm hook, the previous selected value is always proposed in the list.
Limit ReferenceArrayInput proposed list to: 
- effectively selected values
- matching values

Fix ReferenceArrayInput list when filter is changed

---

packages/ra-data-graphcool/README.md

Linked #2174 
Client in never used in the example in graphcool
(Same as previously in graphql-simple)

Fix useless line in ra-data-graphcool readme

---

docs/navigation.html

I often found hard to find intuitivelly the `<Field> Components` menu item since is in between the items of the main views.
```
Before:
<List> View
<Show> View
<Field> Components
<Create> and <Edit> Views
<Input> Components
...
After:
<List> View
<Show> View
<Create> and <Edit> Views
<Field> Components
<Input> Components
...

[RFR] Change docs menu Fields item order with Create and Edit item.

---

packages/ra-ui-materialui/src/form/SimpleFormIterator.js

A warning 
> Each child in a list should have a unique "key" prop
inside CssTransition shows if a record with none empty array input was loaded, and the animation of adding a new element is broken.
It can be reproduced using any resource with ArrayInput and SimpleFormIterator:
1. Open Edit for some record
2. Add few items to an array input
3. Save
4. Open Edit for that record again and see a warning
5. Add few more elements to the array input and see broken animation
For example you can add this input to the CategoryEdit form in the demo app:
```
import { ArrayInput, SimpleFormIterator } from 'react-admin';
...
<ArrayInput label="Test array" source="test">
<NumberInput
source="weight"
label="Weight"
defaultValue={1}
/>
</ArrayInput>
``` …

Fix SimpleFormIterator for non empty array inputs

---

packages/ra-ui-materialui/src/input/SelectArrayInput.tsx

Basically a copy of #4174 (same warning appearing for `SelectArrayInput`).

Fix warning in SelectArrayInput when alwaysOn is true

---

packages/ra-ui-materialui/src/field/UrlField.spec.js
packages/ra-ui-materialui/src/field/UrlField.tsx

UrlField renders a material-ui Link component instead of an anchor element

---

Makefile
examples/demo/src/i18n/en.ts
examples/demo/src/i18n/fr.ts
packages/ra-core/src/i18n/TranslationMessages.ts
packages/ra-core/src/i18n/index.ts
packages/ra-i18n-polyglot/src/index.ts
packages/ra-language-english/package.json
packages/ra-language-english/src/index.ts
packages/ra-language-english/tsconfig.json
packages/ra-language-french/package.json
packages/ra-language-french/src/index.ts
packages/ra-language-french/tsconfig.json

Self explanatory, summary of changes:
1. Added `ra-core/src/i18n/TranslationMessages.ts` that contains the type. I tried with `.d.ts` as the extension, though tsc ignores this on build. Exported from pacakge.
2. typed `ra-18n-polyglot` to accept this new type. 
3. converted `ra-language-english` and `ra-language-french` to typesript packages, added tsconfig.json, added build scripts and updated package.json to include relevant main, files, module and types.
4. Ensure entire monorepo build without errors
@fzaninotto please let me know if I have missed something.

🏷 convert ra-language-english and ra-language-french to typescript

---

docs/CreateEdit.md

https://github.com/marmelab/react-admin/issues/3245

Fix Edit Toolbar docs to explain how to use a CreateButton

---

packages/ra-core/src/dataProvider/useGetList.ts
packages/ra-core/src/reducer/admin/resource/data.spec.ts
packages/ra-core/src/reducer/admin/resource/data.ts

When using string identifiers and an inline delete undoable in a list, once the undo period ends, the getList following the delete threw the following error:
> An error occurred while selecting the store state: Cannot read property 'id' of undefined.
This is due to a combination of 2 bugs (one hiding the other) that this PR fixes.

[RFR] Fix useGetList after delete when using string identifiers

---

examples/demo/src/dashboard/Dashboard.tsx

Hi Guys
I was looking to contribute to converting more of the demo app to typescript and noticed there is a better way to enforce state type.
Please let me know how it looks.

Fix useState return type in demo example Dashboard

---

docs/Ecosystem.md

Added [react-admin-import-csv](https://github.com/benwinding/react-admin-import-csv) to Ecosystem docs. As suggested here: https://github.com/marmelab/react-admin/issues/3809#issuecomment-605686028

Added "react-admin-import-csv" to Ecosystem docs

---

packages/ra-core/src/form/FormWithRedirect.tsx

Fix destroyOnUnregister prop is ignored in SimpleForm and TabbedForm

---

packages/ra-core/src/dataProvider/index.ts
packages/ra-core/src/dataProvider/useRefreshWhenVisible.ts
packages/ra-ui-materialui/src/layout/LoadingIndicator.js

When the user comes back to the app after leaving it more than 5 minutes in the background, the app triggers a refresh.

Add a data refresh when the App comes back from background

---

docs/Admin.md

The existing way throws and error `Error: Expected ref to be a function, a string, an object returned by React.createRef(), or nul`. 
This fix works.

Change Docs: menu item to use an instance of icon

---

packages/ra-core/src/controller/useFilterState.ts

Closes #4507 
Updating filter prop on referenceInput wasn't updating the filters for fetching. The last query uses the first filters provided.
Listening on permanentFilter on setFilter callback solved the issue.

Fix useFilterState: useCallback listens on permanent filter changes

---

docs/Actions.md

Fix useQuery being incorrectly referenced in useMutation definition docs.

---

packages/ra-core/src/controller/useFilterState.ts

comparing two objects using lodash.isEqual

---

docs/Inputs.md

Fixes #4646
On Firefox, the following example crashes.

Improve NumberInput "parse" documentation for Firefox

---

.travis.yml
Makefile
cypress/package.json
cypress/start.js
packages/ra-core/src/controller/useFilterState.ts
packages/ra-core/src/controller/useListController.ts
yarn.lock

This PR have two goals:
- Upgrade Cypress version
- Allow local E2E testing with Firefox (BROWSER=firefox make test-e2e)

Upgrade Cypress version

---

docs/CreateEdit.md

[Docs]: Improve buttons sanitation explanation.

---

packages/ra-ui-materialui/src/input/AutocompleteArrayInput.spec.tsx
packages/ra-ui-materialui/src/input/AutocompleteArrayInput.tsx

Fixes #4454
Ok, this solution is not the best I can find.
@fzaninotto's idea is to let the user deal this situtation.
If the user write a tricky `parse` function, it's his job to make sure the input do not refresh too much by having a useMemo or useCallback above.
The issue is that I can't make it work since `parse` is a function that I cannot define with its value.
**Considered alternatives**
- Force the user who wrote the parse function to wrap the AutocompleteArrayInput into an appropriate memo or useCallback
The issue is that I didn't succeed so because we can't access to the input values outside of this component, so we can't use it as a dependency for useCallback, for example
I didn't tried with a FormDataConsumer, it would not be developer friendly IMHO 
- Use `hash-sum` to hash …

Fix unnecessary AutocompleteArrayInput filter reset

---

packages/ra-ui-materialui/src/field/BooleanField.spec.js
packages/ra-ui-materialui/src/field/BooleanField.tsx
packages/ra-ui-materialui/src/field/ChipField.spec.js
packages/ra-ui-materialui/src/field/DateField.spec.js
packages/ra-ui-materialui/src/field/EmailField.spec.js
packages/ra-ui-materialui/src/field/FileField.spec.js
packages/ra-ui-materialui/src/field/ImageField.spec.js
packages/ra-ui-materialui/src/field/NumberField.spec.js
packages/ra-ui-materialui/src/field/RichTextField.spec.js
packages/ra-ui-materialui/src/field/RichTextField.tsx
packages/ra-ui-materialui/src/field/TextField.spec.js
packages/ra-ui-materialui/src/field/TextField.tsx
packages/ra-ui-materialui/src/field/UrlField.spec.js

Fix EmptyText Inconsistencies

---

packages/ra-ui-materialui/src/list/SingleFieldList.js

Using
```
const useSingleFieldListStyles = makeStyles({
root: {
display: "block",
flexWrap: "unset",
marginTop: 0,
marginBottom: 0
},
link: {
display: "block"
}
});
const Demo = props => {
const singleFieldListClasses = useSingleFieldListStyles();
return (
<SingleFieldList classes={singleFieldListClasses}>
<TextField source="name"/>
</SingleFieldList>
);
};
```
Got an error in console:
`Material-UI: the key link provided to the classes prop is not implemented in undefined.`
Because styles in `SingleFieldList` doesn't have `link` class

Fix error when passing custom link style to SingleFieldList

---

packages/ra-core/src/reducer/admin/ui.ts
packages/ra-ui-materialui/src/layout/Sidebar.js

Currently, the sidebar is opened on desktop and closed on mobile. But this feature uses the material-ui [useMediaQuery](https://material-ui.com/components/use-media-query/) hook, which triggers two renders (the first one is always `false` to work on SSR). To fix it, react-admin forces the sidebar to be opened after the second render.
But as a consequence, it's impossible to define another behaviour by **changing the initial state of the application**.
The solution imagined is to only rely on the initial state of the application (and not force a reopening afterward). And to open the sidebar by default on desktop, we will use directly the `window.matchMedia` method.
**Opened on desktop**
**Closed on mobile**

Don't force the sidebar to be opened by default

---

packages/ra-data-graphql/src/introspection.js

As it was reported on [Issue-4670](https://github.com/marmelab/react-admin/issues/4670)
**ra-data-graphql** uses introspectionQuery from graphql-js. 
The export was finally deprecated  on graphql:15.0.0 [graphql/graphql-js@6b55019](https://github.com/graphql/graphql-js/commit/6b550192e0ce3b458abaec92e4c65d36eeafb7d0), and must be use **getIntrospectionQuery()** instead.
The Error shown **when grapqhql:15.0.0 is installed** in ra-data-graphq and other packages that use the library as ra-data-graphcool  was:
`WARNING in ./node_modules/ra-data-graphql/esm/introspection.js 94:202-220
"export 'introspectionQuery' was not found in 'graphql'
`
Due to ra-data-graphql use graphql:14.1.1, which exports both introspectionQuery and getIntrospectionQuery(), the fix proposed is to replaced depracated …

fix instrospection grapgql query

---

packages/ra-ui-materialui/src/layout/Loading.js

As mentioned in https://github.com/marmelab/react-admin/issues/4302
The default loading component was not vertically center for large screens (greater than `md`).
Fix: This was due to the breakpoints defined in the loading theme. I have updated that to `lg` from `md`.
Let me know if it requires any further updates.
Closes #4302

fix: default app loading is not not center vertically - 4302

---

packages/ra-data-graphql-simple/src/buildVariables.js
packages/ra-data-graphql-simple/src/buildVariables.test.js

Fix ra-data-graphql-simple Many Reference Target Filter

---

packages/ra-ui-materialui/src/input/FileInput.tsx

Moving FormHelperText above previews element

---

docs/Ecosystem.md
docs/Fields.md

Here is a copy-to-clipboard field.
https://github.com/OoDeLally/react-admin-clipboard-list-field
Being new to both React Admin and MaterialUI, I would be grateful if anyone can review my component and suggest improvements.

[Doc] Add a link to Clipboard List Field third-party package

---

packages/ra-ui-materialui/src/list/ListActions.js

Closes #4217
The `Export` button was not updating (enable/disable) when the total no. of items is changed.
`Fix:` the `total` key was missing in the `onlyUpdateForKeys` call.

fix: Export button is not getting updated when  is updated - 4217
